simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/ITKCode/a2itk.cxx File Reference
a2itk.cxx File Reference
#include "SimVascular.h"
#include "itkImage.h"
#include "itkExpNegativeImageFilter.h"
#include "itkFastMarchingImageFilter.h"
#include "itkShapeDetectionLevelSetImageFilter.h"
#include "itkRegionOfInterestImageFilter.h"
#include "itkResampleImageFilter.h"
#include "itkAffineTransform.h"
#include "itkLinearInterpolateImageFunction.h"
#include "itkMinMaxCurvatureFlowImageFilter.h"
#include "itkSigmoidImageFilter.h"
#include "itkThresholdImageFilter.h"
#include "itkThresholdSegmentationLevelSetImageFilter.h"
#include "itkVTKImageImport.h"
#include "itkVTKImageExport.h"
#include "vtkStructuredPoints.h"
#include "vtkImageExport.h"
#include "vtkImageImport.h"
Functions
template<typename ITK_Exporter , typename VTK_Importer >
void ConnectPipelines (ITK_Exporter exporter, VTK_Importer *importer)
template<typename VTK_Exporter , typename ITK_Importer >
void ConnectPipelines (VTK_Exporter *exporter, ITK_Importer importer)
Function Documentation
template<typename ITK_Exporter , typename VTK_Importer > void ConnectPipelines (ITK_Exporter exporter, VTK_Importer * importer)
This function will connect the given itk::VTKImageExport filter to the given vtkImageImport filter.
Definition at line 70 of file a2itk.cxx.
Referenced by a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput1(), and a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput2().
template<typename VTK_Exporter , typename ITK_Importer > void ConnectPipelines (VTK_Exporter * exporter, ITK_Importer importer)
This function will connect the given vtkImageExport filter to the given itk::VTKImageImport filter.
Definition at line 92 of file a2itk.cxx.