simvascular: cvMeshSystem Class Reference
cvMeshSystem Class Reference abstract
#include <cvMeshSystem.h>
Public Member Functions
cvMeshSystem ()
virtual ~cvMeshSystem ()
virtual int LogOn (char *const filename)=0
virtual int LogOff ()=0
Static Public Member Functions
static cvMeshSystem * GetCurrentKernel ()
static cvMeshObject::KernelType GetCurrentKernelType ()
static char * GetCurrentKernelName ()
static int SetCurrentKernel (cvMeshObject::KernelType kernel_type)
static int RegisterKernel (cvMeshObject::KernelType kernel_type, cvMeshSystem *pKernel)
static cvMeshObject * DefaultInstantiateMeshObject (Tcl_Interp *interp=NULL, char *const meshFileName=NULL, char *const solidFileName=NULL)
Protected Member Functions
virtual cvMeshObject * CreateMeshObject (Tcl_Interp *interp)=0
Static Protected Attributes
static cvMeshObject::KernelType gCurrentKernel = cvMeshObject::KERNEL_INVALID
static cvMeshSystem * gMeshSystems [cvMeshObject::KERNEL_MAX_TYPES] = { NULL }
Detailed Description
Definition at line 38 of file cvMeshSystem.h.
Constructor & Destructor Documentation
cvMeshSystem::cvMeshSystem ()
Definition at line 41 of file cvMeshSystem.cxx.
cvMeshSystem::~cvMeshSystem () virtual
Definition at line 45 of file cvMeshSystem.cxx.
Member Function Documentation
virtual cvMeshObject* cvMeshSystem::CreateMeshObject (Tcl_Interp * interp) protected pure virtual
Implemented in cvTetGenMeshSystem, and cvMeshSimMeshSystem.
Referenced by DefaultInstantiateMeshObject().
cvMeshObject * cvMeshSystem::DefaultInstantiateMeshObject (Tcl_Interp * interp = NULL, char *const meshFileName = NULL, char *const solidFileName = NULL) static
Definition at line 127 of file cvMeshSystem.cxx.
References CreateMeshObject(), gCurrentKernel, gMeshSystems, cvMeshObject::KERNEL_MESHSIM, cvMeshObject::KERNEL_TETGEN, NULL, cvMeshObject::SetMeshFileName(), and cvMeshObject::SetSolidFileName().
Referenced by cvMesh_NewObjectCmd().
cvMeshSystem * cvMeshSystem::GetCurrentKernel () static
Definition at line 49 of file cvMeshSystem.cxx.
References gCurrentKernel, gMeshSystems, cvMeshObject::KERNEL_MESHSIM, cvMeshObject::KERNEL_TETGEN, and NULL.
Referenced by cvMesh_LogoffCmd(), and cvMesh_LogonCmd().
char * cvMeshSystem::GetCurrentKernelName () static
Definition at line 59 of file cvMeshSystem.cxx.
References gCurrentKernel, and cvMeshObject::GetKernelName().
Referenced by cvMesh_GetMeshKernelCmd().
static cvMeshObject::KernelType cvMeshSystem::GetCurrentKernelType () inline static
Definition at line 45 of file cvMeshSystem.h.
References gCurrentKernel.
virtual int cvMeshSystem::LogOff () pure virtual
Implemented in cvTetGenMeshSystem, and cvMeshSimMeshSystem.
Referenced by cvMesh_LogoffCmd().
virtual int cvMeshSystem::LogOn (char *const filename) pure virtual
Implemented in cvTetGenMeshSystem, and cvMeshSimMeshSystem.
Referenced by cvMesh_LogonCmd().
int cvMeshSystem::RegisterKernel (cvMeshObject::KernelType kernel_type, cvMeshSystem * pKernel) static
Definition at line 94 of file cvMeshSystem.cxx.
References CV_ERROR, CV_OK, gCurrentKernel, gMeshSystems, cvMeshObject::KERNEL_MESHSIM, and cvMeshObject::KERNEL_TETGEN.
Referenced by Gdscmesh_Init(), and Tetgenmesh_Init().
int cvMeshSystem::SetCurrentKernel (cvMeshObject::KernelType kernel_type) static
Definition at line 64 of file cvMeshSystem.cxx.
References CV_ERROR, CV_OK, gCurrentKernel, gMeshSystems, cvMeshObject::KERNEL_INVALID, cvMeshObject::KERNEL_MESHSIM, cvMeshObject::KERNEL_TETGEN, and NULL.
Referenced by cvMesh_SetMeshKernelCmd(), and Gdscmesh_Init().
Member Data Documentation
cvMeshObject::KernelType cvMeshSystem::gCurrentKernel = cvMeshObject::KERNEL_INVALID static protected
Definition at line 64 of file cvMeshSystem.h.
Referenced by DefaultInstantiateMeshObject(), GetCurrentKernel(), GetCurrentKernelName(), GetCurrentKernelType(), RegisterKernel(), and SetCurrentKernel().
cvMeshSystem * cvMeshSystem::gMeshSystems = { NULL } static protected
Definition at line 65 of file cvMeshSystem.h.
Referenced by DefaultInstantiateMeshObject(), GetCurrentKernel(), RegisterKernel(), and SetCurrentKernel().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/MeshObject/cvMeshSystem.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/MeshObject/cvMeshSystem.cxx