simvascular: cvStateArray Class Reference
cvStateArray Class Reference
#include <cvStateArray.h>
Public Member Functions
cvStateArray (int size)
~cvStateArray ()
int GetNumElems ()
StateT & operator[] (int ix)
int GetSign (int ix)
void SetActive (int ix)
void SetSwept (int ix)
void SetCovered (int ix)
void SweptToCovered ()
int GetNumActive ()
int GetNumCovered ()
void ClearActive ()
void ClearSwept ()
void ClearCovered ()
int GetMemoryUsage ()
Private Attributes
StateT * arr_
int size_
Detailed Description
Definition at line 57 of file cvStateArray.h.
Constructor & Destructor Documentation
cvStateArray::cvStateArray (int size)
Definition at line 41 of file cvStateArray.cxx.
References arr_, and size_.
cvStateArray::~cvStateArray ()
Definition at line 57 of file cvStateArray.cxx.
References arr_.
Member Function Documentation
void cvStateArray::ClearActive ()
Definition at line 103 of file cvStateArray.cxx.
References arr_, size_, and STATE_NODE_ACTIVE.
Referenced by cvLevelSetSparseGrid::Sweep_MarkActiveNodes().
void cvStateArray::ClearCovered ()
Definition at line 131 of file cvStateArray.cxx.
References arr_, size_, and STATE_NODE_COVERED.
Referenced by cvLevelSetSparseGrid::Sweep_MarkActiveNodes().
void cvStateArray::ClearSwept ()
Definition at line 117 of file cvStateArray.cxx.
References arr_, size_, and STATE_NODE_SWEPT.
Referenced by cvLevelSetSparseGrid::Sweep().
int cvStateArray::GetMemoryUsage ()
Definition at line 145 of file cvStateArray.cxx.
References size_.
Referenced by cvLevelSetSparseGrid::GetMemoryUsage().
int cvStateArray::GetNumActive ()
Definition at line 67 of file cvStateArray.cxx.
References arr_, size_, and STATE_NODE_ACTIVE.
Referenced by cvLevelSetSparseGrid::ConstructHT_Sweep().
int cvStateArray::GetNumCovered ()
Definition at line 85 of file cvStateArray.cxx.
References arr_, size_, and STATE_NODE_COVERED.
int cvStateArray::GetNumElems () inline
Definition at line 63 of file cvStateArray.h.
References size_.
int cvStateArray::GetSign (int ix) inline
Definition at line 102 of file cvStateArray.h.
References arr_, size_, STATE_PHI_INSIDE, STATE_PHI_MASK, STATE_PHI_ON, and STATE_PHI_OUTSIDE.
Referenced by cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetSparseGrid::PollNeighborSigns(), cvLevelSetSparseGrid::Sweep(), cvLevelSetSparseGrid::Sweep_ComparePair(), and cvLevelSetSparseGrid::Sweep_MarkActiveNodes().
StateT & cvStateArray::operator[] (int ix) inline
Definition at line 91 of file cvStateArray.h.
References arr_, and size_.
void cvStateArray::SetActive (int ix) inline
Definition at line 123 of file cvStateArray.h.
References arr_, size_, and STATE_NODE_ACTIVE.
Referenced by cvLevelSetSparseGrid::Sweep_ComparePair(), and cvLevelSetSparseGrid::Sweep_MarkActiveNodes().
void cvStateArray::SetCovered (int ix) inline
Definition at line 151 of file cvStateArray.h.
References arr_, size_, and STATE_NODE_COVERED.
void cvStateArray::SetSwept (int ix) inline
Definition at line 137 of file cvStateArray.h.
References arr_, size_, and STATE_NODE_SWEPT.
Referenced by cvLevelSetSparseGrid::Sweep().
void cvStateArray::SweptToCovered () inline
Definition at line 165 of file cvStateArray.h.
References arr_, size_, STATE_NODE_COVERED, and STATE_NODE_SWEPT.
Referenced by cvLevelSetSparseGrid::Sweep().
Member Data Documentation
StateT* cvStateArray::arr_ private
Definition at line 81 of file cvStateArray.h.
Referenced by ClearActive(), ClearCovered(), ClearSwept(), cvStateArray(), GetNumActive(), GetNumCovered(), GetSign(), operator[](), SetActive(), SetCovered(), SetSwept(), SweptToCovered(), and ~cvStateArray().
int cvStateArray::size_ private
Definition at line 82 of file cvStateArray.h.
Referenced by ClearActive(), ClearCovered(), ClearSwept(), cvStateArray(), GetMemoryUsage(), GetNumActive(), GetNumCovered(), GetNumElems(), GetSign(), operator[](), SetActive(), SetCovered(), SetSwept(), and SweptToCovered().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvStateArray.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvStateArray.cxx