simvascular: cvLevelSetVelocityImage Class Reference
cvLevelSetVelocityImage Class Reference
#include <cvLevelSetVelocityImage.h>
Public Member Functions
cvLevelSetVelocityImage ()
virtual ~cvLevelSetVelocityImage ()
int SetImage (Image_T *i, int closed=0)
int SetImage (char *filebase, int fileNumRange[], int imgDims[], double pixDims[], int closed=0)
int SetImage (short *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (double *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (float *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int GetImage (Image_T **i)
int GetMagGradRange (double rng[])
int GetXYMagGradRange (double rng[])
int GetZMagGradRange (double rng[])
int GetIntensityRange (double rng[])
int ClearImage ()
virtual void PostSetImageAction ()
Public Member Functions inherited from cvLevelSetVelocity
cvLevelSetVelocity ()
virtual ~cvLevelSetVelocity ()
int LinkLevelSet (cvLevelSet *ls)
int UnlinkLevelSet ()
int GetLevelSet (cvLevelSet **ls)
int UpdateTolerance ()
void SetStopV (double d)
double GetStopV ()
virtual int Valid ()
virtual int StopCondition ()
virtual int Evaluate (double pos[], double *f0, double *f1, double v[], int *forceFlag, double toDot[])=0
virtual int GetMemoryUsage ()=0
Protected Member Functions
int GetImgSize ()
Protected Attributes
Image_T * image_
Protected Attributes inherited from cvLevelSetVelocity
cvLevelSet * ls_
double tol_
double stopV_
Additional Inherited Members
Public Attributes inherited from cvLevelSetVelocity
char tclName_ [CV_STRLEN]
Detailed Description
Definition at line 45 of file cvLevelSetVelocityImage.h.
Constructor & Destructor Documentation
cvLevelSetVelocityImage::cvLevelSetVelocityImage ()
Definition at line 42 of file cvLevelSetVelocityImage.cxx.
References image_, and NULL.
cvLevelSetVelocityImage::~cvLevelSetVelocityImage () virtual
Definition at line 52 of file cvLevelSetVelocityImage.cxx.
References ClearImage().
Member Function Documentation
int cvLevelSetVelocityImage::ClearImage ()
Definition at line 260 of file cvLevelSetVelocityImage.cxx.
References CV_OK, image_, Image_Delete(), and NULL.
Referenced by SetImage(), and ~cvLevelSetVelocityImage().
int cvLevelSetVelocityImage::GetImage (Image_T ** i)
Definition at line 185 of file cvLevelSetVelocityImage.cxx.
References CV_ERROR, CV_OK, image_, and NULL.
Referenced by LsetVImage_GetImageMtd(), and LsetVImage_GetImageObjMtd().
int cvLevelSetVelocityImage::GetImgSize () inline protected
Definition at line 70 of file cvLevelSetVelocityImage.h.
References image_, and Img_GetMemoryUsage().
int cvLevelSetVelocityImage::GetIntensityRange (double rng[])
Definition at line 245 of file cvLevelSetVelocityImage.cxx.
References CV_ERROR, CV_OK, image_, Img_GetIntensityRange(), and NULL.
Referenced by LsetVImage_GetIntensityRangeMtd().
int cvLevelSetVelocityImage::GetMagGradRange (double rng[])
Definition at line 200 of file cvLevelSetVelocityImage.cxx.
References CV_ERROR, CV_OK, image_, Img_GetMagGradRange(), and NULL.
Referenced by LsetVImage_GetMagGradRangeMtd().
int cvLevelSetVelocityImage::GetXYMagGradRange (double rng[])
Definition at line 215 of file cvLevelSetVelocityImage.cxx.
References CV_ERROR, CV_OK, image_, Img_GetXYMagGradRange(), and NULL.
Referenced by LsetVImage_GetXYMagGradRangeMtd().
int cvLevelSetVelocityImage::GetZMagGradRange (double rng[])
Definition at line 230 of file cvLevelSetVelocityImage.cxx.
References CV_ERROR, CV_OK, image_, Img_GetZMagGradRange(), and NULL.
Referenced by LsetVImage_GetZMagGradRangeMtd().
virtual void cvLevelSetVelocityImage::PostSetImageAction () inline virtual
Reimplemented in cvLevelSetVelocityKGI.
Definition at line 66 of file cvLevelSetVelocityImage.h.
Referenced by SetImage().
int cvLevelSetVelocityImage::SetImage (Image_T * i, int closed = 0)
Definition at line 62 of file cvLevelSetVelocityImage.cxx.
References ComputeImageGrad(), CV_ERROR, CV_OK, image_, NULL, PostSetImageAction(), and SetImageClosed().
Referenced by LsetVImage_SetImageMtd(), and LsetVImage_SetImageObjMtd().
int cvLevelSetVelocityImage::SetImage (char * filebase, int fileNumRange[], int imgDims[], double pixDims[], int closed = 0)
Definition at line 82 of file cvLevelSetVelocityImage.cxx.
References ClearImage(), ComputeImageGrad(), CV_ERROR, CV_OK, image_, NULL, PostSetImageAction(), ReadImage(), and SetImageClosed().
int cvLevelSetVelocityImage::SetImage (short * imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed = 0)
Definition at line 110 of file cvLevelSetVelocityImage.cxx.
References ClearImage(), ComputeImageGrad(), CreateImage(), CV_ERROR, CV_OK, image_, NULL, PostSetImageAction(), SetImageClosed(), and SetLowerLeft().
int cvLevelSetVelocityImage::SetImage (double * imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed = 0)
Definition at line 135 of file cvLevelSetVelocityImage.cxx.
References ClearImage(), ComputeImageGrad(), CreateImage(), CV_ERROR, CV_OK, image_, NULL, PostSetImageAction(), SetImageClosed(), and SetLowerLeft().
int cvLevelSetVelocityImage::SetImage (float * imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed = 0)
Definition at line 160 of file cvLevelSetVelocityImage.cxx.
References ClearImage(), ComputeImageGrad(), CreateImage(), CV_ERROR, CV_OK, image_, NULL, PostSetImageAction(), SetImageClosed(), and SetLowerLeft().
Member Data Documentation
Image_T* cvLevelSetVelocityImage::image_ protected
Definition at line 66 of file cvLevelSetVelocityImage.h.
Referenced by ClearImage(), cvLevelSetVelocityImage(), cvLevelSetVelocityThreshold::Evaluate(), cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), cvLevelSetVelocityExponentialDecay::Evaluate(), GetImage(), GetImgSize(), GetIntensityRange(), GetMagGradRange(), cvLevelSetVelocityKGI::GetMaxImageIGrad(), cvLevelSetVelocityThreshold::GetMemoryUsage(), cvLevelSetVelocityPotential::GetMemoryUsage(), cvLevelSetVelocityKGI::GetMemoryUsage(), cvLevelSetVelocityExponentialDecay::GetMemoryUsage(), GetXYMagGradRange(), GetZMagGradRange(), cvLevelSetVelocityKGI::PostSetImageAction(), SetImage(), cvLevelSetVelocityThreshold::Valid(), cvLevelSetVelocityPotential::Valid(), cvLevelSetVelocityKGI::Valid(), and cvLevelSetVelocityExponentialDecay::Valid().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityImage.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityImage.cxx