simvascular: cvMeshSimMeshObject Class Reference
cvMeshSimMeshObject Class Reference
#include <cvMeshSimMeshObject.h>
Classes
struct MSoptions
Public Member Functions
cvMeshSimMeshObject (Tcl_Interp *interp)
cvMeshSimMeshObject (const cvMeshSimMeshObject &sm)
~cvMeshSimMeshObject ()
int SetMeshFileName (const char *meshFileName)
int SetSolidFileName (const char *solidFileName)
int InitTraversal ()
int Update ()
int Print ()
cvMeshObject * Copy () const
int LoadModel (char *filename)
int GetBoundaryFaces (double angle)
int LoadMesh (char *filename)
int NewMesh ()
int SetSurfaceMeshFlag (int value)
int SetSurfaceOptimization (int value)
int SetSurfaceSmoothing (int value)
int SetVolumeMeshFlag (int value)
int SetVolumeOptimization (int value)
int SetVolumeSmoothing (int value)
int SetGlobalSize (int type, double gsize)
int SetLocalSize (int type, int id, double size)
int SetGlobalCurv (int type, double size)
int SetLocalCurv (int type, int id, double size)
int SetGlobalMinCurv (int type, double size)
int SetLocalMinCurv (int type, int id, double size)
int SetBoundaryLayer (int type, int id, int side, int nL, double *H)
int SetMeshOptions (char *flags, double value)
int SetCylinderRefinement (double size, double radius, double length, double *center, double *normal)
int SetSphereRefinement (double size, double radius, double *center)
int SetSizeFunctionBasedMesh (double size, char *filename)
int GenerateMesh ()
int WriteMesh (char *filename, int smsver)
int WriteStats (char *filename)
int WriteDataExplorer (char *filename)
int WriteMetisAdjacency (char *filename)
int GetElementConnectivity (int element)
int GetNodeCoords (int node)
cvPolyData * GetPolyData ()
cvUnstructuredGrid * GetUnstructuredGrid ()
int GetElementNodesOnModelFace (int face, char *filename)
int GetElementFacesOnModelFace (int face, int explicitFaceOut, char *filename)
cvPolyData * GetFacePolyData (int orgfaceid)
int GetModelFaceInfo (char rtnstr[99999])
int GetElementsInModelRegion (int region, char *filename)
int GetExteriorElementFacesOnRegion (int region, char *filename)
int GenerateQuadraticElements ()
int FindFaceNumber (pRegion region, int pseudofaceID, int *facenum)
int FindNodesOnElementFace (pFace face, int *nodes)
void initNodeTraversal ()
void initElementTraversal ()
void initRegionTraversal ()
int getNextNode ()
int getNextElement ()
int getNextRegion ()
int getNeighborMdlRegIds ()
int OutputExteriorElementFaces (pRegion region, int pseudoFaceID, char *filename)
int getIdentForFaceId (int orgfaceid, int *faceID)
int SetVtkPolyDataObject (vtkPolyData *newPolyData)
Public Member Functions inherited from cvMeshObject
cvMeshObject ()
virtual ~cvMeshObject ()
cvMeshObject::KernelType GetMeshKernel () const
SolidModel_KernelT GetSolidModelKernel () const
void SetSolidModelKernel (SolidModel_KernelT kernel)
int GetMeshLoaded ()
int GetElementType ()
int WriteAbaqusInputDeck (char *filename)
int WriteProphlexInputDeck (char *filename)
int WriteSpectrumSolverElements (char *filename)
int WriteSpectrumSolverNodes (char *filename)
int WriteSpectrumVisMesh (char *filename)
int WriteSpectrumVisData (char *filename)
int WriteMeshVrml (char *filename)
int WriteSurfaceMeshVrml (char *filename)
int WriteSurfaceMeshOogl (char *filename)
int WriteHypermeshAscii (char *filename)
int openOutputFile (char *filename)
int closeOutputFile ()
Public Member Functions inherited from cvRepositoryData
cvRepositoryData (RepositoryDataT type)
virtual ~cvRepositoryData ()
void Lock ()
void Release ()
int NumLocks ()
RepositoryDataT GetType ()
char * GetName ()
void SetName (char *in)
int GetNumLabels ()
void GetLabelKeys (int *numKeys, char **keys[])
int IsLabelPresent (char *key)
int GetLabel (char *key, char **value)
int SetLabel (char *key, char *value)
void ClearLabel (char *key)
virtual int GetMemoryUsage ()
Static Public Member Functions
static int Logon (const char *filename)
static int Logoff ()
Static Public Member Functions inherited from cvMeshObject
static char * GetKernelName (KernelType kernel)
static KernelType GetKernelType (const char *kernel_name)
Private Types
typedef struct
cvMeshSimMeshObject::MSoptions MSoptions
Private Member Functions
int MapIDtoPID (int id, pGEntity *pid)
Private Attributes
char meshFileName_ [MAXPATHLEN]
char solidFileName_ [MAXPATHLEN]
pMesh mesh
SGModel * model
pParasolidNativeModel paramodel_
int part_
Tcl_Interp * interp_
int loadedVolumeMesh_
pRegion pCurrentMeshRegion_
double * pts_
VIter ptrNodes_
int iterNodes_
EIter ptrEdges_
RIter ptrElements_
int iterElements_
GRIter ptrModelRegions_
int iterModelRegions_
MSoptions meshoptions_
pAManager manager_
pACase case_
Additional Inherited Members
Public Types inherited from cvMeshObject
enum KernelType {
KERNEL_INVALID, KERNEL_MESHSIM, KERNEL_TETGEN, KERNEL_GMSH,
KERNEL_MAX_TYPES
}
Public Attributes inherited from cvMeshObject
int nodeID_
double nodeX_
double nodeY_
double nodeZ_
Protected Attributes inherited from cvMeshObject
cvMeshObject::KernelType mesh_kernel_
SolidModel_KernelT solidmodeling_kernel_
int meshloaded_
int quadElem_
int numLinearNodes_
int numNodes_
int numElements_
int numModelRegions_
int * regionID_
int curElemID_
int connID_ [30]
int curElemNe_ [4][2]
int curMdlRegID_
FILE * fp_
Detailed Description
Definition at line 65 of file cvMeshSimMeshObject.h.
Member Typedef Documentation
typedef struct cvMeshSimMeshObject::MSoptions cvMeshSimMeshObject::MSoptions private
Constructor & Destructor Documentation
cvMeshSimMeshObject::cvMeshSimMeshObject (Tcl_Interp * interp)
Definition at line 61 of file cvMeshSimMeshObject.cxx.
References case_, interp_, loadedVolumeMesh_, manager_, mesh, meshFileName_, cvMeshObject::meshloaded_, model, NULL, ptrEdges_, ptrElements_, ptrModelRegions_, ptrNodes_, pts_, cvMeshObject::quadElem_, SM_KT_PARASOLID, solidFileName_, and cvMeshObject::solidmodeling_kernel_.
Referenced by Copy().
cvMeshSimMeshObject::cvMeshSimMeshObject (const cvMeshSimMeshObject & sm)
Definition at line 96 of file cvMeshSimMeshObject.cxx.
cvMeshSimMeshObject::~cvMeshSimMeshObject ()
Definition at line 109 of file cvMeshSimMeshObject.cxx.
References case_, manager_, mesh, model, NULL, ptrEdges_, ptrElements_, ptrModelRegions_, ptrNodes_, pts_, and cvMeshObject::regionID_.
Member Function Documentation
cvMeshObject * cvMeshSimMeshObject::Copy () const virtual
Implements cvMeshObject.
Definition at line 234 of file cvMeshSimMeshObject.cxx.
References cvMeshSimMeshObject().
int cvMeshSimMeshObject::FindFaceNumber (pRegion region, int pseudofaceID, int * facenum)
Definition at line 2230 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, and MY_MESHSIM_VERTEX_ORDERING.
Referenced by GetElementFacesOnModelFace(), and OutputExteriorElementFaces().
int cvMeshSimMeshObject::FindNodesOnElementFace (pFace face, int * nodes)
Definition at line 2324 of file cvMeshSimMeshObject.cxx.
References MY_MESHSIM_VERTEX_ORDERING, NULL, point, and cvMeshObject::quadElem_.
Referenced by GetElementNodesOnModelFace(), and GetFacePolyData().
int cvMeshSimMeshObject::GenerateMesh () virtual
Implements cvMeshObject.
Definition at line 1513 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, InitTraversal(), mesh, meshoptions_, NULL, cvMeshSimMeshObject::MSoptions::surface_optimization, cvMeshSimMeshObject::MSoptions::surface_smoothing, cvMeshSimMeshObject::MSoptions::volume_optimization, and cvMeshSimMeshObject::MSoptions::volume_smoothing.
int cvMeshSimMeshObject::GenerateQuadraticElements () virtual
Implements cvMeshObject.
Definition at line 359 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, mesh, cvMeshObject::numNodes_, and cvMeshObject::quadElem_.
int cvMeshSimMeshObject::GetBoundaryFaces (double angle) inline virtual
Implements cvMeshObject.
Definition at line 103 of file cvMeshSimMeshObject.h.
References CV_ERROR.
int cvMeshSimMeshObject::GetElementConnectivity (int element) virtual
Implements cvMeshObject.
Definition at line 409 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, interp_, mesh, MY_MESHSIM_VERTEX_ORDERING, NULL, cvMeshObject::numElements_, and cvMeshObject::quadElem_.
int cvMeshSimMeshObject::GetElementFacesOnModelFace (int face, int explicitFaceOut, char * filename) virtual
Implements cvMeshObject.
Definition at line 1758 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::closeOutputFile(), cvMeshObject::connID_, cvMeshObject::curElemID_, CV_ERROR, CV_OK, FindFaceNumber(), cvMeshObject::fp_, getIdentForFaceId(), getNextElement(), getNextRegion(), gzprintf, initElementTraversal(), initRegionTraversal(), interp_, model, NULL, cvMeshObject::openOutputFile(), pCurrentMeshRegion_, and cvMeshObject::quadElem_.
int cvMeshSimMeshObject::GetElementNodesOnModelFace (int face, char * filename) virtual
Implements cvMeshObject.
Definition at line 1854 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::closeOutputFile(), CV_ERROR, CV_OK, FindNodesOnElementFace(), cvMeshObject::fp_, getIdentForFaceId(), getNextElement(), getNextRegion(), gzprintf, initElementTraversal(), initRegionTraversal(), interp_, model, NULL, cvMeshObject::numNodes_, cvMeshObject::openOutputFile(), and pCurrentMeshRegion_.
int cvMeshSimMeshObject::GetElementsInModelRegion (int region, char * filename) virtual
Implements cvMeshObject.
Definition at line 1672 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::closeOutputFile(), cvMeshObject::connID_, cvMeshObject::curElemID_, cvMeshObject::curMdlRegID_, CV_ERROR, CV_OK, cvMeshObject::fp_, getNextElement(), getNextRegion(), gzprintf, initElementTraversal(), initRegionTraversal(), interp_, model, NULL, cvMeshObject::openOutputFile(), cvMeshObject::quadElem_, SM_KT_PARASOLID, and cvMeshObject::solidmodeling_kernel_.
int cvMeshSimMeshObject::GetExteriorElementFacesOnRegion (int region, char * filename) virtual
Implements cvMeshObject.
Definition at line 2152 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::closeOutputFile(), cvMeshObject::curElemNe_, cvMeshObject::curMdlRegID_, CV_ERROR, CV_OK, getNeighborMdlRegIds(), getNextElement(), getNextRegion(), initElementTraversal(), initRegionTraversal(), model, NULL, cvMeshObject::openOutputFile(), OutputExteriorElementFaces(), pCurrentMeshRegion_, SM_KT_PARASOLID, and cvMeshObject::solidmodeling_kernel_.
cvPolyData * cvMeshSimMeshObject::GetFacePolyData (int orgfaceid) virtual
Implements cvMeshObject.
Definition at line 1945 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, FindNodesOnElementFace(), getIdentForFaceId(), GetNodeCoords(), mesh, model, cvMeshObject::nodeID_, cvMeshObject::nodeX_, cvMeshObject::nodeY_, cvMeshObject::nodeZ_, and NULL.
int cvMeshSimMeshObject::getIdentForFaceId (int orgfaceid, int * faceID)
Definition at line 975 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, model, NULL, PsdUtils_CheckIdentForFaceId(), SM_KT_DISCRETE, SM_KT_PARASOLID, and cvMeshObject::solidmodeling_kernel_.
Referenced by GetElementFacesOnModelFace(), GetElementNodesOnModelFace(), and GetFacePolyData().
int cvMeshSimMeshObject::GetModelFaceInfo (char rtnstr[99999]) virtual
Implements cvMeshObject.
Definition at line 2094 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, model, PsdUtils_GetFaceAttribute(), SM_KT_DISCRETE, SM_KT_PARASOLID, and cvMeshObject::solidmodeling_kernel_.
int cvMeshSimMeshObject::getNeighborMdlRegIds () virtual
Implements cvMeshObject.
Definition at line 924 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::curElemNe_, MY_MESHSIM_FACE_ORDERING, NULL, cvMeshObject::numModelRegions_, and pCurrentMeshRegion_.
Referenced by GetExteriorElementFacesOnRegion().
int cvMeshSimMeshObject::getNextElement () virtual
Implements cvMeshObject.
Definition at line 862 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::connID_, cvMeshObject::curElemID_, cvMeshObject::curMdlRegID_, iterElements_, MY_MESHSIM_VERTEX_ORDERING, cvMeshObject::numElements_, pCurrentMeshRegion_, point, ptrElements_, and cvMeshObject::quadElem_.
Referenced by GetElementFacesOnModelFace(), GetElementNodesOnModelFace(), GetElementsInModelRegion(), GetExteriorElementFacesOnRegion(), GetUnstructuredGrid(), and InitTraversal().
int cvMeshSimMeshObject::getNextNode () virtual
Implements cvMeshObject.
Definition at line 800 of file cvMeshSimMeshObject.cxx.
References iterNodes_, cvMeshObject::nodeID_, cvMeshObject::nodeX_, cvMeshObject::nodeY_, cvMeshObject::nodeZ_, NULL, cvMeshObject::numLinearNodes_, cvMeshObject::numNodes_, point, ptrEdges_, ptrNodes_, and cvMeshObject::quadElem_.
int cvMeshSimMeshObject::getNextRegion () virtual
Implements cvMeshObject.
Definition at line 847 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::curMdlRegID_, iterModelRegions_, cvMeshObject::numModelRegions_, and cvMeshObject::regionID_.
Referenced by GetElementFacesOnModelFace(), GetElementNodesOnModelFace(), GetElementsInModelRegion(), GetExteriorElementFacesOnRegion(), GetUnstructuredGrid(), and InitTraversal().
int cvMeshSimMeshObject::GetNodeCoords (int node) virtual
Implements cvMeshObject.
Definition at line 490 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, mesh, cvMeshObject::nodeID_, cvMeshObject::nodeX_, cvMeshObject::nodeY_, cvMeshObject::nodeZ_, point, pts_, and cvMeshObject::quadElem_.
Referenced by GetFacePolyData().
cvPolyData * cvMeshSimMeshObject::GetPolyData () virtual
Implements cvMeshObject.
Definition at line 582 of file cvMeshSimMeshObject.cxx.
References GetUnstructuredGrid(), cvUnstructuredGrid::GetVtkUnstructuredGrid(), loadedVolumeMesh_, mesh, MY_MESHSIM_VERTEX_ORDERING, NULL, and point.
cvUnstructuredGrid * cvMeshSimMeshObject::GetUnstructuredGrid () virtual
Implements cvMeshObject.
Definition at line 696 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::connID_, cvMeshObject::curElemID_, cvMeshObject::curMdlRegID_, getNextElement(), getNextRegion(), initElementTraversal(), initRegionTraversal(), mesh, NULL, and point.
Referenced by GetPolyData().
void cvMeshSimMeshObject::initElementTraversal () virtual
Implements cvMeshObject.
Definition at line 972 of file cvMeshSimMeshObject.cxx.
References iterElements_, and ptrElements_.
Referenced by GetElementFacesOnModelFace(), GetElementNodesOnModelFace(), GetElementsInModelRegion(), GetExteriorElementFacesOnRegion(), GetUnstructuredGrid(), and InitTraversal().
void cvMeshSimMeshObject::initNodeTraversal () virtual
Implements cvMeshObject.
Definition at line 971 of file cvMeshSimMeshObject.cxx.
References iterNodes_, ptrEdges_, and ptrNodes_.
void cvMeshSimMeshObject::initRegionTraversal () virtual
Implements cvMeshObject.
Definition at line 973 of file cvMeshSimMeshObject.cxx.
References iterModelRegions_, and ptrModelRegions_.
Referenced by GetElementFacesOnModelFace(), GetElementNodesOnModelFace(), GetElementsInModelRegion(), GetExteriorElementFacesOnRegion(), GetUnstructuredGrid(), and InitTraversal().
int cvMeshSimMeshObject::InitTraversal ()
Definition at line 245 of file cvMeshSimMeshObject.cxx.
References CV_OK, getNextElement(), getNextRegion(), initElementTraversal(), initRegionTraversal(), loadedVolumeMesh_, mesh, cvMeshObject::meshloaded_, model, cvMeshObject::numElements_, cvMeshObject::numLinearNodes_, cvMeshObject::numModelRegions_, cvMeshObject::numNodes_, ptrEdges_, ptrElements_, ptrModelRegions_, ptrNodes_, pts_, and cvMeshObject::regionID_.
Referenced by GenerateMesh(), and LoadMesh().
int cvMeshSimMeshObject::LoadMesh (char * filename) virtual
Implements cvMeshObject.
Definition at line 1247 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, InitTraversal(), mesh, meshFileName_, model, NewMesh(), and NULL.
Referenced by Update().
int cvMeshSimMeshObject::LoadModel (char * filename) virtual
Implements cvMeshObject.
Definition at line 1093 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, manager_, mesh, model, NULL, paramodel_, part_, PsdUtils_ReadNative(), SM_KT_DISCRETE, SM_KT_PARASOLID, solidFileName_, and cvMeshObject::solidmodeling_kernel_.
Referenced by Update().
int cvMeshSimMeshObject::Logoff () static
Definition at line 167 of file cvMeshSimMeshObject.cxx.
References CV_OK.
int cvMeshSimMeshObject::Logon (const char * filename) static
Definition at line 161 of file cvMeshSimMeshObject.cxx.
References CV_OK.
int cvMeshSimMeshObject::MapIDtoPID (int id, pGEntity * pid) private
Definition at line 1409 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, model, NULL, part_, PsdUtils_GetIdent(), SM_KT_DISCRETE, SM_KT_PARASOLID, and cvMeshObject::solidmodeling_kernel_.
Referenced by SetBoundaryLayer(), SetLocalCurv(), SetLocalMinCurv(), and SetLocalSize().
int cvMeshSimMeshObject::NewMesh () virtual
Implements cvMeshObject.
Definition at line 1290 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, loadedVolumeMesh_, manager_, mesh, cvMeshObject::meshloaded_, model, and NULL.
Referenced by LoadMesh().
int cvMeshSimMeshObject::OutputExteriorElementFaces (pRegion region, int pseudoFaceID, char * filename)
Definition at line 2213 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::closeOutputFile(), cvMeshObject::curElemID_, CV_ERROR, CV_OK, FindFaceNumber(), cvMeshObject::fp_, gzprintf, interp_, NULL, and pCurrentMeshRegion_.
Referenced by GetExteriorElementFacesOnRegion().
int cvMeshSimMeshObject::Print () virtual
Implements cvMeshObject.
Definition at line 177 of file cvMeshSimMeshObject.cxx.
References CV_OK, interp_, mesh, model, cvMeshObject::numModelRegions_, cvMeshObject::quadElem_, and cvMeshObject::regionID_.
int cvMeshSimMeshObject::SetBoundaryLayer (int type, int id, int side, int nL, double * H) virtual
Implements cvMeshObject.
Definition at line 1653 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, and MapIDtoPID().
int cvMeshSimMeshObject::SetCylinderRefinement (double size, double radius, double length, double * center, double * normal) virtual
Implements cvMeshObject.
Definition at line 1629 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, mesh, and NULL.
int cvMeshSimMeshObject::SetGlobalCurv (int type, double size) virtual
Implements cvMeshObject.
Definition at line 1475 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, cvMeshSimMeshObject::MSoptions::gcurv, cvMeshSimMeshObject::MSoptions::gcurv_type, mesh, meshoptions_, model, and NULL.
int cvMeshSimMeshObject::SetGlobalMinCurv (int type, double size) virtual
Implements cvMeshObject.
Definition at line 1501 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, cvMeshSimMeshObject::MSoptions::gmincurv, cvMeshSimMeshObject::MSoptions::gmincurv_type, mesh, meshoptions_, model, and NULL.
int cvMeshSimMeshObject::SetGlobalSize (int type, double gsize) virtual
Implements cvMeshObject.
Definition at line 1394 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, cvMeshSimMeshObject::MSoptions::gsize, cvMeshSimMeshObject::MSoptions::gsize_type, mesh, meshoptions_, model, and NULL.
int cvMeshSimMeshObject::SetLocalCurv (int type, int id, double size) virtual
Implements cvMeshObject.
Definition at line 1460 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, MapIDtoPID(), mesh, and NULL.
int cvMeshSimMeshObject::SetLocalMinCurv (int type, int id, double size) virtual
Implements cvMeshObject.
Definition at line 1486 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, MapIDtoPID(), mesh, and NULL.
int cvMeshSimMeshObject::SetLocalSize (int type, int id, double size) virtual
Implements cvMeshObject.
Definition at line 1443 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, MapIDtoPID(), mesh, and NULL.
int cvMeshSimMeshObject::SetMeshFileName (const char * meshFileName) virtual
Implements cvMeshObject.
Definition at line 141 of file cvMeshSimMeshObject.cxx.
References CV_OK, meshFileName_, and NULL.
int cvMeshSimMeshObject::SetMeshOptions (char * flags, double value) inline virtual
Implements cvMeshObject.
Definition at line 123 of file cvMeshSimMeshObject.h.
References CV_ERROR.
int cvMeshSimMeshObject::SetSizeFunctionBasedMesh (double size, char * filename) inline virtual
Implements cvMeshObject.
Definition at line 128 of file cvMeshSimMeshObject.h.
References CV_ERROR.
int cvMeshSimMeshObject::SetSolidFileName (const char * solidFileName) virtual
Implements cvMeshObject.
Definition at line 151 of file cvMeshSimMeshObject.cxx.
References CV_OK, NULL, and solidFileName_.
int cvMeshSimMeshObject::SetSphereRefinement (double size, double radius, double * center) virtual
Implements cvMeshObject.
Definition at line 1641 of file cvMeshSimMeshObject.cxx.
References case_, CV_ERROR, CV_OK, mesh, and NULL.
int cvMeshSimMeshObject::SetSurfaceMeshFlag (int value) virtual
Implements cvMeshObject.
Definition at line 1314 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, mesh, meshoptions_, NULL, and cvMeshSimMeshObject::MSoptions::surface.
int cvMeshSimMeshObject::SetSurfaceOptimization (int value) virtual
Implements cvMeshObject.
Definition at line 1327 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, mesh, meshoptions_, NULL, and cvMeshSimMeshObject::MSoptions::surface_optimization.
int cvMeshSimMeshObject::SetSurfaceSmoothing (int value) virtual
Implements cvMeshObject.
Definition at line 1340 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, mesh, meshoptions_, NULL, and cvMeshSimMeshObject::MSoptions::surface_smoothing.
int cvMeshSimMeshObject::SetVolumeMeshFlag (int value) virtual
Implements cvMeshObject.
Definition at line 1354 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, mesh, meshoptions_, NULL, and cvMeshSimMeshObject::MSoptions::volume.
int cvMeshSimMeshObject::SetVolumeOptimization (int value) virtual
Implements cvMeshObject.
Definition at line 1367 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, mesh, meshoptions_, NULL, and cvMeshSimMeshObject::MSoptions::surface_optimization.
int cvMeshSimMeshObject::SetVolumeSmoothing (int value) virtual
Implements cvMeshObject.
Definition at line 1380 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, mesh, meshoptions_, NULL, and cvMeshSimMeshObject::MSoptions::volume_smoothing.
int cvMeshSimMeshObject::SetVtkPolyDataObject (vtkPolyData * newPolyData) inline virtual
Implements cvMeshObject.
Definition at line 172 of file cvMeshSimMeshObject.h.
References CV_ERROR.
int cvMeshSimMeshObject::Update () virtual
Implements cvMeshObject.
Definition at line 334 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, LoadMesh(), LoadModel(), meshFileName_, cvMeshObject::meshloaded_, model, NULL, and solidFileName_.
int cvMeshSimMeshObject::WriteDataExplorer (char * filename) inline virtual
Implements cvMeshObject.
Definition at line 137 of file cvMeshSimMeshObject.h.
References CV_ERROR.
int cvMeshSimMeshObject::WriteMesh (char * filename, int smsver) virtual
Implements cvMeshObject.
Definition at line 1585 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, mesh, meshFileName_, and NULL.
int cvMeshSimMeshObject::WriteMetisAdjacency (char * filename) virtual
Implements cvMeshObject.
Definition at line 1017 of file cvMeshSimMeshObject.cxx.
References cvMeshObject::closeOutputFile(), CV_ERROR, CV_OK, faces(), cvMeshObject::fp_, gzprintf, mesh, MY_MESHSIM_FACE_ORDERING, NULL, numel, and cvMeshObject::openOutputFile().
int cvMeshSimMeshObject::WriteStats (char * filename) virtual
Implements cvMeshObject.
Definition at line 1617 of file cvMeshSimMeshObject.cxx.
References CV_ERROR, CV_OK, M_writeSTS(), mesh, and NULL.
Member Data Documentation
pACase cvMeshSimMeshObject::case_ private
Definition at line 214 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), GenerateMesh(), LoadModel(), NewMesh(), SetBoundaryLayer(), SetCylinderRefinement(), SetGlobalCurv(), SetGlobalMinCurv(), SetGlobalSize(), SetLocalCurv(), SetLocalMinCurv(), SetLocalSize(), SetSphereRefinement(), and ~cvMeshSimMeshObject().
Tcl_Interp* cvMeshSimMeshObject::interp_ private
Definition at line 190 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), GetElementConnectivity(), GetElementFacesOnModelFace(), GetElementNodesOnModelFace(), GetElementsInModelRegion(), OutputExteriorElementFaces(), and Print().
int cvMeshSimMeshObject::iterElements_ private
Definition at line 201 of file cvMeshSimMeshObject.h.
Referenced by getNextElement(), and initElementTraversal().
int cvMeshSimMeshObject::iterModelRegions_ private
Definition at line 204 of file cvMeshSimMeshObject.h.
Referenced by getNextRegion(), and initRegionTraversal().
int cvMeshSimMeshObject::iterNodes_ private
Definition at line 197 of file cvMeshSimMeshObject.h.
Referenced by getNextNode(), and initNodeTraversal().
int cvMeshSimMeshObject::loadedVolumeMesh_ private
Definition at line 191 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), GetPolyData(), InitTraversal(), and NewMesh().
pAManager cvMeshSimMeshObject::manager_ private
Definition at line 213 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), LoadModel(), NewMesh(), and ~cvMeshSimMeshObject().
pMesh cvMeshSimMeshObject::mesh private
Definition at line 180 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), GenerateMesh(), GenerateQuadraticElements(), GetElementConnectivity(), GetFacePolyData(), GetNodeCoords(), GetPolyData(), GetUnstructuredGrid(), InitTraversal(), LoadMesh(), LoadModel(), NewMesh(), Print(), SetCylinderRefinement(), SetGlobalCurv(), SetGlobalMinCurv(), SetGlobalSize(), SetLocalCurv(), SetLocalMinCurv(), SetLocalSize(), SetSphereRefinement(), SetSurfaceMeshFlag(), SetSurfaceOptimization(), SetSurfaceSmoothing(), SetVolumeMeshFlag(), SetVolumeOptimization(), SetVolumeSmoothing(), WriteMesh(), WriteMetisAdjacency(), WriteStats(), and ~cvMeshSimMeshObject().
char cvMeshSimMeshObject::meshFileName_[MAXPATHLEN] private
Definition at line 178 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), LoadMesh(), SetMeshFileName(), Update(), and WriteMesh().
MSoptions cvMeshSimMeshObject::meshoptions_ private
Definition at line 206 of file cvMeshSimMeshObject.h.
Referenced by GenerateMesh(), SetGlobalCurv(), SetGlobalMinCurv(), SetGlobalSize(), SetSurfaceMeshFlag(), SetSurfaceOptimization(), SetSurfaceSmoothing(), SetVolumeMeshFlag(), SetVolumeOptimization(), and SetVolumeSmoothing().
SGModel* cvMeshSimMeshObject::model private
Definition at line 181 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), GetElementFacesOnModelFace(), GetElementNodesOnModelFace(), GetElementsInModelRegion(), GetExteriorElementFacesOnRegion(), GetFacePolyData(), getIdentForFaceId(), GetModelFaceInfo(), InitTraversal(), LoadMesh(), LoadModel(), MapIDtoPID(), NewMesh(), Print(), SetGlobalCurv(), SetGlobalMinCurv(), SetGlobalSize(), Update(), and ~cvMeshSimMeshObject().
pParasolidNativeModel cvMeshSimMeshObject::paramodel_ private
Definition at line 183 of file cvMeshSimMeshObject.h.
Referenced by LoadModel().
int cvMeshSimMeshObject::part_ private
Definition at line 188 of file cvMeshSimMeshObject.h.
Referenced by LoadModel(), and MapIDtoPID().
pRegion cvMeshSimMeshObject::pCurrentMeshRegion_ private
Definition at line 192 of file cvMeshSimMeshObject.h.
Referenced by GetElementFacesOnModelFace(), GetElementNodesOnModelFace(), GetExteriorElementFacesOnRegion(), getNeighborMdlRegIds(), getNextElement(), and OutputExteriorElementFaces().
EIter cvMeshSimMeshObject::ptrEdges_ private
Definition at line 198 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), getNextNode(), initNodeTraversal(), InitTraversal(), and ~cvMeshSimMeshObject().
RIter cvMeshSimMeshObject::ptrElements_ private
Definition at line 200 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), getNextElement(), initElementTraversal(), InitTraversal(), and ~cvMeshSimMeshObject().
GRIter cvMeshSimMeshObject::ptrModelRegions_ private
Definition at line 203 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), initRegionTraversal(), InitTraversal(), and ~cvMeshSimMeshObject().
VIter cvMeshSimMeshObject::ptrNodes_ private
Definition at line 196 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), getNextNode(), initNodeTraversal(), InitTraversal(), and ~cvMeshSimMeshObject().
double* cvMeshSimMeshObject::pts_ private
Definition at line 194 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), GetNodeCoords(), InitTraversal(), and ~cvMeshSimMeshObject().
char cvMeshSimMeshObject::solidFileName_[MAXPATHLEN] private
Definition at line 179 of file cvMeshSimMeshObject.h.
Referenced by cvMeshSimMeshObject(), LoadModel(), SetSolidFileName(), and Update().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimMeshObject/cvMeshSimMeshObject.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimMeshObject/cvMeshSimMeshObject.cxx