simvascular: cvITKLevelSetBase< TInputImage, TInternalPixelType > Class Template Reference
cvITKLevelSetBase< TInputImage, TInternalPixelType > Class Template Reference
#include <cvITKLevelSetBase.h>
Public Types
enum { ImageDimension = TInputImage::ImageDimension }
typedef cvITKLevelSetBase Self
typedef TInputImage ITKExternalImageType
typedef itk::Image
< TInternalPixelType,
ITKExternalImageType::ImageDimension > ITKInternalImageType
typedef itk::VTKImageImport
< ITKExternalImageType > itkExternalImportType
typedef itk::VTKImageExport
< ITKExternalImageType > itkExternalExportType
typedef itk::VTKImageImport
< ITKInternalImageType > itkInternalImportType
typedef itk::VTKImageExport
< ITKInternalImageType > itkInternalExportType
Public Member Functions
virtual const char * GetNameOfClass () const
void DeallocateFeatureObjs ()
int SetFeatureImage (cvStrPts *s)
int GetFeatureImage (cvStrPts **s)
cvStrPts * GetVelocityImage ()
void DeallocateSeedObjs ()
int ComputePhaseOneLevelSet (float kc, float expFactorRising, float expFactorFalling)
int ComputePhaseTwoLevelSet (float kupp, float klow)
int ComputeGACLevelSet (float exponent, float kappa=5, float iso=.5)
int ComputeLaplacianLevelSet (float exponent, float kappa=5, float iso=.5)
int GenerateFeatureImage ()
int GenerateSeedImage ()
int CopyFrontToSeed ()
void DeallocateFrontObjs ()
int GetFront (cvPolyData **front)
cvPolyData * GetFront ()
cvStrPts * GetFrontImage ()
virtual void SetMaxIterations (int value)
virtual int GetMaxIterations ()
virtual void SetMaxRMSError (double value)
virtual double GetMaxRMSError ()
virtual void SetAdvectionScaling (double value)
virtual double GetAdvectionScaling ()
virtual void SetLaplacianScaling (double value)
virtual double GetLaplacianScaling ()
virtual void SetPropagationScaling (double value)
virtual double GetPropagationScaling ()
virtual void SetCurvatureScaling (double value)
virtual double GetCurvatureScaling ()
virtual void SetSigmaFeature (double value)
virtual double GetSigmaFeature ()
virtual void SetSigmaAdvection (double value)
virtual double GetSigmaAdvection ()
virtual int SetSeed (cvPolyData *value)
virtual int GetSeed (cvPolyData **value)
virtual void SetDebug (bool value)
virtual bool GetDebug ()
virtual void SetUseNormalVectorCurvature (bool value)
virtual bool GetUseNormalVectorCurvature ()
virtual void SetUseMeanCurvature (bool value)
virtual bool GetUseMeanCurvature ()
virtual void SetUseMinimalCurvature (bool value)
virtual bool GetUseMinimalCurvature ()
virtual void SetBinarySeed (bool value)
virtual bool GetBinarySeed ()
int SetInputImage (cvStrPts *s)
virtual int GetInputImage (cvStrPts **value)
void SetInternalImgInfo (vtkStructuredPoints *vtksp)
void ViewITKFront ()
template<typename TLevelSetFilterType >
void ShowDebug (typename TLevelSetFilterType::Pointer levelSetFilter)
void WriteFrontImages ()
cvITKLevelSetBase ()
virtual ~cvITKLevelSetBase ()
Public Attributes
char tclName_ [CV_STRLEN]
Protected Member Functions
void GenerateData ()
cvITKLevelSetBase (const cvITKLevelSetBase &)
void operator= (const cvITKLevelSetBase &)
Private Attributes
ImgInfo InternalImgInfo
ImgInfo ExternalImgInfo
cvStrPts * m_cvInputImage
cvPolyData * m_cvSeed
ITKInternalImageType::Pointer m_itkFeatureImage
ITKInternalImageType::Pointer m_itkSeedImage
vtkSmartPointer< vtkPolyData > m_vtkFrontPolyData
vtkSmartPointer
< vtkStructuredPoints > m_vtkFrontImage
vtkSmartPointer
< vtkStructuredPoints > m_vtkFeatureImage
ITKInternalImageType::Pointer m_itkFrontImage
cvStrPts * m_cvSeedImage
double m_SigmaFeature
double m_SigmaAdvection
double m_MaxRMSError
int m_MaxIterations
double m_PropagationScaling
double m_CurvatureScaling
double m_AdvectionScaling
double m_LaplacianScaling
bool m_UseNormalVectorCurvature
bool m_UseMeanCurvature
bool m_UseMinimalCurvature
bool m_BinarySeed
bool m_Debug
Detailed Description
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float>
class cvITKLevelSetBase< TInputImage, TInternalPixelType >
Definition at line 55 of file cvITKLevelSetBase.h.
Member Typedef Documentation
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> typedef itk::VTKImageExport<ITKExternalImageType> cvITKLevelSetBase< TInputImage, TInternalPixelType >::itkExternalExportType
Definition at line 73 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> typedef TInputImage cvITKLevelSetBase< TInputImage, TInternalPixelType >::ITKExternalImageType
Definition at line 63 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> typedef itk::VTKImageImport<ITKExternalImageType> cvITKLevelSetBase< TInputImage, TInternalPixelType >::itkExternalImportType
Definition at line 72 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> typedef itk::VTKImageExport<ITKInternalImageType> cvITKLevelSetBase< TInputImage, TInternalPixelType >::itkInternalExportType
Definition at line 76 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> typedef itk::Image<TInternalPixelType, ITKExternalImageType::ImageDimension> cvITKLevelSetBase< TInputImage, TInternalPixelType >::ITKInternalImageType
Definition at line 65 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> typedef itk::VTKImageImport<ITKInternalImageType> cvITKLevelSetBase< TInputImage, TInternalPixelType >::itkInternalImportType
Definition at line 75 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> typedef cvITKLevelSetBase cvITKLevelSetBase< TInputImage, TInternalPixelType >::Self
Typedefs
Definition at line 62 of file cvITKLevelSetBase.h.
Member Enumeration Documentation
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> anonymous enum
Enumerator
ImageDimension
Definition at line 66 of file cvITKLevelSetBase.h.
Constructor & Destructor Documentation
template<typename TInputImage , typename TInternalPixelType > cvITKLevelSetBase< TInputImage, TInternalPixelType >::cvITKLevelSetBase ()
Definition at line 63 of file cvITKLevelSetBase.cxx.
References NULL.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual cvITKLevelSetBase< TInputImage, TInternalPixelType >::~cvITKLevelSetBase () inline virtual
Definition at line 190 of file cvITKLevelSetBase.h.
References cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_cvInputImage, cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_cvSeedImage, and NULL.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> cvITKLevelSetBase< TInputImage, TInternalPixelType >::cvITKLevelSetBase (const cvITKLevelSetBase< TInputImage, TInternalPixelType > &) protected
Member Function Documentation
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputeGACLevelSet (float exponent, float kappa = 5, float iso = .5)
Definition at line 263 of file cvITKLevelSetBase.cxx.
References cvITKLSUtil::CopyITKtoVTK(), cvITKTemplateNewMacro, cvITKLSUtil::itkDeepCopy(), and cvITKLSUtil::WriteImage2().
Referenced by itkls2d_GACLevelSetMtd(), and itkls3d_GACLevelSetMtd().
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputeLaplacianLevelSet (float exponent, float kappa = 5, float iso = .5)
Definition at line 404 of file cvITKLevelSetBase.cxx.
References cvITKLSUtil::CopyITKtoVTK(), cvITKTemplateNewMacro, cvITKLSUtil::itkDeepCopy(), and cvITKLSUtil::WriteImage2().
Referenced by itkls3d_LaplacianLevelSetMtd().
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputePhaseOneLevelSet (float kc, float expFactorRising, float expFactorFalling)
Definition at line 545 of file cvITKLevelSetBase.cxx.
References cvITKTemplateNewMacro, and cvITKLSUtil::WriteImage2().
Referenced by itkls2d_PhaseOneLevelSetMtd(), and itkls3d_PhaseOneLevelSetMtd().
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputePhaseTwoLevelSet (float kupp, float klow)
Definition at line 655 of file cvITKLevelSetBase.cxx.
References cvITKTemplateNewMacro, and cvITKLSUtil::itk2vtkRecast().
Referenced by itkls2d_PhaseTwoLevelSetMtd(), and itkls3d_PhaseTwoLevelSetMtd().
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::CopyFrontToSeed ()
Definition at line 861 of file cvITKLevelSetBase.cxx.
References cvITKLSUtil::vtk2itkBinaryImageToSeedImage(), and cvITKLSUtil::vtkWriteImage2().
Referenced by itkls3d_CopyFrontToSeedMtd().
template<typename TInputImage , typename TInternalPixelType > void cvITKLevelSetBase< TInputImage, TInternalPixelType >::DeallocateFeatureObjs ()
Definition at line 102 of file cvITKLevelSetBase.cxx.
References NULL.
template<typename TInputImage , typename TInternalPixelType > void cvITKLevelSetBase< TInputImage, TInternalPixelType >::DeallocateFrontObjs ()
Definition at line 209 of file cvITKLevelSetBase.cxx.
template<typename TInputImage , typename TInternalPixelType > void cvITKLevelSetBase< TInputImage, TInternalPixelType >::DeallocateSeedObjs ()
Definition at line 248 of file cvITKLevelSetBase.cxx.
References NULL.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> void cvITKLevelSetBase< TInputImage, TInternalPixelType >::GenerateData () protected
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::GenerateFeatureImage ()
Definition at line 742 of file cvITKLevelSetBase.cxx.
References cvITKLSUtil::WriteImage2().
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::GenerateSeedImage ()
Definition at line 762 of file cvITKLevelSetBase.cxx.
References cvITKLSUtil::vtk2itkBinaryImageToSeedImage(), cvITKLSUtil::vtkPolyDataTo2DImage(), cvITKLSUtil::vtkPolyDataToVolume(), and cvITKLSUtil::vtkWriteImage2().
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual double cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetAdvectionScaling () inline virtual
Definition at line 119 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetBinarySeed () inline virtual
Definition at line 152 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual double cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetCurvatureScaling () inline virtual
Definition at line 128 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetDebug () inline virtual
Definition at line 140 of file cvITKLevelSetBase.h.
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetFeatureImage (cvStrPts ** s)
Definition at line 164 of file cvITKLevelSetBase.cxx.
References NULL.
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetFront (cvPolyData ** front)
Definition at line 217 of file cvITKLevelSetBase.cxx.
template<typename TInputImage , typename TInternalPixelType > cvPolyData * cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetFront ()
Definition at line 230 of file cvITKLevelSetBase.cxx.
References NULL.
template<typename TInputImage , typename TInternalPixelType > cvStrPts * cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetFrontImage ()
Definition at line 191 of file cvITKLevelSetBase.cxx.
References NULL.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual int cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetInputImage (cvStrPts ** value) inline virtual
Definition at line 156 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual double cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetLaplacianScaling () inline virtual
Definition at line 122 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual int cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetMaxIterations () inline virtual
Definition at line 113 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual double cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetMaxRMSError () inline virtual
Definition at line 116 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual const char* cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetNameOfClass () const inline virtual
Definition at line 78 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual double cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetPropagationScaling () inline virtual
Definition at line 125 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual int cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetSeed (cvPolyData ** value) inline virtual
Definition at line 137 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual double cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetSigmaAdvection () inline virtual
Definition at line 134 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual double cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetSigmaFeature () inline virtual
Definition at line 131 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetUseMeanCurvature () inline virtual
Definition at line 146 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetUseMinimalCurvature () inline virtual
Definition at line 149 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetUseNormalVectorCurvature () inline virtual
Definition at line 143 of file cvITKLevelSetBase.h.
template<typename TInputImage , typename TInternalPixelType > cvStrPts * cvITKLevelSetBase< TInputImage, TInternalPixelType >::GetVelocityImage ()
Definition at line 177 of file cvITKLevelSetBase.cxx.
References NULL.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> void cvITKLevelSetBase< TInputImage, TInternalPixelType >::operator= (const cvITKLevelSetBase< TInputImage, TInternalPixelType > &) protected
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetAdvectionScaling (double value) inline virtual
Definition at line 118 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetBinarySeed (bool value) inline virtual
Definition at line 151 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetCurvatureScaling (double value) inline virtual
Definition at line 127 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetDebug (bool value) inline virtual
Definition at line 139 of file cvITKLevelSetBase.h.
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetFeatureImage (cvStrPts * s)
Definition at line 140 of file cvITKLevelSetBase.cxx.
References cvStrPts::GetVtkStructuredPoints(), ImgInfo::SetExtent(), and ImgInfo::SetMaxValue().
template<typename TInputImage , typename TInternalPixelType > int cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetInputImage (cvStrPts * s)
Definition at line 113 of file cvITKLevelSetBase.cxx.
References cvRepositoryData::GetName(), cvStrPts::GetVtkStructuredPoints(), ImgInfo::SetExtent(), ImgInfo::SetMaxValue(), and cvRepositoryData::SetName().
Referenced by itkls2d_SetInputsMtd(), and itkls3d_SetInputsMtd().
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetInternalImgInfo (vtkStructuredPoints * vtksp) inline
Definition at line 159 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetLaplacianScaling (double value) inline virtual
Definition at line 121 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetMaxIterations (int value) inline virtual
Definition at line 112 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetMaxRMSError (double value) inline virtual
Definition at line 115 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetPropagationScaling (double value) inline virtual
Definition at line 124 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual int cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetSeed (cvPolyData * value) inline virtual
Definition at line 136 of file cvITKLevelSetBase.h.
Referenced by itkls2d_SetInputsMtd(), and itkls3d_SetInputsMtd().
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetSigmaAdvection (double value) inline virtual
Definition at line 133 of file cvITKLevelSetBase.h.
Referenced by itkls2d_PhaseOneLevelSetMtd(), itkls2d_PhaseTwoLevelSetMtd(), itkls3d_PhaseOneLevelSetMtd(), and itkls3d_PhaseTwoLevelSetMtd().
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetSigmaFeature (double value) inline virtual
Definition at line 130 of file cvITKLevelSetBase.h.
Referenced by itkls2d_PhaseOneLevelSetMtd(), itkls2d_PhaseTwoLevelSetMtd(), itkls3d_GACLevelSetMtd(), itkls3d_LaplacianLevelSetMtd(), itkls3d_PhaseOneLevelSetMtd(), and itkls3d_PhaseTwoLevelSetMtd().
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetUseMeanCurvature (bool value) inline virtual
Definition at line 145 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetUseMinimalCurvature (bool value) inline virtual
Definition at line 148 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> virtual void cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetUseNormalVectorCurvature (bool value) inline virtual
Definition at line 142 of file cvITKLevelSetBase.h.
template<typename TInputImage , typename TInternalPixelType > template<typename TLevelSetFilterType > void cvITKLevelSetBase< TInputImage, TInternalPixelType >::ShowDebug (typename TLevelSetFilterType::Pointer levelSetFilter)
Definition at line 792 of file cvITKLevelSetBase.cxx.
References cvITKTemplateNewMacro.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> void cvITKLevelSetBase< TInputImage, TInternalPixelType >::ViewITKFront () inline
Definition at line 165 of file cvITKLevelSetBase.h.
References cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_itkFrontImage.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> void cvITKLevelSetBase< TInputImage, TInternalPixelType >::WriteFrontImages () inline
Definition at line 180 of file cvITKLevelSetBase.h.
References cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_itkFrontImage, cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_vtkFrontImage, and cvITKLSUtil::WriteImage().
Referenced by itkls2d_WriteFrontMtd(), and itkls3d_WriteFrontMtd().
Member Data Documentation
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> ImgInfo cvITKLevelSetBase< TInputImage, TInternalPixelType >::ExternalImgInfo private
Definition at line 218 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> ImgInfo cvITKLevelSetBase< TInputImage, TInternalPixelType >::InternalImgInfo private
Definition at line 217 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> double cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_AdvectionScaling private
Definition at line 244 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_BinarySeed private
Definition at line 251 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> double cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_CurvatureScaling private
Definition at line 243 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> cvStrPts* cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_cvInputImage private
Definition at line 220 of file cvITKLevelSetBase.h.
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::~cvITKLevelSetBase().
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> cvPolyData* cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_cvSeed private
Definition at line 221 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> cvStrPts* cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_cvSeedImage private
Definition at line 233 of file cvITKLevelSetBase.h.
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::~cvITKLevelSetBase().
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_Debug private
Definition at line 254 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> ITKInternalImageType::Pointer cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_itkFeatureImage private
Definition at line 223 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> ITKInternalImageType::Pointer cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_itkFrontImage private
Definition at line 232 of file cvITKLevelSetBase.h.
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::ViewITKFront(), and cvITKLevelSetBase< TInputImage, TInternalPixelType >::WriteFrontImages().
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> ITKInternalImageType::Pointer cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_itkSeedImage private
Definition at line 224 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> double cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_LaplacianScaling private
Definition at line 245 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> int cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_MaxIterations private
Definition at line 241 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> double cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_MaxRMSError private
Definition at line 240 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> double cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_PropagationScaling private
Definition at line 242 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> double cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_SigmaAdvection private
Definition at line 237 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> double cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_SigmaFeature private
Definition at line 236 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_UseMeanCurvature private
Definition at line 249 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_UseMinimalCurvature private
Definition at line 250 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> bool cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_UseNormalVectorCurvature private
Definition at line 248 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> vtkSmartPointer<vtkStructuredPoints> cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_vtkFeatureImage private
Definition at line 231 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> vtkSmartPointer<vtkStructuredPoints> cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_vtkFrontImage private
Definition at line 228 of file cvITKLevelSetBase.h.
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::WriteFrontImages().
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> vtkSmartPointer<vtkPolyData> cvITKLevelSetBase< TInputImage, TInternalPixelType >::m_vtkFrontPolyData private
Definition at line 227 of file cvITKLevelSetBase.h.
template<typename TInputImage = itk::Image<short,2>, typename TInternalPixelType = float> char cvITKLevelSetBase< TInputImage, TInternalPixelType >::tclName_[CV_STRLEN]
Definition at line 201 of file cvITKLevelSetBase.h.
Referenced by Deleteitkls2d(), Deleteitkls3d(), itkls2d_NewCmd(), and itkls3d_NewCmd().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/ITK/cvITKLevelSetBase.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/ITK/cvITKLevelSetBase.cxx