simvascular: cvAdapt Class Reference
cvAdapt Class Reference
Public Member Functions
cvAdapt ()
~cvAdapt ()
int Adapt (int, int, double, int, int, double, double, int option, int discreteFlag)
Public Member Functions inherited from cvAdaptCore
long eigen (double pos[3][3], double e[3][3], double v[3], int checkOrthogonality)
int checkUnitaryOthoganal (double e[3][3], int &factor)
double trace (double pos[3][3])
double trace2 (double pos[3][3])
double det (double pos[3][3])
long FindQuadraticRoots (const double b, const double c, double x[3])
long FindCubicRoots (const double coeff[4], double x[3])
long NullSpace (const double *a, double *result, double eps, long n)
double * InterpolateSolution (pRegion region, double xi[3], int ndof, pMeshDataId modes)
void display_region (pRegion region)
int inverseMap (pRegion region, double *qpt, double *pt)
void ModifyHessiansAtBdry (pMesh mesh)
void ModifyMetric (pVertex vertex, double dir[3][3], double *h)
void SmoothErrorIndicators (pMesh mesh, int option)
void SmoothHessians (pMesh mesh)
void V_AnalyticHessian (pVertex v, double H[3][3], int option)
void V_Hessian (pVertex v, double T[3][3])
void V_getHessians (double *hessiansFromPhasta, pMesh mesh, int nvar, int option, double *hessians)
void attachArray (double *valueArray, pMesh mesh, pMeshDataId dataID, int nVar, int poly)
void getAttachedArray (double *&valueArray, pMesh mesh, pMeshDataId dataID, int nVar, int poly)
void cleanAttachedData (pMesh mesh, pMeshDataId dataID, int en_type, int array=1)
void buildSystem (pRegion region, double *eltMatrix)
void phastaTransfer (MeshModType mtype, pMeshChanges mco, void *userData)
void elementGradient (pRegion region, double *elementGradient)
void elementHessian (pRegion region, double *elemHessian)
void fix4SolutionTransfer (pMesh mesh)
void gradientsFromPatch (pMesh mesh)
void hessiansFromPatch (pMesh mesh)
void hessiansFromSolution (pMesh mesh, int stepNumber)
int applyMarkingStrategy (pMesh mesh, pMSAdapt simAdapter, double factor, double hmin, double hmax, double &totalError, double &maxError, double &minError, double &threshold, int option)
double getErrorThreshold (pMesh mesh, double factor, double &totalError, double &maxError, double &minError, int option)
double getErrorValue (double *nodalValues, int option)
void readParametersFromFile (char *filename, char *fieldName, int &nshg, int &numVars)
void readArrayFromFile (char *filename, char *fieldName, double *&valueArray)
void writeArrayToFile (char *filename, char *fieldName, char *outputFormat, char *mode, int nshg, int numVars, int stepNumber, double *valueArray)
void setSizeFieldUsingHessians (pMesh mesh, pMSAdapt simAdapter, double factor, double hmax, double hmin, int option, double sphere[5])
double maxLocalError (pVertex vertex, double H[3][3])
double E_error (pEdge edge, double H[3][3])
void setIsotropicSizeField (pMesh mesh, pMSAdapt simAdapter, double factor, double hmax, double hmin, int option)
void setManualSizeField (pMesh mesh, pMSAdapt simAdapter, int strategy)
void tagEntitiesForRefinement (pMesh mesh, pMSAdapt simAdapter, double factor, double hmax, double hmin, int option)
void writeMEDITSolution (pMesh mesh)
void writeMEDITSizeField (Hessian *hess, pMesh mesh)
void writeRestartHessians (pMesh mesh)
void writeSmoothEIs (pMesh mesh)
void attachSolution (char *solfile, pMesh mesh, map< pEntity, double * > &data, int ndof, int P)
void attachSoln (char *solfile, pMesh mesh, pMeshDataId phSol, int ndof, int P)
int attachVPSoln (char *solfile, pMesh mesh, pMeshDataId phSol, pMeshDataId modes, int ndof)
void solution (pEntity ent, pMeshDataId phSol, double **sol)
void numberofmodes (pEntity ent, pMeshDataId modes, int *sol)
int restart (char filename[], double *q, int nshg, int nvr)
void check (pMesh mesh)
Public Attributes
char model_file_ [1024]
char mesh_file_ [1024]
char solution_file_ [1024]
char error_indicator_file_ [1024]
char out_mesh_file_ [1024]
char out_solution_file_ [1024]
double sphere_ [5]
Public Attributes inherited from cvAdaptCore
pMeshDataId phasta_solution
pMeshDataId nodalgradientID
pMeshDataId nodalhessianID
pMeshDataId errorIndicatorID
std::ofstream adaptSimLog
int CBcounter
int CBinvalidRegionCount
pMeshDataId modes
int numVars
char * iformat
Additional Inherited Members
Public Types inherited from cvAdaptCore
typedef struct Hessian Hessian
Detailed Description
Definition at line 71 of file main.cxx.
Constructor & Destructor Documentation
cvAdapt::cvAdapt () inline
Definition at line 75 of file main.cxx.
References cvAdaptCore::adaptSimLog, cvAdaptCore::CBcounter, cvAdaptCore::CBinvalidRegionCount, error_indicator_file_, cvAdaptCore::iformat, mesh_file_, model_file_, cvAdaptCore::numVars, out_mesh_file_, out_solution_file_, solution_file_, and sphere_.
cvAdapt::~cvAdapt () inline
Definition at line 91 of file main.cxx.
References cvAdaptCore::adaptSimLog.
Member Function Documentation
int cvAdapt::Adapt (int lstep, int strategy, double factor, int ndof, int nvar, double hmax, double hmin, int option, int discreteFlag)
Definition at line 583 of file main.cxx.
References cvAdaptCore::attachArray(), cvAdaptCore::CBcounter, cvAdaptCore::CBinvalidRegionCount, cvAdaptCore::cleanAttachedData(), cstylePhastaTransfer(), CV_ERROR, CV_OK, error_indicator_file_, cvAdaptCore::errorIndicatorID, cvAdaptCore::fix4SolutionTransfer(), cvAdaptCore::getAttachedArray(), cvAdaptCore::hessiansFromSolution(), mesh_file_, model_file_, cvAdaptCore::modes, cvAdaptCore::nodalhessianID, nshg, NULL, out_mesh_file_, out_solution_file_, cvAdaptCore::phasta_solution, PsdUtils_Init(), PsdUtils_ReadNative(), cvAdaptCore::readArrayFromFile(), cvAdaptCore::setIsotropicSizeField(), cvAdaptCore::setManualSizeField(), cvAdaptCore::setSizeFieldUsingHessians(), cvAdaptCore::SmoothErrorIndicators(), cvAdaptCore::SmoothHessians(), cvAdaptCore::solution(), solution_file_, sphere_, cvAdaptCore::tagEntitiesForRefinement(), cvAdaptCore::V_getHessians(), cvAdaptCore::writeArrayToFile(), and cvAdaptCore::writeSmoothEIs().
Referenced by main().
Member Data Documentation
char cvAdapt::error_indicator_file_[1024]
Definition at line 100 of file main.cxx.
Referenced by Adapt(), cvAdapt(), and main().
char cvAdapt::mesh_file_[1024]
Definition at line 98 of file main.cxx.
Referenced by Adapt(), cvAdapt(), and main().
char cvAdapt::model_file_[1024]
Definition at line 97 of file main.cxx.
Referenced by Adapt(), cvAdapt(), and main().
char cvAdapt::out_mesh_file_[1024]
Definition at line 101 of file main.cxx.
Referenced by Adapt(), cvAdapt(), and main().
char cvAdapt::out_solution_file_[1024]
Definition at line 102 of file main.cxx.
Referenced by Adapt(), cvAdapt(), and main().
char cvAdapt::solution_file_[1024]
Definition at line 99 of file main.cxx.
Referenced by Adapt(), cvAdapt(), and main().
double cvAdapt::sphere_[5]
Definition at line 104 of file main.cxx.
Referenced by Adapt(), cvAdapt(), and main().
The documentation for this class was generated from the following file:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/Adaptor/Adapt/main.cxx