simvascular: cvDistanceMap Class Reference
cvDistanceMap Class Reference
#include <cvDistanceMap.h>
Public Member Functions
cvDistanceMap ()
~cvDistanceMap ()
int createDistanceMap (vtkStructuredPoints *vtksp, vtkFloatingPointType thrval, int start[3])
vtkStructuredPoints * getDistanceMap ()
void setDistanceMap (vtkStructuredPoints *sp)
vtkPolyData * getPath (int stop[3], int minqstop)
vtkPolyData * getPathByThinning (int stop[3], int minqstop, int maxIterNum)
vtkPolyData * getPathOld (int stop[3])
void setUseCityBlockDistance ()
void setUse26ConnectivityDistance ()
Private Member Functions
int getCityBlockNeighbors (int p)
int get26ConnectivityNeighbors (int p)
int createInitMask ()
int thinMask (int *numPixelsRemoved)
Private Attributes
vtkStructuredPoints * map_
vtkStructuredPoints * mask_
vtkPolyData * path_
int start_ [3]
int stop_ [3]
int neighbors_ [26]
int numNeighbors_
int b_ [3][26]
int useCityBlock_
int imgDims_ [3]
Detailed Description
Definition at line 48 of file cvDistanceMap.h.
Constructor & Destructor Documentation
cvDistanceMap::cvDistanceMap ()
Definition at line 41 of file cvDistanceMap.cxx.
References b_, map_, mask_, NULL, path_, and useCityBlock_.
cvDistanceMap::~cvDistanceMap ()
Definition at line 66 of file cvDistanceMap.cxx.
References map_, NULL, and path_.
Member Function Documentation
int cvDistanceMap::createDistanceMap (vtkStructuredPoints * vtksp, vtkFloatingPointType thrval, int start[3])
Definition at line 75 of file cvDistanceMap.cxx.
References CV_OK, DISTANCEMAPVTKTYPE, get26ConnectivityNeighbors(), getCityBlockNeighbors(), imgDims_, map_, MAX_DISTANCE_VAL, neighbors_, NULL, numNeighbors_, start_, and useCityBlock_.
Referenced by Image_CreateDistanceMapCmd().
int cvDistanceMap::createInitMask () private
Definition at line 732 of file cvDistanceMap.cxx.
References CV_OK, imgDims_, map_, mask_, MAX_DISTANCE_VAL, and NULL.
Referenced by getPathByThinning().
int cvDistanceMap::get26ConnectivityNeighbors (int p) private
Definition at line 701 of file cvDistanceMap.cxx.
References b_, CV_OK, imgDims_, neighbors_, and numNeighbors_.
Referenced by createDistanceMap(), getPath(), getPathByThinning(), and getPathOld().
int cvDistanceMap::getCityBlockNeighbors (int p) private
Definition at line 649 of file cvDistanceMap.cxx.
References CV_OK, imgDims_, neighbors_, and numNeighbors_.
Referenced by createDistanceMap(), getPath(), getPathByThinning(), and getPathOld().
vtkStructuredPoints * cvDistanceMap::getDistanceMap ()
Definition at line 282 of file cvDistanceMap.cxx.
References map_.
Referenced by Image_CreateDistanceMapCmd().
vtkPolyData * cvDistanceMap::getPath (int stop[3], int minqstop)
Definition at line 384 of file cvDistanceMap.cxx.
References get26ConnectivityNeighbors(), getCityBlockNeighbors(), imgDims_, map_, MAX_DISTANCE_VAL, neighbors_, NULL, numNeighbors_, path_, stop_, and useCityBlock_.
Referenced by Image_FindPathCmd().
vtkPolyData * cvDistanceMap::getPathByThinning (int stop[3], int minqstop, int maxIterNum)
Definition at line 479 of file cvDistanceMap.cxx.
References createInitMask(), get26ConnectivityNeighbors(), getCityBlockNeighbors(), imgDims_, map_, mask_, MAX_DISTANCE_VAL, neighbors_, NULL, numNeighbors_, path_, stop_, thinMask(), and useCityBlock_.
Referenced by Image_FindPathCmd().
vtkPolyData * cvDistanceMap::getPathOld (int stop[3])
Definition at line 286 of file cvDistanceMap.cxx.
References get26ConnectivityNeighbors(), getCityBlockNeighbors(), imgDims_, map_, MAX_DISTANCE_VAL, neighbors_, NULL, numNeighbors_, path_, stop_, and useCityBlock_.
void cvDistanceMap::setDistanceMap (vtkStructuredPoints * sp)
Definition at line 636 of file cvDistanceMap.cxx.
References map_.
Referenced by Image_FindPathCmd().
void cvDistanceMap::setUse26ConnectivityDistance ()
Definition at line 644 of file cvDistanceMap.cxx.
References useCityBlock_.
Referenced by Image_CreateDistanceMapCmd(), and Image_FindPathCmd().
void cvDistanceMap::setUseCityBlockDistance ()
Definition at line 640 of file cvDistanceMap.cxx.
References useCityBlock_.
int cvDistanceMap::thinMask (int * numPixelsRemoved) private
Definition at line 787 of file cvDistanceMap.cxx.
References CV_OK, imgDims_, and mask_.
Referenced by getPathByThinning().
Member Data Documentation
int cvDistanceMap::b_[3][26] private
Definition at line 83 of file cvDistanceMap.h.
Referenced by cvDistanceMap(), and get26ConnectivityNeighbors().
int cvDistanceMap::imgDims_[3] private
Definition at line 86 of file cvDistanceMap.h.
Referenced by createDistanceMap(), createInitMask(), get26ConnectivityNeighbors(), getCityBlockNeighbors(), getPath(), getPathByThinning(), getPathOld(), and thinMask().
vtkStructuredPoints* cvDistanceMap::map_ private
Definition at line 74 of file cvDistanceMap.h.
Referenced by createDistanceMap(), createInitMask(), cvDistanceMap(), getDistanceMap(), getPath(), getPathByThinning(), getPathOld(), setDistanceMap(), and ~cvDistanceMap().
vtkStructuredPoints* cvDistanceMap::mask_ private
Definition at line 75 of file cvDistanceMap.h.
Referenced by createInitMask(), cvDistanceMap(), getPathByThinning(), and thinMask().
int cvDistanceMap::neighbors_[26] private
Definition at line 80 of file cvDistanceMap.h.
Referenced by createDistanceMap(), get26ConnectivityNeighbors(), getCityBlockNeighbors(), getPath(), getPathByThinning(), and getPathOld().
int cvDistanceMap::numNeighbors_ private
Definition at line 81 of file cvDistanceMap.h.
Referenced by createDistanceMap(), get26ConnectivityNeighbors(), getCityBlockNeighbors(), getPath(), getPathByThinning(), and getPathOld().
vtkPolyData* cvDistanceMap::path_ private
Definition at line 76 of file cvDistanceMap.h.
Referenced by cvDistanceMap(), getPath(), getPathByThinning(), getPathOld(), and ~cvDistanceMap().
int cvDistanceMap::start_[3] private
Definition at line 77 of file cvDistanceMap.h.
Referenced by createDistanceMap().
int cvDistanceMap::stop_[3] private
Definition at line 78 of file cvDistanceMap.h.
Referenced by getPath(), getPathByThinning(), and getPathOld().
int cvDistanceMap::useCityBlock_ private
Definition at line 84 of file cvDistanceMap.h.
Referenced by createDistanceMap(), cvDistanceMap(), getPath(), getPathByThinning(), getPathOld(), setUse26ConnectivityDistance(), and setUseCityBlockDistance().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Image/cvDistanceMap.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Image/cvDistanceMap.cxx