simvascular: cvSolidModel Class Reference
cvSolidModel Class Reference abstract
#include <cvSolidModel.h>
Public Member Functions
cvSolidModel (SolidModel_KernelT t)
virtual ~cvSolidModel ()
SolidModel_KernelT GetKernelT () const
virtual void Clear ()=0
virtual void Print () const =0
virtual void Check (int *nerr) const =0
virtual cvSolidModel * Copy () const =0
virtual int Copy (const cvSolidModel &src)=0
virtual int MakePoly2d (cvPolyData *pd)=0
virtual int MakePoly2dPts (cvPolyData *pd)=0
virtual int MakeCircle (double radius, double ctr[])=0
virtual int MakeEllipse (double xr, double yr, double ctr[])=0
virtual int MakeBox2d (double dims[], double ctr[])=0
virtual int MakeBox3d (double dims[], double ctr[])=0
virtual int MakeSphere (double r, double ctr[])=0
virtual int MakeEllipsoid (double r[], double ctr[])
virtual int MakeCylinder (double r, double length, double ctr[], double axis[])=0
virtual int MakeTorus (double rmaj, double rmin, double ctr[], double axis[])
virtual int MakeTruncatedCone (double pt[], double dir[], double r1, double r2)=0
virtual int SetPoly3dFacetMethod (SolidModel_FacetT code)=0
virtual int MakePoly3dSolid (cvPolyData *pd, double angle)=0
virtual int MakePoly3dSurface (cvPolyData *pd)=0
virtual int ExtrudeZ (cvSolidModel *in, double dist)=0
virtual int Extrude (cvSolidModel *in, double **dist)=0
virtual int MakeInterpCurveLoop (cvPolyData *pd, int closed)=0
virtual int MakeApproxCurveLoop (cvPolyData *pd, double tol, int closed)=0
virtual int MakeLoftedSurf (cvSolidModel **curves, int numCurves, char *name)=0
virtual int CapSurfToSolid (cvSolidModel *surf)
virtual int Intersect (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st=SM_Simplify_All)=0
virtual int Union (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st=SM_Simplify_All)=0
virtual int Subtract (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st=SM_Simplify_All)=0
virtual int Translate (double vec[], int ndim)=0
virtual int Rotate (double axis[], int ndim, double rad)=0
virtual int Scale (double factor)=0
virtual int Reflect (double pos[], double nrm[])=0
virtual int Apply4x4 (double mat[][4])=0
virtual cvPolyData * GetPolyData (int useMaxDist, double max_dist) const =0
virtual cvPolyData * GetFacePolyData (int faceid, int useMaxDist, double max_dist) const =0
virtual cvPolyData * GetDiscontinuities () const =0
virtual cvSolidModel * GetAxialIsoparametricCurve (double p) const =0
virtual int FindExtent (double *extent)=0
virtual int FindCentroid (double *centroid)=0
virtual int GetTopoDim (int *tdim) const =0
virtual int GetSpatialDim (int *sdim) const =0
virtual int ClassifyPt (double pt[], int v, int *ans) const =0
virtual int ClassifyPt (double x, double y, int v, int *ans) const =0
virtual int ClassifyPt (double x, double y, double z, int v, int *ans) const =0
virtual int DistanceAlongVec (double start[], double end[], int v, double *ans) const =0
virtual int Distance (double pos[], double upperLimit, double *dist)=0
virtual int GetFaceNormal (int faceid, double u, double v, double normal[])=0
virtual int GetBoundaryFaces (double angle)=0
virtual int GetFaceIds (int *numFaces, int **faceIds)=0
virtual int GetFaceAttribute (char *attr, int faceid, char **value)=0
virtual int SetFaceAttribute (char *attr, int faceid, char *value)=0
virtual int GetRegionIds (int *numRegions, int **RegionIds)=0
virtual int GetRegionAttribute (char *attr, int regionid, char **value)=0
virtual int SetRegionAttribute (char *attr, int regionid, char *value)=0
virtual int DeleteRegion (int regionid)=0
virtual int ReadNative (char *filename)=0
virtual int WriteNative (int file_version, char *filename) const =0
virtual int WriteVtkPolyData (char *filename)=0
virtual int DeleteFaces (int numfaces, int *faces)=0
virtual int CreateEdgeBlend (int faceA, int faceB, double radius)=0
virtual int CombineFaces (int targetface, int loseface)=0
virtual int RemeshFace (int numfaces, int *excludedFaces, double size)=0
virtual int SetVtkPolyDataObject (vtkPolyData *newPolyData)=0
Public Member Functions inherited from cvRepositoryData
cvRepositoryData (RepositoryDataT type)
virtual ~cvRepositoryData ()
void Lock ()
void Release ()
int NumLocks ()
RepositoryDataT GetType ()
char * GetName ()
void SetName (char *in)
int GetNumLabels ()
void GetLabelKeys (int *numKeys, char **keys[])
int IsLabelPresent (char *key)
int GetLabel (char *key, char **value)
int SetLabel (char *key, char *value)
void ClearLabel (char *key)
virtual int GetMemoryUsage ()
Static Public Member Functions
static cvSolidModel * DefaultInstantiateSolidModel (Tcl_Interp *interp=NULL)
Static Public Attributes
static SolidModel_KernelT gCurrentKernel = SM_KT_PARASOLID
static cvFactoryRegistrar gRegistrar
Protected Attributes
double tol_
Private Attributes
SolidModel_KernelT kernel_
Detailed Description
Definition at line 85 of file cvSolidModel.h.
Constructor & Destructor Documentation
cvSolidModel::cvSolidModel (SolidModel_KernelT t)
Definition at line 111 of file cvSolidModel.cxx.
References FindMachineEpsilon(), kernel_, and tol_.
cvSolidModel::~cvSolidModel () virtual
Definition at line 123 of file cvSolidModel.cxx.
Member Function Documentation
virtual int cvSolidModel::Apply4x4 (double mat[][4]) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_Apply4x4Mtd().
virtual int cvSolidModel::CapSurfToSolid (cvSolidModel * surf) inline virtual
Reimplemented in cvPolyDataSolid, and cvParasolidSolidModel.
Definition at line 135 of file cvSolidModel.h.
References CV_ERROR.
Referenced by Solid_CapSurfToSolidCmd().
virtual void cvSolidModel::Check (int * nerr) const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_CheckMtd().
virtual int cvSolidModel::ClassifyPt (double pt[], int v, int * ans) const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSetSparseGrid::ConstructHT(), cvLevelSetDenseGrid::InitPhi(), Solid_ClassifyPtMtd(), and sys_geom_Pick().
virtual int cvSolidModel::ClassifyPt (double x, double y, int v, int * ans) const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
virtual int cvSolidModel::ClassifyPt (double x, double y, double z, int v, int * ans) const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
virtual void cvSolidModel::Clear () pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by sys_geom_Pick().
virtual int cvSolidModel::CombineFaces (int targetface, int loseface) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_CombineFacesMtd().
virtual cvSolidModel* cvSolidModel::Copy () const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSet::SetSeed(), and Solid_CopyCmd().
virtual int cvSolidModel::Copy (const cvSolidModel & src) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
virtual int cvSolidModel::CreateEdgeBlend (int faceA, int faceB, double radius) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_CreateEdgeBlendMtd().
cvSolidModel * cvSolidModel::DefaultInstantiateSolidModel (Tcl_Interp * interp = NULL) static
Definition at line 68 of file cvSolidModel.cxx.
References gCurrentKernel, gVtkTclInterp, NULL, SM_KT_DISCRETE, SM_KT_PARASOLID, SM_KT_POLYDATA, and cvFactoryRegistrar::UseFactoryMethod().
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetDenseGrid::InitPhi(), Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_CopyCmd(), Solid_CylinderCmd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_IntersectCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_SphereCmd(), Solid_SubtractCmd(), Solid_TorusCmd(), Solid_TruncatedConeCmd(), Solid_UnionCmd(), and sys_geom_Pick().
virtual int cvSolidModel::DeleteFaces (int numfaces, int * faces) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_DeleteFacesMtd().
virtual int cvSolidModel::DeleteRegion (int regionid) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_DeleteRegionMtd().
virtual int cvSolidModel::Distance (double pos[], double upperLimit, double * dist) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSetDenseGrid::InitPhi(), and Solid_DistanceMtd().
virtual int cvSolidModel::DistanceAlongVec (double start[], double end[], int v, double * ans) const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
virtual int cvSolidModel::Extrude (cvSolidModel * in, double ** dist) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_ExtrudeCmd().
virtual int cvSolidModel::ExtrudeZ (cvSolidModel * in, double dist) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_ExtrudeZCmd().
virtual int cvSolidModel::FindCentroid (double * centroid) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_FindCentroidMtd().
virtual int cvSolidModel::FindExtent (double * extent) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_FindExtentMtd().
virtual cvSolidModel* cvSolidModel::GetAxialIsoparametricCurve (double p) const pure virtual
Implemented in cvMeshSimDiscreteSolidModel, cvPolyDataSolid, and cvParasolidSolidModel.
Referenced by Solid_GetAxialIsoparametricCurveMtd().
virtual int cvSolidModel::GetBoundaryFaces (double angle) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_GetBoundaryFacesMtd().
virtual cvPolyData* cvSolidModel::GetDiscontinuities () const pure virtual
Implemented in cvMeshSimDiscreteSolidModel, cvPolyDataSolid, and cvParasolidSolidModel.
Referenced by Solid_GetDiscontinuitiesMtd().
virtual int cvSolidModel::GetFaceAttribute (char * attr, int faceid, char ** value) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_GetFaceAttrMtd().
virtual int cvSolidModel::GetFaceIds (int * numFaces, int ** faceIds) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_GetFaceIdsMtd().
virtual int cvSolidModel::GetFaceNormal (int faceid, double u, double v, double normal[]) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_GetFaceNormalMtd().
virtual cvPolyData* cvSolidModel::GetFacePolyData (int faceid, int useMaxDist, double max_dist) const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_GetFacePolyDataMtd().
SolidModel_KernelT cvSolidModel::GetKernelT () const inline
Definition at line 92 of file cvSolidModel.h.
References kernel_.
Referenced by cvParasolidSolidModel::CapSurfToSolid(), cvParasolidSolidModel::Copy(), cvPolyDataSolid::Copy(), cvParasolidSolidModel::Extrude(), cvParasolidSolidModel::ExtrudeZ(), cvParasolidSolidModel::Intersect(), cvParasolidSolidModel::MakeLoftedSurf(), Solid_GetKernelMtd(), cvParasolidSolidModel::Subtract(), and cvParasolidSolidModel::Union().
virtual cvPolyData* cvSolidModel::GetPolyData (int useMaxDist, double max_dist) const pure virtual
Implemented in cvMeshSimDiscreteSolidModel, cvPolyDataSolid, and cvParasolidSolidModel.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), cvPolyDataSolid::Intersect(), Solid_GetPolyDataMtd(), cvPolyDataSolid::Subtract(), and cvPolyDataSolid::Union().
virtual int cvSolidModel::GetRegionAttribute (char * attr, int regionid, char ** value) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_GetRegionAttrMtd().
virtual int cvSolidModel::GetRegionIds (int * numRegions, int ** RegionIds) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_GetRegionIdsMtd().
virtual int cvSolidModel::GetSpatialDim (int * sdim) const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_ClassifyPtMtd(), Solid_DistanceMtd(), Solid_FindCentroidMtd(), and Solid_GetSpatialDimMtd().
virtual int cvSolidModel::GetTopoDim (int * tdim) const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_ClassifyPtMtd(), and Solid_GetTopoDimMtd().
virtual int cvSolidModel::Intersect (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st = SM_Simplify_All) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), and Solid_IntersectCmd().
virtual int cvSolidModel::MakeApproxCurveLoop (cvPolyData * pd, double tol, int closed) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_MakeApproxCurveLoopCmd().
virtual int cvSolidModel::MakeBox2d (double dims[], double ctr[]) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), and Solid_Box2dCmd().
virtual int cvSolidModel::MakeBox3d (double dims[], double ctr[]) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), and Solid_Box3dCmd().
virtual int cvSolidModel::MakeCircle (double radius, double ctr[]) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_CircleCmd().
virtual int cvSolidModel::MakeCylinder (double r, double length, double ctr[], double axis[]) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_CylinderCmd().
virtual int cvSolidModel::MakeEllipse (double xr, double yr, double ctr[]) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_EllipseCmd().
virtual int cvSolidModel::MakeEllipsoid (double r[], double ctr[]) inline virtual
Reimplemented in cvPolyDataSolid.
Definition at line 118 of file cvSolidModel.h.
References CV_ERROR.
Referenced by Solid_EllipsoidCmd().
virtual int cvSolidModel::MakeInterpCurveLoop (cvPolyData * pd, int closed) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_MakeInterpCurveLoopCmd().
virtual int cvSolidModel::MakeLoftedSurf (cvSolidModel ** curves, int numCurves, char * name) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_MakeLoftedSurfCmd().
virtual int cvSolidModel::MakePoly2d (cvPolyData * pd) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetDenseGrid::InitPhi(), Solid_PolyCmd(), and sys_geom_Pick().
virtual int cvSolidModel::MakePoly2dPts (cvPolyData * pd) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_PolyPtsCmd().
virtual int cvSolidModel::MakePoly3dSolid (cvPolyData * pd, double angle) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSetSparseGrid::ConstructHT(), cvLevelSetDenseGrid::InitPhi(), and Solid_Poly3dSolidCmd().
virtual int cvSolidModel::MakePoly3dSurface (cvPolyData * pd) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), and Solid_Poly3dSurfaceCmd().
virtual int cvSolidModel::MakeSphere (double r, double ctr[]) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_SphereCmd().
virtual int cvSolidModel::MakeTorus (double rmaj, double rmin, double ctr[], double axis[]) inline virtual
Reimplemented in cvPolyDataSolid, and cvParasolidSolidModel.
Definition at line 122 of file cvSolidModel.h.
References CV_ERROR.
Referenced by Solid_TorusCmd().
virtual int cvSolidModel::MakeTruncatedCone (double pt[], double dir[], double r1, double r2) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_TruncatedConeCmd().
virtual void cvSolidModel::Print () const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_PrintMtd().
virtual int cvSolidModel::ReadNative (char * filename) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_ReadNativeCmd().
virtual int cvSolidModel::Reflect (double pos[], double nrm[]) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_ReflectMtd().
virtual int cvSolidModel::RemeshFace (int numfaces, int * excludedFaces, double size) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_RemeshFaceMtd().
virtual int cvSolidModel::Rotate (double axis[], int ndim, double rad) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_RotateMtd().
virtual int cvSolidModel::Scale (double factor) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_ScaleMtd().
virtual int cvSolidModel::SetFaceAttribute (char * attr, int faceid, char * value) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_SetFaceAttrMtd().
virtual int cvSolidModel::SetPoly3dFacetMethod (SolidModel_FacetT code) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), Solid_Poly3dSolidCmd(), and Solid_Poly3dSurfaceCmd().
virtual int cvSolidModel::SetRegionAttribute (char * attr, int regionid, char * value) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_SetRegionAttrMtd().
virtual int cvSolidModel::SetVtkPolyDataObject (vtkPolyData * newPolyData) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_SetVtkPolyDataMtd().
virtual int cvSolidModel::Subtract (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st = SM_Simplify_All) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_SubtractCmd().
virtual int cvSolidModel::Translate (double vec[], int ndim) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_TranslateMtd().
virtual int cvSolidModel::Union (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st = SM_Simplify_All) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_UnionCmd().
virtual int cvSolidModel::WriteNative (int file_version, char * filename) const pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_WriteNativeMtd().
virtual int cvSolidModel::WriteVtkPolyData (char * filename) pure virtual
Implemented in cvPolyDataSolid, cvMeshSimDiscreteSolidModel, and cvParasolidSolidModel.
Referenced by Solid_WriteVtkPolyDataMtd().
Member Data Documentation
SolidModel_KernelT cvSolidModel::gCurrentKernel = SM_KT_PARASOLID static
Definition at line 99 of file cvSolidModel.h.
Referenced by DefaultInstantiateSolidModel(), Solid_GetKernelCmd(), Solid_Init(), Solid_ReadNativeCmd(), and Solid_SetKernelCmd().
cvFactoryRegistrar cvSolidModel::gRegistrar static
Definition at line 100 of file cvSolidModel.h.
Referenced by Solid_Init().
SolidModel_KernelT cvSolidModel::kernel_ private
Definition at line 199 of file cvSolidModel.h.
Referenced by cvSolidModel(), and GetKernelT().
double cvSolidModel::tol_ protected
Definition at line 196 of file cvSolidModel.h.
Referenced by cvSolidModel().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/SolidModel/cvSolidModel.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/SolidModel/cvSolidModel.cxx