simvascular: cvTetAdapt Class Reference
cvTetAdapt Class Reference
Public Member Functions
cvTetAdapt ()
~cvTetAdapt ()
int Adapt (int, int, double, int, int, double, double)
Public Member Functions inherited from cvTetAdaptCore
void ModifyHessiansAtBdry (vtkUnstructuredGrid *mesh)
void ModifyMetric (vtkIdType vertex, double dir[3][3], double *h)
void SmoothHessians (vtkUnstructuredGrid *mesh)
simple average over a patch surrounding the vertex
void getHessiansFromPhasta (double *hessiansFromPhasta, vtkUnstructuredGrid *mesh, int nvar, double *hessians)
extracts hessians from vector retrieved from restart and puts it in an attachable format for vtk
void getHessian (vtkDoubleArray *Hessians, vtkIdType v, double T[3][3])
returns a vector with hessian values from vtkDoubleArray
void attachArray (double *valueArray, vtkUnstructuredGrid *mesh, std::string dataName, int nVar, int poly)
This attaches an array of doubles to a vtkUnstructuredGrid.
void getAttachedArray (double *&valueArray, vtkUnstructuredGrid *mesh, std::string dataName, int nVar, int poly)
This gets an array that is attached to a vtkUnstructuredGrid.
void phastaTransfer (int mtype, int mco, void *userData)
void fix4SolutionTransfer (vtkUnstructuredGrid *inmesh, vtkUnstructuredGrid *outmesh, int nVar)
This function interpolates the solution from the old mesh onto the new mesh.
void gradientsFromFilter (vtkUnstructuredGrid *mesh)
Filter to take the gradients of a scalar array, should be speed.
void hessiansFromFilter (vtkUnstructuredGrid *mesh)
Filter to take the hessians of gradient array.
void hessiansFromSolution (vtkUnstructuredGrid *mesh, int stepNumber)
This function calls the gradient and hessian filters to get hessian matrix in order to set the mesh size field.
int applyMarkingStrategy (vtkUnstructuredGrid *mesh, int simTetGenAdapter, double factor, double hmin, double hmax, double &totalError, double &maxError, double &minError, double &threshold, int option)
double getErrorThreshold (vtkUnstructuredGrid *mesh, double factor, double &totalError, double &maxError, double &minError, int option)
double getErrorValue (double *nodalValues, int option)
void setSizeFieldUsingHessians (vtkUnstructuredGrid *mesh, tetgenio *inmesh, double factor, double hmax, double hmin)
This function takes the hessian field data and computes a mesh size field for the mesh adaptation/refinement.
double maxLocalError (vtkUnstructuredGrid *mesh, vtkIdType vertex, double H[3][3])
This returns the maximum relative interpolation error at a vertex.
double E_error (double xyz[2][3], double H[3][3])
This is called by maxLocalError. It gets the error along an edge.
void setIsotropicSizeField (vtkUnstructuredGrid *mesh, int simTetGenAdapter, double factor, double hmax, double hmin, int option)
void setManualSizeField (vtkUnstructuredGrid *mesh, int simTetGenAdapter, int strategy)
void tagEntitiesForRefinement (vtkUnstructuredGrid *mesh, int simTetGenAdapter, double factor, double hmax, double hmin, int option)
void writeMEDITSolution (vtkUnstructuredGrid *mesh)
void writeMEDITSizeField (Hessian *hess, vtkUnstructuredGrid *mesh)
int getSurfaceBooleans (vtkUnstructuredGrid *mesh, bool *pointOnSurface, int *pointMapper)
This is a function to determine what points of a mesh on on the surface. This is done by applying node ids, extracting the surface, and then checking for matching node ids.
int convertToTetGen (vtkUnstructuredGrid *mesh, vtkPolyData *surfaceMesh, tetgenio *inmesh)
Function to convert the current mesh to a tetgen mesh object to be able to remesh.
int runAdaptor (tetgenio *inmesh, tetgenio *outmesh)
This is a function to run tetgen on the mesh.
int convertToVTK (vtkUnstructuredGrid *mesh, vtkPolyData *surfaceMesh, tetgenio *outmesh)
This is a function to convert back to vtk structured from a tetgen mesh.
Public Attributes
char surface_mesh_file_ [1024]
char mesh_file_ [1024]
char solution_file_ [1024]
char error_indicator_file_ [1024]
char out_surface_mesh_file_ [1024]
char out_mesh_file_ [1024]
char out_solution_file_ [1024]
Public Attributes inherited from cvTetAdaptCore
int phasta_solution
int nodalgradientID
int nodalhessianID
int errorIndicatorID
std::ofstream adaptSimLog
int CBcounter
int CBinvalidRegionCount
int modes
int numVars
char * iformat
Detailed Description
Definition at line 70 of file main.cxx.
Constructor & Destructor Documentation
cvTetAdapt::cvTetAdapt () inline
Definition at line 74 of file main.cxx.
References cvTetAdaptCore::CBcounter, cvTetAdaptCore::CBinvalidRegionCount, error_indicator_file_, cvTetAdaptCore::iformat, mesh_file_, cvTetAdaptCore::numVars, out_mesh_file_, out_solution_file_, out_surface_mesh_file_, solution_file_, and surface_mesh_file_.
cvTetAdapt::~cvTetAdapt () inline
Definition at line 88 of file main.cxx.
Member Function Documentation
int cvTetAdapt::Adapt (int lstep, int strategy, double factor, int ndof, int nvar, double hmax, double hmin)
Definition at line 451 of file main.cxx.
References cvTetAdaptCore::attachArray(), cvTetAdaptCore::convertToTetGen(), cvTetAdaptCore::convertToVTK(), error_indicator_file_, cvTetAdaptCore::fix4SolutionTransfer(), cvTetAdaptCore::getAttachedArray(), cvTetAdaptCore::getHessiansFromPhasta(), cvTetAdaptCore::hessiansFromSolution(), mesh_file_, nshg, out_mesh_file_, out_solution_file_, out_surface_mesh_file_, readArrayFromFile(), cvTetAdaptCore::runAdaptor(), cvTetAdaptCore::setSizeFieldUsingHessians(), solution_file_, surface_mesh_file_, and writeArrayToFile().
Referenced by main().
Member Data Documentation
char cvTetAdapt::error_indicator_file_[1024]
Definition at line 96 of file main.cxx.
Referenced by Adapt(), cvTetAdapt(), and main().
char cvTetAdapt::mesh_file_[1024]
Definition at line 94 of file main.cxx.
Referenced by Adapt(), cvTetAdapt(), and main().
char cvTetAdapt::out_mesh_file_[1024]
Definition at line 98 of file main.cxx.
Referenced by Adapt(), cvTetAdapt(), and main().
char cvTetAdapt::out_solution_file_[1024]
Definition at line 99 of file main.cxx.
Referenced by Adapt(), cvTetAdapt(), and main().
char cvTetAdapt::out_surface_mesh_file_[1024]
Definition at line 97 of file main.cxx.
Referenced by Adapt(), cvTetAdapt(), and main().
char cvTetAdapt::solution_file_[1024]
Definition at line 95 of file main.cxx.
Referenced by Adapt(), cvTetAdapt(), and main().
char cvTetAdapt::surface_mesh_file_[1024]
Definition at line 93 of file main.cxx.
Referenced by Adapt(), cvTetAdapt(), and main().
The documentation for this class was generated from the following file:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/TetAdapt/main.cxx