simvascular: vtkvmtkMath Class Reference
vtkvmtkMath Class Reference
#include <vtkvmtkMath.h>
Public Member Functions
vtkTypeMacro (vtkvmtkMath, vtkObject)
Static Public Member Functions
static vtkvmtkMath * New ()
static double Cotangent (double point0[3], double point1[3], double point2[3])
static double TriangleArea (double point0[3], double point1[3], double point2[3])
static int IsAngleObtuse (double point0[3], double point1[3], double point2[3])
static int IsTriangleObtuse (double point0[3], double point1[3], double point2[3])
static double VoronoiSectorArea (double point0[3], double point1[3], double point2[3])
static double TriangleGradient (double point0[3], double point1[3], double point2[3], double scalar0, double scalar1, double scalar2, double gradient[3])
static void TwoSphereIntersection (double center0[3], double radius0, double center1[3], double radius1, double origin[3], double normal[3])
static double AngleBetweenNormals (double normal0[3], double normal1[3])
static double EvaluateSphereFunction (double center[3], double radius, double point[3])
Protected Member Functions
vtkvmtkMath ()
~vtkvmtkMath ()
Static Protected Member Functions
static double GetTolerance (float cookie)
static double GetTolerance (double cookie)
static double GetLarge (float cookie)
static double GetLarge (double cookie)
Private Member Functions
vtkvmtkMath (const vtkvmtkMath &)
void operator= (const vtkvmtkMath &)
Detailed Description
Definition at line 37 of file vtkvmtkMath.h.
Constructor & Destructor Documentation
vtkvmtkMath::vtkvmtkMath () inline protected
Definition at line 56 of file vtkvmtkMath.h.
vtkvmtkMath::~vtkvmtkMath () inline protected
Definition at line 57 of file vtkvmtkMath.h.
vtkvmtkMath::vtkvmtkMath (const vtkvmtkMath &) private
Member Function Documentation
double vtkvmtkMath::AngleBetweenNormals (double normal0[3], double normal1[3]) static
Definition at line 209 of file vtkvmtkMath.cxx.
References Norm().
double vtkvmtkMath::Cotangent (double point0[3], double point1[3], double point2[3]) static
Definition at line 28 of file vtkvmtkMath.cxx.
References GetLarge(), and GetTolerance().
Referenced by VoronoiSectorArea().
double vtkvmtkMath::EvaluateSphereFunction (double center[3], double radius, double point[3]) static
Definition at line 227 of file vtkvmtkMath.cxx.
static double vtkvmtkMath::GetLarge (float cookie) inline static protected
Definition at line 69 of file vtkvmtkMath.h.
References VTK_VMTK_LARGE_FLOAT.
Referenced by Cotangent(), and TriangleGradient().
static double vtkvmtkMath::GetLarge (double cookie) inline static protected
Definition at line 74 of file vtkvmtkMath.h.
References VTK_VMTK_LARGE_DOUBLE.
static double vtkvmtkMath::GetTolerance (float cookie) inline static protected
Definition at line 59 of file vtkvmtkMath.h.
References VTK_VMTK_FLOAT_TOL.
Referenced by Cotangent(), IsAngleObtuse(), TriangleArea(), TriangleGradient(), TwoSphereIntersection(), and VoronoiSectorArea().
static double vtkvmtkMath::GetTolerance (double cookie) inline static protected
Definition at line 64 of file vtkvmtkMath.h.
References VTK_VMTK_DOUBLE_TOL.
int vtkvmtkMath::IsAngleObtuse (double point0[3], double point1[3], double point2[3]) static
Definition at line 77 of file vtkvmtkMath.cxx.
References GetTolerance().
Referenced by IsTriangleObtuse().
int vtkvmtkMath::IsTriangleObtuse (double point0[3], double point1[3], double point2[3]) static
Definition at line 85 of file vtkvmtkMath.cxx.
References IsAngleObtuse(), VTK_VMTK_NON_OBTUSE, VTK_VMTK_OBTUSE_IN_POINT, and VTK_VMTK_OBTUSE_NOT_IN_POINT.
static vtkvmtkMath* vtkvmtkMath::New () static
void vtkvmtkMath::operator= (const vtkvmtkMath &) private
double vtkvmtkMath::TriangleArea (double point0[3], double point1[3], double point2[3]) static
Definition at line 61 of file vtkvmtkMath.cxx.
References GetTolerance().
Referenced by vtkvmtkPolyDataManifoldStencil::ComputeArea(), and TriangleGradient().
double vtkvmtkMath::TriangleGradient (double point0[3], double point1[3], double point2[3], double scalar0, double scalar1, double scalar2, double gradient[3]) static
Definition at line 114 of file vtkvmtkMath.cxx.
References Cross(), GetLarge(), GetTolerance(), Norm(), and TriangleArea().
void vtkvmtkMath::TwoSphereIntersection (double center0[3], double radius0, double center1[3], double radius1, double origin[3], double normal[3]) static
Definition at line 166 of file vtkvmtkMath.cxx.
References GetTolerance().
double vtkvmtkMath::VoronoiSectorArea (double point0[3], double point1[3], double point2[3]) static
Definition at line 95 of file vtkvmtkMath.cxx.
References Cotangent(), and GetTolerance().
vtkvmtkMath::vtkTypeMacro (vtkvmtkMath , vtkObject)
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkMath.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkMath.cxx