simvascular: cvLevelSet Class Reference
cvLevelSet Class Reference
#include <cvLevelSet.h>
Public Member Functions
cvLevelSet ()
~cvLevelSet ()
int SetDtFactor (double dtf)
int GetDtFactor (double *dtf)
double GetDtFactor ()
int SetSimTime (double simTime)
int GetSimTime (double *simTime)
int GetCurrTime (double *currTime)
int GetTimeStep ()
void ResetTimeStep ()
int SetGridType (GridT gt)
GridT GetGridType ()
int SetGridSpacing (double hv[])
int GetGridSpacing (double hv[])
int SetGridSize (int gsize[])
int GetGridSize (int gsize[])
int SetGridOrigin (double origin[])
int GetGridOrigin (double origin[])
int SetGridBandParams (double bandExt[], double mineWd)
int GetGridBandParams (double bandExt[], double *mineWd)
int SetSeed (Seed_T *s)
int GetSeed (Seed_T *s)
int SetSeed (cvPolyData *s)
int GetSeed (cvPolyData **s)
int SetSeed (cvSolidModel *s)
int GetSeed (cvSolidModel **s)
int SetSeed (cvStrPts *s, double thr)
int GetSeed (cvStrPts **s, double *thr)
int LinkVelocity (cvLevelSetVelocity *v)
int UnlinkVelocity ()
int GetVelocity (cvLevelSetVelocity **v)
cvLevelSetStructuredGrid * GetGrid ()
int Status ()
int Init ()
int EvolveOneTimeStep ()
cvPolyData * ExtractFront (int closed=0)
int RebuildPhi ()
cvDataObject * ExtractPhi ()
cvStrPts * ExtractCurvature ()
cvPolyData * ExtractVectors ()
double GetMaxPhiIncr ()
double GetMaxV ()
int Vanished ()
cvPolyData * ExtractActiveNodes ()
char * GetGridStatString ()
int SetVExtension (ExtensionT etype)
int GetVExtension (ExtensionT *etype)
void SetTimers (int flag)
void GetTimers (int *flag)
double GetTimerGranularity ()
int GetMemoryUsage ()
void SetSaveProjectionSets (int flag)
void GetSaveProjectionSets (int *flag)
Public Attributes
char tclName_ [CV_STRLEN]
Private Member Functions
void DeallocateSeedObjs ()
int ValidSeedExists ()
int StopCondition ()
Private Attributes
cvLevelSetStructuredGrid * grid_
GridT gridType_
cvLevelSetVelocity * velocity_
Seed_T * seed_
cvPolyData * pdSeed_
cvSolidModel * smSeed_
cvStrPts * imgSeed_
double imgSeedThr_
double dt_
double dtFactor_
double simTime_
double currTime_
int tn_
int status_
ExtensionT etype_
int rebuildPhiValid_
double maxPhiIncr_
double maxV_
double hx_
double hy_
double hz_
int gridx_
int gridy_
int gridz_
double origin_ [3]
int originValid_
double bandExt_ [2]
double mineWd_
int zlsVanished_
int timers_
cvCPUTimer cpuTimer
int saveProjectionSets_
Friends
class cvLevelSetVelocity
Detailed Description
Definition at line 78 of file cvLevelSet.h.
Constructor & Destructor Documentation
cvLevelSet::cvLevelSet ()
Definition at line 56 of file cvLevelSet.cxx.
References bandExt_, currTime_, Dense_GridT, dt_, dtFactor_, etype_, grid_, gridType_, gridx_, gridy_, gridz_, hx_, hy_, hz_, imgSeed_, maxPhiIncr_, maxV_, mineWd_, NULL, originValid_, pdSeed_, PROJECT_V, rebuildPhiValid_, saveProjectionSets_, seed_, simTime_, smSeed_, status_, timers_, tn_, velocity_, and zlsVanished_.
cvLevelSet::~cvLevelSet ()
Definition at line 97 of file cvLevelSet.cxx.
References DeallocateSeedObjs(), grid_, cvLevelSetVelocity::UnlinkLevelSet(), and velocity_.
Member Function Documentation
void cvLevelSet::DeallocateSeedObjs () private
Definition at line 324 of file cvLevelSet.cxx.
References imgSeed_, NULL, pdSeed_, seed_, and smSeed_.
Referenced by SetSeed(), and ~cvLevelSet().
int cvLevelSet::EvolveOneTimeStep ()
Definition at line 674 of file cvLevelSet.cxx.
References cvLevelSetStructuredGrid::ComputeDeltaPhi(), cpuTimer, currTime_, CV_OK, dt_, dtFactor_, etype_, cvLevelSetStructuredGrid::EvaluateV(), EXTEND_V, cvLevelSetStructuredGrid::ExtendV(), grid_, NULL, PROJECT_V, cvLevelSetStructuredGrid::ProjectV(), rebuildPhiValid_, cvBaseTimer::reset(), saveProjectionSets_, cvBaseTimer::seconds(), StopCondition(), tclName_, timers_, tn_, cvLevelSetStructuredGrid::UpdatePhi(), velocity_, and zlsVanished_.
Referenced by LsetCore_EvolveOneTimeStepMtd().
cvPolyData * cvLevelSet::ExtractActiveNodes ()
Definition at line 923 of file cvLevelSet.cxx.
References cpuTimer, cvLevelSetStructuredGrid::GetActiveNodes(), grid_, cvBaseTimer::reset(), cvBaseTimer::seconds(), and timers_.
cvStrPts * cvLevelSet::ExtractCurvature ()
Definition at line 883 of file cvLevelSet.cxx.
References cpuTimer, cvLevelSetStructuredGrid::GetCurvature(), grid_, cvBaseTimer::reset(), cvBaseTimer::seconds(), and timers_.
Referenced by LsetCore_ExtractCurvatureMtd().
cvPolyData * cvLevelSet::ExtractFront (int closed = 0)
Definition at line 761 of file cvLevelSet.cxx.
References cpuTimer, cvLevelSetStructuredGrid::GetFront(), grid_, cvBaseTimer::reset(), cvBaseTimer::seconds(), and timers_.
Referenced by LsetCore_ExtractFrontMtd().
cvDataObject * cvLevelSet::ExtractPhi ()
Definition at line 863 of file cvLevelSet.cxx.
References cpuTimer, cvLevelSetStructuredGrid::GetPhi(), grid_, cvBaseTimer::reset(), cvBaseTimer::seconds(), and timers_.
Referenced by LsetCore_ExtractPhiMtd().
cvPolyData * cvLevelSet::ExtractVectors ()
Definition at line 903 of file cvLevelSet.cxx.
References cpuTimer, cvLevelSetStructuredGrid::GetVelocityVectors(), grid_, cvBaseTimer::reset(), cvBaseTimer::seconds(), and timers_.
Referenced by LsetCore_ExtractVelMtd().
int cvLevelSet::GetCurrTime (double * currTime)
Definition at line 313 of file cvLevelSet.cxx.
References currTime_.
Referenced by LsetCore_GetTimeMtd(), cvLevelSetVelocityConstant::StopCondition(), cvLevelSetVelocityThreshold::StopCondition(), and cvLevelSetVelocityKGI::StopCondition().
int cvLevelSet::GetDtFactor (double * dtf)
Definition at line 128 of file cvLevelSet.cxx.
References dtFactor_.
Referenced by LsetCore_GetTimeMtd().
double cvLevelSet::GetDtFactor () inline
Definition at line 89 of file cvLevelSet.h.
References dtFactor_.
cvLevelSetStructuredGrid* cvLevelSet::GetGrid () inline
Definition at line 122 of file cvLevelSet.h.
References grid_.
Referenced by cvLevelSetVelocityConstant::Evaluate(), cvLevelSetVelocityThreshold::Evaluate(), cvLevelSetVelocitySmooth::Evaluate(), cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), cvLevelSetVelocityExponentialDecay::Evaluate(), LsetCore_ExtractActiveNodesMtd(), LsetCore_ExtractCoveredNodesMtd(), LsetCore_ExtractForceMinVNodesMtd(), LsetCore_ExtractMineNodesMtd(), LsetCore_ExtractProjectionSetsMtd(), LsetCore_ExtractUncoveredNodesMtd(), LsetCore_GetBoundaryDataMtd(), LsetCore_GridModifiedMtd(), LsetCore_SaveGridMtd(), cvLevelSetVelocityThreshold::StopCondition(), cvLevelSetVelocityKGI::StopCondition(), and cvLevelSetVelocity::UpdateTolerance().
int cvLevelSet::GetGridBandParams (double bandExt[], double * mineWd)
Definition at line 296 of file cvLevelSet.cxx.
References bandExt_, and mineWd_.
Referenced by LsetCore_GetGridMtd().
int cvLevelSet::GetGridOrigin (double origin[])
Definition at line 262 of file cvLevelSet.cxx.
References origin_, and originValid_.
Referenced by LsetCore_GetGridMtd().
int cvLevelSet::GetGridSize (int gsize[])
Definition at line 231 of file cvLevelSet.cxx.
References gridx_, gridy_, and gridz_.
Referenced by LsetCore_GetGridMtd().
int cvLevelSet::GetGridSpacing (double hv[])
Definition at line 197 of file cvLevelSet.cxx.
References hx_, hy_, and hz_.
Referenced by LsetCore_GetGridMtd().
char * cvLevelSet::GetGridStatString ()
Definition at line 971 of file cvLevelSet.cxx.
References CV_STRLEN, grid_, NULL, and cvLevelSetStructuredGrid::StatString().
Referenced by LsetCore_GetGridStatsMtd().
GridT cvLevelSet::GetGridType () inline
Definition at line 98 of file cvLevelSet.h.
References gridType_.
Referenced by LsetCore_GetGridMtd().
double cvLevelSet::GetMaxPhiIncr () inline
Definition at line 135 of file cvLevelSet.h.
References maxPhiIncr_.
double cvLevelSet::GetMaxV () inline
Definition at line 136 of file cvLevelSet.h.
References maxV_.
Referenced by LsetCore_FindMaxVMtd().
int cvLevelSet::GetMemoryUsage ()
Definition at line 989 of file cvLevelSet.cxx.
References cvDataObject::GetMemoryUsage(), cvLevelSetVelocity::GetMemoryUsage(), cvRepositoryData::GetMemoryUsage(), cvLevelSetStructuredGrid::GetMemoryUsage(), grid_, imgSeed_, pdSeed_, seed_, smSeed_, and velocity_.
Referenced by LsetCore_GetMemoryUsageMtd().
void cvLevelSet::GetSaveProjectionSets (int * flag) inline
Definition at line 157 of file cvLevelSet.h.
Referenced by LsetCore_GetSaveProjectionSetsMtd().
int cvLevelSet::GetSeed (Seed_T * s)
Definition at line 382 of file cvLevelSet.cxx.
References NULL, and seed_.
Referenced by LsetCore_GetCircleSeedMtd(), LsetCore_GetImageSeedMtd(), LsetCore_GetPdSeedMtd(), and LsetCore_GetSolidSeedMtd().
int cvLevelSet::GetSeed (cvPolyData ** s)
Definition at line 412 of file cvLevelSet.cxx.
References NULL, and pdSeed_.
int cvLevelSet::GetSeed (cvSolidModel ** s)
Definition at line 442 of file cvLevelSet.cxx.
References NULL, and smSeed_.
int cvLevelSet::GetSeed (cvStrPts ** s, double * thr)
Definition at line 472 of file cvLevelSet.cxx.
References imgSeed_, imgSeedThr_, and NULL.
int cvLevelSet::GetSimTime (double * simTime)
Definition at line 154 of file cvLevelSet.cxx.
References simTime_.
Referenced by LsetCore_GetTimeMtd().
double cvLevelSet::GetTimerGranularity () inline
Definition at line 150 of file cvLevelSet.h.
References cpuTimer, and cvBaseTimer::granularity().
Referenced by LsetCore_GetTimerGranularityMtd().
void cvLevelSet::GetTimers (int * flag) inline
Definition at line 149 of file cvLevelSet.h.
References timers_.
Referenced by LsetCore_GetTimersMtd().
int cvLevelSet::GetTimeStep () inline
Definition at line 93 of file cvLevelSet.h.
References tn_.
Referenced by LsetCore_GetTimeStepMtd().
int cvLevelSet::GetVelocity (cvLevelSetVelocity ** v)
Definition at line 539 of file cvLevelSet.cxx.
References CV_OK, and velocity_.
Referenced by cvLevelSetVelocity::LinkLevelSet(), and LsetCore_GetVelocityMtd().
int cvLevelSet::GetVExtension (ExtensionT * etype)
Definition at line 960 of file cvLevelSet.cxx.
References CV_OK, and etype_.
Referenced by LsetCore_GetVExtensionMtd().
int cvLevelSet::Init ()
Definition at line 551 of file cvLevelSet.cxx.
References bandExt_, cpuTimer, currTime_, CV_OK, Dense_GridT, grid_, gridType_, gridx_, gridy_, gridz_, hx_, hy_, hz_, imgSeed_, imgSeedThr_, cvLevelSetStructuredGrid::InitPhi(), mineWd_, NULL, origin_, originValid_, pdSeed_, Seed_T::pos, Seed_T::r, cvBaseTimer::reset(), cvBaseTimer::seconds(), seed_, cvLevelSetStructuredGrid::SetBandParams(), smSeed_, Sparse_GridT, status_, timers_, tn_, cvLevelSetVelocity::UpdateTolerance(), ValidSeedExists(), velocity_, and zlsVanished_.
Referenced by LsetCore_InitMtd().
int cvLevelSet::LinkVelocity (cvLevelSetVelocity * v)
Definition at line 493 of file cvLevelSet.cxx.
References CV_ERROR, CV_OK, cvLevelSetVelocity::GetLevelSet(), cvLevelSetVelocity::LinkLevelSet(), NULL, UnlinkVelocity(), and velocity_.
Referenced by cvLevelSetVelocity::LinkLevelSet(), and LsetCore_SetVelocityMtd().
int cvLevelSet::RebuildPhi ()
Definition at line 781 of file cvLevelSet.cxx.
References cpuTimer, CV_OK, grid_, rebuildPhiValid_, cvLevelSetStructuredGrid::ReinitPhi(), cvBaseTimer::reset(), cvBaseTimer::seconds(), and timers_.
Referenced by LsetCore_RebuildPhiMtd().
void cvLevelSet::ResetTimeStep () inline
Definition at line 94 of file cvLevelSet.h.
References tn_.
Referenced by LsetCore_ResetTimeStepMtd().
int cvLevelSet::SetDtFactor (double dtf)
Definition at line 111 of file cvLevelSet.cxx.
References dtFactor_, FindMachineEpsilon(), and minimum.
Referenced by LsetCore_SetTimeMtd().
int cvLevelSet::SetGridBandParams (double bandExt[], double mineWd)
Definition at line 279 of file cvLevelSet.cxx.
References bandExt_, and mineWd_.
Referenced by LsetCore_SetGridMtd().
int cvLevelSet::SetGridOrigin (double origin[])
Definition at line 248 of file cvLevelSet.cxx.
References origin_, and originValid_.
Referenced by LsetCore_SetGridMtd().
int cvLevelSet::SetGridSize (int gsize[])
Definition at line 214 of file cvLevelSet.cxx.
References gridx_, gridy_, and gridz_.
Referenced by LsetCore_SetGridMtd().
int cvLevelSet::SetGridSpacing (double hv[])
Definition at line 180 of file cvLevelSet.cxx.
References hx_, hy_, and hz_.
Referenced by LsetCore_SetGridMtd().
int cvLevelSet::SetGridType (GridT gt)
Definition at line 165 of file cvLevelSet.cxx.
References gridType_, and Invalid_GridT.
Referenced by LsetCore_SetGridMtd().
void cvLevelSet::SetSaveProjectionSets (int flag) inline
Definition at line 156 of file cvLevelSet.h.
References saveProjectionSets_.
Referenced by LsetCore_SetSaveProjectionSetsMtd().
int cvLevelSet::SetSeed (Seed_T * s)
Definition at line 364 of file cvLevelSet.cxx.
References DeallocateSeedObjs(), NULL, and seed_.
Referenced by LsetCore_SetCircleSeedMtd(), LsetCore_SetImageSeedMtd(), LsetCore_SetPdSeedMtd(), and LsetCore_SetSolidSeedMtd().
int cvLevelSet::SetSeed (cvPolyData * s)
Definition at line 398 of file cvLevelSet.cxx.
References DeallocateSeedObjs(), cvRepositoryData::GetName(), pdSeed_, and cvRepositoryData::SetName().
int cvLevelSet::SetSeed (cvSolidModel * s)
Definition at line 428 of file cvLevelSet.cxx.
References cvSolidModel::Copy(), DeallocateSeedObjs(), cvRepositoryData::GetName(), cvRepositoryData::SetName(), and smSeed_.
int cvLevelSet::SetSeed (cvStrPts * s, double thr)
Definition at line 457 of file cvLevelSet.cxx.
References DeallocateSeedObjs(), cvRepositoryData::GetName(), cvStrPts::GetVtkStructuredPoints(), imgSeed_, imgSeedThr_, and cvRepositoryData::SetName().
int cvLevelSet::SetSimTime (double simTime)
Definition at line 139 of file cvLevelSet.cxx.
References simTime_.
Referenced by LsetCore_SetTimeMtd().
void cvLevelSet::SetTimers (int flag) inline
Definition at line 148 of file cvLevelSet.h.
References timers_.
Referenced by LsetCore_SetTimersMtd().
int cvLevelSet::SetVExtension (ExtensionT etype)
Definition at line 945 of file cvLevelSet.cxx.
References CV_ERROR, CV_OK, etype_, and INVALID_V.
Referenced by LsetCore_SetVExtensionMtd().
int cvLevelSet::Status () inline
Definition at line 125 of file cvLevelSet.h.
References status_.
Referenced by LsetCore_EvolveOneTimeStepMtd(), and LsetCore_IsInitMtd().
int cvLevelSet::StopCondition () private
Definition at line 813 of file cvLevelSet.cxx.
References currTime_, dt_, cvLevelSetStructuredGrid::GetMaxF(), cvLevelSetStructuredGrid::GetMaxV(), cvLevelSetVelocity::GetStopV(), grid_, maxV_, simTime_, cvLevelSetVelocity::StopCondition(), and velocity_.
Referenced by EvolveOneTimeStep().
int cvLevelSet::UnlinkVelocity ()
Definition at line 522 of file cvLevelSet.cxx.
References CV_OK, cvLevelSetVelocity::ls_, NULL, and velocity_.
Referenced by LinkVelocity(), and cvLevelSetVelocity::~cvLevelSetVelocity().
int cvLevelSet::ValidSeedExists () private
Definition at line 349 of file cvLevelSet.cxx.
References imgSeed_, pdSeed_, seed_, and smSeed_.
Referenced by Init().
int cvLevelSet::Vanished () inline
Definition at line 137 of file cvLevelSet.h.
References zlsVanished_.
Referenced by LsetCore_VanishedMtd().
Friends And Related Function Documentation
friend class cvLevelSetVelocity friend
Definition at line 80 of file cvLevelSet.h.
Member Data Documentation
double cvLevelSet::bandExt_[2] private
Definition at line 189 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridBandParams(), Init(), and SetGridBandParams().
cvCPUTimer cvLevelSet::cpuTimer private
Definition at line 196 of file cvLevelSet.h.
Referenced by EvolveOneTimeStep(), ExtractActiveNodes(), ExtractCurvature(), ExtractFront(), ExtractPhi(), ExtractVectors(), GetTimerGranularity(), Init(), and RebuildPhi().
double cvLevelSet::currTime_ private
Definition at line 176 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), GetCurrTime(), Init(), and StopCondition().
double cvLevelSet::dt_ private
Definition at line 175 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), and StopCondition().
double cvLevelSet::dtFactor_ private
Definition at line 175 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), GetDtFactor(), and SetDtFactor().
ExtensionT cvLevelSet::etype_ private
Definition at line 179 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), GetVExtension(), and SetVExtension().
cvLevelSetStructuredGrid* cvLevelSet::grid_ private
Definition at line 163 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), ExtractActiveNodes(), ExtractCurvature(), ExtractFront(), ExtractPhi(), ExtractVectors(), GetGrid(), GetGridStatString(), GetMemoryUsage(), Init(), RebuildPhi(), StopCondition(), and ~cvLevelSet().
GridT cvLevelSet::gridType_ private
Definition at line 164 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridType(), Init(), and SetGridType().
int cvLevelSet::gridx_ private
Definition at line 186 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridSize(), Init(), and SetGridSize().
int cvLevelSet::gridy_ private
Definition at line 186 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridSize(), Init(), and SetGridSize().
int cvLevelSet::gridz_ private
Definition at line 186 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridSize(), Init(), and SetGridSize().
double cvLevelSet::hx_ private
Definition at line 185 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridSpacing(), Init(), and SetGridSpacing().
double cvLevelSet::hy_ private
Definition at line 185 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridSpacing(), Init(), and SetGridSpacing().
double cvLevelSet::hz_ private
Definition at line 185 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridSpacing(), Init(), and SetGridSpacing().
cvStrPts* cvLevelSet::imgSeed_ private
Definition at line 172 of file cvLevelSet.h.
Referenced by cvLevelSet(), DeallocateSeedObjs(), GetMemoryUsage(), GetSeed(), Init(), SetSeed(), and ValidSeedExists().
double cvLevelSet::imgSeedThr_ private
Definition at line 173 of file cvLevelSet.h.
Referenced by GetSeed(), Init(), and SetSeed().
double cvLevelSet::maxPhiIncr_ private
Definition at line 181 of file cvLevelSet.h.
Referenced by cvLevelSet(), and GetMaxPhiIncr().
double cvLevelSet::maxV_ private
Definition at line 182 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetMaxV(), and StopCondition().
double cvLevelSet::mineWd_ private
Definition at line 190 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridBandParams(), Init(), and SetGridBandParams().
double cvLevelSet::origin_[3] private
Definition at line 187 of file cvLevelSet.h.
Referenced by GetGridOrigin(), Init(), and SetGridOrigin().
int cvLevelSet::originValid_ private
Definition at line 188 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetGridOrigin(), Init(), and SetGridOrigin().
cvPolyData* cvLevelSet::pdSeed_ private
Definition at line 170 of file cvLevelSet.h.
Referenced by cvLevelSet(), DeallocateSeedObjs(), GetMemoryUsage(), GetSeed(), Init(), SetSeed(), and ValidSeedExists().
int cvLevelSet::rebuildPhiValid_ private
Definition at line 180 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), and RebuildPhi().
int cvLevelSet::saveProjectionSets_ private
Definition at line 197 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), and SetSaveProjectionSets().
Seed_T* cvLevelSet::seed_ private
Definition at line 169 of file cvLevelSet.h.
Referenced by cvLevelSet(), DeallocateSeedObjs(), GetMemoryUsage(), GetSeed(), Init(), SetSeed(), and ValidSeedExists().
double cvLevelSet::simTime_ private
Definition at line 176 of file cvLevelSet.h.
Referenced by cvLevelSet(), GetSimTime(), SetSimTime(), and StopCondition().
cvSolidModel* cvLevelSet::smSeed_ private
Definition at line 171 of file cvLevelSet.h.
Referenced by cvLevelSet(), DeallocateSeedObjs(), GetMemoryUsage(), GetSeed(), Init(), SetSeed(), and ValidSeedExists().
int cvLevelSet::status_ private
Definition at line 178 of file cvLevelSet.h.
Referenced by cvLevelSet(), Init(), and Status().
char cvLevelSet::tclName_[CV_STRLEN]
Definition at line 157 of file cvLevelSet.h.
Referenced by DeleteLsetCore(), EvolveOneTimeStep(), and LsetCore_NewCmd().
int cvLevelSet::timers_ private
Definition at line 195 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), ExtractActiveNodes(), ExtractCurvature(), ExtractFront(), ExtractPhi(), ExtractVectors(), GetTimers(), Init(), RebuildPhi(), and SetTimers().
int cvLevelSet::tn_ private
Definition at line 177 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), GetTimeStep(), Init(), and ResetTimeStep().
cvLevelSetVelocity* cvLevelSet::velocity_ private
Definition at line 165 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), GetMemoryUsage(), GetVelocity(), Init(), LinkVelocity(), StopCondition(), cvLevelSetVelocity::UnlinkLevelSet(), UnlinkVelocity(), and ~cvLevelSet().
int cvLevelSet::zlsVanished_ private
Definition at line 193 of file cvLevelSet.h.
Referenced by cvLevelSet(), EvolveOneTimeStep(), Init(), and Vanished().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSet.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSet.cxx