simvascular: a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType > Class Template Reference
a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType > Class Template Reference
#include <a2itk.h>
Public Member Functions
a2itk ()
~a2itk ()
int setInput1 (vtkStructuredPoints *img)
int setInput2 (vtkStructuredPoints *img)
vtkStructuredPoints * getOutput ()
int itkRegionOfInterestFilter (int starting[], int dimensions[])
int itkResampleFilter (double spacingParam, int dimensions[])
int itkMinMaxCurvFlowFilter (const unsigned int numIter, const long radius, const double timeStep)
int itkSigMapFilter (const double min, const double max, const double alpha, const double beta)
int itkFmmFilter (const double inputSeeds[SEEDS_ARRAY_MAX][3], int numSeeds, const double start, const double stop)
int itkThresholdLevelSet (const double upper, const double lower, const double propagationScaling, const double curvatureScaling, const int numIterations)
int createSignedDistanceImageWithFMM (int numSeeds, double *pts, double origin[3], double spacing[3], int dims[3], int start[3], double time)
int expNegativeImageFilter (double factor)
int shapeDetectionLevelSet (double propagationScaling, double curvatureScaling, double maxRMSerror, int maxNumIters)
Static Public Attributes
static const int SEEDS_ARRAY_MAX = 1024
Private Attributes
int dimension_
itk::Image< InputPixelType1,
Ta2itkDim >::Pointer input1_
itk::Image< InputPixelType2,
Ta2itkDim >::Pointer input2_
itk::Image< OutputPixelType,
Ta2itkDim >::Pointer output1_
Detailed Description
template<unsigned int Ta2itkDim, typename InputPixelType1 = float, typename InputPixelType2 = InputPixelType1, typename OutputPixelType = InputPixelType1>
class a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >
Definition at line 38 of file a2itk.h.
Constructor & Destructor Documentation
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::a2itk ()
Definition at line 109 of file a2itk.cxx.
References NULL.
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::~a2itk ()
Definition at line 117 of file a2itk.cxx.
Member Function Documentation
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::createSignedDistanceImageWithFMM (int numSeeds, double * pts, double origin[3], double spacing[3], int dims[3], int start[3], double time)
Definition at line 232 of file a2itk.cxx.
References CV_OK.
Referenced by gdscITK_createSignedDistanceImageWithFMMCmd().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::expNegativeImageFilter (double factor)
Definition at line 216 of file a2itk.cxx.
References CV_OK.
Referenced by gdscITK_expNegativeImageCmd().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > vtkStructuredPoints * a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput ()
Definition at line 162 of file a2itk.cxx.
References ConnectPipelines().
Referenced by FMMHelper(), gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_expNegativeImageCmd(), gdscITK_shapeDetectionCmd(), ReadRegionHelper(), SigMapHelper(), SmoothHelper(), and TLSFHelper().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkFmmFilter (const double inputSeeds[SEEDS_ARRAY_MAX][3], int numSeeds, const double start, const double stop)
Definition at line 529 of file a2itk.cxx.
References CV_OK.
Referenced by FMMHelper().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkMinMaxCurvFlowFilter (const unsigned int numIter, const long radius, const double timeStep)
Function: itkminMaxCurvFlowFilter
Uses an itk filter to smooth the image.
Definition at line 476 of file a2itk.cxx.
References CV_OK.
Referenced by SmoothHelper().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkRegionOfInterestFilter (int starting[], int dimensions[])
Method: itkRegionOfInterestFilter
Returns a specified region of interest
Parameters
starting[3] represents the x,y,z starting coordinates.
dimensions[3] represents the size of the x,y,z scales
requires input1_
Definition at line 375 of file a2itk.cxx.
References CV_OK.
Referenced by ReadRegionHelper().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkResampleFilter (double spacingParam, int dimensions[])
Method: itkResampleFilter
Resamples data according to spacingParam
Parameters
@param dimensions[3] represents the size of the x,y,z scales
requires input1_
Definition at line 412 of file a2itk.cxx.
References CV_OK.
Referenced by ReadRegionHelper().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkSigMapFilter (const double min, const double max, const double alpha, const double beta)
Function: itkSigMapFilter
Creates a mapping of the image according to a sigmoid curve.
Definition at line 498 of file a2itk.cxx.
References CV_OK.
Referenced by SigMapHelper().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkThresholdLevelSet (const double upper, const double lower, const double propagationScaling, const double curvatureScaling, const int numIterations)
Function: itkThresholdLevelSet
Completes a segmentation using the itk threshold level set segmentation filter. Expects input1_ to be the levelset input and input2_ to be the feature file.
Definition at line 582 of file a2itk.cxx.
References CV_OK.
Referenced by TLSFHelper().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput1 (vtkStructuredPoints * img)
Definition at line 125 of file a2itk.cxx.
References ConnectPipelines(), and CV_OK.
Referenced by FMMHelper(), gdscITK_expNegativeImageCmd(), gdscITK_shapeDetectionCmd(), ReadRegionHelper(), SigMapHelper(), SmoothHelper(), and TLSFHelper().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput2 (vtkStructuredPoints * img)
Definition at line 144 of file a2itk.cxx.
References ConnectPipelines(), and CV_OK.
Referenced by gdscITK_shapeDetectionCmd(), and TLSFHelper().
template<unsigned int Ta2itkDim, typename InputPixelType1 , typename InputPixelType2 , typename OutputPixelType > int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::shapeDetectionLevelSet (double propagationScaling, double curvatureScaling, double maxRMSerror, int maxNumIters)
Definition at line 341 of file a2itk.cxx.
References CV_OK.
Referenced by gdscITK_shapeDetectionCmd().
Member Data Documentation
template<unsigned int Ta2itkDim, typename InputPixelType1 = float, typename InputPixelType2 = InputPixelType1, typename OutputPixelType = InputPixelType1> int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::dimension_ private
Definition at line 119 of file a2itk.h.
template<unsigned int Ta2itkDim, typename InputPixelType1 = float, typename InputPixelType2 = InputPixelType1, typename OutputPixelType = InputPixelType1> itk::Image<InputPixelType1, Ta2itkDim>::Pointer a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::input1_ private
Definition at line 120 of file a2itk.h.
template<unsigned int Ta2itkDim, typename InputPixelType1 = float, typename InputPixelType2 = InputPixelType1, typename OutputPixelType = InputPixelType1> itk::Image<InputPixelType2, Ta2itkDim>::Pointer a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::input2_ private
Definition at line 121 of file a2itk.h.
template<unsigned int Ta2itkDim, typename InputPixelType1 = float, typename InputPixelType2 = InputPixelType1, typename OutputPixelType = InputPixelType1> itk::Image<OutputPixelType, Ta2itkDim>::Pointer a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::output1_ private
Definition at line 122 of file a2itk.h.
template<unsigned int Ta2itkDim, typename InputPixelType1 = float, typename InputPixelType2 = InputPixelType1, typename OutputPixelType = InputPixelType1> const int a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::SEEDS_ARRAY_MAX = 1024 static
Function: itkFmmFilter
Creates a signed distance image using FMM. Similar to createSignedDistanceImageWithFmm, but takes different parameters.
Definition at line 90 of file a2itk.h.
Referenced by FMMHelper().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/ITKCode/a2itk.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/ITKCode/a2itk.cxx