simvascular: vtkvmtkPolyDataSurfaceRemeshing Class Reference
vtkvmtkPolyDataSurfaceRemeshing Class Reference
#include <vtkvmtkPolyDataSurfaceRemeshing.h>
Public Types
enum {
SUCCESS = 0, EDGE_ON_BOUNDARY, EDGE_BETWEEN_ENTITIES, EDGE_LOCKED,
NOT_EDGE, NON_MANIFOLD, NOT_TRIANGLES, DEGENERATE_TRIANGLES,
TRIANGLE_LOCKED
}
enum { DO_CHANGE, DO_NOTHING }
enum { TARGET_AREA, TARGET_AREA_ARRAY }
enum { RELOCATE_SUCCESS, RELOCATE_FAILURE }
enum { INTERNAL_POINT, POINT_ON_BOUNDARY, NO_NEIGHBORS }
Public Member Functions
vtkTypeMacro (vtkvmtkPolyDataSurfaceRemeshing, vtkPolyDataAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
vtkSetMacro (AspectRatioThreshold, double)
vtkGetMacro (AspectRatioThreshold, double)
vtkSetMacro (InternalAngleTolerance, double)
vtkGetMacro (InternalAngleTolerance, double)
vtkSetMacro (NormalAngleTolerance, double)
vtkGetMacro (NormalAngleTolerance, double)
vtkSetMacro (CollapseAngleThreshold, double)
vtkGetMacro (CollapseAngleThreshold, double)
vtkSetMacro (Relaxation, double)
vtkGetMacro (Relaxation, double)
vtkSetMacro (TargetArea, double)
vtkGetMacro (TargetArea, double)
vtkSetMacro (TargetAreaFactor, double)
vtkGetMacro (TargetAreaFactor, double)
vtkSetMacro (TriangleSplitFactor, double)
vtkGetMacro (TriangleSplitFactor, double)
vtkSetMacro (MinAreaFactor, double)
vtkGetMacro (MinAreaFactor, double)
vtkSetMacro (MaxArea, double)
vtkGetMacro (MaxArea, double)
vtkSetMacro (MinArea, double)
vtkGetMacro (MinArea, double)
vtkSetMacro (NumberOfIterations, int)
vtkGetMacro (NumberOfIterations, int)
vtkSetMacro (NumberOfConnectivityOptimizationIterations, int)
vtkGetMacro (NumberOfConnectivityOptimizationIterations, int)
vtkSetStringMacro (TargetAreaArrayName)
vtkGetStringMacro (TargetAreaArrayName)
vtkSetMacro (ElementSizeMode, int)
vtkGetMacro (ElementSizeMode, int)
void SetElementSizeModeToTargetArea ()
void SetElementSizeModeToTargetAreaArray ()
vtkSetMacro (PreserveBoundaryEdges, int)
vtkGetMacro (PreserveBoundaryEdges, int)
vtkBooleanMacro (PreserveBoundaryEdges, int)
vtkSetStringMacro (CellEntityIdsArrayName)
vtkGetStringMacro (CellEntityIdsArrayName)
vtkSetObjectMacro (ExcludedEntityIds, vtkIdList)
vtkGetObjectMacro (ExcludedEntityIds, vtkIdList)
Static Public Member Functions
static
vtkvmtkPolyDataSurfaceRemeshing * New ()
Protected Member Functions
vtkvmtkPolyDataSurfaceRemeshing ()
~vtkvmtkPolyDataSurfaceRemeshing ()
virtual int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
void BuildEntityBoundary (vtkPolyData *input, vtkPolyData *entityBoundary)
int EdgeFlipConnectivityOptimizationIteration ()
int EdgeFlipIteration ()
int EdgeCollapseIteration ()
int TriangleSplitIteration ()
int EdgeSplitIteration ()
int PointRelocationIteration (bool projectToSurface=true)
int TestFlipEdgeValidity (vtkIdType pt1, vtkIdType pt2, vtkIdType cell1, vtkIdType cell2, vtkIdType pt3, vtkIdType pt4)
int TestConnectivityFlipEdge (vtkIdType pt1, vtkIdType pt2)
int TestDelaunayFlipEdge (vtkIdType pt1, vtkIdType pt2)
int TestAspectRatioCollapseEdge (vtkIdType cellId, vtkIdType &pt1, vtkIdType &pt2)
int TestTriangleSplit (vtkIdType cellId)
int TestAreaSplitEdge (vtkIdType cellId, vtkIdType &pt1, vtkIdType &pt2)
int IsElementExcluded (vtkIdType cellId)
int GetEdgeCellsAndOppositeEdge (vtkIdType pt1, vtkIdType pt2, vtkIdType &cell1, vtkIdType &cell2, vtkIdType &pt3, vtkIdType &pt4)
int SplitEdge (vtkIdType pt1, vtkIdType pt2)
int CollapseEdge (vtkIdType pt1, vtkIdType pt2)
int FlipEdge (vtkIdType pt1, vtkIdType pt2)
int SplitTriangle (vtkIdType cellId)
int CollapseTriangle (vtkIdType cellId)
int RelocatePoint (vtkIdType pointId, bool projectToSurface)
int IsPointOnBoundary (vtkIdType pointId)
int IsPointOnEntityBoundary (vtkIdType pointId)
int GetNumberOfBoundaryEdges (vtkIdType cellId)
double ComputeTriangleTargetArea (vtkIdType cellId)
int FindOneRingNeighbors (vtkIdType pointId, vtkIdList *neighborIds)
Protected Attributes
vtkPolyData * Mesh
vtkPolyData * InputBoundary
vtkPolyData * InputEntityBoundary
vtkCellLocator * Locator
vtkCellLocator * BoundaryLocator
vtkCellLocator * EntityBoundaryLocator
vtkIntArray * CellEntityIdsArray
vtkDataArray * TargetAreaArray
vtkIdList * ExcludedEntityIds
double AspectRatioThreshold
double InternalAngleTolerance
double NormalAngleTolerance
double CollapseAngleThreshold
double Relaxation
int NumberOfConnectivityOptimizationIterations
int NumberOfIterations
int PreserveBoundaryEdges
int ElementSizeMode
double TargetArea
double TargetAreaFactor
double MaxArea
double MinArea
double MinAreaFactor
double TriangleSplitFactor
char * TargetAreaArrayName
char * CellEntityIdsArrayName
Private Member Functions
vtkvmtkPolyDataSurfaceRemeshing (const vtkvmtkPolyDataSurfaceRemeshing &)
void operator= (const vtkvmtkPolyDataSurfaceRemeshing &)
Detailed Description
Definition at line 36 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Member Enumeration Documentation
anonymous enum
Enumerator
SUCCESS
EDGE_ON_BOUNDARY
EDGE_BETWEEN_ENTITIES
EDGE_LOCKED
NOT_EDGE
NON_MANIFOLD
NOT_TRIANGLES
DEGENERATE_TRIANGLES
TRIANGLE_LOCKED
Definition at line 104 of file vtkvmtkPolyDataSurfaceRemeshing.h.
anonymous enum
Enumerator
DO_CHANGE
DO_NOTHING
Definition at line 116 of file vtkvmtkPolyDataSurfaceRemeshing.h.
anonymous enum
Enumerator
TARGET_AREA
TARGET_AREA_ARRAY
Definition at line 121 of file vtkvmtkPolyDataSurfaceRemeshing.h.
anonymous enum
Enumerator
RELOCATE_SUCCESS
RELOCATE_FAILURE
Definition at line 126 of file vtkvmtkPolyDataSurfaceRemeshing.h.
anonymous enum
Enumerator
INTERNAL_POINT
POINT_ON_BOUNDARY
NO_NEIGHBORS
Definition at line 131 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Constructor & Destructor Documentation
vtkvmtkPolyDataSurfaceRemeshing::vtkvmtkPolyDataSurfaceRemeshing () protected
Definition at line 41 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References AspectRatioThreshold, BoundaryLocator, CellEntityIdsArray, CellEntityIdsArrayName, CollapseAngleThreshold, ElementSizeMode, EntityBoundaryLocator, ExcludedEntityIds, InputBoundary, InputEntityBoundary, InternalAngleTolerance, Locator, MaxArea, Mesh, MinArea, MinAreaFactor, NormalAngleTolerance, NULL, NumberOfConnectivityOptimizationIterations, NumberOfIterations, PreserveBoundaryEdges, Relaxation, TARGET_AREA, TargetArea, TargetAreaArray, TargetAreaArrayName, TargetAreaFactor, TriangleSplitFactor, and VTK_VMTK_LARGE_FLOAT.
vtkvmtkPolyDataSurfaceRemeshing::~vtkvmtkPolyDataSurfaceRemeshing () protected
Definition at line 73 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References BoundaryLocator, CellEntityIdsArray, CellEntityIdsArrayName, EntityBoundaryLocator, ExcludedEntityIds, InputBoundary, InputEntityBoundary, Locator, Mesh, NULL, and TargetAreaArrayName.
vtkvmtkPolyDataSurfaceRemeshing::vtkvmtkPolyDataSurfaceRemeshing (const vtkvmtkPolyDataSurfaceRemeshing &) private
Member Function Documentation
void vtkvmtkPolyDataSurfaceRemeshing::BuildEntityBoundary (vtkPolyData * input, vtkPolyData * entityBoundary) protected
Definition at line 386 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References CellEntityIdsArray.
Referenced by RequestData().
int vtkvmtkPolyDataSurfaceRemeshing::CollapseEdge (vtkIdType pt1, vtkIdType pt2) protected
Definition at line 1247 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References CellEntityIdsArray, EDGE_BETWEEN_ENTITIES, EDGE_LOCKED, EDGE_ON_BOUNDARY, GetEdgeCellsAndOppositeEdge(), IsElementExcluded(), IsPointOnBoundary(), IsPointOnEntityBoundary(), Mesh, PreserveBoundaryEdges, and SUCCESS.
Referenced by EdgeCollapseIteration().
int vtkvmtkPolyDataSurfaceRemeshing::CollapseTriangle (vtkIdType cellId) protected
Definition at line 1126 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
double vtkvmtkPolyDataSurfaceRemeshing::ComputeTriangleTargetArea (vtkIdType cellId) protected
Definition at line 1587 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References ElementSizeMode, Locator, MaxArea, Mesh, MinArea, NULL, TARGET_AREA, TARGET_AREA_ARRAY, TargetArea, TargetAreaArray, and TargetAreaFactor.
Referenced by TestAreaSplitEdge(), TestAspectRatioCollapseEdge(), and TestTriangleSplit().
int vtkvmtkPolyDataSurfaceRemeshing::EdgeCollapseIteration () protected
Definition at line 550 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References CollapseEdge(), DO_NOTHING, Mesh, and TestAspectRatioCollapseEdge().
Referenced by RequestData().
int vtkvmtkPolyDataSurfaceRemeshing::EdgeFlipConnectivityOptimizationIteration () protected
Definition at line 487 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References DO_NOTHING, FlipEdge(), Mesh, and TestConnectivityFlipEdge().
Referenced by RequestData().
int vtkvmtkPolyDataSurfaceRemeshing::EdgeFlipIteration () protected
Definition at line 519 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References DO_NOTHING, FlipEdge(), Mesh, and TestDelaunayFlipEdge().
Referenced by RequestData().
int vtkvmtkPolyDataSurfaceRemeshing::EdgeSplitIteration () protected
Definition at line 572 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References DO_NOTHING, Mesh, SplitEdge(), and TestAreaSplitEdge().
Referenced by RequestData().
int vtkvmtkPolyDataSurfaceRemeshing::FindOneRingNeighbors (vtkIdType pointId, vtkIdList * neighborIds) protected
Definition at line 681 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References INTERNAL_POINT, Mesh, NO_NEIGHBORS, NULL, and POINT_ON_BOUNDARY.
Referenced by RelocatePoint().
int vtkvmtkPolyDataSurfaceRemeshing::FlipEdge (vtkIdType pt1, vtkIdType pt2) protected
Definition at line 1365 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References CellEntityIdsArray, EDGE_LOCKED, GetEdgeCellsAndOppositeEdge(), IsElementExcluded(), Mesh, and SUCCESS.
Referenced by EdgeFlipConnectivityOptimizationIteration(), and EdgeFlipIteration().
int vtkvmtkPolyDataSurfaceRemeshing::GetEdgeCellsAndOppositeEdge (vtkIdType pt1, vtkIdType pt2, vtkIdType & cell1, vtkIdType & cell2, vtkIdType & pt3, vtkIdType & pt4) protected
Definition at line 957 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References CellEntityIdsArray, DEGENERATE_TRIANGLES, EDGE_BETWEEN_ENTITIES, EDGE_ON_BOUNDARY, Mesh, NON_MANIFOLD, NOT_EDGE, NOT_TRIANGLES, and SUCCESS.
Referenced by CollapseEdge(), FlipEdge(), SplitEdge(), TestAreaSplitEdge(), TestAspectRatioCollapseEdge(), TestConnectivityFlipEdge(), and TestDelaunayFlipEdge().
int vtkvmtkPolyDataSurfaceRemeshing::GetNumberOfBoundaryEdges (vtkIdType cellId) protected
Definition at line 435 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References Mesh.
Referenced by RequestData().
int vtkvmtkPolyDataSurfaceRemeshing::IsElementExcluded (vtkIdType cellId) protected
Definition at line 630 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References CellEntityIdsArray, ExcludedEntityIds, and NULL.
Referenced by CollapseEdge(), FlipEdge(), RelocatePoint(), SplitEdge(), and SplitTriangle().
int vtkvmtkPolyDataSurfaceRemeshing::IsPointOnBoundary (vtkIdType pointId) protected
Definition at line 456 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References Mesh.
Referenced by CollapseEdge().
int vtkvmtkPolyDataSurfaceRemeshing::IsPointOnEntityBoundary (vtkIdType pointId) protected
Definition at line 646 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References CellEntityIdsArray, and Mesh.
Referenced by CollapseEdge(), and RelocatePoint().
static vtkvmtkPolyDataSurfaceRemeshing* vtkvmtkPolyDataSurfaceRemeshing::New () static
void vtkvmtkPolyDataSurfaceRemeshing::operator= (const vtkvmtkPolyDataSurfaceRemeshing &) private
int vtkvmtkPolyDataSurfaceRemeshing::PointRelocationIteration (bool projectToSurface = true) protected
Definition at line 615 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References Mesh, RELOCATE_FAILURE, RELOCATE_SUCCESS, and RelocatePoint().
Referenced by RequestData().
void vtkvmtkPolyDataSurfaceRemeshing::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 1881 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
int vtkvmtkPolyDataSurfaceRemeshing::RelocatePoint (vtkIdType pointId, bool projectToSurface) protected
Definition at line 807 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References BoundaryLocator, vtkvmtkPolyDataUmbrellaStencil::Build(), EntityBoundaryLocator, FindOneRingNeighbors(), vtkvmtkNeighborhood::GetNumberOfPoints(), vtkvmtkNeighborhood::GetPointId(), vtkvmtkStencil::GetWeight(), INTERNAL_POINT, IsElementExcluded(), IsPointOnEntityBoundary(), Locator, Mesh, vtkvmtkPolyDataUmbrellaStencil::New(), point, Relaxation, RELOCATE_SUCCESS, and vtkvmtkDataSetItem::SetDataSet().
Referenced by PointRelocationIteration().
int vtkvmtkPolyDataSurfaceRemeshing::RequestData (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected virtual
Definition at line 136 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References BoundaryLocator, BuildEntityBoundary(), CellEntityIdsArray, CellEntityIdsArrayName, Dot(), EdgeCollapseIteration(), EdgeFlipConnectivityOptimizationIteration(), EdgeFlipIteration(), EdgeSplitIteration(), ElementSizeMode, EntityBoundaryLocator, GetNumberOfBoundaryEdges(), input(), InputBoundary, InputEntityBoundary, Locator, Mesh, vtkvmtkPolyDataBoundaryExtractor::New(), NULL, NumberOfConnectivityOptimizationIterations, NumberOfIterations, PointRelocationIteration(), RELOCATE_FAILURE, RELOCATE_SUCCESS, TARGET_AREA_ARRAY, TargetAreaArray, TargetAreaArrayName, and TriangleSplitIteration().
void vtkvmtkPolyDataSurfaceRemeshing::SetElementSizeModeToTargetArea () inline
Definition at line 88 of file vtkvmtkPolyDataSurfaceRemeshing.h.
void vtkvmtkPolyDataSurfaceRemeshing::SetElementSizeModeToTargetAreaArray () inline
Definition at line 90 of file vtkvmtkPolyDataSurfaceRemeshing.h.
int vtkvmtkPolyDataSurfaceRemeshing::SplitEdge (vtkIdType pt1, vtkIdType pt2) protected
Definition at line 1132 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References BoundaryLocator, CellEntityIdsArray, EDGE_BETWEEN_ENTITIES, EDGE_LOCKED, EDGE_ON_BOUNDARY, EntityBoundaryLocator, GetEdgeCellsAndOppositeEdge(), IsElementExcluded(), Locator, Mesh, PreserveBoundaryEdges, and SUCCESS.
Referenced by EdgeSplitIteration().
int vtkvmtkPolyDataSurfaceRemeshing::SplitTriangle (vtkIdType cellId) protected
Definition at line 1070 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References CellEntityIdsArray, IsElementExcluded(), Locator, Mesh, NOT_TRIANGLES, SUCCESS, and TRIANGLE_LOCKED.
Referenced by TriangleSplitIteration().
int vtkvmtkPolyDataSurfaceRemeshing::TestAreaSplitEdge (vtkIdType cellId, vtkIdType & pt1, vtkIdType & pt2) protected
Definition at line 1806 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References ComputeTriangleTargetArea(), DO_CHANGE, DO_NOTHING, EDGE_BETWEEN_ENTITIES, EDGE_ON_BOUNDARY, GetEdgeCellsAndOppositeEdge(), Mesh, PreserveBoundaryEdges, and SUCCESS.
Referenced by EdgeSplitIteration().
int vtkvmtkPolyDataSurfaceRemeshing::TestAspectRatioCollapseEdge (vtkIdType cellId, vtkIdType & pt1, vtkIdType & pt2) protected
Definition at line 1663 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References AspectRatioThreshold, CollapseAngleThreshold, ComputeTriangleTargetArea(), DO_CHANGE, DO_NOTHING, Dot(), EDGE_BETWEEN_ENTITIES, EDGE_ON_BOUNDARY, GetEdgeCellsAndOppositeEdge(), Mesh, MinAreaFactor, PreserveBoundaryEdges, and SUCCESS.
Referenced by EdgeCollapseIteration().
int vtkvmtkPolyDataSurfaceRemeshing::TestConnectivityFlipEdge (vtkIdType pt1, vtkIdType pt2) protected
Definition at line 1477 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References DO_CHANGE, DO_NOTHING, GetEdgeCellsAndOppositeEdge(), Mesh, SUCCESS, and TestFlipEdgeValidity().
Referenced by EdgeFlipConnectivityOptimizationIteration().
int vtkvmtkPolyDataSurfaceRemeshing::TestDelaunayFlipEdge (vtkIdType pt1, vtkIdType pt2) protected
Definition at line 1514 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References DO_CHANGE, DO_NOTHING, Dot(), GetEdgeCellsAndOppositeEdge(), InternalAngleTolerance, Mesh, SUCCESS, and TestFlipEdgeValidity().
Referenced by EdgeFlipIteration().
int vtkvmtkPolyDataSurfaceRemeshing::TestFlipEdgeValidity (vtkIdType pt1, vtkIdType pt2, vtkIdType cell1, vtkIdType cell2, vtkIdType pt3, vtkIdType pt4) protected
Definition at line 1425 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References DO_CHANGE, DO_NOTHING, Dot(), Mesh, and NormalAngleTolerance.
Referenced by TestConnectivityFlipEdge(), and TestDelaunayFlipEdge().
int vtkvmtkPolyDataSurfaceRemeshing::TestTriangleSplit (vtkIdType cellId) protected
Definition at line 1634 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References ComputeTriangleTargetArea(), DO_CHANGE, DO_NOTHING, Mesh, and TriangleSplitFactor.
Referenced by TriangleSplitIteration().
int vtkvmtkPolyDataSurfaceRemeshing::TriangleSplitIteration () protected
Definition at line 594 of file vtkvmtkPolyDataSurfaceRemeshing.cxx.
References DO_NOTHING, Mesh, SplitTriangle(), and TestTriangleSplit().
Referenced by RequestData().
vtkvmtkPolyDataSurfaceRemeshing::vtkBooleanMacro (PreserveBoundaryEdges , int)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (AspectRatioThreshold , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (InternalAngleTolerance , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (NormalAngleTolerance , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (CollapseAngleThreshold , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (Relaxation , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (TargetArea , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (TargetAreaFactor , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (TriangleSplitFactor , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (MinAreaFactor , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (MaxArea , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (MinArea , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (NumberOfIterations , int)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (NumberOfConnectivityOptimizationIterations , int)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (ElementSizeMode , int)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetMacro (PreserveBoundaryEdges , int)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetObjectMacro (ExcludedEntityIds , vtkIdList)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetStringMacro (TargetAreaArrayName)
vtkvmtkPolyDataSurfaceRemeshing::vtkGetStringMacro (CellEntityIdsArrayName)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (AspectRatioThreshold , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (InternalAngleTolerance , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (NormalAngleTolerance , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (CollapseAngleThreshold , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (Relaxation , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (TargetArea , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (TargetAreaFactor , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (TriangleSplitFactor , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (MinAreaFactor , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (MaxArea , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (MinArea , double)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (NumberOfIterations , int)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (NumberOfConnectivityOptimizationIterations , int)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (ElementSizeMode , int)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetMacro (PreserveBoundaryEdges , int)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetObjectMacro (ExcludedEntityIds , vtkIdList)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetStringMacro (TargetAreaArrayName)
vtkvmtkPolyDataSurfaceRemeshing::vtkSetStringMacro (CellEntityIdsArrayName)
vtkvmtkPolyDataSurfaceRemeshing::vtkTypeMacro (vtkvmtkPolyDataSurfaceRemeshing , vtkPolyDataAlgorithm)
Member Data Documentation
double vtkvmtkPolyDataSurfaceRemeshing::AspectRatioThreshold protected
Definition at line 191 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by TestAspectRatioCollapseEdge(), and vtkvmtkPolyDataSurfaceRemeshing().
vtkCellLocator* vtkvmtkPolyDataSurfaceRemeshing::BoundaryLocator protected
Definition at line 185 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by RelocatePoint(), RequestData(), SplitEdge(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
vtkIntArray* vtkvmtkPolyDataSurfaceRemeshing::CellEntityIdsArray protected
Definition at line 187 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by BuildEntityBoundary(), CollapseEdge(), FlipEdge(), GetEdgeCellsAndOppositeEdge(), IsElementExcluded(), IsPointOnEntityBoundary(), RequestData(), SplitEdge(), SplitTriangle(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
char* vtkvmtkPolyDataSurfaceRemeshing::CellEntityIdsArrayName protected
Definition at line 210 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by RequestData(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::CollapseAngleThreshold protected
Definition at line 194 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by TestAspectRatioCollapseEdge(), and vtkvmtkPolyDataSurfaceRemeshing().
int vtkvmtkPolyDataSurfaceRemeshing::ElementSizeMode protected
Definition at line 201 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by ComputeTriangleTargetArea(), RequestData(), and vtkvmtkPolyDataSurfaceRemeshing().
vtkCellLocator* vtkvmtkPolyDataSurfaceRemeshing::EntityBoundaryLocator protected
Definition at line 186 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by RelocatePoint(), RequestData(), SplitEdge(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
vtkIdList* vtkvmtkPolyDataSurfaceRemeshing::ExcludedEntityIds protected
Definition at line 189 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by IsElementExcluded(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
vtkPolyData* vtkvmtkPolyDataSurfaceRemeshing::InputBoundary protected
Definition at line 182 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by RequestData(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
vtkPolyData* vtkvmtkPolyDataSurfaceRemeshing::InputEntityBoundary protected
Definition at line 183 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by RequestData(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::InternalAngleTolerance protected
Definition at line 192 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by TestDelaunayFlipEdge(), and vtkvmtkPolyDataSurfaceRemeshing().
vtkCellLocator* vtkvmtkPolyDataSurfaceRemeshing::Locator protected
Definition at line 184 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by ComputeTriangleTargetArea(), RelocatePoint(), RequestData(), SplitEdge(), SplitTriangle(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::MaxArea protected
Definition at line 204 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by ComputeTriangleTargetArea(), and vtkvmtkPolyDataSurfaceRemeshing().
vtkPolyData* vtkvmtkPolyDataSurfaceRemeshing::Mesh protected
Definition at line 181 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by CollapseEdge(), ComputeTriangleTargetArea(), EdgeCollapseIteration(), EdgeFlipConnectivityOptimizationIteration(), EdgeFlipIteration(), EdgeSplitIteration(), FindOneRingNeighbors(), FlipEdge(), GetEdgeCellsAndOppositeEdge(), GetNumberOfBoundaryEdges(), IsPointOnBoundary(), IsPointOnEntityBoundary(), PointRelocationIteration(), RelocatePoint(), RequestData(), SplitEdge(), SplitTriangle(), TestAreaSplitEdge(), TestAspectRatioCollapseEdge(), TestConnectivityFlipEdge(), TestDelaunayFlipEdge(), TestFlipEdgeValidity(), TestTriangleSplit(), TriangleSplitIteration(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::MinArea protected
Definition at line 205 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by ComputeTriangleTargetArea(), and vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::MinAreaFactor protected
Definition at line 206 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by TestAspectRatioCollapseEdge(), and vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::NormalAngleTolerance protected
Definition at line 193 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by TestFlipEdgeValidity(), and vtkvmtkPolyDataSurfaceRemeshing().
int vtkvmtkPolyDataSurfaceRemeshing::NumberOfConnectivityOptimizationIterations protected
Definition at line 196 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by RequestData(), and vtkvmtkPolyDataSurfaceRemeshing().
int vtkvmtkPolyDataSurfaceRemeshing::NumberOfIterations protected
Definition at line 197 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by RequestData(), and vtkvmtkPolyDataSurfaceRemeshing().
int vtkvmtkPolyDataSurfaceRemeshing::PreserveBoundaryEdges protected
Definition at line 199 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by CollapseEdge(), SplitEdge(), TestAreaSplitEdge(), TestAspectRatioCollapseEdge(), and vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::Relaxation protected
Definition at line 195 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by RelocatePoint(), and vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::TargetArea protected
Definition at line 202 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by ComputeTriangleTargetArea(), and vtkvmtkPolyDataSurfaceRemeshing().
vtkDataArray* vtkvmtkPolyDataSurfaceRemeshing::TargetAreaArray protected
Definition at line 188 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by ComputeTriangleTargetArea(), RequestData(), and vtkvmtkPolyDataSurfaceRemeshing().
char* vtkvmtkPolyDataSurfaceRemeshing::TargetAreaArrayName protected
Definition at line 208 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by RequestData(), vtkvmtkPolyDataSurfaceRemeshing(), and ~vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::TargetAreaFactor protected
Definition at line 203 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by ComputeTriangleTargetArea(), and vtkvmtkPolyDataSurfaceRemeshing().
double vtkvmtkPolyDataSurfaceRemeshing::TriangleSplitFactor protected
Definition at line 207 of file vtkvmtkPolyDataSurfaceRemeshing.h.
Referenced by TestTriangleSplit(), and vtkvmtkPolyDataSurfaceRemeshing().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkPolyDataSurfaceRemeshing.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkPolyDataSurfaceRemeshing.cxx