simvascular: Input Class Reference
Input Class Reference
#include <Input.h>
Public Member Functions
Input (const string &)
Input (const char *)
~Input ()
map< string, string > InputMap () const
ValType GetValue (const string &, const string &, bool, bool) const
void EchoInputMap (const ostream &ofile)
Private Member Functions
void trim_string (string *str)
void get_input_lines (vector< string > *, ifstream &)
void build_map (map< string, string > *, vector< string > *)
Private Attributes
map< string, string > * input_map
map< string, string > * default_map
vector< string > * input_text
vector< string > * default_text
Detailed Description
Definition at line 54 of file Input.h.
Constructor & Destructor Documentation
Input::Input (const string & fname)
Definition at line 99 of file Cinput.cxx.
References build_map(), default_map, default_text, get_input_lines(), input_map, input_text, iter, and myrank.
Input::Input (const char *)
Input::~Input ()
Definition at line 226 of file Cinput.cxx.
References input_map, and input_text.
Member Function Documentation
void Input::build_map (map< string, string > * inmap, vector< string > * intext) private
Definition at line 265 of file Cinput.cxx.
References trim_string().
Referenced by Input().
void Input::EchoInputMap (const ostream & ofile)
Definition at line 240 of file Cinput.cxx.
References input_map, iter, and myrank.
void Input::get_input_lines (vector< string > * text, ifstream & infile) private
Definition at line 252 of file Cinput.cxx.
Referenced by Input().
ValType Input::GetValue (const string & str, const string & default_value, bool required, bool printout) const
Definition at line 57 of file Cinput.cxx.
References input_map, and myrank.
Referenced by input_fform().
map< string, string > Input::InputMap () const
Definition at line 234 of file Cinput.cxx.
References input_map.
void Input::trim_string (string * str) private
Definition at line 301 of file Cinput.cxx.
Referenced by build_map().
Member Data Documentation
map<string,string>* Input::default_map private
Definition at line 80 of file Input.h.
Referenced by Input().
vector<string>* Input::default_text private
Definition at line 83 of file Input.h.
Referenced by Input().
map<string,string>* Input::input_map private
Definition at line 79 of file Input.h.
Referenced by EchoInputMap(), GetValue(), Input(), InputMap(), and ~Input().
vector<string>* Input::input_text private
Definition at line 82 of file Input.h.
Referenced by Input(), and ~Input().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/IncompressibleSolver/Solver/Input.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/IncompressibleSolver/Solver/Cinput.cxx