simvascular: cvDataSet Class Reference
cvDataSet Class Reference
#include <cvDataSet.h>
Public Member Functions
cvDataSet (RepositoryDataT type)
~cvDataSet ()
Public Member Functions inherited from cvDataObject
cvDataObject (RepositoryDataT type)
virtual ~cvDataObject ()
vtkDataObject * GetVtkPtr ()
virtual int GetMemoryUsage ()
Public Member Functions inherited from cvRepositoryData
cvRepositoryData (RepositoryDataT type)
virtual ~cvRepositoryData ()
void Lock ()
void Release ()
int NumLocks ()
RepositoryDataT GetType ()
char * GetName ()
void SetName (char *in)
int GetNumLabels ()
void GetLabelKeys (int *numKeys, char **keys[])
int IsLabelPresent (char *key)
int GetLabel (char *key, char **value)
int SetLabel (char *key, char *value)
void ClearLabel (char *key)
Protected Member Functions
void ShallowCopy (vtkDataSet *src)
Additional Inherited Members
Protected Attributes inherited from cvDataObject
vtkDataObject * data_
Detailed Description
Definition at line 40 of file cvDataSet.h.
Constructor & Destructor Documentation
cvDataSet::cvDataSet (RepositoryDataT type)
Definition at line 36 of file cvDataSet.cxx.
cvDataSet::~cvDataSet ()
Definition at line 44 of file cvDataSet.cxx.
Member Function Documentation
void cvDataSet::ShallowCopy (vtkDataSet * src) protected
Definition at line 56 of file cvDataSet.cxx.
References cvDataObject::data_, and NULL.
Referenced by cvPolyData::cvPolyData(), cvStrPts::cvStrPts(), and cvUnstructuredGrid::cvUnstructuredGrid().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvDataSet.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvDataSet.cxx