simvascular: vtkIntegrateFlowThroughSurface Class Reference
vtkIntegrateFlowThroughSurface Class Reference
#include <vtkIntegrateFlowThroughSurface.h>
Public Member Functions
vtkTypeMacro (vtkIntegrateFlowThroughSurface, vtkUnstructuredGridAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
Static Public Member Functions
static
vtkIntegrateFlowThroughSurface * New ()
Protected Member Functions
vtkIntegrateFlowThroughSurface ()
~vtkIntegrateFlowThroughSurface ()
virtual int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
virtual int RequestUpdateExtent (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
virtual int FillInputPortInformation (int port, vtkInformation *info)
virtual vtkExecutive * CreateDefaultExecutive ()
vtkDataSet * GenerateSurfaceVectors (vtkDataSet *input)
Private Member Functions
vtkIntegrateFlowThroughSurface (const vtkIntegrateFlowThroughSurface &)
void operator= (const vtkIntegrateFlowThroughSurface &)
Detailed Description
Definition at line 30 of file vtkIntegrateFlowThroughSurface.h.
Constructor & Destructor Documentation
vtkIntegrateFlowThroughSurface::vtkIntegrateFlowThroughSurface () protected
Definition at line 37 of file vtkIntegrateFlowThroughSurface.cxx.
vtkIntegrateFlowThroughSurface::~vtkIntegrateFlowThroughSurface () protected
Definition at line 45 of file vtkIntegrateFlowThroughSurface.cxx.
vtkIntegrateFlowThroughSurface::vtkIntegrateFlowThroughSurface (const vtkIntegrateFlowThroughSurface &) private
Member Function Documentation
vtkExecutive * vtkIntegrateFlowThroughSurface::CreateDefaultExecutive () protected virtual
Definition at line 186 of file vtkIntegrateFlowThroughSurface.cxx.
int vtkIntegrateFlowThroughSurface::FillInputPortInformation (int port, vtkInformation * info) protected virtual
Definition at line 198 of file vtkIntegrateFlowThroughSurface.cxx.
vtkDataSet * vtkIntegrateFlowThroughSurface::GenerateSurfaceVectors (vtkDataSet * input) protected
Definition at line 67 of file vtkIntegrateFlowThroughSurface.cxx.
References vtkSurfaceVectors::New(), and vtkSurfaceVectors::SetConstraintModeToPerpendicularScale().
Referenced by RequestData().
static vtkIntegrateFlowThroughSurface* vtkIntegrateFlowThroughSurface::New () static
Referenced by sys_geom_IntegrateSurface2().
void vtkIntegrateFlowThroughSurface::operator= (const vtkIntegrateFlowThroughSurface &) private
void vtkIntegrateFlowThroughSurface::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 192 of file vtkIntegrateFlowThroughSurface.cxx.
int vtkIntegrateFlowThroughSurface::RequestData (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected virtual
Definition at line 99 of file vtkIntegrateFlowThroughSurface.cxx.
References GenerateSurfaceVectors(), input(), iter, and vtkIntegrateAttributes::New().
int vtkIntegrateFlowThroughSurface::RequestUpdateExtent (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected virtual
Definition at line 50 of file vtkIntegrateFlowThroughSurface.cxx.
vtkIntegrateFlowThroughSurface::vtkTypeMacro (vtkIntegrateFlowThroughSurface , vtkUnstructuredGridAlgorithm)
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkIntegrateFlowThroughSurface.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkIntegrateFlowThroughSurface.cxx