simvascular: cvCalculateWallShearStress Class Reference
cvCalculateWallShearStress Class Reference
#include <cvCalculateWallShearStress.h>
Public Member Functions
cvCalculateWallShearStress ()
~cvCalculateWallShearStress ()
int SetSurfaceMesh (cvPolyData *surfaceMesh)
int SetTensors (cvPolyData *tensors)
int SetTractions (cvPolyData *tractions)
int CalcWallShearFromStresses ()
int CalcWallShearFromTractions ()
cvPolyData * CalcWallShearMean (int numPds, cvPolyData **shearPds)
cvPolyData * CalcWallShearPulse (int numPds, cvPolyData **shearPds)
cvPolyData * CalcOSI (cvPolyData *shearMean, cvPolyData *shearPulse)
cvPolyData * GetWallShear ()
cvPolyData * CalcAvgPointData (int numPds, cvPolyData **inputPds)
Private Attributes
vtkPolyData * surfaceMesh_
vtkPolyData * tensors_
vtkPolyData * tractions_
vtkFloatingPointArrayType * wallshear_
Detailed Description
Definition at line 44 of file cvCalculateWallShearStress.h.
Constructor & Destructor Documentation
cvCalculateWallShearStress::cvCalculateWallShearStress ()
Definition at line 49 of file cvCalculateWallShearStress.cxx.
References NULL, surfaceMesh_, tensors_, and wallshear_.
cvCalculateWallShearStress::~cvCalculateWallShearStress ()
Definition at line 61 of file cvCalculateWallShearStress.cxx.
References NULL, and wallshear_.
Member Function Documentation
cvPolyData * cvCalculateWallShearStress::CalcAvgPointData (int numPds, cvPolyData ** inputPds)
Definition at line 425 of file cvCalculateWallShearStress.cxx.
References cvPolyData::GetVtkPolyData(), NULL, and surfaceMesh_.
Referenced by gdscPost_calcAvgPointDataCmd().
cvPolyData * cvCalculateWallShearStress::CalcOSI (cvPolyData * shearMean, cvPolyData * shearPulse)
Definition at line 376 of file cvCalculateWallShearStress.cxx.
References cvPolyData::GetVtkPolyData(), NULL, and surfaceMesh_.
Referenced by gdscPost_calcOSICmd().
int cvCalculateWallShearStress::CalcWallShearFromStresses ()
Definition at line 102 of file cvCalculateWallShearStress.cxx.
References CV_ERROR, CV_OK, surfaceMesh_, tensors_, and wallshear_.
Referenced by gdscPost_calcWallShearCmd().
int cvCalculateWallShearStress::CalcWallShearFromTractions ()
Definition at line 190 of file cvCalculateWallShearStress.cxx.
References CV_ERROR, CV_OK, surfaceMesh_, tractions_, and wallshear_.
Referenced by gdscPost_calcWallShearCmd().
cvPolyData * cvCalculateWallShearStress::CalcWallShearMean (int numPds, cvPolyData ** shearPds)
Definition at line 279 of file cvCalculateWallShearStress.cxx.
References cvPolyData::GetVtkPolyData(), NULL, and surfaceMesh_.
Referenced by gdscPost_calcWallShearMeanCmd().
cvPolyData * cvCalculateWallShearStress::CalcWallShearPulse (int numPds, cvPolyData ** shearPds)
Definition at line 329 of file cvCalculateWallShearStress.cxx.
References cvPolyData::GetVtkPolyData(), NULL, and surfaceMesh_.
Referenced by gdscPost_calcWallShearPulseCmd().
cvPolyData * cvCalculateWallShearStress::GetWallShear ()
Definition at line 269 of file cvCalculateWallShearStress.cxx.
References surfaceMesh_, and wallshear_.
Referenced by gdscPost_calcWallShearCmd().
int cvCalculateWallShearStress::SetSurfaceMesh (cvPolyData * surfaceMesh)
Definition at line 72 of file cvCalculateWallShearStress.cxx.
References CV_OK, cvPolyData::GetVtkPolyData(), NULL, and surfaceMesh_.
Referenced by gdscPost_calcAvgPointDataCmd(), gdscPost_calcOSICmd(), gdscPost_calcWallShearCmd(), gdscPost_calcWallShearMeanCmd(), and gdscPost_calcWallShearPulseCmd().
int cvCalculateWallShearStress::SetTensors (cvPolyData * tensors)
Definition at line 82 of file cvCalculateWallShearStress.cxx.
References CV_OK, cvPolyData::GetVtkPolyData(), NULL, and tensors_.
Referenced by gdscPost_calcWallShearCmd().
int cvCalculateWallShearStress::SetTractions (cvPolyData * tractions)
Definition at line 92 of file cvCalculateWallShearStress.cxx.
References CV_OK, cvPolyData::GetVtkPolyData(), NULL, and tractions_.
Referenced by gdscPost_calcWallShearCmd().
Member Data Documentation
vtkPolyData* cvCalculateWallShearStress::surfaceMesh_ private
Definition at line 69 of file cvCalculateWallShearStress.h.
Referenced by CalcAvgPointData(), CalcOSI(), CalcWallShearFromStresses(), CalcWallShearFromTractions(), CalcWallShearMean(), CalcWallShearPulse(), cvCalculateWallShearStress(), GetWallShear(), and SetSurfaceMesh().
vtkPolyData* cvCalculateWallShearStress::tensors_ private
Definition at line 70 of file cvCalculateWallShearStress.h.
Referenced by CalcWallShearFromStresses(), cvCalculateWallShearStress(), and SetTensors().
vtkPolyData* cvCalculateWallShearStress::tractions_ private
Definition at line 71 of file cvCalculateWallShearStress.h.
Referenced by CalcWallShearFromTractions(), and SetTractions().
vtkFloatingPointArrayType* cvCalculateWallShearStress::wallshear_ private
Definition at line 72 of file cvCalculateWallShearStress.h.
Referenced by CalcWallShearFromStresses(), CalcWallShearFromTractions(), cvCalculateWallShearStress(), GetWallShear(), and ~cvCalculateWallShearStress().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/PostProcessing/cvCalculateWallShearStress.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/PostProcessing/cvCalculateWallShearStress.cxx