simvascular: cvLispList< T > Class Template Reference
cvLispList< T > Class Template Reference
#include <cvLispList.h>
Public Member Functions
cvLispList ()
virtual ~cvLispList ()
virtual void Prepend (T item)
virtual void Append (T item)
T Front ()
T RemoveFront ()
void Remove (T item)
Bool IsInList (T item) const
unsigned int NumInList ()
Bool IsEmpty ()
void Apply (void(*f)(T)) const
virtual void SanityCheck () const
void SelfTest (T *p, int numEntries)
Protected Attributes
cvLispListElement< T > * first
cvLispListElement< T > * last
int numInList
Friends
class cvLispListIterator< T >
Detailed Description
template<class T>
class cvLispList< T >
Definition at line 105 of file cvLispList.h.
Constructor & Destructor Documentation
template<class T > cvLispList< T >::cvLispList ()
Definition at line 104 of file cvLispList.cxx.
References NULL.
template<class T > cvLispList< T >::~cvLispList () virtual
Definition at line 116 of file cvLispList.cxx.
References Assert.
Member Function Documentation
template<class T> void cvLispList< T >::Append (T item) virtual
Reimplemented in cvSortedList< T >, and cvSortedList< TableStruct * >.
Definition at line 134 of file cvLispList.cxx.
References Assert, and cvLispListElement< T >::next.
Referenced by cvParasolidSolidModel::MakePoly3dSolid(), and cvParasolidSolidModel::MakePoly3dSurface().
template<class T> void cvLispList< T >::Apply (void(*)(T) f) const
Definition at line 276 of file cvLispList.cxx.
References cvLispListElement< T >::item, cvLispListElement< T >::next, and NULL.
template<class T> T cvLispList< T >::Front () inline
Definition at line 113 of file cvLispList.h.
Referenced by cvParasolidSolidModel::MakeApproxCurveLoop(), cvParasolidSolidModel::MakeInterpCurveLoop(), and cvParasolidSolidModel::MakeLoftedSurf().
template<class T> Bool cvLispList< T >::IsEmpty () inline
Definition at line 123 of file cvLispList.h.
Referenced by cvLevelSetSparseGrid::ClearHT().
template<class T> Bool cvLispList< T >::IsInList (T item) const
Definition at line 246 of file cvLispList.cxx.
References FALSE, cvLispListElement< T >::item, cvLispListElement< T >::next, NULL, and TRUE.
template<class T> unsigned int cvLispList< T >::NumInList () inline
Definition at line 121 of file cvLispList.h.
Referenced by cvParasolidSolidModel::CapSurfToSolid(), cvParasolidSolidModel::ListToArray(), cvParasolidSolidModel::MakeLoftedSurf(), and cvParasolidSolidModel::Print().
template<class T> void cvLispList< T >::Prepend (T item) virtual
Reimplemented in cvSortedList< T >, and cvSortedList< TableStruct * >.
Definition at line 157 of file cvLispList.cxx.
References Assert, and cvLispListElement< T >::next.
template<class T> void cvLispList< T >::Remove (T item)
Definition at line 210 of file cvLispList.cxx.
References Assert, cvLispListElement< T >::item, cvLispListElement< T >::next, NULL, and T.
Referenced by cvLevelSetSparseGrid::ConstructHT_Sweep().
template<class T > T cvLispList< T >::RemoveFront ()
Definition at line 184 of file cvLispList.cxx.
References Assert, cvLispListElement< T >::next, NULL, and T.
Referenced by cvLevelSetSparseGrid::ClearHT().
template<class T > void cvLispList< T >::SanityCheck () const virtual
Reimplemented in cvSortedList< T >, and cvSortedList< TableStruct * >.
Definition at line 339 of file cvLispList.cxx.
References Assert, cvLispListElement< T >::next, and NULL.
Referenced by cvSortedList< T >::SanityCheck().
template<class T> void cvLispList< T >::SelfTest (T * p, int numEntries)
Definition at line 365 of file cvLispList.cxx.
References Assert, cvLispListIterator< T >::IsDone(), cvLispListIterator< T >::Next(), and NULL.
Referenced by cvSortedList< T >::SelfTest().
Friends And Related Function Documentation
template<class T> friend class cvLispListIterator< T > friend
Definition at line 139 of file cvLispList.h.
Member Data Documentation
template<class T> cvLispListElement<T>* cvLispList< T >::first protected
Definition at line 135 of file cvLispList.h.
Referenced by cvLispListIterator< TableStruct * >::cvLispListIterator(), and cvLispList< TableStruct * >::Front().
template<class T> cvLispListElement<T>* cvLispList< T >::last protected
Definition at line 136 of file cvLispList.h.
template<class T> int cvLispList< T >::numInList protected
Definition at line 137 of file cvLispList.h.
Referenced by cvLispList< TableStruct * >::IsEmpty(), and cvLispList< TableStruct * >::NumInList().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvLispList.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvLispList.cxx