simvascular: vtkvmtkPolyDataBoundaryExtractor Class Reference
vtkvmtkPolyDataBoundaryExtractor Class Reference
#include <vtkvmtkPolyDataBoundaryExtractor.h>
Public Member Functions
vtkTypeMacro (vtkvmtkPolyDataBoundaryExtractor, vtkPolyDataAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
Static Public Member Functions
static
vtkvmtkPolyDataBoundaryExtractor * New ()
Protected Member Functions
vtkvmtkPolyDataBoundaryExtractor ()
~vtkvmtkPolyDataBoundaryExtractor ()
virtual int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
Private Member Functions
vtkvmtkPolyDataBoundaryExtractor (const vtkvmtkPolyDataBoundaryExtractor &)
void operator= (const vtkvmtkPolyDataBoundaryExtractor &)
Detailed Description
Definition at line 32 of file vtkvmtkPolyDataBoundaryExtractor.h.
Constructor & Destructor Documentation
vtkvmtkPolyDataBoundaryExtractor::vtkvmtkPolyDataBoundaryExtractor () protected
Definition at line 37 of file vtkvmtkPolyDataBoundaryExtractor.cxx.
vtkvmtkPolyDataBoundaryExtractor::~vtkvmtkPolyDataBoundaryExtractor () inline protected
Definition at line 42 of file vtkvmtkPolyDataBoundaryExtractor.h.
vtkvmtkPolyDataBoundaryExtractor::vtkvmtkPolyDataBoundaryExtractor (const vtkvmtkPolyDataBoundaryExtractor &) private
Member Function Documentation
static vtkvmtkPolyDataBoundaryExtractor* vtkvmtkPolyDataBoundaryExtractor::New () static
Referenced by vtkvmtkSimpleCapPolyData::RequestData(), vtkvmtkCapPolyData::RequestData(), vtkvmtkBoundaryReferenceSystems::RequestData(), and vtkvmtkPolyDataSurfaceRemeshing::RequestData().
void vtkvmtkPolyDataBoundaryExtractor::operator= (const vtkvmtkPolyDataBoundaryExtractor &) private
void vtkvmtkPolyDataBoundaryExtractor::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 216 of file vtkvmtkPolyDataBoundaryExtractor.cxx.
int vtkvmtkPolyDataBoundaryExtractor::RequestData (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected virtual
Definition at line 41 of file vtkvmtkPolyDataBoundaryExtractor.cxx.
References input().
vtkvmtkPolyDataBoundaryExtractor::vtkTypeMacro (vtkvmtkPolyDataBoundaryExtractor , vtkPolyDataAlgorithm)
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkPolyDataBoundaryExtractor.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkPolyDataBoundaryExtractor.cxx