simvascular: vtkvmtkVoronoiDiagram3D Class Reference
vtkvmtkVoronoiDiagram3D Class Reference
#include <vtkvmtkVoronoiDiagram3D.h>
Public Member Functions
vtkTypeMacro (vtkvmtkVoronoiDiagram3D, vtkPolyDataAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
vtkSetStringMacro (RadiusArrayName)
vtkGetStringMacro (RadiusArrayName)
vtkGetObjectMacro (PoleIds, vtkIdList)
Static Public Member Functions
static vtkvmtkVoronoiDiagram3D * New ()
Protected Member Functions
vtkvmtkVoronoiDiagram3D ()
~vtkvmtkVoronoiDiagram3D ()
int FillInputPortInformation (int, vtkInformation *info)
virtual int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
void ExtractUniqueEdges (vtkUnstructuredGrid *input, vtkCellArray *edgeArray)
void BuildVoronoiPolys (vtkUnstructuredGrid *input, vtkCellArray *voronoiPolys)
void BuildVoronoiLines ()
Protected Attributes
int BuildLines
vtkIdList * PoleIds
char * RadiusArrayName
Private Member Functions
vtkvmtkVoronoiDiagram3D (const vtkvmtkVoronoiDiagram3D &)
void operator= (const vtkvmtkVoronoiDiagram3D &)
Detailed Description
Definition at line 36 of file vtkvmtkVoronoiDiagram3D.h.
Constructor & Destructor Documentation
vtkvmtkVoronoiDiagram3D::vtkvmtkVoronoiDiagram3D () protected
Definition at line 37 of file vtkvmtkVoronoiDiagram3D.cxx.
References BuildLines, NULL, PoleIds, and RadiusArrayName.
vtkvmtkVoronoiDiagram3D::~vtkvmtkVoronoiDiagram3D () protected
Definition at line 44 of file vtkvmtkVoronoiDiagram3D.cxx.
References NULL, PoleIds, and RadiusArrayName.
vtkvmtkVoronoiDiagram3D::vtkvmtkVoronoiDiagram3D (const vtkvmtkVoronoiDiagram3D &) private
Member Function Documentation
void vtkvmtkVoronoiDiagram3D::BuildVoronoiLines () inline protected
Definition at line 67 of file vtkvmtkVoronoiDiagram3D.h.
Referenced by RequestData().
void vtkvmtkVoronoiDiagram3D::BuildVoronoiPolys (vtkUnstructuredGrid * input, vtkCellArray * voronoiPolys) protected
Definition at line 108 of file vtkvmtkVoronoiDiagram3D.cxx.
References ExtractUniqueEdges(), and NULL.
Referenced by RequestData().
void vtkvmtkVoronoiDiagram3D::ExtractUniqueEdges (vtkUnstructuredGrid * input, vtkCellArray * edgeArray) protected
Definition at line 61 of file vtkvmtkVoronoiDiagram3D.cxx.
Referenced by BuildVoronoiPolys().
int vtkvmtkVoronoiDiagram3D::FillInputPortInformation (int , vtkInformation * info) protected
Definition at line 55 of file vtkvmtkVoronoiDiagram3D.cxx.
static vtkvmtkVoronoiDiagram3D* vtkvmtkVoronoiDiagram3D::New () static
Referenced by vtkvmtkPolyDataCenterlines::RequestData().
void vtkvmtkVoronoiDiagram3D::operator= (const vtkvmtkVoronoiDiagram3D &) private
void vtkvmtkVoronoiDiagram3D::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 311 of file vtkvmtkVoronoiDiagram3D.cxx.
int vtkvmtkVoronoiDiagram3D::RequestData (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected virtual
Definition at line 190 of file vtkvmtkVoronoiDiagram3D.cxx.
References BuildLines, BuildVoronoiLines(), BuildVoronoiPolys(), input(), PoleIds, RadiusArrayName, and VTK_VMTK_DOUBLE_TOL.
vtkvmtkVoronoiDiagram3D::vtkGetObjectMacro (PoleIds , vtkIdList)
vtkvmtkVoronoiDiagram3D::vtkGetStringMacro (RadiusArrayName)
vtkvmtkVoronoiDiagram3D::vtkSetStringMacro (RadiusArrayName)
vtkvmtkVoronoiDiagram3D::vtkTypeMacro (vtkvmtkVoronoiDiagram3D , vtkPolyDataAlgorithm)
Member Data Documentation
int vtkvmtkVoronoiDiagram3D::BuildLines protected
Definition at line 67 of file vtkvmtkVoronoiDiagram3D.h.
Referenced by RequestData(), and vtkvmtkVoronoiDiagram3D().
vtkIdList* vtkvmtkVoronoiDiagram3D::PoleIds protected
Definition at line 70 of file vtkvmtkVoronoiDiagram3D.h.
Referenced by RequestData(), vtkvmtkVoronoiDiagram3D(), and ~vtkvmtkVoronoiDiagram3D().
char* vtkvmtkVoronoiDiagram3D::RadiusArrayName protected
Definition at line 71 of file vtkvmtkVoronoiDiagram3D.h.
Referenced by RequestData(), vtkvmtkVoronoiDiagram3D(), and ~vtkvmtkVoronoiDiagram3D().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkVoronoiDiagram3D.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkVoronoiDiagram3D.cxx