simvascular: vtkSurfaceBooleanOperations Class Reference
vtkSurfaceBooleanOperations Class Reference
#include <vtkSurfaceBooleanOperations.h>
Public Types
enum Modes { BOOLEAN_UNION, BOOLEAN_INTERSECTION, BOOLEAN_DIFFERENCE }
Public Member Functions
vtkTypeRevisionMacro (vtkSurfaceBooleanOperations, vtkPolyDataAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
vtkSetMacro (Loud, int)
vtkBooleanMacro (Loud, int)
void SetMode (int mode)
void SetModeToUnion ()
void SetModeToIntersection ()
void SetModeToDifference ()
Static Public Member Functions
static
vtkSurfaceBooleanOperations * New ()
Protected Member Functions
vtkSurfaceBooleanOperations ()
~vtkSurfaceBooleanOperations ()
int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
virtual int FillInputPortInformation (int port, vtkInformation *info)
Protected Attributes
int Mode
int Loud
Private Member Functions
vtkSurfaceBooleanOperations (const vtkSurfaceBooleanOperations &)
void operator= (const vtkSurfaceBooleanOperations &)
Detailed Description
This class performs set operations on two surfaces The operation is implemented using the GTS library: http://gts.sourceforge.net/
The code to copy a vtkPolyData to gts was written by Hiraki Hideaki: http://www.vtk.org/pipermail/vtkusers/2009-July/101865.html
By default, the Union operator will be applied.
By setting e.g. Difference to On, you automatically set Union and Intersection to Off.
Definition at line 27 of file vtkSurfaceBooleanOperations.h.
Member Enumeration Documentation
enum vtkSurfaceBooleanOperations::Modes
Enumerator
BOOLEAN_UNION
BOOLEAN_INTERSECTION
BOOLEAN_DIFFERENCE
Definition at line 38 of file vtkSurfaceBooleanOperations.h.
Constructor & Destructor Documentation
vtkSurfaceBooleanOperations::vtkSurfaceBooleanOperations () protected
Definition at line 34 of file vtkSurfaceBooleanOperations.cxx.
vtkSurfaceBooleanOperations::~vtkSurfaceBooleanOperations () protected
Definition at line 41 of file vtkSurfaceBooleanOperations.cxx.
vtkSurfaceBooleanOperations::vtkSurfaceBooleanOperations (const vtkSurfaceBooleanOperations &) private
Member Function Documentation
int vtkSurfaceBooleanOperations::FillInputPortInformation (int port, vtkInformation * info) protected virtual
Definition at line 44 of file vtkSurfaceBooleanOperations.cxx.
static vtkSurfaceBooleanOperations* vtkSurfaceBooleanOperations::New () static
Referenced by cvPolyDataSolid::Intersect(), cvPolyDataSolid::Subtract(), and cvPolyDataSolid::Union().
void vtkSurfaceBooleanOperations::operator= (const vtkSurfaceBooleanOperations &) private
void vtkSurfaceBooleanOperations::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 231 of file vtkSurfaceBooleanOperations.cxx.
int vtkSurfaceBooleanOperations::RequestData (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected
implementation of algorithm
Definition at line 143 of file vtkSurfaceBooleanOperations.cxx.
References gts2vtk(), NULL, vtk2gts(), and vtkNew.
void vtkSurfaceBooleanOperations::SetMode (int mode)
Definition at line 52 of file vtkSurfaceBooleanOperations.cxx.
void vtkSurfaceBooleanOperations::SetModeToDifference ()
Definition at line 69 of file vtkSurfaceBooleanOperations.cxx.
Referenced by cvPolyDataSolid::Subtract().
void vtkSurfaceBooleanOperations::SetModeToIntersection ()
Definition at line 63 of file vtkSurfaceBooleanOperations.cxx.
Referenced by cvPolyDataSolid::Intersect().
void vtkSurfaceBooleanOperations::SetModeToUnion ()
Definition at line 57 of file vtkSurfaceBooleanOperations.cxx.
Referenced by cvPolyDataSolid::Union().
vtkSurfaceBooleanOperations::vtkBooleanMacro (Loud , int)
vtkSurfaceBooleanOperations::vtkSetMacro (Loud , int)
vtkSurfaceBooleanOperations::vtkTypeRevisionMacro (vtkSurfaceBooleanOperations , vtkPolyDataAlgorithm)
Member Data Documentation
int vtkSurfaceBooleanOperations::Loud protected
Definition at line 58 of file vtkSurfaceBooleanOperations.h.
int vtkSurfaceBooleanOperations::Mode protected
Definition at line 56 of file vtkSurfaceBooleanOperations.h.
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkSurfaceBooleanOperations.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkSurfaceBooleanOperations.cxx