simvascular: vtkBooleanOperationPolyDataFilter2::Impl Class Reference
vtkBooleanOperationPolyDataFilter2::Impl Class Reference
Public Member Functions
Impl ()
virtual ~Impl ()
void Initialize ()
void SetCheckArrays ()
void SetBoundaryArrays ()
void ResetCheckArrays ()
void GetBooleanRegions (int inputIndex, std::vector< simLoop > *loops)
void DetermineIntersection (std::vector< simLoop > *loops)
void PerformBoolean (vtkPolyData *output, int Operation)
Public Attributes
int intersectionCase
vtkPolyData * Mesh [2]
vtkPolyData * IntersectionLines
vtkIntArray * BoundaryPointArray [2]
vtkIntArray * BoundaryCellArray [2]
vtkIntArray * BooleanArray [2]
vtkIntArray * NewCellIds [2]
vtkIntArray * OrientedCellArray [2]
vtkIntArray * FalsePositiveArray [2]
vtkIdType * checked [2]
vtkIdType * checkedcarefully [2]
vtkIdType * pointMapper [2]
vtkIdType * reversePointMapper [2]
vtkIdList * CheckCells
vtkIdList * CheckCells2
vtkIdList * CheckCellsCareful
vtkIdList * CheckCellsCareful2
Protected Member Functions
int RunLoopFind (vtkIdType interPt, vtkIdType nextCell, bool *usedPt, simLoop *loop)
int RunLoopTest (vtkIdType interPt, vtkIdType nextCell, simLoop *loop, bool *usedPt)
int GetCellOrientation (vtkPolyData *pd, vtkIdType cellId, vtkIdType p0, vtkIdType p1, int index)
int FindRegion (int inputIndex, int fillnumber, int start, int fill)
int FindRegionTipToe (int inputIndex, int fillnumber, int fill)
Detailed Description
Definition at line 72 of file vtkBooleanOperationPolyDataFilter2.cxx.
Constructor & Destructor Documentation
vtkBooleanOperationPolyDataFilter2::Impl::Impl ()
Definition at line 126 of file vtkBooleanOperationPolyDataFilter2.cxx.
References BooleanArray, BoundaryCellArray, BoundaryPointArray, CheckCells, CheckCells2, CheckCellsCareful, CheckCellsCareful2, checked, checkedcarefully, FalsePositiveArray, intersectionCase, IntersectionLines, Mesh, NewCellIds, NULL, OrientedCellArray, pointMapper, and reversePointMapper.
vtkBooleanOperationPolyDataFilter2::Impl::~Impl () virtual
Definition at line 155 of file vtkBooleanOperationPolyDataFilter2.cxx.
Member Function Documentation
void vtkBooleanOperationPolyDataFilter2::Impl::DetermineIntersection (std::vector< simLoop > * loops)
Definition at line 1019 of file vtkBooleanOperationPolyDataFilter2.cxx.
References simLoop::endPt, intersectionCase, IntersectionLines, simLoop::loopType, RunLoopFind(), and simLoop::startPt.
Referenced by vtkBooleanOperationPolyDataFilter2::RequestData().
int vtkBooleanOperationPolyDataFilter2::Impl::FindRegion (int inputIndex, int fillnumber, int start, int fill) protected
Definition at line 183 of file vtkBooleanOperationPolyDataFilter2.cxx.
References c.
int vtkBooleanOperationPolyDataFilter2::Impl::FindRegionTipToe (int inputIndex, int fillnumber, int fill) protected
Definition at line 283 of file vtkBooleanOperationPolyDataFilter2.cxx.
References c.
void vtkBooleanOperationPolyDataFilter2::Impl::GetBooleanRegions (int inputIndex, std::vector< simLoop > * loops)
Definition at line 517 of file vtkBooleanOperationPolyDataFilter2.cxx.
References simLine::id, simLine::pt1, and simLine::pt2.
Referenced by vtkBooleanOperationPolyDataFilter2::RequestData().
int vtkBooleanOperationPolyDataFilter2::Impl::GetCellOrientation (vtkPolyData * pd, vtkIdType cellId, vtkIdType p0, vtkIdType p1, int index) protected
Definition at line 578 of file vtkBooleanOperationPolyDataFilter2.cxx.
References Cross(), and Dot().
void vtkBooleanOperationPolyDataFilter2::Impl::Initialize ()
Definition at line 426 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by vtkBooleanOperationPolyDataFilter2::RequestData().
void vtkBooleanOperationPolyDataFilter2::Impl::PerformBoolean (vtkPolyData * output, int Operation)
Definition at line 1257 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by vtkBooleanOperationPolyDataFilter2::RequestData().
void vtkBooleanOperationPolyDataFilter2::Impl::ResetCheckArrays ()
Definition at line 728 of file vtkBooleanOperationPolyDataFilter2.cxx.
int vtkBooleanOperationPolyDataFilter2::Impl::RunLoopFind (vtkIdType interPt, vtkIdType nextCell, bool * usedPt, simLoop * loop) protected
Definition at line 1073 of file vtkBooleanOperationPolyDataFilter2.cxx.
References simLoop::cells, simLoop::endPt, simLine::id, simLoop::loopType, simLine::pt1, and simLine::pt2.
Referenced by DetermineIntersection().
int vtkBooleanOperationPolyDataFilter2::Impl::RunLoopTest (vtkIdType interPt, vtkIdType nextCell, simLoop * loop, bool * usedPt) protected
Definition at line 1152 of file vtkBooleanOperationPolyDataFilter2.cxx.
References simLoop::cells, simLine::id, input(), simLine::pt1, and simLine::pt2.
void vtkBooleanOperationPolyDataFilter2::Impl::SetBoundaryArrays ()
Definition at line 750 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by vtkBooleanOperationPolyDataFilter2::RequestData().
void vtkBooleanOperationPolyDataFilter2::Impl::SetCheckArrays ()
Definition at line 804 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by vtkBooleanOperationPolyDataFilter2::RequestData().
Member Data Documentation
vtkIntArray* vtkBooleanOperationPolyDataFilter2::Impl::BooleanArray[2]
Definition at line 110 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIntArray* vtkBooleanOperationPolyDataFilter2::Impl::BoundaryCellArray[2]
Definition at line 109 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIntArray* vtkBooleanOperationPolyDataFilter2::Impl::BoundaryPointArray[2]
Definition at line 108 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIdList* vtkBooleanOperationPolyDataFilter2::Impl::CheckCells
Definition at line 120 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIdList* vtkBooleanOperationPolyDataFilter2::Impl::CheckCells2
Definition at line 121 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIdList* vtkBooleanOperationPolyDataFilter2::Impl::CheckCellsCareful
Definition at line 122 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIdList* vtkBooleanOperationPolyDataFilter2::Impl::CheckCellsCareful2
Definition at line 123 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIdType* vtkBooleanOperationPolyDataFilter2::Impl::checked[2]
Definition at line 115 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIdType* vtkBooleanOperationPolyDataFilter2::Impl::checkedcarefully[2]
Definition at line 116 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIntArray* vtkBooleanOperationPolyDataFilter2::Impl::FalsePositiveArray[2]
Definition at line 113 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
int vtkBooleanOperationPolyDataFilter2::Impl::intersectionCase
Definition at line 103 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by DetermineIntersection(), and Impl().
vtkPolyData* vtkBooleanOperationPolyDataFilter2::Impl::IntersectionLines
Definition at line 106 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by DetermineIntersection(), Impl(), and vtkBooleanOperationPolyDataFilter2::RequestData().
vtkPolyData* vtkBooleanOperationPolyDataFilter2::Impl::Mesh[2]
Definition at line 105 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl(), and vtkBooleanOperationPolyDataFilter2::RequestData().
vtkIntArray* vtkBooleanOperationPolyDataFilter2::Impl::NewCellIds[2]
Definition at line 111 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIntArray* vtkBooleanOperationPolyDataFilter2::Impl::OrientedCellArray[2]
Definition at line 112 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIdType* vtkBooleanOperationPolyDataFilter2::Impl::pointMapper[2]
Definition at line 117 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
vtkIdType* vtkBooleanOperationPolyDataFilter2::Impl::reversePointMapper[2]
Definition at line 118 of file vtkBooleanOperationPolyDataFilter2.cxx.
Referenced by Impl().
The documentation for this class was generated from the following file:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkBooleanOperationPolyDataFilter2.cxx