simvascular: cvLevelSetSparseGrid Class Reference
cvLevelSetSparseGrid Class Reference
#include <cvLevelSetSparseGrid.h>
Public Member Functions
cvLevelSetSparseGrid (double h[], int dims[], double o[])
~cvLevelSetSparseGrid ()
void DeallocateNodes ()
int InitPhi (double ctr[], double radius)
int InitPhi (cvPolyData *front)
int InitPhi (cvSolidModel *solid)
int InitPhi (cvStrPts *img, double thr)
int ReinitPhi ()
int SetBandParams (double innerPhi, double outerPhi, double mineWidth)
int GetBandParams (double *innerPhi, double *outerPhi, double *mineWidth)
int ProjectV (int save)
void ExtendV ()
int UpdatePhi ()
cvDataObject * GetPhi ()
cvStrPts * GetCurvature ()
char * StatString ()
int GetNumBandNodes () const
cvPolyData * CreateGridPolyData ()
int GridModified () const
cvPolyData * CSRToPolyData (GridScalarT t)
cvPolyData * PartitionToPolyData (int partNum)
cvDataObject * GetCSRStructure ()
int GetMemoryUsage ()
int PartitionGraph (int numParts)
int PackagePartition (int partNum)
Public Member Functions inherited from cvLevelSetStructuredGrid
cvLevelSetStructuredGrid (double h[], int dims[], double o[])
virtual ~cvLevelSetStructuredGrid ()
int CloseHoles ()
int EvaluateV (cvLevelSetVelocity *vfn, double factor=1.0)
double ComputeDeltaPhi (double factor=1.0)
void GetAdjacentIxs (cvLevelSetNode *n, int ixs[])
void GetAdjacentIxs (int index, int ixs[])
int IxWithinExtent (int i, int j, int k)
void FindDpi ()
void FindDmi ()
void FindD0 ()
void FindK ()
void FindK2d ()
void FindK3dg ()
void FindK3dm ()
void FindN ()
int GetAnchorIx (double pos[], int *ix)
int FindEdge (double pos[], cvLevelSetNode **a, cvLevelSetNode **b, char *dir)
int InterpZLS (cvLevelSetNode *a, cvLevelSetNode *b, char code, double zls[])
int InterpK (double pos[], double *k)
int InterpKm (double pos[], double *k)
int InterpKg (double pos[], double *k)
int InterpN (double pos[], double n[])
double GetMaxF ()
vtkFloatingPointType GetMaxV ()
double GetMaxPhiIncr ()
cvPolyData * GetVelocityVectors ()
cvPolyData * GetFront (int closed=0)
cvPolyData * GetActiveNodes ()
virtual cvPolyData * GetBoundaryData (GridScalarT t)
int GetNodeSets (cvPolyData ***nodeSets, int *numSets)
int SaveActiveNodes ()
int NumActiveNodes ()
int SaveCoveredNodes ()
int SaveUncoveredNodes ()
int SaveForceMinVNodes ()
int SaveMineNodes ()
int PSetsValid ()
int GetDim ()
int GetHv (double *hx, double *hy, double *hz)
double GetMinH ()
double ComputeDt (double cflFactor)
double ComputeDt (double maxf, double cflFactor)
double GetMainDiagonal ()
Private Member Functions
int InitSign_Internal (cvPolyData *front)
int InitPhi_Internal (cvPolyData *front)
void InitIter ()
cvLevelSetNode * GetNext ()
int IJKToIndex (int i, int j, int k)
int IJKToSparseIx (int i, int j, int k)
int IJKToDenseIx (int i, int j, int k)
void UndoTimeStep ()
void ClearSeedInterface ()
int BuildSeedInterface (cvSolidModel *seed)
int ConstructHT (double ctr[], double radius)
int ConstructHT (cvPolyData *front)
int ConstructHT (cvSolidModel *sm)
int ConstructHT_Sweep (cvPolyData *front)
int PollNeighborSigns (int i, int j, int k)
void Sweep_MarkActiveNodes ()
void Sweep_ComparePair (int currIx, int currSign, int ip, int jp, int kp)
int Sweep (int sign, int levels)
int Blot (int dim[3])
void ClearHT ()
int IJKPresentInHT (int i, int j, int k, cvSortedList< TableStruct * > **bucket, TableStruct **entry)
int ComputeHashIx (int i, int j, int k)
void InitHTIterator ()
TableStruct * GetNextHTItem ()
void TopoUpdate ()
int ConstructCSR ()
int SanityCheckCSR ()
int GetNeighborSparseIxs (cvLevelSetNode *node, int ixs[])
void DeallocateCSR ()
int SetNeighborInfo (cvLevelSetNode *node)
cvLevelSetNode * IJKPresentInCSR (int i, int j, int k)
void MakePhiVtk (int closed=0)
void MakeClosedPhiVtk ()
void ClearPartitioning ()
int GetPartSize (int partNum)
int BuildL1Map ()
int BuildL2Map ()
int L1_FwdMap (int i, int j, int k)
int L1_RevMap (int ixIn, int *i, int *j, int *k)
int L2_FwdMap (int ixIn, int *ixOut)
int L2_RevMap (int ixIn, int *ixOut)
int BuildGlobalToLocalMap (int partNum, int **map)
int BuildLocalToGlobalMap (int g2lMap[], int **l2gMap, int *l2gSz)
int InitIxBuffer ()
int InitNodeSets ()
Private Attributes
int currIx_
cvPolyData * seedInterface_
cvSortedList< TableStruct * > ** nodeTable_
int numBuckets_
int htCurrBucketId_
cvLispListIterator
< TableStruct * > * htIter_
cvStateArray * topoOverlay_
int overlaySz_
int numSparseNodes_
int numSparseEdges_
int * adjIa_
int * adjJa_
int iaSz_
int jaSz_
int closedPhiVtkValid_
int * color_
int numParts_
int localSize_
int packageSize_
int * L1map_
int * L2map_
double outerExtent_
double innerExtent_
double mineWidth_
double outerExtent2_
double innerExtent2_
double mineWidth2_
int mineHit_
cvLevelSetSparseGridStateT gridState_
cvLevelSetSparseGridBandT bandMethod_
Additional Inherited Members
Protected Member Functions inherited from cvLevelSetStructuredGrid
int GetStructuredGridMemoryUsage ()
void FindD0i ()
void FindD0xi ()
void FindD0yi ()
void FindD0zi ()
void FindDelPlus ()
void FindDelMinus ()
int IJKToLogicalIx (int i, int j, int k)
int LogicalIxToIJK (int log_ix, int *i, int *j, int *k)
int ProjectV (int posFlag, int save)
int CheckProjectCoverage ()
int SteepestDescentPhi (int ix)
int SteepestAscentPhi (int ix)
void ResetNodeSets ()
void ClearActive ()
void ClearForceMinV ()
void ClearCovered ()
void AssignNode (cvLevelSetNode *n, double f0, double f1, int forceMinVFlag, double toDot[])
void AssignVToNode (cvLevelSetNode *n, double f0, double f1, int forceMinVFlag, double toDot[])
void AssignVToEdge (cvLevelSetNode *a, cvLevelSetNode *b, double f0, double f1, int forceMinVFlag, double toDot[])
Protected Attributes inherited from cvLevelSetStructuredGrid
cvLevelSetNode * curr_
int * ixBuffer_
int ixBufferSz_
int * nodeSets_
int nodeSetsSize_
int nodeSetsPos_
int pSetsValid_
cvLevelSetNode * grid_
int numNodes_
int I_
int J_
int K_
int numDenseNodes_
double hv_ [3]
double minh_
double maxh_
double origin_ [3]
int dim_
double mainDiagonal_
double tol_
double oneOverTol_
double relTol_
int init_
int d0Valid_
int dpiValid_
int dmiValid_
int delPlusValid_
int delMinusValid_
int deltaPhiValid_
int nValid_
int kValid_
int k3dmValid_
int k3dgValid_
vtkDataSet * phiVtk_
int phiVtkValid_
cvPolyData * velocityVectors_
cvLevelSetVelocity * velocity_
Detailed Description
Definition at line 82 of file cvLevelSetSparseGrid.h.
Constructor & Destructor Documentation
cvLevelSetSparseGrid::cvLevelSetSparseGrid (double h[], int dims[], double o[])
Definition at line 51 of file cvLevelSetSparseGrid.cxx.
References adjIa_, adjJa_, BAND_SWEEP, bandMethod_, closedPhiVtkValid_, color_, currIx_, gridState_, htIter_, cvLevelSetStructuredGrid::I_, iaSz_, cvLevelSetStructuredGrid::J_, jaSz_, cvLevelSetStructuredGrid::K_, L1map_, L2map_, mineHit_, nodeTable_, NULL, numBuckets_, cvLevelSetStructuredGrid::numDenseNodes_, numSparseEdges_, numSparseNodes_, overlaySz_, seedInterface_, SGST_Start, TableStructCompareFn(), and topoOverlay_.
cvLevelSetSparseGrid::~cvLevelSetSparseGrid ()
Definition at line 114 of file cvLevelSetSparseGrid.cxx.
References adjIa_, adjJa_, ClearSeedInterface(), DeallocateNodes(), and topoOverlay_.
Member Function Documentation
int cvLevelSetSparseGrid::Blot (int dim[3]) private
Definition at line 1624 of file cvLevelSetSparseGrid.cxx.
References c, CV_OK, cvLevelSetStructuredGrid::I_, IJKToDenseIx(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, STATE_NODE_ACTIVE, STATE_NODE_COVERED, and topoOverlay_.
Referenced by ConstructHT_Sweep().
int cvLevelSetSparseGrid::BuildGlobalToLocalMap (int partNum, int ** map) private
Definition at line 3077 of file cvLevelSetSparseGrid.cxx.
References color_, CV_ERROR, CV_OK, NULL, numParts_, and numSparseNodes_.
Referenced by PartitionToPolyData().
int cvLevelSetSparseGrid::BuildL1Map () private
Definition at line 3020 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, cvLevelSetStructuredGrid::grid_, gridState_, IJKToDenseIx(), L1map_, NULL, numSparseNodes_, and SGST_CSR.
int cvLevelSetSparseGrid::BuildL2Map () private
Definition at line 3062 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR.
int cvLevelSetSparseGrid::BuildLocalToGlobalMap (int g2lMap[], int ** l2gMap, int * l2gSz) private
Definition at line 3117 of file cvLevelSetSparseGrid.cxx.
References color_, CV_ERROR, CV_OK, NULL, and numSparseNodes_.
int cvLevelSetSparseGrid::BuildSeedInterface (cvSolidModel * seed) private
Definition at line 631 of file cvLevelSetSparseGrid.cxx.
References ClearSeedInterface(), CV_ERROR, CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), cvLevelSetStructuredGrid::dim_, cvSolidModel::GetPolyData(), cvLevelSetStructuredGrid::hv_, cvLevelSetStructuredGrid::I_, cvSolidModel::Intersect(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, cvSolidModel::MakeBox2d(), cvSolidModel::MakeBox3d(), cvSolidModel::MakePoly2d(), cvSolidModel::MakePoly3dSurface(), NULL, cvLevelSetStructuredGrid::origin_, seedInterface_, cvSolidModel::SetPoly3dFacetMethod(), SM_Facet_Union, and sys_geom_BBox().
Referenced by ConstructHT().
void cvLevelSetSparseGrid::ClearHT () private
Definition at line 147 of file cvLevelSetSparseGrid.cxx.
References cvLispList< T >::IsEmpty(), nodeTable_, numBuckets_, and cvLispList< T >::RemoveFront().
Referenced by DeallocateNodes().
void cvLevelSetSparseGrid::ClearPartitioning () private
Definition at line 193 of file cvLevelSetSparseGrid.cxx.
References color_, and NULL.
Referenced by DeallocateNodes().
void cvLevelSetSparseGrid::ClearSeedInterface () private
Definition at line 612 of file cvLevelSetSparseGrid.cxx.
References NULL, and seedInterface_.
Referenced by BuildSeedInterface(), and ~cvLevelSetSparseGrid().
int cvLevelSetSparseGrid::ComputeHashIx (int i, int j, int k) inline private
Definition at line 294 of file cvLevelSetSparseGrid.h.
References cvLevelSetStructuredGrid::I_, IJKToDenseIx(), and numBuckets_.
Referenced by ConstructHT(), ConstructHT_Sweep(), and IJKPresentInHT().
int cvLevelSetSparseGrid::ConstructCSR () private
Definition at line 1676 of file cvLevelSetSparseGrid.cxx.
References adjIa_, adjJa_, CV_ERROR, CV_NODE_MINE, CV_OK, cvLevelSetNodeCompareFn(), DeallocateCSR(), GetNext(), GetNextHTItem(), cvLevelSetStructuredGrid::grid_, gridState_, cvLevelSetStructuredGrid::hv_, cvLevelSetNode::i_, iaSz_, IJKToDenseIx(), cvLevelSetNode::index_, InitHTIterator(), InitIter(), InitIxBuffer(), InitNodeSets(), cvLevelSetNode::j_, jaSz_, cvLevelSetNode::k_, TableStruct::logicalIx_, cvLevelSetNode::logicalIx_, NULL, numSparseEdges_, numSparseNodes_, cvLevelSetStructuredGrid::origin_, TableStruct::phi_, cvLevelSetNode::phi_, cvLevelSetNode::pos_, SetNeighborInfo(), SGST_CSR, SGST_GridAllocated, SGST_HashTable, TableStruct::state_, cvLevelSetNode::state_, STATE_MINE, cvLevelSetNode::xNextIndex_, cvLevelSetNode::xPrevIndex_, cvLevelSetNode::yNextIndex_, cvLevelSetNode::yPrevIndex_, cvLevelSetNode::zNextIndex_, and cvLevelSetNode::zPrevIndex_.
Referenced by ConstructHT(), and ConstructHT_Sweep().
int cvLevelSetSparseGrid::ConstructHT (double ctr[], double radius) private
Definition at line 830 of file cvLevelSetSparseGrid.cxx.
References ComputeHashIx(), ConstructCSR(), CV_ERROR, DeallocateNodes(), gridState_, cvLevelSetStructuredGrid::hv_, cvLevelSetStructuredGrid::I_, IJKToDenseIx(), cvLevelSetStructuredGrid::init_, innerExtent_, cvSortedList< T >::Insert(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, TableStruct::logicalIx_, mineWidth_, nodeTable_, numSparseNodes_, cvLevelSetStructuredGrid::origin_, outerExtent_, TableStruct::phi_, SGST_ExtentDefined, SGST_HashTable, TableStruct::state_, STATE_MINE, STATE_PHI_INSIDE, STATE_PHI_MASK, STATE_PHI_ON, STATE_PHI_OUTSIDE, TableStruct::tag_, cvLevelSetStructuredGrid::tol_, and topoOverlay_.
Referenced by ConstructHT(), InitPhi(), and InitPhi_Internal().
int cvLevelSetSparseGrid::ConstructHT (cvPolyData * front) private
Definition at line 1132 of file cvLevelSetSparseGrid.cxx.
References ComputeHashIx(), ConstructCSR(), ConstructHT(), CV_ERROR, DeallocateNodes(), cvSolidModel::DefaultInstantiateSolidModel(), cvLevelSetStructuredGrid::dim_, cvPolyData::FindDistance2(), gridState_, cvLevelSetStructuredGrid::hv_, cvLevelSetStructuredGrid::I_, IJKToDenseIx(), cvLevelSetStructuredGrid::init_, innerExtent2_, innerExtent_, cvSortedList< T >::Insert(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, TableStruct::logicalIx_, cvSolidModel::MakePoly2d(), cvSolidModel::MakePoly3dSolid(), mineWidth_, nodeTable_, NULL, numSparseNodes_, cvLevelSetStructuredGrid::origin_, outerExtent2_, outerExtent_, TableStruct::phi_, SGST_ExtentDefined, SGST_HashTable, TableStruct::state_, STATE_MINE, STATE_PHI_INSIDE, STATE_PHI_MASK, STATE_PHI_ON, STATE_PHI_OUTSIDE, TableStruct::tag_, topoOverlay_, and TopoUpdate().
int cvLevelSetSparseGrid::ConstructHT (cvSolidModel * sm) private
Definition at line 982 of file cvLevelSetSparseGrid.cxx.
References BuildSeedInterface(), cvSolidModel::ClassifyPt(), ComputeHashIx(), ConstructCSR(), CV_ERROR, CV_OK, DeallocateNodes(), cvPolyData::FindDistance2(), gridState_, cvLevelSetStructuredGrid::hv_, cvLevelSetStructuredGrid::I_, IJKToDenseIx(), cvLevelSetStructuredGrid::init_, innerExtent2_, innerExtent_, cvSortedList< T >::Insert(), IntSign(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, TableStruct::logicalIx_, cvLevelSetStructuredGrid::maxh_, maximum, mineWidth_, nodeTable_, numSparseNodes_, cvLevelSetStructuredGrid::origin_, outerExtent2_, outerExtent_, TableStruct::phi_, seedInterface_, SGST_ExtentDefined, SGST_HashTable, TableStruct::state_, STATE_MINE, STATE_PHI_INSIDE, STATE_PHI_ON, STATE_PHI_OUTSIDE, TableStruct::tag_, and cvLevelSetStructuredGrid::tol_.
int cvLevelSetSparseGrid::ConstructHT_Sweep (cvPolyData * front) private
Definition at line 1280 of file cvLevelSetSparseGrid.cxx.
References Blot(), ComputeHashIx(), ConstructCSR(), CV_ERROR, CV_OK, DeallocateNodes(), cvPolyData::FindDistance(), cvStateArray::GetNumActive(), cvStateArray::GetSign(), gridState_, cvLevelSetStructuredGrid::hv_, cvLevelSetStructuredGrid::I_, IJKPresentInHT(), IJKToDenseIx(), cvLevelSetStructuredGrid::init_, innerExtent_, cvSortedList< T >::Insert(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, TableStruct::logicalIx_, maximum, mineWidth_, cvLevelSetStructuredGrid::minh_, nodeTable_, numSparseNodes_, cvLevelSetStructuredGrid::origin_, outerExtent_, TableStruct::phi_, PollNeighborSigns(), cvLispList< T >::Remove(), SGST_ExtentDefined, SGST_HashTable, TableStruct::state_, STATE_MINE, STATE_NODE_ACTIVE, STATE_NODE_COVERED, STATE_PHI_MASK, STATE_PHI_ON, Sweep_MarkActiveNodes(), TableStruct::tag_, cvLevelSetStructuredGrid::tol_, topoOverlay_, and TopoUpdate().
Referenced by InitPhi_Internal().
cvPolyData* cvLevelSetSparseGrid::CreateGridPolyData () inline virtual
Reimplemented from cvLevelSetStructuredGrid.
Definition at line 118 of file cvLevelSetSparseGrid.h.
References CSRToPolyData(), and GS_INVALID.
cvPolyData * cvLevelSetSparseGrid::CSRToPolyData (GridScalarT t)
Definition at line 3159 of file cvLevelSetSparseGrid.cxx.
References MakePhiVtk(), and cvLevelSetStructuredGrid::phiVtk_.
Referenced by CreateGridPolyData().
void cvLevelSetSparseGrid::DeallocateCSR () private
Definition at line 169 of file cvLevelSetSparseGrid.cxx.
References adjIa_, adjJa_, cvLevelSetStructuredGrid::grid_, iaSz_, jaSz_, and NULL.
Referenced by ConstructCSR(), and DeallocateNodes().
void cvLevelSetSparseGrid::DeallocateNodes () virtual
Implements cvLevelSetStructuredGrid.
Definition at line 133 of file cvLevelSetSparseGrid.cxx.
References ClearHT(), ClearPartitioning(), DeallocateCSR(), and numSparseNodes_.
Referenced by ConstructHT(), ConstructHT_Sweep(), and ~cvLevelSetSparseGrid().
void cvLevelSetSparseGrid::ExtendV () virtual
Implements cvLevelSetStructuredGrid.
Definition at line 2445 of file cvLevelSetSparseGrid.cxx.
int cvLevelSetSparseGrid::GetBandParams (double * innerPhi, double * outerPhi, double * mineWidth) virtual
Reimplemented from cvLevelSetStructuredGrid.
Definition at line 273 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, gridState_, innerExtent_, mineWidth_, outerExtent_, and SGST_ExtentDefined.
cvDataObject * cvLevelSetSparseGrid::GetCSRStructure ()
Definition at line 3250 of file cvLevelSetSparseGrid.cxx.
References cvLevelSetStructuredGrid::dim_, cvLevelSetStructuredGrid::grid_, gridState_, cvLevelSetNode::i_, IJKPresentInCSR(), cvLevelSetNode::index_, cvLevelSetNode::j_, cvLevelSetNode::k_, NULL, numSparseNodes_, cvLevelSetNode::pos_, SGST_CSR, cvLevelSetNode::xNextIndex_, cvLevelSetNode::yNextIndex_, and cvLevelSetNode::zNextIndex_.
cvStrPts * cvLevelSetSparseGrid::GetCurvature () virtual
Implements cvLevelSetStructuredGrid.
Definition at line 2955 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR.
int cvLevelSetSparseGrid::GetMemoryUsage () virtual
Implements cvLevelSetStructuredGrid.
Definition at line 3350 of file cvLevelSetSparseGrid.cxx.
References adjIa_, adjJa_, color_, cvDataObject::GetMemoryUsage(), cvStateArray::GetMemoryUsage(), cvLevelSetStructuredGrid::GetStructuredGridMemoryUsage(), cvLevelSetStructuredGrid::grid_, htIter_, iaSz_, jaSz_, L1map_, L2map_, nodeTable_, numBuckets_, numSparseNodes_, seedInterface_, and topoOverlay_.
int cvLevelSetSparseGrid::GetNeighborSparseIxs (cvLevelSetNode * node, int ixs[]) private
Definition at line 1831 of file cvLevelSetSparseGrid.cxx.
References cvLevelSetNode::i_, IJKPresentInCSR(), cvLevelSetNode::index_, cvLevelSetNode::j_, cvLevelSetNode::k_, and NULL.
Referenced by SanityCheckCSR().
cvLevelSetNode * cvLevelSetSparseGrid::GetNext () inline private virtual
Implements cvLevelSetStructuredGrid.
Definition at line 329 of file cvLevelSetSparseGrid.h.
References currIx_, cvLevelSetStructuredGrid::grid_, NULL, and numSparseNodes_.
Referenced by ConstructCSR(), MakePhiVtk(), ReinitPhi(), SanityCheckCSR(), TopoUpdate(), UndoTimeStep(), and UpdatePhi().
TableStruct * cvLevelSetSparseGrid::GetNextHTItem () private
Definition at line 796 of file cvLevelSetSparseGrid.cxx.
References gridState_, htCurrBucketId_, htIter_, cvLispListIterator< T >::IsDone(), cvLispListIterator< T >::Item(), cvLispListIterator< T >::Next(), nodeTable_, NULL, numBuckets_, and SGST_HashTable.
Referenced by ConstructCSR().
int cvLevelSetSparseGrid::GetNumBandNodes () const
Definition at line 207 of file cvLevelSetSparseGrid.cxx.
References gridState_, numSparseNodes_, and SGST_HashTable.
int cvLevelSetSparseGrid::GetPartSize (int partNum) private
Definition at line 2985 of file cvLevelSetSparseGrid.cxx.
References color_, NULL, numParts_, and numSparseNodes_.
Referenced by PartitionToPolyData().
cvDataObject * cvLevelSetSparseGrid::GetPhi () virtual
Implements cvLevelSetStructuredGrid.
Definition at line 2941 of file cvLevelSetSparseGrid.cxx.
References MakePhiVtk(), and cvLevelSetStructuredGrid::phiVtk_.
int cvLevelSetSparseGrid::GridModified () const inline virtual
Reimplemented from cvLevelSetStructuredGrid.
Definition at line 119 of file cvLevelSetSparseGrid.h.
References mineHit_.
cvLevelSetNode * cvLevelSetSparseGrid::IJKPresentInCSR (int i, int j, int k) private
Definition at line 2317 of file cvLevelSetSparseGrid.cxx.
References cvLevelSetStructuredGrid::grid_, cvLevelSetStructuredGrid::I_, IJKToSparseIx(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, and NULL.
Referenced by GetCSRStructure(), GetNeighborSparseIxs(), MakeClosedPhiVtk(), MakePhiVtk(), SanityCheckCSR(), and SetNeighborInfo().
int cvLevelSetSparseGrid::IJKPresentInHT (int i, int j, int k, cvSortedList< TableStruct * > ** bucket, TableStruct ** entry) private
Definition at line 2119 of file cvLevelSetSparseGrid.cxx.
References ComputeHashIx(), cvLevelSetStructuredGrid::I_, IJKToDenseIx(), cvLispListIterator< T >::IsDone(), cvLispListIterator< T >::Item(), iter, cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, cvLispListIterator< T >::Next(), nodeTable_, NULL, and TableStruct::tag_.
Referenced by ConstructHT_Sweep().
int cvLevelSetSparseGrid::IJKToDenseIx (int i, int j, int k) inline private
Definition at line 307 of file cvLevelSetSparseGrid.h.
References cvLevelSetStructuredGrid::I_, and cvLevelSetStructuredGrid::J_.
Referenced by Blot(), BuildL1Map(), ComputeHashIx(), ConstructCSR(), ConstructHT(), ConstructHT_Sweep(), IJKPresentInHT(), IJKToSparseIx(), InitPhi(), InitSign_Internal(), MakeClosedPhiVtk(), PollNeighborSigns(), SanityCheckCSR(), Sweep(), Sweep_ComparePair(), Sweep_MarkActiveNodes(), and TopoUpdate().
int cvLevelSetSparseGrid::IJKToIndex (int i, int j, int k) inline private virtual
Implements cvLevelSetStructuredGrid.
Definition at line 318 of file cvLevelSetSparseGrid.h.
References IJKToSparseIx().
Referenced by SanityCheckCSR().
int cvLevelSetSparseGrid::IJKToSparseIx (int i, int j, int k) private
Definition at line 2255 of file cvLevelSetSparseGrid.cxx.
References cvLevelSetStructuredGrid::grid_, gridState_, cvLevelSetNode::i_, IJKToDenseIx(), cvLevelSetNode::index_, cvLevelSetNode::j_, cvLevelSetNode::k_, numSparseNodes_, and SGST_GridAllocated.
Referenced by IJKPresentInCSR(), and IJKToIndex().
void cvLevelSetSparseGrid::InitHTIterator () private
Definition at line 778 of file cvLevelSetSparseGrid.cxx.
References gridState_, htCurrBucketId_, htIter_, nodeTable_, NULL, and SGST_HashTable.
Referenced by ConstructCSR().
void cvLevelSetSparseGrid::InitIter () inline private virtual
Implements cvLevelSetStructuredGrid.
Definition at line 137 of file cvLevelSetSparseGrid.h.
References currIx_.
Referenced by ConstructCSR(), MakePhiVtk(), ReinitPhi(), SanityCheckCSR(), TopoUpdate(), UndoTimeStep(), and UpdatePhi().
int cvLevelSetSparseGrid::InitIxBuffer () private
Definition at line 2407 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, gridState_, cvLevelSetStructuredGrid::ixBuffer_, cvLevelSetStructuredGrid::ixBufferSz_, NULL, numSparseNodes_, and SGST_CSR.
Referenced by ConstructCSR().
int cvLevelSetSparseGrid::InitNodeSets () private
Definition at line 2425 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, gridState_, cvLevelSetStructuredGrid::nodeSets_, cvLevelSetStructuredGrid::nodeSetsPos_, cvLevelSetStructuredGrid::nodeSetsSize_, NULL, numSparseNodes_, and SGST_CSR.
Referenced by ConstructCSR().
int cvLevelSetSparseGrid::InitPhi (double ctr[], double radius) virtual
Implements cvLevelSetStructuredGrid.
Definition at line 290 of file cvLevelSetSparseGrid.cxx.
References closedPhiVtkValid_, ConstructHT(), CV_ERROR, CV_OK, cvLevelSetStructuredGrid::init_, and cvLevelSetStructuredGrid::phiVtkValid_.
Referenced by InitPhi(), and UpdatePhi().
int cvLevelSetSparseGrid::InitPhi (cvPolyData * front) virtual
Implements cvLevelSetStructuredGrid.
Definition at line 337 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, cvLevelSetStructuredGrid::init_, InitPhi_Internal(), and InitSign_Internal().
int cvLevelSetSparseGrid::InitPhi (cvSolidModel * solid) virtual
Implements cvLevelSetStructuredGrid.
Definition at line 476 of file cvLevelSetSparseGrid.cxx.
References closedPhiVtkValid_, ConstructHT(), CV_ERROR, CV_OK, cvLevelSetStructuredGrid::init_, and cvLevelSetStructuredGrid::phiVtkValid_.
int cvLevelSetSparseGrid::InitPhi (cvStrPts * img, double thr) virtual
Implements cvLevelSetStructuredGrid.
Definition at line 501 of file cvLevelSetSparseGrid.cxx.
References BAND_SWEEP, bandMethod_, CreateImage(), CV_ERROR, GetIntensity(), cvDataObject::GetVtkPtr(), cvLevelSetStructuredGrid::hv_, cvLevelSetStructuredGrid::I_, IJKToDenseIx(), Image_Delete(), cvLevelSetStructuredGrid::init_, InitPhi(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, NULL, cvLevelSetStructuredGrid::origin_, SetLowerLeft(), STATE_PHI_INSIDE, STATE_PHI_ON, STATE_PHI_OUTSIDE, and cvLevelSetStructuredGrid::tol_.
int cvLevelSetSparseGrid::InitPhi_Internal (cvPolyData * front) private
Definition at line 432 of file cvLevelSetSparseGrid.cxx.
References BAND_SDIST, BAND_SWEEP, bandMethod_, closedPhiVtkValid_, ConstructHT(), ConstructHT_Sweep(), CV_ERROR, CV_OK, cvLevelSetStructuredGrid::init_, and cvLevelSetStructuredGrid::phiVtkValid_.
Referenced by InitPhi().
int cvLevelSetSparseGrid::InitSign_Internal (cvPolyData * front) private
Definition at line 354 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, cvLevelSetStructuredGrid::dim_, cvLevelSetStructuredGrid::hv_, cvLevelSetStructuredGrid::I_, IJKToDenseIx(), cvLevelSetStructuredGrid::init_, cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, cvLevelSetStructuredGrid::origin_, STATE_PHI_INSIDE, STATE_PHI_OUTSIDE, sys_geom_Classify(), and sys_geom_PtInPoly().
Referenced by InitPhi().
int cvLevelSetSparseGrid::L1_FwdMap (int i, int j, int k) private
int cvLevelSetSparseGrid::L1_RevMap (int ixIn, int * i, int * j, int * k) private
int cvLevelSetSparseGrid::L2_FwdMap (int ixIn, int * ixOut) private
int cvLevelSetSparseGrid::L2_RevMap (int ixIn, int * ixOut) private
void cvLevelSetSparseGrid::MakeClosedPhiVtk () private
Definition at line 2829 of file cvLevelSetSparseGrid.cxx.
References closedPhiVtkValid_, cvLevelSetStructuredGrid::dim_, cvLevelSetNode::GetDoubleDatum(), gridState_, GS_PHI, cvLevelSetStructuredGrid::hv_, cvLevelSetStructuredGrid::I_, IJKPresentInCSR(), IJKToDenseIx(), IntSign(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, NULL, cvLevelSetStructuredGrid::origin_, cvLevelSetStructuredGrid::phiVtk_, cvLevelSetStructuredGrid::phiVtkValid_, SGST_CSR, STATE_PHI_INSIDE, STATE_PHI_MASK, STATE_PHI_ON, STATE_PHI_OUTSIDE, cvLevelSetStructuredGrid::tol_, and topoOverlay_.
Referenced by MakePhiVtk().
void cvLevelSetSparseGrid::MakePhiVtk (int closed = 0) private virtual
Implements cvLevelSetStructuredGrid.
Definition at line 2675 of file cvLevelSetSparseGrid.cxx.
References closedPhiVtkValid_, cvLevelSetStructuredGrid::dim_, cvLevelSetNode::GetDoubleDatum(), GetNext(), cvLevelSetStructuredGrid::grid_, gridState_, GS_PHI, cvLevelSetNode::i_, cvLevelSetStructuredGrid::I_, IJKPresentInCSR(), cvLevelSetNode::index_, InitIter(), cvLevelSetNode::j_, cvLevelSetStructuredGrid::J_, cvLevelSetNode::k_, cvLevelSetStructuredGrid::K_, MakeClosedPhiVtk(), NULL, numSparseNodes_, cvLevelSetStructuredGrid::phiVtk_, cvLevelSetStructuredGrid::phiVtkValid_, cvLevelSetNode::pos_, SGST_CSR, cvLevelSetStructuredGrid::tol_, cvLevelSetNode::xNextIndex_, cvLevelSetNode::yNextIndex_, and cvLevelSetNode::zNextIndex_.
Referenced by CSRToPolyData(), and GetPhi().
int cvLevelSetSparseGrid::PackagePartition (int partNum)
Definition at line 3446 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, gridState_, localSize_, numSparseNodes_, packageSize_, SGST_PackagingComplete, and SGST_Partitioned.
int cvLevelSetSparseGrid::PartitionGraph (int numParts)
Definition at line 3395 of file cvLevelSetSparseGrid.cxx.
References color_, CV_ERROR, CV_OK, gridState_, numParts_, numSparseNodes_, SGST_CSR, and SGST_Partitioned.
cvPolyData * cvLevelSetSparseGrid::PartitionToPolyData (int partNum)
Definition at line 3177 of file cvLevelSetSparseGrid.cxx.
References adjIa_, adjJa_, BuildGlobalToLocalMap(), CV_ERROR, CV_OK, GetPartSize(), cvLevelSetStructuredGrid::grid_, gridState_, numSparseNodes_, cvLevelSetNode::pos_, and SGST_Partitioned.
int cvLevelSetSparseGrid::PollNeighborSigns (int i, int j, int k) private
Definition at line 1433 of file cvLevelSetSparseGrid.cxx.
References cvStateArray::GetSign(), cvLevelSetStructuredGrid::I_, IJKToDenseIx(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, and topoOverlay_.
Referenced by ConstructHT_Sweep().
int cvLevelSetSparseGrid::ProjectV (int save) virtual
Implements cvLevelSetStructuredGrid.
Definition at line 2339 of file cvLevelSetSparseGrid.cxx.
References cvLevelSetStructuredGrid::CheckProjectCoverage(), cvLevelSetStructuredGrid::ClearCovered(), CV_ERROR, CV_OK, gridState_, cvLevelSetStructuredGrid::NumActiveNodes(), cvLevelSetStructuredGrid::ProjectV(), ReinitPhi(), cvLevelSetStructuredGrid::ResetNodeSets(), and SGST_CSR.
int cvLevelSetSparseGrid::ReinitPhi () virtual
Implements cvLevelSetStructuredGrid.
Definition at line 729 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, cvPolyData::FindDistance(), cvLevelSetStructuredGrid::GetFront(), GetNext(), cvPolyData::GetVtkPolyData(), gridState_, InitIter(), cvLevelSetNode::phi_, cvLevelSetNode::pos_, SGST_CSR, and cvLevelSetStructuredGrid::tol_.
Referenced by ProjectV().
int cvLevelSetSparseGrid::SanityCheckCSR () private
Definition at line 1891 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, GetNeighborSparseIxs(), GetNext(), cvLevelSetStructuredGrid::grid_, cvLevelSetNode::i_, cvLevelSetStructuredGrid::I_, IJKPresentInCSR(), IJKToDenseIx(), IJKToIndex(), cvLevelSetNode::index_, InitIter(), cvLevelSetNode::j_, cvLevelSetStructuredGrid::J_, cvLevelSetNode::k_, cvLevelSetStructuredGrid::K_, cvLevelSetNode::logicalIx_, NULL, and numSparseNodes_.
int cvLevelSetSparseGrid::SetBandParams (double innerPhi, double outerPhi, double mineWidth) virtual
Reimplemented from cvLevelSetStructuredGrid.
Definition at line 224 of file cvLevelSetSparseGrid.cxx.
References CV_ERROR, CV_OK, gridState_, innerExtent2_, innerExtent_, cvLevelSetStructuredGrid::mainDiagonal_, mineWidth2_, mineWidth_, outerExtent2_, outerExtent_, cvLevelSetStructuredGrid::relTol_, and SGST_ExtentDefined.
int cvLevelSetSparseGrid::SetNeighborInfo (cvLevelSetNode * node) private
Definition at line 2195 of file cvLevelSetSparseGrid.cxx.
References cvLevelSetNode::i_, IJKPresentInCSR(), cvLevelSetNode::index_, cvLevelSetNode::j_, cvLevelSetNode::k_, NULL, cvLevelSetNode::xNextIndex_, cvLevelSetNode::xPrevIndex_, cvLevelSetNode::yNextIndex_, cvLevelSetNode::yPrevIndex_, cvLevelSetNode::zNextIndex_, and cvLevelSetNode::zPrevIndex_.
Referenced by ConstructCSR().
char * cvLevelSetSparseGrid::StatString () virtual
Implements cvLevelSetStructuredGrid.
Definition at line 2965 of file cvLevelSetSparseGrid.cxx.
References CV_STRLEN, gridState_, numBuckets_, numSparseNodes_, and SGST_CSR.
int cvLevelSetSparseGrid::Sweep (int sign, int levels) private
Definition at line 1542 of file cvLevelSetSparseGrid.cxx.
References cvIntArrayList::Append(), cvStateArray::ClearSwept(), CV_ERROR, CV_OK, cvLevelSetStructuredGrid::GetAdjacentIxs(), cvStateArray::GetSign(), cvLevelSetStructuredGrid::I_, IJKToDenseIx(), cvIntArrayList::IsEmpty(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, cvIntArrayList::RemoveFromHead(), cvIntArrayList::Reset(), cvStateArray::SetSwept(), STATE_NODE_ACTIVE, STATE_NODE_SWEPT, cvStateArray::SweptToCovered(), and topoOverlay_.
void cvLevelSetSparseGrid::Sweep_ComparePair (int currIx, int currSign, int ip, int jp, int kp) private
Definition at line 1519 of file cvLevelSetSparseGrid.cxx.
References cvStateArray::GetSign(), IJKToDenseIx(), cvLevelSetStructuredGrid::IxWithinExtent(), cvStateArray::SetActive(), and topoOverlay_.
Referenced by Sweep_MarkActiveNodes().
void cvLevelSetSparseGrid::Sweep_MarkActiveNodes () private
Definition at line 1485 of file cvLevelSetSparseGrid.cxx.
References cvStateArray::ClearActive(), cvStateArray::ClearCovered(), cvStateArray::GetSign(), cvLevelSetStructuredGrid::I_, IJKToDenseIx(), cvLevelSetStructuredGrid::J_, cvLevelSetStructuredGrid::K_, cvStateArray::SetActive(), Sweep_ComparePair(), and topoOverlay_.
Referenced by ConstructHT_Sweep().
void cvLevelSetSparseGrid::TopoUpdate () private
Definition at line 2081 of file cvLevelSetSparseGrid.cxx.
References GetNext(), gridState_, cvLevelSetNode::i_, IJKToDenseIx(), InitIter(), IntSign(), cvLevelSetNode::j_, cvLevelSetNode::k_, cvLevelSetNode::phi_, SGST_CSR, STATE_PHI_INSIDE, STATE_PHI_MASK, STATE_PHI_ON, STATE_PHI_OUTSIDE, and cvLevelSetStructuredGrid::tol_.
Referenced by ConstructHT(), and ConstructHT_Sweep().
void cvLevelSetSparseGrid::UndoTimeStep () private
Definition at line 2631 of file cvLevelSetSparseGrid.cxx.
References cvLevelSetNode::deltaPhi_, GetNext(), InitIter(), and cvLevelSetNode::phi_.
Referenced by UpdatePhi().
int cvLevelSetSparseGrid::UpdatePhi () virtual
Reimplemented from cvLevelSetStructuredGrid.
Definition at line 2458 of file cvLevelSetSparseGrid.cxx.
References BAND_SWEEP, bandMethod_, closedPhiVtkValid_, CV_ERROR, CV_NODE_ACTIVE, CV_NODE_COVERED, CV_NODE_MINE, CV_OK, cvLevelSetStructuredGrid::d0Valid_, cvLevelSetStructuredGrid::delMinusValid_, cvLevelSetStructuredGrid::delPlusValid_, cvLevelSetNode::deltaPhi_, cvLevelSetStructuredGrid::deltaPhiValid_, cvLevelSetStructuredGrid::dmiValid_, cvLevelSetStructuredGrid::dpiValid_, cvLevelSetStructuredGrid::GetFront(), GetNext(), InitIter(), InitPhi(), IntSign(), cvLevelSetStructuredGrid::k3dgValid_, cvLevelSetStructuredGrid::k3dmValid_, cvLevelSetStructuredGrid::kValid_, mineHit_, cvLevelSetStructuredGrid::nValid_, cvLevelSetNode::phi_, cvLevelSetStructuredGrid::phiVtkValid_, cvLevelSetNode::state_, cvLevelSetStructuredGrid::tol_, and UndoTimeStep().
Member Data Documentation
int* cvLevelSetSparseGrid::adjIa_ private
Definition at line 228 of file cvLevelSetSparseGrid.h.
Referenced by ConstructCSR(), cvLevelSetSparseGrid(), DeallocateCSR(), GetMemoryUsage(), PartitionToPolyData(), and ~cvLevelSetSparseGrid().
int* cvLevelSetSparseGrid::adjJa_ private
Definition at line 229 of file cvLevelSetSparseGrid.h.
Referenced by ConstructCSR(), cvLevelSetSparseGrid(), DeallocateCSR(), GetMemoryUsage(), PartitionToPolyData(), and ~cvLevelSetSparseGrid().
cvLevelSetSparseGridBandT cvLevelSetSparseGrid::bandMethod_ private
Definition at line 273 of file cvLevelSetSparseGrid.h.
Referenced by cvLevelSetSparseGrid(), InitPhi(), InitPhi_Internal(), and UpdatePhi().
int cvLevelSetSparseGrid::closedPhiVtkValid_ private
Definition at line 235 of file cvLevelSetSparseGrid.h.
Referenced by cvLevelSetSparseGrid(), InitPhi(), InitPhi_Internal(), MakeClosedPhiVtk(), MakePhiVtk(), and UpdatePhi().
int* cvLevelSetSparseGrid::color_ private
Definition at line 238 of file cvLevelSetSparseGrid.h.
Referenced by BuildGlobalToLocalMap(), BuildLocalToGlobalMap(), ClearPartitioning(), cvLevelSetSparseGrid(), GetMemoryUsage(), GetPartSize(), and PartitionGraph().
int cvLevelSetSparseGrid::currIx_ private
Definition at line 142 of file cvLevelSetSparseGrid.h.
Referenced by cvLevelSetSparseGrid(), GetNext(), and InitIter().
cvLevelSetSparseGridStateT cvLevelSetSparseGrid::gridState_ private
Definition at line 272 of file cvLevelSetSparseGrid.h.
Referenced by BuildL1Map(), ConstructCSR(), ConstructHT(), ConstructHT_Sweep(), cvLevelSetSparseGrid(), GetBandParams(), GetCSRStructure(), GetNextHTItem(), GetNumBandNodes(), IJKToSparseIx(), InitHTIterator(), InitIxBuffer(), InitNodeSets(), MakeClosedPhiVtk(), MakePhiVtk(), PackagePartition(), PartitionGraph(), PartitionToPolyData(), ProjectV(), ReinitPhi(), SetBandParams(), StatString(), and TopoUpdate().
int cvLevelSetSparseGrid::htCurrBucketId_ private
Definition at line 203 of file cvLevelSetSparseGrid.h.
Referenced by GetNextHTItem(), and InitHTIterator().
cvLispListIterator<TableStruct*>* cvLevelSetSparseGrid::htIter_ private
Definition at line 204 of file cvLevelSetSparseGrid.h.
Referenced by cvLevelSetSparseGrid(), GetMemoryUsage(), GetNextHTItem(), and InitHTIterator().
int cvLevelSetSparseGrid::iaSz_ private
Definition at line 230 of file cvLevelSetSparseGrid.h.
Referenced by ConstructCSR(), cvLevelSetSparseGrid(), DeallocateCSR(), and GetMemoryUsage().
double cvLevelSetSparseGrid::innerExtent2_ private
Definition at line 263 of file cvLevelSetSparseGrid.h.
Referenced by ConstructHT(), and SetBandParams().
double cvLevelSetSparseGrid::innerExtent_ private
Definition at line 260 of file cvLevelSetSparseGrid.h.
Referenced by ConstructHT(), ConstructHT_Sweep(), GetBandParams(), and SetBandParams().
int cvLevelSetSparseGrid::jaSz_ private
Definition at line 231 of file cvLevelSetSparseGrid.h.
Referenced by ConstructCSR(), cvLevelSetSparseGrid(), DeallocateCSR(), and GetMemoryUsage().
int* cvLevelSetSparseGrid::L1map_ private
Definition at line 252 of file cvLevelSetSparseGrid.h.
Referenced by BuildL1Map(), cvLevelSetSparseGrid(), and GetMemoryUsage().
int* cvLevelSetSparseGrid::L2map_ private
Definition at line 253 of file cvLevelSetSparseGrid.h.
Referenced by cvLevelSetSparseGrid(), and GetMemoryUsage().
int cvLevelSetSparseGrid::localSize_ private
Definition at line 242 of file cvLevelSetSparseGrid.h.
Referenced by PackagePartition().
int cvLevelSetSparseGrid::mineHit_ private
Definition at line 266 of file cvLevelSetSparseGrid.h.
Referenced by cvLevelSetSparseGrid(), GridModified(), and UpdatePhi().
double cvLevelSetSparseGrid::mineWidth2_ private
Definition at line 264 of file cvLevelSetSparseGrid.h.
Referenced by SetBandParams().
double cvLevelSetSparseGrid::mineWidth_ private
Definition at line 261 of file cvLevelSetSparseGrid.h.
Referenced by ConstructHT(), ConstructHT_Sweep(), GetBandParams(), and SetBandParams().
cvSortedList<TableStruct*>** cvLevelSetSparseGrid::nodeTable_ private
Definition at line 199 of file cvLevelSetSparseGrid.h.
Referenced by ClearHT(), ConstructHT(), ConstructHT_Sweep(), cvLevelSetSparseGrid(), GetMemoryUsage(), GetNextHTItem(), IJKPresentInHT(), and InitHTIterator().
int cvLevelSetSparseGrid::numBuckets_ private
Definition at line 200 of file cvLevelSetSparseGrid.h.
Referenced by ClearHT(), ComputeHashIx(), cvLevelSetSparseGrid(), GetMemoryUsage(), GetNextHTItem(), and StatString().
int cvLevelSetSparseGrid::numParts_ private
Definition at line 239 of file cvLevelSetSparseGrid.h.
Referenced by BuildGlobalToLocalMap(), GetPartSize(), and PartitionGraph().
int cvLevelSetSparseGrid::numSparseEdges_ private
Definition at line 226 of file cvLevelSetSparseGrid.h.
Referenced by ConstructCSR(), and cvLevelSetSparseGrid().
int cvLevelSetSparseGrid::numSparseNodes_ private
Definition at line 225 of file cvLevelSetSparseGrid.h.
Referenced by BuildGlobalToLocalMap(), BuildL1Map(), BuildLocalToGlobalMap(), ConstructCSR(), ConstructHT(), ConstructHT_Sweep(), cvLevelSetSparseGrid(), DeallocateNodes(), GetCSRStructure(), GetMemoryUsage(), GetNext(), GetNumBandNodes(), GetPartSize(), IJKToSparseIx(), InitIxBuffer(), InitNodeSets(), MakePhiVtk(), PackagePartition(), PartitionGraph(), PartitionToPolyData(), SanityCheckCSR(), and StatString().
double cvLevelSetSparseGrid::outerExtent2_ private
Definition at line 262 of file cvLevelSetSparseGrid.h.
Referenced by ConstructHT(), and SetBandParams().
double cvLevelSetSparseGrid::outerExtent_ private
Definition at line 259 of file cvLevelSetSparseGrid.h.
Referenced by ConstructHT(), ConstructHT_Sweep(), GetBandParams(), and SetBandParams().
int cvLevelSetSparseGrid::overlaySz_ private
Definition at line 215 of file cvLevelSetSparseGrid.h.
Referenced by cvLevelSetSparseGrid().
int cvLevelSetSparseGrid::packageSize_ private
Definition at line 243 of file cvLevelSetSparseGrid.h.
Referenced by PackagePartition().
cvPolyData* cvLevelSetSparseGrid::seedInterface_ private
Definition at line 156 of file cvLevelSetSparseGrid.h.
Referenced by BuildSeedInterface(), ClearSeedInterface(), ConstructHT(), cvLevelSetSparseGrid(), and GetMemoryUsage().
cvStateArray* cvLevelSetSparseGrid::topoOverlay_ private
Definition at line 214 of file cvLevelSetSparseGrid.h.
Referenced by Blot(), ConstructHT(), ConstructHT_Sweep(), cvLevelSetSparseGrid(), GetMemoryUsage(), MakeClosedPhiVtk(), PollNeighborSigns(), Sweep(), Sweep_ComparePair(), Sweep_MarkActiveNodes(), and ~cvLevelSetSparseGrid().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetSparseGrid.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetSparseGrid.cxx