simvascular: cvLevelSetVelocityExponentialDecay Class Reference
cvLevelSetVelocityExponentialDecay Class Reference
#include <cvLevelSetVelocityExponentialDecay.h>
Public Member Functions
cvLevelSetVelocityExponentialDecay ()
~cvLevelSetVelocityExponentialDecay ()
int SetEI (double d)
double GetEI ()
int SetEIneg (double d)
int GetEIneg (double *d)
int SetKt (double d)
double GetKt ()
int Set3DKType (char *kt_name)
int Set3DKType (cvLevelSetVelocityExponentialDecay3DKT kt)
int Get3DKType (cvLevelSetVelocityExponentialDecay3DKT *kt)
void SetClamp (int f)
int GetClamp ()
void SetMonotonic (int f)
int GetMonotonic ()
void SetExpand (int f)
int GetExpand ()
int Valid ()
int StopCondition ()
int Evaluate (double pos[], double *f0, double *f1, double v[], int *forceFlag, double toDot[])
int GetMemoryUsage ()
Public Member Functions inherited from cvLevelSetVelocityImage
cvLevelSetVelocityImage ()
virtual ~cvLevelSetVelocityImage ()
int SetImage (Image_T *i, int closed=0)
int SetImage (char *filebase, int fileNumRange[], int imgDims[], double pixDims[], int closed=0)
int SetImage (short *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (double *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (float *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int GetImage (Image_T **i)
int GetMagGradRange (double rng[])
int GetXYMagGradRange (double rng[])
int GetZMagGradRange (double rng[])
int GetIntensityRange (double rng[])
int ClearImage ()
virtual void PostSetImageAction ()
Public Member Functions inherited from cvLevelSetVelocity
cvLevelSetVelocity ()
virtual ~cvLevelSetVelocity ()
int LinkLevelSet (cvLevelSet *ls)
int UnlinkLevelSet ()
int GetLevelSet (cvLevelSet **ls)
int UpdateTolerance ()
void SetStopV (double d)
double GetStopV ()
Private Attributes
double eI_
double eIneg_
double Kt_
int clamp_
int monotonic_
int expand_
int eInegValid_
cvLevelSetVelocityExponentialDecay3DKT ktype_
Additional Inherited Members
Public Attributes inherited from cvLevelSetVelocity
char tclName_ [CV_STRLEN]
Protected Member Functions inherited from cvLevelSetVelocityImage
int GetImgSize ()
Protected Attributes inherited from cvLevelSetVelocityImage
Image_T * image_
Protected Attributes inherited from cvLevelSetVelocity
cvLevelSet * ls_
double tol_
double stopV_
Detailed Description
Definition at line 46 of file cvLevelSetVelocityExponentialDecay.h.
Constructor & Destructor Documentation
cvLevelSetVelocityExponentialDecay::cvLevelSetVelocityExponentialDecay ()
Definition at line 41 of file cvLevelSetVelocityExponentialDecay.cxx.
References clamp_, eI_, eInegValid_, expand_, Kt_, ktype_, monotonic_, and VED_Mean_K.
cvLevelSetVelocityExponentialDecay::~cvLevelSetVelocityExponentialDecay ()
Definition at line 57 of file cvLevelSetVelocityExponentialDecay.cxx.
Member Function Documentation
int cvLevelSetVelocityExponentialDecay::Evaluate (double pos[], double * f0, double * f1, double v[], int * forceFlag, double toDot[]) virtual
Implements cvLevelSetVelocity.
Definition at line 240 of file cvLevelSetVelocityExponentialDecay.cxx.
References clamp_, Compute3dks(), CV_ERROR, CV_OK, Image_T::dim, Dot(), eI_, eIneg_, eInegValid_, expand_, cvLevelSetStructuredGrid::GetDim(), GetGradIx(), GetGradIy(), GetGradIz(), cvLevelSet::GetGrid(), GetImageClosed(), cvLevelSetVelocityImage::image_, InBorder(), cvLevelSetStructuredGrid::InterpK(), cvLevelSetStructuredGrid::InterpKg(), cvLevelSetStructuredGrid::InterpKm(), cvLevelSetStructuredGrid::InterpN(), K, Kt_, ktype_, cvLevelSetVelocity::ls_, Magnitude(), monotonic_, NULL, cvLevelSetVelocity::stopV_, cvLevelSetVelocity::tol_, Valid(), VED_Default_K, VED_Gaussian_K, VED_Mean_K, VED_PrincipleK1_K, and VED_PrincipleK2_K.
int cvLevelSetVelocityExponentialDecay::Get3DKType (cvLevelSetVelocityExponentialDecay3DKT * kt)
Definition at line 160 of file cvLevelSetVelocityExponentialDecay.cxx.
References CV_OK, and ktype_.
Referenced by LsetVExpDecay_GetConstMtd().
int cvLevelSetVelocityExponentialDecay::GetClamp () inline
Definition at line 66 of file cvLevelSetVelocityExponentialDecay.h.
References clamp_.
Referenced by LsetVExpDecay_GetConstMtd().
double cvLevelSetVelocityExponentialDecay::GetEI () inline
Definition at line 53 of file cvLevelSetVelocityExponentialDecay.h.
References eI_.
Referenced by LsetVExpDecay_GetConstMtd().
int cvLevelSetVelocityExponentialDecay::GetEIneg (double * d)
Definition at line 104 of file cvLevelSetVelocityExponentialDecay.cxx.
References CV_ERROR, CV_OK, eIneg_, and eInegValid_.
Referenced by LsetVExpDecay_GetConstMtd().
int cvLevelSetVelocityExponentialDecay::GetExpand () inline
Definition at line 72 of file cvLevelSetVelocityExponentialDecay.h.
References expand_.
Referenced by LsetVExpDecay_GetConstMtd().
double cvLevelSetVelocityExponentialDecay::GetKt () inline
Definition at line 59 of file cvLevelSetVelocityExponentialDecay.h.
References Kt_.
Referenced by LsetVExpDecay_GetConstMtd().
int cvLevelSetVelocityExponentialDecay::GetMemoryUsage () virtual
Implements cvLevelSetVelocity.
Definition at line 406 of file cvLevelSetVelocityExponentialDecay.cxx.
References cvLevelSetVelocityImage::image_, and Img_GetMemoryUsage().
int cvLevelSetVelocityExponentialDecay::GetMonotonic () inline
Definition at line 69 of file cvLevelSetVelocityExponentialDecay.h.
References monotonic_.
Referenced by LsetVExpDecay_GetConstMtd().
int cvLevelSetVelocityExponentialDecay::Set3DKType (char * kt_name)
Definition at line 131 of file cvLevelSetVelocityExponentialDecay.cxx.
References DKT_StrToEnum().
Referenced by LsetVExpDecay_SetConstMtd().
int cvLevelSetVelocityExponentialDecay::Set3DKType (cvLevelSetVelocityExponentialDecay3DKT kt)
Definition at line 144 of file cvLevelSetVelocityExponentialDecay.cxx.
References CV_ERROR, CV_OK, ktype_, and VED_Invalid_K.
void cvLevelSetVelocityExponentialDecay::SetClamp (int f)
Definition at line 171 of file cvLevelSetVelocityExponentialDecay.cxx.
References clamp_.
Referenced by LsetVExpDecay_SetConstMtd().
int cvLevelSetVelocityExponentialDecay::SetEI (double d)
Definition at line 67 of file cvLevelSetVelocityExponentialDecay.cxx.
References CV_OK, and eI_.
Referenced by LsetVExpDecay_SetConstMtd().
int cvLevelSetVelocityExponentialDecay::SetEIneg (double d)
Definition at line 88 of file cvLevelSetVelocityExponentialDecay.cxx.
References CV_OK, eIneg_, and eInegValid_.
Referenced by LsetVExpDecay_SetConstMtd().
void cvLevelSetVelocityExponentialDecay::SetExpand (int f)
Definition at line 201 of file cvLevelSetVelocityExponentialDecay.cxx.
References expand_.
Referenced by LsetVExpDecay_SetConstMtd().
int cvLevelSetVelocityExponentialDecay::SetKt (double d)
Definition at line 118 of file cvLevelSetVelocityExponentialDecay.cxx.
References CV_ERROR, CV_OK, and Kt_.
Referenced by LsetVExpDecay_SetConstMtd().
void cvLevelSetVelocityExponentialDecay::SetMonotonic (int f)
Definition at line 186 of file cvLevelSetVelocityExponentialDecay.cxx.
References monotonic_.
int cvLevelSetVelocityExponentialDecay::StopCondition () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 230 of file cvLevelSetVelocityExponentialDecay.cxx.
int cvLevelSetVelocityExponentialDecay::Valid () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 216 of file cvLevelSetVelocityExponentialDecay.cxx.
References cvLevelSetVelocityImage::image_, NULL, and cvLevelSetVelocity::Valid().
Referenced by Evaluate().
Member Data Documentation
int cvLevelSetVelocityExponentialDecay::clamp_ private
Definition at line 85 of file cvLevelSetVelocityExponentialDecay.h.
Referenced by cvLevelSetVelocityExponentialDecay(), Evaluate(), GetClamp(), and SetClamp().
double cvLevelSetVelocityExponentialDecay::eI_ private
Definition at line 82 of file cvLevelSetVelocityExponentialDecay.h.
Referenced by cvLevelSetVelocityExponentialDecay(), Evaluate(), GetEI(), and SetEI().
double cvLevelSetVelocityExponentialDecay::eIneg_ private
Definition at line 83 of file cvLevelSetVelocityExponentialDecay.h.
Referenced by Evaluate(), GetEIneg(), and SetEIneg().
int cvLevelSetVelocityExponentialDecay::eInegValid_ private
Definition at line 88 of file cvLevelSetVelocityExponentialDecay.h.
Referenced by cvLevelSetVelocityExponentialDecay(), Evaluate(), GetEIneg(), and SetEIneg().
int cvLevelSetVelocityExponentialDecay::expand_ private
Definition at line 87 of file cvLevelSetVelocityExponentialDecay.h.
Referenced by cvLevelSetVelocityExponentialDecay(), Evaluate(), GetExpand(), and SetExpand().
double cvLevelSetVelocityExponentialDecay::Kt_ private
Definition at line 84 of file cvLevelSetVelocityExponentialDecay.h.
Referenced by cvLevelSetVelocityExponentialDecay(), Evaluate(), GetKt(), and SetKt().
cvLevelSetVelocityExponentialDecay3DKT cvLevelSetVelocityExponentialDecay::ktype_ private
Definition at line 89 of file cvLevelSetVelocityExponentialDecay.h.
Referenced by cvLevelSetVelocityExponentialDecay(), Evaluate(), Get3DKType(), and Set3DKType().
int cvLevelSetVelocityExponentialDecay::monotonic_ private
Definition at line 86 of file cvLevelSetVelocityExponentialDecay.h.
Referenced by cvLevelSetVelocityExponentialDecay(), Evaluate(), GetMonotonic(), and SetMonotonic().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityExponentialDecay.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityExponentialDecay.cxx