simvascular: cvSortedList< T > Class Template Reference
cvSortedList< T > Class Template Reference
#include <cvLispList.h>
Public Member Functions
cvSortedList (int(*comp)(T x, T y))
~cvSortedList ()
void Insert (T item)
void SanityCheck () const
void SelfTest (T *p, int numEntries)
Public Member Functions inherited from cvLispList< T >
cvLispList ()
virtual ~cvLispList ()
T Front ()
T RemoveFront ()
void Remove (T item)
Bool IsInList (T item) const
unsigned int NumInList ()
Bool IsEmpty ()
void Apply (void(*f)(T)) const
void SelfTest (T *p, int numEntries)
Private Member Functions
void Prepend (T item)
void Append (T item)
Private Attributes
int(* compare)(T x, T y)
Additional Inherited Members
Protected Attributes inherited from cvLispList< T >
cvLispListElement< T > * first
cvLispListElement< T > * last
int numInList
Detailed Description
template<class T>
class cvSortedList< T >
Definition at line 153 of file cvLispList.h.
Constructor & Destructor Documentation
template<class T> cvSortedList< T >::cvSortedList (int(*)(T x, T y) comp) inline
Definition at line 155 of file cvLispList.h.
template<class T> cvSortedList< T >::~cvSortedList () inline
Definition at line 156 of file cvLispList.h.
Member Function Documentation
template<class T> void cvSortedList< T >::Append (T item) inline private virtual
Reimplemented from cvLispList< T >.
Definition at line 169 of file cvLispList.h.
template<class T> void cvSortedList< T >::Insert (T item)
Definition at line 301 of file cvLispList.cxx.
References Assert, cvLispListElement< T >::item, cvLispListElement< T >::next, and NULL.
Referenced by cvSortedList< TableStruct * >::Append(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::ConstructHT_Sweep(), and cvSortedList< TableStruct * >::Prepend().
template<class T> void cvSortedList< T >::Prepend (T item) inline private virtual
Reimplemented from cvLispList< T >.
Definition at line 167 of file cvLispList.h.
template<class T > void cvSortedList< T >::SanityCheck () const virtual
Reimplemented from cvLispList< T >.
Definition at line 403 of file cvLispList.cxx.
References Assert, cvLispListElement< T >::item, cvLispListElement< T >::next, NULL, and cvLispList< T >::SanityCheck().
template<class T> void cvSortedList< T >::SelfTest (T * p, int numEntries)
Definition at line 423 of file cvLispList.cxx.
References Assert, cvLispList< T >::SelfTest(), and T.
Member Data Documentation
template<class T> int(* cvSortedList< T >::compare)(T x, T y) private
Definition at line 165 of file cvLispList.h.
Referenced by cvSortedList< TableStruct * >::cvSortedList().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvLispList.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvLispList.cxx