simvascular: vtkvmtkUnstructuredGridTetraFilter Class Reference
vtkvmtkUnstructuredGridTetraFilter Class Reference
#include <vtkvmtkUnstructuredGridTetraFilter.h>
Public Member Functions
vtkTypeMacro (vtkvmtkUnstructuredGridTetraFilter, vtkUnstructuredGridAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
vtkSetMacro (TetrahedraOnly, int)
vtkGetMacro (TetrahedraOnly, int)
vtkBooleanMacro (TetrahedraOnly, int)
Static Public Member Functions
static
vtkvmtkUnstructuredGridTetraFilter * New ()
Protected Member Functions
vtkvmtkUnstructuredGridTetraFilter ()
~vtkvmtkUnstructuredGridTetraFilter ()
virtual int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
int TriangulateQuad (vtkUnstructuredGrid *output, vtkIdList *quadPtIds, vtkIdList *ptIds)
void Execute (vtkUnstructuredGrid *, vtkUnstructuredGrid *)
Protected Attributes
vtkOrderedTriangulator * Triangulator
int TetrahedraOnly
Private Member Functions
vtkvmtkUnstructuredGridTetraFilter (const vtkvmtkUnstructuredGridTetraFilter &)
void operator= (const vtkvmtkUnstructuredGridTetraFilter &)
Detailed Description
Definition at line 34 of file vtkvmtkUnstructuredGridTetraFilter.h.
Constructor & Destructor Documentation
vtkvmtkUnstructuredGridTetraFilter::vtkvmtkUnstructuredGridTetraFilter () protected
Definition at line 39 of file vtkvmtkUnstructuredGridTetraFilter.cxx.
References TetrahedraOnly, and Triangulator.
vtkvmtkUnstructuredGridTetraFilter::~vtkvmtkUnstructuredGridTetraFilter () protected
Definition at line 47 of file vtkvmtkUnstructuredGridTetraFilter.cxx.
References NULL, and Triangulator.
vtkvmtkUnstructuredGridTetraFilter::vtkvmtkUnstructuredGridTetraFilter (const vtkvmtkUnstructuredGridTetraFilter &) private
Member Function Documentation
void vtkvmtkUnstructuredGridTetraFilter::Execute (vtkUnstructuredGrid * dataSetInput, vtkUnstructuredGrid * output) protected
Definition at line 112 of file vtkvmtkUnstructuredGridTetraFilter.cxx.
References input(), NULL, TetrahedraOnly, TriangulateQuad(), and Triangulator.
Referenced by RequestData().
static vtkvmtkUnstructuredGridTetraFilter* vtkvmtkUnstructuredGridTetraFilter::New () static
void vtkvmtkUnstructuredGridTetraFilter::operator= (const vtkvmtkUnstructuredGridTetraFilter &) private
void vtkvmtkUnstructuredGridTetraFilter::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 283 of file vtkvmtkUnstructuredGridTetraFilter.cxx.
References TetrahedraOnly.
int vtkvmtkUnstructuredGridTetraFilter::RequestData (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected virtual
Definition at line 53 of file vtkvmtkUnstructuredGridTetraFilter.cxx.
References Execute(), and input().
int vtkvmtkUnstructuredGridTetraFilter::TriangulateQuad (vtkUnstructuredGrid * output, vtkIdList * quadPtIds, vtkIdList * ptIds) protected
Definition at line 75 of file vtkvmtkUnstructuredGridTetraFilter.cxx.
Referenced by Execute().
vtkvmtkUnstructuredGridTetraFilter::vtkBooleanMacro (TetrahedraOnly , int)
vtkvmtkUnstructuredGridTetraFilter::vtkGetMacro (TetrahedraOnly , int)
vtkvmtkUnstructuredGridTetraFilter::vtkSetMacro (TetrahedraOnly , int)
vtkvmtkUnstructuredGridTetraFilter::vtkTypeMacro (vtkvmtkUnstructuredGridTetraFilter , vtkUnstructuredGridAlgorithm)
Member Data Documentation
int vtkvmtkUnstructuredGridTetraFilter::TetrahedraOnly protected
Definition at line 57 of file vtkvmtkUnstructuredGridTetraFilter.h.
Referenced by Execute(), PrintSelf(), and vtkvmtkUnstructuredGridTetraFilter().
vtkOrderedTriangulator* vtkvmtkUnstructuredGridTetraFilter::Triangulator protected
Definition at line 53 of file vtkvmtkUnstructuredGridTetraFilter.h.
Referenced by Execute(), vtkvmtkUnstructuredGridTetraFilter(), and ~vtkvmtkUnstructuredGridTetraFilter().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkUnstructuredGridTetraFilter.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkUnstructuredGridTetraFilter.cxx