simvascular: cvMath Class Reference
cvMath Class Reference
#include <cvMath.h>
Public Member Functions
cvMath ()
~cvMath ()
double ** createArray (int a, int b)
void deleteArray (double **ptr, int a, int b)
int linearInterpolate (double **orgPts, int numOrgPts, double t0, double dt, int numOutPts, double ***outPts)
int linearInterpolateCurve (double **orgPts, int numOrgPts, int closed, int numOutPts, double ***rtnOutPts)
void FFT (double Qdata[], int nn, int isign)
int FFT (double **pts, int numPts, int numInterpPts, int numDesiredTerms, double ***terms)
int inverseFFT (double **terms, int numTerms, double t0, double dt, double omega, int numRtnPts, double ***rtnPts)
int compute_v_womersley (double **terms, int numTerms, double viscosity, double density, double omega, double radmax, double rad, double time, double *v)
int curveLength (double **pts, int numPts, int closed, double *length)
int smoothCurve (double **orgPts, int numOrgPts, int closed, int keepNumModes, int numOutPts, double ***rtnOutPts)
int fitLeastSquares (int numberOfSamples, double **xt, int xOrder, double **yt, int yOrder, double **mt)
Private Member Functions
int complex_mult (double z1[], double z2[], double zout[])
double complex_mag (double z1[])
int complex_div (double z1[], double z2[], double zout[])
double factrl (int n)
int ber_bei (int order, double x, double z[])
double compute_velocity (int k, double omega, double time, double radmax, double alpha_k, double Y, double Qk[])
Detailed Description
Definition at line 40 of file cvMath.h.
Constructor & Destructor Documentation
cvMath::cvMath ()
Definition at line 43 of file cvMath.cxx.
cvMath::~cvMath ()
Definition at line 46 of file cvMath.cxx.
Member Function Documentation
int cvMath::ber_bei (int order, double x, double z[]) private
Definition at line 329 of file cvMath.cxx.
References factrl(), and order.
Referenced by compute_velocity().
int cvMath::complex_div (double z1[], double z2[], double zout[]) private
Definition at line 427 of file cvMath.cxx.
References complex_mag().
Referenced by compute_velocity().
double cvMath::complex_mag (double z1[]) private
Definition at line 416 of file cvMath.cxx.
Referenced by complex_div().
int cvMath::complex_mult (double z1[], double z2[], double zout[]) private
Definition at line 406 of file cvMath.cxx.
Referenced by compute_velocity().
int cvMath::compute_v_womersley (double ** terms, int numTerms, double viscosity, double density, double omega, double radmax, double rad, double time, double * v)
Definition at line 270 of file cvMath.cxx.
References compute_velocity(), CV_OK, and Y.
Referenced by Math_computeWomersleyCmd().
double cvMath::compute_velocity (int k, double omega, double time, double radmax, double alpha_k, double Y, double Qk[]) private
Definition at line 297 of file cvMath.cxx.
References ber_bei(), complex_div(), and complex_mult().
Referenced by compute_v_womersley().
double ** cvMath::createArray (int a, int b)
Definition at line 50 of file cvMath.cxx.
References NULL.
Referenced by FFT(), img_calcCorrectionEqn(), img_calcCorrectionEqnAuto(), inverseFFT(), linearInterpolate(), linearInterpolateCurve(), Math_computeWomersleyCmd(), Math_curveLengthCmd(), Math_FFTCmd(), Math_fitLeastSquaresCmd(), Math_inverseFFTCmd(), Math_linearInterpCmd(), Math_linearInterpolateCurveCmd(), Math_smoothCurveCmd(), smoothCurve(), and sys_geom_sampleLoop().
int cvMath::curveLength (double ** pts, int numPts, int closed, double * length)
Definition at line 440 of file cvMath.cxx.
References CV_ERROR, and CV_OK.
Referenced by linearInterpolateCurve(), Math_curveLengthCmd(), and smoothCurve().
void cvMath::deleteArray (double ** ptr, int a, int b)
Definition at line 70 of file cvMath.cxx.
Referenced by FFT(), img_calcCorrectionEqn(), img_calcCorrectionEqnAuto(), linearInterpolate(), linearInterpolateCurve(), Math_computeWomersleyCmd(), Math_curveLengthCmd(), Math_FFTCmd(), Math_fitLeastSquaresCmd(), Math_inverseFFTCmd(), Math_linearInterpCmd(), Math_linearInterpolateCurveCmd(), Math_smoothCurveCmd(), smoothCurve(), and sys_geom_sampleLoop().
double cvMath::factrl (int n) private
Definition at line 389 of file cvMath.cxx.
Referenced by ber_bei().
void cvMath::FFT (double Qdata[], int nn, int isign)
Definition at line 144 of file cvMath.cxx.
References istep, and SWAP.
Referenced by FFT(), Math_FFTCmd(), and smoothCurve().
int cvMath::FFT (double ** pts, int numPts, int numInterpPts, int numDesiredTerms, double *** terms)
Definition at line 192 of file cvMath.cxx.
References createArray(), CV_ERROR, CV_OK, deleteArray(), FFT(), linearInterpolate(), and NULL.
int cvMath::fitLeastSquares (int numberOfSamples, double ** xt, int xOrder, double ** yt, int yOrder, double ** mt)
Definition at line 578 of file cvMath.cxx.
References CV_ERROR, and CV_OK.
Referenced by img_calcCorrectionEqn(), img_calcCorrectionEqnAuto(), and Math_fitLeastSquaresCmd().
int cvMath::inverseFFT (double ** terms, int numTerms, double t0, double dt, double omega, int numRtnPts, double *** rtnPts)
Definition at line 243 of file cvMath.cxx.
References createArray(), CV_ERROR, CV_OK, and NULL.
Referenced by Math_inverseFFTCmd(), and smoothCurve().
int cvMath::linearInterpolate (double ** orgPts, int numOrgPts, double t0, double dt, int numOutPts, double *** outPts)
Definition at line 77 of file cvMath.cxx.
References createArray(), CV_ERROR, CV_OK, deleteArray(), and NULL.
Referenced by FFT(), linearInterpolateCurve(), and Math_linearInterpCmd().
int cvMath::linearInterpolateCurve (double ** orgPts, int numOrgPts, int closed, int numOutPts, double *** rtnOutPts)
Definition at line 478 of file cvMath.cxx.
References createArray(), curveLength(), CV_ERROR, CV_OK, deleteArray(), linearInterpolate(), and NULL.
Referenced by Math_linearInterpolateCurveCmd(), and sys_geom_sampleLoop().
int cvMath::smoothCurve (double ** orgPts, int numOrgPts, int closed, int keepNumModes, int numOutPts, double *** rtnOutPts)
Definition at line 593 of file cvMath.cxx.
References createArray(), curveLength(), CV_ERROR, CV_OK, deleteArray(), FFT(), inverseFFT(), and NULL.
Referenced by Math_smoothCurveCmd().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvMath.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvMath.cxx