simvascular: cvRepositoryData Class Reference
cvRepositoryData Class Reference
#include <cvRepositoryData.h>
Public Member Functions
cvRepositoryData (RepositoryDataT type)
virtual ~cvRepositoryData ()
void Lock ()
void Release ()
int NumLocks ()
RepositoryDataT GetType ()
char * GetName ()
void SetName (char *in)
int GetNumLabels ()
void GetLabelKeys (int *numKeys, char **keys[])
int IsLabelPresent (char *key)
int GetLabel (char *key, char **value)
int SetLabel (char *key, char *value)
void ClearLabel (char *key)
virtual int GetMemoryUsage ()
Private Attributes
RepositoryDataT type_
char name_ [1024]
int lockCnt_
Tcl_HashTable labels_
Detailed Description
Definition at line 65 of file cvRepositoryData.h.
Constructor & Destructor Documentation
cvRepositoryData::cvRepositoryData (RepositoryDataT type)
Definition at line 101 of file cvRepositoryData.cxx.
References labels_, lockCnt_, name_, and type_.
cvRepositoryData::~cvRepositoryData () virtual
Definition at line 114 of file cvRepositoryData.cxx.
References labels_, and NULL.
Member Function Documentation
void cvRepositoryData::ClearLabel (char * key)
Definition at line 285 of file cvRepositoryData.cxx.
References labels_, and NULL.
Referenced by Repos_ClearLabelCmd(), and Solid_ClearLabelMtd().
int cvRepositoryData::GetLabel (char * key, char ** value)
Definition at line 240 of file cvRepositoryData.cxx.
References labels_, and NULL.
Referenced by Repos_GetLabelCmd(), and Solid_GetLabelMtd().
void cvRepositoryData::GetLabelKeys (int * numKeys, char ** keys[])
Definition at line 197 of file cvRepositoryData.cxx.
References GetNumLabels(), labels_, and NULL.
Referenced by Repos_GetLabelKeysCmd(), and Solid_GetLabelKeysMtd().
virtual int cvRepositoryData::GetMemoryUsage () inline virtual
Reimplemented in cvDataObject.
Definition at line 96 of file cvRepositoryData.h.
Referenced by cvLevelSet::GetMemoryUsage().
char* cvRepositoryData::GetName () inline
Definition at line 84 of file cvRepositoryData.h.
References name_.
Referenced by cvMesh_GenerateQuadraticElementsMtd(), cvMesh_GetBoundaryFacesMtd(), cvMesh_GetElementConnectivityMtd(), cvMesh_GetElementFacesOnModelFaceMtd(), cvMesh_GetElementNodesOnModelFaceMtd(), cvMesh_GetElementsInModelRegionMtd(), cvMesh_GetExteriorElementFacesOnRegionMtd(), cvMesh_GetFacePolyDataMtd(), cvMesh_GetNodeCoordsMtd(), cvMesh_GetPolyDataMtd(), cvMesh_GetUnstructuredGridMtd(), cvMesh_NewObjectCmd(), cvMesh_WriteABAQUSMtd(), cvMesh_WriteDataExplorerMtd(), cvMesh_WriteHypermeshMtd(), cvMesh_WriteMeshVRMLMtd(), cvMesh_WriteMetisAdjacencyMtd(), cvMesh_WritePROPHLEXMtd(), cvMesh_WriteSpectrumSolverElementsMtd(), cvMesh_WriteSpectrumSolverNodesMtd(), cvMesh_WriteSpectrumVisMtd(), cvMesh_WriteSurfaceMeshOOGLMtd(), cvMesh_WriteSurfaceMeshVRMLMtd(), DeletegdscMesh(), DeleteSolid(), FMMHelper(), gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_expNegativeImageCmd(), gdscITK_shapeDetectionCmd(), gdscPost_calcAvgPointDataCmd(), gdscPost_calcOSICmd(), gdscPost_calcTKECmd(), gdscPost_calcWallShearCmd(), gdscPost_calcWallShearMeanCmd(), gdscPost_calcWallShearPulseCmd(), gdscPost_readVisMeshCmd(), gdscPost_readVisResCmd(), Geom_AddPointDataCmd(), Geom_AlignProfileCmd(), Geom_CopyCmd(), Geom_DisorientProfileCmd(), Geom_DividePointDataCmd(), Geom_GetClosedLineRegionCmd(), Geom_IntersectCmd(), Geom_MakePolysConsistentCmd(), Geom_MergePtsCmd(), Geom_MultiplyPointDataCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_ProjectCmd(), Geom_ReduceCmd(), Geom_ReorderPgnCmd(), Geom_ReplacePointDataCmd(), Geom_ReverseAllCellsCmd(), Geom_RmSmallPolysCmd(), Geom_sampleLoopCmd(), Geom_ScaleAvgCmd(), Geom_SubtractCmd(), Geom_SubtractPointDataCmd(), Geom_TranslateCmd(), Geom_UnionCmd(), Geom_Warp3dPtsCmd(), Image_CreateDistanceMapCmd(), Image_DecodeCmd(), Image_FindPathCmd(), Image_MaskInPlaceCmd(), Image_ThresholdCmd(), itkutils_GenerateCircleCmd(), itkutils_PdToImgCmd(), itkutils_PdToVolCmd(), LsetCore_ExtractActiveNodesMtd(), LsetCore_ExtractCurvatureMtd(), LsetCore_ExtractFrontMtd(), LsetCore_ExtractPhiMtd(), LsetCore_ExtractVelMtd(), LsetCore_GetBoundaryDataMtd(), LsetCore_GetImageSeedMtd(), LsetCore_GetPdSeedMtd(), LsetCore_GetSolidSeedMtd(), LsetCore_SaveGridMtd(), LsetVImage_GetImageObjMtd(), ReadRegionHelper(), Repos_ImportVtkImgCmd(), Repos_ImportVtkPdCmd(), Repos_ImportVtkSpCmd(), Repos_ImportVtkUnstructuredGridCmd(), Repos_ReadVtkPolyDataCmd(), cvITKLevelSet::SetInputImage(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetInputImage(), cvLevelSet::SetSeed(), SigMapHelper(), SmoothHelper(), Solid_Apply4x4Mtd(), Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_ClassifyPtMtd(), Solid_CombineFacesMtd(), Solid_CopyCmd(), Solid_CreateEdgeBlendMtd(), Solid_CylinderCmd(), Solid_DeleteFacesMtd(), Solid_DeleteRegionMtd(), Solid_DistanceMtd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_FindCentroidMtd(), Solid_FindExtentMtd(), Solid_GetAxialIsoparametricCurveMtd(), Solid_GetBoundaryFacesMtd(), Solid_GetDiscontinuitiesMtd(), Solid_GetFaceIdsMtd(), Solid_GetFacePolyDataMtd(), Solid_GetPolyDataMtd(), Solid_GetRegionIdsMtd(), Solid_GetSpatialDimMtd(), Solid_GetTopoDimMtd(), Solid_IntersectCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_ReflectMtd(), Solid_RemeshFaceMtd(), Solid_RotateMtd(), Solid_ScaleMtd(), Solid_SphereCmd(), Solid_SubtractCmd(), Solid_TorusCmd(), Solid_TranslateMtd(), Solid_TruncatedConeCmd(), Solid_UnionCmd(), Solid_WriteNativeMtd(), Solid_WriteVtkPolyDataMtd(), sys_geom_Align(), sys_geom_AlignByDist(), and TLSFHelper().
int cvRepositoryData::GetNumLabels ()
Definition at line 175 of file cvRepositoryData.cxx.
References labels_, and NULL.
Referenced by GetLabelKeys().
RepositoryDataT cvRepositoryData::GetType () inline
Definition at line 83 of file cvRepositoryData.h.
References type_.
Referenced by gdscITK_expNegativeImageCmd(), gdscITK_FastMarchCmd(), gdscITK_MinMaxCurvSmoothCmd(), gdscITK_ReadRegionOfInterestCmd(), gdscITK_shapeDetectionCmd(), gdscITK_SigMapCmd(), gdscITK_TLSF_Cmd(), gdscPost_calcAvgPointDataCmd(), gdscPost_calcOSICmd(), gdscPost_calcTKECmd(), gdscPost_calcWallShearCmd(), gdscPost_calcWallShearMeanCmd(), gdscPost_calcWallShearPulseCmd(), gdscPost_readVisResCmd(), Geom_2dWindingNumCmd(), Geom_AddPointDataCmd(), Geom_AlignProfileCmd(), Geom_AvgPtCmd(), Geom_BBoxCmd(), Geom_ClassifyCmd(), Geom_CopyCmd(), Geom_DisorientProfileCmd(), Geom_DividePointDataCmd(), Geom_FindDistanceCmd(), Geom_GetClosedLineRegionCmd(), Geom_GetOrderedPtsCmd(), Geom_GetPolyCentroidCmd(), Geom_IntegrateEnergyCmd(), Geom_IntegrateScalarSurfCmd(), Geom_IntegrateScalarThreshCmd(), Geom_IntegrateSurface2Cmd(), Geom_IntegrateSurfaceCmd(), Geom_InterpolateScalarCmd(), Geom_InterpolateVectorCmd(), Geom_IntersectCmd(), Geom_IntersectWithLineCmd(), Geom_MakePolysConsistentCmd(), Geom_MergePtsCmd(), Geom_MultiplyPointDataCmd(), Geom_NumClosedLineRegionsCmd(), Geom_NumPtsCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_PolygonNormCmd(), Geom_PolysClosedCmd(), Geom_PrintSmallPolysCmd(), Geom_PrintTriStatsCmd(), Geom_ProjectCmd(), Geom_PtInPolyCmd(), Geom_ReduceCmd(), Geom_ReorderPgnCmd(), Geom_ReplacePointDataCmd(), Geom_ReverseAllCellsCmd(), Geom_RmSmallPolysCmd(), Geom_sampleLoopCmd(), Geom_ScaleAvgCmd(), Geom_SplinePtsToPathPlanCmd(), Geom_SubtractCmd(), Geom_SubtractPointDataCmd(), Geom_SurfAreaCmd(), Geom_TranslateCmd(), Geom_UnionCmd(), Geom_Warp3dPtsCmd(), Geom_WriteLinesCmd(), Geom_WriteOrderedPtsCmd(), cvRepository::GetType(), Image_CalcCorrectionEqnAutoCmd(), Image_CalcCorrectionEqnCmd(), Image_ComputeStructuredCoordCmd(), Image_CreateDistanceMapCmd(), Image_DecodeCmd(), Image_FindPathCmd(), Image_MaskInPlaceCmd(), Image_ThresholdCmd(), itkls2d_SetInputsMtd(), itkls3d_SetInputsMtd(), itkutils_FractEdgeProximity3DCmd(), itkutils_GradientMagnitudeGaussianCmd(), itkutils_PdToImgCmd(), itkutils_PdToVolCmd(), itkutils_WriteImageCmd(), LsetCore_SetImageSeedMtd(), LsetCore_SetPdSeedMtd(), LsetCore_SetSolidSeedMtd(), LsetVImage_SetImageObjMtd(), Repos_ExportToVtkCmd(), Solid_CapSurfToSolidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), and Solid_PolyPtsCmd().
int cvRepositoryData::IsLabelPresent (char * key)
Definition at line 223 of file cvRepositoryData.cxx.
References labels_, and NULL.
Referenced by Repos_ClearLabelCmd(), Repos_SetLabelCmd(), Solid_ClearLabelMtd(), and Solid_SetLabelMtd().
void cvRepositoryData::Lock ()
Definition at line 135 of file cvRepositoryData.cxx.
References lockCnt_.
int cvRepositoryData::NumLocks () inline
Definition at line 81 of file cvRepositoryData.h.
References lockCnt_.
Referenced by cvRepository::UnRegister().
void cvRepositoryData::Release ()
Definition at line 146 of file cvRepositoryData.cxx.
References lockCnt_.
int cvRepositoryData::SetLabel (char * key, char * value)
Definition at line 261 of file cvRepositoryData.cxx.
References labels_.
Referenced by Repos_SetLabelCmd(), and Solid_SetLabelMtd().
void cvRepositoryData::SetName (char * in)
Definition at line 159 of file cvRepositoryData.cxx.
References name_, and RD_MAX_NAME_LEN.
Referenced by FMMHelper(), gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_expNegativeImageCmd(), gdscITK_shapeDetectionCmd(), Image_CreateDistanceMapCmd(), Image_DecodeCmd(), Image_FindPathCmd(), Image_ThresholdCmd(), itkutils_GenerateCircleCmd(), itkutils_PdToImgCmd(), itkutils_PdToVolCmd(), LsetVImage_GetImageObjMtd(), ReadRegionHelper(), cvRepository::Register(), Repos_ImportVtkImgCmd(), Repos_ImportVtkPdCmd(), Repos_ImportVtkSpCmd(), Repos_ImportVtkUnstructuredGridCmd(), cvITKLevelSet::SetInputImage(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetInputImage(), cvLevelSet::SetSeed(), SigMapHelper(), SmoothHelper(), and TLSFHelper().
Member Data Documentation
Tcl_HashTable cvRepositoryData::labels_ private
Definition at line 102 of file cvRepositoryData.h.
Referenced by ClearLabel(), cvRepositoryData(), GetLabel(), GetLabelKeys(), GetNumLabels(), IsLabelPresent(), SetLabel(), and ~cvRepositoryData().
int cvRepositoryData::lockCnt_ private
Definition at line 101 of file cvRepositoryData.h.
Referenced by cvRepositoryData(), Lock(), NumLocks(), and Release().
char cvRepositoryData::name_[1024] private
Definition at line 100 of file cvRepositoryData.h.
Referenced by cvRepositoryData(), GetName(), and SetName().
RepositoryDataT cvRepositoryData::type_ private
Definition at line 99 of file cvRepositoryData.h.
Referenced by cvRepositoryData(), and GetType().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvRepositoryData.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvRepositoryData.cxx