simvascular: EdgeRemapImageFilter< TInputImage1, TOutputImage > Class Template Reference
EdgeRemapImageFilter< TInputImage1, TOutputImage > Class Template Reference
#include <EdgeRemapImageFilter.h>
Public Types
typedef EdgeRemapImageFilter Self
typedef
itk::UnaryFunctorImageFilter
< TInputImage1, TOutputImage,
EdgeRemapFunctor< typename
TInputImage1::PixelType,
typename
TOutputImage::PixelType > > Superclass
typedef itk::SmartPointer< Self > Pointer
typedef itk::SmartPointer
< const Self > ConstPointer
Public Member Functions
itkNewMacro (Self)
itkTypeMacro (EdgeRemapImageFilter, UnaryFunctorImageFilter)
void SetKappa (float kappa)
void GetKappa ()
virtual void SetExponent (float exponent)
virtual void GetExponent ()
Detailed Description
template<typename TInputImage1, typename TOutputImage = TInputImage1>
class EdgeRemapImageFilter< TInputImage1, TOutputImage >
Definition at line 75 of file EdgeRemapImageFilter.h.
Member Typedef Documentation
template<typename TInputImage1 , typename TOutputImage = TInputImage1> typedef itk::SmartPointer< const Self > EdgeRemapImageFilter< TInputImage1, TOutputImage >::ConstPointer
Definition at line 89 of file EdgeRemapImageFilter.h.
template<typename TInputImage1 , typename TOutputImage = TInputImage1> typedef itk::SmartPointer< Self > EdgeRemapImageFilter< TInputImage1, TOutputImage >::Pointer
Definition at line 88 of file EdgeRemapImageFilter.h.
template<typename TInputImage1 , typename TOutputImage = TInputImage1> typedef EdgeRemapImageFilter EdgeRemapImageFilter< TInputImage1, TOutputImage >::Self
Definition at line 82 of file EdgeRemapImageFilter.h.
template<typename TInputImage1 , typename TOutputImage = TInputImage1> typedef itk::UnaryFunctorImageFilter< TInputImage1, TOutputImage, EdgeRemapFunctor< typename TInputImage1::PixelType, typename TOutputImage::PixelType > > EdgeRemapImageFilter< TInputImage1, TOutputImage >::Superclass
Definition at line 86 of file EdgeRemapImageFilter.h.
Member Function Documentation
template<typename TInputImage1 , typename TOutputImage = TInputImage1> virtual void EdgeRemapImageFilter< TInputImage1, TOutputImage >::GetExponent () inline virtual
Definition at line 120 of file EdgeRemapImageFilter.h.
Referenced by EdgeRemapImageFilter< TInputImage1, TOutputImage >::SetExponent().
template<typename TInputImage1 , typename TOutputImage = TInputImage1> void EdgeRemapImageFilter< TInputImage1, TOutputImage >::GetKappa () inline
Definition at line 109 of file EdgeRemapImageFilter.h.
Referenced by EdgeRemapImageFilter< TInputImage1, TOutputImage >::SetKappa().
template<typename TInputImage1 , typename TOutputImage = TInputImage1> EdgeRemapImageFilter< TInputImage1, TOutputImage >::itkNewMacro (Self)
Method for creation through the object factory.
template<typename TInputImage1 , typename TOutputImage = TInputImage1> EdgeRemapImageFilter< TInputImage1, TOutputImage >::itkTypeMacro (EdgeRemapImageFilter< TInputImage1, TOutputImage > , UnaryFunctorImageFilter)
Runtime information support.
template<typename TInputImage1 , typename TOutputImage = TInputImage1> virtual void EdgeRemapImageFilter< TInputImage1, TOutputImage >::SetExponent (float exponent) inline virtual
Set the Third operand as a constant
Definition at line 111 of file EdgeRemapImageFilter.h.
References EdgeRemapImageFilter< TInputImage1, TOutputImage >::GetExponent().
template<typename TInputImage1 , typename TOutputImage = TInputImage1> void EdgeRemapImageFilter< TInputImage1, TOutputImage >::SetKappa (float kappa) inline
Set the second operand as a constant
Definition at line 100 of file EdgeRemapImageFilter.h.
References EdgeRemapImageFilter< TInputImage1, TOutputImage >::GetKappa().
The documentation for this class was generated from the following file:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/ITK/ITKCode/EdgeRemapImageFilter.h