simvascular: vtkBooleanOperationPolyDataFilter2 Class Reference
vtkBooleanOperationPolyDataFilter2 Class Reference
#include <vtkBooleanOperationPolyDataFilter2.h>
Classes
class Impl
Public Types
enum OperationType { VTK_UNION =0, VTK_INTERSECTION, VTK_DIFFERENCE }
Public Member Functions
vtkTypeMacro (vtkBooleanOperationPolyDataFilter2, vtkPolyDataAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
vtkGetMacro (NumberOfIntersectionPoints, int)
vtkSetMacro (NumberOfIntersectionPoints, int)
vtkBooleanMacro (NumberOfIntersectionPoints, int)
vtkGetMacro (NumberOfIntersectionLines, int)
vtkSetMacro (NumberOfIntersectionLines, int)
vtkBooleanMacro (NumberOfIntersectionLines, int)
vtkGetMacro (NoIntersectionOutput, int)
vtkSetMacro (NoIntersectionOutput, int)
vtkBooleanMacro (NoIntersectionOutput, int)
vtkSetClampMacro (Operation, int, VTK_UNION, VTK_DIFFERENCE)
vtkGetMacro (Operation, int)
void SetOperationToUnion ()
void SetOperationToIntersection ()
void SetOperationToDifference ()
Static Public Member Functions
static
vtkBooleanOperationPolyDataFilter2 * New ()
Protected Member Functions
vtkBooleanOperationPolyDataFilter2 ()
~vtkBooleanOperationPolyDataFilter2 ()
int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
int FillInputPortInformation (int, vtkInformation *)
Private Member Functions
vtkBooleanOperationPolyDataFilter2 (const vtkBooleanOperationPolyDataFilter2 &)
void operator= (const vtkBooleanOperationPolyDataFilter2 &)
Private Attributes
vtkPolyData * OutputSurface
int Operation
int NoIntersectionOutput
int NumberOfIntersectionPoints
int NumberOfIntersectionLines
Detailed Description
Definition at line 42 of file vtkBooleanOperationPolyDataFilter2.h.
Member Enumeration Documentation
enum vtkBooleanOperationPolyDataFilter2::OperationType
Enumerator
VTK_UNION
VTK_INTERSECTION
VTK_DIFFERENCE
Definition at line 68 of file vtkBooleanOperationPolyDataFilter2.h.
Constructor & Destructor Documentation
vtkBooleanOperationPolyDataFilter2::vtkBooleanOperationPolyDataFilter2 () protected
Definition at line 828 of file vtkBooleanOperationPolyDataFilter2.cxx.
References NoIntersectionOutput, NumberOfIntersectionLines, NumberOfIntersectionPoints, Operation, and VTK_UNION.
vtkBooleanOperationPolyDataFilter2::~vtkBooleanOperationPolyDataFilter2 () protected
Definition at line 842 of file vtkBooleanOperationPolyDataFilter2.cxx.
vtkBooleanOperationPolyDataFilter2::vtkBooleanOperationPolyDataFilter2 (const vtkBooleanOperationPolyDataFilter2 &) private
Member Function Documentation
int vtkBooleanOperationPolyDataFilter2::FillInputPortInformation (int port, vtkInformation * info) protected
Definition at line 998 of file vtkBooleanOperationPolyDataFilter2.cxx.
static vtkBooleanOperationPolyDataFilter2* vtkBooleanOperationPolyDataFilter2::New () static
Referenced by cvPolyDataSolid::Intersect(), cvPolyDataSolid::Subtract(), and cvPolyDataSolid::Union().
void vtkBooleanOperationPolyDataFilter2::operator= (const vtkBooleanOperationPolyDataFilter2 &) private
void vtkBooleanOperationPolyDataFilter2::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 974 of file vtkBooleanOperationPolyDataFilter2.cxx.
References Operation, VTK_DIFFERENCE, VTK_INTERSECTION, and VTK_UNION.
int vtkBooleanOperationPolyDataFilter2::RequestData (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected
Definition at line 847 of file vtkBooleanOperationPolyDataFilter2.cxx.
References vtkIntersectionPolyDataFilter2::CleanAndCheckSurface(), vtkBooleanOperationPolyDataFilter2::Impl::DetermineIntersection(), vtkBooleanOperationPolyDataFilter2::Impl::GetBooleanRegions(), impl, vtkBooleanOperationPolyDataFilter2::Impl::Initialize(), vtkBooleanOperationPolyDataFilter2::Impl::IntersectionLines, vtkBooleanOperationPolyDataFilter2::Impl::Mesh, NoIntersectionOutput, NumberOfIntersectionLines, NumberOfIntersectionPoints, Operation, vtkBooleanOperationPolyDataFilter2::Impl::PerformBoolean(), vtkBooleanOperationPolyDataFilter2::Impl::SetBoundaryArrays(), and vtkBooleanOperationPolyDataFilter2::Impl::SetCheckArrays().
void vtkBooleanOperationPolyDataFilter2::SetOperationToDifference () inline
Definition at line 83 of file vtkBooleanOperationPolyDataFilter2.h.
Referenced by cvPolyDataSolid::Subtract().
void vtkBooleanOperationPolyDataFilter2::SetOperationToIntersection () inline
Definition at line 81 of file vtkBooleanOperationPolyDataFilter2.h.
Referenced by cvPolyDataSolid::Intersect().
void vtkBooleanOperationPolyDataFilter2::SetOperationToUnion () inline
Definition at line 79 of file vtkBooleanOperationPolyDataFilter2.h.
Referenced by cvPolyDataSolid::Union().
vtkBooleanOperationPolyDataFilter2::vtkBooleanMacro (NumberOfIntersectionPoints , int)
vtkBooleanOperationPolyDataFilter2::vtkBooleanMacro (NumberOfIntersectionLines , int)
vtkBooleanOperationPolyDataFilter2::vtkBooleanMacro (NoIntersectionOutput , int)
vtkBooleanOperationPolyDataFilter2::vtkGetMacro (NumberOfIntersectionPoints , int)
vtkBooleanOperationPolyDataFilter2::vtkGetMacro (NumberOfIntersectionLines , int)
vtkBooleanOperationPolyDataFilter2::vtkGetMacro (NoIntersectionOutput , int)
vtkBooleanOperationPolyDataFilter2::vtkGetMacro (Operation , int)
vtkBooleanOperationPolyDataFilter2::vtkSetClampMacro (Operation , int , VTK_UNION , VTK_DIFFERENCE)
vtkBooleanOperationPolyDataFilter2::vtkSetMacro (NumberOfIntersectionPoints , int)
vtkBooleanOperationPolyDataFilter2::vtkSetMacro (NumberOfIntersectionLines , int)
vtkBooleanOperationPolyDataFilter2::vtkSetMacro (NoIntersectionOutput , int)
vtkBooleanOperationPolyDataFilter2::vtkTypeMacro (vtkBooleanOperationPolyDataFilter2 , vtkPolyDataAlgorithm)
Member Data Documentation
int vtkBooleanOperationPolyDataFilter2::NoIntersectionOutput private
Definition at line 105 of file vtkBooleanOperationPolyDataFilter2.h.
Referenced by RequestData(), and vtkBooleanOperationPolyDataFilter2().
int vtkBooleanOperationPolyDataFilter2::NumberOfIntersectionLines private
Definition at line 107 of file vtkBooleanOperationPolyDataFilter2.h.
Referenced by RequestData(), and vtkBooleanOperationPolyDataFilter2().
int vtkBooleanOperationPolyDataFilter2::NumberOfIntersectionPoints private
Definition at line 106 of file vtkBooleanOperationPolyDataFilter2.h.
Referenced by RequestData(), and vtkBooleanOperationPolyDataFilter2().
int vtkBooleanOperationPolyDataFilter2::Operation private
Definition at line 104 of file vtkBooleanOperationPolyDataFilter2.h.
Referenced by PrintSelf(), RequestData(), and vtkBooleanOperationPolyDataFilter2().
vtkPolyData* vtkBooleanOperationPolyDataFilter2::OutputSurface private
Definition at line 100 of file vtkBooleanOperationPolyDataFilter2.h.
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkBooleanOperationPolyDataFilter2.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkBooleanOperationPolyDataFilter2.cxx