simvascular: vtkvmtkPolyDataUmbrellaStencil Class Reference
vtkvmtkPolyDataUmbrellaStencil Class Reference
#include <vtkvmtkPolyDataUmbrellaStencil.h>
Public Member Functions
vtkTypeMacro (vtkvmtkPolyDataUmbrellaStencil, vtkvmtkPolyDataManifoldStencil)
virtual vtkIdType GetItemType ()
void Build ()
Public Member Functions inherited from vtkvmtkPolyDataManifoldStencil
vtkTypeMacro (vtkvmtkPolyDataManifoldStencil, vtkvmtkStencil)
vtkGetMacro (Area, double)
virtual void ComputeArea ()
void DeepCopy (vtkvmtkPolyDataManifoldStencil *src)
vtkGetMacro (UseExtendedNeighborhood, int)
vtkSetMacro (UseExtendedNeighborhood, int)
vtkBooleanMacro (UseExtendedNeighborhood, int)
Public Member Functions inherited from vtkvmtkStencil
vtkTypeMacro (vtkvmtkStencil, vtkvmtkNeighborhood)
vtkSetMacro (NumberOfComponents, vtkIdType)
vtkGetMacro (NumberOfComponents, vtkIdType)
double GetWeight (vtkIdType i)
void SetWeight (vtkIdType i, double weight)
double GetWeight (vtkIdType i, vtkIdType component)
void SetWeight (vtkIdType i, vtkIdType component, double weight)
vtkIdType GetNumberOfWeights ()
void ScaleWeights (double factor)
double GetCenterWeight ()
void SetCenterWeight (double weight)
const double * GetCenterWeightTuple ()
double GetCenterWeight (vtkIdType component)
void SetCenterWeight (vtkIdType component, double weightComponent)
virtual void DeepCopy (vtkvmtkItem *src)
vtkSetMacro (WeightScaling, int) vtkGetMacro(WeightScaling
int vtkBooleanMacro (WeightScaling, int) vtkSetMacro(NegateWeights
int int vtkGetMacro (NegateWeights, int) vtkBooleanMacro(NegateWeights
Public Member Functions inherited from vtkvmtkNeighborhood
vtkTypeMacro (vtkvmtkNeighborhood, vtkvmtkDataSetItem)
vtkGetMacro (IsBoundary, bool)
vtkIdType GetNumberOfPoints ()
vtkIdType GetPointId (vtkIdType i)
vtkIdType * GetPointer (vtkIdType i)
Public Member Functions inherited from vtkvmtkDataSetItem
vtkTypeMacro (vtkvmtkDataSetItem, vtkvmtkItem)
void SetDataSet (vtkDataSet *dataSet)
vtkDataSet * GetDataSet ()
vtkSetMacro (DataSetPointId, vtkIdType)
vtkGetMacro (DataSetPointId, vtkIdType)
vtkSetMacro (ReallocateOnBuild, int) vtkGetMacro(ReallocateOnBuild
int vtkBooleanMacro(ReallocateOnBuild,
int) protected ~vtkvmtkDataSetItem ()
Public Member Functions inherited from vtkvmtkItem
vtkTypeMacro (vtkvmtkItem, vtkObject)
Static Public Member Functions
static
vtkvmtkPolyDataUmbrellaStencil * New ()
Protected Member Functions
vtkvmtkPolyDataUmbrellaStencil ()
~vtkvmtkPolyDataUmbrellaStencil ()
void ScaleWithArea ()
Protected Member Functions inherited from vtkvmtkPolyDataManifoldStencil
vtkvmtkPolyDataManifoldStencil ()
~vtkvmtkPolyDataManifoldStencil ()
void ScaleWithAreaFactor (double factor)
Protected Member Functions inherited from vtkvmtkStencil
vtkvmtkStencil ()
~vtkvmtkStencil ()
void ResizePointList (vtkIdType ptId, int size)
void ChangeWeightSign ()
Protected Member Functions inherited from vtkvmtkNeighborhood
vtkvmtkNeighborhood ()
~vtkvmtkNeighborhood ()
void ResizePointList (vtkIdType ptId, int size)
Protected Member Functions inherited from vtkvmtkItem
vtkvmtkItem ()
~vtkvmtkItem ()
Private Member Functions
vtkvmtkPolyDataUmbrellaStencil (const vtkvmtkPolyDataUmbrellaStencil &)
void operator= (const vtkvmtkPolyDataUmbrellaStencil &)
Additional Inherited Members
Public Attributes inherited from vtkvmtkDataSetItem
vtkDataSet * DataSet
vtkIdType DataSetPointId
int ReallocateOnBuild
Protected Attributes inherited from vtkvmtkPolyDataManifoldStencil
double Area
int UseExtendedNeighborhood
Protected Attributes inherited from vtkvmtkStencil
vtkIdType NumberOfComponents
double * Weights
double * CenterWeight
int WeightScaling
int NegateWeights
Protected Attributes inherited from vtkvmtkNeighborhood
vtkIdType NPoints
vtkIdType * PointIds
bool IsBoundary
Detailed Description
Definition at line 33 of file vtkvmtkPolyDataUmbrellaStencil.h.
Constructor & Destructor Documentation
vtkvmtkPolyDataUmbrellaStencil::vtkvmtkPolyDataUmbrellaStencil () protected
Definition at line 28 of file vtkvmtkPolyDataUmbrellaStencil.cxx.
References vtkvmtkPolyDataManifoldStencil::UseExtendedNeighborhood.
vtkvmtkPolyDataUmbrellaStencil::~vtkvmtkPolyDataUmbrellaStencil () inline protected
Definition at line 46 of file vtkvmtkPolyDataUmbrellaStencil.h.
vtkvmtkPolyDataUmbrellaStencil::vtkvmtkPolyDataUmbrellaStencil (const vtkvmtkPolyDataUmbrellaStencil &) private
Member Function Documentation
void vtkvmtkPolyDataUmbrellaStencil::Build () virtual
Reimplemented from vtkvmtkPolyDataManifoldStencil.
Definition at line 33 of file vtkvmtkPolyDataUmbrellaStencil.cxx.
References vtkvmtkPolyDataManifoldStencil::Area, vtkvmtkStencil::CenterWeight, vtkvmtkStencil::ChangeWeightSign(), vtkvmtkNeighborhood::NPoints, and vtkvmtkStencil::Weights.
Referenced by vtkvmtkPolyDataSurfaceRemeshing::RelocatePoint().
virtual vtkIdType vtkvmtkPolyDataUmbrellaStencil::GetItemType () inline virtual
Implements vtkvmtkItem.
Definition at line 40 of file vtkvmtkPolyDataUmbrellaStencil.h.
References VTK_VMTK_UMBRELLA_STENCIL.
static vtkvmtkPolyDataUmbrellaStencil* vtkvmtkPolyDataUmbrellaStencil::New () static
Referenced by vtkvmtkPolyDataSurfaceRemeshing::RelocatePoint().
void vtkvmtkPolyDataUmbrellaStencil::operator= (const vtkvmtkPolyDataUmbrellaStencil &) private
void vtkvmtkPolyDataUmbrellaStencil::ScaleWithArea () inline protected virtual
Implements vtkvmtkPolyDataManifoldStencil.
Definition at line 48 of file vtkvmtkPolyDataUmbrellaStencil.h.
vtkvmtkPolyDataUmbrellaStencil::vtkTypeMacro (vtkvmtkPolyDataUmbrellaStencil , vtkvmtkPolyDataManifoldStencil)
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkPolyDataUmbrellaStencil.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkPolyDataUmbrellaStencil.cxx