simvascular: cvPolyDataSolid Class Reference
cvPolyDataSolid Class Reference
#include <cvPolyDataSolid.h>
Public Member Functions
cvPolyDataSolid ()
Constructor for cvPolyDataSolid (Should never be called directly)
cvPolyDataSolid (const cvPolyDataSolid &sm)
Copy Constructor for cvPolyDataSolid.
~cvPolyDataSolid ()
Destructor for cvPolyDataSolid.
void Clear ()
void ClearSurf ()
void Print () const
void Check (int *nerr) const
cvSolidModel * Copy () const
int Copy (const cvSolidModel &src)
Copy for cvSolidModel.
int MakePoly2d (cvPolyData *pd)
int MakePoly2dPts (cvPolyData *pd)
int MakeCircle (double radius, double ctr[])
int MakeEllipse (double xr, double yr, double ctr[])
int MakeBox2d (double dims[], double ctr[])
int MakeBox3d (double dims[], double ctr[])
int MakeSphere (double r, double ctr[])
int MakeEllipsoid (double r[], double ctr[])
int MakeCylinder (double r, double length, double ctr[], double axis[])
int MakeTorus (double rmaj, double rmin, double ctr[], double axis[])
int MakeTruncatedCone (double pt[], double dir[], double r1, double r2)
int SetPoly3dFacetMethod (SolidModel_FacetT code)
int MakePoly3dSolid (cvPolyData *pd, double angle)
int MakePoly3dSurface (cvPolyData *pd)
int ExtrudeZ (cvSolidModel *in, double dist)
int Extrude (cvSolidModel *in, double **dist)
int MakeInterpCurveLoop (cvPolyData *pd, int closed)
int MakeApproxCurveLoop (cvPolyData *pd, double tol, int closed)
int MakeLoftedSurf (cvSolidModel **curves, int numCurves, char *name)
int CapSurfToSolid (cvSolidModel *surf)
int Intersect (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st=SM_Simplify_All)
Function to intersect two PolyData using the vtk Booleans filter.
int Union (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st=SM_Simplify_All)
Function to union two PolyData using the vtk Booleans filter.
int Subtract (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st=SM_Simplify_All)
Function to subtract one PolyData from another using the vtk Booleans filter.
int Translate (double vec[], int ndim)
int Rotate (double axis[], int ndim, double rad)
int Scale (double factor)
int Reflect (double pos[], double nrm[])
int Apply4x4 (double mat[][4])
cvPolyData * GetPolyData (int useMaxDist, double max_dist) const
Function to get the member vtkPolyData.
cvPolyData * GetFacePolyData (int faceid, int useMaxDist, double max_dist) const
Procedure gets one face based on faceid defined in PolyDataUtils.
cvPolyData * GetDiscontinuities () const
cvPolyDataSolid * GetAxialIsoparametricCurve (double p) const
int FindExtent (double *extent)
int FindCentroid (double *centroid)
int GetTopoDim (int *tdim) const
int GetSpatialDim (int *sdim) const
int ClassifyPt (double pt[], int v, int *ans) const
int ClassifyPt (double x, double y, int v, int *ans) const
int ClassifyPt (double x, double y, double z, int v, int *ans) const
int DistanceAlongVec (double start[], double end[], int v, double *ans) const
int Distance (double pos[], double upperLimit, double *dist)
int GetFaceNormal (int faceid, double u, double v, double normal[])
void MakeSurf ()
int GetBoundaryFaces (double angle)
Function to extract the boundaries for the member vtkPolyData.
int GetFaceIds (int *numFaces, int **faceIds)
Function to get the Ids associated with the face of the PolyData.
int GetFaceAttribute (char *attr, int faceid, char **value)
int SetFaceAttribute (char *attr, int faceid, char *value)
int GetRegionIds (int *numRegions, int **RegionIds)
int GetRegionAttribute (char *attr, int regionid, char **value)
int SetRegionAttribute (char *attr, int regionid, char *value)
int DeleteRegion (int regionid)
int ReadNative (char *filename)
Function to load in a solid file.
int WriteNative (int file_version, char *filename) const
Function to write the polydata.
int WriteVtkPolyData (char *filename)
int DeleteFaces (int numfaces, int *faces)
Function to delete the cells in the polydata.
int CreateEdgeBlend (int faceA, int faceB, double radius)
int CombineFaces (int targetface, int loseface)
Function to combine the ids of two faces in the polydata.
int RemeshFace (int numfaces, int *excludedFaces, double size)
int SetVtkPolyDataObject (vtkPolyData *newPolyData)
Function to set the PolyData member object.
Public Member Functions inherited from cvSolidModel
cvSolidModel (SolidModel_KernelT t)
virtual ~cvSolidModel ()
SolidModel_KernelT GetKernelT () const
Public Member Functions inherited from cvRepositoryData
cvRepositoryData (RepositoryDataT type)
virtual ~cvRepositoryData ()
void Lock ()
void Release ()
int NumLocks ()
RepositoryDataT GetType ()
char * GetName ()
void SetName (char *in)
int GetNumLabels ()
void GetLabelKeys (int *numKeys, char **keys[])
int IsLabelPresent (char *key)
int GetLabel (char *key, char **value)
int SetLabel (char *key, char *value)
void ClearLabel (char *key)
virtual int GetMemoryUsage ()
Protected Attributes
vtkPolyData * geom_
int numBoundaryRegions
Protected Attributes inherited from cvSolidModel
double tol_
Additional Inherited Members
Static Public Member Functions inherited from cvSolidModel
static cvSolidModel * DefaultInstantiateSolidModel (Tcl_Interp *interp=NULL)
Static Public Attributes inherited from cvSolidModel
static SolidModel_KernelT gCurrentKernel = SM_KT_PARASOLID
static cvFactoryRegistrar gRegistrar
Detailed Description
Definition at line 71 of file cvPolyDataSolid.h.
Constructor & Destructor Documentation
cvPolyDataSolid::cvPolyDataSolid ()
Constructor for cvPolyDataSolid (Should never be called directly)
Data Member is a vtkPolyData. It is initiated as NULL. When a solid is loaded, a new PolyData is created
Definition at line 70 of file cvPolyDataSolid.cxx.
References geom_, NULL, and numBoundaryRegions.
Referenced by Copy().
cvPolyDataSolid::cvPolyDataSolid (const cvPolyDataSolid & sm)
Copy Constructor for cvPolyDataSolid.
Definition at line 103 of file cvPolyDataSolid.cxx.
References Copy(), geom_, and NULL.
cvPolyDataSolid::~cvPolyDataSolid ()
Destructor for cvPolyDataSolid.
Definition at line 89 of file cvPolyDataSolid.cxx.
References geom_, and NULL.
Member Function Documentation
int cvPolyDataSolid::Apply4x4 (double mat[][4]) inline virtual
Implements cvSolidModel.
Definition at line 127 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::CapSurfToSolid (cvSolidModel * surf) inline virtual
Reimplemented from cvSolidModel.
Definition at line 112 of file cvPolyDataSolid.h.
References CV_ERROR.
void cvPolyDataSolid::Check (int * nerr) const inline virtual
Implements cvSolidModel.
Definition at line 83 of file cvPolyDataSolid.h.
int cvPolyDataSolid::ClassifyPt (double pt[], int v, int * ans) const inline virtual
Implements cvSolidModel.
Definition at line 138 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::ClassifyPt (double x, double y, int v, int * ans) const inline virtual
Implements cvSolidModel.
Definition at line 139 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::ClassifyPt (double x, double y, double z, int v, int * ans) const inline virtual
Implements cvSolidModel.
Definition at line 140 of file cvPolyDataSolid.h.
References CV_ERROR.
void cvPolyDataSolid::Clear () inline virtual
Implements cvSolidModel.
Definition at line 80 of file cvPolyDataSolid.h.
void cvPolyDataSolid::ClearSurf () inline
Definition at line 81 of file cvPolyDataSolid.h.
int cvPolyDataSolid::CombineFaces (int targetface, int loseface) virtual
Function to combine the ids of two faces in the polydata.
Parameters
targetface id of the face to set the two faces to have new id of
loseface id of the second face, id will be lost
Returns
CV_OK if executed correctly, CV_ERROR if the geometry is NULL or the function does not return properly.
Implements cvSolidModel.
Definition at line 669 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, NULL, numBoundaryRegions, and PlyDtaUtils_CombineFaces().
cvSolidModel * cvPolyDataSolid::Copy () const virtual
Implements cvSolidModel.
Definition at line 166 of file cvPolyDataSolid.cxx.
References cvPolyDataSolid().
Referenced by cvPolyDataSolid().
int cvPolyDataSolid::Copy (const cvSolidModel & src) virtual
Copy for cvSolidModel.
Implements cvSolidModel.
Definition at line 117 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, cvSolidModel::GetKernelT(), NULL, and SM_KT_POLYDATA.
int cvPolyDataSolid::CreateEdgeBlend (int faceA, int faceB, double radius) inline virtual
Implements cvSolidModel.
Definition at line 167 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::DeleteFaces (int numfaces, int * faces) virtual
Function to delete the cells in the polydata.
Parameters
numfaces this is the number of cells to delete from the polydata
faces this is an array containing the ids of the cells to delete
Returns
CV_OK if executed correctly, CV_ERROR if the geometry is NULL or the function does not return properly.
Implements cvSolidModel.
Definition at line 640 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PlyDtaUtils_DeleteCells().
int cvPolyDataSolid::DeleteRegion (int regionid) virtual
Implements cvSolidModel.
Definition at line 384 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, NULL, numBoundaryRegions, and PlyDtaUtils_DeleteRegion().
int cvPolyDataSolid::Distance (double pos[], double upperLimit, double * dist) inline virtual
Implements cvSolidModel.
Definition at line 144 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::DistanceAlongVec (double start[], double end[], int v, double * ans) const inline virtual
Implements cvSolidModel.
Definition at line 142 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::Extrude (cvSolidModel * in, double ** dist) inline virtual
Implements cvSolidModel.
Definition at line 107 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::ExtrudeZ (cvSolidModel * in, double dist) inline virtual
Implements cvSolidModel.
Definition at line 106 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::FindCentroid (double * centroid) inline virtual
Implements cvSolidModel.
Definition at line 135 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::FindExtent (double * extent) inline virtual
Implements cvSolidModel.
Definition at line 134 of file cvPolyDataSolid.h.
References CV_ERROR.
cvPolyDataSolid* cvPolyDataSolid::GetAxialIsoparametricCurve (double p) const inline virtual
Implements cvSolidModel.
Definition at line 133 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::GetBoundaryFaces (double angle) virtual
Function to extract the boundaries for the member vtkPolyData.
Parameters
angle double that specifies the extraction angle. Any faces with a difference between face normals larger than this angle will be considered a separate face
Returns
*result: CV_ERROR is member data hasn't been loaded, or if the GetBoundaryFaces function does not work properly. CV_OK is executed properly
Implements cvSolidModel.
Definition at line 307 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, NULL, numBoundaryRegions, and PlyDtaUtils_GetBoundaryFaces().
cvPolyData* cvPolyDataSolid::GetDiscontinuities () const inline virtual
Implements cvSolidModel.
Definition at line 132 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::GetFaceAttribute (char * attr, int faceid, char ** value) virtual
Implements cvSolidModel.
Definition at line 350 of file cvPolyDataSolid.cxx.
References CV_OK, geom_, and NULL.
int cvPolyDataSolid::GetFaceIds (int * numFaces, int ** faceIds) virtual
Function to get the Ids associated with the face of the PolyData.
Parameters
*numFaces Pointer to the number of faces the poly should have
**faceIds Pointer to a pointer of vector containing the numerical values corresponding to each face region
Returns
*result: CV_ERROR is member data hasn't been loaded, if the number of faces is zero or faceIds don't exist
Implements cvSolidModel.
Definition at line 331 of file cvPolyDataSolid.cxx.
References CV_OK, geom_, NULL, numBoundaryRegions, and PlyDtaUtils_GetFaceIds().
int cvPolyDataSolid::GetFaceNormal (int faceid, double u, double v, double normal[]) inline virtual
Implements cvSolidModel.
Definition at line 146 of file cvPolyDataSolid.h.
References CV_ERROR.
cvPolyData * cvPolyDataSolid::GetFacePolyData (int faceid, int useMaxDist, double max_dist) const virtual
Procedure gets one face based on faceid defined in PolyDataUtils.
Parameters
face_id int which is the number of the face to extract
useMaxDist UNUSED CURRENTLY
max_dist UNUSED CURRENTLY
Returns
*result: cvPolyData containg the face vtkPolyData
Implements cvSolidModel.
Definition at line 266 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, NULL, PlyDtaUtils_GetFacePolyData(), and sys_geom_MergePts().
cvPolyData * cvPolyDataSolid::GetPolyData (int useMaxDist, double max_dist) const virtual
Function to get the member vtkPolyData.
Parameters
file_version int for filetype (UNUSED CURRENTLY)
*filename Pointer to a char filename of the file to write
Returns
*result: cvPolyData containing the member vtkPolyData
Procedure returns the current vtkPolyData member as a cvPolyData
Implements cvSolidModel.
Definition at line 245 of file cvPolyDataSolid.cxx.
References geom_.
int cvPolyDataSolid::GetRegionAttribute (char * attr, int regionid, char ** value) inline virtual
Implements cvSolidModel.
Definition at line 155 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::GetRegionIds (int * numRegions, int ** RegionIds) inline virtual
Implements cvSolidModel.
Definition at line 154 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::GetSpatialDim (int * sdim) const inline virtual
Implements cvSolidModel.
Definition at line 137 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::GetTopoDim (int * tdim) const inline virtual
Implements cvSolidModel.
Definition at line 136 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::Intersect (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st = SM_Simplify_All) virtual
Function to intersect two PolyData using the vtk Booleans filter.
Parameters
*a Pointer to the first object to be intersected
*b Pointer to the second object to be intersected
Returns
CV_ERROR if the objects don't exist of the filter doesn't work correctly
Implements cvSolidModel.
Definition at line 421 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, cvSolidModel::GetPolyData(), vtkSurfaceBooleanOperations::New(), vtkBooleanOperationPolyDataFilter2::New(), NULL, vtkSurfaceBooleanOperations::SetModeToIntersection(), and vtkBooleanOperationPolyDataFilter2::SetOperationToIntersection().
int cvPolyDataSolid::MakeApproxCurveLoop (cvPolyData * pd, double tol, int closed) inline virtual
Implements cvSolidModel.
Definition at line 110 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeBox2d (double dims[], double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 92 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeBox3d (double dims[], double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 94 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeCircle (double radius, double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 90 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeCylinder (double r, double length, double ctr[], double axis[]) inline virtual
Implements cvSolidModel.
Definition at line 97 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeEllipse (double xr, double yr, double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 91 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeEllipsoid (double r[], double ctr[]) inline virtual
Reimplemented from cvSolidModel.
Definition at line 96 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeInterpCurveLoop (cvPolyData * pd, int closed) inline virtual
Implements cvSolidModel.
Definition at line 109 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeLoftedSurf (cvSolidModel ** curves, int numCurves, char * name) inline virtual
Implements cvSolidModel.
Definition at line 111 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakePoly2d (cvPolyData * pd) inline virtual
Implements cvSolidModel.
Definition at line 88 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakePoly2dPts (cvPolyData * pd) inline virtual
Implements cvSolidModel.
Definition at line 89 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakePoly3dSolid (cvPolyData * pd, double angle) inline virtual
Implements cvSolidModel.
Definition at line 104 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakePoly3dSurface (cvPolyData * pd) inline virtual
Implements cvSolidModel.
Definition at line 105 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeSphere (double r, double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 95 of file cvPolyDataSolid.h.
References CV_ERROR.
void cvPolyDataSolid::MakeSurf () inline
Definition at line 149 of file cvPolyDataSolid.h.
int cvPolyDataSolid::MakeTorus (double rmaj, double rmin, double ctr[], double axis[]) inline virtual
Reimplemented from cvSolidModel.
Definition at line 99 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::MakeTruncatedCone (double pt[], double dir[], double r1, double r2) inline virtual
Implements cvSolidModel.
Definition at line 101 of file cvPolyDataSolid.h.
References CV_ERROR.
void cvPolyDataSolid::Print () const inline virtual
Implements cvSolidModel.
Definition at line 82 of file cvPolyDataSolid.h.
int cvPolyDataSolid::ReadNative (char * filename) virtual
Function to load in a solid file.
Parameters
*filename Pointer to a char filename of the file to read in
Returns
CV_OK if executed correctly, CV_ERROR if the geometry is not NULL or the read function does not return properly.
Note
Current accepted filetypes include:
STL
VTP
VTK
PLY
Implements cvSolidModel.
Definition at line 187 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PlyDtaUtils_ReadNative().
int cvPolyDataSolid::Reflect (double pos[], double nrm[]) inline virtual
Implements cvSolidModel.
Definition at line 126 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::RemeshFace (int numfaces, int * excludedFaces, double size) virtual
Implements cvSolidModel.
Definition at line 689 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and VMTKUtils_SurfaceRemeshing().
int cvPolyDataSolid::Rotate (double axis[], int ndim, double rad) inline virtual
Implements cvSolidModel.
Definition at line 124 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::Scale (double factor) inline virtual
Implements cvSolidModel.
Definition at line 125 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::SetFaceAttribute (char * attr, int faceid, char * value) virtual
Implements cvSolidModel.
Definition at line 367 of file cvPolyDataSolid.cxx.
References CV_OK, geom_, and NULL.
int cvPolyDataSolid::SetPoly3dFacetMethod (SolidModel_FacetT code) inline virtual
Implements cvSolidModel.
Definition at line 103 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::SetRegionAttribute (char * attr, int regionid, char * value) inline virtual
Implements cvSolidModel.
Definition at line 156 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::SetVtkPolyDataObject (vtkPolyData * newPolyData) virtual
Function to set the PolyData member object.
Parameters
*newPolyData Pointer to vtkPolyData object that you want to be set as the class member data
Returns
CV_OK if executed correctly
Implements cvSolidModel.
Definition at line 149 of file cvPolyDataSolid.cxx.
References CV_OK, geom_, and NULL.
int cvPolyDataSolid::Subtract (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st = SM_Simplify_All) virtual
Function to subtract one PolyData from another using the vtk Booleans filter.
Parameters
*a Pointer to the first object to be subtracted
*b Pointer to the second object to be subtracted
Returns
CV_ERROR if the objects don't exist of the filter doesn't work correctly
Implements cvSolidModel.
Definition at line 568 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, cvSolidModel::GetPolyData(), vtkSurfaceBooleanOperations::New(), vtkBooleanOperationPolyDataFilter2::New(), NULL, vtkSurfaceBooleanOperations::SetModeToDifference(), and vtkBooleanOperationPolyDataFilter2::SetOperationToDifference().
int cvPolyDataSolid::Translate (double vec[], int ndim) inline virtual
Implements cvSolidModel.
Definition at line 123 of file cvPolyDataSolid.h.
References CV_ERROR.
int cvPolyDataSolid::Union (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st = SM_Simplify_All) virtual
Function to union two PolyData using the vtk Booleans filter.
Parameters
*a Pointer to the first object to be unioned
*b Pointer to the second object to be unioned
Returns
CV_ERROR if the objects don't exist of the filter doesn't work correctly
Implements cvSolidModel.
Definition at line 495 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, cvSolidModel::GetPolyData(), vtkSurfaceBooleanOperations::New(), vtkBooleanOperationPolyDataFilter2::New(), NULL, vtkSurfaceBooleanOperations::SetModeToUnion(), and vtkBooleanOperationPolyDataFilter2::SetOperationToUnion().
int cvPolyDataSolid::WriteNative (int file_version, char * filename) const virtual
Function to write the polydata.
Parameters
file_version int for filetype (UNUSED CURRENTLY)
*filename Pointer to a char filename of the file to write
Returns
CV_OK if executed correctly, CV_ERROR if the geometry is NULL or the write function does not return properly.
Implements cvSolidModel.
Definition at line 222 of file cvPolyDataSolid.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PlyDtaUtils_WriteNative().
int cvPolyDataSolid::WriteVtkPolyData (char * filename) inline virtual
Implements cvSolidModel.
Definition at line 162 of file cvPolyDataSolid.h.
References CV_ERROR.
Member Data Documentation
vtkPolyData* cvPolyDataSolid::geom_ protected
Definition at line 174 of file cvPolyDataSolid.h.
Referenced by CombineFaces(), Copy(), cvPolyDataSolid(), DeleteFaces(), DeleteRegion(), GetBoundaryFaces(), GetFaceAttribute(), GetFaceIds(), GetFacePolyData(), GetPolyData(), Intersect(), ReadNative(), RemeshFace(), SetFaceAttribute(), SetVtkPolyDataObject(), Subtract(), Union(), WriteNative(), and ~cvPolyDataSolid().
int cvPolyDataSolid::numBoundaryRegions protected
Definition at line 175 of file cvPolyDataSolid.h.
Referenced by CombineFaces(), cvPolyDataSolid(), DeleteRegion(), GetBoundaryFaces(), and GetFaceIds().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/PolyDataSolid/cvPolyDataSolid.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/PolyDataSolid/cvPolyDataSolid.cxx