simvascular: cvLevelSetVelocityThreshold Class Reference
cvLevelSetVelocityThreshold Class Reference
#include <cvLevelSetVelocityThreshold.h>
Public Member Functions
cvLevelSetVelocityThreshold ()
~cvLevelSetVelocityThreshold ()
int SetBalloonF (double b)
int GetBalloonF (double *b)
int SetThreshold (double t)
int GetThreshold (double *t)
int Valid ()
int StopCondition ()
int Evaluate (double pos[], double *f0, double *f1, double v[], int *forceFlag, double toDot[])
int GetMemoryUsage ()
Public Member Functions inherited from cvLevelSetVelocityImage
cvLevelSetVelocityImage ()
virtual ~cvLevelSetVelocityImage ()
int SetImage (Image_T *i, int closed=0)
int SetImage (char *filebase, int fileNumRange[], int imgDims[], double pixDims[], int closed=0)
int SetImage (short *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (double *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (float *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int GetImage (Image_T **i)
int GetMagGradRange (double rng[])
int GetXYMagGradRange (double rng[])
int GetZMagGradRange (double rng[])
int GetIntensityRange (double rng[])
int ClearImage ()
virtual void PostSetImageAction ()
Public Member Functions inherited from cvLevelSetVelocity
cvLevelSetVelocity ()
virtual ~cvLevelSetVelocity ()
int LinkLevelSet (cvLevelSet *ls)
int UnlinkLevelSet ()
int GetLevelSet (cvLevelSet **ls)
int UpdateTolerance ()
void SetStopV (double d)
double GetStopV ()
Private Attributes
double balloonF_
int balloonFvalid_
double thr_
Additional Inherited Members
Public Attributes inherited from cvLevelSetVelocity
char tclName_ [CV_STRLEN]
Protected Member Functions inherited from cvLevelSetVelocityImage
int GetImgSize ()
Protected Attributes inherited from cvLevelSetVelocityImage
Image_T * image_
Protected Attributes inherited from cvLevelSetVelocity
cvLevelSet * ls_
double tol_
double stopV_
Detailed Description
Definition at line 40 of file cvLevelSetVelocityThreshold.h.
Constructor & Destructor Documentation
cvLevelSetVelocityThreshold::cvLevelSetVelocityThreshold ()
Definition at line 42 of file cvLevelSetVelocityThreshold.cxx.
References balloonFvalid_, and thr_.
cvLevelSetVelocityThreshold::~cvLevelSetVelocityThreshold ()
Definition at line 53 of file cvLevelSetVelocityThreshold.cxx.
Member Function Documentation
int cvLevelSetVelocityThreshold::Evaluate (double pos[], double * f0, double * f1, double v[], int * forceFlag, double toDot[]) virtual
Implements cvLevelSetVelocity.
Definition at line 159 of file cvLevelSetVelocityThreshold.cxx.
References balloonF_, CV_ERROR, CV_OK, cvLevelSet::GetGrid(), GetIntensity(), cvLevelSetVelocityImage::image_, cvLevelSetStructuredGrid::InterpN(), cvLevelSetVelocity::ls_, NULL, thr_, and Valid().
int cvLevelSetVelocityThreshold::GetBalloonF (double * b)
Definition at line 75 of file cvLevelSetVelocityThreshold.cxx.
References balloonF_, balloonFvalid_, CV_ERROR, and CV_OK.
Referenced by LsetVThr_GetConstMtd().
int cvLevelSetVelocityThreshold::GetMemoryUsage () virtual
Implements cvLevelSetVelocity.
Definition at line 212 of file cvLevelSetVelocityThreshold.cxx.
References cvLevelSetVelocityImage::image_, and Img_GetMemoryUsage().
int cvLevelSetVelocityThreshold::GetThreshold (double * t)
Definition at line 103 of file cvLevelSetVelocityThreshold.cxx.
References CV_ERROR, CV_OK, and thr_.
Referenced by LsetVThr_GetConstMtd().
int cvLevelSetVelocityThreshold::SetBalloonF (double b)
Definition at line 63 of file cvLevelSetVelocityThreshold.cxx.
References balloonF_, balloonFvalid_, and CV_OK.
Referenced by LsetVThr_SetConstMtd().
int cvLevelSetVelocityThreshold::SetThreshold (double t)
Definition at line 89 of file cvLevelSetVelocityThreshold.cxx.
References CV_ERROR, CV_OK, and thr_.
Referenced by LsetVThr_SetConstMtd().
int cvLevelSetVelocityThreshold::StopCondition () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 133 of file cvLevelSetVelocityThreshold.cxx.
References cvLevelSet::GetCurrTime(), cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::GetMaxF(), and cvLevelSetVelocity::ls_.
int cvLevelSetVelocityThreshold::Valid () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 117 of file cvLevelSetVelocityThreshold.cxx.
References balloonFvalid_, cvLevelSetVelocityImage::image_, NULL, thr_, and cvLevelSetVelocity::Valid().
Referenced by Evaluate().
Member Data Documentation
double cvLevelSetVelocityThreshold::balloonF_ private
Definition at line 60 of file cvLevelSetVelocityThreshold.h.
Referenced by Evaluate(), GetBalloonF(), and SetBalloonF().
int cvLevelSetVelocityThreshold::balloonFvalid_ private
Definition at line 61 of file cvLevelSetVelocityThreshold.h.
Referenced by cvLevelSetVelocityThreshold(), GetBalloonF(), SetBalloonF(), and Valid().
double cvLevelSetVelocityThreshold::thr_ private
Definition at line 62 of file cvLevelSetVelocityThreshold.h.
Referenced by cvLevelSetVelocityThreshold(), Evaluate(), GetThreshold(), SetThreshold(), and Valid().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityThreshold.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityThreshold.cxx