simvascular: vtkIntersectionPolyDataFilter2 Class Reference
vtkIntersectionPolyDataFilter2 Class Reference
#include <vtkIntersectionPolyDataFilter2.h>
Classes
class Impl
Public Member Functions
vtkTypeMacro (vtkIntersectionPolyDataFilter2, vtkPolyDataAlgorithm)
virtual void PrintSelf (ostream &os, vtkIndent indent)
vtkGetMacro (NumberOfIntersectionPoints, int)
vtkSetMacro (NumberOfIntersectionPoints, int)
vtkBooleanMacro (NumberOfIntersectionPoints, int)
vtkGetMacro (NumberOfIntersectionLines, int)
vtkSetMacro (NumberOfIntersectionLines, int)
vtkBooleanMacro (NumberOfIntersectionLines, int)
vtkGetMacro (SplitFirstOutput, int)
vtkSetMacro (SplitFirstOutput, int)
vtkBooleanMacro (SplitFirstOutput, int)
vtkGetMacro (SplitSecondOutput, int)
vtkSetMacro (SplitSecondOutput, int)
vtkBooleanMacro (SplitSecondOutput, int)
vtkGetMacro (ApplyBoundaryPointArray, int)
vtkSetMacro (ApplyBoundaryPointArray, int)
vtkBooleanMacro (ApplyBoundaryPointArray, int)
vtkGetMacro (CheckMesh, int)
vtkSetMacro (CheckMesh, int)
vtkBooleanMacro (CheckMesh, int)
Static Public Member Functions
static
vtkIntersectionPolyDataFilter2 * New ()
static int TriangleTriangleIntersection (double p1[3], double q1[3], double r1[3], double p2[3], double q2[3], double r2[3], int &coplanar, double pt1[3], double pt2[3], double surfaceid[2])
static void CleanAndCheckSurface (vtkPolyData *pd, double stats[2])
Protected Member Functions
vtkIntersectionPolyDataFilter2 ()
~vtkIntersectionPolyDataFilter2 ()
int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
int FillInputPortInformation (int, vtkInformation *)
Private Member Functions
vtkIntersectionPolyDataFilter2 (const vtkIntersectionPolyDataFilter2 &)
void operator= (const vtkIntersectionPolyDataFilter2 &)
Private Attributes
int NumberOfIntersectionPoints
int NumberOfIntersectionLines
int SplitFirstOutput
int SplitSecondOutput
int ApplyBoundaryPointArray
int CheckMesh
Detailed Description
Definition at line 37 of file vtkIntersectionPolyDataFilter2.h.
Constructor & Destructor Documentation
vtkIntersectionPolyDataFilter2::vtkIntersectionPolyDataFilter2 () protected
Definition at line 1309 of file vtkIntersectionPolyDataFilter2.cxx.
References ApplyBoundaryPointArray, CheckMesh, NumberOfIntersectionLines, and NumberOfIntersectionPoints.
vtkIntersectionPolyDataFilter2::~vtkIntersectionPolyDataFilter2 () protected
Definition at line 1323 of file vtkIntersectionPolyDataFilter2.cxx.
vtkIntersectionPolyDataFilter2::vtkIntersectionPolyDataFilter2 (const vtkIntersectionPolyDataFilter2 &) private
Member Function Documentation
void vtkIntersectionPolyDataFilter2::CleanAndCheckSurface (vtkPolyData * pd, double stats[2]) static
Definition at line 1531 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by vtkBooleanOperationPolyDataFilter2::RequestData(), RequestData(), and sys_geom_checksurface().
int vtkIntersectionPolyDataFilter2::FillInputPortInformation (int port, vtkInformation * info) protected
Definition at line 1848 of file vtkIntersectionPolyDataFilter2.cxx.
static vtkIntersectionPolyDataFilter2* vtkIntersectionPolyDataFilter2::New () static
void vtkIntersectionPolyDataFilter2::operator= (const vtkIntersectionPolyDataFilter2 &) private
void vtkIntersectionPolyDataFilter2::PrintSelf (ostream & os, vtkIndent indent) virtual
Definition at line 1328 of file vtkIntersectionPolyDataFilter2.cxx.
References ApplyBoundaryPointArray, CheckMesh, SplitFirstOutput, and SplitSecondOutput.
int vtkIntersectionPolyDataFilter2::RequestData (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected
Definition at line 1592 of file vtkIntersectionPolyDataFilter2.cxx.
References ApplyBoundaryPointArray, vtkIntersectionPolyDataFilter2::Impl::BoundaryPoints, vtkIntersectionPolyDataFilter2::Impl::CellIds, CheckMesh, CleanAndCheckSurface(), vtkIntersectionPolyDataFilter2::Impl::FindTriangleIntersections(), impl, vtkIntersectionPolyDataFilter2::Impl::IntersectionLines, vtkIntersectionPolyDataFilter2::Impl::Mesh, vtkIntersectionPolyDataFilter2::Impl::NewCellIds, NumberOfIntersectionLines, NumberOfIntersectionPoints, vtkIntersectionPolyDataFilter2::Impl::OBBTree1, vtkIntersectionPolyDataFilter2::Impl::PointCellIds, vtkIntersectionPolyDataFilter2::Impl::PointMapper, vtkIntersectionPolyDataFilter2::Impl::PointMerger, SplitFirstOutput, vtkIntersectionPolyDataFilter2::Impl::SplitMesh(), SplitSecondOutput, and vtkIntersectionPolyDataFilter2::Impl::SurfaceId.
int vtkIntersectionPolyDataFilter2::TriangleTriangleIntersection (double p1[3], double q1[3], double r1[3], double p2[3], double q2[3], double r2[3], int & coplanar, double pt1[3], double pt2[3], double surfaceid[2]) static
Definition at line 1340 of file vtkIntersectionPolyDataFilter2.cxx.
References Cross(), and Dot().
Referenced by vtkIntersectionPolyDataFilter2::Impl::FindTriangleIntersections().
vtkIntersectionPolyDataFilter2::vtkBooleanMacro (NumberOfIntersectionPoints , int)
vtkIntersectionPolyDataFilter2::vtkBooleanMacro (NumberOfIntersectionLines , int)
vtkIntersectionPolyDataFilter2::vtkBooleanMacro (SplitFirstOutput , int)
vtkIntersectionPolyDataFilter2::vtkBooleanMacro (SplitSecondOutput , int)
vtkIntersectionPolyDataFilter2::vtkBooleanMacro (ApplyBoundaryPointArray , int)
vtkIntersectionPolyDataFilter2::vtkBooleanMacro (CheckMesh , int)
vtkIntersectionPolyDataFilter2::vtkGetMacro (NumberOfIntersectionPoints , int)
vtkIntersectionPolyDataFilter2::vtkGetMacro (NumberOfIntersectionLines , int)
vtkIntersectionPolyDataFilter2::vtkGetMacro (SplitFirstOutput , int)
vtkIntersectionPolyDataFilter2::vtkGetMacro (SplitSecondOutput , int)
vtkIntersectionPolyDataFilter2::vtkGetMacro (ApplyBoundaryPointArray , int)
vtkIntersectionPolyDataFilter2::vtkGetMacro (CheckMesh , int)
vtkIntersectionPolyDataFilter2::vtkSetMacro (NumberOfIntersectionPoints , int)
vtkIntersectionPolyDataFilter2::vtkSetMacro (NumberOfIntersectionLines , int)
vtkIntersectionPolyDataFilter2::vtkSetMacro (SplitFirstOutput , int)
vtkIntersectionPolyDataFilter2::vtkSetMacro (SplitSecondOutput , int)
vtkIntersectionPolyDataFilter2::vtkSetMacro (ApplyBoundaryPointArray , int)
vtkIntersectionPolyDataFilter2::vtkSetMacro (CheckMesh , int)
vtkIntersectionPolyDataFilter2::vtkTypeMacro (vtkIntersectionPolyDataFilter2 , vtkPolyDataAlgorithm)
Member Data Documentation
int vtkIntersectionPolyDataFilter2::ApplyBoundaryPointArray private
Definition at line 110 of file vtkIntersectionPolyDataFilter2.h.
Referenced by PrintSelf(), RequestData(), and vtkIntersectionPolyDataFilter2().
int vtkIntersectionPolyDataFilter2::CheckMesh private
Definition at line 111 of file vtkIntersectionPolyDataFilter2.h.
Referenced by PrintSelf(), RequestData(), and vtkIntersectionPolyDataFilter2().
int vtkIntersectionPolyDataFilter2::NumberOfIntersectionLines private
Definition at line 107 of file vtkIntersectionPolyDataFilter2.h.
Referenced by RequestData(), and vtkIntersectionPolyDataFilter2().
int vtkIntersectionPolyDataFilter2::NumberOfIntersectionPoints private
Definition at line 106 of file vtkIntersectionPolyDataFilter2.h.
Referenced by RequestData(), and vtkIntersectionPolyDataFilter2().
int vtkIntersectionPolyDataFilter2::SplitFirstOutput private
Definition at line 108 of file vtkIntersectionPolyDataFilter2.h.
Referenced by PrintSelf(), and RequestData().
int vtkIntersectionPolyDataFilter2::SplitSecondOutput private
Definition at line 109 of file vtkIntersectionPolyDataFilter2.h.
Referenced by PrintSelf(), and RequestData().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkIntersectionPolyDataFilter2.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkIntersectionPolyDataFilter2.cxx