simvascular: cvLispListIterator< T > Class Template Reference
cvLispListIterator< T > Class Template Reference
#include <cvLispList.h>
Public Member Functions
cvLispListIterator (cvLispList< T > *list)
Bool IsDone ()
T Item ()
void Next ()
Private Attributes
cvLispListElement< T > * current
Detailed Description
template<class T>
class cvLispListIterator< T >
Definition at line 80 of file cvLispList.h.
Constructor & Destructor Documentation
template<class T> cvLispListIterator< T >::cvLispListIterator (cvLispList< T > * list) inline
Definition at line 184 of file cvLispList.h.
Member Function Documentation
template<class T> Bool cvLispListIterator< T >::IsDone () inline
Definition at line 187 of file cvLispList.h.
Referenced by cvLevelSetSparseGrid::GetNextHTItem(), cvLevelSetSparseGrid::IJKPresentInHT(), cvLispListIterator< TableStruct * >::Item(), cvParasolidSolidModel::ListToArray(), and cvLispList< T >::SelfTest().
template<class T> T cvLispListIterator< T >::Item () inline
Definition at line 190 of file cvLispList.h.
Referenced by cvLevelSetSparseGrid::GetNextHTItem(), cvLevelSetSparseGrid::IJKPresentInHT(), and cvParasolidSolidModel::ListToArray().
template<class T> void cvLispListIterator< T >::Next () inline
Definition at line 193 of file cvLispList.h.
Referenced by cvLevelSetSparseGrid::GetNextHTItem(), cvLevelSetSparseGrid::IJKPresentInHT(), cvParasolidSolidModel::ListToArray(), and cvLispList< T >::SelfTest().
Member Data Documentation
template<class T> cvLispListElement<T>* cvLispListIterator< T >::current private
Definition at line 193 of file cvLispList.h.
Referenced by cvLispListIterator< TableStruct * >::cvLispListIterator(), cvLispListIterator< TableStruct * >::IsDone(), cvLispListIterator< TableStruct * >::Item(), and cvLispListIterator< TableStruct * >::Next().
The documentation for this class was generated from the following file:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvLispList.h