simvascular: cvTetAdaptCore Class Reference
cvTetAdaptCore Class Reference
#include <cvTetAdaptCore.h>
Public Member Functions
void ModifyHessiansAtBdry (vtkUnstructuredGrid *mesh)
void ModifyMetric (vtkIdType vertex, double dir[3][3], double *h)
void SmoothHessians (vtkUnstructuredGrid *mesh)
simple average over a patch surrounding the vertex
void getHessiansFromPhasta (double *hessiansFromPhasta, vtkUnstructuredGrid *mesh, int nvar, double *hessians)
extracts hessians from vector retrieved from restart and puts it in an attachable format for vtk
void getHessian (vtkDoubleArray *Hessians, vtkIdType v, double T[3][3])
returns a vector with hessian values from vtkDoubleArray
void attachArray (double *valueArray, vtkUnstructuredGrid *mesh, std::string dataName, int nVar, int poly)
This attaches an array of doubles to a vtkUnstructuredGrid.
void getAttachedArray (double *&valueArray, vtkUnstructuredGrid *mesh, std::string dataName, int nVar, int poly)
This gets an array that is attached to a vtkUnstructuredGrid.
void phastaTransfer (int mtype, int mco, void *userData)
void fix4SolutionTransfer (vtkUnstructuredGrid *inmesh, vtkUnstructuredGrid *outmesh, int nVar)
This function interpolates the solution from the old mesh onto the new mesh.
void gradientsFromFilter (vtkUnstructuredGrid *mesh)
Filter to take the gradients of a scalar array, should be speed.
void hessiansFromFilter (vtkUnstructuredGrid *mesh)
Filter to take the hessians of gradient array.
void hessiansFromSolution (vtkUnstructuredGrid *mesh, int stepNumber)
This function calls the gradient and hessian filters to get hessian matrix in order to set the mesh size field.
int applyMarkingStrategy (vtkUnstructuredGrid *mesh, int simTetGenAdapter, double factor, double hmin, double hmax, double &totalError, double &maxError, double &minError, double &threshold, int option)
double getErrorThreshold (vtkUnstructuredGrid *mesh, double factor, double &totalError, double &maxError, double &minError, int option)
double getErrorValue (double *nodalValues, int option)
void setSizeFieldUsingHessians (vtkUnstructuredGrid *mesh, tetgenio *inmesh, double factor, double hmax, double hmin)
This function takes the hessian field data and computes a mesh size field for the mesh adaptation/refinement.
double maxLocalError (vtkUnstructuredGrid *mesh, vtkIdType vertex, double H[3][3])
This returns the maximum relative interpolation error at a vertex.
double E_error (double xyz[2][3], double H[3][3])
This is called by maxLocalError. It gets the error along an edge.
void setIsotropicSizeField (vtkUnstructuredGrid *mesh, int simTetGenAdapter, double factor, double hmax, double hmin, int option)
void setManualSizeField (vtkUnstructuredGrid *mesh, int simTetGenAdapter, int strategy)
void tagEntitiesForRefinement (vtkUnstructuredGrid *mesh, int simTetGenAdapter, double factor, double hmax, double hmin, int option)
void writeMEDITSolution (vtkUnstructuredGrid *mesh)
void writeMEDITSizeField (Hessian *hess, vtkUnstructuredGrid *mesh)
int getSurfaceBooleans (vtkUnstructuredGrid *mesh, bool *pointOnSurface, int *pointMapper)
This is a function to determine what points of a mesh on on the surface. This is done by applying node ids, extracting the surface, and then checking for matching node ids.
int convertToTetGen (vtkUnstructuredGrid *mesh, vtkPolyData *surfaceMesh, tetgenio *inmesh)
Function to convert the current mesh to a tetgen mesh object to be able to remesh.
int runAdaptor (tetgenio *inmesh, tetgenio *outmesh)
This is a function to run tetgen on the mesh.
int convertToVTK (vtkUnstructuredGrid *mesh, vtkPolyData *surfaceMesh, tetgenio *outmesh)
This is a function to convert back to vtk structured from a tetgen mesh.
Public Attributes
int phasta_solution
int nodalgradientID
int nodalhessianID
int errorIndicatorID
std::ofstream adaptSimLog
int CBcounter
int CBinvalidRegionCount
int modes
int numVars
char * iformat
Detailed Description
Definition at line 77 of file cvTetAdaptCore.h.
Member Function Documentation
int cvTetAdaptCore::applyMarkingStrategy (vtkUnstructuredGrid * mesh, int simAdapter, double factor, double hmin, double hmax, double & totalError, double & maxError, double & minError, double & threshold, int option)
Parameters
@param
Definition at line 510 of file cvTetAdaptCore.cxx.
References CV_ERROR.
void cvTetAdaptCore::attachArray (double * valueArray, vtkUnstructuredGrid * mesh, std::string dataName, int nVar, int poly)
This attaches an array of doubles to a vtkUnstructuredGrid.
Parameters
nVar = 5 (for flow problems) or 27 (for hessians)
poly is the polynomial order
Note
called in setSizeFieldUsingHessians (sizefield.cc)
Definition at line 219 of file cvTetAdaptCore.cxx.
Referenced by cvTetAdapt::Adapt().
int cvTetAdaptCore::convertToTetGen (vtkUnstructuredGrid * mesh, vtkPolyData * surfaceMesh, tetgenio * inmesh)
Function to convert the current mesh to a tetgen mesh object to be able to remesh.
Parameters
mesh This is the full mesh to be remeshed
surfaceMesh This is the intial mesh; If we don't need the final mesh regions, then we don't have to actually use this
inmesh This is the tegen mesh object to be transferred to
Definition at line 938 of file cvTetAdaptCore.cxx.
References CV_OK.
Referenced by cvTetAdapt::Adapt().
int cvTetAdaptCore::convertToVTK (vtkUnstructuredGrid * mesh, vtkPolyData * surfaceMesh, tetgenio * outmesh)
This is a function to convert back to vtk structured from a tetgen mesh.
Parameters
mesh This is the vtk object to contain the new mesh
surfaceMesh This is the vtk object to contain the new surface mesh
outmesh This is the tetgen object returned from tetgen
Definition at line 1101 of file cvTetAdaptCore.cxx.
References CV_OK, and NULL.
Referenced by cvTetAdapt::Adapt().
double cvTetAdaptCore::E_error (double xyz[2][3], double H[3][3])
This is called by maxLocalError. It gets the error along an edge.
Parameters
xyz contains the x, y, and z coordinates for the two points on an edge
H This contains the Hessian information
Definition at line 836 of file cvTetAdaptCore.cxx.
References ABS.
Referenced by maxLocalError().
void cvTetAdaptCore::fix4SolutionTransfer (vtkUnstructuredGrid * inmesh, vtkUnstructuredGrid * outmesh, int nVar)
This function interpolates the solution from the old mesh onto the new mesh.
Parameters
inmesh This is the original mesh
outmesh This is the new adapted mesh that needs solution information
nVar This is the number of components in the solutions array
Note
This takes the solution from the closest node
Definition at line 332 of file cvTetAdaptCore.cxx.
Referenced by cvTetAdapt::Adapt().
void cvTetAdaptCore::getAttachedArray (double *& valueArray, vtkUnstructuredGrid * mesh, std::string dataName, int nVar, int poly)
This gets an array that is attached to a vtkUnstructuredGrid.
Parameters
valueArray This is the array containing the extracted field
mesh this is the vtkUnstructured Grid with the data fields
dataName This is the name of the data field to be extraced
nVar This is the number of components of the array
poly This is the polynomial order of the data (currently only 1)
Definition at line 276 of file cvTetAdaptCore.cxx.
References adaptSimLog, and nshg.
Referenced by cvTetAdapt::Adapt().
double cvTetAdaptCore::getErrorThreshold (vtkUnstructuredGrid * mesh, double factor, double & totalError, double & maxError, double & minError, int option)
Parameters
@param
Definition at line 528 of file cvTetAdaptCore.cxx.
References CV_ERROR.
double cvTetAdaptCore::getErrorValue (double * nodalValues, int option)
Parameters
@param
Definition at line 547 of file cvTetAdaptCore.cxx.
References adaptSimLog.
void cvTetAdaptCore::getHessian (vtkDoubleArray * Hessians, vtkIdType v, double T[3][3])
returns a vector with hessian values from vtkDoubleArray
Note
The hessian returned is a 6 component symmetric matrix
u_xx, u_xy, u_xz, u_yy, u_yz, u_zz
called in setSizeFieldUsingHessians (sizefield.cc)
Definition at line 193 of file cvTetAdaptCore.cxx.
Referenced by setSizeFieldUsingHessians().
void cvTetAdaptCore::getHessiansFromPhasta (double * hessiansFromPhasta, vtkUnstructuredGrid * mesh, int nvar, double * hessians)
extracts hessians from vector retrieved from restart and puts it in an attachable format for vtk
Parameters
the vector from the restart containing all the hessians
hessians this is the new stored array with the six components of the symmetric hessian matrix
Definition at line 167 of file cvTetAdaptCore.cxx.
Referenced by cvTetAdapt::Adapt().
int cvTetAdaptCore::getSurfaceBooleans (vtkUnstructuredGrid * mesh, bool * pointOnSurface, int * pointMapper)
This is a function to determine what points of a mesh on on the surface. This is done by applying node ids, extracting the surface, and then checking for matching node ids.
Parameters
mesh This is the mesh to get the booleans for
pointOnSurface This is a boolean vector with information on whether or not a point is on the surface of the mesh
pointMapper This is a vector containing the mappings between the surface mesh and the volumetric mesh
Definition at line 1009 of file cvTetAdaptCore.cxx.
References NULL.
Referenced by SmoothHessians().
void cvTetAdaptCore::gradientsFromFilter (vtkUnstructuredGrid * mesh)
Filter to take the gradients of a scalar array, should be speed.
Parameters
mesh The mesh with the attached field data information (speed)
Definition at line 384 of file cvTetAdaptCore.cxx.
Referenced by hessiansFromSolution().
void cvTetAdaptCore::hessiansFromFilter (vtkUnstructuredGrid * mesh)
Filter to take the hessians of gradient array.
Parameters
mesh The mesh with the attached gradient field data
Definition at line 430 of file cvTetAdaptCore.cxx.
Referenced by hessiansFromSolution().
void cvTetAdaptCore::hessiansFromSolution (vtkUnstructuredGrid * mesh, int stepNumber)
This function calls the gradient and hessian filters to get hessian matrix in order to set the mesh size field.
Note
hessian returned : 6-component (symmetric)
u_xx, u_xy, u_xz, u_yy, u_yz, u_zz
Definition at line 474 of file cvTetAdaptCore.cxx.
References gradientsFromFilter(), hessiansFromFilter(), and SmoothHessians().
Referenced by cvTetAdapt::Adapt().
double cvTetAdaptCore::maxLocalError (vtkUnstructuredGrid * mesh, vtkIdType vertex, double H[3][3])
This returns the maximum relative interpolation error at a vertex.
Parameters
vertex This is the vertex where the max local error is calculated
H This is the Hessian matrix that the error is calculated for
Definition at line 776 of file cvTetAdaptCore.cxx.
References E_error().
Referenced by setSizeFieldUsingHessians().
void cvTetAdaptCore::ModifyHessiansAtBdry (vtkUnstructuredGrid * mesh)
void cvTetAdaptCore::ModifyMetric (vtkIdType vertex, double dir[3][3], double * h)
Definition at line 57 of file cvTetAdaptCore.cxx.
void cvTetAdaptCore::phastaTransfer (int mtype, int mco, void * userData)
Parameters
@param
Definition at line 317 of file cvTetAdaptCore.cxx.
int cvTetAdaptCore::runAdaptor (tetgenio * inmesh, tetgenio * outmesh)
This is a function to run tetgen on the mesh.
Parameters
inmesh This is the original mesh as a tetgen object
outmesh This is the new adapted mesh as a tetgen object
Definition at line 1065 of file cvTetAdaptCore.cxx.
References CV_OK.
Referenced by cvTetAdapt::Adapt().
void cvTetAdaptCore::setIsotropicSizeField (vtkUnstructuredGrid * mesh, int simAdapter, double factor, double hmax, double hmin, int option)
Parameters
@param
Definition at line 863 of file cvTetAdaptCore.cxx.
void cvTetAdaptCore::setManualSizeField (vtkUnstructuredGrid * mesh, int simAdapter, int strategy)
Parameters
@param
Definition at line 882 of file cvTetAdaptCore.cxx.
void cvTetAdaptCore::setSizeFieldUsingHessians (vtkUnstructuredGrid * mesh, tetgenio * inmesh, double factor, double hmax, double hmin)
This function takes the hessian field data and computes a mesh size field for the mesh adaptation/refinement.
Parameters
mesh This is the mesh to be adapted
inmesh This is the tetgen mesh object to be constructucted
factor This is the ratio refinement factor
hmax This is the maximum edge length acceptable for the mesh
hmin This is the minimum edge length acceptable for the mesh
Definition at line 585 of file cvTetAdaptCore.cxx.
References ABS, adaptSimLog, getHessian(), MAX, maxLocalError(), mytred, nshg, T, three, and tql2.
Referenced by cvTetAdapt::Adapt().
void cvTetAdaptCore::SmoothHessians (vtkUnstructuredGrid * mesh)
simple average over a patch surrounding the vertex
Note
This smooths the hessians by patch method
Definition at line 69 of file cvTetAdaptCore.cxx.
References getSurfaceBooleans(), and NULL.
Referenced by hessiansFromSolution().
void cvTetAdaptCore::tagEntitiesForRefinement (vtkUnstructuredGrid * mesh, int simAdapter, double factor, double hmax, double hmin, int option)
Parameters
@param
Definition at line 900 of file cvTetAdaptCore.cxx.
void cvTetAdaptCore::writeMEDITSizeField (Hessian * hess, vtkUnstructuredGrid * mesh)
Parameters
@param
Definition at line 922 of file cvTetAdaptCore.cxx.
void cvTetAdaptCore::writeMEDITSolution (vtkUnstructuredGrid * mesh)
Member Data Documentation
std::ofstream cvTetAdaptCore::adaptSimLog
Definition at line 209 of file cvTetAdaptCore.h.
Referenced by getAttachedArray(), getErrorValue(), and setSizeFieldUsingHessians().
int cvTetAdaptCore::CBcounter
Definition at line 212 of file cvTetAdaptCore.h.
Referenced by cvTetAdapt::cvTetAdapt().
int cvTetAdaptCore::CBinvalidRegionCount
Definition at line 213 of file cvTetAdaptCore.h.
Referenced by cvTetAdapt::cvTetAdapt().
int cvTetAdaptCore::errorIndicatorID
Definition at line 207 of file cvTetAdaptCore.h.
char* cvTetAdaptCore::iformat
Definition at line 216 of file cvTetAdaptCore.h.
Referenced by cvTetAdapt::cvTetAdapt().
int cvTetAdaptCore::modes
Definition at line 214 of file cvTetAdaptCore.h.
int cvTetAdaptCore::nodalgradientID
Definition at line 205 of file cvTetAdaptCore.h.
int cvTetAdaptCore::nodalhessianID
Definition at line 206 of file cvTetAdaptCore.h.
int cvTetAdaptCore::numVars
Definition at line 215 of file cvTetAdaptCore.h.
Referenced by cvTetAdapt::cvTetAdapt().
int cvTetAdaptCore::phasta_solution
Definition at line 204 of file cvTetAdaptCore.h.
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/TetAdapt/cvTetAdaptCore.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/TetAdapt/cvTetAdaptCore.cxx