simvascular: cvMeshObject Class Reference
cvMeshObject Class Reference abstract
#include <cvMeshObject.h>
Public Types
enum KernelType {
KERNEL_INVALID, KERNEL_MESHSIM, KERNEL_TETGEN, KERNEL_GMSH,
KERNEL_MAX_TYPES
}
Public Member Functions
cvMeshObject ()
virtual ~cvMeshObject ()
virtual int SetMeshFileName (const char *filename)=0
virtual int SetSolidFileName (const char *filename)=0
cvMeshObject::KernelType GetMeshKernel () const
SolidModel_KernelT GetSolidModelKernel () const
void SetSolidModelKernel (SolidModel_KernelT kernel)
int GetMeshLoaded ()
int GetElementType ()
virtual int Update ()=0
virtual int Print ()=0
virtual cvMeshObject * Copy () const =0
virtual int LoadModel (char *filename)=0
virtual int GetBoundaryFaces (double angle)=0
virtual int LoadMesh (char *filename)=0
virtual int NewMesh ()=0
virtual int SetSurfaceMeshFlag (int value)=0
virtual int SetSurfaceOptimization (int value)=0
virtual int SetSurfaceSmoothing (int value)=0
virtual int SetVolumeMeshFlag (int value)=0
virtual int SetVolumeOptimization (int value)=0
virtual int SetVolumeSmoothing (int value)=0
virtual int SetGlobalSize (int type, double gsize)=0
virtual int SetLocalSize (int type, int id, double size)=0
virtual int SetGlobalCurv (int type, double size)=0
virtual int SetLocalCurv (int type, int id, double size)=0
virtual int SetGlobalMinCurv (int type, double size)=0
virtual int SetLocalMinCurv (int type, int id, double size)=0
virtual int SetMeshOptions (char *flags, double value)=0
virtual int SetBoundaryLayer (int type, int id, int side, int nL, double *H)=0
virtual int SetCylinderRefinement (double size, double radius, double length, double *center, double *normal)=0
virtual int SetSphereRefinement (double size, double radius, double *center)=0
virtual int SetSizeFunctionBasedMesh (double size, char *sizefunctionname)=0
virtual int GenerateMesh ()=0
virtual int WriteMesh (char *filename, int smsver)=0
virtual int WriteStats (char *filename)=0
int WriteAbaqusInputDeck (char *filename)
int WriteProphlexInputDeck (char *filename)
int WriteSpectrumSolverElements (char *filename)
int WriteSpectrumSolverNodes (char *filename)
int WriteSpectrumVisMesh (char *filename)
int WriteSpectrumVisData (char *filename)
virtual int WriteDataExplorer (char *filename)=0
int WriteMeshVrml (char *filename)
int WriteSurfaceMeshVrml (char *filename)
int WriteSurfaceMeshOogl (char *filename)
int WriteHypermeshAscii (char *filename)
virtual int WriteMetisAdjacency (char *filename)=0
virtual int GetElementConnectivity (int element)=0
virtual int GetNodeCoords (int node)=0
virtual cvPolyData * GetPolyData ()=0
virtual cvUnstructuredGrid * GetUnstructuredGrid ()=0
virtual int GetModelFaceInfo (char rtnstr[99999])=0
virtual int GetElementNodesOnModelFace (int face, char *filename)=0
virtual int GetElementFacesOnModelFace (int face, int explicitFaceOut, char *filename)=0
virtual cvPolyData * GetFacePolyData (int orgfaceid)=0
virtual int GetElementsInModelRegion (int region, char *filename)=0
virtual int GetExteriorElementFacesOnRegion (int region, char *filename)=0
virtual int GenerateQuadraticElements ()=0
virtual void initNodeTraversal ()=0
virtual void initElementTraversal ()=0
virtual void initRegionTraversal ()=0
virtual int getNextNode ()=0
virtual int getNextElement ()=0
virtual int getNextRegion ()=0
virtual int getNeighborMdlRegIds ()=0
virtual int SetVtkPolyDataObject (vtkPolyData *newPolyData)=0
int openOutputFile (char *filename)
int closeOutputFile ()
Public Member Functions inherited from cvRepositoryData
cvRepositoryData (RepositoryDataT type)
virtual ~cvRepositoryData ()
void Lock ()
void Release ()
int NumLocks ()
RepositoryDataT GetType ()
char * GetName ()
void SetName (char *in)
int GetNumLabels ()
void GetLabelKeys (int *numKeys, char **keys[])
int IsLabelPresent (char *key)
int GetLabel (char *key, char **value)
int SetLabel (char *key, char *value)
void ClearLabel (char *key)
virtual int GetMemoryUsage ()
Static Public Member Functions
static char * GetKernelName (KernelType kernel)
static KernelType GetKernelType (const char *kernel_name)
Public Attributes
int nodeID_
double nodeX_
double nodeY_
double nodeZ_
Protected Attributes
cvMeshObject::KernelType mesh_kernel_
SolidModel_KernelT solidmodeling_kernel_
int meshloaded_
int quadElem_
int numLinearNodes_
int numNodes_
int numElements_
int numModelRegions_
int * regionID_
int curElemID_
int connID_ [30]
int curElemNe_ [4][2]
int curMdlRegID_
FILE * fp_
Private Member Functions
int outputOoglFaceNodes (int n1, int n2, int n3, int n4, double maxpoint)
Detailed Description
Definition at line 65 of file cvMeshObject.h.
Member Enumeration Documentation
enum cvMeshObject::KernelType
Enumerator
KERNEL_INVALID
KERNEL_MESHSIM
KERNEL_TETGEN
KERNEL_GMSH
KERNEL_MAX_TYPES
Definition at line 68 of file cvMeshObject.h.
Constructor & Destructor Documentation
cvMeshObject::cvMeshObject ()
Definition at line 42 of file cvMeshObject.cxx.
cvMeshObject::~cvMeshObject () virtual
Definition at line 53 of file cvMeshObject.cxx.
Member Function Documentation
int cvMeshObject::closeOutputFile ()
Definition at line 122 of file cvMeshObject.cxx.
References CV_OK, fp_, and gzclose.
Referenced by cvMeshSimMeshObject::GetElementFacesOnModelFace(), cvMeshSimMeshObject::GetElementNodesOnModelFace(), cvMeshSimMeshObject::GetElementsInModelRegion(), cvMeshSimMeshObject::GetExteriorElementFacesOnRegion(), cvMeshSimMeshObject::OutputExteriorElementFaces(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), cvMeshSimMeshObject::WriteMetisAdjacency(), cvTetGenMeshObject::WriteMetisAdjacency(), WriteProphlexInputDeck(), WriteSpectrumSolverElements(), WriteSpectrumSolverNodes(), WriteSpectrumVisData(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
virtual cvMeshObject* cvMeshObject::Copy () const pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
virtual int cvMeshObject::GenerateMesh () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GenerateMeshMtd().
virtual int cvMeshObject::GenerateQuadraticElements () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GenerateQuadraticElementsMtd().
virtual int cvMeshObject::GetBoundaryFaces (double angle) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetBoundaryFacesMtd().
virtual int cvMeshObject::GetElementConnectivity (int element) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetElementConnectivityMtd().
virtual int cvMeshObject::GetElementFacesOnModelFace (int face, int explicitFaceOut, char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetElementFacesOnModelFaceMtd().
virtual int cvMeshObject::GetElementNodesOnModelFace (int face, char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetElementNodesOnModelFaceMtd().
virtual int cvMeshObject::GetElementsInModelRegion (int region, char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetElementsInModelRegionMtd().
int cvMeshObject::GetElementType () inline
Definition at line 94 of file cvMeshObject.h.
References quadElem_.
Referenced by cvMesh_GetElementTypeMtd().
virtual int cvMeshObject::GetExteriorElementFacesOnRegion (int region, char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetExteriorElementFacesOnRegionMtd().
virtual cvPolyData* cvMeshObject::GetFacePolyData (int orgfaceid) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetFacePolyDataMtd().
char * cvMeshObject::GetKernelName (cvMeshObject::KernelType kernel) static
Definition at line 61 of file cvMeshObject.cxx.
References KERNEL_GMSH, KERNEL_MESHSIM, KERNEL_TETGEN, and NULL.
Referenced by cvMeshSystem::GetCurrentKernelName().
cvMeshObject::KernelType cvMeshObject::GetKernelType (const char * kernel_name) static
Definition at line 87 of file cvMeshObject.cxx.
References KERNEL_GMSH, KERNEL_INVALID, KERNEL_MESHSIM, and KERNEL_TETGEN.
Referenced by cvMesh_SetMeshKernelCmd().
cvMeshObject::KernelType cvMeshObject::GetMeshKernel () const inline
Definition at line 88 of file cvMeshObject.h.
References mesh_kernel_.
int cvMeshObject::GetMeshLoaded () inline
Definition at line 93 of file cvMeshObject.h.
References meshloaded_.
Referenced by cvMesh_ObjectCmd().
virtual int cvMeshObject::GetModelFaceInfo (char rtnstr[99999]) pure virtual
Implemented in cvMeshSimMeshObject, and cvTetGenMeshObject.
Referenced by cvMesh_GetModelFaceInfoMtd().
virtual int cvMeshObject::getNeighborMdlRegIds () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
virtual int cvMeshObject::getNextElement () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverElements(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
virtual int cvMeshObject::getNextNode () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverNodes(), WriteSpectrumVisData(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
virtual int cvMeshObject::getNextRegion () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverElements(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
virtual int cvMeshObject::GetNodeCoords (int node) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetNodeCoordsMtd(), and outputOoglFaceNodes().
virtual cvPolyData* cvMeshObject::GetPolyData () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetPolyDataMtd().
SolidModel_KernelT cvMeshObject::GetSolidModelKernel () const inline
Definition at line 90 of file cvMeshObject.h.
References solidmodeling_kernel_.
Referenced by cvMesh_GetSolidKernelMtd().
virtual cvUnstructuredGrid* cvMeshObject::GetUnstructuredGrid () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_GetUnstructuredGridMtd().
virtual void cvMeshObject::initElementTraversal () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverElements(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
virtual void cvMeshObject::initNodeTraversal () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverNodes(), WriteSpectrumVisData(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
virtual void cvMeshObject::initRegionTraversal () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverElements(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
virtual int cvMeshObject::LoadMesh (char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_LoadMeshMtd().
virtual int cvMeshObject::LoadModel (char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_LoadModelMtd().
virtual int cvMeshObject::NewMesh () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_NewMeshMtd().
int cvMeshObject::openOutputFile (char * filename)
Definition at line 100 of file cvMeshObject.cxx.
References CV_ERROR, CV_OK, fp_, gzopen, MAXPATHLEN, and NULL.
Referenced by cvMeshSimMeshObject::GetElementFacesOnModelFace(), cvMeshSimMeshObject::GetElementNodesOnModelFace(), cvMeshSimMeshObject::GetElementsInModelRegion(), cvMeshSimMeshObject::GetExteriorElementFacesOnRegion(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), cvMeshSimMeshObject::WriteMetisAdjacency(), cvTetGenMeshObject::WriteMetisAdjacency(), WriteProphlexInputDeck(), WriteSpectrumSolverElements(), WriteSpectrumSolverNodes(), WriteSpectrumVisData(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
int cvMeshObject::outputOoglFaceNodes (int n1, int n2, int n3, int n4, double maxpoint) private
Definition at line 805 of file cvMeshObject.cxx.
References CV_ERROR, CV_OK, fp_, GetNodeCoords(), gzprintf, nodeX_, nodeY_, and nodeZ_.
Referenced by WriteSurfaceMeshOogl().
virtual int cvMeshObject::Print () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_PrintMtd().
virtual int cvMeshObject::SetBoundaryLayer (int type, int id, int side, int nL, double * H) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetBoundaryLayerMtd().
virtual int cvMeshObject::SetCylinderRefinement (double size, double radius, double length, double * center, double * normal) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetCylinderRefinementMtd().
virtual int cvMeshObject::SetGlobalCurv (int type, double size) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetGlobalCurvMtd().
virtual int cvMeshObject::SetGlobalMinCurv (int type, double size) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetGlobalMinCurvMtd().
virtual int cvMeshObject::SetGlobalSize (int type, double gsize) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetGlobalSizeMtd().
virtual int cvMeshObject::SetLocalCurv (int type, int id, double size) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetLocalCurvMtd().
virtual int cvMeshObject::SetLocalMinCurv (int type, int id, double size) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetLocalMinCurvMtd().
virtual int cvMeshObject::SetLocalSize (int type, int id, double size) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetLocalSizeMtd().
virtual int cvMeshObject::SetMeshFileName (const char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMeshSystem::DefaultInstantiateMeshObject().
virtual int cvMeshObject::SetMeshOptions (char * flags, double value) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetMeshOptionsMtd().
virtual int cvMeshObject::SetSizeFunctionBasedMesh (double size, char * sizefunctionname) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetSizeFunctionBasedMeshMtd().
virtual int cvMeshObject::SetSolidFileName (const char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMeshSystem::DefaultInstantiateMeshObject().
void cvMeshObject::SetSolidModelKernel (SolidModel_KernelT kernel) inline
Definition at line 91 of file cvMeshObject.h.
References solidmodeling_kernel_.
Referenced by cvMesh_SetSolidKernelMtd().
virtual int cvMeshObject::SetSphereRefinement (double size, double radius, double * center) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetSphereRefinementMtd().
virtual int cvMeshObject::SetSurfaceMeshFlag (int value) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetSurfaceMeshFlagMtd().
virtual int cvMeshObject::SetSurfaceOptimization (int value) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetSurfaceOptimizationMtd().
virtual int cvMeshObject::SetSurfaceSmoothing (int value) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetSurfaceSmoothingMtd().
virtual int cvMeshObject::SetVolumeMeshFlag (int value) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetVolumeMeshFlagMtd().
virtual int cvMeshObject::SetVolumeOptimization (int value) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetVolumeOptimizationMtd().
virtual int cvMeshObject::SetVolumeSmoothing (int value) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_SetVolumeSmoothingMtd().
virtual int cvMeshObject::SetVtkPolyDataObject (vtkPolyData * newPolyData) pure virtual
Implemented in cvMeshSimMeshObject, and cvTetGenMeshObject.
Referenced by cvMesh_SetVtkPolyDataMtd().
virtual int cvMeshObject::Update () pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_ObjectCmd(), and cvMesh_UpdateMtd().
int cvMeshObject::WriteAbaqusInputDeck (char * filename)
Definition at line 388 of file cvMeshObject.cxx.
References closeOutputFile(), connID_, curElemID_, curMdlRegID_, CV_ERROR, CV_OK, fp_, getNextElement(), getNextNode(), getNextRegion(), gzprintf, initElementTraversal(), initNodeTraversal(), initRegionTraversal(), nodeID_, nodeX_, nodeY_, nodeZ_, numModelRegions_, openOutputFile(), quadElem_, and regionID_.
Referenced by cvMesh_WriteABAQUSMtd().
virtual int cvMeshObject::WriteDataExplorer (char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_WriteDataExplorerMtd().
int cvMeshObject::WriteHypermeshAscii (char * filename)
Definition at line 635 of file cvMeshObject.cxx.
References closeOutputFile(), connID_, curElemID_, curMdlRegID_, CV_ERROR, CV_OK, fp_, getNextElement(), getNextNode(), getNextRegion(), gzprintf, initElementTraversal(), initNodeTraversal(), initRegionTraversal(), nodeID_, nodeX_, nodeY_, nodeZ_, openOutputFile(), and quadElem_.
Referenced by cvMesh_WriteHypermeshMtd().
virtual int cvMeshObject::WriteMesh (char * filename, int smsver) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_WriteMeshMtd().
int cvMeshObject::WriteMeshVrml (char * filename)
Definition at line 457 of file cvMeshObject.cxx.
References closeOutputFile(), connID_, curMdlRegID_, CV_ERROR, CV_OK, fp_, getNextElement(), getNextNode(), getNextRegion(), gzprintf, initElementTraversal(), initNodeTraversal(), initRegionTraversal(), nodeX_, nodeY_, nodeZ_, numModelRegions_, and openOutputFile().
Referenced by cvMesh_WriteMeshVRMLMtd().
virtual int cvMeshObject::WriteMetisAdjacency (char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_WriteMetisAdjacencyMtd().
int cvMeshObject::WriteProphlexInputDeck (char * filename)
Definition at line 311 of file cvMeshObject.cxx.
References closeOutputFile(), connID_, curElemID_, curMdlRegID_, CV_ERROR, CV_OK, fp_, getNextElement(), getNextNode(), getNextRegion(), gzprintf, initElementTraversal(), initNodeTraversal(), initRegionTraversal(), nodeID_, nodeX_, nodeY_, nodeZ_, numModelRegions_, openOutputFile(), quadElem_, and regionID_.
Referenced by cvMesh_WritePROPHLEXMtd().
int cvMeshObject::WriteSpectrumSolverElements (char * filename)
Definition at line 133 of file cvMeshObject.cxx.
References closeOutputFile(), connID_, curElemID_, CV_ERROR, CV_OK, fp_, getNextElement(), getNextRegion(), gzprintf, initElementTraversal(), initRegionTraversal(), and openOutputFile().
Referenced by cvMesh_WriteSpectrumSolverElementsMtd().
int cvMeshObject::WriteSpectrumSolverNodes (char * filename)
Definition at line 159 of file cvMeshObject.cxx.
References closeOutputFile(), CV_ERROR, CV_OK, fp_, getNextNode(), gzprintf, initNodeTraversal(), nodeID_, nodeX_, nodeY_, nodeZ_, and openOutputFile().
Referenced by cvMesh_WriteSpectrumSolverNodesMtd().
int cvMeshObject::WriteSpectrumVisData (char * filename)
Definition at line 183 of file cvMeshObject.cxx.
References closeOutputFile(), CV_ERROR, CV_OK, fp_, getNextNode(), gzprintf, initNodeTraversal(), numLinearNodes_, and openOutputFile().
Referenced by cvMesh_WriteSpectrumVisMtd().
int cvMeshObject::WriteSpectrumVisMesh (char * filename)
Definition at line 246 of file cvMeshObject.cxx.
References closeOutputFile(), connID_, curElemID_, CV_ERROR, CV_OK, fp_, getNextElement(), getNextNode(), getNextRegion(), gzprintf, initElementTraversal(), initNodeTraversal(), initRegionTraversal(), nodeID_, nodeX_, nodeY_, nodeZ_, numElements_, numLinearNodes_, and openOutputFile().
Referenced by cvMesh_WriteSpectrumVisMtd().
virtual int cvMeshObject::WriteStats (char * filename) pure virtual
Implemented in cvTetGenMeshObject, and cvMeshSimMeshObject.
Referenced by cvMesh_WriteStatsMtd().
int cvMeshObject::WriteSurfaceMeshOogl (char * filename)
Definition at line 682 of file cvMeshObject.cxx.
References closeOutputFile(), connID_, curElemNe_, CV_ERROR, CV_OK, fp_, getNeighborMdlRegIds(), getNextElement(), getNextNode(), getNextRegion(), gzprintf, initElementTraversal(), initNodeTraversal(), initRegionTraversal(), nodeX_, nodeY_, nodeZ_, numModelRegions_, openOutputFile(), and outputOoglFaceNodes().
Referenced by cvMesh_WriteSurfaceMeshOOGLMtd().
int cvMeshObject::WriteSurfaceMeshVrml (char * filename)
Definition at line 543 of file cvMeshObject.cxx.
References closeOutputFile(), connID_, curElemNe_, curMdlRegID_, CV_ERROR, CV_OK, fp_, getNeighborMdlRegIds(), getNextElement(), getNextNode(), getNextRegion(), gzprintf, initElementTraversal(), initNodeTraversal(), initRegionTraversal(), nodeX_, nodeY_, nodeZ_, numModelRegions_, and openOutputFile().
Referenced by cvMesh_WriteSurfaceMeshVRMLMtd().
Member Data Documentation
int cvMeshObject::connID_[30] protected
Definition at line 208 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::GetElementFacesOnModelFace(), cvMeshSimMeshObject::GetElementsInModelRegion(), cvMeshSimMeshObject::getNextElement(), cvMeshSimMeshObject::GetUnstructuredGrid(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverElements(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
int cvMeshObject::curElemID_ protected
Definition at line 207 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::GetElementFacesOnModelFace(), cvMeshSimMeshObject::GetElementsInModelRegion(), cvMeshSimMeshObject::getNextElement(), cvMeshSimMeshObject::GetUnstructuredGrid(), cvMeshSimMeshObject::OutputExteriorElementFaces(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteProphlexInputDeck(), WriteSpectrumSolverElements(), and WriteSpectrumVisMesh().
int cvMeshObject::curElemNe_[4][2] protected
Definition at line 209 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::GetExteriorElementFacesOnRegion(), cvMeshSimMeshObject::getNeighborMdlRegIds(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
int cvMeshObject::curMdlRegID_ protected
Definition at line 212 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::GetElementsInModelRegion(), cvMeshSimMeshObject::GetExteriorElementFacesOnRegion(), cvMeshSimMeshObject::getNextElement(), cvMeshSimMeshObject::getNextRegion(), cvMeshSimMeshObject::GetUnstructuredGrid(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), and WriteSurfaceMeshVrml().
FILE* cvMeshObject::fp_ protected
Definition at line 215 of file cvMeshObject.h.
Referenced by closeOutputFile(), cvMeshSimMeshObject::GetElementFacesOnModelFace(), cvMeshSimMeshObject::GetElementNodesOnModelFace(), cvMeshSimMeshObject::GetElementsInModelRegion(), openOutputFile(), cvMeshSimMeshObject::OutputExteriorElementFaces(), outputOoglFaceNodes(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), cvMeshSimMeshObject::WriteMetisAdjacency(), cvTetGenMeshObject::WriteMetisAdjacency(), WriteProphlexInputDeck(), WriteSpectrumSolverElements(), WriteSpectrumSolverNodes(), WriteSpectrumVisData(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
cvMeshObject::KernelType cvMeshObject::mesh_kernel_ protected
Definition at line 194 of file cvMeshObject.h.
Referenced by GetMeshKernel().
int cvMeshObject::meshloaded_ protected
Definition at line 196 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::cvMeshSimMeshObject(), cvTetGenMeshObject::cvTetGenMeshObject(), GetMeshLoaded(), cvMeshSimMeshObject::InitTraversal(), cvMeshSimMeshObject::NewMesh(), cvTetGenMeshObject::NewMesh(), and cvMeshSimMeshObject::Update().
int cvMeshObject::nodeID_
Definition at line 188 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::GetFacePolyData(), cvMeshSimMeshObject::getNextNode(), cvMeshSimMeshObject::GetNodeCoords(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteProphlexInputDeck(), WriteSpectrumSolverNodes(), and WriteSpectrumVisMesh().
double cvMeshObject::nodeX_
Definition at line 189 of file cvMeshObject.h.
Referenced by cvMesh_GetNodeCoordsMtd(), cvMeshSimMeshObject::GetFacePolyData(), cvMeshSimMeshObject::getNextNode(), cvMeshSimMeshObject::GetNodeCoords(), outputOoglFaceNodes(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverNodes(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
double cvMeshObject::nodeY_
Definition at line 190 of file cvMeshObject.h.
Referenced by cvMesh_GetNodeCoordsMtd(), cvMeshSimMeshObject::GetFacePolyData(), cvMeshSimMeshObject::getNextNode(), cvMeshSimMeshObject::GetNodeCoords(), outputOoglFaceNodes(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverNodes(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
double cvMeshObject::nodeZ_
Definition at line 191 of file cvMeshObject.h.
Referenced by cvMesh_GetNodeCoordsMtd(), cvMeshSimMeshObject::GetFacePolyData(), cvMeshSimMeshObject::getNextNode(), cvMeshSimMeshObject::GetNodeCoords(), outputOoglFaceNodes(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSpectrumSolverNodes(), WriteSpectrumVisMesh(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
int cvMeshObject::numElements_ protected
Definition at line 201 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::GetElementConnectivity(), cvMeshSimMeshObject::getNextElement(), cvMeshSimMeshObject::InitTraversal(), and WriteSpectrumVisMesh().
int cvMeshObject::numLinearNodes_ protected
Definition at line 199 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::getNextNode(), cvMeshSimMeshObject::InitTraversal(), WriteSpectrumVisData(), and WriteSpectrumVisMesh().
int cvMeshObject::numModelRegions_ protected
Definition at line 203 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::getNeighborMdlRegIds(), cvMeshSimMeshObject::getNextRegion(), cvMeshSimMeshObject::InitTraversal(), cvMeshSimMeshObject::Print(), WriteAbaqusInputDeck(), WriteMeshVrml(), WriteProphlexInputDeck(), WriteSurfaceMeshOogl(), and WriteSurfaceMeshVrml().
int cvMeshObject::numNodes_ protected
Definition at line 200 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::GenerateQuadraticElements(), cvMeshSimMeshObject::GetElementNodesOnModelFace(), cvMeshSimMeshObject::getNextNode(), and cvMeshSimMeshObject::InitTraversal().
int cvMeshObject::quadElem_ protected
Definition at line 197 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::cvMeshSimMeshObject(), cvMeshSimMeshObject::FindNodesOnElementFace(), cvMeshSimMeshObject::GenerateQuadraticElements(), cvMeshSimMeshObject::GetElementConnectivity(), cvMeshSimMeshObject::GetElementFacesOnModelFace(), cvMeshSimMeshObject::GetElementsInModelRegion(), GetElementType(), cvMeshSimMeshObject::getNextElement(), cvMeshSimMeshObject::getNextNode(), cvMeshSimMeshObject::GetNodeCoords(), cvMeshSimMeshObject::Print(), WriteAbaqusInputDeck(), WriteHypermeshAscii(), and WriteProphlexInputDeck().
int* cvMeshObject::regionID_ protected
Definition at line 204 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::getNextRegion(), cvMeshSimMeshObject::InitTraversal(), cvMeshSimMeshObject::Print(), WriteAbaqusInputDeck(), WriteProphlexInputDeck(), and cvMeshSimMeshObject::~cvMeshSimMeshObject().
SolidModel_KernelT cvMeshObject::solidmodeling_kernel_ protected
Definition at line 195 of file cvMeshObject.h.
Referenced by cvMeshSimMeshObject::cvMeshSimMeshObject(), cvTetGenMeshObject::cvTetGenMeshObject(), cvMeshSimMeshObject::GetElementsInModelRegion(), cvMeshSimMeshObject::GetExteriorElementFacesOnRegion(), cvMeshSimMeshObject::getIdentForFaceId(), cvMeshSimMeshObject::GetModelFaceInfo(), GetSolidModelKernel(), cvMeshSimMeshObject::LoadModel(), cvMeshSimMeshObject::MapIDtoPID(), and SetSolidModelKernel().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/MeshObject/cvMeshObject.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/MeshObject/cvMeshObject.cxx