simvascular: cvFactoryRegistrar Class Reference
cvFactoryRegistrar Class Reference
#include <cvFactoryRegistrar.h>
Public Member Functions
cvFactoryRegistrar ()
FactoryMethodPtr GetFactoryMethodPtr (int factory_type)
void SetFactoryMethodPtr (int factory_type, FactoryMethodPtr factory_ptr)
void * UseFactoryMethod (int factory_type)
Protected Attributes
FactoryMethodPtr factoryMethodPtrs [CV_MAX_FACTORY_METHOD_PTRS]
Detailed Description
Definition at line 39 of file cvFactoryRegistrar.h.
Constructor & Destructor Documentation
cvFactoryRegistrar::cvFactoryRegistrar ()
Definition at line 39 of file cvFactoryRegistrar.cxx.
References CV_MAX_FACTORY_METHOD_PTRS, factoryMethodPtrs, and NULL.
Member Function Documentation
FactoryMethodPtr cvFactoryRegistrar::GetFactoryMethodPtr (int factory_type)
Definition at line 45 of file cvFactoryRegistrar.cxx.
References CV_MAX_FACTORY_METHOD_PTRS, and factoryMethodPtrs.
Referenced by PolyDataSolid_RegistrarsListCmd(), and Solid_RegistrarsListCmd().
void cvFactoryRegistrar::SetFactoryMethodPtr (int factory_type, FactoryMethodPtr factory_ptr)
Definition at line 52 of file cvFactoryRegistrar.cxx.
References CV_MAX_FACTORY_METHOD_PTRS, and factoryMethodPtrs.
Referenced by Meshsimdiscretesolid_Init(), Parasolidsolid_Init(), and PolyDataSolid_Init().
void * cvFactoryRegistrar::UseFactoryMethod (int factory_type)
Definition at line 58 of file cvFactoryRegistrar.cxx.
References CV_MAX_FACTORY_METHOD_PTRS, and factoryMethodPtrs.
Referenced by cvSolidModel::DefaultInstantiateSolidModel().
Member Data Documentation
FactoryMethodPtr cvFactoryRegistrar::factoryMethodPtrs[CV_MAX_FACTORY_METHOD_PTRS] protected
Definition at line 51 of file cvFactoryRegistrar.h.
Referenced by cvFactoryRegistrar(), GetFactoryMethodPtr(), SetFactoryMethodPtr(), and UseFactoryMethod().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvFactoryRegistrar.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvFactoryRegistrar.cxx