simvascular: cvLevelSetVelocitySmooth Class Reference
cvLevelSetVelocitySmooth Class Reference
#include <cvLevelSetVelocitySmooth.h>
Public Member Functions
cvLevelSetVelocitySmooth ()
~cvLevelSetVelocitySmooth ()
int SetKts (double upper_kt, double lower_kt)
int GetKts (double *upper_kt, double *lower_kt)
int Set3DKType (char *kt_name)
int Set3DKType (cvLevelSetVelocitySmooth3DKT kt)
int Get3DKType (cvLevelSetVelocitySmooth3DKT *kt)
int Valid ()
int StopCondition ()
int Evaluate (double pos[], double *f0, double *f1, double v[], int *forceFlag, double toDot[])
int GetMemoryUsage ()
Public Member Functions inherited from cvLevelSetVelocity
cvLevelSetVelocity ()
virtual ~cvLevelSetVelocity ()
int LinkLevelSet (cvLevelSet *ls)
int UnlinkLevelSet ()
int GetLevelSet (cvLevelSet **ls)
int UpdateTolerance ()
void SetStopV (double d)
double GetStopV ()
Private Attributes
double upper_kt_
double lower_kt_
int ktsValid_
cvLevelSetVelocitySmooth3DKT ktype_
Additional Inherited Members
Public Attributes inherited from cvLevelSetVelocity
char tclName_ [CV_STRLEN]
Protected Attributes inherited from cvLevelSetVelocity
cvLevelSet * ls_
double tol_
double stopV_
Detailed Description
Definition at line 46 of file cvLevelSetVelocitySmooth.h.
Constructor & Destructor Documentation
cvLevelSetVelocitySmooth::cvLevelSetVelocitySmooth ()
Definition at line 46 of file cvLevelSetVelocitySmooth.cxx.
References ktsValid_, ktype_, and VS_Mean_K.
cvLevelSetVelocitySmooth::~cvLevelSetVelocitySmooth ()
Definition at line 57 of file cvLevelSetVelocitySmooth.cxx.
Member Function Documentation
int cvLevelSetVelocitySmooth::Evaluate (double pos[], double * f0, double * f1, double v[], int * forceFlag, double toDot[]) virtual
Implements cvLevelSetVelocity.
Definition at line 162 of file cvLevelSetVelocitySmooth.cxx.
References Compute3dks(), CV_ERROR, CV_OK, cvLevelSetStructuredGrid::GetDim(), cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::InterpK(), cvLevelSetStructuredGrid::InterpKg(), cvLevelSetStructuredGrid::InterpKm(), cvLevelSetStructuredGrid::InterpN(), ktype_, lower_kt_, cvLevelSetVelocity::ls_, NULL, cvLevelSetVelocity::tol_, upper_kt_, Valid(), VS_Gaussian_K, VS_Mean_K, VS_PrincipleK1_K, and VS_PrincipleK2_K.
int cvLevelSetVelocitySmooth::Get3DKType (cvLevelSetVelocitySmooth3DKT * kt)
Definition at line 127 of file cvLevelSetVelocitySmooth.cxx.
References CV_OK, and ktype_.
Referenced by LsetVSmooth_GetConstMtd().
int cvLevelSetVelocitySmooth::GetKts (double * upper_kt, double * lower_kt)
Definition at line 83 of file cvLevelSetVelocitySmooth.cxx.
References CV_ERROR, CV_OK, ktsValid_, lower_kt_, and upper_kt_.
Referenced by LsetVSmooth_GetConstMtd().
int cvLevelSetVelocitySmooth::GetMemoryUsage () inline virtual
Implements cvLevelSetVelocity.
Definition at line 64 of file cvLevelSetVelocitySmooth.h.
int cvLevelSetVelocitySmooth::Set3DKType (char * kt_name)
Definition at line 98 of file cvLevelSetVelocitySmooth.cxx.
References KT_StrToEnum().
Referenced by LsetVSmooth_SetConstMtd().
int cvLevelSetVelocitySmooth::Set3DKType (cvLevelSetVelocitySmooth3DKT kt)
Definition at line 111 of file cvLevelSetVelocitySmooth.cxx.
References CV_ERROR, CV_OK, ktype_, and VS_Invalid_K.
int cvLevelSetVelocitySmooth::SetKts (double upper_kt, double lower_kt)
Definition at line 67 of file cvLevelSetVelocitySmooth.cxx.
References CV_ERROR, CV_OK, ktsValid_, lower_kt_, and upper_kt_.
Referenced by LsetVSmooth_SetConstMtd().
int cvLevelSetVelocitySmooth::StopCondition () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 152 of file cvLevelSetVelocitySmooth.cxx.
int cvLevelSetVelocitySmooth::Valid () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 138 of file cvLevelSetVelocitySmooth.cxx.
References ktsValid_, and cvLevelSetVelocity::Valid().
Referenced by Evaluate().
Member Data Documentation
int cvLevelSetVelocitySmooth::ktsValid_ private
Definition at line 69 of file cvLevelSetVelocitySmooth.h.
Referenced by cvLevelSetVelocitySmooth(), GetKts(), SetKts(), and Valid().
cvLevelSetVelocitySmooth3DKT cvLevelSetVelocitySmooth::ktype_ private
Definition at line 70 of file cvLevelSetVelocitySmooth.h.
Referenced by cvLevelSetVelocitySmooth(), Evaluate(), Get3DKType(), and Set3DKType().
double cvLevelSetVelocitySmooth::lower_kt_ private
Definition at line 68 of file cvLevelSetVelocitySmooth.h.
Referenced by Evaluate(), GetKts(), and SetKts().
double cvLevelSetVelocitySmooth::upper_kt_ private
Definition at line 67 of file cvLevelSetVelocitySmooth.h.
Referenced by Evaluate(), GetKts(), and SetKts().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocitySmooth.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocitySmooth.cxx