simvascular: cvLevelSetVelocityPotential Class Reference
cvLevelSetVelocityPotential Class Reference
#include <cvLevelSetVelocityPotential.h>
Public Member Functions
cvLevelSetVelocityPotential ()
~cvLevelSetVelocityPotential ()
int SetEP (double d)
double GetEP ()
int SetEK (double d)
double GetEK ()
int SetKlow (double d)
double GetKlow ()
int SetKupp (double d)
double GetKupp ()
int SetBalloonF (double b)
double GetBalloonF ()
int Valid ()
int StopCondition ()
int Evaluate (double pos[], double *f0, double *f1, double v[], int *forceFlag, double toDot[])
int GetMemoryUsage ()
Public Member Functions inherited from cvLevelSetVelocityImage
cvLevelSetVelocityImage ()
virtual ~cvLevelSetVelocityImage ()
int SetImage (Image_T *i, int closed=0)
int SetImage (char *filebase, int fileNumRange[], int imgDims[], double pixDims[], int closed=0)
int SetImage (short *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (double *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (float *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int GetImage (Image_T **i)
int GetMagGradRange (double rng[])
int GetXYMagGradRange (double rng[])
int GetZMagGradRange (double rng[])
int GetIntensityRange (double rng[])
int ClearImage ()
virtual void PostSetImageAction ()
Public Member Functions inherited from cvLevelSetVelocity
cvLevelSetVelocity ()
virtual ~cvLevelSetVelocity ()
int LinkLevelSet (cvLevelSet *ls)
int UnlinkLevelSet ()
int GetLevelSet (cvLevelSet **ls)
int UpdateTolerance ()
void SetStopV (double d)
double GetStopV ()
Private Attributes
double balloonF_
double eP_
double eK_
double Klow_
double Kupp_
Additional Inherited Members
Public Attributes inherited from cvLevelSetVelocity
char tclName_ [CV_STRLEN]
Protected Member Functions inherited from cvLevelSetVelocityImage
int GetImgSize ()
Protected Attributes inherited from cvLevelSetVelocityImage
Image_T * image_
Protected Attributes inherited from cvLevelSetVelocity
cvLevelSet * ls_
double tol_
double stopV_
Detailed Description
Definition at line 40 of file cvLevelSetVelocityPotential.h.
Constructor & Destructor Documentation
cvLevelSetVelocityPotential::cvLevelSetVelocityPotential ()
Definition at line 42 of file cvLevelSetVelocityPotential.cxx.
References balloonF_, eK_, eP_, Klow_, and Kupp_.
cvLevelSetVelocityPotential::~cvLevelSetVelocityPotential ()
Definition at line 56 of file cvLevelSetVelocityPotential.cxx.
Member Function Documentation
int cvLevelSetVelocityPotential::Evaluate (double pos[], double * f0, double * f1, double v[], int * forceFlag, double toDot[]) virtual
Implements cvLevelSetVelocity.
Definition at line 146 of file cvLevelSetVelocityPotential.cxx.
References CV_ERROR, CV_OK, Image_T::dim, eK_, eP_, GetGradIx(), GetGradIy(), GetGradIz(), cvLevelSet::GetGrid(), GetImageClosed(), GetIntensity(), cvLevelSetVelocityImage::image_, InBorder(), cvLevelSetStructuredGrid::InterpK(), cvLevelSetStructuredGrid::InterpN(), K, Klow_, Kupp_, cvLevelSetVelocity::ls_, NULL, and Valid().
double cvLevelSetVelocityPotential::GetBalloonF () inline
Definition at line 59 of file cvLevelSetVelocityPotential.h.
References balloonF_.
Referenced by LsetVPotential_GetConstMtd().
double cvLevelSetVelocityPotential::GetEK () inline
Definition at line 50 of file cvLevelSetVelocityPotential.h.
References eK_.
Referenced by LsetVPotential_GetConstMtd().
double cvLevelSetVelocityPotential::GetEP () inline
Definition at line 47 of file cvLevelSetVelocityPotential.h.
References eP_.
Referenced by LsetVPotential_GetConstMtd().
double cvLevelSetVelocityPotential::GetKlow () inline
Definition at line 53 of file cvLevelSetVelocityPotential.h.
References Klow_.
Referenced by LsetVPotential_GetConstMtd().
double cvLevelSetVelocityPotential::GetKupp () inline
Definition at line 56 of file cvLevelSetVelocityPotential.h.
References Kupp_.
Referenced by LsetVPotential_GetConstMtd().
int cvLevelSetVelocityPotential::GetMemoryUsage () virtual
Implements cvLevelSetVelocity.
Definition at line 260 of file cvLevelSetVelocityPotential.cxx.
References cvLevelSetVelocityImage::image_, and Img_GetMemoryUsage().
int cvLevelSetVelocityPotential::SetBalloonF (double b)
Definition at line 66 of file cvLevelSetVelocityPotential.cxx.
References balloonF_, and CV_OK.
int cvLevelSetVelocityPotential::SetEK (double d)
Definition at line 88 of file cvLevelSetVelocityPotential.cxx.
References CV_OK, and eK_.
Referenced by LsetVPotential_SetConstMtd().
int cvLevelSetVelocityPotential::SetEP (double d)
Definition at line 77 of file cvLevelSetVelocityPotential.cxx.
References CV_OK, and eP_.
Referenced by LsetVPotential_SetConstMtd().
int cvLevelSetVelocityPotential::SetKlow (double d)
Definition at line 99 of file cvLevelSetVelocityPotential.cxx.
References CV_OK, and Klow_.
Referenced by LsetVPotential_SetConstMtd().
int cvLevelSetVelocityPotential::SetKupp (double d)
Definition at line 110 of file cvLevelSetVelocityPotential.cxx.
References CV_OK, and Kupp_.
Referenced by LsetVPotential_SetConstMtd().
int cvLevelSetVelocityPotential::StopCondition () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 136 of file cvLevelSetVelocityPotential.cxx.
int cvLevelSetVelocityPotential::Valid () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 121 of file cvLevelSetVelocityPotential.cxx.
References cvLevelSetVelocityImage::image_, Klow_, Kupp_, NULL, and cvLevelSetVelocity::Valid().
Referenced by Evaluate().
Member Data Documentation
double cvLevelSetVelocityPotential::balloonF_ private
Definition at line 69 of file cvLevelSetVelocityPotential.h.
Referenced by cvLevelSetVelocityPotential(), GetBalloonF(), and SetBalloonF().
double cvLevelSetVelocityPotential::eK_ private
Definition at line 71 of file cvLevelSetVelocityPotential.h.
Referenced by cvLevelSetVelocityPotential(), Evaluate(), GetEK(), and SetEK().
double cvLevelSetVelocityPotential::eP_ private
Definition at line 70 of file cvLevelSetVelocityPotential.h.
Referenced by cvLevelSetVelocityPotential(), Evaluate(), GetEP(), and SetEP().
double cvLevelSetVelocityPotential::Klow_ private
Definition at line 72 of file cvLevelSetVelocityPotential.h.
Referenced by cvLevelSetVelocityPotential(), Evaluate(), GetKlow(), SetKlow(), and Valid().
double cvLevelSetVelocityPotential::Kupp_ private
Definition at line 73 of file cvLevelSetVelocityPotential.h.
Referenced by cvLevelSetVelocityPotential(), Evaluate(), GetKupp(), SetKupp(), and Valid().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityPotential.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityPotential.cxx