simvascular: vtkIntegrateAttributes Class Reference
vtkIntegrateAttributes Class Reference
#include <vtkIntegrateAttributes.h>
Classes
class vtkFieldList
Public Types
enum CommunicationIds { IntegrateAttrInfo =2000, IntegrateAttrData }
Public Member Functions
vtkTypeMacro (vtkIntegrateAttributes, vtkUnstructuredGridAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
void SetController (vtkMultiProcessController *controller)
Static Public Member Functions
static vtkIntegrateAttributes * New ()
Protected Member Functions
vtkIntegrateAttributes ()
~vtkIntegrateAttributes ()
virtual int RequestData (vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector)
virtual vtkExecutive * CreateDefaultExecutive ()
virtual int FillInputPortInformation (int, vtkInformation *)
int CompareIntegrationDimension (vtkDataSet *output, int dim)
void IntegratePolyLine (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdList *cellPtIds)
void IntegratePolygon (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdList *cellPtIds)
void IntegrateTriangleStrip (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdList *cellPtIds)
void IntegrateTriangle (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdType pt1Id, vtkIdType pt2Id, vtkIdType pt3Id)
void IntegrateTetrahedron (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdType pt1Id, vtkIdType pt2Id, vtkIdType pt3Id, vtkIdType pt4Id)
void IntegratePixel (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdList *cellPtIds)
void IntegrateVoxel (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdList *cellPtIds)
void IntegrateGeneral1DCell (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdList *cellPtIds)
void IntegrateGeneral2DCell (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdList *cellPtIds)
void IntegrateGeneral3DCell (vtkDataSet *input, vtkUnstructuredGrid *output, vtkIdType cellId, vtkIdList *cellPtIds)
void IntegrateSatelliteData (vtkDataSetAttributes *inda, vtkDataSetAttributes *outda)
void ZeroAttributes (vtkDataSetAttributes *outda)
Protected Attributes
vtkMultiProcessController * Controller
int IntegrationDimension
double Sum
double SumCenter [3]
Private Member Functions
vtkIntegrateAttributes (const vtkIntegrateAttributes &)
void operator= (const vtkIntegrateAttributes &)
void AllocateAttributes (vtkFieldList &fieldList, vtkDataSetAttributes *outda)
void ExecuteBlock (vtkDataSet *input, vtkUnstructuredGrid *output, int fieldset_index, vtkFieldList &pdList, vtkFieldList &cdList)
void IntegrateData1 (vtkDataSetAttributes *inda, vtkDataSetAttributes *outda, vtkIdType pt1Id, double k, vtkFieldList &fieldlist, int fieldlist_index)
void IntegrateData2 (vtkDataSetAttributes *inda, vtkDataSetAttributes *outda, vtkIdType pt1Id, vtkIdType pt2Id, double k, vtkFieldList &fieldlist, int fieldlist_index)
void IntegrateData3 (vtkDataSetAttributes *inda, vtkDataSetAttributes *outda, vtkIdType pt1Id, vtkIdType pt2Id, vtkIdType pt3Id, double k, vtkFieldList &fieldlist, int fieldlist_index)
void IntegrateData4 (vtkDataSetAttributes *inda, vtkDataSetAttributes *outda, vtkIdType pt1Id, vtkIdType pt2Id, vtkIdType pt3Id, vtkIdType pt4Id, double k, vtkFieldList &fieldlist, int fieldlist_index)
Private Attributes
vtkFieldList * CellFieldList
vtkFieldList * PointFieldList
int FieldListIndex
Detailed Description
Definition at line 37 of file vtkIntegrateAttributes.h.
Member Enumeration Documentation
enum vtkIntegrateAttributes::CommunicationIds
Enumerator
IntegrateAttrInfo
IntegrateAttrData
Definition at line 147 of file vtkIntegrateAttributes.h.
Constructor & Destructor Documentation
vtkIntegrateAttributes::vtkIntegrateAttributes () protected
Definition at line 51 of file vtkIntegrateAttributes.cxx.
References CellFieldList, Controller, FieldListIndex, IntegrationDimension, PointFieldList, SetController(), Sum, and SumCenter.
vtkIntegrateAttributes::~vtkIntegrateAttributes () protected
Definition at line 68 of file vtkIntegrateAttributes.cxx.
References Controller.
vtkIntegrateAttributes::vtkIntegrateAttributes (const vtkIntegrateAttributes &) private
Member Function Documentation
void vtkIntegrateAttributes::AllocateAttributes (vtkIntegrateAttributes::vtkFieldList & fieldList, vtkDataSetAttributes * outda) private
Definition at line 575 of file vtkIntegrateAttributes.cxx.
References vtkIntegrateAttributes::vtkFieldList::SetFieldIndex().
Referenced by RequestData().
int vtkIntegrateAttributes::CompareIntegrationDimension (vtkDataSet * output, int dim) protected
Definition at line 119 of file vtkIntegrateAttributes.cxx.
References IntegrationDimension, Sum, SumCenter, and ZeroAttributes().
Referenced by ExecuteBlock(), and RequestData().
vtkExecutive * vtkIntegrateAttributes::CreateDefaultExecutive () protected virtual
Definition at line 101 of file vtkIntegrateAttributes.cxx.
void vtkIntegrateAttributes::ExecuteBlock (vtkDataSet * input, vtkUnstructuredGrid * output, int fieldset_index, vtkIntegrateAttributes::vtkFieldList & pdList, vtkIntegrateAttributes::vtkFieldList & cdList) private
Definition at line 137 of file vtkIntegrateAttributes.cxx.
References CellFieldList, CompareIntegrationDimension(), FieldListIndex, IntegrateGeneral1DCell(), IntegrateGeneral2DCell(), IntegrateGeneral3DCell(), IntegratePixel(), IntegratePolygon(), IntegratePolyLine(), IntegrateTetrahedron(), IntegrateTriangle(), IntegrateTriangleStrip(), IntegrateVoxel(), NULL, and PointFieldList.
Referenced by RequestData().
int vtkIntegrateAttributes::FillInputPortInformation (int port, vtkInformation * info) protected virtual
Definition at line 107 of file vtkIntegrateAttributes.cxx.
void vtkIntegrateAttributes::IntegrateData1 (vtkDataSetAttributes * inda, vtkDataSetAttributes * outda, vtkIdType pt1Id, double k, vtkIntegrateAttributes::vtkFieldList & fieldList, int fieldlist_index) private
Definition at line 620 of file vtkIntegrateAttributes.cxx.
Referenced by IntegrateGeneral1DCell(), IntegratePixel(), IntegratePolyLine(), IntegrateTetrahedron(), IntegrateTriangle(), and IntegrateVoxel().
void vtkIntegrateAttributes::IntegrateData2 (vtkDataSetAttributes * inda, vtkDataSetAttributes * outda, vtkIdType pt1Id, vtkIdType pt2Id, double k, vtkIntegrateAttributes::vtkFieldList & fieldList, int fieldlist_index) private
Definition at line 651 of file vtkIntegrateAttributes.cxx.
Referenced by IntegrateGeneral1DCell(), and IntegratePolyLine().
void vtkIntegrateAttributes::IntegrateData3 (vtkDataSetAttributes * inda, vtkDataSetAttributes * outda, vtkIdType pt1Id, vtkIdType pt2Id, vtkIdType pt3Id, double k, vtkIntegrateAttributes::vtkFieldList & fieldList, int fieldlist_index) private
Definition at line 684 of file vtkIntegrateAttributes.cxx.
Referenced by IntegrateTriangle().
void vtkIntegrateAttributes::IntegrateData4 (vtkDataSetAttributes * inda, vtkDataSetAttributes * outda, vtkIdType pt1Id, vtkIdType pt2Id, vtkIdType pt3Id, vtkIdType pt4Id, double k, vtkIntegrateAttributes::vtkFieldList & fieldList, int fieldlist_index) private
Definition at line 720 of file vtkIntegrateAttributes.cxx.
Referenced by IntegratePixel(), IntegrateTetrahedron(), and IntegrateVoxel().
void vtkIntegrateAttributes::IntegrateGeneral1DCell (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdList * cellPtIds) protected
Definition at line 838 of file vtkIntegrateAttributes.cxx.
References CellFieldList, FieldListIndex, IntegrateData1(), IntegrateData2(), PointFieldList, Sum, and SumCenter.
Referenced by ExecuteBlock().
void vtkIntegrateAttributes::IntegrateGeneral2DCell (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdList * cellPtIds) protected
Definition at line 1029 of file vtkIntegrateAttributes.cxx.
References IntegrateTriangle().
Referenced by ExecuteBlock().
void vtkIntegrateAttributes::IntegrateGeneral3DCell (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdList * cellPtIds) protected
Definition at line 1181 of file vtkIntegrateAttributes.cxx.
References IntegrateTetrahedron().
Referenced by ExecuteBlock().
void vtkIntegrateAttributes::IntegratePixel (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdList * cellPtIds) protected
Definition at line 930 of file vtkIntegrateAttributes.cxx.
References CellFieldList, FieldListIndex, IntegrateData1(), IntegrateData4(), PointFieldList, Sum, and SumCenter.
Referenced by ExecuteBlock().
void vtkIntegrateAttributes::IntegratePolygon (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdList * cellPtIds) protected
Definition at line 910 of file vtkIntegrateAttributes.cxx.
References IntegrateTriangle().
Referenced by ExecuteBlock().
void vtkIntegrateAttributes::IntegratePolyLine (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdList * cellPtIds) protected
Definition at line 795 of file vtkIntegrateAttributes.cxx.
References CellFieldList, FieldListIndex, IntegrateData1(), IntegrateData2(), PointFieldList, Sum, and SumCenter.
Referenced by ExecuteBlock().
void vtkIntegrateAttributes::IntegrateSatelliteData (vtkDataSetAttributes * inda, vtkDataSetAttributes * outda) protected
Definition at line 758 of file vtkIntegrateAttributes.cxx.
Referenced by RequestData().
void vtkIntegrateAttributes::IntegrateTetrahedron (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdType pt1Id, vtkIdType pt2Id, vtkIdType pt3Id, vtkIdType pt4Id) protected
Definition at line 1059 of file vtkIntegrateAttributes.cxx.
References c, CellFieldList, Cross(), Dot(), FieldListIndex, IntegrateData1(), IntegrateData4(), PointFieldList, Sum, and SumCenter.
Referenced by ExecuteBlock(), and IntegrateGeneral3DCell().
void vtkIntegrateAttributes::IntegrateTriangle (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdType pt1Id, vtkIdType pt2Id, vtkIdType pt3Id) protected
Definition at line 976 of file vtkIntegrateAttributes.cxx.
References CellFieldList, Cross(), MyUt::cross(), FieldListIndex, IntegrateData1(), IntegrateData3(), PointFieldList, Sum, and SumCenter.
Referenced by ExecuteBlock(), IntegrateGeneral2DCell(), IntegratePolygon(), and IntegrateTriangleStrip().
void vtkIntegrateAttributes::IntegrateTriangleStrip (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdList * cellPtIds) protected
Definition at line 890 of file vtkIntegrateAttributes.cxx.
References IntegrateTriangle().
Referenced by ExecuteBlock().
void vtkIntegrateAttributes::IntegrateVoxel (vtkDataSet * input, vtkUnstructuredGrid * output, vtkIdType cellId, vtkIdList * cellPtIds) protected
Definition at line 1109 of file vtkIntegrateAttributes.cxx.
References CellFieldList, FieldListIndex, IntegrateData1(), IntegrateData4(), PointFieldList, Sum, and SumCenter.
Referenced by ExecuteBlock().
static vtkIntegrateAttributes* vtkIntegrateAttributes::New () static
Referenced by vtkIntegrateFlowThroughSurface::RequestData(), and sys_geom_IntegrateSurface2().
void vtkIntegrateAttributes::operator= (const vtkIntegrateAttributes &) private
void vtkIntegrateAttributes::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 1214 of file vtkIntegrateAttributes.cxx.
References IntegrationDimension.
int vtkIntegrateAttributes::RequestData (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected virtual
Definition at line 320 of file vtkIntegrateAttributes.cxx.
References AllocateAttributes(), CompareIntegrationDimension(), Controller, ExecuteBlock(), input(), IntegrateAttrData, IntegrateAttrInfo, IntegrateSatelliteData(), IntegrationDimension, iter, Sum, and SumCenter.
void vtkIntegrateAttributes::SetController (vtkMultiProcessController * controller)
Referenced by vtkIntegrateAttributes().
vtkIntegrateAttributes::vtkTypeMacro (vtkIntegrateAttributes , vtkUnstructuredGridAlgorithm)
void vtkIntegrateAttributes::ZeroAttributes (vtkDataSetAttributes * outda) protected
Definition at line 604 of file vtkIntegrateAttributes.cxx.
Referenced by CompareIntegrationDimension().
Member Data Documentation
vtkFieldList* vtkIntegrateAttributes::CellFieldList private
Definition at line 115 of file vtkIntegrateAttributes.h.
Referenced by ExecuteBlock(), IntegrateGeneral1DCell(), IntegratePixel(), IntegratePolyLine(), IntegrateTetrahedron(), IntegrateTriangle(), IntegrateVoxel(), and vtkIntegrateAttributes().
vtkMultiProcessController* vtkIntegrateAttributes::Controller protected
Definition at line 51 of file vtkIntegrateAttributes.h.
Referenced by RequestData(), vtkIntegrateAttributes(), and ~vtkIntegrateAttributes().
int vtkIntegrateAttributes::FieldListIndex private
Definition at line 118 of file vtkIntegrateAttributes.h.
Referenced by ExecuteBlock(), IntegrateGeneral1DCell(), IntegratePixel(), IntegratePolyLine(), IntegrateTetrahedron(), IntegrateTriangle(), IntegrateVoxel(), and vtkIntegrateAttributes().
int vtkIntegrateAttributes::IntegrationDimension protected
Definition at line 64 of file vtkIntegrateAttributes.h.
Referenced by CompareIntegrationDimension(), PrintSelf(), RequestData(), and vtkIntegrateAttributes().
vtkFieldList* vtkIntegrateAttributes::PointFieldList private
Definition at line 117 of file vtkIntegrateAttributes.h.
Referenced by ExecuteBlock(), IntegrateGeneral1DCell(), IntegratePixel(), IntegratePolyLine(), IntegrateTetrahedron(), IntegrateTriangle(), IntegrateVoxel(), and vtkIntegrateAttributes().
double vtkIntegrateAttributes::Sum protected
Definition at line 67 of file vtkIntegrateAttributes.h.
Referenced by CompareIntegrationDimension(), IntegrateGeneral1DCell(), IntegratePixel(), IntegratePolyLine(), IntegrateTetrahedron(), IntegrateTriangle(), IntegrateVoxel(), RequestData(), and vtkIntegrateAttributes().
double vtkIntegrateAttributes::SumCenter[3] protected
Definition at line 69 of file vtkIntegrateAttributes.h.
Referenced by CompareIntegrationDimension(), IntegrateGeneral1DCell(), IntegratePixel(), IntegratePolyLine(), IntegrateTetrahedron(), IntegrateTriangle(), IntegrateVoxel(), RequestData(), and vtkIntegrateAttributes().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkIntegrateAttributes.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkIntegrateAttributes.cxx