simvascular: cvParasolidSolidModel Class Reference
cvParasolidSolidModel Class Reference
#include <cvParasolidSolidModel.h>
Public Member Functions
cvParasolidSolidModel ()
cvParasolidSolidModel (const cvParasolidSolidModel &sm)
~cvParasolidSolidModel ()
void Clear ()
void Print () const
void Check (int *nerr) const
cvSolidModel * Copy () const
int Copy (const cvSolidModel &src)
int MakePoly2d (cvPolyData *pd)
int MakePoly2dPts (cvPolyData *pd)
int MakeCircle (double radius, double ctr[])
int MakeEllipse (double xr, double yr, double ctr[])
int MakeBox2d (double dims[], double ctr[])
int MakeBox3d (double dims[], double ctr[])
int MakeSphere (double r, double ctr[])
int MakeCylinder (double r, double length, double ctr[], double axis[])
int MakeTorus (double rmaj, double rmin, double ctr[], double axis[])
int MakeTruncatedCone (double pt[], double dir[], double r1, double r2)
int SetPoly3dFacetMethod (SolidModel_FacetT code)
int MakePoly3dSolid (cvPolyData *pd, double angle)
int MakePoly3dSurface (cvPolyData *pd)
int ExtrudeZ (cvSolidModel *in, double dist)
int Extrude (cvSolidModel *in, double **dist)
int MakeInterpCurveLoop (cvPolyData *pd, int closed)
int MakeApproxCurveLoop (cvPolyData *pd, double tol, int closed)
int MakeLoftedSurf (cvSolidModel **curves, int numCurves, char *name)
int CapSurfToSolid (cvSolidModel *surf)
int Intersect (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st)
int Union (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st)
int Subtract (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st)
int Translate (double vec[], int ndim)
int Rotate (double axis[], int ndim, double rad)
int Scale (double factor)
int Reflect (double pos[], double nrm[])
int Apply4x4 (double mat[][4])
cvPolyData * GetPolyData (int useMaxDist, double max_dist) const
cvPolyData * GetDiscontinuities () const
cvSolidModel * GetAxialIsoparametricCurve (double p) const
int FindExtent (double *extent)
int FindCentroid (double *centroid)
int GetTopoDim (int *tdim) const
int GetSpatialDim (int *sdim) const
int ClassifyPt (double pt[], int v, int *ans) const
int ClassifyPt (double x, double y, int v, int *ans) const
int ClassifyPt (double x, double y, double z, int v, int *ans) const
int DistanceAlongVec (double start[], double end[], int v, double *ans) const
int Distance (double pos[], double upperLimit, double *dist)
int GetFaceNormal (int faceid, double u, double v, double normal[])
int GetBoundaryFaces (double angle)
int GetFaceIds (int *numFaces, int **faceIds)
cvPolyData * GetFacePolyData (int faceid, int useMaxDist, double max_dist) const
int GetFaceAttribute (char *attr, int faceid, char **value)
int SetFaceAttribute (char *attr, int faceid, char *value)
int GetRegionIds (int *numRegions, int **regionIds)
int GetRegionAttribute (char *attr, int regionid, char **value)
int SetRegionAttribute (char *attr, int regionid, char *value)
int DeleteRegion (int regionid)
int ReadNative (char *filename)
int WriteNative (int file_version, char *filename) const
int WriteVtkPolyData (char *filename)
int DeleteFaces (int numfaces, int *faces)
int CreateEdgeBlend (int faceA, int faceB, double radius)
int CombineFaces (int targetface, int loseface)
int RemeshFace (int numfaces, int *excludedFaces, double size)
int SetVtkPolyDataObject (vtkPolyData *newPolyData)
Public Member Functions inherited from cvSolidModel
cvSolidModel (SolidModel_KernelT t)
virtual ~cvSolidModel ()
SolidModel_KernelT GetKernelT () const
virtual int MakeEllipsoid (double r[], double ctr[])
Public Member Functions inherited from cvRepositoryData
cvRepositoryData (RepositoryDataT type)
virtual ~cvRepositoryData ()
void Lock ()
void Release ()
int NumLocks ()
RepositoryDataT GetType ()
char * GetName ()
void SetName (char *in)
int GetNumLabels ()
void GetLabelKeys (int *numKeys, char **keys[])
int IsLabelPresent (char *key)
int GetLabel (char *key, char **value)
int SetLabel (char *key, char *value)
void ClearLabel (char *key)
virtual int GetMemoryUsage ()
Private Member Functions
int ListToArray (PK_ENTITY_t **arr, int *num)
void ClearSurf ()
void MakeSurf ()
PsdSmpT SmpCode_GenericToPsd (SolidModel_SimplifyT st)
Private Attributes
cvLispList< PsdItem * > * geom_
cvLispListIterator< PsdItem * > * iter_
cvPolyData * surf_
Additional Inherited Members
Static Public Member Functions inherited from cvSolidModel
static cvSolidModel * DefaultInstantiateSolidModel (Tcl_Interp *interp=NULL)
Static Public Attributes inherited from cvSolidModel
static SolidModel_KernelT gCurrentKernel = SM_KT_PARASOLID
static cvFactoryRegistrar gRegistrar
Protected Attributes inherited from cvSolidModel
double tol_
Detailed Description
Definition at line 40 of file cvParasolidSolidModel.h.
Constructor & Destructor Documentation
cvParasolidSolidModel::cvParasolidSolidModel ()
Definition at line 47 of file cvParasolidSolidModel.cxx.
References geom_, NULL, and surf_.
Referenced by Copy(), and GetAxialIsoparametricCurve().
cvParasolidSolidModel::cvParasolidSolidModel (const cvParasolidSolidModel & sm)
Definition at line 59 of file cvParasolidSolidModel.cxx.
References Copy(), geom_, NULL, and surf_.
cvParasolidSolidModel::~cvParasolidSolidModel ()
Definition at line 72 of file cvParasolidSolidModel.cxx.
References Clear(), geom_, and NULL.
Member Function Documentation
int cvParasolidSolidModel::Apply4x4 (double mat[][4]) virtual
Implements cvSolidModel.
Definition at line 983 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_Apply4x4().
int cvParasolidSolidModel::CapSurfToSolid (cvSolidModel * surf) virtual
Reimplemented from cvSolidModel.
Definition at line 721 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, cvSolidModel::GetKernelT(), NULL, cvLispList< T >::NumInList(), PsdUtils_CapSurfToSolid(), and SM_KT_PARASOLID.
void cvParasolidSolidModel::Check (int * nerr) const virtual
Implements cvSolidModel.
Definition at line 147 of file cvParasolidSolidModel.cxx.
References geom_, NULL, and PsdUtils_CheckBodies().
int cvParasolidSolidModel::ClassifyPt (double pt[], int v, int * ans) const virtual
Implements cvSolidModel.
Definition at line 1049 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_ClassifyPt().
Referenced by ClassifyPt(), and Distance().
int cvParasolidSolidModel::ClassifyPt (double x, double y, int v, int * ans) const virtual
Implements cvSolidModel.
Definition at line 1068 of file cvParasolidSolidModel.cxx.
References ClassifyPt(), CV_ERROR, geom_, and NULL.
int cvParasolidSolidModel::ClassifyPt (double x, double y, double z, int v, int * ans) const virtual
Implements cvSolidModel.
Definition at line 1089 of file cvParasolidSolidModel.cxx.
References ClassifyPt(), CV_ERROR, geom_, and NULL.
void cvParasolidSolidModel::Clear () virtual
Implements cvSolidModel.
Definition at line 85 of file cvParasolidSolidModel.cxx.
References ClearSurf(), geom_, NULL, and PsdUtils_Delete().
Referenced by Extrude(), ExtrudeZ(), MakeBox2d(), MakeBox3d(), MakeCylinder(), MakePoly2d(), MakeSphere(), MakeTorus(), and ~cvParasolidSolidModel().
void cvParasolidSolidModel::ClearSurf () private
Definition at line 100 of file cvParasolidSolidModel.cxx.
References NULL, and surf_.
Referenced by Clear(), Extrude(), ExtrudeZ(), MakeBox2d(), MakeBox3d(), MakeCylinder(), MakePoly2d(), MakePoly2dPts(), MakePoly3dSolid(), MakePoly3dSurface(), MakeSphere(), and MakeTorus().
int cvParasolidSolidModel::CombineFaces (int targetface, int loseface) inline virtual
Implements cvSolidModel.
Definition at line 121 of file cvParasolidSolidModel.h.
References CV_ERROR.
cvSolidModel * cvParasolidSolidModel::Copy () const virtual
Implements cvSolidModel.
Definition at line 194 of file cvParasolidSolidModel.cxx.
References cvParasolidSolidModel().
Referenced by cvParasolidSolidModel().
int cvParasolidSolidModel::Copy (const cvSolidModel & src) virtual
Implements cvSolidModel.
Definition at line 205 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, cvSolidModel::GetKernelT(), NULL, PsdUtils_DeepCopy(), and SM_KT_PARASOLID.
int cvParasolidSolidModel::CreateEdgeBlend (int faceA, int faceB, double radius) virtual
Implements cvSolidModel.
Definition at line 1540 of file cvParasolidSolidModel.cxx.
References CV_ERROR, geom_, NULL, and PsdUtils_CreateEdgeBlend().
int cvParasolidSolidModel::DeleteFaces (int numfaces, int * faces) virtual
Implements cvSolidModel.
Definition at line 1522 of file cvParasolidSolidModel.cxx.
References CV_ERROR, geom_, NULL, and PsdUtils_DeleteFaces().
int cvParasolidSolidModel::DeleteRegion (int regionid) inline virtual
Implements cvSolidModel.
Definition at line 112 of file cvParasolidSolidModel.h.
References CV_ERROR.
int cvParasolidSolidModel::Distance (double pos[], double upperLimit, double * dist) virtual
Implements cvSolidModel.
Definition at line 1155 of file cvParasolidSolidModel.cxx.
References c, ClassifyPt(), CV_ERROR, CV_OK, cvPolyData::FindDistance(), MakeSurf(), and surf_.
int cvParasolidSolidModel::DistanceAlongVec (double start[], double end[], int v, double * ans) const virtual
Implements cvSolidModel.
Definition at line 1111 of file cvParasolidSolidModel.cxx.
References CV_ERROR.
int cvParasolidSolidModel::Extrude (cvSolidModel * in, double ** dist) virtual
Implements cvSolidModel.
Definition at line 507 of file cvParasolidSolidModel.cxx.
References Clear(), ClearSurf(), CV_ERROR, CV_OK, geom_, cvSolidModel::GetKernelT(), NULL, PsdUtils_Extrude(), and SM_KT_PARASOLID.
int cvParasolidSolidModel::ExtrudeZ (cvSolidModel * in, double dist) virtual
Implements cvSolidModel.
Definition at line 477 of file cvParasolidSolidModel.cxx.
References Clear(), ClearSurf(), CV_ERROR, CV_OK, geom_, cvSolidModel::GetKernelT(), NULL, PsdUtils_Extrude(), and SM_KT_PARASOLID.
int cvParasolidSolidModel::FindCentroid (double * centroid) virtual
Implements cvSolidModel.
Definition at line 1015 of file cvParasolidSolidModel.cxx.
References CV_ERROR.
int cvParasolidSolidModel::FindExtent (double * extent) virtual
Implements cvSolidModel.
Definition at line 999 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_FindExtent().
cvSolidModel * cvParasolidSolidModel::GetAxialIsoparametricCurve (double p) const virtual
Implements cvSolidModel.
Definition at line 1412 of file cvParasolidSolidModel.cxx.
References CV_OK, cvParasolidSolidModel(), geom_, NULL, and PsdUtils_GetAxialIsoparametricCurve().
int cvParasolidSolidModel::GetBoundaryFaces (double angle) inline virtual
Implements cvSolidModel.
Definition at line 104 of file cvParasolidSolidModel.h.
References CV_ERROR.
cvPolyData * cvParasolidSolidModel::GetDiscontinuities () const virtual
Implements cvSolidModel.
Definition at line 1395 of file cvParasolidSolidModel.cxx.
References geom_, NULL, and PsdUtils_GetDiscontinuities().
int cvParasolidSolidModel::GetFaceAttribute (char * attr, int faceid, char ** value) virtual
Implements cvSolidModel.
Definition at line 1471 of file cvParasolidSolidModel.cxx.
References CV_OK, geom_, NULL, and PsdUtils_GetFaceAttribute().
int cvParasolidSolidModel::GetFaceIds (int * numFaces, int ** faceIds) virtual
Implements cvSolidModel.
Definition at line 1435 of file cvParasolidSolidModel.cxx.
References CV_OK, geom_, NULL, and PsdUtils_GetFaceIds().
int cvParasolidSolidModel::GetFaceNormal (int faceid, double u, double v, double normal[]) virtual
Implements cvSolidModel.
Definition at line 1504 of file cvParasolidSolidModel.cxx.
References CV_ERROR, geom_, NULL, and PsdUtils_GetFaceNormal().
cvPolyData * cvParasolidSolidModel::GetFacePolyData (int faceid, int useMaxDist, double max_dist) const virtual
Implements cvSolidModel.
Definition at line 1310 of file cvParasolidSolidModel.cxx.
References PsdPolyGeom::conn, PsdPolyGeom::conn_size, CV_ERROR, CV_OK, geom_, NULL, PsdPolyGeom::num_polys, PsdPolyGeom::num_verts, PsdUtils_GetFacePolyData(), PsdPolyGeom::verts, and VtkUtils_NewVtkPolyData().
cvPolyData * cvParasolidSolidModel::GetPolyData (int useMaxDist, double max_dist) const virtual
Implements cvSolidModel.
Definition at line 1217 of file cvParasolidSolidModel.cxx.
References PsdPolyGeom::conn, PsdPolyGeom::conn_size, CV_ERROR, CV_OK, geom_, NULL, PsdPolyGeom::num_polys, PsdPolyGeom::num_verts, PsdUtils_GetPolyData(), PsdUtils_GetTopoDim(), PsdPolyGeom::verts, VtkUtils_NewVtkPolyData(), and VtkUtils_NewVtkPolyDataLines().
Referenced by MakeSurf().
int cvParasolidSolidModel::GetRegionAttribute (char * attr, int regionid, char ** value) inline virtual
Implements cvSolidModel.
Definition at line 110 of file cvParasolidSolidModel.h.
References CV_ERROR.
int cvParasolidSolidModel::GetRegionIds (int * numRegions, int ** regionIds) virtual
Implements cvSolidModel.
Definition at line 1453 of file cvParasolidSolidModel.cxx.
References CV_OK, geom_, NULL, and PsdUtils_GetRegionIds().
int cvParasolidSolidModel::GetSpatialDim (int * sdim) const virtual
Implements cvSolidModel.
Definition at line 1036 of file cvParasolidSolidModel.cxx.
References CV_ERROR.
int cvParasolidSolidModel::GetTopoDim (int * tdim) const virtual
Implements cvSolidModel.
Definition at line 1025 of file cvParasolidSolidModel.cxx.
References CV_OK, geom_, and PsdUtils_GetTopoDim().
int cvParasolidSolidModel::Intersect (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st) virtual
Implements cvSolidModel.
Definition at line 753 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, cvSolidModel::GetKernelT(), NULL, PsdListT, PsdSmpT_Invalid, PsdUtils_DeepCopy(), PsdUtils_Intersect(), SM_KT_PARASOLID, SmpCode_GenericToPsd(), and surf_.
int cvParasolidSolidModel::ListToArray (PK_ENTITY_t ** arr, int * num) private
Definition at line 166 of file cvParasolidSolidModel.cxx.
References CV_OK, geom_, cvLispListIterator< T >::IsDone(), PsdItem::item, cvLispListIterator< T >::Item(), iter_, cvLispListIterator< T >::Next(), NULL, cvLispList< T >::NumInList(), and PsdIterT.
int cvParasolidSolidModel::MakeApproxCurveLoop (cvPolyData * pd, double tol, int closed) virtual
Implements cvSolidModel.
Definition at line 546 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, cvLispList< T >::Front(), geom_, NULL, PsdUtils_MakeFittedBCurve(), PsdItem::src_pd, sys_geom_DeepCopy(), and sys_geom_GetOrderedPts().
int cvParasolidSolidModel::MakeBox2d (double dims[], double ctr[]) virtual
Implements cvSolidModel.
Definition at line 300 of file cvParasolidSolidModel.cxx.
References Clear(), ClearSurf(), CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_MakeBox2d().
int cvParasolidSolidModel::MakeBox3d (double dims[], double ctr[]) virtual
Implements cvSolidModel.
Definition at line 318 of file cvParasolidSolidModel.cxx.
References Clear(), ClearSurf(), CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_MakeBox3d().
int cvParasolidSolidModel::MakeCircle (double radius, double ctr[]) virtual
Implements cvSolidModel.
Definition at line 280 of file cvParasolidSolidModel.cxx.
References CV_ERROR.
int cvParasolidSolidModel::MakeCylinder (double r, double length, double ctr[], double axis[]) virtual
Implements cvSolidModel.
Definition at line 359 of file cvParasolidSolidModel.cxx.
References Clear(), ClearSurf(), CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_MakeCylinder().
int cvParasolidSolidModel::MakeEllipse (double xr, double yr, double ctr[]) virtual
Implements cvSolidModel.
Definition at line 290 of file cvParasolidSolidModel.cxx.
References CV_ERROR.
int cvParasolidSolidModel::MakeInterpCurveLoop (cvPolyData * pd, int closed) virtual
Implements cvSolidModel.
Definition at line 595 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, cvLispList< T >::Front(), geom_, NULL, PsdUtils_MakeSplinewiseBCurve(), PsdItem::src_pd, sys_geom_DeepCopy(), and sys_geom_GetOrderedPts().
int cvParasolidSolidModel::MakeLoftedSurf (cvSolidModel ** curves, int numCurves, char * name) virtual
Implements cvSolidModel.
Definition at line 647 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, cvLispList< T >::Front(), geom_, cvSolidModel::GetKernelT(), NULL, cvLispList< T >::NumInList(), PsdListT, PsdUtils_DeleteListOnly(), PsdUtils_MakeCap(), PsdUtils_MakeLoftedSurf(), SM_KT_PARASOLID, and PsdItem::src_pd.
int cvParasolidSolidModel::MakePoly2d (cvPolyData * pd) virtual
Implements cvSolidModel.
Definition at line 232 of file cvParasolidSolidModel.cxx.
References Clear(), ClearSurf(), CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_MakePoly2d().
int cvParasolidSolidModel::MakePoly2dPts (cvPolyData * pd) virtual
Implements cvSolidModel.
Definition at line 251 of file cvParasolidSolidModel.cxx.
References ClearSurf(), CV_ERROR, CV_OK, geom_, cvPolyData::GetVtkPolyData(), NULL, PsdListT, PsdUtils_MakePoly2dPts(), and VtkUtils_GetPoints().
int cvParasolidSolidModel::MakePoly3dSolid (cvPolyData * pd, double angle) virtual
Implements cvSolidModel.
Definition at line 409 of file cvParasolidSolidModel.cxx.
References cvLispList< T >::Append(), ClearSurf(), CV_ERROR, CV_OK, geom_, cvParasolidSolidFromPolyData::GetParaBodyPtr(), cvPolyData::GetVtkPolyData(), PsdItem::item, NULL, PsdListT, PsdUtils_NewItem(), and cvParasolidSolidFromPolyData::workSolid().
int cvParasolidSolidModel::MakePoly3dSurface (cvPolyData * pd) virtual
Implements cvSolidModel.
Definition at line 445 of file cvParasolidSolidModel.cxx.
References cvLispList< T >::Append(), ClearSurf(), CV_ERROR, CV_OK, geom_, cvParasolidSolidFromPolyData::GetParaBodyPtr(), cvPolyData::GetVtkPolyData(), PsdItem::item, NULL, PsdListT, PsdUtils_NewItem(), and cvParasolidSolidFromPolyData::workSurface().
int cvParasolidSolidModel::MakeSphere (double r, double ctr[]) virtual
Implements cvSolidModel.
Definition at line 336 of file cvParasolidSolidModel.cxx.
References Clear(), ClearSurf(), CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_MakeSphere().
void cvParasolidSolidModel::MakeSurf () private
Definition at line 1122 of file cvParasolidSolidModel.cxx.
References GetPolyData(), NULL, and surf_.
Referenced by Distance().
int cvParasolidSolidModel::MakeTorus (double rmaj, double rmin, double ctr[], double axis[]) virtual
Reimplemented from cvSolidModel.
Definition at line 379 of file cvParasolidSolidModel.cxx.
References Clear(), ClearSurf(), CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_MakeTorus().
int cvParasolidSolidModel::MakeTruncatedCone (double pt[], double dir[], double r1, double r2) inline virtual
Implements cvSolidModel.
Definition at line 63 of file cvParasolidSolidModel.h.
References CV_ERROR.
void cvParasolidSolidModel::Print () const virtual
Implements cvSolidModel.
Definition at line 114 of file cvParasolidSolidModel.cxx.
References c, geom_, iter, NULL, cvLispList< T >::NumInList(), and PsdIterT.
int cvParasolidSolidModel::ReadNative (char * filename) virtual
Implements cvSolidModel.
Definition at line 1174 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_ReadNative().
int cvParasolidSolidModel::Reflect (double pos[], double nrm[]) virtual
Implements cvSolidModel.
Definition at line 967 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_Reflect().
int cvParasolidSolidModel::RemeshFace (int numfaces, int * excludedFaces, double size) inline virtual
Implements cvSolidModel.
Definition at line 122 of file cvParasolidSolidModel.h.
References CV_ERROR.
int cvParasolidSolidModel::Rotate (double axis[], int ndim, double rad) virtual
Implements cvSolidModel.
Definition at line 935 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_Rotate().
int cvParasolidSolidModel::Scale (double factor) virtual
Implements cvSolidModel.
Definition at line 951 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_Scale().
int cvParasolidSolidModel::SetFaceAttribute (char * attr, int faceid, char * value) virtual
Implements cvSolidModel.
Definition at line 1488 of file cvParasolidSolidModel.cxx.
References CV_OK, geom_, NULL, and PsdUtils_SetFaceAttribute().
int cvParasolidSolidModel::SetPoly3dFacetMethod (SolidModel_FacetT code) virtual
Implements cvSolidModel.
Definition at line 399 of file cvParasolidSolidModel.cxx.
References CV_OK.
int cvParasolidSolidModel::SetRegionAttribute (char * attr, int regionid, char * value) inline virtual
Implements cvSolidModel.
Definition at line 111 of file cvParasolidSolidModel.h.
References CV_ERROR.
int cvParasolidSolidModel::SetVtkPolyDataObject (vtkPolyData * newPolyData) inline virtual
Implements cvSolidModel.
Definition at line 124 of file cvParasolidSolidModel.h.
References CV_ERROR.
PsdSmpT cvParasolidSolidModel::SmpCode_GenericToPsd (SolidModel_SimplifyT st) private
Definition at line 1135 of file cvParasolidSolidModel.cxx.
References PsdSmpT_All, PsdSmpT_Invalid, SM_Simplify_All, SM_Simplify_Invalid, and SM_Simplify_None.
Referenced by Intersect(), Subtract(), and Union().
int cvParasolidSolidModel::Subtract (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st) virtual
Implements cvSolidModel.
Definition at line 864 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, cvSolidModel::GetKernelT(), NULL, PsdListT, PsdSmpT_Invalid, PsdUtils_DeepCopy(), PsdUtils_Subtract(), SM_KT_PARASOLID, SmpCode_GenericToPsd(), and surf_.
int cvParasolidSolidModel::Translate (double vec[], int ndim) virtual
Implements cvSolidModel.
Definition at line 919 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_Translate().
int cvParasolidSolidModel::Union (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st) virtual
Implements cvSolidModel.
Definition at line 808 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, cvSolidModel::GetKernelT(), NULL, PsdListT, PsdSmpT_Invalid, PsdUtils_DeepCopy(), PsdUtils_Union(), SM_KT_PARASOLID, SmpCode_GenericToPsd(), and surf_.
int cvParasolidSolidModel::WriteNative (int file_version, char * filename) const virtual
Implements cvSolidModel.
Definition at line 1201 of file cvParasolidSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and PsdUtils_WriteNative().
int cvParasolidSolidModel::WriteVtkPolyData (char * filename) virtual
Implements cvSolidModel.
Definition at line 1191 of file cvParasolidSolidModel.cxx.
References CV_ERROR.
Member Data Documentation
cvLispList<PsdItem*>* cvParasolidSolidModel::geom_ private
Definition at line 128 of file cvParasolidSolidModel.h.
Referenced by Apply4x4(), CapSurfToSolid(), Check(), ClassifyPt(), Clear(), Copy(), CreateEdgeBlend(), cvParasolidSolidModel(), DeleteFaces(), Extrude(), ExtrudeZ(), FindExtent(), GetAxialIsoparametricCurve(), GetDiscontinuities(), GetFaceAttribute(), GetFaceIds(), GetFaceNormal(), GetFacePolyData(), GetPolyData(), GetRegionIds(), GetTopoDim(), Intersect(), ListToArray(), MakeApproxCurveLoop(), MakeBox2d(), MakeBox3d(), MakeCylinder(), MakeInterpCurveLoop(), MakeLoftedSurf(), MakePoly2d(), MakePoly2dPts(), MakePoly3dSolid(), MakePoly3dSurface(), MakeSphere(), MakeTorus(), Print(), ReadNative(), Reflect(), Rotate(), Scale(), SetFaceAttribute(), Subtract(), Translate(), Union(), WriteNative(), and ~cvParasolidSolidModel().
cvLispListIterator<PsdItem*>* cvParasolidSolidModel::iter_ private
Definition at line 129 of file cvParasolidSolidModel.h.
Referenced by ListToArray().
cvPolyData* cvParasolidSolidModel::surf_ private
Definition at line 134 of file cvParasolidSolidModel.h.
Referenced by ClearSurf(), cvParasolidSolidModel(), Distance(), Intersect(), MakeSurf(), Subtract(), and Union().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/ParasolidSolidModel/cvParasolidSolidModel.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/ParasolidSolidModel/cvParasolidSolidModel.cxx