simvascular: cvMeshSimDiscreteSolidModel Class Reference
cvMeshSimDiscreteSolidModel Class Reference
#include <cvMeshSimDiscreteSolidModel.h>
Public Member Functions
cvMeshSimDiscreteSolidModel ()
cvMeshSimDiscreteSolidModel (const cvMeshSimDiscreteSolidModel &sm)
~cvMeshSimDiscreteSolidModel ()
void Clear ()
void Print () const
void Check (int *nerr) const
cvSolidModel * Copy () const
int Copy (const cvSolidModel &src)
int MakePoly2d (cvPolyData *pd)
int MakePoly2dPts (cvPolyData *pd)
int MakeCircle (double radius, double ctr[])
int MakeEllipse (double xr, double yr, double ctr[])
int MakeBox2d (double dims[], double ctr[])
int MakeBox3d (double dims[], double ctr[])
int MakeSphere (double r, double ctr[])
int MakePoly3dSolid (cvPolyData *pd, double angle)
int MakePoly3dSurface (cvPolyData *pd)
int SetPoly3dFacetMethod (SolidModel_FacetT code)
int MakeCylinder (double r, double length, double ctr[], double axis[])
int ExtrudeZ (cvSolidModel *in, double dist)
int Extrude (cvSolidModel *in, double **dist)
int MakeTruncatedCone (double pt[], double dir[], double r1, double r2)
int MakeInterpCurveLoop (cvPolyData *pd, int closed)
int MakeApproxCurveLoop (cvPolyData *pd, double tol, int closed)
int MakeLoftedSurf (cvSolidModel **curves, int numCurves, char *name)
int Intersect (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st)
int Union (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st)
int Subtract (cvSolidModel *a, cvSolidModel *b, SolidModel_SimplifyT st)
int Translate (double vec[], int ndim)
int Rotate (double axis[], int ndim, double rad)
int Scale (double factor)
int Reflect (double pos[], double nrm[])
int Apply4x4 (double mat[][4])
int FindExtent (double *extent)
int FindCentroid (double *centroid)
int GetTopoDim (int *tdim) const
int GetSpatialDim (int *sdim) const
int ClassifyPt (double pt[], int v, int *ans) const
int ClassifyPt (double x, double y, int v, int *ans) const
int ClassifyPt (double x, double y, double z, int v, int *ans) const
int DistanceAlongVec (double start[], double end[], int v, double *ans) const
int Distance (double pos[], double upperLimit, double *dist)
int GetFaceNormal (int faceid, double u, double v, double normal[])
int GetBoundaryFaces (double angle)
int GetFaceIds (int *numFaces, int **faceIds)
cvPolyData * GetFacePolyData (int faceid, int useMaxDist, double max_dist) const
int GetFaceAttribute (char *attr, int faceid, char **value)
int SetFaceAttribute (char *attr, int faceid, char *value)
int GetRegionIds (int *numRegions, int **regionIds)
int GetRegionAttribute (char *attr, int regionid, char **value)
int SetRegionAttribute (char *attr, int regionid, char *value)
int DeleteRegion (int regionid)
int ReadNative (char *filename)
int WriteNative (int file_version, char *filename) const
int WriteVtkPolyData (char *filename)
cvPolyData * GetPolyData (int useMaxDist, double max_dist) const
cvPolyData * GetDiscontinuities () const
cvSolidModel * GetAxialIsoparametricCurve (double p) const
virtual int DeleteFaces (int numfaces, int *faces)
int CreateEdgeBlend (int faceA, int faceB, double radius)
int CombineFaces (int targetface, int loseface)
int RemeshFace (int numfaces, int *excludedFaces, double size)
int SetVtkPolyDataObject (vtkPolyData *newPolyData)
Public Member Functions inherited from cvSolidModel
cvSolidModel (SolidModel_KernelT t)
virtual ~cvSolidModel ()
SolidModel_KernelT GetKernelT () const
virtual int MakeEllipsoid (double r[], double ctr[])
virtual int MakeTorus (double rmaj, double rmin, double ctr[], double axis[])
virtual int CapSurfToSolid (cvSolidModel *surf)
Public Member Functions inherited from cvRepositoryData
cvRepositoryData (RepositoryDataT type)
virtual ~cvRepositoryData ()
void Lock ()
void Release ()
int NumLocks ()
RepositoryDataT GetType ()
char * GetName ()
void SetName (char *in)
int GetNumLabels ()
void GetLabelKeys (int *numKeys, char **keys[])
int IsLabelPresent (char *key)
int GetLabel (char *key, char **value)
int SetLabel (char *key, char *value)
void ClearLabel (char *key)
virtual int GetMemoryUsage ()
Public Attributes
pDiscreteModel geom_
Private Member Functions
int FindNodesOnElementFace (pFace face, int *nodes, double *xyz) const
Private Attributes
int quadElem_
Additional Inherited Members
Static Public Member Functions inherited from cvSolidModel
static cvSolidModel * DefaultInstantiateSolidModel (Tcl_Interp *interp=NULL)
Static Public Attributes inherited from cvSolidModel
static SolidModel_KernelT gCurrentKernel = SM_KT_PARASOLID
static cvFactoryRegistrar gRegistrar
Protected Attributes inherited from cvSolidModel
double tol_
Detailed Description
Definition at line 58 of file cvMeshSimDiscreteSolidModel.h.
Constructor & Destructor Documentation
cvMeshSimDiscreteSolidModel::cvMeshSimDiscreteSolidModel ()
Definition at line 41 of file cvMeshSimDiscreteSolidModel.cxx.
References geom_, NULL, and quadElem_.
cvMeshSimDiscreteSolidModel::cvMeshSimDiscreteSolidModel (const cvMeshSimDiscreteSolidModel & sm)
cvMeshSimDiscreteSolidModel::~cvMeshSimDiscreteSolidModel ()
Definition at line 53 of file cvMeshSimDiscreteSolidModel.cxx.
References geom_, and NULL.
Member Function Documentation
int cvMeshSimDiscreteSolidModel::Apply4x4 (double mat[][4]) inline virtual
Implements cvSolidModel.
Definition at line 103 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
void cvMeshSimDiscreteSolidModel::Check (int * nerr) const virtual
Implements cvSolidModel.
Definition at line 298 of file cvMeshSimDiscreteSolidModel.cxx.
References geom_, and NULL.
int cvMeshSimDiscreteSolidModel::ClassifyPt (double pt[], int v, int * ans) const inline virtual
Implements cvSolidModel.
Definition at line 110 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::ClassifyPt (double x, double y, int v, int * ans) const inline virtual
Implements cvSolidModel.
Definition at line 111 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::ClassifyPt (double x, double y, double z, int v, int * ans) const inline virtual
Implements cvSolidModel.
Definition at line 112 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
void cvMeshSimDiscreteSolidModel::Clear () virtual
Implements cvSolidModel.
Definition at line 67 of file cvMeshSimDiscreteSolidModel.cxx.
References geom_, and NULL.
Referenced by MakePoly3dSolid().
int cvMeshSimDiscreteSolidModel::CombineFaces (int targetface, int loseface) inline virtual
Implements cvSolidModel.
Definition at line 141 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
cvSolidModel* cvMeshSimDiscreteSolidModel::Copy () const inline virtual
Implements cvSolidModel.
Definition at line 68 of file cvMeshSimDiscreteSolidModel.h.
References NULL.
int cvMeshSimDiscreteSolidModel::Copy (const cvSolidModel & src) inline virtual
Implements cvSolidModel.
Definition at line 69 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::CreateEdgeBlend (int faceA, int faceB, double radius) inline virtual
Implements cvSolidModel.
Definition at line 140 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
virtual int cvMeshSimDiscreteSolidModel::DeleteFaces (int numfaces, int * faces) inline virtual
Implements cvSolidModel.
Definition at line 139 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::DeleteRegion (int regionid) inline virtual
Implements cvSolidModel.
Definition at line 127 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::Distance (double pos[], double upperLimit, double * dist) inline virtual
Implements cvSolidModel.
Definition at line 115 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::DistanceAlongVec (double start[], double end[], int v, double * ans) const inline virtual
Implements cvSolidModel.
Definition at line 113 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::Extrude (cvSolidModel * in, double ** dist) inline virtual
Implements cvSolidModel.
Definition at line 86 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::ExtrudeZ (cvSolidModel * in, double dist) inline virtual
Implements cvSolidModel.
Definition at line 85 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::FindCentroid (double * centroid) inline virtual
Implements cvSolidModel.
Definition at line 107 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::FindExtent (double * extent) inline virtual
Implements cvSolidModel.
Definition at line 106 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::FindNodesOnElementFace (pFace face, int * nodes, double * xyz) const private
Definition at line 134 of file cvMeshSimDiscreteSolidModel.cxx.
References MY_MESHSIM_VERTEX_ORDERING, NULL, point, and quadElem_.
Referenced by GetFacePolyData().
cvSolidModel* cvMeshSimDiscreteSolidModel::GetAxialIsoparametricCurve (double p) const inline virtual
Implements cvSolidModel.
Definition at line 136 of file cvMeshSimDiscreteSolidModel.h.
References NULL.
int cvMeshSimDiscreteSolidModel::GetBoundaryFaces (double angle) inline virtual
Implements cvSolidModel.
Definition at line 119 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
cvPolyData* cvMeshSimDiscreteSolidModel::GetDiscontinuities () const inline virtual
Implements cvSolidModel.
Definition at line 135 of file cvMeshSimDiscreteSolidModel.h.
References NULL.
int cvMeshSimDiscreteSolidModel::GetFaceAttribute (char * attr, int faceid, char ** value) inline virtual
Implements cvSolidModel.
Definition at line 122 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::GetFaceIds (int * numFaces, int ** faceIds) virtual
Implements cvSolidModel.
Definition at line 98 of file cvMeshSimDiscreteSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, NULL, and Print().
int cvMeshSimDiscreteSolidModel::GetFaceNormal (int faceid, double u, double v, double normal[]) inline virtual
Implements cvSolidModel.
Definition at line 116 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
cvPolyData * cvMeshSimDiscreteSolidModel::GetFacePolyData (int faceid, int useMaxDist, double max_dist) const virtual
Implements cvSolidModel.
Definition at line 181 of file cvMeshSimDiscreteSolidModel.cxx.
References FindNodesOnElementFace(), geom_, NULL, and sys_geom_MergePts().
cvPolyData * cvMeshSimDiscreteSolidModel::GetPolyData (int useMaxDist, double max_dist) const virtual
Implements cvSolidModel.
Definition at line 346 of file cvMeshSimDiscreteSolidModel.cxx.
References CV_OK, DiscreteUtils_GetVtkPolyData(), geom_, and NULL.
int cvMeshSimDiscreteSolidModel::GetRegionAttribute (char * attr, int regionid, char ** value) inline virtual
Implements cvSolidModel.
Definition at line 125 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::GetRegionIds (int * numRegions, int ** regionIds) inline virtual
Implements cvSolidModel.
Definition at line 124 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::GetSpatialDim (int * sdim) const inline virtual
Implements cvSolidModel.
Definition at line 109 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::GetTopoDim (int * tdim) const inline virtual
Implements cvSolidModel.
Definition at line 108 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::Intersect (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st) inline virtual
Implements cvSolidModel.
Definition at line 94 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeApproxCurveLoop (cvPolyData * pd, double tol, int closed) inline virtual
Implements cvSolidModel.
Definition at line 90 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeBox2d (double dims[], double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 76 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeBox3d (double dims[], double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 79 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeCircle (double radius, double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 74 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeCylinder (double r, double length, double ctr[], double axis[]) inline virtual
Implements cvSolidModel.
Definition at line 84 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeEllipse (double xr, double yr, double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 75 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeInterpCurveLoop (cvPolyData * pd, int closed) inline virtual
Implements cvSolidModel.
Definition at line 89 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeLoftedSurf (cvSolidModel ** curves, int numCurves, char * name) inline virtual
Implements cvSolidModel.
Definition at line 91 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakePoly2d (cvPolyData * pd) inline virtual
Implements cvSolidModel.
Definition at line 72 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakePoly2dPts (cvPolyData * pd) inline virtual
Implements cvSolidModel.
Definition at line 73 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakePoly3dSolid (cvPolyData * pd, double angle) virtual
Implements cvSolidModel.
Definition at line 366 of file cvMeshSimDiscreteSolidModel.cxx.
References Clear(), CV_ERROR, CV_OK, DiscreteUtils_MakePoly3dSolidVtk(), geom_, cvPolyData::GetVtkPolyData(), and NULL.
int cvMeshSimDiscreteSolidModel::MakePoly3dSurface (cvPolyData * pd) inline virtual
Implements cvSolidModel.
Definition at line 82 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeSphere (double r, double ctr[]) inline virtual
Implements cvSolidModel.
Definition at line 80 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::MakeTruncatedCone (double pt[], double dir[], double r1, double r2) inline virtual
Implements cvSolidModel.
Definition at line 87 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
void cvMeshSimDiscreteSolidModel::Print () const virtual
Implements cvSolidModel.
Definition at line 81 of file cvMeshSimDiscreteSolidModel.cxx.
References geom_, and NULL.
Referenced by GetFaceIds().
int cvMeshSimDiscreteSolidModel::ReadNative (char * filename) virtual
Implements cvSolidModel.
Definition at line 309 of file cvMeshSimDiscreteSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, and NULL.
int cvMeshSimDiscreteSolidModel::Reflect (double pos[], double nrm[]) inline virtual
Implements cvSolidModel.
Definition at line 102 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::RemeshFace (int numfaces, int * excludedFaces, double size) inline virtual
Implements cvSolidModel.
Definition at line 142 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::Rotate (double axis[], int ndim, double rad) inline virtual
Implements cvSolidModel.
Definition at line 100 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::Scale (double factor) inline virtual
Implements cvSolidModel.
Definition at line 101 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::SetFaceAttribute (char * attr, int faceid, char * value) inline virtual
Implements cvSolidModel.
Definition at line 123 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::SetPoly3dFacetMethod (SolidModel_FacetT code) inline virtual
Implements cvSolidModel.
Definition at line 83 of file cvMeshSimDiscreteSolidModel.h.
References CV_OK.
int cvMeshSimDiscreteSolidModel::SetRegionAttribute (char * attr, int regionid, char * value) inline virtual
Implements cvSolidModel.
Definition at line 126 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::SetVtkPolyDataObject (vtkPolyData * newPolyData) inline virtual
Implements cvSolidModel.
Definition at line 144 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::Subtract (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st) inline virtual
Implements cvSolidModel.
Definition at line 96 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::Translate (double vec[], int ndim) inline virtual
Implements cvSolidModel.
Definition at line 99 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::Union (cvSolidModel * a, cvSolidModel * b, SolidModel_SimplifyT st) inline virtual
Implements cvSolidModel.
Definition at line 95 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
int cvMeshSimDiscreteSolidModel::WriteNative (int file_version, char * filename) const virtual
Implements cvSolidModel.
Definition at line 329 of file cvMeshSimDiscreteSolidModel.cxx.
References CV_ERROR, CV_OK, geom_, and NULL.
int cvMeshSimDiscreteSolidModel::WriteVtkPolyData (char * filename) inline virtual
Implements cvSolidModel.
Definition at line 132 of file cvMeshSimDiscreteSolidModel.h.
References CV_ERROR.
Member Data Documentation
pDiscreteModel cvMeshSimDiscreteSolidModel::geom_
Definition at line 147 of file cvMeshSimDiscreteSolidModel.h.
Referenced by Check(), Clear(), cvMeshSimDiscreteSolidModel(), GetFaceIds(), GetFacePolyData(), GetPolyData(), MakePoly3dSolid(), Print(), ReadNative(), WriteNative(), and ~cvMeshSimDiscreteSolidModel().
int cvMeshSimDiscreteSolidModel::quadElem_ private
Definition at line 153 of file cvMeshSimDiscreteSolidModel.h.
Referenced by cvMeshSimDiscreteSolidModel(), and FindNodesOnElementFace().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimDiscreteSolidModel/cvMeshSimDiscreteSolidModel.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimDiscreteSolidModel/cvMeshSimDiscreteSolidModel.cxx