simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PreSolver/cmd.cxx File Reference
cmd.cxx File Reference
#include "cvFlowsolverOptions.h"
#include "cmd.h"
Functions
int debugprint (FILE *fp, char *fmt,...)
int cmd_proc (char *cmd, int *ok)
int cmd_token_get (int *p_n, char *string, char *token, int *end)
int cmd_set_input (int p_cmd_input, FILE *p_fp)
Variables
FILE * stddbg
int cmd_input = 1
FILE * fp_input = stdin
static Cmd cmd_table []
Function Documentation
int cmd_proc (char * cmd, int * ok)
Definition at line 147 of file cmd.cxx.
References CV_ERROR, CV_OK, debugprint(), MAXSTRINGLENGTH, Cmd::name, NULL, Cmd::pt2Function, and stddbg.
Referenced by main().
int cmd_set_input (int p_cmd_input, FILE * p_fp)
Definition at line 285 of file cmd.cxx.
References cmd_input, CV_OK, and fp_input.
Referenced by main().
int cmd_token_get (int * p_n, char * string, char * token, int * end)
Definition at line 196 of file cmd.cxx.
References c, CV_ERROR, and CV_OK.
Referenced by cmd_read_accelerations_vtu(), cmd_read_displacements_vtu(), cmd_read_pressure_vtu(), cmd_read_varwallprop_vtu(), cmd_read_velocity_vtu(), cmd_write_geombcdat(), parseCmdStr(), parseDouble2(), parseDouble3(), and parseNum2().
int debugprint (FILE * fp, char * fmt, ...)
Definition at line 126 of file cmd.cxx.
References CV_OK, NULL, and verbose_.
Referenced by calcInitDisplacements(), calcInitDisplacements_var_prop(), check_node_order(), cmd_adjacency(), cmd_append_displacements(), cmd_ascii_format(), cmd_boundary_faces(), cmd_create_mesh_deformable(), cmd_create_mesh_deformable_vtp(), cmd_cvsolver_node_order(), cmd_deformable_Evw(), cmd_deformable_kcons(), cmd_deformable_nuvw(), cmd_deformable_pressure(), cmd_deformable_solve(), cmd_deformable_thickness(), cmd_deformable_wall(), cmd_deformable_wall_vtp(), cmd_deformable_write_feap(), cmd_deformable_write_vtk_mesh(), cmd_elements(), cmd_fix_free_edge_nodes(), cmd_fix_free_edge_nodes_vtp(), cmd_initial_pressure(), cmd_initial_velocity(), cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), cmd_nodes(), cmd_noslip(), cmd_noslip_vtp(), cmd_number_of_elements(), cmd_number_of_mesh_edges(), cmd_number_of_mesh_faces(), cmd_number_of_nodes(), cmd_number_of_solnvars(), cmd_prescribed_velocities(), cmd_prescribed_velocities_vtp(), cmd_pressure(), cmd_pressure_vtp(), cmd_proc(), cmd_read_accelerations_vtu(), cmd_read_all_variables_vtu(), cmd_read_displacements(), cmd_read_displacements_vtu(), cmd_read_pressure_velocity_vtu(), cmd_read_pressure_vtu(), cmd_read_restart_accelerations(), cmd_read_restart_displacements(), cmd_read_restart_solution(), cmd_read_varwallprop_vtu(), cmd_read_velocity_vtu(), cmd_set_surface_id(), cmd_set_surface_id_vtp(), cmd_verbose(), cmd_write_geombcdat(), cmd_write_restartdat(), cmd_zero_pressure(), cmd_zero_pressure_vtp(), createMeshForDispCalc(), fixFreeEdgeNodes(), main(), read_variables_vtu(), setBoundaryFacesWithCode(), setBoundaryFacesWithCodeVTK(), setNodesWithCode(), StanfordIterativeSolve(), and StanfordSolveSparseMatrix().
Variable Documentation
int cmd_input = 1
Definition at line 43 of file cmd.cxx.
Referenced by cmd_set_input().
Cmd cmd_table[] static
Definition at line 46 of file cmd.cxx.
FILE* fp_input = stdin
Definition at line 44 of file cmd.cxx.
Referenced by cmd_set_input().
FILE* stddbg
Definition at line 42 of file cmd.cxx.
Referenced by calcInitDisplacements(), calcInitDisplacements_var_prop(), cmd_adjacency(), cmd_append_displacements(), cmd_ascii_format(), cmd_boundary_faces(), cmd_create_mesh_deformable(), cmd_create_mesh_deformable_vtp(), cmd_cvsolver_node_order(), cmd_deformable_Evw(), cmd_deformable_kcons(), cmd_deformable_nuvw(), cmd_deformable_pressure(), cmd_deformable_solve(), cmd_deformable_thickness(), cmd_deformable_wall(), cmd_deformable_wall_vtp(), cmd_deformable_write_feap(), cmd_deformable_write_vtk_mesh(), cmd_elements(), cmd_fix_free_edge_nodes(), cmd_fix_free_edge_nodes_vtp(), cmd_initial_pressure(), cmd_initial_velocity(), cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), cmd_nodes(), cmd_noslip(), cmd_noslip_vtp(), cmd_number_of_elements(), cmd_number_of_mesh_edges(), cmd_number_of_mesh_faces(), cmd_number_of_nodes(), cmd_number_of_solnvars(), cmd_prescribed_velocities(), cmd_prescribed_velocities_vtp(), cmd_pressure(), cmd_pressure_vtp(), cmd_proc(), cmd_read_accelerations_vtu(), cmd_read_all_variables_vtu(), cmd_read_displacements(), cmd_read_displacements_vtu(), cmd_read_pressure_velocity_vtu(), cmd_read_pressure_vtu(), cmd_read_restart_accelerations(), cmd_read_restart_displacements(), cmd_read_restart_solution(), cmd_read_varwallprop_vtu(), cmd_read_velocity_vtu(), cmd_set_surface_id(), cmd_set_surface_id_vtp(), cmd_verbose(), cmd_write_geombcdat(), cmd_write_restartdat(), cmd_zero_pressure(), cmd_zero_pressure_vtp(), createMeshForDispCalc(), fixFreeEdgeNodes(), main(), read_variables_vtu(), setBoundaryFacesWithCode(), setBoundaryFacesWithCodeVTK(), setNodesWithCode(), and StanfordIterativeSolve().