simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PreSolver/cmd.h File Reference
cmd.h File Reference
#include "cvFlowsolverOptions.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
Classes
struct Cmd
Macros
#define MAXSTRINGLENGTH 1024
#define MAXCMDLINELENGTH 1024
#define MAXPATHLEN 1024
#define DATA_MAX_SIZE 100
#define CV_OK 1
#define CV_ERROR 0
#define CALLTYPE
Typedefs
typedef struct Cmd Cmd
Functions
int cmd_proc (char *cmd, int *ok)
int cmd_token_get (int *p_n, char *string, char *token, int *end)
int cmd_set_input (int p_cmd_input, FILE *p_fp)
int debugprint (FILE *, char *,...)
int cmd_number_of_nodes (char *)
int cmd_number_of_elements (char *)
int cmd_number_of_mesh_edges (char *)
int cmd_number_of_mesh_faces (char *)
int cmd_nodes (char *)
int cmd_elements (char *)
int cmd_boundary_faces (char *)
int cmd_adjacency (char *)
int cmd_noslip (char *)
int cmd_prescribed_velocities (char *)
int cmd_zero_pressure (char *)
int cmd_pressure (char *)
int cmd_set_surface_id (char *)
int cmd_mesh_vtu (char *)
int cmd_mesh_and_adjncy_vtu (char *)
Command to generate adjacency from the existing vtu mesh.
int cmd_read_all_variables_vtu (char *)
int cmd_read_pressure_velocity_vtu (char *)
int cmd_read_pressure_vtu (char *)
int cmd_read_velocity_vtu (char *)
int cmd_read_displacements_vtu (char *)
int cmd_read_accelerations_vtu (char *)
int cmd_read_varwallprop_vtu (char *)
int cmd_noslip_vtp (char *)
int cmd_prescribed_velocities_vtp (char *)
int cmd_zero_pressure_vtp (char *)
int cmd_pressure_vtp (char *)
int cmd_deformable_wall_vtp (char *)
int cmd_set_surface_id_vtp (char *)
int cmd_fix_free_edge_nodes_vtp (char *)
int cmd_number_of_solnvars (char *)
int cmd_ascii_format (char *)
int cmd_verbose (char *)
int cmd_cvsolver_node_order (char *)
int cmd_initial_pressure (char *)
int cmd_initial_velocity (char *)
int cmd_deformable_wall (char *)
int cmd_fix_free_edge_nodes (char *)
int cmd_create_mesh_deformable (char *)
int cmd_create_mesh_deformable_vtp (char *)
int cmd_deformable_direct_solve (char *)
int cmd_deformable_iterative_solve (char *)
int cmd_deformable_write_vtk_mesh (char *)
int cmd_deformable_write_feap (char *)
int cmd_deformable_Evw (char *)
int cmd_deformable_nuvw (char *)
int cmd_deformable_thickness (char *)
int cmd_deformable_pressure (char *)
int cmd_deformable_kcons (char *)
int cmd_read_restart_solution (char *)
int cmd_read_restart_displacements (char *)
int cmd_read_restart_accelerations (char *)
int cmd_read_displacements (char *)
int cmd_write_restartdat (char *)
int cmd_write_geombcdat (char *)
int cmd_append_displacements (char *)
int cmd_set_scalar_BCs (char *cmd)
Variables
int cmd_input
FILE * fp_input
FILE * stddbg
int verbose_
int cvsolver_node_order_
Macro Definition Documentation
#define CALLTYPE
Definition at line 53 of file cmd.h.
#define CV_ERROR 0
Definition at line 42 of file cmd.h.
#define CV_OK 1
Definition at line 41 of file cmd.h.
#define DATA_MAX_SIZE 100
Definition at line 40 of file cmd.h.
#define MAXCMDLINELENGTH 1024
Definition at line 38 of file cmd.h.
Referenced by main(), NWgetNextLine(), and NWgetNextNonBlankLine().
#define MAXPATHLEN 1024
Definition at line 39 of file cmd.h.
#define MAXSTRINGLENGTH 1024
Definition at line 37 of file cmd.h.
Referenced by cmd_proc(), cmd_read_accelerations_vtu(), cmd_read_displacements_vtu(), cmd_read_pressure_vtu(), cmd_read_varwallprop_vtu(), cmd_read_velocity_vtu(), cmd_write_geombcdat(), parseCmdStr(), parseDouble(), parseDouble2(), parseDouble3(), parseNum(), and parseNum2().
Typedef Documentation
typedef struct Cmd Cmd
Function Documentation
int cmd_adjacency (char *)
Definition at line 681 of file supre-cmds.cxx.
References adjncy_, adjncySize_, buffer_, CV_ERROR, CV_OK, debugprint(), NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), stddbg, xadj_, and xadjSize_.
int cmd_append_displacements (char *)
Definition at line 1664 of file supre-cmds.cxx.
References closefile_(), CV_ERROR, CV_OK, debugprint(), DisplacementSolution_, dispsoln_, lstep, MAXPATHLEN, nshg, NULL, numNodes_, numSolnVars_, oformat, openfile_(), parseCmdStr(), stddbg, writedatablock_(), and writeheader_().
int cmd_ascii_format (char *)
Definition at line 169 of file supre-cmds.cxx.
References CV_OK, debugprint(), oformat, and stddbg.
int cmd_boundary_faces (char *)
Definition at line 435 of file supre-cmds.cxx.
References boundaryElements_, boundaryElementsIds_, buffer_, check_node_order(), CV_ERROR, CV_OK, debugprint(), NULL, numBoundaryFaces_, numElements_, numMeshFaces_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
int cmd_create_mesh_deformable (char *)
Definition at line 557 of file supre-cmds.cxx.
References createMeshForDispCalc(), CV_ERROR, CV_OK, debugprint(), and stddbg.
int cmd_create_mesh_deformable_vtp (char *)
Definition at line 1732 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, MAXPATHLEN, NULL, parseCmdStr(), siftDownKentriesCalcMesh(), and stddbg.
int cmd_cvsolver_node_order (char *)
Definition at line 193 of file supre-cmds.cxx.
References CV_OK, cvsolver_node_order_, debugprint(), and stddbg.
int cmd_deformable_direct_solve (char *)
Definition at line 1209 of file supre-cmds.cxx.
References cmd_deformable_solve().
int cmd_deformable_Evw (char *)
Definition at line 747 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_Evw_, parseDouble(), and stddbg.
int cmd_deformable_iterative_solve (char *)
Definition at line 1212 of file supre-cmds.cxx.
References cmd_deformable_solve().
int cmd_deformable_kcons (char *)
Definition at line 807 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_kcons_, parseDouble(), and stddbg.
int cmd_deformable_nuvw (char *)
Definition at line 767 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_nuvw_, parseDouble(), and stddbg.
int cmd_deformable_pressure (char *)
Definition at line 827 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_pressure_, parseDouble(), and stddbg.
int cmd_deformable_thickness (char *)
Definition at line 787 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_thickness_, parseDouble(), and stddbg.
int cmd_deformable_wall (char *)
Definition at line 628 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), setBoundaryFacesWithCode(), and stddbg.
int cmd_deformable_wall_vtp (char *)
Definition at line 1471 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), setBoundaryFacesWithCodeVTK(), and stddbg.
int cmd_deformable_write_feap (char *)
Definition at line 1379 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, iBC_, MAXPATHLEN, nodes_, NULL, numSolnVars_, parseCmdStr(), and stddbg.
int cmd_deformable_write_vtk_mesh (char *)
Definition at line 1222 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, MAXPATHLEN, nodes_, NULL, numNodes_, numSolnVars_, parseCmdStr(), and stddbg.
int cmd_elements (char *)
Definition at line 379 of file supre-cmds.cxx.
References buffer_, check_node_order(), CV_ERROR, CV_OK, debugprint(), elements_, NULL, numElements_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
int cmd_fix_free_edge_nodes (char *)
Definition at line 542 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), fixFreeEdgeNodes(), and stddbg.
int cmd_fix_free_edge_nodes_vtp (char *)
Definition at line 1523 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), edges, iBC_, MAXPATHLEN, NULL, parseCmdStr(), siftDownEdges(), and stddbg.
int cmd_initial_pressure (char *)
Definition at line 289 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), init_p_, parseDouble(), and stddbg.
int cmd_initial_velocity (char *)
Definition at line 310 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), init_v_, parseDouble3(), and stddbg.
int cmd_mesh_and_adjncy_vtu (char * cmd)
Command to generate adjacency from the existing vtu mesh.
Author
Adam Updegrove
updeg.nosp@m.a2@g.nosp@m.mail..nosp@m.com
UC Berkeley
shaddenlab.berkeley.edu
Parameters
*char cmd; should just be the vtu file
Returns
CV_OK if function completes properly
Definition at line 398 of file presolver-vtk-cmds.cxx.
References adjncy_, adjncySize_, BCB_, boundaryElements_, boundaryElementsIds_, check_node_order(), CV_ERROR, CV_OK, debugprint(), elements_, iBC_, iBCB_, MAXPATHLEN, nodes_, NULL, numBoundaryFaces_, numElements_, numMeshEdges_, numMeshFaces_, numNodes_, numSolnVars_, parseCmdStr(), stddbg, xadj_, and xadjSize_.
int cmd_mesh_vtu (char *)
Definition at line 147 of file presolver-vtk-cmds.cxx.
References BCB_, boundaryElements_, boundaryElementsIds_, check_node_order(), CV_ERROR, CV_OK, debugprint(), elements_, iBC_, iBCB_, MAXPATHLEN, nodes_, NULL, numBoundaryFaces_, numElements_, numMeshEdges_, numMeshFaces_, numNodes_, numSolnVars_, parseCmdStr(), and stddbg.
int cmd_nodes (char *)
Definition at line 331 of file supre-cmds.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), nodes_, NULL, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
int cmd_noslip (char *)
Definition at line 512 of file supre-cmds.cxx.
References CV_OK, debugprint(), setNodesWithCode(), and stddbg.
int cmd_noslip_vtp (char *)
Definition at line 1183 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), iBC_, MAXPATHLEN, NULL, parseCmdStr(), and stddbg.
Referenced by cmd_prescribed_velocities_vtp().
int cmd_number_of_elements (char *)
Definition at line 220 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numElements_, parseNum(), and stddbg.
int cmd_number_of_mesh_edges (char *)
Definition at line 254 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numMeshEdges_, parseNum(), and stddbg.
int cmd_number_of_mesh_faces (char *)
Definition at line 237 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numMeshFaces_, parseNum(), and stddbg.
int cmd_number_of_nodes (char *)
Definition at line 202 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numNodes_, parseNum(), and stddbg.
int cmd_number_of_solnvars (char *)
Definition at line 271 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numSolnVars_, parseNum(), and stddbg.
int cmd_prescribed_velocities (char *)
Definition at line 527 of file supre-cmds.cxx.
References CV_OK, debugprint(), setNodesWithCode(), and stddbg.
int cmd_prescribed_velocities_vtp (char *)
Definition at line 1235 of file presolver-vtk-cmds.cxx.
References cmd_noslip_vtp(), CV_OK, debugprint(), and stddbg.
int cmd_pressure (char *)
Definition at line 597 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), parseDouble2(), setBoundaryFacesWithCode(), and stddbg.
int cmd_pressure_vtp (char *)
Definition at line 1441 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), parseDouble2(), setBoundaryFacesWithCodeVTK(), and stddbg.
int cmd_proc (char * cmd, int * ok)
Definition at line 147 of file cmd.cxx.
References CV_ERROR, CV_OK, debugprint(), MAXSTRINGLENGTH, Cmd::name, NULL, Cmd::pt2Function, and stddbg.
Referenced by main().
int cmd_read_accelerations_vtu (char *)
Definition at line 1119 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_read_all_variables_vtu (char *)
Definition at line 988 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), read_variables_vtu(), and stddbg.
int cmd_read_displacements (char *)
Definition at line 1719 of file supre-cmds.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), dispsoln_, nshg, NULL, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
int cmd_read_displacements_vtu (char *)
Definition at line 1087 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_read_pressure_velocity_vtu (char *)
Definition at line 1005 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), read_variables_vtu(), and stddbg.
int cmd_read_pressure_vtu (char *)
Definition at line 1023 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_read_restart_accelerations (char *)
Definition at line 1531 of file supre-cmds.cxx.
References CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), readRESTARTDAT(), and stddbg.
int cmd_read_restart_displacements (char *)
Definition at line 1510 of file supre-cmds.cxx.
References CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), readRESTARTDAT(), and stddbg.
int cmd_read_restart_solution (char *)
Definition at line 1489 of file supre-cmds.cxx.
References CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), readRESTARTDAT(), and stddbg.
int cmd_read_varwallprop_vtu (char *)
Definition at line 1151 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_read_velocity_vtu (char *)
Definition at line 1055 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_set_input (int p_cmd_input, FILE * p_fp)
Definition at line 285 of file cmd.cxx.
References cmd_input, CV_OK, and fp_input.
Referenced by main().
int cmd_set_scalar_BCs (char * cmd)
int cmd_set_surface_id (char *)
Definition at line 652 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), parseNum2(), setBoundaryFacesWithCode(), and stddbg.
int cmd_set_surface_id_vtp (char *)
Definition at line 1494 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), parseNum2(), setBoundaryFacesWithCodeVTK(), and stddbg.
int cmd_token_get (int * p_n, char * string, char * token, int * end)
Definition at line 196 of file cmd.cxx.
References c, CV_ERROR, and CV_OK.
Referenced by cmd_read_accelerations_vtu(), cmd_read_displacements_vtu(), cmd_read_pressure_vtu(), cmd_read_varwallprop_vtu(), cmd_read_velocity_vtu(), cmd_write_geombcdat(), parseCmdStr(), parseDouble2(), parseDouble3(), and parseNum2().
int cmd_verbose (char *)
Definition at line 182 of file supre-cmds.cxx.
References CV_OK, debugprint(), stddbg, and verbose_.
int cmd_write_geombcdat (char *)
Definition at line 1599 of file supre-cmds.cxx.
References cmd_token_get(), CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, stddbg, and writeGEOMBCDAT().
int cmd_write_restartdat (char *)
Definition at line 1468 of file supre-cmds.cxx.
References CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), stddbg, and writeRESTARTDAT().
int cmd_zero_pressure (char *)
Definition at line 572 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), setBoundaryFacesWithCode(), and stddbg.
int cmd_zero_pressure_vtp (char *)
Definition at line 1417 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), setBoundaryFacesWithCodeVTK(), and stddbg.
int debugprint (FILE * , char * , ...)
Definition at line 126 of file cmd.cxx.
Variable Documentation
int cmd_input
Definition at line 43 of file cmd.cxx.
Referenced by cmd_set_input().
int cvsolver_node_order_
Definition at line 49 of file supre.cxx.
Referenced by check_node_order(), and cmd_cvsolver_node_order().
FILE* fp_input
Definition at line 44 of file cmd.cxx.
Referenced by cmd_set_input().
FILE* stddbg
Definition at line 63 of file cmd.h.
Referenced by StanfordSolveSparseMatrix().
int verbose_
Definition at line 48 of file supre.cxx.
Referenced by cmd_verbose(), and debugprint().