simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cv_LsetCore_init.cxx File Reference
cv_LsetCore_init.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include <string.h>
#include "cv_LsetCore_init.h"
#include "cvLevelSet.h"
#include "cvLevelSetVelocity.h"
#include "cvRepository.h"
#include "cvSolidModel.h"
#include "cv_misc_utils.h"
#include "cv_arg.h"
#include "cv_globals.h"
Functions
int LsetCore_NewCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
void DeleteLsetCore (ClientData clientData)
int LsetCore_ListMethodsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetCore_ListInstancesCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetCore_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetTimeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetTimeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetTimeStepMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ResetTimeStepMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetGridMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetGridMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetCircleSeedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetCircleSeedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetPdSeedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetPdSeedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetSolidSeedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetSolidSeedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetImageSeedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetImageSeedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetVelocityMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetVelocityMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetTimersMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetTimersMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetTimerGranularityMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetVExtensionMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetVExtensionMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_InitMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_IsInitMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_EvolveOneTimeStepMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GridModifiedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractFrontMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_RebuildPhiMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractPhiMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetBoundaryDataMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractCurvatureMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractVelMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_FindMaxVMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_VanishedMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractActiveNodesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractForceMinVNodesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractProjectionSetsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractCoveredNodesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractUncoveredNodesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_ExtractMineNodesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SetSaveProjectionSetsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetSaveProjectionSetsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_SaveGridMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetGridStatsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetCore_GetMemoryUsageMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int NewName (CONST84 char *name)
static int NewName (CONST84 char *name, Tcl_Interp *interp)
static void PrintMethods ()
static void CleanUpNodeSets (cvPolyData *nodeSets[], int numSets)
int Lsetcore_Init (Tcl_Interp *interp)
Function Documentation
void CleanUpNodeSets (cvPolyData * nodeSets[], int numSets) static
Definition at line 2329 of file cv_LsetCore_init.cxx.
Referenced by LsetCore_ExtractCoveredNodesMtd(), LsetCore_ExtractForceMinVNodesMtd(), LsetCore_ExtractMineNodesMtd(), and LsetCore_ExtractUncoveredNodesMtd().
void DeleteLsetCore (ClientData clientData)
Definition at line 359 of file cv_LsetCore_init.cxx.
References gLsetCoreTable, NULL, and cvLevelSet::tclName_.
Referenced by LsetCore_NewCmd().
static int LsetCore_EvolveOneTimeStepMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1926 of file cv_LsetCore_init.cxx.
References CV_STRLEN, cvLevelSet::EvolveOneTimeStep(), NULL, and cvLevelSet::Status().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractActiveNodesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2345 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvLevelSetStructuredGrid::GetActiveNodes(), cvLevelSet::GetGrid(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractCoveredNodesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2526 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CleanUpNodeSets(), CV_OK, cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::GetNodeSets(), gRepository, NULL, cvRepository::Register(), REQUIRED, cvLevelSetStructuredGrid::SaveCoveredNodes(), and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractCurvatureMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2180 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvLevelSet::ExtractCurvature(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractForceMinVNodesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2396 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CleanUpNodeSets(), CV_OK, cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::GetNodeSets(), gRepository, NULL, cvRepository::Register(), REQUIRED, cvLevelSetStructuredGrid::SaveForceMinVNodes(), and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractFrontMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1988 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvLevelSet::ExtractFront(), GDSC_OPTIONAL, cvRepositoryData::GetName(), gRepository, INT_Type, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractMineNodesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2644 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CleanUpNodeSets(), CV_OK, cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::GetNodeSets(), gRepository, NULL, cvRepository::Register(), REQUIRED, cvLevelSetStructuredGrid::SaveMineNodes(), and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractPhiMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2065 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvLevelSet::ExtractPhi(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractProjectionSetsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2457 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, CV_STRLEN, cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::GetNodeSets(), gRepository, NULL, cvLevelSetStructuredGrid::PSetsValid(), cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractUncoveredNodesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2583 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CleanUpNodeSets(), CV_OK, cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::GetNodeSets(), gRepository, NULL, cvRepository::Register(), REQUIRED, cvLevelSetStructuredGrid::SaveUncoveredNodes(), and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ExtractVelMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2226 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvLevelSet::ExtractVectors(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_FindMaxVMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2276 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), cvLevelSet::GetMaxV(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetBoundaryDataMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2110 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvLevelSetStructuredGrid::GetBoundaryData(), cvLevelSet::GetGrid(), cvRepositoryData::GetName(), gRepository, GridScalarT_EnumToStr(), GridScalarT_StrToEnum(), GS_INVALID, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetCircleSeedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1268 of file cv_LsetCore_init.cxx.
References CV_STRLEN, cvLevelSet::GetSeed(), NULL, Seed_T::pos, and Seed_T::r.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetGridMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1123 of file cv_LsetCore_init.cxx.
References CV_STRLEN, cvLevelSet::GetGridBandParams(), cvLevelSet::GetGridOrigin(), cvLevelSet::GetGridSize(), cvLevelSet::GetGridSpacing(), cvLevelSet::GetGridType(), GridT_EnumToStr(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetGridStatsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2836 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), cvLevelSet::GetGridStatString(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetImageSeedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1543 of file cv_LsetCore_init.cxx.
References cvRepositoryData::GetName(), and cvLevelSet::GetSeed().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetMemoryUsageMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2859 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), cvLevelSet::GetMemoryUsage(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetPdSeedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1371 of file cv_LsetCore_init.cxx.
References cvRepositoryData::GetName(), and cvLevelSet::GetSeed().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetSaveProjectionSetsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2743 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), CV_STRLEN, cvLevelSet::GetSaveProjectionSets(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetSolidSeedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1452 of file cv_LsetCore_init.cxx.
References cvRepositoryData::GetName(), and cvLevelSet::GetSeed().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetTimeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 839 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), CV_STRLEN, cvLevelSet::GetCurrTime(), cvLevelSet::GetDtFactor(), cvLevelSet::GetSimTime(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetTimerGranularityMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1757 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), cvLevelSet::GetTimerGranularity(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetTimersMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1729 of file cv_LsetCore_init.cxx.
References cvLevelSet::GetTimers(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetTimeStepMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 894 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), cvLevelSet::GetTimeStep(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetVelocityMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1625 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, cvLevelSet::GetVelocity(), NULL, and cvLevelSetVelocity::tclName_.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GetVExtensionMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1828 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ExtensionT_EnumToStr(), cvLevelSet::GetVExtension(), and NULL.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_GridModifiedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1961 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::GridModified(), and NULL.
Referenced by LsetCore_ObjectCmd().
int Lsetcore_Init (Tcl_Interp * interp)
Definition at line 283 of file cv_LsetCore_init.cxx.
References gLsetCoreTable, LsetCore_ListInstancesCmd(), LsetCore_ListMethodsCmd(), LsetCore_NewCmd(), NULL, and projectionSetBase_.
Referenced by SimVascular_Init().
static int LsetCore_InitMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1865 of file cv_LsetCore_init.cxx.
References CV_STRLEN, and cvLevelSet::Init().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_IsInitMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1892 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), NULL, and cvLevelSet::Status().
Referenced by LsetCore_ObjectCmd().
int LsetCore_ListInstancesCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 402 of file cv_LsetCore_init.cxx.
References gLsetCoreTable, and NULL.
Referenced by Lsetcore_Init().
int LsetCore_ListMethodsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 382 of file cv_LsetCore_init.cxx.
References NULL, and PrintMethods().
Referenced by Lsetcore_Init().
int LsetCore_NewCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 303 of file cv_LsetCore_init.cxx.
References DeleteLsetCore(), gLsetCoreTable, LsetCore_ObjectCmd(), NewName(), NULL, and cvLevelSet::tclName_.
Referenced by Lsetcore_Init().
int LsetCore_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 485 of file cv_LsetCore_init.cxx.
References LsetCore_EvolveOneTimeStepMtd(), LsetCore_ExtractActiveNodesMtd(), LsetCore_ExtractCoveredNodesMtd(), LsetCore_ExtractCurvatureMtd(), LsetCore_ExtractForceMinVNodesMtd(), LsetCore_ExtractFrontMtd(), LsetCore_ExtractMineNodesMtd(), LsetCore_ExtractPhiMtd(), LsetCore_ExtractProjectionSetsMtd(), LsetCore_ExtractUncoveredNodesMtd(), LsetCore_ExtractVelMtd(), LsetCore_FindMaxVMtd(), LsetCore_GetBoundaryDataMtd(), LsetCore_GetCircleSeedMtd(), LsetCore_GetGridMtd(), LsetCore_GetGridStatsMtd(), LsetCore_GetImageSeedMtd(), LsetCore_GetMemoryUsageMtd(), LsetCore_GetPdSeedMtd(), LsetCore_GetSaveProjectionSetsMtd(), LsetCore_GetSolidSeedMtd(), LsetCore_GetTimeMtd(), LsetCore_GetTimerGranularityMtd(), LsetCore_GetTimersMtd(), LsetCore_GetTimeStepMtd(), LsetCore_GetVelocityMtd(), LsetCore_GetVExtensionMtd(), LsetCore_GridModifiedMtd(), LsetCore_InitMtd(), LsetCore_IsInitMtd(), LsetCore_RebuildPhiMtd(), LsetCore_ResetTimeStepMtd(), LsetCore_SaveGridMtd(), LsetCore_SetCircleSeedMtd(), LsetCore_SetGridMtd(), LsetCore_SetImageSeedMtd(), LsetCore_SetPdSeedMtd(), LsetCore_SetSaveProjectionSetsMtd(), LsetCore_SetSolidSeedMtd(), LsetCore_SetTimeMtd(), LsetCore_SetTimersMtd(), LsetCore_SetVelocityMtd(), LsetCore_SetVExtensionMtd(), LsetCore_VanishedMtd(), NULL, and PrintMethods().
Referenced by LsetCore_NewCmd().
static int LsetCore_RebuildPhiMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2039 of file cv_LsetCore_init.cxx.
References CV_STRLEN, and cvLevelSet::RebuildPhi().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_ResetTimeStepMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 922 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), NULL, and cvLevelSet::ResetTimeStep().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SaveGridMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2775 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvLevelSetStructuredGrid::CreateGridPolyData(), cvRepository::Exists(), cvLevelSet::GetGrid(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetCircleSeedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1218 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, NULL, Seed_T::pos, Seed_T::r, REQUIRED, and cvLevelSet::SetSeed().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetGridMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 944 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argv, Dense_GridT, DOUBLE_Type, GDSC_OPTIONAL, GridT_EnumToStr(), GridT_StrToEnum(), INT_Type, Invalid_GridT, LIST_Type, NULL, REQUIRED, cvLevelSet::SetGridBandParams(), cvLevelSet::SetGridOrigin(), cvLevelSet::SetGridSize(), cvLevelSet::SetGridSpacing(), cvLevelSet::SetGridType(), Sparse_GridT, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetImageSeedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1480 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, REQUIRED, cvLevelSet::SetSeed(), STRING_Type, and STRUCTURED_PTS_T.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetPdSeedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1313 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, cvLevelSet::SetSeed(), and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetSaveProjectionSetsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2705 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), INT_Type, NULL, REQUIRED, and cvLevelSet::SetSaveProjectionSets().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetSolidSeedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1399 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, REQUIRED, cvLevelSet::SetSeed(), SOLID_MODEL_T, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetTimeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 760 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, GDSC_OPTIONAL, NULL, cvLevelSet::SetDtFactor(), and cvLevelSet::SetSimTime().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetTimersMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1664 of file cv_LsetCore_init.cxx.
References CV_STRLEN, NULL, and cvLevelSet::SetTimers().
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetVelocityMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1574 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, gLsetVTable, cvLevelSet::LinkVelocity(), NULL, REQUIRED, and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_SetVExtensionMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1786 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, ExtensionT_StrToEnum(), NULL, REQUIRED, cvLevelSet::SetVExtension(), and STRING_Type.
Referenced by LsetCore_ObjectCmd().
static int LsetCore_VanishedMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2304 of file cv_LsetCore_init.cxx.
References ARG_GenSyntaxStr(), NULL, and cvLevelSet::Vanished().
Referenced by LsetCore_ObjectCmd().
static int NewName (CONST84 char * name) static
Definition at line 241 of file cv_LsetCore_init.cxx.
References gLsetCoreTable, and NULL.
Referenced by LsetCore_NewCmd().
static int NewName (CONST84 char * name, Tcl_Interp * interp) static
Definition at line 256 of file cv_LsetCore_init.cxx.
References NULL.
static void PrintMethods () static
Definition at line 426 of file cv_LsetCore_init.cxx.
Referenced by LsetCore_ListMethodsCmd(), and LsetCore_ObjectCmd().