simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/PolyDataSolid/cv_polydatasolid_utils.cxx File Reference
cv_polydatasolid_utils.cxx File Reference
The implementations of functions in cv_polydatasolid_utils.
#include "SimVascular.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <assert.h>
#include <string.h>
#include "cv_polydatasolid_utils.h"
#include "cv_misc_utils.h"
#include "cv_sys_geom.h"
#include "cv_globals.h"
#include "vtkSmartPointer.h"
#include "vtkSTLReader.h"
#include "vtkSTLWriter.h"
#include "vtkGenericDataObjectReader.h"
#include "vtkGenericDataObjectWriter.h"
#include "vtkXMLPolyDataReader.h"
#include "vtkXMLPolyDataWriter.h"
#include "vtkXMLUnstructuredGridWriter.h"
#include "vtkPLYReader.h"
#include "vtkPLYWriter.h"
#include "vtkPolyData.h"
#include "vtkGetBoundaryFaces.h"
#include "vtkUnstructuredGrid.h"
#include "vtkGeometryFilter.h"
#include "vtkThreshold.h"
#include "vtkDataSetSurfaceFilter.h"
#include "vtkAppendFilter.h"
Functions
int PlyDtaUtils_Init ()
Initialization function for cv_polydata_utils (not necessary)
int PlyDtaUtils_GetFaceIds (vtkPolyData *geom, int *v_num_faces, int **v_faces)
Procedure to get face numbers that correspond to the scalars assigned to the geometry in vtkGetBoundaryFaces.cxx.
int PlyDtaUtils_GetBoundaryFaces (vtkPolyData *geom, double angle, int *numRegions)
Custom filter to extract the boundaries from surface.
int PlyDtaUtils_GetFacePolyData (vtkPolyData *geom, int *faceid, vtkPolyData *facepd)
Based on Scalars Defined by the GetBoundaryFaces filter, separate into face VTKs.
int PlyDtaUtils_ReadNative (char *filename, vtkPolyData *result)
Function to load in a solid file.
int PlyDtaUtils_WriteNative (vtkPolyData *geom, int file_version, char *filename)
Function to write the polydata.
int PlyDtaUtils_CombineFaces (vtkPolyData *geom, int *targetface, int *loseface)
Function to combine the ids of two faces in the polydata.
int PlyDtaUtils_DeleteCells (vtkPolyData *geom, int *numcells, int *cells)
Function to delete the cells in the polydata.
int PlyDtaUtils_DeleteRegion (vtkPolyData *geom, int *regionid)
Function to delete a region in the polydata.
int PlyDtaUtils_PDCheckArrayName (vtkPolyData *object, int datatype, std::string arrayname)
Function to check is array with name exists in cell or point data.
int PlyDtaUtils_UGCheckArrayName (vtkUnstructuredGrid *object, int datatype, std::string arrayname)
Function to check is array with name exists in cell or point data.
Detailed Description
The implementations of functions in cv_polydatasolid_utils.
Author
Adam Updegrove
updeg.nosp@m.a2@g.nosp@m.mail..nosp@m.com
UC Berkeley
shaddenlab.berkeley.edu
Definition in file cv_polydatasolid_utils.cxx.
Function Documentation
int PlyDtaUtils_CombineFaces (vtkPolyData * geom, int * targetface, int * loseface)
Function to combine the ids of two faces in the polydata.
Parameters
targetface id of the face to set the two faces to have new id of
loseface id of the second face, id will be lost
Returns
CV_OK if executed correctly, CV_ERROR if the geometry is NULL or the function does not return properly.
Definition at line 417 of file cv_polydatasolid_utils.cxx.
References CV_ERROR, CV_OK, and PlyDtaUtils_PDCheckArrayName().
Referenced by cvPolyDataSolid::CombineFaces().
int PlyDtaUtils_DeleteCells (vtkPolyData * geom, int * numcells, int * cells)
Function to delete the cells in the polydata.
Parameters
numfaces this is the number of cells to delete from the polydata
faces this is an array containing the ids of the cells to delete
Returns
CV_OK if executed correctly, CV_ERROR if the geometry is NULL or the function does not return properly.
Definition at line 463 of file cv_polydatasolid_utils.cxx.
References CV_OK.
Referenced by cvPolyDataSolid::DeleteFaces().
int PlyDtaUtils_DeleteRegion (vtkPolyData * geom, int * regionid)
Function to delete a region in the polydata.
Parameters
regionid this is the region id to delete all of the cells in
Returns
CV_OK if executed correctly, CV_ERROR if the geometry is NULL or the function does not return properly.
Definition at line 490 of file cv_polydatasolid_utils.cxx.
References CV_ERROR, CV_OK, and PlyDtaUtils_PDCheckArrayName().
Referenced by cvPolyDataSolid::DeleteRegion().
int PlyDtaUtils_GetBoundaryFaces (vtkPolyData * geom, double angle, int * numRegions)
Custom filter to extract the boundaries from surface.
Parameters
*geom input vtkPolyData on which to get the surfaces
angle double that specifies the extraction angle. Any faces with a difference between face normals larger than this angle will be considered a separate face
Returns
CV_OK if function completes properly
Definition at line 175 of file cv_polydatasolid_utils.cxx.
References CV_OK.
Referenced by cvTetGenMeshObject::GetBoundaryFaces(), and cvPolyDataSolid::GetBoundaryFaces().
int PlyDtaUtils_GetFaceIds (vtkPolyData * geom, int * v_num_faces, int ** v_faces)
Procedure to get face numbers that correspond to the scalars assigned to the geometry in vtkGetBoundaryFaces.cxx.
Parameters
*geom input vtkPolyData on which to get the face ids
*v_num_faces int that contains the number of total face regions
**v_faces vector containing the array of numerical values corresponding to each face region
Returns
CV_OK if function completes properly
Definition at line 99 of file cv_polydatasolid_utils.cxx.
References CV_ERROR, CV_OK, NULL, and PlyDtaUtils_PDCheckArrayName().
Referenced by cvPolyDataSolid::GetFaceIds().
int PlyDtaUtils_GetFacePolyData (vtkPolyData * geom, int * faceid, vtkPolyData * facepd)
Based on Scalars Defined by the GetBoundaryFaces filter, separate into face VTKs.
Parameters
*geom input vtkPolyData on which to get the face PolyData
angle double that specifies the extraction angle. Any faces with a difference between face normals larger than this angle will be considered a separate face
Returns
CV_OK if function completes properly
Note
There is another method to do this that does not retain id information. It may be faster, but doesn't reatain info
Definition at line 217 of file cv_polydatasolid_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by cvPolyDataSolid::GetFacePolyData().
int PlyDtaUtils_Init ()
Initialization function for cv_polydata_utils (not necessary)
Definition at line 80 of file cv_polydatasolid_utils.cxx.
References CV_OK.
Referenced by PolyDataSolid_Init().
int PlyDtaUtils_PDCheckArrayName (vtkPolyData * object, int datatype, std::string arrayname)
Function to check is array with name exists in cell or point data.
Parameters
object this is the object to check if the array exists
datatype this is point or cell. point =0,cell=1
arrayname this is the name of the array to check this returns 1 if the array exists and zero if it doesn't or the function does not return properly.
Definition at line 533 of file cv_polydatasolid_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by cvTetGenMeshObject::GenerateSurfaceRemesh(), cvTetGenMeshObject::GetModelFaceInfo(), cvTetGenMeshObject::NewMesh(), PlyDtaUtils_CombineFaces(), PlyDtaUtils_DeleteRegion(), PlyDtaUtils_GetFaceIds(), TGenUtils_ConvertToTetGen(), TGenUtils_GetFacePolyData(), TGenUtils_ResetOriginalRegions(), TGenUtils_SetRefinementSphere(), and TGenUtils_SetSizeFunctionArray().
int PlyDtaUtils_ReadNative (char * filename, vtkPolyData * result)
Function to load in a solid file.
Parameters
*filename Pointer to a char filename of the file to read in
*result vtkPolyData that is to store input file info
Returns
CV_OK if executed correctly
Note
Current accepted filetypes include:
STL
VTP
VTK
PLY
Definition at line 264 of file cv_polydatasolid_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by cvTetGenMeshObject::LoadModel(), and cvPolyDataSolid::ReadNative().
int PlyDtaUtils_UGCheckArrayName (vtkUnstructuredGrid * object, int datatype, std::string arrayname)
Function to check is array with name exists in cell or point data.
Parameters
object this is the object to check if the array exists
datatype this is point or cell. point =0,cell=1
arrayname this is the name of the array to check this returns 1 if the array exists and zero if it doesn't or the function does not return properly.
Definition at line 584 of file cv_polydatasolid_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by TGenUtils_writeDiffAdj(), and cvTetGenMeshObject::WriteMetisAdjacency().
int PlyDtaUtils_WriteNative (vtkPolyData * geom, int file_version, char * filename)
Function to write the polydata.
Parameters
*filename Pointer to a char filename of the file to write
file_version int for filetype
*geom vtkPolyData that contains the info to be written to file
Returns
CV_OK if executed correctly, CV_ERROR if the geometry is NULL or the write function does not return properly.
Definition at line 327 of file cv_polydatasolid_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by cvPolyDataSolid::WriteNative().