simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/TetGenMeshObject/cv_tetgen_mesh_init.cxx File Reference
cv_tetgen_mesh_init.cxx File Reference
Ipmlements function to register TetGenMeshObject as a mesh type.
#include "SimVascular.h"
#include "cv_misc_utils.h"
#include "cv_tetgen_mesh_init.h"
#include "cvTetGenMeshSystem.h"
#include "cv_tetgenmesh_utils.h"
#include "cv_arg.h"
#include <stdio.h>
#include <string.h>
#include "cvRepository.h"
#include "cv_globals.h"
Functions
int TetGenMesh_AvailableCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Tetgenmesh_Init (Tcl_Interp *interp)
Detailed Description
Ipmlements function to register TetGenMeshObject as a mesh type.
Initiates TetGenMeshObject as a valid solid type upon startup.
Author
Adam Updegrove
updeg.nosp@m.a2@g.nosp@m.mail..nosp@m.com
UC Berkeley
shaddenlab.berkeley.edu
The Tetgenmesh_Init is called upon startup of Simvascular and registers the TetGenMeshObject within the Mesh System
Author
Adam Updegrove
updeg.nosp@m.a2@g.nosp@m.mail..nosp@m.com
UC Berkeley
shaddenlab.berkeley.edu
Definition in file cv_tetgen_mesh_init.cxx.
Function Documentation
int TetGenMesh_AvailableCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 112 of file cv_tetgen_mesh_init.cxx.
Referenced by Tetgenmesh_Init().
int Tetgenmesh_Init (Tcl_Interp * interp)
Definition at line 74 of file cv_tetgen_mesh_init.cxx.
References CV_OK, cvMeshObject::KERNEL_TETGEN, NULL, cvMeshSystem::RegisterKernel(), TetGenMesh_AvailableCmd(), and TGenUtils_Init().
Referenced by SimVascular_Init().