simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/ITK/cv_ITKLset2d_init.cxx File Reference
cv_ITKLset2d_init.cxx File Reference
#include "SimVascular.h"
#include "cvTCLMacros.h"
#include "cv_LsetCore_init.h"
#include "cvITKLevelSet.h"
#include "cvITKLevelSetBase.h"
#include "cvLevelSetVelocity.h"
#include "cvRepository.h"
#include "cvSolidModel.h"
#include "cv_misc_utils.h"
#include "cv_arg.h"
#include "Util/cvITKUtils.h"
#include "cv_ITKLset_init.h"
#include "cv_globals.h"
Functions
static int NewName (CONST84 char *name)
static void PrintMethods ()
static int itkls2d_NewCmd (CXX_TCL_STDARGS)
void Deleteitkls2d (ClientData clientData)
static int itkls2d_ObjectCmd (CXX_TCL_STDARGS)
static int itkls2d_SetInputsMtd (CXX_TCL_STDARGS)
static int itkls2d_PhaseOneLevelSetMtd (CXX_TCL_STDARGS)
static int itkls2d_PhaseTwoLevelSetMtd (CXX_TCL_STDARGS)
static int itkls2d_GACLevelSetMtd (CXX_TCL_STDARGS)
CVTCLMtdDeclareMacro (itkls2d, GetFront)
CVTCLMtdDeclareMacro (itkls2d, GetFrontImage)
CVTCLMtdDeclareMacro (itkls2d, GetVelocityImage)
CVTCLMtdDeclareMacro (itkls2d, WriteFront)
CVTCLMtdDeclareMacro (itkls2d, SetMaxIterations)
CVTCLMtdDeclareMacro (itkls2d, SetMaxRMSError)
CVTCLMtdDeclareMacro (itkls2d, SetDebug)
CVTCLMtdDeclareMacro (itkls2d, SetPropagationScaling)
CVTCLMtdDeclareMacro (itkls2d, SetAdvectionScaling)
CVTCLMtdDeclareMacro (itkls2d, SetCurvatureScaling)
CVTCLMtdDeclareMacro (itkls2d, SetUseNormalVectorCurvature)
CVTCLMtdDeclareMacro (itkls2d, SetUseMeanCurvature)
CVTCLMtdDeclareMacro (itkls2d, SetUseMinimalCurvature)
CVTCLObjMemberGetObjPropertyMacro (itkls2d, cvITKLevelSetBase<>, Front, cvPolyData)
CVTCLObjMemberGetObjPropertyMacro (itkls2d, cvITKLevelSetBase<>, VelocityImage, cvStrPts)
CVTCLObjMemberGetObjPropertyMacro (itkls2d, cvITKLevelSetBase<>, FrontImage, cvStrPts)
CVTCLObjMemberSetPropertyMacro (itkls2d, cvITKLevelSetBase<>, MaxIterations, int, INT_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d, cvITKLevelSetBase<>, MaxRMSError, double, DOUBLE_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d, cvITKLevelSetBase<>, PropagationScaling, double, DOUBLE_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d, cvITKLevelSetBase<>, CurvatureScaling, double, DOUBLE_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d, cvITKLevelSetBase<>, AdvectionScaling, double, DOUBLE_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d, cvITKLevelSetBase<>, Debug, bool, BOOL_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d, cvITKLevelSetBase<>, UseNormalVectorCurvature, bool, BOOL_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d, cvITKLevelSetBase<>, UseMeanCurvature, bool, BOOL_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d, cvITKLevelSetBase<>, UseMinimalCurvature, bool, BOOL_Type)
int itkls2d_Init (Tcl_Interp *interp)
static int itkls2d_WriteFrontMtd (CXX_TCL_STDARGS)
Function Documentation
CVTCLMtdDeclareMacro (itkls2d , GetFront)
CVTCLMtdDeclareMacro (itkls2d , GetFrontImage)
CVTCLMtdDeclareMacro (itkls2d , GetVelocityImage)
CVTCLMtdDeclareMacro (itkls2d , WriteFront)
CVTCLMtdDeclareMacro (itkls2d , SetMaxIterations)
CVTCLMtdDeclareMacro (itkls2d , SetMaxRMSError)
CVTCLMtdDeclareMacro (itkls2d , SetDebug)
CVTCLMtdDeclareMacro (itkls2d , SetPropagationScaling)
CVTCLMtdDeclareMacro (itkls2d , SetAdvectionScaling)
CVTCLMtdDeclareMacro (itkls2d , SetCurvatureScaling)
CVTCLMtdDeclareMacro (itkls2d , SetUseNormalVectorCurvature)
CVTCLMtdDeclareMacro (itkls2d , SetUseMeanCurvature)
CVTCLMtdDeclareMacro (itkls2d , SetUseMinimalCurvature)
CVTCLObjMemberGetObjPropertyMacro (itkls2d , cvITKLevelSetBase<> , Front , cvPolyData)
CVTCLObjMemberGetObjPropertyMacro (itkls2d , cvITKLevelSetBase<> , VelocityImage , cvStrPts)
CVTCLObjMemberGetObjPropertyMacro (itkls2d , cvITKLevelSetBase<> , FrontImage , cvStrPts)
CVTCLObjMemberSetPropertyMacro (itkls2d , cvITKLevelSetBase<> , MaxIterations , int , INT_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d , cvITKLevelSetBase<> , MaxRMSError , double , DOUBLE_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d , cvITKLevelSetBase<> , PropagationScaling , double , DOUBLE_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d , cvITKLevelSetBase<> , CurvatureScaling , double , DOUBLE_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d , cvITKLevelSetBase<> , AdvectionScaling , double , DOUBLE_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d , cvITKLevelSetBase<> , Debug , bool , BOOL_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d , cvITKLevelSetBase<> , UseNormalVectorCurvature , bool , BOOL_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d , cvITKLevelSetBase<> , UseMeanCurvature , bool , BOOL_Type)
CVTCLObjMemberSetPropertyMacro (itkls2d , cvITKLevelSetBase<> , UseMinimalCurvature , bool , BOOL_Type)
void Deleteitkls2d (ClientData clientData)
Definition at line 217 of file cv_ITKLset2d_init.cxx.
References gLsetCoreTable, NULL, and cvITKLevelSetBase< TInputImage, TInternalPixelType >::tclName_.
Referenced by itkls2d_NewCmd().
static int itkls2d_GACLevelSetMtd (CXX_TCL_STDARGS) static
Definition at line 382 of file cv_ITKLset2d_init.cxx.
References ARG_GenSyntaxStr(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputeGACLevelSet(), CVTCLParseTclStrMacro, CVTCLTestArgsMacro, DOUBLE_Type, GDSC_OPTIONAL, NULL, and REQUIRED.
int itkls2d_Init (Tcl_Interp * interp)
Definition at line 102 of file cv_ITKLset2d_init.cxx.
References CVTCLFunctionInit.
Referenced by SimVascular_Init().
static int itkls2d_NewCmd (CXX_TCL_STDARGS) static
Definition at line 161 of file cv_ITKLset2d_init.cxx.
References Deleteitkls2d(), gLsetCoreTable, itkls2d_ObjectCmd(), NewName(), NULL, and cvITKLevelSetBase< TInputImage, TInternalPixelType >::tclName_.
int itkls2d_ObjectCmd (CXX_TCL_STDARGS) static
Definition at line 113 of file cv_ITKLset2d_init.cxx.
References CVTCLObjMethodInit, NULL, and PrintMethods().
Referenced by itkls2d_NewCmd().
static int itkls2d_PhaseOneLevelSetMtd (CXX_TCL_STDARGS) static
Definition at line 315 of file cv_ITKLset2d_init.cxx.
References ARG_GenSyntaxStr(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputePhaseOneLevelSet(), CVTCLParseTclStrMacro, CVTCLTestArgsMacro, DOUBLE_Type, GDSC_OPTIONAL, NULL, REQUIRED, cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetSigmaAdvection(), and cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetSigmaFeature().
static int itkls2d_PhaseTwoLevelSetMtd (CXX_TCL_STDARGS) static
Definition at line 350 of file cv_ITKLset2d_init.cxx.
References ARG_GenSyntaxStr(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputePhaseTwoLevelSet(), CVTCLParseTclStrMacro, CVTCLTestArgsMacro, DOUBLE_Type, GDSC_OPTIONAL, NULL, REQUIRED, cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetSigmaAdvection(), and cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetSigmaFeature().
int itkls2d_SetInputsMtd (CXX_TCL_STDARGS) static
Definition at line 235 of file cv_ITKLset2d_init.cxx.
References ARG_GenSyntaxStr(), CVTCLParseTclStrMacro, CVTCLTestArgsMacro, cvRepository::GetObject(), cvRepositoryData::GetType(), cvRepository::GetType(), gRepository, NULL, POLY_DATA_T, RepositoryDataT_EnumToStr(), REQUIRED, cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetInputImage(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetSeed(), STRING_Type, and STRUCTURED_PTS_T.
static int itkls2d_WriteFrontMtd (CXX_TCL_STDARGS) static
Definition at line 407 of file cv_ITKLset2d_init.cxx.
References cvITKLevelSetBase< TInputImage, TInternalPixelType >::WriteFrontImages().
static int NewName (CONST84 char * name) static
Definition at line 88 of file cv_ITKLset2d_init.cxx.
References gLsetCoreTable, and NULL.
Referenced by itkls2d_NewCmd().
static void PrintMethods () static
Definition at line 151 of file cv_ITKLset2d_init.cxx.
Referenced by itkls2d_ObjectCmd().