simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/PolyDataSolid/cv_polydatasolid_init.cxx File Reference
cv_polydatasolid_init.cxx File Reference
Ipmlements function to register PolyDataSolid as a solid type.
#include "SimVascular.h"
#include <stdio.h>
#include <string.h>
#include "cvRepository.h"
#include "cv_solid_init.h"
#include "cv_polydatasolid_init.h"
#include "cv_polydatasolid_utils.h"
#include "cvSolidModel.h"
#include "cv_arg.h"
#include "cv_misc_utils.h"
#include "cv_vtk_utils.h"
#include "cvPolyData.h"
#include "cvPolyDataSolid.h"
#include "vtkPolyData.h"
#include "cvFactoryRegistrar.h"
#include "cv_globals.h"
Functions
cvPolyDataSolid * CreatePolyDataSolid ()
int PolyDataSolid_AvailableCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int PolyDataSolid_RegistrarsListCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int PolyDataSolid_Init (Tcl_Interp *interp)
Detailed Description
Ipmlements function to register PolyDataSolid as a solid type.
Initiates PolyDataSolid as a valid solid type upon startup.
Author
Adam Updegrove
updeg.nosp@m.a2@g.nosp@m.mail..nosp@m.com
UC Berkeley
shaddenlab.berkeley.edu
The PolyDataSolid_Init is called upon startup of Simvascular and registers the PolyDataSolid with the cvFactoryRegistrar so that PolyDataSolid can be used as a solid type
Author
Adam Updegrove
updeg.nosp@m.a2@g.nosp@m.mail..nosp@m.com
UC Berkeley
shaddenlab.berkeley.edu
Definition in file cv_polydatasolid_init.cxx.
Function Documentation
cvPolyDataSolid* CreatePolyDataSolid ()
Definition at line 72 of file cv_polydatasolid_init.cxx.
Referenced by PolyDataSolid_Init().
int PolyDataSolid_AvailableCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 116 of file cv_polydatasolid_init.cxx.
Referenced by PolyDataSolid_Init().
int PolyDataSolid_Init (Tcl_Interp * interp)
Definition at line 88 of file cv_polydatasolid_init.cxx.
References CreatePolyDataSolid(), CV_OK, NULL, PlyDtaUtils_Init(), PolyDataSolid_AvailableCmd(), PolyDataSolid_RegistrarsListCmd(), cvFactoryRegistrar::SetFactoryMethodPtr(), and SM_KT_POLYDATA.
Referenced by SimVascular_Init().
int PolyDataSolid_RegistrarsListCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 124 of file cv_polydatasolid_init.cxx.
References cvFactoryRegistrar::GetFactoryMethodPtr(), and NULL.
Referenced by PolyDataSolid_Init().