simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cv_math_init.cxx File Reference
cv_math_init.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include "cv_arg.h"
#include "cv_misc_utils.h"
#include "cvMath.h"
#include "cv_math_init.h"
Functions
int Math_FFTCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Math_inverseFFTCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Math_computeWomersleyCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Math_linearInterpCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Math_curveLengthCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Math_linearInterpolateCurveCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Math_fitLeastSquaresCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Math_smoothCurveCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Math_Init (Tcl_Interp *interp)
Function Documentation
int Math_computeWomersleyCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 324 of file cv_math_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, cvMath::compute_v_womersley(), cvMath::createArray(), CV_ERROR, cvMath::deleteArray(), DOUBLE_Type, LIST_Type, NULL, REQUIRED, and time.
Referenced by Math_Init().
int Math_curveLengthCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 541 of file cv_math_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, cvMath::createArray(), cvMath::curveLength(), CV_ERROR, cvMath::deleteArray(), DOUBLE_Type, INT_Type, LIST_Type, NULL, and REQUIRED.
Referenced by Math_Init().
int Math_FFTCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 104 of file cv_math_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, cvMath::createArray(), CV_ERROR, cvMath::deleteArray(), DOUBLE_Type, cvMath::FFT(), INT_Type, LIST_Type, NULL, and REQUIRED.
Referenced by Math_Init().
int Math_fitLeastSquaresCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 748 of file cv_math_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, cvMath::createArray(), CV_ERROR, cvMath::deleteArray(), DOUBLE_Type, cvMath::fitLeastSquares(), INT_Type, LIST_Type, NULL, and REQUIRED.
Referenced by Math_Init().
int Math_Init (Tcl_Interp * interp)
Definition at line 77 of file cv_math_init.cxx.
References Math_computeWomersleyCmd(), Math_curveLengthCmd(), Math_FFTCmd(), Math_fitLeastSquaresCmd(), Math_inverseFFTCmd(), Math_linearInterpCmd(), Math_linearInterpolateCurveCmd(), Math_smoothCurveCmd(), and NULL.
Referenced by SimVascular_Init().
int Math_inverseFFTCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 212 of file cv_math_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, cvMath::createArray(), CV_ERROR, cvMath::deleteArray(), DOUBLE_Type, INT_Type, cvMath::inverseFFT(), LIST_Type, NULL, and REQUIRED.
Referenced by Math_Init().
int Math_linearInterpCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 435 of file cv_math_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, cvMath::createArray(), CV_ERROR, cvMath::deleteArray(), DOUBLE_Type, INT_Type, cvMath::linearInterpolate(), LIST_Type, NULL, and REQUIRED.
Referenced by Math_Init().
int Math_linearInterpolateCurveCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 640 of file cv_math_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, cvMath::createArray(), CV_ERROR, cvMath::deleteArray(), DOUBLE_Type, INT_Type, cvMath::linearInterpolateCurve(), LIST_Type, NULL, and REQUIRED.
Referenced by Math_Init().
int Math_smoothCurveCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 900 of file cv_math_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, cvMath::createArray(), CV_ERROR, cvMath::deleteArray(), DOUBLE_Type, INT_Type, LIST_Type, NULL, REQUIRED, and cvMath::smoothCurve().
Referenced by Math_Init().