simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/ParasolidSolidModel/cv_parasolid_utils.h File Reference
cv_parasolid_utils.h File Reference
#include "parasolid_kernel.h"
#include "kernel_interface.h"
#include "cvPolyData.h"
#include "cvLispList.h"
#include "cv_vtk_utils.h"
Classes
struct PsdItem
struct PsdPolyGeom
Macros
#define PARAS_VEC_SET(vec, x, y, z)
#define PARAS_BASIS_LOC_SET(basis, x, y, z)
#define PARAS_BASIS_AXIS_SET(basis, x, y, z)
#define PARAS_BASIS_REF_SET(basis, x, y, z)
#define PsdListT cvLispList<PsdItem*>
#define PsdIterT cvLispListIterator<PsdItem*>
Enumerations
enum PsdSmpT { PsdSmpT_All, PsdSmpT_Invalid }
Functions
int PsdUtils_TagCaps (cvLispList< PsdItem * > *solid, char *name)
int PsdUtils_GetFaceIds (cvLispList< PsdItem * > *geom, int *p_num_faces, int **p_faces)
int PsdUtils_GetFaceAttribute (cvLispList< PsdItem * > *solid, char *attr, int faceid, char **value)
int PsdUtils_GetFaceAttribute (char *attr, int faceid, char **value)
int PsdUtils_SetFaceAttribute (cvLispList< PsdItem * > *solid, char *attr, int faceid, char *value)
int PsdUtils_GetRegionIds (cvLispList< PsdItem * > *geom, int *p_num_regions, int **p_regions)
int PsdUtils_CheckIdentForFaceId (int orgfaceid)
int PsdUtils_GetIdent (PK_PART_t part, int id, PK_ENTITY_t *entity)
int PsdUtils_Init ()
void PsdUtils_PrintInfo ()
int PsdUtils_CheckBodies (cvLispList< PsdItem * > *geom)
PsdItem * PsdUtils_NewItem ()
int PsdUtils_DeepCopy (cvLispList< PsdItem * > *src, cvLispList< PsdItem * > **dst)
int PsdUtils_Delete (cvLispList< PsdItem * > *geom)
int PsdUtils_DeleteListOnly (cvLispList< PsdItem * > *geom)
int PsdUtils_MakeSphere (double r, double ctr[], cvLispList< PsdItem * > **result)
int PsdUtils_MakeCylinder (double r, double len, double ctr[], double axis[], cvLispList< PsdItem * > **result)
int PsdUtils_MakeTorus (double rmaj, double rmin, double ctr[], double axis[], cvLispList< PsdItem * > **result)
int PsdUtils_MakeBox2d (double w, double h, double ctr[], cvLispList< PsdItem * > **result)
int PsdUtils_MakeBox3d (double dims[], double ctr[], cvLispList< PsdItem * > **result)
int PsdUtils_MakePoly2d (cvPolyData *pd, cvLispList< PsdItem * > **result)
cvLispList< PsdItem * > * PsdUtils_MakePoly2dPts (int num_pts, double pts[])
int PsdUtils_Extrude (cvLispList< PsdItem * > *geom, double dir[], double dist, cvLispList< PsdItem * > **result)
int PsdUtils_MakeFittedBCurve (int num_pts, double ord_pts[], double tol, int closed, cvLispList< PsdItem * > **result)
int PsdUtils_MakeSplinewiseBCurve (int num_pts, double ord_pts[], int closed, cvLispList< PsdItem * > **result)
int PsdUtils_MakeLoftedBSurf (int num_curves, cvLispList< PsdItem * > *geoms[], cvLispList< PsdItem * > **result, char *name)
int PsdUtils_MakeLoftedSurf (int num_curves, cvLispList< PsdItem * > *geoms[], cvLispList< PsdItem * > **result, char *name)
int PsdUtils_MakeCap (cvPolyData *profile, cvLispList< PsdItem * > **result)
int PsdUtils_CapSurfToSolid (cvLispList< PsdItem * > *geom, cvLispList< PsdItem * > **result)
int PsdUtils_Translate (cvLispList< PsdItem * > *geom, double vec[])
int PsdUtils_Rotate (cvLispList< PsdItem * > *geom, double axis[], double rad)
int PsdUtils_Scale (cvLispList< PsdItem * > *geom, double scale)
int PsdUtils_Reflect (cvLispList< PsdItem * > *geom, double pos[], double nrm[])
int PsdUtils_Apply4x4 (cvLispList< PsdItem * > *geom, double mat[][4])
void PsdUtils_SetSmpOptions (PsdSmpT smp, PK_BODY_boolean_o_t *opts)
int PsdUtils_DispatchBoolean (cvLispList< PsdItem * > *geomA, cvLispList< PsdItem * > *geomB, PsdSmpT smp, PK_boolean_function_t fn, cvLispList< PsdItem * > **result)
int PsdUtils_Intersect (cvLispList< PsdItem * > *geomA, cvLispList< PsdItem * > *geomB, PsdSmpT smp, cvLispList< PsdItem * > **result)
int PsdUtils_Subtract (cvLispList< PsdItem * > *geomA, cvLispList< PsdItem * > *geomB, PsdSmpT smp, cvLispList< PsdItem * > **result)
int PsdUtils_Union (cvLispList< PsdItem * > *geomA, cvLispList< PsdItem * > *geomB, PsdSmpT smp, cvLispList< PsdItem * > **result)
int PsdUtils_GetEdges (cvLispList< PsdItem * > *geom, int *num, PK_EDGE_t **edges)
int PsdUtils_GetFaces (cvLispList< PsdItem * > *geom, int *num, PK_FACE_t **faces)
int PsdUtils_GetRegions (cvLispList< PsdItem * > *geom, int *num, PK_REGION_t **regions)
int PsdUtils_FindExtent (cvLispList< PsdItem * > *geom, double *extent)
int PsdUtils_GetTopoDim (cvLispList< PsdItem * > *geom, int *result)
int PsdUtils_GetBBox (cvLispList< PsdItem * > *geom, double bbox[])
int PsdUtils_ClassifyPt (cvLispList< PsdItem * > *geom, double pt[], int *ans)
int PsdUtils_GetPolyData (cvLispList< PsdItem * > *geom, int dim, int useMaxDist, double max_dist, int *p_num_geoms, PsdPolyGeom **p_geoms)
int PsdUtils_GetFacePolyData (cvLispList< PsdItem * > *geom, int faceid, int useMaxDist, double max_dist, int *p_num_geoms, PsdPolyGeom **p_geoms)
int PsdUtils_GetFaceNormal (cvLispList< PsdItem * > *geom, int faceid, double u, double v, double normal[])
int PsdUtils_GetSurfPolys (PK_BODY_t geom, int useMaxDist, double max_dist, int *p_num_verts, vtkFloatingPointType **p_verts, int *p_num_tri, int **p_conn)
int PsdUtils_GetCurveLines (PK_BODY_t geom, int *p_num_verts, vtkFloatingPointType **p_verts, int *p_num_lines, int **p_lines)
int PsdUtils_GetWireGeometry (PK_BODY_t geom, int *p_num_verts, vtkFloatingPointType **p_verts, int *p_num_lines, int **p_lines)
int PsdUtils_GetCurveGeometry (PK_CURVE_t curve, int *p_num_verts, vtkFloatingPointType **p_verts, int *p_num_lines, int **p_lines)
cvPolyData * PsdUtils_GetDiscontinuities (cvLispList< PsdItem * > *geom)
int PsdUtils_GetAxialIsoparametricCurve (cvLispList< PsdItem * > *geom, double p, cvLispList< PsdItem * > **result)
int PsdUtils_ReadNative (char filename[], cvLispList< PsdItem * > **result, PK_PART_t *firstPart, int *isAssembly)
int PsdUtils_WriteNative (cvLispList< PsdItem * > *geom, int file_version, char filename[])
int PsdUtils_DeleteFaces (cvLispList< PsdItem * > *geom_, int numfaces, int *faces, cvLispList< PsdItem * > **newgeom)
int PsdUtils_CreateEdgeBlend (cvLispList< PsdItem * > *geom, int faceA, int faceB, double radius)
Macro Definition Documentation
#define PARAS_BASIS_AXIS_SET (basis, x, y, z)
Value:
basis.axis.coord[0] = x;        \
          basis.axis.coord[1] = y;       \
          basis.axis.coord[2] = z;
Definition at line 57 of file cv_parasolid_utils.h.
Referenced by PsdUtils_MakeBox2d(), PsdUtils_MakeCylinder(), PsdUtils_MakeFittedBCurve(), PsdUtils_MakeSphere(), and PsdUtils_MakeTorus().
#define PARAS_BASIS_LOC_SET (basis, x, y, z)
Value:
basis.location.coord[0] = x;  \
          basis.location.coord[1] = y;  \
          basis.location.coord[2] = z;
Definition at line 52 of file cv_parasolid_utils.h.
Referenced by PsdUtils_MakeBox2d(), PsdUtils_MakeCylinder(), PsdUtils_MakeFittedBCurve(), PsdUtils_MakeSphere(), and PsdUtils_MakeTorus().
#define PARAS_BASIS_REF_SET (basis, x, y, z)
Value:
basis.ref_direction.coord[0] = x;       \
          basis.ref_direction.coord[1] = y;       \
          basis.ref_direction.coord[2] = z;
Definition at line 62 of file cv_parasolid_utils.h.
Referenced by PsdUtils_MakeBox2d(), PsdUtils_MakeCylinder(), PsdUtils_MakeSphere(), and PsdUtils_MakeTorus().
#define PARAS_VEC_SET (vec, x, y, z)
Value:
vec.coord[0] = x;              \
          vec.coord[1] = y;              \
          vec.coord[2] = z;
Definition at line 47 of file cv_parasolid_utils.h.
Referenced by dp_paras_xform(), PsdUtils_ClassifyPt(), PsdUtils_Extrude(), PsdUtils_MakePoly2dPts(), PsdUtils_Reflect(), PsdUtils_Rotate(), PsdUtils_Scale(), and PsdUtils_Translate().
#define PsdIterT cvLispListIterator<PsdItem*>
Definition at line 78 of file cv_parasolid_utils.h.
Referenced by cvParasolidSolidModel::ListToArray(), cvParasolidSolidModel::Print(), PsdUtils_Apply4x4(), PsdUtils_CheckBodies(), PsdUtils_ClassifyPt(), PsdUtils_DeepCopy(), PsdUtils_DeleteFaces(), PsdUtils_DispatchBoolean(), PsdUtils_Extrude(), PsdUtils_FindExtent(), PsdUtils_GetAxialIsoparametricCurve(), PsdUtils_GetBBox(), PsdUtils_GetDiscontinuities(), PsdUtils_GetEdges(), PsdUtils_GetFaceIds(), PsdUtils_GetFaces(), PsdUtils_GetPolyData(), PsdUtils_GetRegionIds(), PsdUtils_GetRegions(), PsdUtils_GetTopoDim(), PsdUtils_Reflect(), PsdUtils_Rotate(), PsdUtils_Scale(), PsdUtils_Subtract(), PsdUtils_TagCaps(), PsdUtils_Translate(), and PsdUtils_WriteNative().
#define PsdListT cvLispList<PsdItem*>
Definition at line 77 of file cv_parasolid_utils.h.
Referenced by cvParasolidSolidModel::Intersect(), cvParasolidSolidModel::MakeLoftedSurf(), cvParasolidSolidModel::MakePoly2dPts(), cvParasolidSolidModel::MakePoly3dSolid(), cvParasolidSolidModel::MakePoly3dSurface(), PsdUtils_CapSurfToSolid(), PsdUtils_DeepCopy(), PsdUtils_DeleteFaces(), PsdUtils_DispatchBoolean(), PsdUtils_Extrude(), PsdUtils_GetAxialIsoparametricCurve(), PsdUtils_MakeBox2d(), PsdUtils_MakeBox3d(), PsdUtils_MakeCap(), PsdUtils_MakeCylinder(), PsdUtils_MakeFittedBCurve(), PsdUtils_MakeLoftedBSurf(), PsdUtils_MakeLoftedSurf(), PsdUtils_MakePoly2d(), PsdUtils_MakePoly2dPts(), PsdUtils_MakeSphere(), PsdUtils_MakeSplinewiseBCurve(), PsdUtils_MakeTorus(), PsdUtils_ReadNative(), PsdUtils_Subtract(), cvParasolidSolidModel::Subtract(), and cvParasolidSolidModel::Union().
Enumeration Type Documentation
enum PsdSmpT
Enumerator
PsdSmpT_All
PsdSmpT_Invalid
Definition at line 90 of file cv_parasolid_utils.h.
Function Documentation
int PsdUtils_Apply4x4 (cvLispList< PsdItem * > * geom, double mat[][4])
Definition at line 877 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, NULL, and PsdIterT.
Referenced by cvParasolidSolidModel::Apply4x4().
int PsdUtils_CapSurfToSolid (cvLispList< PsdItem * > * geom, cvLispList< PsdItem * > ** result)
Definition at line 3396 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, faces(), PsdItem::item, NULL, PsdListT, and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::CapSurfToSolid().
int PsdUtils_CheckBodies (cvLispList< PsdItem * > * geom)
Definition at line 578 of file cv_parasolid_utils.cxx.
References iter, and PsdIterT.
Referenced by cvParasolidSolidModel::Check().
int PsdUtils_CheckIdentForFaceId (int orgfaceid)
Definition at line 5278 of file cv_parasolid_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by cvMeshSimMeshObject::getIdentForFaceId().
int PsdUtils_ClassifyPt (cvLispList< PsdItem * > * geom, double pt[], int * ans)
Definition at line 1471 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, PARAS_VEC_SET, and PsdIterT.
Referenced by cvParasolidSolidModel::ClassifyPt().
int PsdUtils_CreateEdgeBlend (cvLispList< PsdItem * > * geom, int faceA, int faceB, double radius)
Definition at line 5147 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, and edges.
Referenced by cvParasolidSolidModel::CreateEdgeBlend().
int PsdUtils_DeepCopy (cvLispList< PsdItem * > * src, cvLispList< PsdItem * > ** dst)
Definition at line 1518 of file cv_parasolid_utils.cxx.
References PsdItem::b_item, CV_ERROR, CV_OK, PsdItem::item, iter, NULL, PsdIterT, PsdListT, PsdUtils_Delete(), and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::Copy(), cvParasolidSolidModel::Intersect(), PsdUtils_Subtract(), cvParasolidSolidModel::Subtract(), and cvParasolidSolidModel::Union().
int PsdUtils_Delete (cvLispList< PsdItem * > * geom)
Definition at line 1566 of file cv_parasolid_utils.cxx.
References PsdItem::b_item, CV_OK, and PsdItem::item.
Referenced by cvParasolidSolidModel::Clear(), PsdUtils_DeepCopy(), PsdUtils_Extrude(), PsdUtils_MakeBox3d(), and PsdUtils_Subtract().
int PsdUtils_DeleteFaces (cvLispList< PsdItem * > * geom_, int numfaces, int * faces, cvLispList< PsdItem * > ** newgeom)
Definition at line 4925 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, edges, PsdItem::item, iter, NULL, PsdIterT, PsdListT, and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::DeleteFaces().
int PsdUtils_DeleteListOnly (cvLispList< PsdItem * > * geom)
Definition at line 1592 of file cv_parasolid_utils.cxx.
References CV_OK.
Referenced by cvParasolidSolidModel::MakeLoftedSurf(), PsdUtils_MakeCap(), and PsdUtils_Subtract().
int PsdUtils_DispatchBoolean (cvLispList< PsdItem * > * geomA, cvLispList< PsdItem * > * geomB, PsdSmpT smp, PK_boolean_function_t fn, cvLispList< PsdItem * > ** result)
Definition at line 941 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, PsdItem::item, iter, PsdIterT, PsdListT, PsdUtils_NewItem(), and PsdUtils_SetSmpOptions().
Referenced by PsdUtils_Intersect(), PsdUtils_Subtract(), and PsdUtils_Union().
int PsdUtils_Extrude (cvLispList< PsdItem * > * geom, double dir[], double dist, cvLispList< PsdItem * > ** result)
Definition at line 2150 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, PsdItem::item, iter, local, NormVector(), PARAS_VEC_SET, PsdIterT, PsdListT, PsdUtils_Delete(), and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::Extrude(), and cvParasolidSolidModel::ExtrudeZ().
int PsdUtils_FindExtent (cvLispList< PsdItem * > * geom, double * extent)
Definition at line 1304 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, NULL, PsdIterT, PsdUtils_GetEdges(), PsdUtils_GetFaces(), PsdUtils_GetRegions(), and PsdUtils_GetTopoDim().
Referenced by cvParasolidSolidModel::FindExtent().
int PsdUtils_GetAxialIsoparametricCurve (cvLispList< PsdItem * > * geom, double p, cvLispList< PsdItem * > ** result)
Definition at line 4600 of file cv_parasolid_utils.cxx.
References c, CV_ERROR, CV_OK, faces(), PsdItem::item, iter, NULL, PsdIterT, PsdListT, and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::GetAxialIsoparametricCurve().
int PsdUtils_GetBBox (cvLispList< PsdItem * > * geom, double bbox[])
Definition at line 1425 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, maximum, minimum, and PsdIterT.
int PsdUtils_GetCurveGeometry (PK_CURVE_t curve, int * p_num_verts, vtkFloatingPointType ** p_verts, int * p_num_lines, int ** p_lines)
Definition at line 4375 of file cv_parasolid_utils.cxx.
References CV_OK, and FindMachineEpsilon().
Referenced by PsdUtils_GetPolyData().
int PsdUtils_GetCurveLines (PK_BODY_t geom, int * p_num_verts, vtkFloatingPointType ** p_verts, int * p_num_lines, int ** p_lines)
Definition at line 4134 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, fin, NULL, and point.
cvPolyData* PsdUtils_GetDiscontinuities (cvLispList< PsdItem * > * geom)
Definition at line 4459 of file cv_parasolid_utils.cxx.
References PsdItem::b_item, c, iter, NULL, and PsdIterT.
Referenced by cvParasolidSolidModel::GetDiscontinuities().
int PsdUtils_GetEdges (cvLispList< PsdItem * > * geom, int * num, PK_EDGE_t ** edges)
Definition at line 1202 of file cv_parasolid_utils.cxx.
References CV_OK, iter, NULL, and PsdIterT.
Referenced by PsdUtils_FindExtent().
int PsdUtils_GetFaceAttribute (cvLispList< PsdItem * > * solid, char * attr, int faceid, char ** value)
Definition at line 2781 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, and NULL.
Referenced by cvParasolidSolidModel::GetFaceAttribute(), and cvMeshSimMeshObject::GetModelFaceInfo().
int PsdUtils_GetFaceAttribute (char * attr, int faceid, char ** value)
Definition at line 2942 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, and NULL.
int PsdUtils_GetFaceIds (cvLispList< PsdItem * > * geom, int * p_num_faces, int ** p_faces)
Definition at line 3766 of file cv_parasolid_utils.cxx.
References CV_OK, faces(), iter, NULL, and PsdIterT.
Referenced by cvParasolidSolidModel::GetFaceIds().
int PsdUtils_GetFaceNormal (cvLispList< PsdItem * > * geom, int faceid, double u, double v, double normal[])
Definition at line 3661 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, and FALSE.
Referenced by cvParasolidSolidModel::GetFaceNormal().
int PsdUtils_GetFacePolyData (cvLispList< PsdItem * > * geom, int faceid, int useMaxDist, double max_dist, int * p_num_geoms, PsdPolyGeom ** p_geoms)
Definition at line 3591 of file cv_parasolid_utils.cxx.
References PsdPolyGeom::conn, PsdPolyGeom::conn_size, CV_ERROR, CV_OK, NULL, PsdPolyGeom::num_polys, PsdPolyGeom::num_verts, PsdUtils_GetSurfPolys(), and PsdPolyGeom::verts.
Referenced by cvParasolidSolidModel::GetFacePolyData().
int PsdUtils_GetFaces (cvLispList< PsdItem * > * geom, int * num, PK_FACE_t ** faces)
Definition at line 1236 of file cv_parasolid_utils.cxx.
References CV_OK, iter, NULL, and PsdIterT.
Referenced by PsdUtils_FindExtent().
int PsdUtils_GetIdent (PK_PART_t part, int id, PK_ENTITY_t * entity)
Definition at line 5314 of file cv_parasolid_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by cvMeshSimMeshObject::MapIDtoPID().
int PsdUtils_GetPolyData (cvLispList< PsdItem * > * geom, int dim, int useMaxDist, double max_dist, int * p_num_geoms, PsdPolyGeom ** p_geoms)
Definition at line 3491 of file cv_parasolid_utils.cxx.
References PsdPolyGeom::conn, PsdPolyGeom::conn_size, CV_ERROR, CV_OK, iter, NULL, PsdPolyGeom::num_polys, PsdPolyGeom::num_verts, PsdIterT, PsdUtils_GetCurveGeometry(), PsdUtils_GetSurfPolys(), PsdUtils_GetWireGeometry(), and PsdPolyGeom::verts.
Referenced by cvParasolidSolidModel::GetPolyData().
int PsdUtils_GetRegionIds (cvLispList< PsdItem * > * geom, int * p_num_regions, int ** p_regions)
Definition at line 3819 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, NULL, and PsdIterT.
Referenced by cvParasolidSolidModel::GetRegionIds().
int PsdUtils_GetRegions (cvLispList< PsdItem * > * geom, int * num, PK_REGION_t ** regions)
Definition at line 1270 of file cv_parasolid_utils.cxx.
References CV_OK, iter, NULL, and PsdIterT.
Referenced by PsdUtils_FindExtent().
int PsdUtils_GetSurfPolys (PK_BODY_t geom, int useMaxDist, double max_dist, int * p_num_verts, vtkFloatingPointType ** p_verts, int * p_num_tri, int ** p_conn)
Definition at line 3886 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, fin, NULL, and point.
Referenced by PsdUtils_GetFacePolyData(), and PsdUtils_GetPolyData().
int PsdUtils_GetTopoDim (cvLispList< PsdItem * > * geom, int * result)
Definition at line 1386 of file cv_parasolid_utils.cxx.
References CV_OK, iter, and PsdIterT.
Referenced by cvParasolidSolidModel::GetPolyData(), cvParasolidSolidModel::GetTopoDim(), and PsdUtils_FindExtent().
int PsdUtils_GetWireGeometry (PK_BODY_t geom, int * p_num_verts, vtkFloatingPointType ** p_verts, int * p_num_lines, int ** p_lines)
Definition at line 4273 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, edges, and FindMachineEpsilon().
Referenced by PsdUtils_GetPolyData().
int PsdUtils_Init ()
Definition at line 458 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, fru_init(), and NULL.
Referenced by cvAdapt::Adapt(), and Parasolidsolid_Init().
int PsdUtils_Intersect (cvLispList< PsdItem * > * geomA, cvLispList< PsdItem * > * geomB, PsdSmpT smp, cvLispList< PsdItem * > ** result)
Definition at line 1066 of file cv_parasolid_utils.cxx.
References PsdUtils_DispatchBoolean().
Referenced by cvParasolidSolidModel::Intersect().
int PsdUtils_MakeBox2d (double w, double h, double ctr[], cvLispList< PsdItem * > ** result)
Definition at line 1738 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, PsdItem::item, PARAS_BASIS_AXIS_SET, PARAS_BASIS_LOC_SET, PARAS_BASIS_REF_SET, PsdListT, and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::MakeBox2d().
int PsdUtils_MakeBox3d (double dims[], double ctr[], cvLispList< PsdItem * > ** result)
Definition at line 1768 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, PsdItem::item, NULL, PsdListT, PsdUtils_Delete(), PsdUtils_NewItem(), and PsdUtils_Translate().
Referenced by cvParasolidSolidModel::MakeBox3d().
int PsdUtils_MakeCap (cvPolyData * profile, cvLispList< PsdItem * > ** result)
Definition at line 3218 of file cv_parasolid_utils.cxx.
References PsdItem::b_item, CV_ERROR, CV_OK, dp_cont_norm_comp(), dp_mth_mat3x3_rot_extract(), dp_mth_norm_frame(), dp_mth_omat3x3_inv(), dp_mth_xform_frame(), dp_mth_xform_pt(), dp_paras_xform(), edges, FindMachineEpsilon(), PsdItem::item, NULL, PsdListT, PsdUtils_DeleteListOnly(), PsdUtils_MakeSplinewiseBCurve(), PsdUtils_NewItem(), sys_geom_GetOrderedPts(), and sys_geom_PolygonNormal().
Referenced by cvParasolidSolidModel::MakeLoftedSurf().
int PsdUtils_MakeCylinder (double r, double len, double ctr[], double axis[], cvLispList< PsdItem * > ** result)
Definition at line 1638 of file cv_parasolid_utils.cxx.
References Cross(), CV_ERROR, CV_OK, PsdItem::item, Magnitude(), NormVector(), PARAS_BASIS_AXIS_SET, PARAS_BASIS_LOC_SET, PARAS_BASIS_REF_SET, PsdListT, and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::MakeCylinder().
int PsdUtils_MakeFittedBCurve (int num_pts, double ord_pts[], double tol, int closed, cvLispList< PsdItem * > ** result)
Definition at line 2202 of file cv_parasolid_utils.cxx.
References PsdItem::b_item, CV_ERROR, CV_OK, PsdItem::item, Magnitude(), NormVector(), PARAS_BASIS_AXIS_SET, PARAS_BASIS_LOC_SET, PsdListT, and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::MakeApproxCurveLoop().
int PsdUtils_MakeLoftedBSurf (int num_curves, cvLispList< PsdItem * > * geoms[], cvLispList< PsdItem * > ** result, char * name)
Definition at line 2441 of file cv_parasolid_utils.cxx.
References PsdItem::b_item, CV_ERROR, CV_OK, PsdItem::item, PsdListT, PsdUtils_NewItem(), and PsdUtils_TagCaps().
int PsdUtils_MakeLoftedSurf (int num_curves, cvLispList< PsdItem * > * geoms[], cvLispList< PsdItem * > ** result, char * name)
Definition at line 2550 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, edges, PsdItem::item, PsdListT, PsdUtils_NewItem(), and PsdUtils_TagCaps().
Referenced by cvParasolidSolidModel::MakeLoftedSurf().
int PsdUtils_MakePoly2d (cvPolyData * pd, cvLispList< PsdItem * > ** result)
Definition at line 1855 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, NULL, PsdListT, PsdUtils_MakePoly2dPts(), and sys_geom_GetOrderedPts().
Referenced by cvParasolidSolidModel::MakePoly2d().
cvLispList<PsdItem*>* PsdUtils_MakePoly2dPts (int num_pts, double pts[])
Definition at line 1803 of file cv_parasolid_utils.cxx.
References PsdItem::item, NULL, PARAS_VEC_SET, PsdListT, PsdUtils_NewItem(), and sys_geom_ReversePtList().
Referenced by cvParasolidSolidModel::MakePoly2dPts(), and PsdUtils_MakePoly2d().
int PsdUtils_MakeSphere (double r, double ctr[], cvLispList< PsdItem * > ** result)
Definition at line 1609 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, PsdItem::item, PARAS_BASIS_AXIS_SET, PARAS_BASIS_LOC_SET, PARAS_BASIS_REF_SET, PsdListT, and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::MakeSphere().
int PsdUtils_MakeSplinewiseBCurve (int num_pts, double ord_pts[], int closed, cvLispList< PsdItem * > ** result)
Definition at line 2360 of file cv_parasolid_utils.cxx.
References PsdItem::b_item, CV_ERROR, CV_OK, PsdItem::item, NULL, PsdListT, and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::MakeInterpCurveLoop(), and PsdUtils_MakeCap().
int PsdUtils_MakeTorus (double rmaj, double rmin, double ctr[], double axis[], cvLispList< PsdItem * > ** result)
Definition at line 1691 of file cv_parasolid_utils.cxx.
References Cross(), CV_ERROR, CV_OK, PsdItem::item, Magnitude(), NormVector(), PARAS_BASIS_AXIS_SET, PARAS_BASIS_LOC_SET, PARAS_BASIS_REF_SET, PsdListT, and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::MakeTorus().
PsdItem* PsdUtils_NewItem ()
Definition at line 685 of file cv_parasolid_utils.cxx.
References PsdItem::b_item, PsdItem::item, NULL, and PsdItem::src_pd.
Referenced by cvParasolidSolidModel::MakePoly3dSolid(), cvParasolidSolidModel::MakePoly3dSurface(), PsdUtils_CapSurfToSolid(), PsdUtils_DeepCopy(), PsdUtils_DeleteFaces(), PsdUtils_DispatchBoolean(), PsdUtils_Extrude(), PsdUtils_GetAxialIsoparametricCurve(), PsdUtils_MakeBox2d(), PsdUtils_MakeBox3d(), PsdUtils_MakeCap(), PsdUtils_MakeCylinder(), PsdUtils_MakeFittedBCurve(), PsdUtils_MakeLoftedBSurf(), PsdUtils_MakeLoftedSurf(), PsdUtils_MakePoly2dPts(), PsdUtils_MakeSphere(), PsdUtils_MakeSplinewiseBCurve(), PsdUtils_MakeTorus(), PsdUtils_ReadNative(), and PsdUtils_Subtract().
void PsdUtils_PrintInfo ()
Definition at line 539 of file cv_parasolid_utils.cxx.
References PsdUtils_TranslateLogical().
int PsdUtils_ReadNative (char filename[], cvLispList< PsdItem * > ** result, PK_PART_t * firstPart, int * isAssembly)
Definition at line 4688 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, PsdItem::item, NULL, PsdListT, and PsdUtils_NewItem().
Referenced by cvAdapt::Adapt(), cvMeshSimMeshObject::LoadModel(), and cvParasolidSolidModel::ReadNative().
int PsdUtils_Reflect (cvLispList< PsdItem * > * geom, double pos[], double nrm[])
Definition at line 835 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, NormVector(), NULL, PARAS_VEC_SET, and PsdIterT.
Referenced by cvParasolidSolidModel::Reflect().
int PsdUtils_Rotate (cvLispList< PsdItem * > * geom, double axis[], double rad)
Definition at line 748 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, NormVector(), NULL, PARAS_VEC_SET, and PsdIterT.
Referenced by cvParasolidSolidModel::Rotate().
int PsdUtils_Scale (cvLispList< PsdItem * > * geom, double scale)
Definition at line 789 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, NULL, PARAS_VEC_SET, and PsdIterT.
Referenced by cvParasolidSolidModel::Scale().
int PsdUtils_SetFaceAttribute (cvLispList< PsdItem * > * solid, char * attr, int faceid, char * value)
Definition at line 3105 of file cv_parasolid_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by PsdUtils_TagCaps(), and cvParasolidSolidModel::SetFaceAttribute().
void PsdUtils_SetSmpOptions (PsdSmpT smp, PK_BODY_boolean_o_t * opts)
Definition at line 918 of file cv_parasolid_utils.cxx.
References PsdSmpT_All, and PsdSmpT_Invalid.
Referenced by PsdUtils_DispatchBoolean().
int PsdUtils_Subtract (cvLispList< PsdItem * > * geomA, cvLispList< PsdItem * > * geomB, PsdSmpT smp, cvLispList< PsdItem * > ** result)
Definition at line 1097 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, PsdItem::item, NULL, PsdIterT, PsdListT, PsdUtils_DeepCopy(), PsdUtils_Delete(), PsdUtils_DeleteListOnly(), PsdUtils_DispatchBoolean(), and PsdUtils_NewItem().
Referenced by cvParasolidSolidModel::Subtract().
int PsdUtils_TagCaps (cvLispList< PsdItem * > * solid, char * name)
Definition at line 2687 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, faces(), iter, NULL, PsdIterT, and PsdUtils_SetFaceAttribute().
Referenced by PsdUtils_MakeLoftedBSurf(), and PsdUtils_MakeLoftedSurf().
int PsdUtils_Translate (cvLispList< PsdItem * > * geom, double vec[])
Definition at line 702 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, NULL, PARAS_VEC_SET, and PsdIterT.
Referenced by PsdUtils_MakeBox3d(), and cvParasolidSolidModel::Translate().
int PsdUtils_Union (cvLispList< PsdItem * > * geomA, cvLispList< PsdItem * > * geomB, PsdSmpT smp, cvLispList< PsdItem * > ** result)
Definition at line 1190 of file cv_parasolid_utils.cxx.
References PsdUtils_DispatchBoolean().
Referenced by cvParasolidSolidModel::Union().
int PsdUtils_WriteNative (cvLispList< PsdItem * > * geom, int file_version, char filename[])
Definition at line 4807 of file cv_parasolid_utils.cxx.
References CV_ERROR, CV_OK, iter, NULL, and PsdIterT.
Referenced by cvParasolidSolidModel::WriteNative().