simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/cv_geom_init.h File Reference
cv_geom_init.h File Reference
#include "SimVascular.h"
#include "tcl.h"
Functions
CV_DLL_EXPORT int Geom_Init (Tcl_Interp *interp)
Function Documentation
CV_DLL_EXPORT int Geom_Init (Tcl_Interp * interp)
Definition at line 247 of file cv_geom_init.cxx.
References Geom_2dWindingNumCmd(), Geom_AddPointDataCmd(), Geom_AlignProfileCmd(), Geom_AvgPtCmd(), Geom_BBoxCmd(), Geom_CheckSurfaceCmd(), Geom_ClassifyCmd(), Geom_CopyCmd(), Geom_DisorientProfileCmd(), Geom_DividePointDataCmd(), Geom_FindDistanceCmd(), Geom_GetClosedLineRegionCmd(), Geom_GetOrderedPtsCmd(), Geom_GetPolyCentroidCmd(), Geom_IntegrateEnergyCmd(), Geom_IntegrateScalarSurfCmd(), Geom_IntegrateScalarThreshCmd(), Geom_IntegrateSurface2Cmd(), Geom_IntegrateSurfaceCmd(), Geom_InterpolateScalarCmd(), Geom_InterpolateVectorCmd(), Geom_IntersectCmd(), Geom_IntersectWithLineCmd(), Geom_MakePolysConsistentCmd(), Geom_MergePtsCmd(), Geom_MultiplyPointDataCmd(), Geom_NumClosedLineRegionsCmd(), Geom_NumPtsCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_PolygonNormCmd(), Geom_PolysClosedCmd(), Geom_PrintSmallPolysCmd(), Geom_PrintTriStatsCmd(), Geom_ProjectCmd(), Geom_PtInPolyCmd(), Geom_ReduceCmd(), Geom_ReorderPgnCmd(), Geom_ReplacePointDataCmd(), Geom_ReverseAllCellsCmd(), Geom_RmSmallPolysCmd(), Geom_sampleLoopCmd(), Geom_ScaleAvgCmd(), Geom_SplinePtsToPathPlanCmd(), Geom_SubtractCmd(), Geom_SubtractPointDataCmd(), Geom_SurfAreaCmd(), Geom_TranslateCmd(), Geom_UnionCmd(), Geom_Warp3dPtsCmd(), Geom_WriteLinesCmd(), Geom_WriteOrderedPtsCmd(), and NULL.
Referenced by SimVascular_Init().