simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cv_misc_utils.cxx File Reference
cv_misc_utils.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include "cv_misc_utils.h"
Functions
char * PopArg (int *argc, char **argv[])
double FindMachineEpsilon ()
int Compute3dks (double Kg, double Km, double tol, double ks[])
int CountLines (char *filename)
Function Documentation
int Compute3dks (double Kg, double Km, double tol, double ks[])
Definition at line 100 of file cv_misc_utils.cxx.
References CV_ERROR, CV_OK, maximum, minimum, and Sign().
Referenced by cvLevelSetNode::ComputeDoubleDatum(), cvLevelSetVelocitySmooth::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int CountLines (char * filename)
Definition at line 153 of file cv_misc_utils.cxx.
References c, and NULL.
double FindMachineEpsilon ()
Definition at line 66 of file cv_misc_utils.cxx.
References PolyConnList::num.
Referenced by CreateImage(), cvLevelSetStructuredGrid::cvLevelSetStructuredGrid(), cvLevelSetVelocity::cvLevelSetVelocity(), cvSolidModel::cvSolidModel(), dp_mth_norm_frame(), Geom_MergePtsCmd(), PsdUtils_GetCurveGeometry(), PsdUtils_GetWireGeometry(), PsdUtils_MakeCap(), ReadImage(), cvLevelSet::SetDtFactor(), sys_geom_DisorientProfile(), sys_geom_Get2DPgon(), sys_geom_MergePts(), sys_geom_PrintTriStats(), and sys_geom_sampleLoop().
char* PopArg (int * argc, char ** argv[])
Definition at line 42 of file cv_misc_utils.cxx.