simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/cv_integrate_surface.h File Reference
cv_integrate_surface.h File Reference
#include "SimVascular.h"
#include "cvVTK.h"
#include "cvPolyData.h"
Functions
int sys_geom_IntegrateSurface (cvPolyData *src, int tensorType, double *nrm, double *q)
int sys_geom_IntegrateSurface2 (cvPolyData *src, int tensorType, double *q, double *area)
int sys_geom_IntegrateScalarSurf (cvPolyData *src, double *q)
int sys_geom_IntegrateScalarThresh (cvPolyData *src, double wssthresh, double *q, double *a)
int sys_geom_IntegrateEnergy (cvPolyData *src, double rho, double *nrm, double *energy)
Function Documentation
int sys_geom_IntegrateEnergy (cvPolyData * src, double rho, double * nrm, double * energy)
Definition at line 688 of file cv_integrate_surface.cxx.
References CV_ERROR, CV_OK, gdscIntegrateSurfElem(), cvPolyData::GetVtkPolyData(), NULL, VtkUtils_GetAllPolys(), and VtkUtils_GetPointsFloat().
Referenced by Geom_IntegrateEnergyCmd().
int sys_geom_IntegrateScalarSurf (cvPolyData * src, double * q)
Definition at line 418 of file cv_integrate_surface.cxx.
References CV_ERROR, CV_OK, F, cvPolyData::GetVtkPolyData(), and NULL.
Referenced by Geom_IntegrateScalarSurfCmd().
int sys_geom_IntegrateScalarThresh (cvPolyData * src, double wssthresh, double * q, double * a)
Definition at line 553 of file cv_integrate_surface.cxx.
References CV_ERROR, CV_OK, F, cvPolyData::GetVtkPolyData(), and NULL.
Referenced by Geom_IntegrateScalarThreshCmd().
int sys_geom_IntegrateSurface (cvPolyData * src, int tensorType, double * nrm, double * q)
Definition at line 237 of file cv_integrate_surface.cxx.
References CV_ERROR, CV_OK, gdscIntegrateSurfElem(), cvPolyData::GetVtkPolyData(), NULL, VtkUtils_GetAllPolys(), and VtkUtils_GetPointsFloat().
Referenced by Geom_IntegrateSurfaceCmd().
int sys_geom_IntegrateSurface2 (cvPolyData * src, int tensorType, double * q, double * area)
Definition at line 340 of file cv_integrate_surface.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), vtkIntegrateFlowThroughSurface::New(), vtkIntegrateAttributes::New(), and NULL.
Referenced by Geom_IntegrateSurface2Cmd().