simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cv_cgeom.cxx File Reference
cv_cgeom.cxx File Reference
#include "SimVascular.h"
#include "cv_cgeom.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
Macros
#define JPK_PI 3.14159265358979
Functions
void cgeom_VertsCompact (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, int *num_new_verts, vtkFloatingPointType **new_verts)
void cgeom_CompArea (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, vtkFloatingPointType *p_area)
void cgeom_CompVol (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, vtkFloatingPointType *p_vol)
void cgeom_PolysClosed (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, int *closed)
void cgeom_NormsComp (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, vtkFloatingPointType **p_norms)
void cgeom_PolysSmooth (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, int level, vtkFloatingPointType **p_sverts)
void cgeom_FindDegen (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, vtkFloatingPointType tol, int *p_num, int *id)
void cgeom_FixDegen (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, vtkFloatingPointType tol, int *p_num_verts, vtkFloatingPointType **p_verts, int *p_num_polys, vtkIdType **p_conn)
void cgeom_FindVert (int num_cvs, int cv_list[][10], int *vert_stat, int v, int *p_id)
void cgeom_PolysManifold (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, int *manifold)
void cgeom_PolysEdgeTab (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, EdgeList ***p_edge_table)
void cgeom_PolysEdgeConn (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, EdgeList **edge_table, int id, int *p_ncp, int *cp)
void cgeom_CalcAngle (double *point1, double *point2, double *theta)
void cgeom_CalcCentroid (double *listOfPts, int numPts, int numDim, double *centroid)
void cgeom_GetPolyCentroid (int num_verts, vtkFloatingPointType *verts, int num_polys, vtkIdType *conn, double rtn_centroid[])
Macro Definition Documentation
#define JPK_PI 3.14159265358979
Definition at line 46 of file cv_cgeom.cxx.
Referenced by cgeom_CalcAngle().
Function Documentation
void cgeom_CalcAngle (double * point1, double * point2, double * theta)
Definition at line 1247 of file cv_cgeom.cxx.
References JPK_PI.
Referenced by VtkUtils_CalcDirection().
void cgeom_CalcCentroid (double * listOfPts, int numPts, int numDim, double * centroid)
Definition at line 1320 of file cv_cgeom.cxx.
Referenced by VtkUtils_CalcDirection().
void cgeom_CompArea (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, vtkFloatingPointType * p_area)
Definition at line 235 of file cv_cgeom.cxx.
Referenced by sys_geom_SurfArea().
void cgeom_CompVol (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, vtkFloatingPointType * p_vol)
Definition at line 292 of file cv_cgeom.cxx.
void cgeom_FindDegen (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, vtkFloatingPointType tol, int * p_num, int * id)
Definition at line 646 of file cv_cgeom.cxx.
Referenced by sys_geom_PrintSmallPolys(), and sys_geom_RmSmallPolys().
void cgeom_FindVert (int num_cvs, int cv_list[][10], int * vert_stat, int v, int * p_id)
Definition at line 1003 of file cv_cgeom.cxx.
void cgeom_FixDegen (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, vtkFloatingPointType tol, int * p_num_verts, vtkFloatingPointType ** p_verts, int * p_num_polys, vtkIdType ** p_conn)
Definition at line 730 of file cv_cgeom.cxx.
References cgeom_PolysEdgeConn(), cgeom_PolysEdgeTab(), and malloc().
Referenced by sys_geom_RmSmallPolys().
void cgeom_GetPolyCentroid (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, double rtn_centroid[])
Definition at line 1362 of file cv_cgeom.cxx.
Referenced by sys_geom_getPolyCentroid().
void cgeom_NormsComp (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, vtkFloatingPointType ** p_norms)
Definition at line 388 of file cv_cgeom.cxx.
References c, and malloc().
void cgeom_PolysClosed (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, int * closed)
Definition at line 349 of file cv_cgeom.cxx.
References cgeom_PolysEdgeTab(), EdgeList::count, and EdgeList::next.
Referenced by sys_geom_PolysClosed().
void cgeom_PolysEdgeConn (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, EdgeList ** edge_table, int id, int * p_ncp, int * cp)
Definition at line 1150 of file cv_cgeom.cxx.
References EdgeList::count, EdgeList::next, EdgeList::node, and EdgeList::polys.
Referenced by cgeom_FixDegen().
void cgeom_PolysEdgeTab (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, EdgeList *** p_edge_table)
Definition at line 1058 of file cv_cgeom.cxx.
References EdgeList::count, EdgeList::loc, malloc(), EdgeList::next, EdgeList::node, NULL, EdgeList::poly, and EdgeList::polys.
Referenced by cgeom_FixDegen(), cgeom_PolysClosed(), and cgeom_PolysManifold().
void cgeom_PolysManifold (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, int * manifold)
Definition at line 1037 of file cv_cgeom.cxx.
References cgeom_PolysEdgeTab().
void cgeom_PolysSmooth (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, int level, vtkFloatingPointType ** p_sverts)
Definition at line 487 of file cv_cgeom.cxx.
References EdgeVertexList::loc, malloc(), EdgeVertexList::next, EdgeVertexList::node, and NULL.
void cgeom_VertsCompact (int num_verts, vtkFloatingPointType * verts, int num_polys, vtkIdType * conn, int * num_new_verts, vtkFloatingPointType ** new_verts)
Definition at line 56 of file cv_cgeom.cxx.
References free(), _coord_bin_::id, _coord_bin_::link, malloc(), NULL, _coord_bin_::x, _coord_bin_::y, and _coord_bin_::z.