simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/ITK/Util/cv_ITKUtils_init.cxx File Reference
cv_ITKUtils_init.cxx File Reference
#include "SimVascular.h"
#include "cvTCLMacros.h"
#include <stdio.h>
#include <string.h>
#include "cvITKLevelSet.h"
#include "cvLevelSetVelocity.h"
#include "cvRepository.h"
#include "cvSolidModel.h"
#include "cv_misc_utils.h"
#include "cv_arg.h"
#include "itkVersion.h"
#include "cvITKUtils.h"
#include "cv_ITKUtils_init.h"
#include "cv_globals.h"
Functions
static int itkutils_GenerateCircleCmd (CXX_TCL_STDARGS)
C++/TCL bindings for ITK Utils.
static int itkutils_PdToImgCmd (CXX_TCL_STDARGS)
Converts a polydata to a 2D image.
static int itkutils_PdToVolCmd (CXX_TCL_STDARGS)
Converts a 3D polydata to a 3D image volume.
static int itkutils_WriteImageCmd (CXX_TCL_STDARGS)
Write an image to vtk format.
static int itkutils_GradientMagnitudeGaussianCmd (CXX_TCL_STDARGS)
Computer the gradient magnitude of a vtk image, after a gaussian blur.
static int itkutils_FractEdgeProximity3DCmd (CXX_TCL_STDARGS)
int itkutils_Init (Tcl_Interp *interp)
Initializes C++/Tcl bindings.
Function Documentation
int itkutils_FractEdgeProximity3DCmd (CXX_TCL_STDARGS) static
Definition at line 415 of file cv_ITKUtils_init.cxx.
References ARG_GenSyntaxStr(), CVTCLParseTclStrMacro, CVTCLRepositoryExistsMacro, CVTCLTestArgsMacro, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, cvRepository::Register(), REQUIRED, ImgInfo::SetExtent(), ImgInfo::SetMaxValue(), ImgInfo::SetMinValue(), STRING_Type, and STRUCTURED_PTS_T.
static int itkutils_GenerateCircleCmd (CXX_TCL_STDARGS) static
C++/TCL bindings for ITK Utils.
This file provides C++/Tcl bindings for itk UtilsGenerate a polydata cirlce with a specified radius and location
(Requires VTK Only) A more elaborate description... TBD
Definition at line 95 of file cv_ITKUtils_init.cxx.
References ARG_GenSyntaxStr(), CVTCLParseTclStrMacro, CVTCLRepositoryExistsMacro, CVTCLTestArgsMacro, DOUBLE_Type, cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, cvRepositoryData::SetName(), STRING_Type, and cvITKLSUtil::vtkGenerateCircle().
int itkutils_GradientMagnitudeGaussianCmd (CXX_TCL_STDARGS) static
Computer the gradient magnitude of a vtk image, after a gaussian blur.
(Requires VTK and ITK) A more elaborate description... TBD
Definition at line 344 of file cv_ITKUtils_init.cxx.
References ARG_GenSyntaxStr(), CVTCLParseTclStrMacro, CVTCLRepositoryExistsMacro, CVTCLTestArgsMacro, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, cvRepository::Register(), REQUIRED, ImgInfo::SetExtent(), STRING_Type, STRUCTURED_PTS_T, and cvITKLSUtil::vtkGenerateFeatureImage().
int itkutils_Init (Tcl_Interp * interp)
Initializes C++/Tcl bindings.
A more elaborate description... TBD
Definition at line 79 of file cv_ITKUtils_init.cxx.
References CVTCLFunctionInit.
Referenced by SimVascular_Init().
static int itkutils_PdToImgCmd (CXX_TCL_STDARGS) static
Converts a polydata to a 2D image.
(Requires VTK Only) A more elaborate description... TBD
Definition at line 142 of file cv_ITKUtils_init.cxx.
References ARG_GenSyntaxStr(), CVTCLParseTclStrMacro, CVTCLRepositoryExistsMacro, CVTCLTestArgsMacro, cvITKLSUtil::DefaultImgInfo, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, ImgInfo::Print(), cvRepository::Register(), REQUIRED, cvRepositoryData::SetName(), STRING_Type, and cvITKLSUtil::vtkPolyDataTo2DImage().
static int itkutils_PdToVolCmd (CXX_TCL_STDARGS) static
Converts a 3D polydata to a 3D image volume.
(Requires VTK Only) A more elaborate description... TBD
Definition at line 208 of file cv_ITKUtils_init.cxx.
References ARG_GenSyntaxStr(), CVTCLParseTclStrMacro, CVTCLRepositoryExistsMacro, CVTCLTestArgsMacro, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, cvRepositoryData::SetName(), STRING_Type, STRUCTURED_PTS_T, and cvITKLSUtil::vtkPolyDataToVolume().
static int itkutils_WriteImageCmd (CXX_TCL_STDARGS) static
Write an image to vtk format.
(Requires VTK Only) A more elaborate description... TBD
Definition at line 295 of file cv_ITKUtils_init.cxx.
References ARG_GenSyntaxStr(), CVTCLParseTclStrMacro, CVTCLTestArgsMacro, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, REQUIRED, STRING_Type, STRUCTURED_PTS_T, and cvITKLSUtil::WritePerciseVtkImage().