simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cv_vtk_utils.cxx File Reference
cv_vtk_utils.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <assert.h>
#include "cv_vtk_utils.h"
#include "cv_misc_utils.h"
#include "cv_cgeom.h"
Classes
struct PrePt_T
struct PostPt_T
Macros
#define START -1
#define INTERMED 0
#define DEADEND 1
#define CLOSED 2
Functions
static int SomeFalse (int *arr, int sz)
static int FirstFalsePos (int *arr, int sz)
static int SearchComplete (int *state, int stateSz)
static void MarkClosed (int *state, int stateSz)
static void MarkDeadEnd (int *state, int stateSz)
static int GetNextPt (int prev, int curr, int *state, int stateSz, int *lines, int numLines)
static int GetStartPt (int *state, int stateSz)
static int UpdateCells (int *cells, int numCells, vtkIdType **newCells, int *numNewCells)
int VtkUtils_NewVtkPolyData (vtkPolyData **pd, int numPts, vtkFloatingPointType pts[], int numCells, vtkIdType polys[])
int VtkUtils_NewVtkPolyDataLines (vtkPolyData **pd, int numPts, vtkFloatingPointType pts[], int numLines, vtkIdType lines[])
int VtkUtils_FixTopology (vtkPolyData *pd, double tol)
int VtkUtils_GetPoints (vtkPolyData *pd, double **pts, int *numPts)
int VtkUtils_GetPointsFloat (vtkPolyData *pd, vtkFloatingPointType **pts, int *numPts)
int VtkUtils_GetAllLines (vtkPolyData *pd, int *numLines, vtkIdType **lines)
int VtkUtils_GetAllPolys (vtkPolyData *pd, int *numPgns, vtkIdType **pgns)
int VtkUtils_GetLines (vtkPolyData *pd, vtkIdType **lines, int *numLines)
int VtkUtils_GetLinkedLines (vtkIdType *lines, int numLines, int ptIx, int **lineIxs, int *numLineIxs)
static int GetNextPt (int prev, int curr, int *state, int stateSz, vtkIdType *lines, int numLines)
int VtkUtils_FindClosedLineRegions (vtkIdType *lines, int numLines, int numPts, int **startIxs, int *numRegions)
int VtkUtils_GetClosedLineRegion (vtkIdType *lines, int numLines, int startIx, int **lineIds, int *numLineIds)
int VtkUtils_MakePolyDataFromLineIds (double *pts, int numPts, vtkIdType *lines, int *lineIds, int numLineIds, vtkPolyData **pd)
int VtkUtils_MakeShortArray (vtkDataArray *s, int *num, short **dataOut)
int VtkUtils_MakeFloatArray (vtkDataArray *s, int *num, float **dataOut)
vtkPoints * VtkUtils_DeepCopyPoints (vtkPoints *ptsIn)
vtkCellArray * VtkUtils_DeepCopyCells (vtkCellArray *cellsIn)
int VtkUtils_MakePolysConsistent (vtkPolyData *pd)
int VtkUtils_ReverseAllCells (vtkPolyData *pd)
int VtkUtils_GetOrderedPoints (vtkPolyData *inputData, int direction, double **orderedPts, int *numOrderedPts)
int VtkUtils_CalcDirection (double *pts, int numPts, int *currentDirection)
int VtkUtils_ReversePtList (int num, double ptsIn[], double *ptsOut[])
Macro Definition Documentation
#define CLOSED 2
Definition at line 46 of file cv_vtk_utils.cxx.
Referenced by MarkClosed(), and VtkUtils_FindClosedLineRegions().
#define DEADEND 1
Definition at line 45 of file cv_vtk_utils.cxx.
Referenced by MarkDeadEnd(), and VtkUtils_FindClosedLineRegions().
#define INTERMED 0
Definition at line 44 of file cv_vtk_utils.cxx.
Referenced by MarkClosed(), MarkDeadEnd(), SearchComplete(), and VtkUtils_FindClosedLineRegions().
#define START -1
Definition at line 43 of file cv_vtk_utils.cxx.
Referenced by GetStartPt(), SearchComplete(), and VtkUtils_FindClosedLineRegions().
Function Documentation
static int FirstFalsePos (int * arr, int sz) static
Definition at line 1097 of file cv_vtk_utils.cxx.
static int GetNextPt (int prev, int curr, int * state, int stateSz, int * lines, int numLines) static
Referenced by VtkUtils_FindClosedLineRegions().
static int GetNextPt (int prev, int curr, int * state, int stateSz, vtkIdType * lines, int numLines) static
Definition at line 745 of file cv_vtk_utils.cxx.
References NULL, and VtkUtils_GetLinkedLines().
static int GetStartPt (int * state, int stateSz) static
Definition at line 811 of file cv_vtk_utils.cxx.
References START.
Referenced by VtkUtils_FindClosedLineRegions().
static void MarkClosed (int * state, int stateSz) static
Definition at line 711 of file cv_vtk_utils.cxx.
References CLOSED, and INTERMED.
Referenced by VtkUtils_FindClosedLineRegions().
static void MarkDeadEnd (int * state, int stateSz) static
Definition at line 727 of file cv_vtk_utils.cxx.
References DEADEND, and INTERMED.
Referenced by VtkUtils_FindClosedLineRegions().
static int SearchComplete (int * state, int stateSz) static
Definition at line 694 of file cv_vtk_utils.cxx.
References INTERMED, and START.
Referenced by VtkUtils_FindClosedLineRegions().
static int SomeFalse (int * arr, int sz) static
Definition at line 1080 of file cv_vtk_utils.cxx.
static int UpdateCells (int * cells, int numCells, vtkIdType ** newCells, int * numNewCells) static
Definition at line 177 of file cv_vtk_utils.cxx.
References CV_OK.
Referenced by VtkUtils_FixTopology().
int VtkUtils_CalcDirection (double * pts, int numPts, int * currentDirection)
Definition at line 1534 of file cv_vtk_utils.cxx.
References cgeom_CalcAngle(), cgeom_CalcCentroid(), and CV_OK.
Referenced by VtkUtils_GetOrderedPoints().
vtkCellArray* VtkUtils_DeepCopyCells (vtkCellArray * cellsIn)
Definition at line 1202 of file cv_vtk_utils.cxx.
References NULL.
Referenced by sys_geom_DeepCopy(), sys_geom_DisorientProfile(), sys_geom_MakePolysConsistent(), sys_geom_OrientProfile(), and sys_geom_ReverseAllCells().
vtkPoints* VtkUtils_DeepCopyPoints (vtkPoints * ptsIn)
Definition at line 1174 of file cv_vtk_utils.cxx.
References NULL.
Referenced by sys_geom_DeepCopy(), sys_geom_MakePolysConsistent(), and sys_geom_ReverseAllCells().
int VtkUtils_FindClosedLineRegions (vtkIdType * lines, int numLines, int numPts, int ** startIxs, int * numRegions)
Definition at line 831 of file cv_vtk_utils.cxx.
References CLOSED, CV_ERROR, CV_OK, DEADEND, GetNextPt(), GetStartPt(), INTERMED, MarkClosed(), MarkDeadEnd(), SearchComplete(), and START.
Referenced by sys_geom_GetClosedLineRegion(), sys_geom_NumClosedLineRegions(), sys_geom_Pick(), and sys_geom_sampleLoop().
int VtkUtils_FixTopology (vtkPolyData * pd, double tol)
Definition at line 256 of file cv_vtk_utils.cxx.
References CV_ERROR, CV_OK, NULL, PrePt_T::postId, PostPt_T::uncompressedId, UpdateCells(), PrePt_T::x, PostPt_T::x, PrePt_T::y, PostPt_T::y, PrePt_T::z, and PostPt_T::z.
Referenced by sys_geom_Reduce().
int VtkUtils_GetAllLines (vtkPolyData * pd, int * numLines, vtkIdType ** lines)
Definition at line 533 of file cv_vtk_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by VtkUtils_GetOrderedPoints().
int VtkUtils_GetAllPolys (vtkPolyData * pd, int * numPgns, vtkIdType ** pgns)
Definition at line 576 of file cv_vtk_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by sys_geom_getPolyCentroid(), sys_geom_IntegrateEnergy(), sys_geom_IntegrateSurface(), sys_geom_PolysClosed(), sys_geom_PrintSmallPolys(), sys_geom_PrintTriStats(), sys_geom_RmSmallPolys(), and sys_geom_SurfArea().
int VtkUtils_GetClosedLineRegion (vtkIdType * lines, int numLines, int startIx, int ** lineIds, int * numLineIds)
Definition at line 944 of file cv_vtk_utils.cxx.
References c, CV_ERROR, CV_OK, and VtkUtils_GetLinkedLines().
Referenced by sys_geom_2DWindingNum(), sys_geom_GetClosedLineRegion(), sys_geom_Pick(), and VtkUtils_GetOrderedPoints().
int VtkUtils_GetLines (vtkPolyData * pd, vtkIdType ** lines, int * numLines)
Definition at line 614 of file cv_vtk_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by sys_geom_2DWindingNum(), sys_geom_GetClosedLineRegion(), sys_geom_GetOrderedPts(), sys_geom_NumClosedLineRegions(), sys_geom_Pick(), sys_geom_sampleLoop(), and sys_geom_WriteLines().
int VtkUtils_GetLinkedLines (vtkIdType * lines, int numLines, int ptIx, int ** lineIxs, int * numLineIxs)
Definition at line 655 of file cv_vtk_utils.cxx.
Referenced by GetNextPt(), sys_geom_GetOrderedPts(), and VtkUtils_GetClosedLineRegion().
int VtkUtils_GetOrderedPoints (vtkPolyData * inputData, int direction, double ** orderedPts, int * numOrderedPts)
Definition at line 1422 of file cv_vtk_utils.cxx.
References CV_OK, VtkUtils_CalcDirection(), VtkUtils_GetAllLines(), VtkUtils_GetClosedLineRegion(), VtkUtils_GetPoints(), and VtkUtils_ReversePtList().
int VtkUtils_GetPoints (vtkPolyData * pd, double ** pts, int * numPts)
Definition at line 477 of file cv_vtk_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by DiscreteUtils_MakePoly3dSolidVtk(), cvParasolidSolidModel::MakePoly2dPts(), sys_geom_2DWindingNum(), sys_geom_AvgPt(), sys_geom_BBox(), sys_geom_GetClosedLineRegion(), sys_geom_GetOrderedPts(), sys_geom_NumClosedLineRegions(), sys_geom_Pick(), sys_geom_PrintTriStats(), sys_geom_sampleLoop(), sys_geom_WriteLines(), and VtkUtils_GetOrderedPoints().
int VtkUtils_GetPointsFloat (vtkPolyData * pd, vtkFloatingPointType ** pts, int * numPts)
Definition at line 504 of file cv_vtk_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by sys_geom_getPolyCentroid(), sys_geom_IntegrateEnergy(), sys_geom_IntegrateSurface(), sys_geom_PolysClosed(), sys_geom_PrintSmallPolys(), sys_geom_RmSmallPolys(), and sys_geom_SurfArea().
int VtkUtils_MakeFloatArray (vtkDataArray * s, int * num, float ** dataOut)
Definition at line 1145 of file cv_vtk_utils.cxx.
References CV_ERROR, CV_OK, and NULL.
Referenced by LsetVImage_SetImageObjMtd().
int VtkUtils_MakePolyDataFromLineIds (double * pts, int numPts, vtkIdType * lines, int * lineIds, int numLineIds, vtkPolyData ** pd)
Definition at line 1042 of file cv_vtk_utils.cxx.
References CV_OK.
Referenced by sys_geom_GetClosedLineRegion(), and sys_geom_Pick().
int VtkUtils_MakePolysConsistent (vtkPolyData * pd)
Definition at line 1228 of file cv_vtk_utils.cxx.
References CV_OK.
Referenced by sys_geom_MakePolysConsistent().
int VtkUtils_MakeShortArray (vtkDataArray * s, int * num, short ** dataOut)
Definition at line 1115 of file cv_vtk_utils.cxx.
References CV_ERROR, CV_OK, and NULL.
Referenced by LsetVImage_SetImageObjMtd().
int VtkUtils_NewVtkPolyData (vtkPolyData ** pd, int numPts, vtkFloatingPointType pts[], int numCells, vtkIdType polys[])
Definition at line 86 of file cv_vtk_utils.cxx.
References CV_OK.
Referenced by cvParasolidSolidModel::GetFacePolyData(), cvParasolidSolidModel::GetPolyData(), and sys_geom_RmSmallPolys().
int VtkUtils_NewVtkPolyDataLines (vtkPolyData ** pd, int numPts, vtkFloatingPointType pts[], int numLines, vtkIdType lines[])
Definition at line 126 of file cv_vtk_utils.cxx.
References CV_OK.
Referenced by cvParasolidSolidModel::GetPolyData(), sys_geom_ReorderPolygon(), and sys_geom_sampleLoop().
int VtkUtils_ReverseAllCells (vtkPolyData * pd)
Definition at line 1391 of file cv_vtk_utils.cxx.
References CV_OK.
Referenced by sys_geom_Align(), sys_geom_AlignByDist(), and sys_geom_ReverseAllCells().
int VtkUtils_ReversePtList (int num, double ptsIn[], double * ptsOut[])
Definition at line 1616 of file cv_vtk_utils.cxx.
References CV_OK.
Referenced by VtkUtils_GetOrderedPoints().