simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimMeshObject/cv_meshsim_mesh_init.cxx File Reference
cv_meshsim_mesh_init.cxx File Reference
#include "SimVascular.h"
#include "cv_misc_utils.h"
#include "cv_arg.h"
#include "cvMeshSimMeshSystem.h"
#include "cv_meshsim_mesh_init.h"
#include "cv_globals.h"
#include "SimAdvMeshing.h"
#include "MeshSim.h"
#include "SimError.h"
#include "SimErrorCodes.h"
#include "SimMeshingErrorCodes.h"
Functions
int MeshSimMesh_AvailableCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Meshsimmesh_Init (Tcl_Interp *interp)
Function Documentation
int MeshSimMesh_AvailableCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 202 of file cv_meshsim_mesh_init.cxx.
Referenced by Meshsimmesh_Init().
int Meshsimmesh_Init (Tcl_Interp * interp)
Definition at line 110 of file cv_meshsim_mesh_init.cxx.
References CV_ERROR, CV_OK, cvMeshObject::KERNEL_MESHSIM, MeshSimMesh_AvailableCmd(), and NULL.
Referenced by SimVascular_Init().