simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/TetGenMeshObject/cv_tetgenmesh_utils.cxx File Reference
cv_tetgenmesh_utils.cxx File Reference
The implementations of functions in cv_tetgenmesh_utils.
#include "SimVascular.h"
#include "vtkPolyData.h"
#include "vtkPoints.h"
#include "vtkUnstructuredGrid.h"
#include "vtkSmartPointer.h"
#include "vtkDataArray.h"
#include "vtkIntArray.h"
#include "vtkDoubleArray.h"
#include "vtkIdList.h"
#include "vtkCellArray.h"
#include "vtkXMLPolyDataWriter.h"
#include "vtkXMLUnstructuredGridWriter.h"
#include "vtkXMLUnstructuredGridReader.h"
#include "vtkCellData.h"
#include "vtkPointData.h"
#include "vtkCellLocator.h"
#include "vtkGenericCell.h"
#include "vtkConnectivityFilter.h"
#include "vtkDataSetSurfaceFilter.h"
#include "tetgen.h"
#include "cv_polydatasolid_utils.h"
#include "cv_misc_utils.h"
#include <stdlib.h>
Macros
#define MAXPATHLEN 1024
#define gzopen fopen
#define gzprintf fprintf
#define gzFile FILE*
#define gzclose fclose
Functions
int TGenUtils_Init ()
int TGenUtils_ConvertToTetGen (tetgenio *inmesh, vtkPolyData *polydatasolid, int meshsizingfunction, vtkDoubleArray *meshSizingFunction, int useBoundary, std::string markerListArrayName, double maxEdgeSize)
Takes vtkPolyData and turns it into TetGen data structures.
int TGenUtils_ConvertToVTK (tetgenio *outmesh, vtkUnstructuredGrid *volumemesh, vtkPolyData *surfacemesh, int *modelRegions, int getBoundary)
Takes tetgenio and turns it into an output vtkPolyData and vtkUnstructuredGrid.
int TGenUtils_WriteVTU (char *filename, vtkUnstructuredGrid *UGrid)
int TGenUtils_WriteVTP (char *filename, vtkPolyData *PData)
int TGenUtils_GetFacePolyData (int id, vtkPolyData *mesh, vtkPolyData *face)
Based on Scalars Defined by the GetBoundaryFaces filter, separate into face VTKs.
int TGenUtils_writeDiffAdj (vtkUnstructuredGrid *volumemesh)
This is the new way to write and adjacency file based on the mesh.
int TGenUtils_SetRefinementSphere (vtkPolyData *polydatasolid, std::string sizingFunctionArrayName, double size, double radius, double *center, int secondarray)
computes the distance between each point on surface and center
int TGenUtils_SetSizeFunctionArray (vtkPolyData *polydatasolid, std::string sizingFunctionArrayName, double size, char *functionname)
computes the distance between each point on surface and center
int TGenUtils_LoadMesh (char *filename, vtkUnstructuredGrid *result)
Function to load in a vtkUnstructuredGrid.
int TGenUtils_ResetOriginalRegions (vtkPolyData *newgeom, vtkPolyData *originalgeom, std::string newName, std::string originalName)
int TGenUtils_CheckSurfaceMesh (vtkPolyData *pd, int boundarylayer)
Function to load in a vtkUnstructuredGrid.
Detailed Description
The implementations of functions in cv_tetgenmesh_utils.
Author
Adam Updegrove
updeg.nosp@m.a2@g.nosp@m.mail..nosp@m.com
UC Berkeley
shaddenlab.berkeley.edu
Definition in file cv_tetgenmesh_utils.cxx.
Macro Definition Documentation
#define gzclose fclose
Definition at line 76 of file cv_tetgenmesh_utils.cxx.
Referenced by TGenUtils_writeDiffAdj().
#define gzFile FILE*
Definition at line 75 of file cv_tetgenmesh_utils.cxx.
#define gzopen fopen
Definition at line 73 of file cv_tetgenmesh_utils.cxx.
Referenced by TGenUtils_writeDiffAdj().
#define gzprintf fprintf
Definition at line 74 of file cv_tetgenmesh_utils.cxx.
Referenced by TGenUtils_writeDiffAdj().
#define MAXPATHLEN 1024
Definition at line 67 of file cv_tetgenmesh_utils.cxx.
Referenced by TGenUtils_writeDiffAdj().
Function Documentation
int TGenUtils_CheckSurfaceMesh (vtkPolyData * pd, int boundarylayer)
Function to load in a vtkUnstructuredGrid.
Note
This is only used by LoadMesh in vtkTetGenMeshObject
Definition at line 1076 of file cv_tetgenmesh_utils.cxx.
References CV_ERROR, and CV_OK.
int TGenUtils_ConvertToTetGen (tetgenio * inmesh, vtkPolyData * polydatasolid, int meshsizingfunction, vtkDoubleArray * meshSizingFunction, int useBoundary, std::string markerListArrayName, double maxEdgeSize)
Takes vtkPolyData and turns it into TetGen data structures.
Parameters
*inmesh tetgenio structure in which to hold the input surface
*polydatasolid the solid in which to take the discrete points from in order to form the mesh to put into TetGen
Returns
CV_OK if function completes properly
Definition at line 99 of file cv_tetgenmesh_utils.cxx.
References CV_ERROR, CV_OK, NULL, and PlyDtaUtils_PDCheckArrayName().
Referenced by cvTetGenMeshObject::NewMesh().
int TGenUtils_ConvertToVTK (tetgenio * outmesh, vtkUnstructuredGrid * volumemesh, vtkPolyData * surfacemesh, int * modelRegions, int getBoundary)
Takes tetgenio and turns it into an output vtkPolyData and vtkUnstructuredGrid.
Parameters
*outmesh tetgen structure for which the mesh is output
*volumemesh vtkPolyData on which to save the surface mesh
*surfacemesh vtkUnstructuredGrid on which to save the volume mesh
Returns
CV_OK if function completes properly
Definition at line 222 of file cv_tetgenmesh_utils.cxx.
References CV_OK, faces(), and NULL.
Referenced by cvTetGenMeshObject::WriteMesh().
int TGenUtils_GetFacePolyData (int id, vtkPolyData * mesh, vtkPolyData * face)
Based on Scalars Defined by the GetBoundaryFaces filter, separate into face VTKs.
Parameters
*mesh vtkPolyData on which to extract the face from
*face vtkPolyData on which to set the face PolyData
angle double that specifies the extraction angle. Any faces
id int that specifies the face id to extract
Returns
CV_OK if function completes properly
Note
There is another method to do this that does not retain id information. It may be faster, but doesn't reatain info
Definition at line 481 of file cv_tetgenmesh_utils.cxx.
References CV_ERROR, CV_OK, and PlyDtaUtils_PDCheckArrayName().
int TGenUtils_Init ()
Definition at line 83 of file cv_tetgenmesh_utils.cxx.
References CV_OK.
Referenced by Tetgenmesh_Init().
int TGenUtils_LoadMesh (char * filename, vtkUnstructuredGrid * result)
Function to load in a vtkUnstructuredGrid.
Note
This is only used by LoadMesh in vtkTetGenMeshObject
Definition at line 882 of file cv_tetgenmesh_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by cvTetGenMeshObject::LoadMesh().
int TGenUtils_ResetOriginalRegions (vtkPolyData * newgeom, vtkPolyData * originalgeom, std::string newName, std::string originalName)
Definition at line 905 of file cv_tetgenmesh_utils.cxx.
References CV_ERROR, CV_OK, and PlyDtaUtils_PDCheckArrayName().
int TGenUtils_SetRefinementSphere (vtkPolyData * polydatasolid, std::string sizingFunctionArrayName, double size, double radius, double * center, int secondarray)
computes the distance between each point on surface and center
of sphere. Then, if inside radius, the meshsizing function at the is set to the reduced size,
Parameters
size This is the smaller refined of the edges within sphere region.
radius This is the radius of the refinement sphere.
center This is the center of the refinement sphere.
Returns
CV_OK if function completes properly
Definition at line 741 of file cv_tetgenmesh_utils.cxx.
References CV_ERROR, CV_OK, and PlyDtaUtils_PDCheckArrayName().
Referenced by cvTetGenMeshObject::SetSphereRefinement().
int TGenUtils_SetSizeFunctionArray (vtkPolyData * polydatasolid, std::string sizingFunctionArrayName, double size, char * functionname)
computes the distance between each point on surface and center
of sphere. Then, if inside radius, the meshsizing function at the is set to the reduced size,
Parameters
size This is the smaller refined of the edges within sphere region.
radius This is the radius of the refinement sphere.
center This is the center of the refinement sphere.
Returns
CV_OK if function completes properly
Definition at line 812 of file cv_tetgenmesh_utils.cxx.
References CV_ERROR, CV_OK, and PlyDtaUtils_PDCheckArrayName().
Referenced by cvTetGenMeshObject::SetSizeFunctionBasedMesh().
int TGenUtils_writeDiffAdj (vtkUnstructuredGrid * volumemesh)
This is the new way to write and adjacency file based on the mesh.
Note
now implemented in the presolver as new command
Definition at line 628 of file cv_tetgenmesh_utils.cxx.
References CV_ERROR, CV_OK, filename, gzclose, gzopen, gzprintf, MAXPATHLEN, NULL, and PlyDtaUtils_UGCheckArrayName().
int TGenUtils_WriteVTP (char * filename, vtkPolyData * PData)
Definition at line 446 of file cv_tetgenmesh_utils.cxx.
References CV_OK.
int TGenUtils_WriteVTU (char * filename, vtkUnstructuredGrid * UGrid)
Definition at line 424 of file cv_tetgenmesh_utils.cxx.
References CV_OK.