simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/Adaptor/Adapt/cvAdaptHelp.h File Reference
cvAdaptHelp.h File Reference
#include "MeshSim.h"
Functions
pPList R_verticesLeft (pRegion region)
double Entity_shapeFunction (pEntity entity, pEntity element, int p, int ith, double *L)
double Bn (int i, int j, int k, double r, double s, double t)
double Bn_2ndChunk (int i, int j, int k, double r, double s, double t)
double Bn_3rdChunk (int i, int j, int k, double r, double s, double t)
double Bn_4thChunk (int i, int j, int k, double r, double s, double t)
double En (int ip, double r, double s)
double Fn (int i, int j, double r, double s)
double V_blendOnEntity (pVertex v, pEntity e, double *L)
double V_blendIndexed (int i, double *L)
double V_blendIndexedOnEdge (int i, double *L)
double E_blendOnFace (pEdge edge, pFace face, double *L)
double F_edgeBlendTri (int index[2], double *L)
double F_edgeBlendQuad (int *index, double *L)
double E_blendOnRegion (pEdge edge, pRegion region, double *L)
double R_edgeBlendTet (int index[2], double *L)
double F_blendOnRegion (pFace face, pRegion region, double *L)
int V_index (pVertex v, pEntity ent, int *index)
int E_index (pEdge e, pEntity ent, int *index)
int F_index (pFace face, pEntity ent, int *index)
double E_modeShape (int p, double *L)
double F_modeShapeTri (int p, int i, double *L)
double F_modeShapeQuad (int p, int i, double *L)
double R_modeShapeTet (int p, int i, double *L)
double R_modeShapeHex (int p, int i, double *L)
Function Documentation
double Bn (int i, int j, int k, double r, double s, double t)
Definition at line 45 of file cvAdaptHelpers.cxx.
References Bn_2ndChunk().
Referenced by R_modeShapeTet().
double Bn_2ndChunk (int i, int j, int k, double r, double s, double t)
Definition at line 991 of file cvAdaptHelpers.cxx.
References Bn_3rdChunk().
Referenced by Bn().
double Bn_3rdChunk (int i, int j, int k, double r, double s, double t)
Definition at line 2008 of file cvAdaptHelpers.cxx.
References Bn_4thChunk().
Referenced by Bn_2ndChunk().
double Bn_4thChunk (int i, int j, int k, double r, double s, double t)
Definition at line 3411 of file cvAdaptHelpers.cxx.
Referenced by Bn_3rdChunk().
double E_blendOnFace (pEdge edge, pFace face, double * L)
Definition at line 292 of file cvAdaptSF.cxx.
References E_index(), F_edgeBlendQuad(), and F_edgeBlendTri().
double E_blendOnRegion (pEdge edge, pRegion region, double * L)
Definition at line 316 of file cvAdaptSF.cxx.
References E_index(), nfaces, and R_edgeBlendTet().
int E_index (pEdge e, pEntity ent, int * index)
Definition at line 152 of file cvAdaptSF.cxx.
Referenced by E_blendOnFace(), E_blendOnRegion(), and Entity_shapeFunction().
double E_modeShape (int p, double * L)
Definition at line 5529 of file cvAdaptHelpers.cxx.
References En().
Referenced by Entity_shapeFunction().
double En (int ip, double r, double s)
Definition at line 4191 of file cvAdaptHelpers.cxx.
Referenced by E_modeShape().
double Entity_shapeFunction (pEntity entity, pEntity element, int p, int ith, double * L)
Definition at line 39 of file cvAdaptSF.cxx.
References E_index(), E_modeShape(), F_edgeBlendQuad(), F_edgeBlendTri(), F_index(), F_modeShapeQuad(), F_modeShapeTri(), nfaces, R_edgeBlendTet(), R_modeShapeHex(), R_modeShapeTet(), and V_blendOnEntity().
Referenced by cvAdaptCore::InterpolateSolution().
double F_blendOnRegion (pFace face, pRegion region, double * L)
Definition at line 333 of file cvAdaptSF.cxx.
References F_index(), and nfaces.
double F_edgeBlendQuad (int * index, double * L)
Definition at line 312 of file cvAdaptSF.cxx.
Referenced by E_blendOnFace(), and Entity_shapeFunction().
double F_edgeBlendTri (int index[2], double * L)
Definition at line 308 of file cvAdaptSF.cxx.
Referenced by E_blendOnFace(), and Entity_shapeFunction().
int F_index (pFace face, pEntity ent, int * index)
Definition at line 205 of file cvAdaptSF.cxx.
Referenced by Entity_shapeFunction(), and F_blendOnRegion().
double F_modeShapeQuad (int p, int i, double * L)
Definition at line 5567 of file cvAdaptHelpers.cxx.
Referenced by Entity_shapeFunction().
double F_modeShapeTri (int p, int i, double * L)
Definition at line 5538 of file cvAdaptHelpers.cxx.
References alpha, and Fn().
Referenced by Entity_shapeFunction().
double Fn (int i, int j, double r, double s)
Definition at line 4371 of file cvAdaptHelpers.cxx.
Referenced by F_modeShapeTri().
double R_edgeBlendTet (int index[2], double * L)
Definition at line 329 of file cvAdaptSF.cxx.
Referenced by E_blendOnRegion(), and Entity_shapeFunction().
double R_modeShapeHex (int p, int i, double * L)
Definition at line 5606 of file cvAdaptHelpers.cxx.
Referenced by Entity_shapeFunction().
double R_modeShapeTet (int p, int i, double * L)
Definition at line 5572 of file cvAdaptHelpers.cxx.
References alpha, Bn(), and gamma.
Referenced by Entity_shapeFunction().
pPList R_verticesLeft (pRegion region)
double V_blendIndexed (int i, double * L)
Definition at line 281 of file cvAdaptSF.cxx.
Referenced by V_blendOnEntity().
double V_blendIndexedOnEdge (int i, double * L)
Definition at line 285 of file cvAdaptSF.cxx.
Referenced by V_blendOnEntity().
double V_blendOnEntity (pVertex v, pEntity e, double * L)
Definition at line 267 of file cvAdaptSF.cxx.
References V_blendIndexed(), V_blendIndexedOnEdge(), and V_index().
Referenced by Entity_shapeFunction().
int V_index (pVertex v, pEntity ent, int * index)
Definition at line 113 of file cvAdaptSF.cxx.
Referenced by V_blendOnEntity().