simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimMeshObject/cvMeshSimMeshObject.cxx File Reference
cvMeshSimMeshObject.cxx File Reference
#include "SimVascular.h"
#include "cvMeshSimMeshObject.h"
#include "cvSolidModel.h"
#include "cv_misc_utils.h"
#include "cv_sys_geom.h"
#include "vtkGeometryFilter.h"
#include "vtkCleanPolyData.h"
Functions
int M_writeSTS (pMesh mesh, char *fname, char *mname)
Function Documentation
int M_writeSTS (pMesh mesh, char * fname, char * mname)
Definition at line 66 of file stats.cxx.
References CV_ERROR, CV_OK, dhd145, dhd160, dhd170, M_PI, MY_MESHSIM_VERTEX_ORDERING, scorecXYZ_aspectRatio2(), scorecXYZ_dihedral(), scorecXYZ_edgLenRatio2(), scorecXYZ_rbyR2(), and scorecXYZ_shape().
Referenced by cvMeshSimMeshObject::WriteStats().