simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/SolverIO/cvSolverIO.cxx File Reference
cvSolverIO.cxx File Reference
#include <string>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "cvSolverIO.h"
#include <ctype.h>
#include <vector>
#include <iostream>
Macros
#define INT 1
#define FLOAT 2
#define DOUBLE 3
#define swap_char(A, B) { ucTmp = A; A = B ; B = ucTmp; }
#define FLOWSOLVER_MAGIC_NUMBER 362436
Functions
int openfile_ (const char *filename, const char *mode, int *fileDescriptor)
void closefile_ (int *fileDescriptor, const char *mode)
void readheader_ (int *fileDescriptor, const char *keyphrase, void *valueArray, int *nItems, const char *datatype, const char *iotype)
void readdatablock_ (int *fileDescriptor, const char *keyphrase, void *valueArray, int *nItems, const char *datatype, const char *iotype)
void writeheader_ (int *fileDescriptor, const char *keyphrase, void *valueArray, int *nItems, int *ndataItems, const char *datatype, const char *iotype)
void writedatablock_ (int *fileDescriptor, const char *keyphrase, void *valueArray, int *nItems, const char *datatype, const char *iotype)
void writestring_ (int *fileDescriptor, const char *string)
void Gather_Headers (int *fileDescriptor, std::vector< std::string > &headers)
Variables
cvsolverIO ** cvsolverIOfp = NULL
Macro Definition Documentation
#define DOUBLE 3
Definition at line 49 of file cvSolverIO.cxx.
#define FLOAT 2
Definition at line 48 of file cvSolverIO.cxx.
#define FLOWSOLVER_MAGIC_NUMBER 362436
Definition at line 52 of file cvSolverIO.cxx.
#define INT 1
Definition at line 47 of file cvSolverIO.cxx.
#define swap_char (A, B) { ucTmp = A; A = B ; B = ucTmp; }
Definition at line 50 of file cvSolverIO.cxx.
Function Documentation
void closefile_ (int * fileDescriptor, const char * mode)
Definition at line 569 of file cvSolverIO.cxx.
References cvsolverIOfp, and NULL.
Referenced by cvAdaptCore::attachVPSoln(), cmd_append_displacements(), PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), PostSolver::ParseRestartFile(), Partition_Problem(), PostSolver::QueryNumberOfProcessors(), PostSolver::QueryNumberOfSolutionVariables(), readArrayFromFile(), cvAdaptCore::readArrayFromFile(), PostSolver::ReadConnectivity(), readlesrestart_(), readParametersFromFile(), cvAdaptCore::readParametersFromFile(), readRESTARTDAT(), savelesrestart_(), Write_Displ(), Write_Error(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().
void Gather_Headers (int * fileDescriptor, std::vector< std::string > & headers)
Definition at line 637 of file cvSolverIO.cxx.
References CVSOLVER_IO_OK, and cvsolverIOfp.
Referenced by Partition_Problem().
int openfile_ (const char * filename, const char * mode, int * fileDescriptor)
Definition at line 533 of file cvSolverIO.cxx.
References CVSOLVER_IO_ERROR, CVSOLVER_IO_OK, cvsolverIOfp, and NULL.
Referenced by cvAdaptCore::attachVPSoln(), cmd_append_displacements(), PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), PostSolver::ParseRestartFile(), Partition_Problem(), PostSolver::QueryNumberOfProcessors(), PostSolver::QueryNumberOfSolutionVariables(), readArrayFromFile(), cvAdaptCore::readArrayFromFile(), PostSolver::ReadConnectivity(), readlesrestart_(), readParametersFromFile(), cvAdaptCore::readParametersFromFile(), readRESTARTDAT(), cvAdaptCore::restart(), savelesrestart_(), Write_Displ(), Write_Error(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().
void readdatablock_ (int * fileDescriptor, const char * keyphrase, void * valueArray, int * nItems, const char * datatype, const char * iotype)
Definition at line 590 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by cvAdaptCore::attachVPSoln(), PostSolver::ParseRestartFile(), Partition_Problem(), readArrayFromFile(), cvAdaptCore::readArrayFromFile(), PostSolver::ReadConnectivity(), readlesrestart_(), readRESTARTDAT(), and cvAdaptCore::restart().
void readheader_ (int * fileDescriptor, const char * keyphrase, void * valueArray, int * nItems, const char * datatype, const char * iotype)
Definition at line 578 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by cvAdaptCore::attachVPSoln(), PostSolver::ParseRestartFile(), Partition_Problem(), PostSolver::QueryNumberOfProcessors(), PostSolver::QueryNumberOfSolutionVariables(), readArrayFromFile(), cvAdaptCore::readArrayFromFile(), PostSolver::ReadConnectivity(), readlesrestart_(), readParametersFromFile(), cvAdaptCore::readParametersFromFile(), readRESTARTDAT(), and cvAdaptCore::restart().
void writedatablock_ (int * fileDescriptor, const char * keyphrase, void * valueArray, int * nItems, const char * datatype, const char * iotype)
Definition at line 617 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by cmd_append_displacements(), PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), Partition_Problem(), savelesrestart_(), Write_Displ(), Write_Error(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeCommonHeader(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().
void writeheader_ (int * fileDescriptor, const char * keyphrase, void * valueArray, int * nItems, int * ndataItems, const char * datatype, const char * iotype)
Definition at line 602 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by cmd_append_displacements(), PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), Partition_Problem(), savelesrestart_(), Write_Displ(), Write_Error(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeCommonHeader(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().
void writestring_ (int * fileDescriptor, const char * string)
Definition at line 629 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), Partition_Problem(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeCommonHeader(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().
Variable Documentation
cvsolverIO** cvsolverIOfp = NULL
Definition at line 54 of file cvSolverIO.cxx.
Referenced by closefile_(), Gather_Headers(), openfile_(), readdatablock_(), readheader_(), writedatablock_(), writeheader_(), and writestring_().