simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/SolverIO/cvSolverIO.h File Reference
cvSolverIO.h File Reference
#include <stdio.h>
#include "cvFlowsolverOptions.h"
#include <stdlib.h>
Macros
#define CVSOLVER_IO_OK 1
#define CVSOLVER_IO_ERROR 0
#define gzopen fopen
#define gzprintf fprintf
#define gzFile FILE*
#define gzclose fclose
#define gzeof feof
#define gzclearerr clearerr
#define gzflush(p1, p2) fflush((p1))
#define gzrewind rewind
#define gzread(p1, p2, p3) fread((p2),(p3),1,(p1))
#define gzwrite(p1, p2, p3) fwrite((p2),(p3),1,(p1))
#define gzseek fseek
#define gzgets(p1, p2, p3) fgets((p2),(p3),(p1))
#define Z_NULL NULL
Functions
int openfile_ (const char *filename, const char *mode, int *fileDescriptor)
void closefile_ (int *fileDescriptor, const char *mode)
void readheader_ (int *fileDescriptor, const char *keyphrase, void *valueArray, int *nItems, const char *datatype, const char *iotype)
void readdatablock_ (int *fileDescriptor, const char *keyphrase, void *valueArray, int *nItems, const char *datatype, const char *iotype)
void writeheader_ (int *fileDescriptor, const char *keyphrase, void *valueArray, int *nItems, int *ndataItems, const char *datatype, const char *iotype)
void writedatablock_ (int *fileDescriptor, const char *keyphrase, void *valueArray, int *nItems, const char *datatype, const char *iotype)
void writestring_ (int *fileDescriptor, const char *string)
Macro Definition Documentation
#define CVSOLVER_IO_ERROR 0
Definition at line 41 of file cvSolverIO.h.
Referenced by openfile_(), Write_Displ(), Write_Error(), and Write_Restart().
#define CVSOLVER_IO_OK 1
Definition at line 40 of file cvSolverIO.h.
Referenced by PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), Gather_Headers(), openfile_(), PostSolver::ParseRestartFile(), PostSolver::QueryNumberOfProcessors(), PostSolver::QueryNumberOfSolutionVariables(), and PostSolver::ReadConnectivity().
#define gzclearerr clearerr
Definition at line 56 of file cvSolverIO.h.
#define gzclose fclose
Definition at line 54 of file cvSolverIO.h.
#define gzeof feof
Definition at line 55 of file cvSolverIO.h.
#define gzFile FILE*
Definition at line 53 of file cvSolverIO.h.
#define gzflush (p1, p2) fflush((p1))
Definition at line 57 of file cvSolverIO.h.
#define gzgets (p1, p2, p3) fgets((p2),(p3),(p1))
Definition at line 62 of file cvSolverIO.h.
#define gzopen fopen
Definition at line 51 of file cvSolverIO.h.
#define gzprintf fprintf
Definition at line 52 of file cvSolverIO.h.
#define gzread (p1, p2, p3) fread((p2),(p3),1,(p1))
Definition at line 59 of file cvSolverIO.h.
Referenced by cv_zlib_gzgetc(), cv_zlib_gzgets(), cv_zlib_gzseek(), gz_uncompress(), and test_gzio().
#define gzrewind rewind
Definition at line 58 of file cvSolverIO.h.
Referenced by cv_zlib_gzseek().
#define gzseek fseek
Definition at line 61 of file cvSolverIO.h.
Referenced by cv_zlib_gztell(), and test_gzio().
#define gzwrite (p1, p2, p3) fwrite((p2),(p3),1,(p1))
Definition at line 60 of file cvSolverIO.h.
Referenced by cv_zlib_gzprintf(), cv_zlib_gzputc(), cv_zlib_gzputs(), cv_zlib_gzseek(), and gz_compress().
#define Z_NULL NULL
Definition at line 63 of file cvSolverIO.h.
Function Documentation
void closefile_ (int * fileDescriptor, const char * mode)
Definition at line 569 of file cvSolverIO.cxx.
References cvsolverIOfp, and NULL.
Referenced by cvAdaptCore::attachVPSoln(), cmd_append_displacements(), PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), PostSolver::ParseRestartFile(), Partition_Problem(), PostSolver::QueryNumberOfProcessors(), PostSolver::QueryNumberOfSolutionVariables(), readArrayFromFile(), cvAdaptCore::readArrayFromFile(), PostSolver::ReadConnectivity(), readlesrestart_(), readParametersFromFile(), cvAdaptCore::readParametersFromFile(), readRESTARTDAT(), savelesrestart_(), Write_Displ(), Write_Error(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().
int openfile_ (const char * filename, const char * mode, int * fileDescriptor)
Definition at line 533 of file cvSolverIO.cxx.
References CVSOLVER_IO_ERROR, CVSOLVER_IO_OK, cvsolverIOfp, and NULL.
Referenced by cvAdaptCore::attachVPSoln(), cmd_append_displacements(), PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), PostSolver::ParseRestartFile(), Partition_Problem(), PostSolver::QueryNumberOfProcessors(), PostSolver::QueryNumberOfSolutionVariables(), readArrayFromFile(), cvAdaptCore::readArrayFromFile(), PostSolver::ReadConnectivity(), readlesrestart_(), readParametersFromFile(), cvAdaptCore::readParametersFromFile(), readRESTARTDAT(), cvAdaptCore::restart(), savelesrestart_(), Write_Displ(), Write_Error(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().
void readdatablock_ (int * fileDescriptor, const char * keyphrase, void * valueArray, int * nItems, const char * datatype, const char * iotype)
Definition at line 590 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by cvAdaptCore::attachVPSoln(), PostSolver::ParseRestartFile(), Partition_Problem(), readArrayFromFile(), cvAdaptCore::readArrayFromFile(), PostSolver::ReadConnectivity(), readlesrestart_(), readRESTARTDAT(), and cvAdaptCore::restart().
void readheader_ (int * fileDescriptor, const char * keyphrase, void * valueArray, int * nItems, const char * datatype, const char * iotype)
Definition at line 578 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by cvAdaptCore::attachVPSoln(), PostSolver::ParseRestartFile(), Partition_Problem(), PostSolver::QueryNumberOfProcessors(), PostSolver::QueryNumberOfSolutionVariables(), readArrayFromFile(), cvAdaptCore::readArrayFromFile(), PostSolver::ReadConnectivity(), readlesrestart_(), readParametersFromFile(), cvAdaptCore::readParametersFromFile(), readRESTARTDAT(), and cvAdaptCore::restart().
void writedatablock_ (int * fileDescriptor, const char * keyphrase, void * valueArray, int * nItems, const char * datatype, const char * iotype)
Definition at line 617 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by cmd_append_displacements(), PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), Partition_Problem(), savelesrestart_(), Write_Displ(), Write_Error(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeCommonHeader(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().
void writeheader_ (int * fileDescriptor, const char * keyphrase, void * valueArray, int * nItems, int * ndataItems, const char * datatype, const char * iotype)
Definition at line 602 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by cmd_append_displacements(), PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), Partition_Problem(), savelesrestart_(), Write_Displ(), Write_Error(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeCommonHeader(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().
void writestring_ (int * fileDescriptor, const char * string)
Definition at line 629 of file cvSolverIO.cxx.
References cvsolverIOfp.
Referenced by PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), Partition_Problem(), Write_Restart(), writeArrayToFile(), cvAdaptCore::writeArrayToFile(), writeCommonHeader(), writeGEOMBCDAT(), writeRESTARTDAT(), and cvAdaptCore::writeRestartHessians().