simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PreSolver/displacements_var_prop.cxx File Reference
displacements_var_prop.cxx File Reference
#include "cvFlowsolverOptions.h"
#include <stdlib.h>
#include <math.h>
#include "cmd.h"
Classes
struct Kentry
Macros
#define SPARSE_OFFSET 1
Functions
int StanfordSolveSparseMatrix (Kentry *Kentries, double *b, int numUniqueEntries, int size, double *soln)
int stiffnessmatrix (double Evw, double nuvw, double thickness, double pressure, double kcons, double x1[3], double x2[3], double x3[3], double Kglobal9[9][9], double fglobal9[9])
void siftDownKentries (Kentry Kentries[], int root, int bottom, int array_size)
void deleteKentries (Kentry *Kentries)
int STANNSPCG (int *n, int *ndim, double *coef, int *jcoef1, int *jcoef2, double *rhs, double *u)
int StanfordIterativeSolve (Kentry *Kentries, double *b, int numUniqueEntries, int size, double *soln)
int calcInitDisplacements_var_prop (double Evw, double nuvw, double thickness, double pressure, double kcons, int use_direct_solve)
Variables
int DisplacementNumElements_
int * DisplacementConn_ [3]
int DisplacementNumNodes_
int * DisplacementNodeMap_
double * DisplacementSolution_
double * ThicknessSolution_
double * EvwSolution_
int * iBC_
int numNodes_
double * nodes_
Macro Definition Documentation
#define SPARSE_OFFSET 1
Definition at line 52 of file displacements_var_prop.cxx.
Referenced by calcInitDisplacements_var_prop().
Function Documentation
int calcInitDisplacements_var_prop (double Evw, double nuvw, double thickness, double pressure, double kcons, int use_direct_solve)
Definition at line 111 of file displacements_var_prop.cxx.
References Kentry::col, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, DisplacementSolution_, EvwSolution_, iBC_, nodes_, NULL, numNodes_, Kentry::row, siftDownKentries(), SPARSE_OFFSET, StanfordIterativeSolve(), StanfordSolveSparseMatrix(), stddbg, stiffnessmatrix(), ThicknessSolution_, and Kentry::value.
void deleteKentries (Kentry * Kentries)
Definition at line 564 of file displacements.cxx.
Referenced by StanfordIterativeSolve().
void siftDownKentries (Kentry Kentries[], int root, int bottom, int array_size)
Definition at line 520 of file displacements.cxx.
Referenced by calcInitDisplacements_var_prop().
int StanfordIterativeSolve (Kentry * Kentries, double * b, int numUniqueEntries, int size, double * soln)
Definition at line 575 of file displacements.cxx.
References Kentry::col, CV_ERROR, CV_OK, debugprint(), deleteKentries(), malloc(), Kentry::row, SPARSE_OFFSET, STANNSPCG, stddbg, and Kentry::value.
Referenced by calcInitDisplacements(), and calcInitDisplacements_var_prop().
int StanfordSolveSparseMatrix (Kentry * Kentries, double * b, int numUniqueEntries, int size, double * soln)
Referenced by calcInitDisplacements_var_prop().
int STANNSPCG (int * n, int * ndim, double * coef, int * jcoef1, int * jcoef2, double * rhs, double * u)
int stiffnessmatrix (double Evw, double nuvw, double thickness, double pressure, double kcons, double x1[3], double x2[3], double x3[3], double Kglobal9[9][9], double fglobal9[9])
Definition at line 145 of file displacements.cxx.
References Cross(), Mat3Vec(), Norm(), SubVec(), and T.
Referenced by calcInitDisplacements(), and calcInitDisplacements_var_prop().
Variable Documentation
int* DisplacementConn_[3]
Definition at line 83 of file supre.cxx.
Referenced by calcInitDisplacements_var_prop().
int* DisplacementNodeMap_
Definition at line 85 of file supre.cxx.
Referenced by calcInitDisplacements_var_prop().
int DisplacementNumElements_
Definition at line 82 of file supre.cxx.
Referenced by calcInitDisplacements_var_prop().
int DisplacementNumNodes_
Definition at line 84 of file supre.cxx.
Referenced by calcInitDisplacements_var_prop().
double* DisplacementSolution_
Definition at line 86 of file supre.cxx.
Referenced by calcInitDisplacements_var_prop().
double* EvwSolution_
Referenced by calcInitDisplacements_var_prop().
int* iBC_
Definition at line 65 of file supre.cxx.
Referenced by calcInitDisplacements_var_prop().
double* nodes_
Definition at line 57 of file supre.cxx.
Referenced by calcInitDisplacements_var_prop().
int numNodes_
Definition at line 51 of file supre.cxx.
Referenced by calcInitDisplacements_var_prop().
double* ThicknessSolution_
Referenced by calcInitDisplacements_var_prop().