simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/ParasolidSolidModel/frustrum.cxx File Reference
frustrum.cxx File Reference
#include "SimVascular.h"
#include "frustrum_ifails.h"
#include "frustrum_tokens.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include "parasolid_kernel.h"
#include "kernel_interface.h"
Classes
struct file_s
Macros
#define FSTART fru_fstart
#define FABORT fru_fabort
#define FSTOP fru_fstop
#define FMALLO fru_fmallo
#define FMFREE fru_fmfree
#define GOSGMT fru_gosgmt
#define GOOPSG fru_goopsg
#define GOCLSG fru_goclsg
#define GOPIXL fru_gopixl
#define GOOPPX fru_gooppx
#define GOCLPX fru_goclpx
#define FFOPRD fru_ffoprd
#define FFOPWR fru_ffopwr
#define FFCLOS fru_ffclos
#define FFREAD fru_ffread
#define FFWRIT fru_ffwrit
#define FFOPRB fru_ffoprb
#define FFSEEK fru_ffseek
#define FFTELL fru_fftell
#define trace_flag 0
#define PS_LONG_NAME 0
#define PS_SHORT_NAME 1
#define FR_not_started FR_unspecified
#define FR_internal_error FR_unspecified
#define null_strid (-1)
#define max_namelen 255 /* maximum length of a full pathname */
#define max_header_line (max_namelen+32) /* for long FILE=name in the header */
#define max_open_files 32
#define read_access 1
#define write_access 2
#define read_write_access 3
#define end_of_string_c '\0'
#define end_of_string_s "\0"
#define new_line_c '\n'
#define new_line_s "\n"
#define semi_colon_c ';'
#define semi_colon_s ";"
#define dir_separator_c '/'
#define dir_separator_s "/"
#define trace_print if (!trace_flag) /* skip */; else printf
Typedefs
typedef struct file_s * file_p
typedef struct file_s file_t
Functions
static char * lowercase (char *str)
static char * format_string (int format)
static char * guise_string (int guise)
static char * filetype_guise_string (int guise, int filesystem)
static char * filetype_format_string (int format, int filesystem)
static char * filekey_string (char *keynam, int keylen)
static void delete_file (char *name, int *ifail)
static void new_open_file (FILE *stream, int guise, int format, int access, char *filename, char *keyname, file_p *file_ptr, int *ifail)
static void write_to_file (file_p file_ptr, const char *buffer, int header, int buffer_len, int *ifail)
static void read_from_file (file_p file_ptr, char *buffer, int header, int max_buffer_len, int *buffer_len, int *ifail)
static void check_valid_filename (char *filename, int *ifail)
static void extend_schema_filename (char *filename, int *ifail)
static void write_header (file_p file_ptr, const char *pd2hdr, int pd2len, int *ifail)
static void write_xml_header (file_p file_ptr, const char *pd2hdr, int pd2len, int *ifail)
static void setup_header (void)
static void skip_header (file_p file_ptr, int *ifail)
void fru_fstart (int *ifail)
void fru_fstop (int *ifail)
void fru_fmallo (int *nbytes, char **memory, int *ifail)
void fru_fmfree (int *nbytes, char **memory, int *ifail)
void fru_ffoprd (const int *guise, const int *format, const char *name, const int *namlen, const int *skiphd, int *strid, int *ifail)
void fru_ffopwr (const int *guise, const int *format, const char *name, const int *namlen, const char *pd2hdr, const int *pd2len, int *strid, int *ifail)
void fru_ffoprb (const int *guise, const int *minsiz, const int *maxsiz, int *actsiz, int *strid, int *ifail)
void fru_ffwrit (const int *guise, const int *strid, const int *nchars, const char *buffer, int *ifail)
void fru_ffread (const int *guise, const int *strid, const int *nmax, char *buffer, int *nactual, int *ifail)
void fru_fftell (const int *guise, const int *strid, int *pos, int *ifail)
void fru_ffseek (const int *guise, const int *strid, const int *pos, int *ifail)
void fru_ffclos (const int *guise, const int *strid, const int *action, int *ifail)
void fru_fabort (int *ifail)
void FTMKEY (int *guise, int *format, int *index, char name[], int *namlen, int *ifail)
void fru_gooppx (const int *nreals, const double *rvals, const int *nints, const int *ivals, int *ifail)
void fru_goclpx (const int *nreals, const double *rvals, const int *nints, const int *ivals, int *ifail)
void fru_gopixl (const int *nreals, const double *rvals, const int *nints, const int *ivals, int *ifail)
void fru_goopsg (const int *segtyp, const int *ntags, const int *tags, const int *ngeom, const double *geom, const int *nlntp, const int *lntp, int *ifail)
void fru_goclsg (const int *segtyp, const int *ntags, const int *tags, const int *ngeom, const double *geom, const int *nlntp, const int *lntp, int *ifail)
void fru_gosgmt (const int *segtyp, const int *ntags, const int *tags, const int *ngeom, const double *geom, const int *nlntp, const int *lntp, int *ifail)
void fru_init ()
Variables
static file_p open_files = NULL
static int stream_id [32]
static int file_count = 0
static int frustrum_started = 0
static char g_preamble_1 [(255+32)] = "\0"
static char g_preamble_2 [(255+32)] = "\0"
static char g_prefix_1 [(255+32)] = "**PART1;\n"
static char g_prefix_2 [(255+32)] = "**PART2;\n"
static char g_prefix_3 [(255+32)] = "**PART3;\n"
static char g_trailer_start [(255+32)] = "**END_OF_HEADER"
static char g_trailer [(255+32)] = "\0"
static char g_unknown_value [] = "unknown"
static char g_fopen_mode_read [] = "r"
static char g_fopen_mode_write [] = "w"
static char g_fopen_mode_append [] = "w+"
static char * input_output_buffer = NULL
static int input_output_buflen = 0
Macro Definition Documentation
#define dir_separator_c '/'
Definition at line 184 of file frustrum.cxx.
Referenced by fru_ffoprd(), and fru_ffopwr().
#define dir_separator_s "/"
Definition at line 185 of file frustrum.cxx.
Referenced by extend_schema_filename().
#define end_of_string_c '\0'
Definition at line 171 of file frustrum.cxx.
Referenced by filekey_string(), fru_ffoprd(), fru_ffopwr(), lowercase(), write_header(), and write_to_file().
#define end_of_string_s "\0"
Definition at line 172 of file frustrum.cxx.
Referenced by filetype_format_string(), and filetype_guise_string().
#define FABORT fru_fabort
Definition at line 35 of file frustrum.cxx.
#define FFCLOS fru_ffclos
Definition at line 49 of file frustrum.cxx.
#define FFOPRB fru_ffoprb
Definition at line 52 of file frustrum.cxx.
#define FFOPRD fru_ffoprd
Definition at line 47 of file frustrum.cxx.
#define FFOPWR fru_ffopwr
Definition at line 48 of file frustrum.cxx.
#define FFREAD fru_ffread
Definition at line 50 of file frustrum.cxx.
#define FFSEEK fru_ffseek
Definition at line 53 of file frustrum.cxx.
#define FFTELL fru_fftell
Definition at line 54 of file frustrum.cxx.
#define FFWRIT fru_ffwrit
Definition at line 51 of file frustrum.cxx.
#define FMALLO fru_fmallo
Definition at line 37 of file frustrum.cxx.
#define FMFREE fru_fmfree
Definition at line 38 of file frustrum.cxx.
#define FR_internal_error FR_unspecified
Definition at line 157 of file frustrum.cxx.
Referenced by fru_ffread(), fru_ffseek(), fru_fftell(), fru_ffwrit(), and FTMKEY().
#define FR_not_started FR_unspecified
Definition at line 156 of file frustrum.cxx.
Referenced by fru_ffclos(), fru_ffoprb(), fru_ffoprd(), fru_ffopwr(), fru_ffread(), fru_ffseek(), fru_fftell(), fru_ffwrit(), fru_fmallo(), fru_fmfree(), and fru_fstop().
#define FSTART fru_fstart
Definition at line 34 of file frustrum.cxx.
#define FSTOP fru_fstop
Definition at line 36 of file frustrum.cxx.
#define GOCLPX fru_goclpx
Definition at line 45 of file frustrum.cxx.
#define GOCLSG fru_goclsg
Definition at line 42 of file frustrum.cxx.
#define GOOPPX fru_gooppx
Definition at line 44 of file frustrum.cxx.
#define GOOPSG fru_goopsg
Definition at line 41 of file frustrum.cxx.
#define GOPIXL fru_gopixl
Definition at line 43 of file frustrum.cxx.
#define GOSGMT fru_gosgmt
Definition at line 40 of file frustrum.cxx.
#define max_header_line (max_namelen+32) /* for long FILE=name in the header */
Definition at line 164 of file frustrum.cxx.
Referenced by skip_header(), write_header(), and write_xml_header().
#define max_namelen 255 /* maximum length of a full pathname */
Definition at line 163 of file frustrum.cxx.
Referenced by check_valid_filename(), extend_schema_filename(), filekey_string(), fru_ffclos(), fru_ffoprb(), fru_ffoprd(), fru_ffopwr(), and FTMKEY().
#define max_open_files 32
Definition at line 165 of file frustrum.cxx.
Referenced by fru_ffoprb(), fru_ffoprd(), fru_ffopwr(), and fru_fstart().
#define new_line_c '\n'
Definition at line 174 of file frustrum.cxx.
Referenced by write_header().
#define new_line_s "\n"
Definition at line 175 of file frustrum.cxx.
Referenced by setup_header().
#define null_strid (-1)
Definition at line 162 of file frustrum.cxx.
Referenced by fru_ffoprb(), fru_ffoprd(), and fru_ffopwr().
#define PS_LONG_NAME 0
Definition at line 151 of file frustrum.cxx.
Referenced by fru_ffoprd(), fru_ffopwr(), and FTMKEY().
#define PS_SHORT_NAME 1
Definition at line 152 of file frustrum.cxx.
Referenced by filetype_format_string(), filetype_guise_string(), fru_ffoprd(), fru_ffopwr(), and FTMKEY().
#define read_access 1
Definition at line 167 of file frustrum.cxx.
Referenced by fru_ffoprd(), and fru_ffread().
#define read_write_access 3
Definition at line 169 of file frustrum.cxx.
Referenced by fru_ffclos(), fru_ffoprb(), fru_ffread(), and fru_ffwrit().
#define semi_colon_c ';'
Definition at line 177 of file frustrum.cxx.
#define semi_colon_s ";"
Definition at line 178 of file frustrum.cxx.
#define trace_flag 0
Definition at line 149 of file frustrum.cxx.
#define trace_print if (!trace_flag) /* skip */; else printf
Definition at line 192 of file frustrum.cxx.
Referenced by check_valid_filename(), delete_file(), extend_schema_filename(), fru_fabort(), fru_ffclos(), fru_ffoprb(), fru_ffoprd(), fru_ffopwr(), fru_ffread(), fru_ffseek(), fru_fftell(), fru_ffwrit(), fru_fmallo(), fru_fmfree(), fru_fstart(), fru_fstop(), fru_goclpx(), fru_goclsg(), fru_gooppx(), fru_goopsg(), fru_gopixl(), fru_gosgmt(), FTMKEY(), new_open_file(), read_from_file(), skip_header(), write_header(), and write_to_file().
#define write_access 2
Definition at line 168 of file frustrum.cxx.
Referenced by fru_ffclos(), fru_ffopwr(), and fru_ffwrit().
Typedef Documentation
typedef struct file_s* file_p
Definition at line 206 of file frustrum.cxx.
typedef struct file_s file_t
Function Documentation
static void check_valid_filename (char * filename, int * ifail) static
Definition at line 1044 of file frustrum.cxx.
References c, max_namelen, and trace_print.
Referenced by extend_schema_filename(), fru_ffoprd(), and fru_ffopwr().
static void delete_file (char * name, int * ifail) static
Definition at line 673 of file frustrum.cxx.
References trace_print.
Referenced by fru_ffclos().
static void extend_schema_filename (char * filename, int * ifail) static
Definition at line 1123 of file frustrum.cxx.
References check_valid_filename(), dir_separator_s, max_namelen, NULL, and trace_print.
Referenced by fru_ffoprd(), and fru_ffopwr().
static char* filekey_string (char * keynam, int keylen) static
Definition at line 647 of file frustrum.cxx.
References end_of_string_c, and max_namelen.
static char* filetype_format_string (int format, int filesystem) static
Definition at line 602 of file frustrum.cxx.
References end_of_string_s, and PS_SHORT_NAME.
Referenced by fru_ffoprd(), fru_ffopwr(), and FTMKEY().
static char* filetype_guise_string (int guise, int filesystem) static
Definition at line 524 of file frustrum.cxx.
References end_of_string_s, and PS_SHORT_NAME.
Referenced by fru_ffoprd(), fru_ffopwr(), and FTMKEY().
static char* format_string (int format) static
Definition at line 318 of file frustrum.cxx.
References g_unknown_value.
Referenced by write_header().
void fru_fabort (int * ifail)
Definition at line 2465 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_ffclos (const int * guise, const int * strid, const int * action, int * ifail)
Definition at line 2375 of file frustrum.cxx.
References file_s::access, delete_file(), file_count, filename, FR_not_started, free(), frustrum_started, max_namelen, file_s::name, file_s::next, NULL, file_s::prev, read_write_access, file_s::stream, stream_id, file_s::strid, trace_print, and write_access.
Referenced by fru_init().
void fru_ffoprb (const int * guise, const int * minsiz, const int * maxsiz, int * actsiz, int * strid, int * ifail)
Definition at line 1989 of file frustrum.cxx.
References file_count, filename, FR_not_started, frustrum_started, g_fopen_mode_append, max_namelen, max_open_files, new_open_file(), null_strid, read_write_access, file_s::strid, and trace_print.
Referenced by fru_init().
void fru_ffoprd (const int * guise, const int * format, const char * name, const int * namlen, const int * skiphd, int * strid, int * ifail)
Definition at line 1677 of file frustrum.cxx.
References check_valid_filename(), dir_separator_c, end_of_string_c, extend_schema_filename(), file_count, filename, filetype_format_string(), filetype_guise_string(), FR_not_started, frustrum_started, g_fopen_mode_read, max_namelen, max_open_files, new_open_file(), null_strid, PS_LONG_NAME, PS_SHORT_NAME, read_access, skip_header(), file_s::strid, and trace_print.
Referenced by fru_init().
void fru_ffopwr (const int * guise, const int * format, const char * name, const int * namlen, const char * pd2hdr, const int * pd2len, int * strid, int * ifail)
Definition at line 1839 of file frustrum.cxx.
References check_valid_filename(), dir_separator_c, end_of_string_c, extend_schema_filename(), file_count, filename, filetype_format_string(), filetype_guise_string(), FR_not_started, frustrum_started, g_fopen_mode_write, max_namelen, max_open_files, new_open_file(), null_strid, PS_LONG_NAME, PS_SHORT_NAME, file_s::strid, trace_print, write_access, write_header(), and write_xml_header().
Referenced by fru_init().
void fru_ffread (const int * guise, const int * strid, const int * nmax, char * buffer, int * nactual, int * ifail)
Definition at line 2146 of file frustrum.cxx.
References file_s::access, FR_internal_error, FR_not_started, frustrum_started, file_s::guise, file_s::next, NULL, read_access, read_from_file(), read_write_access, file_s::strid, and trace_print.
Referenced by fru_init().
void fru_ffseek (const int * guise, const int * strid, const int * pos, int * ifail)
Definition at line 2302 of file frustrum.cxx.
References FR_internal_error, FR_not_started, frustrum_started, file_s::guise, file_s::next, NULL, file_s::stream, file_s::strid, and trace_print.
Referenced by fru_init().
void fru_fftell (const int * guise, const int * strid, int * pos, int * ifail)
Definition at line 2236 of file frustrum.cxx.
References FR_internal_error, FR_not_started, frustrum_started, file_s::guise, file_s::next, NULL, file_s::stream, file_s::strid, and trace_print.
Referenced by fru_init().
void fru_ffwrit (const int * guise, const int * strid, const int * nchars, const char * buffer, int * ifail)
Definition at line 2067 of file frustrum.cxx.
References file_s::access, FR_internal_error, FR_not_started, frustrum_started, file_s::guise, file_s::next, NULL, read_write_access, file_s::stream, file_s::strid, trace_print, write_access, and write_to_file().
Referenced by fru_init().
void fru_fmallo (int * nbytes, char ** memory, int * ifail)
Definition at line 1581 of file frustrum.cxx.
References FR_not_started, frustrum_started, NULL, and trace_print.
Referenced by fru_init().
void fru_fmfree (int * nbytes, char ** memory, int * ifail)
Definition at line 1642 of file frustrum.cxx.
References FR_not_started, frustrum_started, and trace_print.
Referenced by fru_init().
void fru_fstart (int * ifail)
Definition at line 1469 of file frustrum.cxx.
References frustrum_started, max_open_files, setup_header(), stream_id, and trace_print.
Referenced by fru_init().
void fru_fstop (int * ifail)
Definition at line 1514 of file frustrum.cxx.
References file_count, FR_not_started, free(), frustrum_started, input_output_buffer, input_output_buflen, file_s::next, NULL, open_files, file_s::prev, file_s::stream, and trace_print.
Referenced by fru_init().
void fru_goclpx (const int * nreals, const double * rvals, const int * nints, const int * ivals, int * ifail)
Definition at line 2641 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_goclsg (const int * segtyp, const int * ntags, const int * tags, const int * ngeom, const double * geom, const int * nlntp, const int * lntp, int * ifail)
Definition at line 2711 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_gooppx (const int * nreals, const double * rvals, const int * nints, const int * ivals, int * ifail)
Definition at line 2618 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_goopsg (const int * segtyp, const int * ntags, const int * tags, const int * ngeom, const double * geom, const int * nlntp, const int * lntp, int * ifail)
Definition at line 2687 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_gopixl (const int * nreals, const double * rvals, const int * nints, const int * ivals, int * ifail)
Definition at line 2664 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_gosgmt (const int * segtyp, const int * ntags, const int * tags, const int * ngeom, const double * geom, const int * nlntp, const int * lntp, int * ifail)
Definition at line 2735 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_init ()
Definition at line 2749 of file frustrum.cxx.
References fru_fabort(), fru_ffclos(), fru_ffoprb(), fru_ffoprd(), fru_ffopwr(), fru_ffread(), fru_ffseek(), fru_fftell(), fru_ffwrit(), fru_fmallo(), fru_fmfree(), fru_fstart(), fru_fstop(), fru_goclpx(), fru_goclsg(), fru_gooppx(), fru_goopsg(), fru_gopixl(), and fru_gosgmt().
Referenced by PsdUtils_Init().
void FTMKEY (int * guise, int * format, int * index, char name[], int * namlen, int * ifail)
Definition at line 2495 of file frustrum.cxx.
References filename, filetype_format_string(), filetype_guise_string(), FR_internal_error, max_namelen, PS_LONG_NAME, PS_SHORT_NAME, and trace_print.
static char* guise_string (int guise) static
Definition at line 350 of file frustrum.cxx.
References g_unknown_value.
Referenced by write_header().
static char* lowercase (char * str) static
Definition at line 290 of file frustrum.cxx.
References end_of_string_c.
static void new_open_file (FILE * stream, int guise, int format, int access, char * filename, char * keyname, file_p * file_ptr, int * ifail) static
Definition at line 740 of file frustrum.cxx.
References file_s::access, file_count, file_s::format, file_s::guise, file_s::key, file_s::name, file_s::next, NULL, file_s::prev, file_s::stream, stream_id, file_s::strid, and trace_print.
Referenced by fru_ffoprb(), fru_ffoprd(), and fru_ffopwr().
static void read_from_file (file_p file_ptr, char * buffer, int header, int max_buffer_len, int * buffer_len, int * ifail) static
Definition at line 930 of file frustrum.cxx.
References file_s::format, free(), input_output_buffer, input_output_buflen, NULL, file_s::stream, and trace_print.
Referenced by fru_ffread(), and skip_header().
static void setup_header (void) static
Definition at line 1346 of file frustrum.cxx.
References g_preamble_1, g_preamble_2, g_trailer, g_trailer_start, and new_line_s.
Referenced by fru_fstart().
static void skip_header (file_p file_ptr, int * ifail) static
Definition at line 1404 of file frustrum.cxx.
References g_preamble_1, g_trailer_start, max_header_line, read_from_file(), file_s::stream, and trace_print.
Referenced by fru_ffoprd().
static void write_header (file_p file_ptr, const char * pd2hdr, int pd2len, int * ifail) static
Definition at line 1182 of file frustrum.cxx.
References c, end_of_string_c, file_s::format, format_string(), g_preamble_1, g_preamble_2, g_prefix_1, g_prefix_2, g_prefix_3, g_trailer, file_s::guise, guise_string(), file_s::key, max_header_line, file_s::name, new_line_c, trace_print, and write_to_file().
Referenced by fru_ffopwr().
static void write_to_file (file_p file_ptr, const char * buffer, int header, int buffer_len, int * ifail) static
Definition at line 819 of file frustrum.cxx.
References end_of_string_c, file_s::format, free(), input_output_buffer, input_output_buflen, NULL, file_s::stream, and trace_print.
Referenced by fru_ffwrit(), write_header(), and write_xml_header().
static void write_xml_header (file_p file_ptr, const char * pd2hdr, int pd2len, int * ifail) static
Definition at line 1319 of file frustrum.cxx.
References max_header_line, and write_to_file().
Referenced by fru_ffopwr().
Variable Documentation
int file_count = 0 static
Definition at line 225 of file frustrum.cxx.
Referenced by fru_ffclos(), fru_ffoprb(), fru_ffoprd(), fru_ffopwr(), fru_fstop(), and new_open_file().
int frustrum_started = 0 static
Definition at line 228 of file frustrum.cxx.
Referenced by fru_ffclos(), fru_ffoprb(), fru_ffoprd(), fru_ffopwr(), fru_ffread(), fru_ffseek(), fru_fftell(), fru_ffwrit(), fru_fmallo(), fru_fmfree(), fru_fstart(), and fru_fstop().
char g_fopen_mode_append[] = "w+" static
Definition at line 258 of file frustrum.cxx.
Referenced by fru_ffoprb().
char g_fopen_mode_read[] = "r" static
Definition at line 256 of file frustrum.cxx.
Referenced by fru_ffoprd().
char g_fopen_mode_write[] = "w" static
Definition at line 257 of file frustrum.cxx.
Referenced by fru_ffopwr().
char g_preamble_1[(255+32)] = "\0" static
Definition at line 238 of file frustrum.cxx.
Referenced by setup_header(), skip_header(), and write_header().
char g_preamble_2[(255+32)] = "\0" static
Definition at line 239 of file frustrum.cxx.
Referenced by setup_header(), and write_header().
char g_prefix_1[(255+32)] = "**PART1;\n" static
Definition at line 240 of file frustrum.cxx.
Referenced by write_header().
char g_prefix_2[(255+32)] = "**PART2;\n" static
Definition at line 241 of file frustrum.cxx.
Referenced by write_header().
char g_prefix_3[(255+32)] = "**PART3;\n" static
Definition at line 242 of file frustrum.cxx.
Referenced by write_header().
char g_trailer[(255+32)] = "\0" static
Definition at line 244 of file frustrum.cxx.
Referenced by setup_header(), and write_header().
char g_trailer_start[(255+32)] = "**END_OF_HEADER" static
Definition at line 243 of file frustrum.cxx.
Referenced by setup_header(), and skip_header().
char g_unknown_value[] = "unknown" static
Definition at line 245 of file frustrum.cxx.
Referenced by format_string(), and guise_string().
char* input_output_buffer = NULL static
Definition at line 262 of file frustrum.cxx.
Referenced by fru_fstop(), read_from_file(), and write_to_file().
int input_output_buflen = 0 static
Definition at line 263 of file frustrum.cxx.
Referenced by fru_fstop(), read_from_file(), and write_to_file().
file_p open_files = NULL static
Definition at line 221 of file frustrum.cxx.
Referenced by fru_fstop().
int stream_id[32] static
Definition at line 224 of file frustrum.cxx.
Referenced by fru_ffclos(), fru_fstart(), and new_open_file().