simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/UI/gdscInit.cxx File Reference
gdscInit.cxx File Reference
#include "SimVascular.h"
#include "cvIOstream.h"
#include <time.h>
#include <stdlib.h>
#include <tcl.h>
#include <tk.h>
#include "cv_repos_init.h"
#include "cv_LsetCore_init.h"
#include "cv_LsetV_init.h"
#include "cv_geom_init.h"
#include "cv_image_init.h"
#include "cv_math_init.h"
#include "cv_post_init.h"
#include "cv_get_tcl_interp_init.h"
#include "cv_polydatasolid_init.h"
#include "cv_solid_init.h"
#include "cv_VTK_init.h"
#include "cv_globals.h"
Functions
int SimVascular_Init (Tcl_Interp *interp)
void SimVascularWelcome (Tcl_Interp *interp)
Function Documentation
int SimVascular_Init (Tcl_Interp * interp)
Definition at line 145 of file gdscInit.cxx.
References Gdscmesh_Init(), Gdscpost_Init(), Geom_Init(), Getinterp_Init(), Image_Init(), itkls2d_Init(), itkls3d_Init(), itkutils_Init(), Lsetcore_Init(), Lsetv_Init(), Math_Init(), Meshsimdiscretesolid_Init(), Meshsimmesh_Init(), myVtk_Init(), Parasolidsolid_Init(), PolyDataSolid_Init(), Repos_Init(), SimVascularWelcome(), Solid_Init(), and Tetgenmesh_Init().
Referenced by Tcl_AppInit().
void SimVascularWelcome (Tcl_Interp * interp)
Definition at line 115 of file gdscInit.cxx.
Referenced by SimVascular_Init().