simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/ThirdParty/zlib/simvascular_zlib/gzio.c File Reference
gzio.c File Reference
#include <stdio.h>
#include "zutil.h"
Classes
struct internal_state
struct gz_stream
Macros
#define Z_BUFSIZE 16384
#define Z_PRINTF_BUFSIZE 4096
#define ALLOC(size) malloc(size)
#define TRYFREE(p) {if (p) free(p);}
#define ASCII_FLAG 0x01 /* bit 0 set: file probably ascii text */
#define HEAD_CRC 0x02 /* bit 1 set: header CRC present */
#define EXTRA_FIELD 0x04 /* bit 2 set: extra field present */
#define ORIG_NAME 0x08 /* bit 3 set: original file name present */
#define COMMENT 0x10 /* bit 4 set: file comment present */
#define RESERVED 0xE0 /* bits 5..7: reserved */
#define zstrerror(errnum) ""
Typedefs
typedef struct gz_stream gz_stream
Functions
voidp malloc ()
void free ()
static gzFile gz_open ()
static int do_flush ()
static int get_byte ()
static void check_header ()
static int destroy ()
static void putLong ()
static uLong getLong ()
static gzFile gz_open (char *path, char *mode, int fd)
gzFile cv_zlib_gzopen (char *path, char *mode)
gzFile cv_zlib_gzdopen (int fd, char *mode)
int cv_zlib_gzsetparams (gzFile file, int level, int strategy)
static int get_byte (gz_stream *s)
static void check_header (gz_stream *s)
static int destroy (gz_stream *s)
int cv_zlib_gzread (gzFile file, voidp buf, unsigned len)
int cv_zlib_gzgetc (gzFile file)
int cv_zlib_gzungetc (int c, gzFile file)
char * cv_zlib_gzgets (gzFile file, char *buf, int len)
int cv_zlib_gzwrite (gzFile file, voidpc buf, unsigned len)
int cv_zlib_gzprintf (gzFile file, char *format, int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20)
int cv_zlib_gzputc (gzFile file, int c)
int cv_zlib_gzputs (gzFile file, char *s)
static int do_flush (gzFile file, int flush)
int cv_zlib_gzflush (gzFile file, int flush)
long cv_zlib_gzseek (gzFile file, long offset, int whence)
int cv_zlib_gzrewind (gzFile file)
long cv_zlib_gztell (gzFile file)
int cv_zlib_gzeof (gzFile file)
int cv_zlib_gzdirect (gzFile file)
static void putLong (FILE *file, uLong x)
static uLong getLong (gz_stream *s)
int cv_zlib_gzclose (gzFile file)
char * cv_zlib_gzerror (gzFile file, int *errnum)
void cv_zlib_gzclearerr (gzFile file)
Variables
static int gz_magic [2] = {0x1f, 0x8b}
Macro Definition Documentation
#define ALLOC (size) malloc(size)
Definition at line 43 of file gzio.c.
Referenced by cv_zlib_gzerror(), cv_zlib_gzseek(), and gz_open().
#define ASCII_FLAG 0x01 /* bit 0 set: file probably ascii text */
Definition at line 49 of file gzio.c.
#define COMMENT 0x10 /* bit 4 set: file comment present */
Definition at line 53 of file gzio.c.
Referenced by check_header().
#define EXTRA_FIELD 0x04 /* bit 2 set: extra field present */
Definition at line 51 of file gzio.c.
Referenced by check_header().
#define HEAD_CRC 0x02 /* bit 1 set: header CRC present */
Definition at line 50 of file gzio.c.
Referenced by check_header().
#define ORIG_NAME 0x08 /* bit 3 set: original file name present */
Definition at line 52 of file gzio.c.
Referenced by check_header().
#define RESERVED 0xE0 /* bits 5..7: reserved */
Definition at line 54 of file gzio.c.
Referenced by check_header().
#define TRYFREE (p) {if (p) free(p);}
Definition at line 44 of file gzio.c.
Referenced by cv_zlib_gzerror(), and destroy().
#define Z_BUFSIZE 16384
Definition at line 26 of file gzio.c.
Referenced by check_header(), cv_zlib_gzread(), cv_zlib_gzseek(), cv_zlib_gzsetparams(), cv_zlib_gzwrite(), do_flush(), get_byte(), and gz_open().
#define Z_PRINTF_BUFSIZE 4096
Definition at line 30 of file gzio.c.
Referenced by cv_zlib_gzprintf().
#define zstrerror (errnum) ""
Definition at line 977 of file gzio.c.
Referenced by cv_zlib_gzerror().
Typedef Documentation
typedef struct gz_stream gz_stream
Function Documentation
static void check_header () static
Referenced by cv_zlib_gzread(), and gz_open().
static void check_header (gz_stream * s) static
Definition at line 288 of file gzio.c.
References c, COMMENT, EXTRA_FIELD, ferror, get_byte(), HEAD_CRC, ORIG_NAME, RESERVED, Z_BUFSIZE, Z_DATA_ERROR, Z_DEFLATED, Z_ERRNO, and Z_OK.
void cv_zlib_gzclearerr (gzFile file)
Definition at line 1017 of file gzio.c.
References gz_stream::file, NULL, gz_stream::z_eof, gz_stream::z_err, Z_OK, and Z_STREAM_END.
int cv_zlib_gzclose (gzFile file)
Definition at line 953 of file gzio.c.
References gz_stream::crc, destroy(), do_flush(), gz_stream::file, gz_stream::in, gz_stream::mode, NULL, putLong(), Z_FINISH, Z_OK, and Z_STREAM_ERROR.
int cv_zlib_gzdirect (gzFile file)
Definition at line 908 of file gzio.c.
References gz_stream::mode, NULL, and gz_stream::transparent.
gzFile cv_zlib_gzdopen (int fd, char * mode)
Definition at line 219 of file gzio.c.
References gz_open(), and Z_NULL.
int cv_zlib_gzeof (gzFile file)
Definition at line 891 of file gzio.c.
References gz_stream::mode, NULL, gz_stream::z_eof, gz_stream::z_err, and Z_STREAM_END.
char* cv_zlib_gzerror (gzFile file, int * errnum)
Definition at line 987 of file gzio.c.
References ALLOC, ERR_MSG, gz_stream::msg, z_stream_s::msg, NULL, gz_stream::path, gz_stream::stream, TRYFREE, gz_stream::z_err, Z_ERRNO, Z_MEM_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, and zstrerror.
int cv_zlib_gzflush (gzFile file, int flush)
Definition at line 746 of file gzio.c.
References do_flush(), gz_stream::file, gz_stream::z_err, Z_OK, and Z_STREAM_END.
int cv_zlib_gzgetc (gzFile file)
Definition at line 503 of file gzio.c.
References c, and gzread.
char* cv_zlib_gzgets (gzFile file, char * buf, int len)
Definition at line 540 of file gzio.c.
References gzread, and Z_NULL.
gzFile cv_zlib_gzopen (char * path, char * mode)
Definition at line 208 of file gzio.c.
References gz_open().
int cv_zlib_gzprintf (gzFile file, char * format, int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20)
Definition at line 637 of file gzio.c.
References gzwrite, and Z_PRINTF_BUFSIZE.
int cv_zlib_gzputc (gzFile file, int c)
Definition at line 678 of file gzio.c.
References gzwrite.
int cv_zlib_gzputs (gzFile file, char * s)
Definition at line 693 of file gzio.c.
References gzwrite.
int cv_zlib_gzread (gzFile file, voidp buf, unsigned len)
Definition at line 394 of file gzio.c.
References z_stream_s::avail_in, z_stream_s::avail_out, gz_stream::back, check_header(), gz_stream::crc, crc32, ferror, gz_stream::file, getLong(), gz_stream::in, gz_stream::inbuf, inflate, inflateReset, L, gz_stream::last, gz_stream::mode, z_stream_s::next_in, z_stream_s::next_out, NULL, gz_stream::out, gz_stream::stream, gz_stream::transparent, Z_BUFSIZE, Z_DATA_ERROR, gz_stream::z_eof, gz_stream::z_err, Z_ERRNO, Z_NO_FLUSH, Z_NULL, Z_OK, Z_STREAM_END, Z_STREAM_ERROR, and zmemcpy().
int cv_zlib_gzrewind (gzFile file)
Definition at line 857 of file gzio.c.
References z_stream_s::avail_in, gz_stream::back, gz_stream::crc, crc32, gz_stream::file, gz_stream::in, gz_stream::inbuf, inflateReset, L, gz_stream::mode, z_stream_s::next_in, NULL, gz_stream::out, SEEK_SET, gz_stream::start, gz_stream::stream, gz_stream::transparent, gz_stream::z_eof, gz_stream::z_err, Z_NULL, and Z_OK.
long cv_zlib_gzseek (gzFile file, long offset, int whence)
Definition at line 767 of file gzio.c.
References ALLOC, z_stream_s::avail_in, gz_stream::back, gz_stream::file, gzread, gzrewind, gzwrite, gz_stream::in, gz_stream::inbuf, L, gz_stream::last, gz_stream::mode, z_stream_s::next_in, NULL, gz_stream::out, gz_stream::outbuf, SEEK_CUR, SEEK_END, SEEK_SET, gz_stream::stream, gz_stream::transparent, Z_BUFSIZE, Z_DATA_ERROR, gz_stream::z_err, Z_ERRNO, Z_NULL, Z_STREAM_END, and zmemzero().
int cv_zlib_gzsetparams (gzFile file, int level, int strategy)
Definition at line 234 of file gzio.c.
References z_stream_s::avail_out, deflateParams, gz_stream::file, gz_stream::mode, z_stream_s::next_out, NULL, gz_stream::outbuf, gz_stream::stream, Z_BUFSIZE, gz_stream::z_err, Z_ERRNO, and Z_STREAM_ERROR.
long cv_zlib_gztell (gzFile file)
Definition at line 881 of file gzio.c.
References gzseek, L, and SEEK_CUR.
int cv_zlib_gzungetc (int c, gzFile file)
Definition at line 515 of file gzio.c.
References gz_stream::back, c, gz_stream::last, gz_stream::mode, NULL, gz_stream::out, gz_stream::z_eof, gz_stream::z_err, Z_OK, and Z_STREAM_END.
int cv_zlib_gzwrite (gzFile file, voidpc buf, unsigned len)
Definition at line 559 of file gzio.c.
References z_stream_s::avail_in, z_stream_s::avail_out, gz_stream::crc, crc32, deflate, gz_stream::file, gz_stream::in, gz_stream::mode, z_stream_s::next_in, z_stream_s::next_out, NULL, gz_stream::out, gz_stream::outbuf, gz_stream::stream, Z_BUFSIZE, gz_stream::z_err, Z_ERRNO, Z_NO_FLUSH, Z_OK, and Z_STREAM_ERROR.
static int destroy () static
Referenced by cv_zlib_gzclose(), and gz_open().
static int destroy (gz_stream * s) static
Definition at line 355 of file gzio.c.
References deflateEnd, inflateEnd, NULL, TRYFREE, Z_ERRNO, Z_OK, and Z_STREAM_ERROR.
static int do_flush () static
Referenced by cv_zlib_gzclose(), and cv_zlib_gzflush().
static int do_flush (gzFile file, int flush) static
Definition at line 705 of file gzio.c.
References z_stream_s::avail_in, z_stream_s::avail_out, deflate, gz_stream::file, gz_stream::mode, z_stream_s::next_out, NULL, gz_stream::out, gz_stream::outbuf, gz_stream::stream, Z_BUF_ERROR, Z_BUFSIZE, gz_stream::z_err, Z_ERRNO, Z_OK, Z_STREAM_END, and Z_STREAM_ERROR.
void free ()
Referenced by CallFortranGMRES(), cgeom_VertsCompact(), FMMHelper(), fru_ffclos(), fru_fstop(), main(), cvAdaptCore::phastaTransfer(), read_from_file(), readlesrestart_(), ReadRegionHelper(), savelesrestart_(), SigMapHelper(), SmoothHelper(), TLSFHelper(), and write_to_file().
static int get_byte () static
Referenced by check_header(), and getLong().
static int get_byte (gz_stream * s) static
Definition at line 261 of file gzio.c.
References z_stream_s::avail_in, ferror, gz_stream::stream, Z_BUFSIZE, and Z_ERRNO.
static uLong getLong () static
Referenced by cv_zlib_gzread().
static uLong getLong (gz_stream * s) static
Definition at line 935 of file gzio.c.
References c, get_byte(), and Z_DATA_ERROR.
static gzFile gz_open () static
Referenced by cv_zlib_gzdopen(), and cv_zlib_gzopen().
static gzFile gz_open (char * path, char * mode, int fd) static
Definition at line 93 of file gzio.c.
References ALLOC, z_stream_s::avail_in, z_stream_s::avail_out, gz_stream::back, check_header(), gz_stream::crc, crc32, DEF_MEM_LEVEL, deflateInit2, destroy(), F_OPEN, gz_stream::file, gz_stream::in, gz_stream::inbuf, inflateInit2, L, MAX_WBITS, gz_stream::mode, gz_stream::msg, z_stream_s::next_in, z_stream_s::next_out, NULL, z_stream_s::opaque, OS_CODE, gz_stream::out, gz_stream::outbuf, gz_stream::path, gz_stream::start, gz_stream::stream, gz_stream::transparent, Z_BUFSIZE, Z_DEFAULT_COMPRESSION, Z_DEFAULT_STRATEGY, Z_DEFLATED, gz_stream::z_eof, gz_stream::z_err, Z_FILTERED, Z_HUFFMAN_ONLY, Z_NULL, Z_OK, Z_RLE, Z_STREAM_ERROR, z_stream_s::zalloc, and z_stream_s::zfree.
voidp malloc ()
Referenced by CallFortranGMRES(), cgeom_FixDegen(), cgeom_NormsComp(), cgeom_PolysEdgeTab(), cgeom_PolysSmooth(), cgeom_VertsCompact(), FMMHelper(), lesBlkDot2(), lesVdimDot2(), cvAdaptCore::phastaTransfer(), readlesrestart_(), ReadRegionHelper(), savelesrestart_(), SigMapHelper(), SmoothHelper(), StanfordIterativeSolve(), and TLSFHelper().
static void putLong () static
Referenced by cv_zlib_gzclose().
static void putLong (FILE * file, uLong x) static
Definition at line 920 of file gzio.c.
Variable Documentation
int gz_magic[2] = {0x1f, 0x8b} static
Definition at line 46 of file gzio.c.