simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/ThirdParty/zlib/simvascular_zlib/inflate.c File Reference
inflate.c File Reference
#include "zutil.h"
#include "inftrees.h"
#include "inflate.h"
#include "inffast.h"
#include "inffixed.h"
Macros
#define UPDATE(check, buf, len) (state->flags ? crc32(check, buf, len) : adler32(check, buf, len))
#define CRC2(check, word)
#define CRC4(check, word)
#define LOAD()
#define RESTORE()
#define INITBITS()
#define PULLBYTE()
#define NEEDBITS(n)
#define BITS(n) ((unsigned)hold & ((1U << (n)) - 1))
#define DROPBITS(n)
#define BYTEBITS()
#define REVERSE(q)
Functions
static void fixedtables ()
static int updatewindow ()
static unsigned syncsearch ()
int cv_zlib_inflateReset (z_streamp strm)
int cv_zlib_inflatePrime (z_streamp strm, int bits, int value)
int cv_zlib_inflateInit2_ (z_streamp strm, int windowBits, char *version, int stream_size)
int cv_zlib_inflateInit_ (z_streamp strm, char *version, int stream_size)
static void fixedtables (struct inflate_state *state)
static int updatewindow (z_streamp strm, unsigned out)
int cv_zlib_inflate (z_streamp strm, int flush)
int cv_zlib_inflateEnd (z_streamp strm)
int cv_zlib_inflateSetDictionary (z_streamp strm, Bytef *dictionary, uInt dictLength)
int cv_zlib_inflateGetHeader (z_streamp strm, gz_headerp head)
static unsigned syncsearch (unsigned *have, unsigned char *buf, unsigned len)
int cv_zlib_inflateSync (z_streamp strm)
int cv_zlib_inflateSyncPoint (z_streamp strm)
int cv_zlib_inflateCopy (z_streamp dest, z_streamp source)
Macro Definition Documentation
#define BITS (n) ((unsigned)hold & ((1U << (n)) - 1))
Definition at line 450 of file inflate.c.
Referenced by cv_zlib_inflate().
#define BYTEBITS ()
Value:
do { \
        hold >>= bits & 7; \
        bits -= bits & 7; \
    } while (0)
Definition at line 461 of file inflate.c.
Referenced by cv_zlib_inflate().
#define CRC2 (check, word)
Value:
do { \
        hbuf[0] = (unsigned char)(word); \
        hbuf[1] = (unsigned char)((word) >> 8); \
        check = crc32(check, hbuf, 2); \
    } while (0)
Definition at line 385 of file inflate.c.
Referenced by cv_zlib_inflate().
#define CRC4 (check, word)
Value:
do { \
        hbuf[0] = (unsigned char)(word); \
        hbuf[1] = (unsigned char)((word) >> 8); \
        hbuf[2] = (unsigned char)((word) >> 16); \
        hbuf[3] = (unsigned char)((word) >> 24); \
        check = crc32(check, hbuf, 4); \
    } while (0)
Definition at line 392 of file inflate.c.
Referenced by cv_zlib_inflate().
#define DROPBITS (n)
Value:
do { \
        hold >>= (n); \
        bits -= (unsigned)(n); \
    } while (0)
Definition at line 454 of file inflate.c.
Referenced by cv_zlib_inflate().
#define INITBITS ()
Value:
do { \
        hold = 0; \
        bits = 0; \
    } while (0)
Definition at line 425 of file inflate.c.
Referenced by cv_zlib_inflate().
#define LOAD ()
Value:
do { \
        put = strm->next_out; \
        left = strm->avail_out; \
        next = strm->next_in; \
        have = strm->avail_in; \
        hold = state->hold; \
        bits = state->bits; \
    } while (0)
Definition at line 403 of file inflate.c.
Referenced by cv_zlib_inflate().
#define NEEDBITS (n)
Value:
do { \
        while (bits < (unsigned)(n)) \
            PULLBYTE(); \
    } while (0)
Definition at line 443 of file inflate.c.
Referenced by cv_zlib_inflate().
#define PULLBYTE ()
Value:
do { \
        if (have == 0) goto inf_leave; \
        have--; \
        hold += (unsigned long)(*next++) << bits; \
        bits += 8; \
    } while (0)
Definition at line 433 of file inflate.c.
Referenced by cv_zlib_inflate().
#define RESTORE ()
Value:
do { \
        strm->next_out = put; \
        strm->avail_out = left; \
        strm->next_in = next; \
        strm->avail_in = have; \
        state->hold = hold; \
        state->bits = bits; \
    } while (0)
Definition at line 414 of file inflate.c.
Referenced by cv_zlib_inflate().
#define REVERSE (q)
Value:
((((q) >> 24) & 0xff) + (((q) >> 8) & 0xff00) + \
     (((q) & 0xff00) << 8) + (((q) & 0xff) << 24))
Definition at line 468 of file inflate.c.
Referenced by cv_zlib_inflate().
#define UPDATE (check, buf, len) (state->flags ? crc32(check, buf, len) : adler32(check, buf, len))
Definition at line 377 of file inflate.c.
Referenced by cv_zlib_inflate().
Function Documentation
int cv_zlib_inflate (z_streamp strm, int flush)
Definition at line 554 of file inflate.c.
References adler32, BAD, code::bits, inflate_state::bits, BITS, BYTEBITS, CHECK, inflate_state::check, CODELENS, CODES, inflate_state::codes, gz_header_s::comm_max, COMMENT, gz_header_s::comment, COPY, CRC2, crc32, CRC4, DICT, DICTID, DIST, inflate_state::distbits, inflate_state::distcode, DISTEXT, DISTS, inflate_state::dmax, DONE, gz_header_s::done, DROPBITS, EXLEN, EXTRA, inflate_state::extra, gz_header_s::extra, gz_header_s::extra_len, gz_header_s::extra_max, fixedtables(), FLAGS, inflate_state::flags, GUNZIP, inflate_state::have, inflate_state::havedict, HCRC, gz_header_s::hcrc, HEAD, inflate_state::head, inflate_state::hold, inflate_fast(), inflate_table(), INITBITS, L, inflate_state::last, LEN, inflate_state::lenbits, inflate_state::lencode, LENEXT, LENGTH, inflate_state::length, LENLENS, LENS, inflate_state::lens, LIT, LOAD, MATCH, MEM, inflate_state::mode, NAME, gz_header_s::name, gz_header_s::name_max, inflate_state::ncode, inflate_state::ndist, NEEDBITS, inflate_state::next, inflate_state::nlen, inflate_state::offset, code::op, order, OS, gz_header_s::os, PULLBYTE, RESTORE, REVERSE, STORED, SYNC, TABLE, gz_header_s::text, TIME, gz_header_s::time, inflate_state::total, Tracev, Tracevv, TYPE, TYPEDO, U, UPDATE, updatewindow(), code::val, inflate_state::wbits, inflate_state::whave, inflate_state::window, inflate_state::work, inflate_state::wrap, inflate_state::write, inflate_state::wsize, gz_header_s::xflags, Z_BLOCK, Z_BUF_ERROR, Z_DATA_ERROR, Z_DEFLATED, Z_FINISH, Z_MEM_ERROR, Z_NEED_DICT, Z_NULL, Z_OK, Z_STREAM_END, Z_STREAM_ERROR, and zmemcpy().
int cv_zlib_inflateCopy (z_streamp dest, z_streamp source)
Definition at line 1323 of file inflate.c.
References inflate_state::codes, inflate_state::distcode, ENOUGH, inflate_state::lencode, inflate_state::next, z_stream_s::state, U, inflate_state::wbits, inflate_state::window, inflate_state::wsize, Z_MEM_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, z_stream_s::zalloc, ZALLOC, z_stream_s::zfree, ZFREE, and zmemcpy().
int cv_zlib_inflateEnd (z_streamp strm)
Definition at line 1155 of file inflate.c.
References Tracev, inflate_state::window, Z_NULL, Z_OK, Z_STREAM_ERROR, and ZFREE.
int cv_zlib_inflateGetHeader (z_streamp strm, gz_headerp head)
Definition at line 1211 of file inflate.c.
References gz_header_s::done, inflate_state::head, inflate_state::wrap, Z_NULL, Z_OK, and Z_STREAM_ERROR.
int cv_zlib_inflateInit2_ (z_streamp strm, int windowBits, char * version, int stream_size)
Definition at line 144 of file inflate.c.
References inflateReset, Tracev, inflate_state::wbits, inflate_state::window, inflate_state::wrap, Z_MEM_ERROR, Z_NULL, Z_STREAM_ERROR, Z_VERSION_ERROR, ZALLOC, zcalloc(), zcfree(), ZFREE, and ZLIB_VERSION.
int cv_zlib_inflateInit_ (z_streamp strm, char * version, int stream_size)
Definition at line 187 of file inflate.c.
References DEF_WBITS, and inflateInit2_.
int cv_zlib_inflatePrime (z_streamp strm, int bits, int value)
Definition at line 128 of file inflate.c.
References inflate_state::bits, inflate_state::hold, L, Z_NULL, Z_OK, and Z_STREAM_ERROR.
int cv_zlib_inflateReset (z_streamp strm)
Definition at line 103 of file inflate.c.
References inflate_state::bits, inflate_state::codes, inflate_state::distcode, inflate_state::dmax, inflate_state::havedict, HEAD, inflate_state::head, inflate_state::hold, inflate_state::last, inflate_state::lencode, inflate_state::mode, inflate_state::next, inflate_state::total, Tracev, U, inflate_state::whave, inflate_state::write, inflate_state::wsize, Z_NULL, Z_OK, and Z_STREAM_ERROR.
int cv_zlib_inflateSetDictionary (z_streamp strm, Bytef * dictionary, uInt dictLength)
Definition at line 1169 of file inflate.c.
References adler32, inflate_state::check, DICT, inflate_state::havedict, L, MEM, inflate_state::mode, Tracev, updatewindow(), inflate_state::whave, inflate_state::window, inflate_state::wrap, inflate_state::wsize, Z_DATA_ERROR, Z_MEM_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, and zmemcpy().
int cv_zlib_inflateSync (z_streamp strm)
Definition at line 1262 of file inflate.c.
References inflate_state::bits, inflate_state::have, inflate_state::hold, inflateReset, inflate_state::mode, SYNC, syncsearch(), TYPE, Z_BUF_ERROR, Z_DATA_ERROR, Z_NULL, Z_OK, and Z_STREAM_ERROR.
int cv_zlib_inflateSyncPoint (z_streamp strm)
Definition at line 1313 of file inflate.c.
References inflate_state::bits, inflate_state::mode, STORED, Z_NULL, and Z_STREAM_ERROR.
static void fixedtables () static
Referenced by cv_zlib_inflate().
static void fixedtables (struct inflate_state * state) static
Definition at line 205 of file inflate.c.
References distfix, DISTS, inflate_table(), lenfix, and LENS.
static unsigned syncsearch () static
Referenced by cv_zlib_inflateSync().
static unsigned syncsearch (unsigned * have, unsigned char * buf, unsigned len) static
Definition at line 1239 of file inflate.c.
References inflate_state::have, and inflate_state::next.
static int updatewindow () static
Referenced by cv_zlib_inflate(), and cv_zlib_inflateSetDictionary().
static int updatewindow (z_streamp strm, unsigned out) static
Definition at line 323 of file inflate.c.
References U, inflate_state::wbits, inflate_state::whave, inflate_state::window, inflate_state::write, inflate_state::wsize, Z_NULL, ZALLOC, and zmemcpy().