simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/ThirdParty/zlib/simvascular_zlib/inftrees.c File Reference
inftrees.c File Reference
#include "zutil.h"
#include "inftrees.h"
Macros
#define MAXBITS 15
Functions
int inflate_table (codetype type, unsigned short *lens, unsigned codes, code **table, unsigned *bits, unsigned short *work)
Variables
char inflate_copyright []
Macro Definition Documentation
#define MAXBITS 15
Definition at line 9 of file inftrees.c.
Referenced by inflate_table().
Function Documentation
int inflate_table (codetype type, unsigned short * lens, unsigned codes, code * * table, unsigned * bits, unsigned short * work)
Definition at line 32 of file inftrees.c.
References CODES, ENOUGH, FAR, LENS, MAXBITS, MAXD, and U.
Referenced by cv_zlib_inflate(), cv_zlib_inflateBack(), and fixedtables().
Variable Documentation
char inflate_copyright[]
Initial value:
=
   " inflate 1.2.3 Copyright 1995-2005 Mark Adler "
Definition at line 11 of file inftrees.c.