simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/IncompressibleSolver/Solver/leslib_code_lestools.c File Reference
leslib_code_lestools.c File Reference
#include "leslib_code_usr.h"
#include "les.h"
Functions
void lesPrepDiag (UsrHd usrHd)
void lesDiagScaleCp (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff, Integer diagOff, Integer nDims)
void lesZero (UsrHd usrHd, Integer dstId, Integer nDims)
void lesCp (UsrHd usrHd, Integer srcId, Integer dstId, Integer nDims)
void lesScale (UsrHd usrHd, Integer dstId, Real coef, Integer nDims)
void lesScaleCp (UsrHd usrHd, Integer srcId, Integer dstId, Real coef, Integer nDims)
void lesAdd (UsrHd usrHd, Integer srcId, Integer dstId, Integer nDims)
void lesSub (UsrHd usrHd, Integer srcId, Integer dstId, Integer nDims)
Real lesDot1 (UsrHd usrHd, Integer srcId, Integer nDims)
Real lesDot2 (UsrHd usrHd, Integer src1Id, Integer src2Id, Integer nDims)
void lesDaxpy (UsrHd usrHd, Integer srcId, Integer dstId, Real coef, Integer nDims)
void lesDxpay (UsrHd usrHd, Integer srcId, Integer dstId, Real coef, Integer nDims)
void lesInv (UsrHd usrHd, Integer dstId, Integer nDims)
void lesBlkDot2 (UsrHd usrHd, Integer src1Id, Integer src2Id, Real *values, Integer mDims, Integer nDims)
void lesBlkDaxpy (UsrHd usrHd, Integer srcId, Integer dstId, Real *coef, Integer mDims, Integer nDims)
void lesBlkDyeax (UsrHd usrHd, Integer srcId, Integer dstId, Real *coef, Integer mDims, Integer nDims)
void lesBlkDmaxpy (UsrHd usrHd, Integer srcId, Integer dstId, Real *coef, Integer mDims, Integer nDims)
void lesVdimCp (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff, Integer nDims)
void lesVdimDot2 (UsrHd usrHd, Integer src1Id, Integer src2Id, Real *coef, Integer nSrc1Dims, Integer src1Off, Integer nSrc2Dims, Integer src2Off, Integer nDims)
void lesVdimDaxpy (UsrHd usrHd, Integer srcId, Integer dstId, Real *coef, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff, Integer nDims)
void lesApG (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
void lesApKG (UsrHd usrHd, Integer src1Id, Integer src2Id, Integer dstId, Integer nSrc1Dims, Integer src1Off, Integer nSrc2Dims, Integer src2Off, Integer nDstDims, Integer dstOff)
void lesApNGt (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
void lesApNGtC (UsrHd usrHd, Integer src1Id, Integer src2Id, Integer dstId, Integer nSrc1Dims, Integer src1Off, Integer nSrc2Dims, Integer src2Off, Integer nDstDims, Integer dstOff)
void lesApFull (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
void lesApSclr (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
void lesPrecPPE (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
Function Documentation
void lesAdd (UsrHd usrHd, Integer srcId, Integer dstId, Integer nDims)
Definition at line 273 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesApFull (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
Definition at line 1104 of file leslib_code_lestools.c.
References _Usr::BC, _Usr::colm, _Usr::flowDiag, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lesP, _Usr::lesQ, _Usr::lhsK, _Usr::lhsP, _Usr::nNodes, _Usr::nnz_tot, _Usr::rowp, and usrPointer().
void lesApG (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
Definition at line 805 of file leslib_code_lestools.c.
References _Usr::BC, _Usr::colm, _Usr::flowDiag, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lesP, _Usr::lesQ, _Usr::lhsP, _Usr::nNodes, _Usr::nnz_tot, _Usr::rowp, and usrPointer().
void lesApKG (UsrHd usrHd, Integer src1Id, Integer src2Id, Integer dstId, Integer nSrc1Dims, Integer src1Off, Integer nSrc2Dims, Integer src2Off, Integer nDstDims, Integer dstOff)
Definition at line 870 of file leslib_code_lestools.c.
References _Usr::BC, _Usr::colm, _Usr::flowDiag, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lesP, _Usr::lesQ, _Usr::lhsK, _Usr::lhsP, _Usr::nNodes, _Usr::nnz_tot, _Usr::rowp, and usrPointer().
void lesApNGt (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
Definition at line 955 of file leslib_code_lestools.c.
References _Usr::BC, _Usr::colm, _Usr::flowDiag, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lesP, _Usr::lesQ, _Usr::lhsP, _Usr::nNodes, _Usr::nnz_tot, _Usr::rowp, and usrPointer().
void lesApNGtC (UsrHd usrHd, Integer src1Id, Integer src2Id, Integer dstId, Integer nSrc1Dims, Integer src1Off, Integer nSrc2Dims, Integer src2Off, Integer nDstDims, Integer dstOff)
Definition at line 1020 of file leslib_code_lestools.c.
References _Usr::BC, _Usr::colm, _Usr::flowDiag, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lesP, _Usr::lesQ, _Usr::lhsP, _Usr::nNodes, _Usr::nnz_tot, _Usr::rowp, and usrPointer().
void lesApSclr (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
Definition at line 1167 of file leslib_code_lestools.c.
References _Usr::BC, _Usr::colm, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lesP, _Usr::lesQ, _Usr::lhsS, _Usr::nNodes, _Usr::nnz_tot, _Usr::rowp, _Usr::sclrDiag, and usrPointer().
void lesBlkDaxpy (UsrHd usrHd, Integer srcId, Integer dstId, Real * coef, Integer mDims, Integer nDims)
Definition at line 565 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesBlkDmaxpy (UsrHd usrHd, Integer srcId, Integer dstId, Real * coef, Integer mDims, Integer nDims)
Definition at line 648 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesBlkDot2 (UsrHd usrHd, Integer src1Id, Integer src2Id, Real * values, Integer mDims, Integer nDims)
Definition at line 516 of file leslib_code_lestools.c.
References malloc(), _Usr::nNodes, and usrPointer().
void lesBlkDyeax (UsrHd usrHd, Integer srcId, Integer dstId, Real * coef, Integer mDims, Integer nDims)
Definition at line 606 of file leslib_code_lestools.c.
References lesZero(), _Usr::nNodes, and usrPointer().
void lesCp (UsrHd usrHd, Integer srcId, Integer dstId, Integer nDims)
Definition at line 177 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesDaxpy (UsrHd usrHd, Integer srcId, Integer dstId, Real coef, Integer nDims)
Definition at line 418 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesDiagScaleCp (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff, Integer diagOff, Integer nDims)
Definition at line 94 of file leslib_code_lestools.c.
References _Usr::eqnType, _Usr::flowDiag, _Usr::nNodes, _Usr::sclrDiag, and usrPointer().
Real lesDot1 (UsrHd usrHd, Integer srcId, Integer nDims)
Definition at line 341 of file leslib_code_lestools.c.
References flesDot1(), _Usr::nNodes, and usrPointer().
Real lesDot2 (UsrHd usrHd, Integer src1Id, Integer src2Id, Integer nDims)
Definition at line 377 of file leslib_code_lestools.c.
References flesDot2(), _Usr::nNodes, and usrPointer().
void lesDxpay (UsrHd usrHd, Integer srcId, Integer dstId, Real coef, Integer nDims)
Definition at line 454 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesInv (UsrHd usrHd, Integer dstId, Integer nDims)
Definition at line 490 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesPrecPPE (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff)
Definition at line 1261 of file leslib_code_lestools.c.
References _Usr::BC, _Usr::colm, _Usr::flowDiag, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lhsK, _Usr::lhsP, _Usr::rowp, and usrPointer().
void lesPrepDiag (UsrHd usrHd)
Definition at line 62 of file leslib_code_lestools.c.
References _Usr::BC, _Usr::colm, _Usr::eqnType, _Usr::flowDiag, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lhsK, _Usr::lhsP, _Usr::lhsS, _Usr::rowp, and _Usr::sclrDiag.
void lesScale (UsrHd usrHd, Integer dstId, Real coef, Integer nDims)
Definition at line 208 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesScaleCp (UsrHd usrHd, Integer srcId, Integer dstId, Real coef, Integer nDims)
Definition at line 237 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesSub (UsrHd usrHd, Integer srcId, Integer dstId, Integer nDims)
Definition at line 307 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesVdimCp (UsrHd usrHd, Integer srcId, Integer dstId, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff, Integer nDims)
Definition at line 689 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesVdimDaxpy (UsrHd usrHd, Integer srcId, Integer dstId, Real * coef, Integer nSrcDims, Integer srcOff, Integer nDstDims, Integer dstOff, Integer nDims)
Definition at line 767 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
void lesVdimDot2 (UsrHd usrHd, Integer src1Id, Integer src2Id, Real * coef, Integer nSrc1Dims, Integer src1Off, Integer nSrc2Dims, Integer src2Off, Integer nDims)
Definition at line 721 of file leslib_code_lestools.c.
References malloc(), _Usr::nNodes, and usrPointer().
void lesZero (UsrHd usrHd, Integer dstId, Integer nDims)
Definition at line 153 of file leslib_code_lestools.c.
References _Usr::nNodes, and usrPointer().
Referenced by lesBlkDyeax().