simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/IncompressibleSolver/Solver/leslib_code_usr.h File Reference
leslib_code_usr.h File Reference
Classes
struct _Usr
Typedefs
typedef struct _Usr Usr
typedef struct _Usr * UsrHd
Functions
void usrNew (UsrHd usrHd, int *eqnType, double *aperm, double *atemp, double *resf, double *solinc, double *flowDiag, double *sclrDiag, double *lesP, double *lesQ, int *iBC, double *BC, int *iper, int *ilwork, int *numpe, int *nNodes, int *nenl, int *nPermDims, int *nTmpDims, int *rowp, int *colm, double *lhsK, double *lhsP, double *lhsS, int nnz, double *CGsol)
double * usrPointer (UsrHd usrHd, int id, int offset, int nDims)
void getSol (UsrHd usrHd, double *Dy)
double flesDot1 (double *a, int *m, int *n)
double flesDot2 (double *a, double *b, int *m, int *n)
Typedef Documentation
typedef struct _Usr Usr
typedef struct _Usr* UsrHd
Definition at line 82 of file leslib_code_usr.h.
Function Documentation
double flesDot1 (double * a, int * m, int * n)
Referenced by lesDot1().
double flesDot2 (double * a, double * b, int * m, int * n)
Referenced by lesDot2().
void getSol (UsrHd usrHd, double * Dy)
Definition at line 44 of file leslib_code_getsol.c.
References _Usr::solinc.
void usrNew (UsrHd usrHd, int * eqnType, double * aperm, double * atemp, double * resf, double * solinc, double * flowDiag, double * sclrDiag, double * lesP, double * lesQ, int * iBC, double * BC, int * iper, int * ilwork, int * numpe, int * nNodes, int * nenl, int * nPermDims, int * nTmpDims, int * rowp, int * colm, double * lhsK, double * lhsP, double * lhsS, int nnz, double * CGsol)
Definition at line 70 of file leslib_code_usr.c.
References _Usr::aperm, _Usr::atemp, _Usr::BC, _Usr::CGsol, _Usr::colm, _Usr::eqnType, _Usr::flowDiag, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lesP, _Usr::lesQ, _Usr::lhsK, _Usr::lhsP, _Usr::lhsS, _Usr::nenl, nenl, _Usr::nNodes, nnz_tot, _Usr::nnz_tot, _Usr::nPermDims, _Usr::nTmpDims, numpe, _Usr::numpe, _Usr::resf, _Usr::rowp, _Usr::sclrDiag, and _Usr::solinc.
double* usrPointer (UsrHd usrHd, int id, int offset, int nDims)
Definition at line 138 of file leslib_code_usr.c.
References _Usr::aperm, _Usr::atemp, _Usr::nNodes, _Usr::nPermDims, _Usr::resf, and _Usr::solinc.
Referenced by lesAdd(), lesApFull(), lesApG(), lesApKG(), lesApNGt(), lesApNGtC(), lesApSclr(), lesBlkDaxpy(), lesBlkDmaxpy(), lesBlkDot2(), lesBlkDyeax(), lesCp(), lesDaxpy(), lesDiagScaleCp(), lesDot1(), lesDot2(), lesDxpay(), lesInv(), lesPrecPPE(), lesScale(), lesScaleCp(), lesSub(), lesVdimCp(), lesVdimDaxpy(), lesVdimDot2(), and lesZero().