simvascular: MyUt Namespace Reference
MyUt Namespace Reference
Typedefs
typedef itk::Image< double, 2 > Double2dITKImageType
typedef itk::Image< float, 2 > Float2dITKImageType
Functions
void getParams (float params[6], const char *filename)
std::vector< std::vector< float > > getParams (const char *filename)
std::vector< std::vector< float > > getSeeds (const char *filename)
std::vector< std::vector< float > > parsePathsFile (const char *filename)
bool isNumber (const char *s)
bool is_number (const std::string &s)
void DeepCopy (Double2dITKImageType::Pointer input, Double2dITKImageType::Pointer output)
void CopyVTKtoITK (vtkStructuredPoints *in, Double2dITKImageType *out)
void CopyITKtoVTK (const Double2dITKImageType *in, vtkStructuredPoints *out)
void vtkSetupResliceImage (vtkSmartPointer< vtkImageReslice > reslice, vtkSmartPointer< vtkPoints > path, int ii)
void vtkResliceImage (vtkSmartPointer< vtkImageImport > importer, vtkSmartPointer< vtkImageReslice > reslice, double axes[16])
void vtkVecToPoints (vtkSmartPointer< vtkPoints > points, std::vector< std::vector< float > > pts)
std::vector< std::vector< float > > vtkPointsToVec (vtkSmartPointer< vtkPoints > points)
vtkSmartPointer< vtkPoints > vtkInterpolatePath (vtkSmartPointer< vtkPoints > points, int numberOfOutputPoints)
void vtkInterpolatePath (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, int numberOfOutputPoints)
void RenderPathSetup (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, vtkSmartPointer< vtkActor > profile, vtkSmartPointer< vtkActor > glyph, int ball[], float tubearg)
void QuickRenderPolyData (vtkPolyData *front, float radius)
template<typename TImage >
void CreateImage (typename TImage::Pointer image, typename TImage::SizeType size, typename TImage::SpacingType spacing, typename TImage::PointType origin, typename TImage::PixelType value)
template<typename TVectorImage >
void CreateImageVectorImage (typename TVectorImage::Pointer image, typename TVectorImage::PixelType value, typename TVectorImage::SizeType size, typename TVectorImage::SpacingType spacing, typename TVectorImage::PointType origin)
template<typename TVectorImage >
void CreateImageVectorImage (typename TVectorImage::Pointer image, typename TVectorImage::PixelType value)
template<typename TImage >
void SetImagePropoties (typename TImage::Pointer image, typename TImage::SpacingType spacing, typename TImage::PointType origin)
template<typename TImage >
void DeepCopy (const TImage *input, typename TImage::Pointer output)
template<typename TImage >
void DeepCopy (typename TImage::Pointer input, typename TImage::Pointer output)
template<class T >
std::vector< T > & split (const std::string &s, char delim, std::vector< T > &elems)
template<class T >
std::vector< T > split (const std::string &s, char delim)
template<typename T >
void printvec (typename std::vector< T > vec)
template<typename T >
void printArray (T *arr, unsigned int length)
bool isInteger (const std::string &s)
template<typename T >
void make2DSeriesTo3D (std::string FilenameBase, std::string FilenameExt, std::string out_filename, int start, int end)
template<typename TvtkObject >
void vtkResliceImage (vtkSmartPointer< TvtkObject > reader, vtkSmartPointer< vtkImageReslice > reslice, double axes[16])
template<typename TvtkObject >
void vtkResliceImage (vtkSmartPointer< TvtkObject >, vtkSmartPointer< vtkImageReslice > reslice)
void RenderPathSetup (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, vtkSmartPointer< vtkActor > profile, vtkSmartPointer< vtkActor > glyph, double ball[3], float tubearg=0.5)
int recast_string (std::string str, int m)
float recast_string (std::string str, float m)
void printArray (int *arr, unsigned int length)
void printArray (double *arr, unsigned int length)
void RenderPathSetup (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, vtkSmartPointer< vtkActor > profile, vtkSmartPointer< vtkActor > glyph, float tubearg=0.5)
void cross (float x[3], float y[3], float z[3])
void cross (double x[3], double y[3], double z[3])
void MakeResliceAxes (double n[3], double p[3], double axes[16])
void MakeResliceAxesFromPoints (double p1[3], double p2[3], double axes[16])
void printAxes (double axes[16])
void SetupRender (vtkSmartPointer< vtkRenderer > renderer, vtkSmartPointer< vtkRenderWindow > renderWindow, vtkSmartPointer< vtkRenderWindowInteractor > renderWindowInteractor)
void printArrays (int extent[6], double spacing[3], double origin[3], double center[3])
void printArrays (double bounds[6], double spacing[3], double origin[3])
void TransformIndexToPhysical (double spacing[3], double origin[3], double in[3], double out[3])
void TransformPhysicalToIndex (double spacing[3], double origin[3], double in[3], int out[3])
template<typename T >
void make2DSeriesTo3DGradient (std::string FilenameBase, std::string FilenameExt, std::string out_filename, int start, int end)
template<typename TInternalImageType >
void WriteImage (const TInternalImageType *image, std::string FilenameBase, std::string FilenameExt, int FileId)
template<typename TInternalImageType >
void make2DSeriesTo3DAbsOverlay (TInternalImageType *image, std::string FilenameBase, std::string FilenameExt, std::string out_filename, int start, int end)
void RenderPathSetup (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, vtkSmartPointer< vtkActor > profile, vtkSmartPointer< vtkActor > glyph, int ball[3], float tubearg=0.5)
Typedef Documentation
typedef itk::Image<double,2> MyUt::Double2dITKImageType
Definition at line 105 of file MyUtils.h.
typedef itk::Image<float,2> MyUt::Float2dITKImageType
Definition at line 106 of file MyUtils.h.
Function Documentation
void MyUt::CopyITKtoVTK (const Double2dITKImageType * in, vtkStructuredPoints * out)
Definition at line 240 of file MyUtils.cxx.
References ConnectITKToVTK().
void MyUt::CopyVTKtoITK (vtkStructuredPoints * in, Double2dITKImageType * out)
Definition at line 227 of file MyUtils.cxx.
References ConnectVTKToITK(), and DeepCopy().
template<typename TImage > void MyUt::CreateImage (typename TImage::Pointer image, typename TImage::SizeType size, typename TImage::SpacingType spacing, typename TImage::PointType origin, typename TImage::PixelType value)
Definition at line 405 of file MyUtils.h.
template<typename TVectorImage > void MyUt::CreateImageVectorImage (typename TVectorImage::Pointer image, typename TVectorImage::PixelType value, typename TVectorImage::SizeType size, typename TVectorImage::SpacingType spacing, typename TVectorImage::PointType origin)
Definition at line 423 of file MyUtils.h.
template<typename TVectorImage > void MyUt::CreateImageVectorImage (typename TVectorImage::Pointer image, typename TVectorImage::PixelType value)
Definition at line 458 of file MyUtils.h.
void MyUt::cross (float x[3], float y[3], float z[3]) inline
Definition at line 217 of file MyUtils.h.
Referenced by vtkvmtkBoundaryReferenceSystems::ComputeBoundaryNormal(), and vtkIntegrateAttributes::IntegrateTriangle().
void MyUt::cross (double x[3], double y[3], double z[3]) inline
Definition at line 225 of file MyUtils.h.
template<typename TImage > void MyUt::DeepCopy (const TImage * input, typename TImage::Pointer output)
Definition at line 388 of file MyUtils.h.
template<typename TImage > void MyUt::DeepCopy (typename TImage::Pointer input, typename TImage::Pointer output)
Definition at line 371 of file MyUtils.h.
void MyUt::DeepCopy (Double2dITKImageType::Pointer input, Double2dITKImageType::Pointer output)
Definition at line 209 of file MyUtils.cxx.
Referenced by CopyVTKtoITK(), vtkvmtkPolyDataManifoldStencil::DeepCopy(), vtkvmtkNeighborhood::DeepCopy(), vtkvmtkDataSetItem::DeepCopy(), and vtkvmtkStencil::DeepCopy().
void MyUt::getParams (float params[6], const char * filename)
Definition at line 11 of file MyUtils.cxx.
std::vector< std::vector< float > > MyUt::getParams (const char * filename)
Definition at line 37 of file MyUtils.cxx.
std::vector<std::vector<float> > MyUt::getSeeds (const char * filename)
Definition at line 70 of file MyUtils.cxx.
bool MyUt::is_number (const std::string & s)
Definition at line 202 of file MyUtils.cxx.
bool MyUt::isInteger (const std::string & s)
bool MyUt::isNumber (const char * s)
Definition at line 181 of file MyUtils.cxx.
Referenced by parsePathsFile().
template<typename T > void MyUt::make2DSeriesTo3D (std::string FilenameBase, std::string FilenameExt, std::string out_filename, int start, int end)
Definition at line 558 of file MyUtils.h.
References T.
template<typename TInternalImageType > void MyUt::make2DSeriesTo3DAbsOverlay (TInternalImageType * image, std::string FilenameBase, std::string FilenameExt, std::string out_filename, int start, int end)
Definition at line 628 of file MyUtils.h.
template<typename T > void MyUt::make2DSeriesTo3DGradient (std::string FilenameBase, std::string FilenameExt, std::string out_filename, int start, int end)
Definition at line 498 of file MyUtils.h.
References T.
void MyUt::MakeResliceAxes (double n[3], double p[3], double axes[16]) inline
Definition at line 233 of file MyUtils.h.
References printArray().
Referenced by MakeResliceAxesFromPoints().
void MyUt::MakeResliceAxesFromPoints (double p1[3], double p2[3], double axes[16]) inline
Definition at line 262 of file MyUtils.h.
References MakeResliceAxes().
Referenced by vtkSetupResliceImage().
std::vector< std::vector< float > > MyUt::parsePathsFile (const char * filename)
Definition at line 115 of file MyUtils.cxx.
References isNumber(), and MAX.
template<typename T > void MyUt::printArray (T * arr, unsigned int length)
Definition at line 362 of file MyUtils.h.
Referenced by MakeResliceAxes(), printArrays(), and vtkSetupResliceImage().
void MyUt::printArray (int * arr, unsigned int length) inline
Definition at line 204 of file MyUtils.h.
void MyUt::printArray (double * arr, unsigned int length) inline
Definition at line 207 of file MyUtils.h.
void MyUt::printArrays (int extent[6], double spacing[3], double origin[3], double center[3]) inline
Definition at line 287 of file MyUtils.h.
References printArray().
void MyUt::printArrays (double bounds[6], double spacing[3], double origin[3]) inline
Definition at line 304 of file MyUtils.h.
References printArray().
void MyUt::printAxes (double axes[16]) inline
Definition at line 272 of file MyUtils.h.
template<typename T > void MyUt::printvec (typename std::vector< T > vec)
Definition at line 354 of file MyUtils.h.
void MyUt::QuickRenderPolyData (vtkPolyData * front, float radius)
Definition at line 460 of file MyUtils.cxx.
References cvVTKNewMacro.
int MyUt::recast_string (std::string str, int m) inline
Inline methods
Definition at line 197 of file MyUtils.h.
Referenced by split().
float MyUt::recast_string (std::string str, float m) inline
Definition at line 200 of file MyUtils.h.
void MyUt::RenderPathSetup (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, vtkSmartPointer< vtkActor > profile, vtkSmartPointer< vtkActor > glyph, int ball[3], float tubearg = 0.5)
void MyUt::RenderPathSetup (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, vtkSmartPointer< vtkActor > profile, vtkSmartPointer< vtkActor > glyph, double ball[3], float tubearg = 0.5)
void MyUt::RenderPathSetup (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, vtkSmartPointer< vtkActor > profile, vtkSmartPointer< vtkActor > glyph, float tubearg = 0.5) inline
Definition at line 210 of file MyUtils.h.
References RenderPathSetup().
void MyUt::RenderPathSetup (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, vtkSmartPointer< vtkActor > profile, vtkSmartPointer< vtkActor > glyph, int ball[], float tubearg)
Definition at line 401 of file MyUtils.cxx.
Referenced by RenderPathSetup().
template<typename TImage > void MyUt::SetImagePropoties (typename TImage::Pointer image, typename TImage::SpacingType spacing, typename TImage::PointType origin)
Definition at line 475 of file MyUtils.h.
void MyUt::SetupRender (vtkSmartPointer< vtkRenderer > renderer, vtkSmartPointer< vtkRenderWindow > renderWindow, vtkSmartPointer< vtkRenderWindowInteractor > renderWindowInteractor) inline
Definition at line 280 of file MyUtils.h.
template<class T > std::vector< T > & MyUt::split (const std::string & s, char delim, std::vector< T > & elems)
Definition at line 337 of file MyUtils.h.
References recast_string(), and T.
template<class T > std::vector< T > MyUt::split (const std::string & s, char delim)
Definition at line 348 of file MyUtils.h.
void MyUt::TransformIndexToPhysical (double spacing[3], double origin[3], double in[3], double out[3]) inline
Definition at line 316 of file MyUtils.h.
void MyUt::TransformPhysicalToIndex (double spacing[3], double origin[3], double in[3], int out[3]) inline
Definition at line 324 of file MyUtils.h.
References Round().
vtkSmartPointer< vtkPoints > MyUt::vtkInterpolatePath (vtkSmartPointer< vtkPoints > points, int numberOfOutputPoints)
Definition at line 351 of file MyUtils.cxx.
void MyUt::vtkInterpolatePath (vtkSmartPointer< vtkPoints > points, vtkSmartPointer< vtkPoints > path, int numberOfOutputPoints)
Definition at line 361 of file MyUtils.cxx.
std::vector<std::vector<float> > MyUt::vtkPointsToVec (vtkSmartPointer< vtkPoints > points)
Definition at line 330 of file MyUtils.cxx.
template<typename TvtkObject > void MyUt::vtkResliceImage (vtkSmartPointer< TvtkObject > reader, vtkSmartPointer< vtkImageReslice > reslice, double axes[16])
Definition at line 795 of file MyUtils.h.
template<typename TvtkObject > void MyUt::vtkResliceImage (vtkSmartPointer< TvtkObject > , vtkSmartPointer< vtkImageReslice > reslice)
VTK Utils
void MyUt::vtkResliceImage (vtkSmartPointer< vtkImageImport > importer, vtkSmartPointer< vtkImageReslice > reslice, double axes[16])
Definition at line 291 of file MyUtils.cxx.
void MyUt::vtkSetupResliceImage (vtkSmartPointer< vtkImageReslice > reslice, vtkSmartPointer< vtkPoints > path, int ii)
Definition at line 257 of file MyUtils.cxx.
References cvVTKNewMacro, MakeResliceAxesFromPoints(), and printArray().
void MyUt::vtkVecToPoints (vtkSmartPointer< vtkPoints > points, std::vector< std::vector< float > > pts)
Definition at line 316 of file MyUtils.cxx.
template<typename TInternalImageType > void MyUt::WriteImage (const TInternalImageType * image, std::string FilenameBase, std::string FilenameExt, int FileId)
Definition at line 602 of file MyUtils.h.