simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/IncompressibleSolver/Solver/partition.cxx File Reference
partition.cxx File Reference
#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <utility>
#include <fstream>
#include <sys/types.h>
#include <sys/stat.h>
#include "cvSolverIO.h"
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <strings.h>
#include "common_c.h"
#include "cvFlowsolverOptions.h"
Classes
struct lessKey
struct CommuTask
Typedefs
typedef vector< int > block
typedef struct lessKey lessKey
typedef map< block, vector
< vector< int > >, lessKey > Block_Map
typedef struct CommuTask CommuTask
Functions
void METIS_PartGraphKway (int *, int *, int *, int *, int *, int *, int *, int *, int *, int *, int *)
void Gather_Headers (int *fileDescriptor, std::vector< std::string > &headers)
int getMaster (int x)
void generate_keyphrase (char *target, const char *prefix, block &tpblock)
void Partition_Problem (int numProcs, char iformat[], char oformat[])
Variables
char keyphrase [100]
char filename [255]
char _directory_name [256]
map< int, map< int, int > > ParallelData
Typedef Documentation
typedef vector< int > block
Definition at line 84 of file partition.cxx.
typedef map< block, vector< vector< int > >, lessKey > Block_Map
Definition at line 102 of file partition.cxx.
typedef struct CommuTask CommuTask
Definition at line 111 of file partition.cxx.
typedef struct lessKey lessKey
Definition at line 101 of file partition.cxx.
Function Documentation
void Gather_Headers (int * fileDescriptor, std::vector< std::string > & headers)
Definition at line 637 of file cvSolverIO.cxx.
References CVSOLVER_IO_OK, and cvsolverIOfp.
Referenced by Partition_Problem().
void generate_keyphrase (char * target, const char * prefix, block & tpblock)
Definition at line 123 of file partition.cxx.
Referenced by Partition_Problem().
int getMaster (int x)
Definition at line 117 of file partition.cxx.
References iter, and ParallelData.
Referenced by Partition_Problem().
void METIS_PartGraphKway (int * , int * , int * , int * , int * , int * , int * , int * , int * , int * , int *)
Referenced by Partition_Problem().
void Partition_Problem (int numProcs, char iformat[], char oformat[])
Definition at line 172 of file partition.cxx.
References _directory_name, c, closefile_(), fgeom, filename, Gather_Headers(), generate_keyphrase(), getMaster(), iter, keyphrase, METIS_PartGraphKway(), ndof, niter, nomodule, nshg, NULL, numel, numelb, numnp, numpbc, openfile_(), CommuTask::other_pid, ParallelData, readdatablock_(), readheader_(), CommuTask::shpFn, CommuTask::tag, CommuTask::type, unlink(), writedatablock_(), writeheader_(), and writestring_().
Referenced by main().
Variable Documentation
char _directory_name[256]
Definition at line 72 of file partition.cxx.
Referenced by Partition_Problem().
char filename[255]
Definition at line 71 of file partition.cxx.
Referenced by fru_ffclos(), fru_ffoprb(), fru_ffoprd(), fru_ffopwr(), FTMKEY(), Geom_SplinePtsToPathPlanCmd(), Image_ReadHeaderCmd(), PostSolver::ParseRestartFile(), Partition_Problem(), PostSolver::QueryNumberOfProcessors(), PostSolver::QueryNumberOfSolutionVariables(), PostSolver::ReadConnectivity(), ReadImage(), readlesrestart_(), Repos_LoadCmd(), Repos_SaveCmd(), savelesrestart_(), TGenUtils_writeDiffAdj(), and cvAdaptCore::writeRestartHessians().
char keyphrase[100]
Definition at line 70 of file partition.cxx.
Referenced by Partition_Problem().
map< int, map< int, int > > ParallelData
Definition at line 85 of file partition.cxx.
Referenced by getMaster(), and Partition_Problem().