simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PostSolver/post_solver.cxx File Reference
post_solver.cxx File Reference
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <math.h>
#include <memory.h>
#include <float.h>
#include <iostream>
#include <string>
#include <vector>
#include <unistd.h>
#include <strings.h>
#include "cvFlowsolverOptions.h"
#include "SimVascular.h"
#include "cvSolverIO.h"
#include "vtkPoints.h"
#include "vtkUnstructuredGrid.h"
#include "vtkDoubleArray.h"
#include "vtkIntArray.h"
#include "vtkIdList.h"
#include "vtkCellType.h"
#include "vtkXMLUnstructuredGridReader.h"
#include "vtkXMLUnstructuredGridWriter.h"
#include "vtkUnstructuredGridWriter.h"
#include "vtkPointData.h"
#include "vtkGeometryFilter.h"
#include "vtkCleanPolyData.h"
#include "vtkXMLPolyDataWriter.h"
#include "vtkPolyDataWriter.h"
#include "vtkCellData.h"
Classes
class PostSolver
Macros
#define gzopen fopen
#define gzprintf fprintf
#define gzFile FILE*
#define gzclose fclose
Functions
int calcMeanWallShearStressAndPressure (int start, int stop, int incr, bool sim_units_cm, vtkPolyData *pd)
int readResidualFromHistorFile (const char *newResFile, std::vector< double > &newRes)
void GetVTUPointData (vtkUnstructuredGrid *model, std::vector< std::string > &pointDataNames)
int main (int argc, char *argv[])
Macro Definition Documentation
#define gzclose fclose
Definition at line 54 of file post_solver.cxx.
Referenced by main().
#define gzFile FILE*
Definition at line 53 of file post_solver.cxx.
#define gzopen fopen
Definition at line 51 of file post_solver.cxx.
Referenced by main().
#define gzprintf fprintf
Definition at line 52 of file post_solver.cxx.
Referenced by main().
Function Documentation
int calcMeanWallShearStressAndPressure (int start, int stop, int incr, bool sim_units_cm, vtkPolyData * pd)
Definition at line 671 of file post_solver.cxx.
References CV_OK, and NULL.
Referenced by main().
void GetVTUPointData (vtkUnstructuredGrid * model, std::vector< std::string > & pointDataNames)
Definition at line 985 of file post_solver.cxx.
Referenced by PostSolver::CompareVTUFiles().
int main (int argc, char * argv[])
Definition at line 1109 of file post_solver.cxx.
References calcMeanWallShearStressAndPressure(), PostSolver::CompareResidualFiles(), PostSolver::CompareVTUFiles(), CV_ERROR, PostSolver::ExportFlowSolverFileFormat(), PostSolver::ExportYBar(), PostSolver::GetConnectivityPtr(), PostSolver::GetCoordinatePtr(), PostSolver::GetNumberOfElements(), PostSolver::GetNumberOfNodalCoordinates(), PostSolver::GetNumberOfProcessorsUsed(), PostSolver::GetNumberOfSolutionVariables(), PostSolver::GetWallProperties(), gzclose, gzopen, gzprintf, NULL, PostSolver::ParseRestartFile(), PostSolver::QueryNumberOfProcessors(), PostSolver::QueryNumberOfSolutionVariables(), PostSolver::ReadConnectivity(), PostSolver::SetInputDirectory(), and PostSolver::SetInputFileType().
int readResidualFromHistorFile (const char * newResFile, std::vector< double > & newRes)
Definition at line 898 of file post_solver.cxx.
References NULL.
Referenced by PostSolver::CompareResidualFiles().