simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PreSolver/presolver-vtk-cmds.cxx File Reference
presolver-vtk-cmds.cxx File Reference
#include "cvFlowsolverOptions.h"
#include "cmd.h"
#include "SimVascular.h"
#include "cvSolverIO.h"
#include "vtkSmartPointer.h"
#include <stdlib.h>
#include "vtkPoints.h"
#include "vtkUnstructuredGrid.h"
#include "vtkDoubleArray.h"
#include "vtkIntArray.h"
#include "vtkIdList.h"
#include "vtkCellType.h"
#include "vtkPointData.h"
#include "vtkGeometryFilter.h"
#include "vtkCleanPolyData.h"
#include "vtkCellData.h"
#include "vtkCellArray.h"
#include "vtkExtractEdges.h"
#include "vtkXMLUnstructuredGridWriter.h"
#include "vtkUnstructuredGridWriter.h"
#include "vtkXMLPolyDataWriter.h"
#include "vtkPolyDataWriter.h"
#include "vtkXMLUnstructuredGridReader.h"
#include "vtkUnstructuredGridReader.h"
#include "vtkXMLPolyDataReader.h"
#include "vtkPolyDataReader.h"
Macros
#define gzopen fopen
#define gzprintf fprintf
#define gzFile FILE*
#define gzclose fclose
#define gzgets fgets
#define gzeof feof
Functions
int writeGEOMBCDAT (char *filename)
int writeRESTARTDAT (char *filename)
int readRESTARTDAT (char *infile, int readSoln, int readDisp, int readAcc)
int parseNum (char *cmd, int *num)
int parseFile (char *cmd)
int NWgetNextNonBlankLine (int *eof)
int NWcloseFile ()
int setNodesWithCode (char *cmd, int val)
int setBoundaryFacesWithCode (char *cmd, int setSurfID, int surfID, int setCode, int code, double value)
int parseDouble (char *cmd, double *num)
int parseDouble2 (char *cmd, double *num)
int parseDouble3 (char *cmd, double *v1, double *v2, double *v3)
int parseCmdStr (char *cmd, char *mystr)
int parseNum2 (char *cmd, int *num)
int check_node_order (int n0, int n1, int n2, int n3, int elementId, int *k0, int *k1, int *k2, int *k3)
void siftDownEdges (int **edges, int root, int bottom, int array_size)
void siftDownKentriesCalcMesh (int **ids, int root, int bottom, int array_size)
void Cross (double ax, double ay, double az, double bx, double by, double bz, double *prodx, double *prody, double *prodz)
double Dot (double ax, double ay, double az, double bx, double by, double bz)
int cmd_mesh_vtu (char *cmd)
int cmd_mesh_and_adjncy_vtu (char *cmd)
Command to generate adjacency from the existing vtu mesh.
int read_variables_vtu (char *vtufn, string presName, string velName, string dispName, bool dispRequired, string tDName, bool tDRequired, string wpName, bool wpRequired)
int cmd_read_all_variables_vtu (char *cmd)
int cmd_read_pressure_velocity_vtu (char *cmd)
int cmd_read_pressure_vtu (char *cmd)
int cmd_read_velocity_vtu (char *cmd)
int cmd_read_displacements_vtu (char *cmd)
int cmd_read_accelerations_vtu (char *cmd)
int cmd_read_varwallprop_vtu (char *cmd)
int cmd_noslip_vtp (char *cmd)
int cmd_prescribed_velocities_vtp (char *cmd)
int setBoundaryFacesWithCodeVTK (char *cmd, int setSurfID, int surfID, int setCode, int code, double value)
int cmd_zero_pressure_vtp (char *cmd)
int cmd_pressure_vtp (char *cmd)
int cmd_deformable_wall_vtp (char *cmd)
int cmd_set_surface_id_vtp (char *cmd)
int cmd_fix_free_edge_nodes_vtp (char *cmd)
int cmd_create_mesh_deformable_vtp (char *cmd)
Variables
char * oformat
int numNodes_
int numElements_
int numMeshEdges_
int numMeshFaces_
int numSolnVars_
int numBoundaryFaces_
int ** boundaryElements_
double * nodes_
int * elements_
int * boundaryElementsIds_
int * xadj_
int xadjSize_
int * adjncy_
int adjncySize_
int * iBC_
int * iBCB_
double * BCB_
double init_p_
double init_v_ [3]
double * soln_
double * dispsoln_
double * acc_
int DisplacementNumElements_
int * DisplacementConn_ [3]
int DisplacementNumNodes_
int * DisplacementNodeMap_
double * DisplacementSolution_
double Displacement_Evw_
double Displacement_nuvw_
double Displacement_thickness_
double Displacement_kcons_
double Displacement_pressure_
FILE * fp_
char buffer_ [1024]
Macro Definition Documentation
#define gzclose fclose
Definition at line 22 of file presolver-vtk-cmds.cxx.
#define gzeof feof
Definition at line 24 of file presolver-vtk-cmds.cxx.
#define gzFile FILE*
Definition at line 21 of file presolver-vtk-cmds.cxx.
#define gzgets fgets
Definition at line 23 of file presolver-vtk-cmds.cxx.
#define gzopen fopen
Definition at line 19 of file presolver-vtk-cmds.cxx.
#define gzprintf fprintf
Definition at line 20 of file presolver-vtk-cmds.cxx.
Function Documentation
int check_node_order (int n0, int n1, int n2, int n3, int elementId, int * k0, int * k1, int * k2, int * k3)
Definition at line 374 of file helpers.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), and cmd_mesh_vtu().
int cmd_create_mesh_deformable_vtp (char * cmd)
Definition at line 1732 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, MAXPATHLEN, NULL, parseCmdStr(), siftDownKentriesCalcMesh(), and stddbg.
int cmd_deformable_wall_vtp (char * cmd)
Definition at line 1471 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), setBoundaryFacesWithCodeVTK(), and stddbg.
int cmd_fix_free_edge_nodes_vtp (char * cmd)
Definition at line 1523 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), edges, iBC_, MAXPATHLEN, NULL, parseCmdStr(), siftDownEdges(), and stddbg.
int cmd_mesh_and_adjncy_vtu (char * cmd)
Command to generate adjacency from the existing vtu mesh.
Author
Adam Updegrove
updeg.nosp@m.a2@g.nosp@m.mail..nosp@m.com
UC Berkeley
shaddenlab.berkeley.edu
Parameters
*char cmd; should just be the vtu file
Returns
CV_OK if function completes properly
Definition at line 398 of file presolver-vtk-cmds.cxx.
References adjncy_, adjncySize_, BCB_, boundaryElements_, boundaryElementsIds_, check_node_order(), CV_ERROR, CV_OK, debugprint(), elements_, iBC_, iBCB_, MAXPATHLEN, nodes_, NULL, numBoundaryFaces_, numElements_, numMeshEdges_, numMeshFaces_, numNodes_, numSolnVars_, parseCmdStr(), stddbg, xadj_, and xadjSize_.
int cmd_mesh_vtu (char * cmd)
Definition at line 147 of file presolver-vtk-cmds.cxx.
References BCB_, boundaryElements_, boundaryElementsIds_, check_node_order(), CV_ERROR, CV_OK, debugprint(), elements_, iBC_, iBCB_, MAXPATHLEN, nodes_, NULL, numBoundaryFaces_, numElements_, numMeshEdges_, numMeshFaces_, numNodes_, numSolnVars_, parseCmdStr(), and stddbg.
int cmd_noslip_vtp (char * cmd)
Definition at line 1183 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), iBC_, MAXPATHLEN, NULL, parseCmdStr(), and stddbg.
Referenced by cmd_prescribed_velocities_vtp().
int cmd_prescribed_velocities_vtp (char * cmd)
Definition at line 1235 of file presolver-vtk-cmds.cxx.
References cmd_noslip_vtp(), CV_OK, debugprint(), and stddbg.
int cmd_pressure_vtp (char * cmd)
Definition at line 1441 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), parseDouble2(), setBoundaryFacesWithCodeVTK(), and stddbg.
int cmd_read_accelerations_vtu (char * cmd)
Definition at line 1119 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_read_all_variables_vtu (char * cmd)
Definition at line 988 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), read_variables_vtu(), and stddbg.
int cmd_read_displacements_vtu (char * cmd)
Definition at line 1087 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_read_pressure_velocity_vtu (char * cmd)
Definition at line 1005 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), read_variables_vtu(), and stddbg.
int cmd_read_pressure_vtu (char * cmd)
Definition at line 1023 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_read_varwallprop_vtu (char * cmd)
Definition at line 1151 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_read_velocity_vtu (char * cmd)
Definition at line 1055 of file presolver-vtk-cmds.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, read_variables_vtu(), and stddbg.
int cmd_set_surface_id_vtp (char * cmd)
Definition at line 1494 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), parseNum2(), setBoundaryFacesWithCodeVTK(), and stddbg.
int cmd_zero_pressure_vtp (char * cmd)
Definition at line 1417 of file presolver-vtk-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), setBoundaryFacesWithCodeVTK(), and stddbg.
void Cross (double ax, double ay, double az, double bx, double by, double bz, double * prodx, double * prody, double * prodz) inline
Definition at line 127 of file presolver-vtk-cmds.cxx.
Referenced by setBoundaryFacesWithCodeVTK().
double Dot (double ax, double ay, double az, double bx, double by, double bz) inline
Definition at line 140 of file presolver-vtk-cmds.cxx.
Referenced by setBoundaryFacesWithCodeVTK().
int NWcloseFile ()
Definition at line 130 of file helpers.cxx.
int NWgetNextNonBlankLine (int * eof)
Definition at line 157 of file helpers.cxx.
int parseCmdStr (char * cmd, char * mystr)
Definition at line 168 of file helpers.cxx.
Referenced by cmd_create_mesh_deformable_vtp(), cmd_fix_free_edge_nodes_vtp(), cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), cmd_noslip_vtp(), cmd_read_all_variables_vtu(), cmd_read_pressure_velocity_vtu(), and setBoundaryFacesWithCodeVTK().
int parseDouble (char * cmd, double * num)
Definition at line 231 of file helpers.cxx.
int parseDouble2 (char * cmd, double * num)
Definition at line 249 of file helpers.cxx.
Referenced by cmd_pressure_vtp().
int parseDouble3 (char * cmd, double * v1, double * v2, double * v3)
Definition at line 278 of file helpers.cxx.
int parseFile (char * cmd)
Definition at line 318 of file helpers.cxx.
int parseNum (char * cmd, int * num)
Definition at line 181 of file helpers.cxx.
int parseNum2 (char * cmd, int * num)
Definition at line 199 of file helpers.cxx.
Referenced by cmd_set_surface_id_vtp().
int read_variables_vtu (char * vtufn, string presName, string velName, string dispName, bool dispRequired, string tDName, bool tDRequired, string wpName, bool wpRequired)
Definition at line 715 of file presolver-vtk-cmds.cxx.
References acc_, CV_ERROR, CV_OK, debugprint(), dispsoln_, NULL, numNodes_, numSolnVars_, soln_, stddbg, and vel.
Referenced by cmd_read_accelerations_vtu(), cmd_read_all_variables_vtu(), cmd_read_displacements_vtu(), cmd_read_pressure_velocity_vtu(), cmd_read_pressure_vtu(), cmd_read_varwallprop_vtu(), and cmd_read_velocity_vtu().
int readRESTARTDAT (char * infile, int readSoln, int readDisp, int readAcc)
Definition at line 1773 of file supre-cmds.cxx.
References acc_, closefile_(), CV_OK, dispsoln_, irstin, lstep, oformat, openfile_(), readdatablock_(), readheader_(), and soln_.
Referenced by cmd_read_restart_accelerations(), cmd_read_restart_displacements(), and cmd_read_restart_solution().
int setBoundaryFacesWithCode (char * cmd, int setSurfID, int surfID, int setCode, int code, double value)
Definition at line 454 of file helpers.cxx.
int setBoundaryFacesWithCodeVTK (char * cmd, int setSurfID, int surfID, int setCode, int code, double value)
Definition at line 1250 of file presolver-vtk-cmds.cxx.
References BCB_, boundaryElements_, boundaryElementsIds_, c, Cross(), CV_ERROR, CV_OK, debugprint(), Dot(), elements_, iBCB_, MAXPATHLEN, nodes_, NULL, numBoundaryFaces_, numElements_, numNodes_, parseCmdStr(), and stddbg.
Referenced by cmd_deformable_wall_vtp(), cmd_pressure_vtp(), cmd_set_surface_id_vtp(), and cmd_zero_pressure_vtp().
int setNodesWithCode (char * cmd, int val)
Definition at line 329 of file helpers.cxx.
void siftDownEdges (int ** edges, int root, int bottom, int array_size)
Definition at line 578 of file helpers.cxx.
Referenced by cmd_fix_free_edge_nodes_vtp(), and fixFreeEdgeNodes().
void siftDownKentriesCalcMesh (int ** ids, int root, int bottom, int array_size)
Definition at line 813 of file helpers.cxx.
Referenced by cmd_create_mesh_deformable_vtp(), and createMeshForDispCalc().
int writeGEOMBCDAT (char * filename)
Definition at line 1940 of file supre-cmds.cxx.
References adjncy_, adjncySize_, BCB_, boundaryElements_, boundaryElementsIds_, closefile_(), CV_ERROR, CV_OK, elements_, iBC_, iBCB_, nelblk, nen, nodes_, NULL, numBoundaryFaces_, numelb, numElements_, numMeshEdges_, numMeshFaces_, numNodes_, numpbc, numSolnVars_, oformat, openfile_(), writeCommonHeader(), writedatablock_(), writeheader_(), writestring_(), xadj_, and xadjSize_.
Referenced by cmd_write_geombcdat().
int writeRESTARTDAT (char * filename)
Definition at line 1822 of file supre-cmds.cxx.
References acc_, closefile_(), CV_ERROR, CV_OK, dispsoln_, init_p_, init_v_, lstep, nshg, NULL, numNodes_, numSolnVars_, oformat, openfile_(), soln_, writeCommonHeader(), writedatablock_(), writeheader_(), and writestring_().
Referenced by cmd_write_restartdat().
Variable Documentation
double* acc_
Definition at line 76 of file supre.cxx.
Referenced by read_variables_vtu().
int* adjncy_
Definition at line 63 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu().
int adjncySize_
Definition at line 64 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu().
double* BCB_
Definition at line 67 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and setBoundaryFacesWithCodeVTK().
int** boundaryElements_
Definition at line 59 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and setBoundaryFacesWithCodeVTK().
int* boundaryElementsIds_
Definition at line 60 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and setBoundaryFacesWithCodeVTK().
char buffer_[1024]
Definition at line 110 of file helpers.cxx.
double Displacement_Evw_
Definition at line 92 of file supre.cxx.
double Displacement_kcons_
Definition at line 95 of file supre.cxx.
double Displacement_nuvw_
Definition at line 93 of file supre.cxx.
double Displacement_pressure_
Definition at line 96 of file supre.cxx.
double Displacement_thickness_
Definition at line 94 of file supre.cxx.
int* DisplacementConn_[3]
Definition at line 83 of file supre.cxx.
Referenced by cmd_create_mesh_deformable_vtp().
int* DisplacementNodeMap_
Definition at line 85 of file supre.cxx.
Referenced by cmd_create_mesh_deformable_vtp().
int DisplacementNumElements_
Definition at line 82 of file supre.cxx.
Referenced by cmd_create_mesh_deformable_vtp().
int DisplacementNumNodes_
Definition at line 84 of file supre.cxx.
Referenced by cmd_create_mesh_deformable_vtp().
double* DisplacementSolution_
Definition at line 86 of file supre.cxx.
double* dispsoln_
Definition at line 71 of file supre.cxx.
Referenced by read_variables_vtu().
int* elements_
Definition at line 58 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and setBoundaryFacesWithCodeVTK().
FILE* fp_
Definition at line 109 of file helpers.cxx.
int* iBC_
Definition at line 65 of file supre.cxx.
Referenced by cmd_fix_free_edge_nodes_vtp(), cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and cmd_noslip_vtp().
int* iBCB_
Definition at line 66 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and setBoundaryFacesWithCodeVTK().
double init_p_
Definition at line 68 of file supre.cxx.
double init_v_[3]
Definition at line 69 of file supre.cxx.
double* nodes_
Definition at line 57 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and setBoundaryFacesWithCodeVTK().
int numBoundaryFaces_
Definition at line 56 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and setBoundaryFacesWithCodeVTK().
int numElements_
Definition at line 52 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and setBoundaryFacesWithCodeVTK().
int numMeshEdges_
Definition at line 53 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), and cmd_mesh_vtu().
int numMeshFaces_
Definition at line 54 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), and cmd_mesh_vtu().
int numNodes_
Definition at line 51 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), read_variables_vtu(), and setBoundaryFacesWithCodeVTK().
int numSolnVars_
Definition at line 55 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), and read_variables_vtu().
char* oformat
Definition at line 46 of file supre.cxx.
double* soln_
Definition at line 70 of file supre.cxx.
Referenced by read_variables_vtu().
int* xadj_
Definition at line 61 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu().
int xadjSize_
Definition at line 62 of file supre.cxx.
Referenced by cmd_mesh_and_adjncy_vtu().