simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PreSolver/supre-cmds.cxx File Reference
supre-cmds.cxx File Reference
#include "cvFlowsolverOptions.h"
#include "cmd.h"
#include "cvSolverIO.h"
#include <stdlib.h>
#include <strings.h>
#include <time.h>
Macros
#define gzopen fopen
#define gzprintf fprintf
#define gzFile FILE*
#define gzclose fclose
#define gzgets fgets
#define gzeof feof
Functions
void Cross (double ax, double ay, double az, double bx, double by, double bz, double *prodx, double *prody, double *prodz)
double Dot (double ax, double ay, double az, double bx, double by, double bz)
int writeGEOMBCDAT (char *filename)
int writeRESTARTDAT (char *filename)
int readRESTARTDAT (char *infile, int readSoln, int readDisp, int readAcc)
int parseNum (char *cmd, int *num)
int parseFile (char *cmd)
int NWgetNextNonBlankLine (int *eof)
int NWcloseFile ()
int setNodesWithCode (char *cmd, int val)
int setBoundaryFacesWithCode (char *cmd, int setSurfID, int surfID, int setCode, int code, double value)
int parseDouble (char *cmd, double *num)
int parseDouble2 (char *cmd, double *num)
int parseDouble3 (char *cmd, double *v1, double *v2, double *v3)
int parseCmdStr (char *cmd, char *mystr)
int parseNum2 (char *cmd, int *num)
int check_node_order (int n0, int n1, int n2, int n3, int elementId, int *k0, int *k1, int *k2, int *k3)
int fixFreeEdgeNodes (char *cmd)
int createMeshForDispCalc (char *cmd)
int cmd_ascii_format (char *)
int cmd_verbose (char *)
int cmd_cvsolver_node_order (char *)
int cmd_number_of_nodes (char *cmd)
int cmd_number_of_elements (char *cmd)
int cmd_number_of_mesh_faces (char *cmd)
int cmd_number_of_mesh_edges (char *cmd)
int cmd_number_of_solnvars (char *cmd)
int cmd_initial_pressure (char *cmd)
int cmd_initial_velocity (char *cmd)
int cmd_nodes (char *cmd)
int cmd_elements (char *cmd)
int cmd_boundary_faces (char *cmd)
int cmd_noslip (char *cmd)
int cmd_prescribed_velocities (char *cmd)
int cmd_fix_free_edge_nodes (char *cmd)
int cmd_create_mesh_deformable (char *cmd)
int cmd_zero_pressure (char *cmd)
int cmd_pressure (char *cmd)
int cmd_deformable_wall (char *cmd)
int cmd_set_surface_id (char *cmd)
int cmd_adjacency (char *cmd)
int cmd_deformable_Evw (char *cmd)
int cmd_deformable_nuvw (char *cmd)
int cmd_deformable_thickness (char *cmd)
int cmd_deformable_kcons (char *cmd)
int cmd_deformable_pressure (char *cmd)
int calcInitDisplacements (double Evw, double nuvw, double thickness, double pressure, double kcons, int use_direct_solve)
int cmd_deformable_solve (char *cmd, int use_direct_solve)
int cmd_deformable_direct_solve (char *cmd)
int cmd_deformable_iterative_solve (char *cmd)
int cmd_deformable_write_vtk_mesh (char *cmd)
int cmd_deformable_write_feap (char *cmd)
int cmd_write_restartdat (char *cmd)
int cmd_read_restart_solution (char *cmd)
int cmd_read_restart_displacements (char *cmd)
int cmd_read_restart_accelerations (char *cmd)
int cmd_write_geombcdat (char *cmd)
int writeCommonHeader (int *filenum)
int cmd_append_displacements (char *cmd)
int cmd_read_displacements (char *cmd)
Variables
char * oformat
int numNodes_
int numElements_
int numMeshEdges_
int numMeshFaces_
int numSolnVars_
int numBoundaryFaces_
int ** boundaryElements_
double * nodes_
int * elements_
int * boundaryElementsIds_
int * xadj_
int xadjSize_
int * adjncy_
int adjncySize_
int * iBC_
int * iBCB_
double * BCB_
double init_p_
double init_v_ [3]
double * soln_
double * dispsoln_
double * acc_
int DisplacementNumElements_
int * DisplacementConn_ [3]
int DisplacementNumNodes_
int * DisplacementNodeMap_
double * DisplacementSolution_
double Displacement_Evw_
double Displacement_nuvw_
double Displacement_thickness_
double Displacement_kcons_
double Displacement_pressure_
FILE * fp_
char buffer_ [1024]
Macro Definition Documentation
#define gzclose fclose
Definition at line 44 of file supre-cmds.cxx.
#define gzeof feof
Definition at line 46 of file supre-cmds.cxx.
#define gzFile FILE*
Definition at line 43 of file supre-cmds.cxx.
#define gzgets fgets
Definition at line 45 of file supre-cmds.cxx.
#define gzopen fopen
Definition at line 41 of file supre-cmds.cxx.
#define gzprintf fprintf
Definition at line 42 of file supre-cmds.cxx.
Function Documentation
int calcInitDisplacements (double Evw, double nuvw, double thickness, double pressure, double kcons, int use_direct_solve)
Definition at line 657 of file displacements.cxx.
References Kentry::col, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, DisplacementSolution_, iBC_, nodes_, NULL, numNodes_, Kentry::row, siftDownKentries(), SPARSE_OFFSET, StanfordIterativeSolve(), StanfordSolveSparseMatrix(), stddbg, stiffnessmatrix(), and Kentry::value.
Referenced by cmd_deformable_solve().
int check_node_order (int n0, int n1, int n2, int n3, int elementId, int * k0, int * k1, int * k2, int * k3)
Definition at line 374 of file helpers.cxx.
References c, Cross(), CV_ERROR, CV_OK, cvsolver_node_order_, debugprint(), Dot(), elements_, nodes_, numElements_, and numNodes_.
Referenced by cmd_boundary_faces(), and cmd_elements().
int cmd_adjacency (char * cmd)
Definition at line 681 of file supre-cmds.cxx.
References adjncy_, adjncySize_, buffer_, CV_ERROR, CV_OK, debugprint(), NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), stddbg, xadj_, and xadjSize_.
int cmd_append_displacements (char * cmd)
Definition at line 1664 of file supre-cmds.cxx.
References closefile_(), CV_ERROR, CV_OK, debugprint(), DisplacementSolution_, dispsoln_, lstep, MAXPATHLEN, nshg, NULL, numNodes_, numSolnVars_, oformat, openfile_(), parseCmdStr(), stddbg, writedatablock_(), and writeheader_().
int cmd_ascii_format (char *)
Definition at line 169 of file supre-cmds.cxx.
References CV_OK, debugprint(), oformat, and stddbg.
int cmd_boundary_faces (char * cmd)
Definition at line 435 of file supre-cmds.cxx.
References boundaryElements_, boundaryElementsIds_, buffer_, check_node_order(), CV_ERROR, CV_OK, debugprint(), NULL, numBoundaryFaces_, numElements_, numMeshFaces_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
int cmd_create_mesh_deformable (char * cmd)
Definition at line 557 of file supre-cmds.cxx.
References createMeshForDispCalc(), CV_ERROR, CV_OK, debugprint(), and stddbg.
int cmd_cvsolver_node_order (char *)
Definition at line 193 of file supre-cmds.cxx.
References CV_OK, cvsolver_node_order_, debugprint(), and stddbg.
int cmd_deformable_direct_solve (char * cmd)
Definition at line 1209 of file supre-cmds.cxx.
References cmd_deformable_solve().
int cmd_deformable_Evw (char * cmd)
Definition at line 747 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_Evw_, parseDouble(), and stddbg.
int cmd_deformable_iterative_solve (char * cmd)
Definition at line 1212 of file supre-cmds.cxx.
References cmd_deformable_solve().
int cmd_deformable_kcons (char * cmd)
Definition at line 807 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_kcons_, parseDouble(), and stddbg.
int cmd_deformable_nuvw (char * cmd)
Definition at line 767 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_nuvw_, parseDouble(), and stddbg.
int cmd_deformable_pressure (char * cmd)
Definition at line 827 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_pressure_, parseDouble(), and stddbg.
int cmd_deformable_solve (char * cmd, int use_direct_solve)
Definition at line 851 of file supre-cmds.cxx.
References calcInitDisplacements(), CV_OK, debugprint(), Displacement_Evw_, Displacement_kcons_, Displacement_nuvw_, Displacement_pressure_, Displacement_thickness_, DisplacementNodeMap_, DisplacementNumNodes_, DisplacementSolution_, dispsoln_, nshg, NULL, numNodes_, and stddbg.
Referenced by cmd_deformable_direct_solve(), and cmd_deformable_iterative_solve().
int cmd_deformable_thickness (char * cmd)
Definition at line 787 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), Displacement_thickness_, parseDouble(), and stddbg.
int cmd_deformable_wall (char * cmd)
Definition at line 628 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), setBoundaryFacesWithCode(), and stddbg.
int cmd_deformable_write_feap (char * cmd)
Definition at line 1379 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, iBC_, MAXPATHLEN, nodes_, NULL, numSolnVars_, parseCmdStr(), and stddbg.
int cmd_deformable_write_vtk_mesh (char * cmd)
Definition at line 1222 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, MAXPATHLEN, nodes_, NULL, numNodes_, numSolnVars_, parseCmdStr(), and stddbg.
int cmd_elements (char * cmd)
Definition at line 379 of file supre-cmds.cxx.
References buffer_, check_node_order(), CV_ERROR, CV_OK, debugprint(), elements_, NULL, numElements_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
int cmd_fix_free_edge_nodes (char * cmd)
Definition at line 542 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), fixFreeEdgeNodes(), and stddbg.
int cmd_initial_pressure (char * cmd)
Definition at line 289 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), init_p_, parseDouble(), and stddbg.
int cmd_initial_velocity (char * cmd)
Definition at line 310 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), init_v_, parseDouble3(), and stddbg.
int cmd_nodes (char * cmd)
Definition at line 331 of file supre-cmds.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), nodes_, NULL, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
int cmd_noslip (char * cmd)
Definition at line 512 of file supre-cmds.cxx.
References CV_OK, debugprint(), setNodesWithCode(), and stddbg.
int cmd_number_of_elements (char * cmd)
Definition at line 220 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numElements_, parseNum(), and stddbg.
int cmd_number_of_mesh_edges (char * cmd)
Definition at line 254 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numMeshEdges_, parseNum(), and stddbg.
int cmd_number_of_mesh_faces (char * cmd)
Definition at line 237 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numMeshFaces_, parseNum(), and stddbg.
int cmd_number_of_nodes (char * cmd)
Definition at line 202 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numNodes_, parseNum(), and stddbg.
int cmd_number_of_solnvars (char * cmd)
Definition at line 271 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), numSolnVars_, parseNum(), and stddbg.
int cmd_prescribed_velocities (char * cmd)
Definition at line 527 of file supre-cmds.cxx.
References CV_OK, debugprint(), setNodesWithCode(), and stddbg.
int cmd_pressure (char * cmd)
Definition at line 597 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), parseDouble2(), setBoundaryFacesWithCode(), and stddbg.
int cmd_read_displacements (char * cmd)
Definition at line 1719 of file supre-cmds.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), dispsoln_, nshg, NULL, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
int cmd_read_restart_accelerations (char * cmd)
Definition at line 1531 of file supre-cmds.cxx.
References CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), readRESTARTDAT(), and stddbg.
int cmd_read_restart_displacements (char * cmd)
Definition at line 1510 of file supre-cmds.cxx.
References CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), readRESTARTDAT(), and stddbg.
int cmd_read_restart_solution (char * cmd)
Definition at line 1489 of file supre-cmds.cxx.
References CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), readRESTARTDAT(), and stddbg.
int cmd_set_surface_id (char * cmd)
Definition at line 652 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), parseNum2(), setBoundaryFacesWithCode(), and stddbg.
int cmd_verbose (char *)
Definition at line 182 of file supre-cmds.cxx.
References CV_OK, debugprint(), stddbg, and verbose_.
int cmd_write_geombcdat (char * cmd)
Definition at line 1599 of file supre-cmds.cxx.
References cmd_token_get(), CV_OK, debugprint(), MAXPATHLEN, MAXSTRINGLENGTH, stddbg, and writeGEOMBCDAT().
int cmd_write_restartdat (char * cmd)
Definition at line 1468 of file supre-cmds.cxx.
References CV_OK, debugprint(), MAXPATHLEN, parseCmdStr(), stddbg, and writeRESTARTDAT().
int cmd_zero_pressure (char * cmd)
Definition at line 572 of file supre-cmds.cxx.
References CV_ERROR, CV_OK, debugprint(), setBoundaryFacesWithCode(), and stddbg.
int createMeshForDispCalc (char * cmd)
Definition at line 854 of file helpers.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), siftDownKentriesCalcMesh(), and stddbg.
Referenced by cmd_create_mesh_deformable().
void Cross (double ax, double ay, double az, double bx, double by, double bz, double * prodx, double * prody, double * prodz) inline
Definition at line 69 of file supre-cmds.cxx.
double Dot (double ax, double ay, double az, double bx, double by, double bz) inline
Definition at line 85 of file supre-cmds.cxx.
int fixFreeEdgeNodes (char * cmd)
Definition at line 620 of file helpers.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), edges, iBC_, NULL, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), siftDownEdges(), and stddbg.
Referenced by cmd_fix_free_edge_nodes().
int NWcloseFile ()
Definition at line 130 of file helpers.cxx.
Referenced by cmd_adjacency(), cmd_boundary_faces(), cmd_elements(), cmd_nodes(), and cmd_read_displacements().
int NWgetNextNonBlankLine (int * eof)
Definition at line 157 of file helpers.cxx.
Referenced by cmd_adjacency(), cmd_boundary_faces(), cmd_elements(), cmd_nodes(), and cmd_read_displacements().
int parseCmdStr (char * cmd, char * mystr)
Definition at line 168 of file helpers.cxx.
References cmd_token_get(), CV_OK, and MAXSTRINGLENGTH.
Referenced by cmd_append_displacements(), cmd_deformable_write_feap(), cmd_deformable_write_vtk_mesh(), cmd_read_restart_accelerations(), cmd_read_restart_displacements(), cmd_read_restart_solution(), cmd_write_restartdat(), parseDouble(), parseFile(), and parseNum().
int parseDouble (char * cmd, double * num)
Definition at line 231 of file helpers.cxx.
References CV_ERROR, CV_OK, MAXSTRINGLENGTH, and parseCmdStr().
Referenced by cmd_deformable_Evw(), cmd_deformable_kcons(), cmd_deformable_nuvw(), cmd_deformable_pressure(), cmd_deformable_thickness(), and cmd_initial_pressure().
int parseDouble2 (char * cmd, double * num)
Definition at line 249 of file helpers.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, and MAXSTRINGLENGTH.
Referenced by cmd_pressure().
int parseDouble3 (char * cmd, double * v1, double * v2, double * v3)
Definition at line 278 of file helpers.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, MAXPATHLEN, and MAXSTRINGLENGTH.
Referenced by cmd_initial_velocity().
int parseFile (char * cmd)
Definition at line 318 of file helpers.cxx.
Referenced by cmd_adjacency(), cmd_boundary_faces(), cmd_elements(), cmd_nodes(), and cmd_read_displacements().
int parseNum (char * cmd, int * num)
Definition at line 181 of file helpers.cxx.
References CV_ERROR, CV_OK, MAXSTRINGLENGTH, and parseCmdStr().
Referenced by cmd_number_of_elements(), cmd_number_of_mesh_edges(), cmd_number_of_mesh_faces(), cmd_number_of_nodes(), and cmd_number_of_solnvars().
int parseNum2 (char * cmd, int * num)
Definition at line 199 of file helpers.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, MAXPATHLEN, and MAXSTRINGLENGTH.
Referenced by cmd_set_surface_id().
int readRESTARTDAT (char * infile, int readSoln, int readDisp, int readAcc)
Definition at line 1773 of file supre-cmds.cxx.
References acc_, closefile_(), CV_OK, dispsoln_, irstin, lstep, oformat, openfile_(), readdatablock_(), readheader_(), and soln_.
Referenced by cmd_read_restart_accelerations(), cmd_read_restart_displacements(), and cmd_read_restart_solution().
int setBoundaryFacesWithCode (char * cmd, int setSurfID, int surfID, int setCode, int code, double value)
Definition at line 454 of file helpers.cxx.
References BCB_, boundaryElements_, boundaryElementsIds_, buffer_, c, Cross(), CV_ERROR, CV_OK, debugprint(), Dot(), elements_, iBCB_, nodes_, NULL, numBoundaryFaces_, numElements_, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
Referenced by cmd_deformable_wall(), cmd_pressure(), cmd_set_surface_id(), and cmd_zero_pressure().
int setNodesWithCode (char * cmd, int val)
Definition at line 329 of file helpers.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), iBC_, NULL, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
Referenced by cmd_noslip(), and cmd_prescribed_velocities().
int writeCommonHeader (int * filenum)
Definition at line 1626 of file supre-cmds.cxx.
References CV_OK, oformat, one, time, writedatablock_(), writeheader_(), and writestring_().
Referenced by writeGEOMBCDAT(), and writeRESTARTDAT().
int writeGEOMBCDAT (char * filename)
Definition at line 1940 of file supre-cmds.cxx.
References adjncy_, adjncySize_, BCB_, boundaryElements_, boundaryElementsIds_, closefile_(), CV_ERROR, CV_OK, elements_, iBC_, iBCB_, nelblk, nen, nodes_, NULL, numBoundaryFaces_, numelb, numElements_, numMeshEdges_, numMeshFaces_, numNodes_, numpbc, numSolnVars_, oformat, openfile_(), writeCommonHeader(), writedatablock_(), writeheader_(), writestring_(), xadj_, and xadjSize_.
Referenced by cmd_write_geombcdat().
int writeRESTARTDAT (char * filename)
Definition at line 1822 of file supre-cmds.cxx.
References acc_, closefile_(), CV_ERROR, CV_OK, dispsoln_, init_p_, init_v_, lstep, nshg, NULL, numNodes_, numSolnVars_, oformat, openfile_(), soln_, writeCommonHeader(), writedatablock_(), writeheader_(), and writestring_().
Referenced by cmd_write_restartdat().
Variable Documentation
double* acc_
Definition at line 76 of file supre.cxx.
Referenced by readRESTARTDAT(), and writeRESTARTDAT().
int* adjncy_
Definition at line 63 of file supre.cxx.
Referenced by cmd_adjacency(), and writeGEOMBCDAT().
int adjncySize_
Definition at line 64 of file supre.cxx.
Referenced by cmd_adjacency(), and writeGEOMBCDAT().
double* BCB_
Definition at line 67 of file supre.cxx.
Referenced by writeGEOMBCDAT().
int** boundaryElements_
Definition at line 59 of file supre.cxx.
Referenced by cmd_boundary_faces(), and writeGEOMBCDAT().
int* boundaryElementsIds_
Definition at line 60 of file supre.cxx.
Referenced by cmd_boundary_faces(), and writeGEOMBCDAT().
char buffer_[1024]
Definition at line 110 of file helpers.cxx.
Referenced by cmd_adjacency(), cmd_boundary_faces(), cmd_elements(), cmd_nodes(), and cmd_read_displacements().
double Displacement_Evw_
Definition at line 92 of file supre.cxx.
Referenced by cmd_deformable_Evw(), and cmd_deformable_solve().
double Displacement_kcons_
Definition at line 95 of file supre.cxx.
Referenced by cmd_deformable_kcons(), and cmd_deformable_solve().
double Displacement_nuvw_
Definition at line 93 of file supre.cxx.
Referenced by cmd_deformable_nuvw(), and cmd_deformable_solve().
double Displacement_pressure_
Definition at line 96 of file supre.cxx.
Referenced by cmd_deformable_pressure(), and cmd_deformable_solve().
double Displacement_thickness_
Definition at line 94 of file supre.cxx.
Referenced by cmd_deformable_solve(), and cmd_deformable_thickness().
int* DisplacementConn_[3]
Definition at line 83 of file supre.cxx.
Referenced by cmd_deformable_write_feap(), and cmd_deformable_write_vtk_mesh().
int* DisplacementNodeMap_
Definition at line 85 of file supre.cxx.
Referenced by cmd_deformable_solve(), cmd_deformable_write_feap(), and cmd_deformable_write_vtk_mesh().
int DisplacementNumElements_
Definition at line 82 of file supre.cxx.
Referenced by cmd_deformable_write_feap(), and cmd_deformable_write_vtk_mesh().
int DisplacementNumNodes_
Definition at line 84 of file supre.cxx.
Referenced by cmd_deformable_solve(), cmd_deformable_write_feap(), and cmd_deformable_write_vtk_mesh().
double* DisplacementSolution_
Definition at line 86 of file supre.cxx.
Referenced by cmd_append_displacements(), and cmd_deformable_solve().
double* dispsoln_
Definition at line 71 of file supre.cxx.
Referenced by cmd_append_displacements(), cmd_deformable_solve(), cmd_read_displacements(), readRESTARTDAT(), and writeRESTARTDAT().
int* elements_
Definition at line 58 of file supre.cxx.
Referenced by cmd_elements(), and writeGEOMBCDAT().
FILE* fp_
Definition at line 109 of file helpers.cxx.
Referenced by NWcloseFile(), NWgetNextLine(), and NWopenFile().
int* iBC_
Definition at line 65 of file supre.cxx.
Referenced by cmd_deformable_write_feap(), and writeGEOMBCDAT().
int* iBCB_
Definition at line 66 of file supre.cxx.
Referenced by writeGEOMBCDAT().
double init_p_
Definition at line 68 of file supre.cxx.
Referenced by cmd_initial_pressure(), main(), and writeRESTARTDAT().
double init_v_[3]
Definition at line 69 of file supre.cxx.
Referenced by cmd_initial_velocity(), main(), and writeRESTARTDAT().
double* nodes_
Definition at line 57 of file supre.cxx.
Referenced by cmd_deformable_write_feap(), cmd_deformable_write_vtk_mesh(), cmd_nodes(), and writeGEOMBCDAT().
int numBoundaryFaces_
Definition at line 56 of file supre.cxx.
Referenced by cmd_boundary_faces(), and writeGEOMBCDAT().
int numElements_
Definition at line 52 of file supre.cxx.
Referenced by cmd_boundary_faces(), cmd_elements(), cmd_number_of_elements(), and writeGEOMBCDAT().
int numMeshEdges_
Definition at line 53 of file supre.cxx.
Referenced by cmd_number_of_mesh_edges(), and writeGEOMBCDAT().
int numMeshFaces_
Definition at line 54 of file supre.cxx.
Referenced by cmd_boundary_faces(), cmd_number_of_mesh_faces(), and writeGEOMBCDAT().
int numNodes_
Definition at line 51 of file supre.cxx.
Referenced by cmd_append_displacements(), cmd_deformable_solve(), cmd_deformable_write_vtk_mesh(), cmd_nodes(), cmd_number_of_nodes(), cmd_read_displacements(), writeGEOMBCDAT(), and writeRESTARTDAT().
int numSolnVars_
Definition at line 55 of file supre.cxx.
Referenced by cmd_append_displacements(), cmd_deformable_write_feap(), cmd_deformable_write_vtk_mesh(), cmd_number_of_solnvars(), writeGEOMBCDAT(), and writeRESTARTDAT().
char* oformat
Definition at line 46 of file supre.cxx.
Referenced by cmd_append_displacements(), cmd_ascii_format(), readRESTARTDAT(), writeCommonHeader(), writeGEOMBCDAT(), and writeRESTARTDAT().
double* soln_
Definition at line 70 of file supre.cxx.
Referenced by readRESTARTDAT(), and writeRESTARTDAT().
int* xadj_
Definition at line 61 of file supre.cxx.
Referenced by cmd_adjacency(), and writeGEOMBCDAT().
int xadjSize_
Definition at line 62 of file supre.cxx.
Referenced by cmd_adjacency(), and writeGEOMBCDAT().