simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/IncompressibleSolver/Solver/write_restart_files.c File Reference
write_restart_files.c File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include <time.h>
#include "mpi.h"
#include "cvSolverIO.h"
#include "cvFlowsolverOptions.h"
#include <unistd.h>
#include <strings.h>
Functions
void Write_Restart (int *pid, int *stepno, int *nshg, int *numVars, double *array1, double *array2)
void Write_Error (int *pid, int *stepno, int *nshg, int *numVars, double *array1)
void Write_Displ (int *pid, int *stepno, int *nshg, int *numVars, double *array1)
Variables
char cvsolver_iotype [80]
Function Documentation
void Write_Displ (int * pid, int * stepno, int * nshg, int * numVars, double * array1)
Definition at line 220 of file write_restart_files.c.
References closefile_(), CVSOLVER_IO_ERROR, cvsolver_iotype, irstou, openfile_(), time, writedatablock_(), and writeheader_().
void Write_Error (int * pid, int * stepno, int * nshg, int * numVars, double * array1)
Definition at line 180 of file write_restart_files.c.
References closefile_(), CVSOLVER_IO_ERROR, cvsolver_iotype, irstou, openfile_(), time, writedatablock_(), and writeheader_().
void Write_Restart (int * pid, int * stepno, int * nshg, int * numVars, double * array1, double * array2)
Definition at line 77 of file write_restart_files.c.
References closefile_(), CVSOLVER_IO_ERROR, cvsolver_iotype, irstou, openfile_(), time, writedatablock_(), writeheader_(), and writestring_().
Variable Documentation
char cvsolver_iotype[80]
Definition at line 60 of file input_fform.cxx.
Referenced by input_fform(), main(), Write_Displ(), Write_Error(), and Write_Restart().