simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/TetAdapt/AdaptHelpers.cxx File Reference
AdaptHelpers.cxx File Reference
#include "AdaptHelpers.h"
Functions
void readParametersFromFile (char *filename, char *fieldName, int &nshg, int &numVars)
void readArrayFromFile (char *filename, char *fieldName, double *&valueArray)
void writeArrayToFile (char *filename, char *fieldName, char *outputFormat, char *mode, int nshg, int numVars, int stepNumber, double *valueArray)
Function Documentation
void readArrayFromFile (char * filename, char * fieldName, double *& valueArray)
Definition at line 76 of file AdaptHelpers.cxx.
References closefile_(), nshg, openfile_(), readdatablock_(), and readheader_().
Referenced by cvTetAdapt::Adapt().
void readParametersFromFile (char * filename, char * fieldName, int & nshg, int & numVars)
Definition at line 43 of file AdaptHelpers.cxx.
References closefile_(), openfile_(), and readheader_().
void writeArrayToFile (char * filename, char * fieldName, char * outputFormat, char * mode, int nshg, int numVars, int stepNumber, double * valueArray)
Definition at line 125 of file AdaptHelpers.cxx.
References closefile_(), nshg, openfile_(), time, writedatablock_(), writeheader_(), and writestring_().
Referenced by cvTetAdapt::Adapt().