simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/UI/main.cxx File Reference
main.cxx File Reference
#include "SimVascular.h"
#include "cvIOstream.h"
#include <time.h>
#include <stdlib.h>
#include "tcl.h"
#include "tk.h"
#include "cv_globals.h"
Functions
CV_DLL_EXPORT int SimVascular_Init (Tcl_Interp *interp)
void SimVascularWelcome (Tcl_Interp *interp)
int main (int argc, char *argv[])
int Tcl_AppInit (Tcl_Interp *interp)
Variables
FILE * simvascularstdout
FILE * simvascularstderr
Function Documentation
int main (int argc, char * argv[])
Definition at line 69 of file main.cxx.
References gSimVascularBatchMode, L, NULL, simvascularstderr, simvascularstdout, and Tcl_AppInit().
CV_DLL_EXPORT int SimVascular_Init (Tcl_Interp * interp)
Definition at line 145 of file gdscInit.cxx.
References Gdscmesh_Init(), Gdscpost_Init(), Geom_Init(), Getinterp_Init(), Image_Init(), itkls2d_Init(), itkls3d_Init(), itkutils_Init(), Lsetcore_Init(), Lsetv_Init(), Math_Init(), Meshsimdiscretesolid_Init(), Meshsimmesh_Init(), myVtk_Init(), Parasolidsolid_Init(), PolyDataSolid_Init(), Repos_Init(), SimVascularWelcome(), Solid_Init(), and Tetgenmesh_Init().
Referenced by Tcl_AppInit().
void SimVascularWelcome (Tcl_Interp * interp)
Definition at line 115 of file gdscInit.cxx.
Referenced by SimVascular_Init().
int Tcl_AppInit (Tcl_Interp * interp)
Definition at line 279 of file main.cxx.
References gSimVascularBatchMode, and SimVascular_Init().
Referenced by main().
Variable Documentation
FILE* simvascularstderr
Definition at line 67 of file main.cxx.
Referenced by main().
FILE* simvascularstdout
Definition at line 66 of file main.cxx.
Referenced by main().