simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/Adaptor/Adapt/MeshSimInternal_phAdapt.h File Reference
MeshSimInternal_phAdapt.h File Reference
#include "MeshSim.h"
Functions
void fix4NodesOnSurface (pMesh mesh)
void V_info (pVertex)
void R_info (pRegion)
Function Documentation
void fix4NodesOnSurface (pMesh mesh)
void R_info (pRegion)
void V_info (pVertex)
Referenced by cvAdaptCore::InterpolateSolution(), cvAdaptCore::ModifyHessiansAtBdry(), cvAdaptCore::SmoothErrorIndicators(), cvAdaptCore::SmoothHessians(), cvAdaptCore::V_AnalyticHessian(), and cvAdaptCore::writeSmoothEIs().