simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/IncompressibleSolver/Solver/main.cxx File Reference
main.cxx File Reference
#include "cvFlowsolverOptions.h"
#include "mpi.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <iostream>
#include <unistd.h>
Functions
void Partition_Problem (int, char[], char[])
void proces ()
void input (int *size, int *myrank)
int input_fform (char inpfname[])
void catchDebugger ()
void pdarray (void *darray, int start, int end)
void piarray (void *iarray, int start, int end)
int main (int argc, char *argv[])
Variables
char cvsolver_iotype [80]
int myrank
FILE * simvascular_flowsolver_stdout
FILE * simvascular_flowsolver_stderr
Function Documentation
void catchDebugger ()
Definition at line 88 of file main.cxx.
Referenced by main().
void input (int * size, int * myrank)
Referenced by vtkvmtkUnstructuredGridTetraFilter::Execute(), main(), vtkIntegrateFlowThroughSurface::RequestData(), vtkvmtkPolyDataBoundaryExtractor::RequestData(), vtkvmtkPolyDataToUnstructuredGridFilter::RequestData(), vtkvmtkUnstructuredGridTetraFilter::RequestData(), vtkvmtkPolyDataSizingFunction::RequestData(), vtkvmtkSurfaceProjection::RequestData(), vtkvmtkSimpleCapPolyData::RequestData(), vtkIntegrateAttributes::RequestData(), vtkSurfaceVectors::RequestData(), vtkvmtkNonManifoldSteepestDescent::RequestData(), vtkvmtkVoronoiDiagram3D::RequestData(), vtkvmtkPolyDataDistanceToCenterlines::RequestData(), vtkvmtkCapPolyData::RequestData(), vtkGetBoundaryFaces::RequestData(), vtkvmtkBoundaryReferenceSystems::RequestData(), vtkvmtkSimplifyVoronoiDiagram::RequestData(), vtkvmtkInternalTetrahedraExtractor::RequestData(), vtkvmtkSteepestDescentLineTracer::RequestData(), vtkvmtkPolyDataCenterlines::RequestData(), vtkvmtkBoundaryLayerGenerator::RequestData(), vtkvmtkNonManifoldFastMarching::RequestData(), vtkvmtkPolyDataSurfaceRemeshing::RequestData(), vtkBooleanOperationPolyDataFilter2::Impl::RunLoopTest(), and vtkIntersectionPolyDataFilter2::Impl::SplitMesh().
int input_fform (char inpfname[])
Definition at line 70 of file input_fform.cxx.
References aerfrc, conpar, cvsolver_iotype, genpar, Input::GetValue(), incomp, inpdat, intdat, matdat, MAXSURF, myrank, nomodule, outpar, print_error_code(), sclrs, sequence, solpar, timdat, and timpar.
Referenced by input_fform_(), and main().
int main (int argc, char * argv[])
Definition at line 116 of file main.cxx.
References catchDebugger(), cvsolver_iotype, input(), input_fform(), myrank, NULL, Partition_Problem(), proces(), simvascular_flowsolver_stderr, and simvascular_flowsolver_stdout.
void Partition_Problem (int , char [], char [])
Definition at line 172 of file partition.cxx.
References _directory_name, c, closefile_(), fgeom, filename, Gather_Headers(), generate_keyphrase(), getMaster(), iter, keyphrase, METIS_PartGraphKway(), ndof, niter, nomodule, nshg, NULL, numel, numelb, numnp, numpbc, openfile_(), CommuTask::other_pid, ParallelData, readdatablock_(), readheader_(), CommuTask::shpFn, CommuTask::tag, CommuTask::type, unlink(), writedatablock_(), writeheader_(), and writestring_().
Referenced by main().
void pdarray (void * darray, int start, int end)
Definition at line 96 of file main.cxx.
void piarray (void * iarray, int start, int end)
Definition at line 103 of file main.cxx.
void proces ()
Referenced by main().
Variable Documentation
char cvsolver_iotype[80]
Definition at line 77 of file main.cxx.
Referenced by main(), readlesrestart_(), savelesrestart_(), Write_Displ(), Write_Error(), and Write_Restart().
int myrank
Definition at line 85 of file main.cxx.
Referenced by Input::EchoInputMap(), Input::GetValue(), Input::Input(), input_fform(), and main().
FILE* simvascular_flowsolver_stderr
Definition at line 111 of file main.cxx.
Referenced by main().
FILE* simvascular_flowsolver_stdout
Definition at line 110 of file main.cxx.
Referenced by main().