simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PreSolver/Transient_Laplace_Solve.cxx File Reference
Transient_Laplace_Solve.cxx File Reference
#include "cvFlowsolverOptions.h"
#include <stdlib.h>
#include <math.h>
#include "cmd.h"
#include "cvSolverIO.h"
#include <time.h>
#include "gmresfortran.h"
Classes
struct Kentry
Functions
int parseFile (char *cmd)
int NWcloseFile ()
int NWgetNextNonBlankLine (int *eof)
void Cross (double ax, double ay, double az, double bx, double by, double bz, double *prodx, double *prody, double *prodz)
double Dot (double ax, double ay, double az, double bx, double by, double bz)
double Norm (double ax, double ay, double az)
void SubVec (double ax, double ay, double az, double bx, double by, double bz, double *prodx, double *prody, double *prodz)
void Mat3Vec (double mat[3][3], double v[3], double *prodx, double *prody, double *prodz)
double stiffmatrixlocal (double x[4][3], double kab[4][4])
double massmatrixlocal (double x[4][3], double mab[4][4])
void add2ST (Kentry Kentries[], int &NNZ, double newval, int addrow, int addcol)
void matvec_triad (Kentry Kentries[], int &NNZ, double x[], double y[], int isym)
int CallFortranGMRES (Kentry *Kentries, int NNZ, double *b, int nunknown, double *u)
int calcEvwDistribution ()
Variables
double * EvwSolution_
char buffer_ [1024]
int * iBC_
double * gBC_
int numNodes_
int numElements_
double * nodes_
int * elements_
Function Documentation
void add2ST (Kentry Kentries[], int & NNZ, double newval, int addrow, int addcol)
Definition at line 185 of file Laplace_Solve.cxx.
References Kentry::col, Kentry::row, and Kentry::value.
Referenced by calcEvwDistribution(), and calcThicknessEvwDistribution().
int calcEvwDistribution ()
Definition at line 206 of file Transient_Laplace_Solve.cxx.
References add2ST(), CallFortranGMRES(), elements_, EvwSolution_, gBC_, massmatrixlocal(), matvec_triad(), nodes_, numElements_, numNodes_, and stiffmatrixlocal().
int CallFortranGMRES (Kentry * Kentries, int NNZ, double * b, int nunknown, double * u)
Definition at line 200 of file Laplace_Solve.cxx.
References Kentry::col, free(), gmresfortran(), M, malloc(), Kentry::row, and Kentry::value.
Referenced by calcEvwDistribution(), and calcThicknessEvwDistribution().
void Cross (double ax, double ay, double az, double bx, double by, double bz, double * prodx, double * prody, double * prodz) inline
Definition at line 41 of file Transient_Laplace_Solve.cxx.
double Dot (double ax, double ay, double az, double bx, double by, double bz) inline
Definition at line 57 of file Transient_Laplace_Solve.cxx.
double massmatrixlocal (double x[4][3], double mab[4][4])
Definition at line 119 of file Transient_Laplace_Solve.cxx.
Referenced by calcEvwDistribution().
void Mat3Vec (double mat[3][3], double v[3], double * prodx, double * prody, double * prodz) inline
Definition at line 102 of file Transient_Laplace_Solve.cxx.
void matvec_triad (Kentry Kentries[], int & NNZ, double x[], double y[], int isym)
Definition at line 181 of file Transient_Laplace_Solve.cxx.
References Kentry::col, and Kentry::row.
Referenced by calcEvwDistribution().
double Norm (double ax, double ay, double az) inline
Definition at line 72 of file Transient_Laplace_Solve.cxx.
int NWcloseFile ()
Definition at line 130 of file helpers.cxx.
References CV_OK, fp_, gzclose, and NULL.
Referenced by createMeshForDispCalc(), fixFreeEdgeNodes(), setBoundaryFacesWithCode(), and setNodesWithCode().
int NWgetNextNonBlankLine (int * eof)
Definition at line 157 of file helpers.cxx.
References buffer_, CV_ERROR, CV_OK, MAXCMDLINELENGTH, and NWgetNextLine().
Referenced by createMeshForDispCalc(), fixFreeEdgeNodes(), setBoundaryFacesWithCode(), and setNodesWithCode().
int parseFile (char * cmd)
Definition at line 318 of file helpers.cxx.
References MAXPATHLEN, NWopenFile(), and parseCmdStr().
Referenced by createMeshForDispCalc(), fixFreeEdgeNodes(), setBoundaryFacesWithCode(), and setNodesWithCode().
double stiffmatrixlocal (double x[4][3], double kab[4][4])
Definition at line 115 of file Laplace_Solve.cxx.
Referenced by calcEvwDistribution(), and calcThicknessEvwDistribution().
void SubVec (double ax, double ay, double az, double bx, double by, double bz, double * prodx, double * prody, double * prodz) inline
Definition at line 86 of file Transient_Laplace_Solve.cxx.
Variable Documentation
char buffer_[1024]
Definition at line 110 of file helpers.cxx.
Referenced by createMeshForDispCalc(), fixFreeEdgeNodes(), NWgetNextLine(), NWgetNextNonBlankLine(), setBoundaryFacesWithCode(), and setNodesWithCode().
int* elements_
Definition at line 58 of file supre.cxx.
Referenced by calcEvwDistribution().
double* EvwSolution_
Referenced by calcEvwDistribution().
double* gBC_
Referenced by calcEvwDistribution().
int* iBC_
Definition at line 65 of file supre.cxx.
double* nodes_
Definition at line 57 of file supre.cxx.
Referenced by calcEvwDistribution().
int numElements_
Definition at line 52 of file supre.cxx.
Referenced by calcEvwDistribution().
int numNodes_
Definition at line 51 of file supre.cxx.
Referenced by calcEvwDistribution().