simvascular: vtkvmtkBoundaryReferenceSystems Class Reference
vtkvmtkBoundaryReferenceSystems Class Reference
#include <vtkvmtkBoundaryReferenceSystems.h>
Public Member Functions
vtkTypeMacro (vtkvmtkBoundaryReferenceSystems, vtkPolyDataAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
vtkSetStringMacro (BoundaryRadiusArrayName)
vtkGetStringMacro (BoundaryRadiusArrayName)
vtkSetStringMacro (BoundaryNormalsArrayName)
vtkGetStringMacro (BoundaryNormalsArrayName)
vtkSetStringMacro (Point1ArrayName)
vtkGetStringMacro (Point1ArrayName)
vtkSetStringMacro (Point2ArrayName)
vtkGetStringMacro (Point2ArrayName)
Static Public Member Functions
static
vtkvmtkBoundaryReferenceSystems * New ()
static void ComputeBoundaryBarycenter (vtkPoints *points, double barycenter[3])
static double ComputeBoundaryMeanRadius (vtkPoints *points, double barycenter[3])
static void ComputeBoundaryNormal (vtkPoints *points, double barycenter[3], double normal[3])
static void OrientBoundaryNormalOutwards (vtkPolyData *surface, vtkPolyData *boundaries, vtkIdType boundaryCellId, double normal[3], double outwardNormal[3])
static void ComputeReferenceSystemPoints (double origin[3], double normal[3], double radius, double point1[3], double point2[3])
Protected Member Functions
vtkvmtkBoundaryReferenceSystems ()
~vtkvmtkBoundaryReferenceSystems ()
virtual int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
Protected Attributes
char * BoundaryRadiusArrayName
char * BoundaryNormalsArrayName
char * Point1ArrayName
char * Point2ArrayName
Private Member Functions
vtkvmtkBoundaryReferenceSystems (const vtkvmtkBoundaryReferenceSystems &)
void operator= (const vtkvmtkBoundaryReferenceSystems &)
Detailed Description
Definition at line 36 of file vtkvmtkBoundaryReferenceSystems.h.
Constructor & Destructor Documentation
vtkvmtkBoundaryReferenceSystems::vtkvmtkBoundaryReferenceSystems () protected
Definition at line 38 of file vtkvmtkBoundaryReferenceSystems.cxx.
References BoundaryNormalsArrayName, BoundaryRadiusArrayName, NULL, Point1ArrayName, and Point2ArrayName.
vtkvmtkBoundaryReferenceSystems::~vtkvmtkBoundaryReferenceSystems () protected
Definition at line 46 of file vtkvmtkBoundaryReferenceSystems.cxx.
References BoundaryNormalsArrayName, BoundaryRadiusArrayName, NULL, Point1ArrayName, and Point2ArrayName.
vtkvmtkBoundaryReferenceSystems::vtkvmtkBoundaryReferenceSystems (const vtkvmtkBoundaryReferenceSystems &) private
Member Function Documentation
void vtkvmtkBoundaryReferenceSystems::ComputeBoundaryBarycenter (vtkPoints * points, double barycenter[3]) static
Definition at line 73 of file vtkvmtkBoundaryReferenceSystems.cxx.
References VTK_VMTK_DOUBLE_TOL.
Referenced by vtkvmtkCapPolyData::RequestData(), and RequestData().
double vtkvmtkBoundaryReferenceSystems::ComputeBoundaryMeanRadius (vtkPoints * points, double barycenter[3]) static
Definition at line 112 of file vtkvmtkBoundaryReferenceSystems.cxx.
Referenced by vtkvmtkCapPolyData::RequestData(), and RequestData().
void vtkvmtkBoundaryReferenceSystems::ComputeBoundaryNormal (vtkPoints * points, double barycenter[3], double normal[3]) static
Definition at line 130 of file vtkvmtkBoundaryReferenceSystems.cxx.
References Cross(), MyUt::cross(), and point.
Referenced by vtkvmtkCapPolyData::RequestData(), and RequestData().
void vtkvmtkBoundaryReferenceSystems::ComputeReferenceSystemPoints (double origin[3], double normal[3], double radius, double point1[3], double point2[3]) static
Definition at line 242 of file vtkvmtkBoundaryReferenceSystems.cxx.
References Cross().
Referenced by RequestData().
static vtkvmtkBoundaryReferenceSystems* vtkvmtkBoundaryReferenceSystems::New () static
void vtkvmtkBoundaryReferenceSystems::operator= (const vtkvmtkBoundaryReferenceSystems &) private
void vtkvmtkBoundaryReferenceSystems::OrientBoundaryNormalOutwards (vtkPolyData * surface, vtkPolyData * boundaries, vtkIdType boundaryCellId, double normal[3], double outwardNormal[3]) static
Definition at line 169 of file vtkvmtkBoundaryReferenceSystems.cxx.
References c, Dot(), and Round().
Referenced by vtkvmtkCapPolyData::RequestData(), and RequestData().
void vtkvmtkBoundaryReferenceSystems::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 373 of file vtkvmtkBoundaryReferenceSystems.cxx.
int vtkvmtkBoundaryReferenceSystems::RequestData (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected virtual
Definition at line 266 of file vtkvmtkBoundaryReferenceSystems.cxx.
References BoundaryNormalsArrayName, BoundaryRadiusArrayName, ComputeBoundaryBarycenter(), ComputeBoundaryMeanRadius(), ComputeBoundaryNormal(), ComputeReferenceSystemPoints(), input(), vtkvmtkPolyDataBoundaryExtractor::New(), OrientBoundaryNormalOutwards(), Point1ArrayName, and Point2ArrayName.
vtkvmtkBoundaryReferenceSystems::vtkGetStringMacro (BoundaryRadiusArrayName)
vtkvmtkBoundaryReferenceSystems::vtkGetStringMacro (BoundaryNormalsArrayName)
vtkvmtkBoundaryReferenceSystems::vtkGetStringMacro (Point1ArrayName)
vtkvmtkBoundaryReferenceSystems::vtkGetStringMacro (Point2ArrayName)
vtkvmtkBoundaryReferenceSystems::vtkSetStringMacro (BoundaryRadiusArrayName)
vtkvmtkBoundaryReferenceSystems::vtkSetStringMacro (BoundaryNormalsArrayName)
vtkvmtkBoundaryReferenceSystems::vtkSetStringMacro (Point1ArrayName)
vtkvmtkBoundaryReferenceSystems::vtkSetStringMacro (Point2ArrayName)
vtkvmtkBoundaryReferenceSystems::vtkTypeMacro (vtkvmtkBoundaryReferenceSystems , vtkPolyDataAlgorithm)
Member Data Documentation
char* vtkvmtkBoundaryReferenceSystems::BoundaryNormalsArrayName protected
Definition at line 77 of file vtkvmtkBoundaryReferenceSystems.h.
Referenced by RequestData(), vtkvmtkBoundaryReferenceSystems(), and ~vtkvmtkBoundaryReferenceSystems().
char* vtkvmtkBoundaryReferenceSystems::BoundaryRadiusArrayName protected
Definition at line 76 of file vtkvmtkBoundaryReferenceSystems.h.
Referenced by RequestData(), vtkvmtkBoundaryReferenceSystems(), and ~vtkvmtkBoundaryReferenceSystems().
char* vtkvmtkBoundaryReferenceSystems::Point1ArrayName protected
Definition at line 78 of file vtkvmtkBoundaryReferenceSystems.h.
Referenced by RequestData(), vtkvmtkBoundaryReferenceSystems(), and ~vtkvmtkBoundaryReferenceSystems().
char* vtkvmtkBoundaryReferenceSystems::Point2ArrayName protected
Definition at line 79 of file vtkvmtkBoundaryReferenceSystems.h.
Referenced by RequestData(), vtkvmtkBoundaryReferenceSystems(), and ~vtkvmtkBoundaryReferenceSystems().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkBoundaryReferenceSystems.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkBoundaryReferenceSystems.cxx