simvascular: vtkIntersectionPolyDataFilter2::Impl Class Reference
vtkIntersectionPolyDataFilter2::Impl Class Reference
Public Member Functions
Impl ()
virtual ~Impl ()
int SplitMesh (int inputIndex, vtkPolyData *output, vtkPolyData *intersectionLines)
Static Public Member Functions
static int FindTriangleIntersections (vtkOBBNode *node0, vtkOBBNode *node1, vtkMatrix4x4 *transform, void *arg)
Public Attributes
vtkPolyData * Mesh [2]
vtkOBBTree * OBBTree1
vtkCellArray * IntersectionLines
vtkIdTypeArray * SurfaceId
vtkIdTypeArray * NewCellIds [2]
vtkIdTypeArray * CellIds [2]
vtkIdTypeArray * PointCellIds [2]
vtkIntArray * BoundaryPoints [2]
vtkPointLocator * PointMerger
IntersectionMapType * IntersectionMap [2]
IntersectionMapType * IntersectionPtsMap [2]
IntersectionMapType * PointMapper
PointEdgeMapType * PointEdgeMap [2]
Protected Member Functions
vtkCellArray * SplitCell (vtkPolyData *input, vtkIdType cellId, vtkIdType *cellPts, IntersectionMapType *map, vtkPolyData *interLines, int inputIndex, int numCurrCells)
int AddToPointEdgeMap (int index, vtkIdType ptId, double x[3], vtkPolyData *mesh, vtkIdType cellId, vtkIdType edgeId, vtkIdType lineId, vtkIdType triPts[3])
void AddToNewCellMap (int inputIndex, int interPtCount, int interPts[3], vtkPolyData *interLines, int numCurrCells)
void GetLoops (vtkPolyData *pd, std::vector< simPolygon > *loops)
void GetSingleLoop (vtkPolyData *pd, simPolygon *loop, vtkIdType nextCell, bool *interPtBool, bool *lineBool)
void FollowLoopOrientation (vtkPolyData *pd, simPolygon *loop, vtkIdType *nextCell, vtkIdType nextPt, vtkIdType prevPt, vtkIdList *pointCells)
void SetLoopOrientation (vtkPolyData *pd, simPolygon *loop, vtkIdType *nextCell, vtkIdType nextPt, vtkIdType prevPt, vtkIdList *pointCells)
int GetLoopOrientation (vtkPolyData *pd, vtkIdType cell, vtkIdType ptId1, vtkIdType ptId2, int first)
void Orient (vtkPolyData *pd, vtkTransform *transform, vtkPolyData *boundary, vtkPolygon *boundarypoly)
int TestConcave (double line1[3], double line2[3], int orientation)
int CheckLine (vtkPolyData *pd, vtkIdType ptId1, vtkIdType ptId2)
void GetTransform (vtkTransform *transform, vtkPoints *points)
Impl (const Impl &)
void operator= (const Impl &)
Detailed Description
Definition at line 90 of file vtkIntersectionPolyDataFilter2.cxx.
Constructor & Destructor Documentation
vtkIntersectionPolyDataFilter2::Impl::Impl ()
Definition at line 183 of file vtkIntersectionPolyDataFilter2.cxx.
References CellIds, IntersectionMap, IntersectionPtsMap, Mesh, NULL, PointEdgeMap, and PointMapper.
vtkIntersectionPolyDataFilter2::Impl::~Impl () virtual
Definition at line 198 of file vtkIntersectionPolyDataFilter2.cxx.
vtkIntersectionPolyDataFilter2::Impl::Impl (const Impl &) protected
Member Function Documentation
void vtkIntersectionPolyDataFilter2::Impl::AddToNewCellMap (int inputIndex, int interPtCount, int interPts[3], vtkPolyData * interLines, int numCurrCells) protected
Definition at line 1250 of file vtkIntersectionPolyDataFilter2.cxx.
int vtkIntersectionPolyDataFilter2::Impl::AddToPointEdgeMap (int index, vtkIdType ptId, double x[3], vtkPolyData * mesh, vtkIdType cellId, vtkIdType edgeId, vtkIdType lineId, vtkIdType triPts[3]) protected
Definition at line 1207 of file vtkIntersectionPolyDataFilter2.cxx.
References _CellEdgeLine::CellId, _CellEdgeLine::EdgeId, and _CellEdgeLine::LineId.
Referenced by FindTriangleIntersections().
int vtkIntersectionPolyDataFilter2::Impl::CheckLine (vtkPolyData * pd, vtkIdType ptId1, vtkIdType ptId2) protected
Definition at line 2320 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections().
int vtkIntersectionPolyDataFilter2::Impl::FindTriangleIntersections (vtkOBBNode * node0, vtkOBBNode * node1, vtkMatrix4x4 * transform, void * arg) static
Definition at line 212 of file vtkIntersectionPolyDataFilter2.cxx.
References AddToPointEdgeMap(), CellIds, CheckLine(), IntersectionLines, IntersectionMap, IntersectionPtsMap, Mesh, OBBTree1, PointCellIds, PointMerger, SurfaceId, and vtkIntersectionPolyDataFilter2::TriangleTriangleIntersection().
Referenced by vtkIntersectionPolyDataFilter2::RequestData().
void vtkIntersectionPolyDataFilter2::Impl::FollowLoopOrientation (vtkPolyData * pd, simPolygon * loop, vtkIdType * nextCell, vtkIdType nextPt, vtkIdType prevPt, vtkIdList * pointCells) protected
Definition at line 2062 of file vtkIntersectionPolyDataFilter2.cxx.
References Dot(), and simPolygon::orientation.
int vtkIntersectionPolyDataFilter2::Impl::GetLoopOrientation (vtkPolyData * pd, vtkIdType cell, vtkIdType ptId1, vtkIdType ptId2, int first) protected
Definition at line 2197 of file vtkIntersectionPolyDataFilter2.cxx.
void vtkIntersectionPolyDataFilter2::Impl::GetLoops (vtkPolyData * pd, std::vector< simPolygon > * loops) protected
Definition at line 1870 of file vtkIntersectionPolyDataFilter2.cxx.
References simPoint::id, iter, simPolygon::points, and simPoint::pt.
void vtkIntersectionPolyDataFilter2::Impl::GetSingleLoop (vtkPolyData * pd, simPolygon * loop, vtkIdType nextCell, bool * interPtBool, bool * lineBool) protected
Definition at line 1943 of file vtkIntersectionPolyDataFilter2.cxx.
References simPoint::id, simPolygon::orientation, simPolygon::points, and simPoint::pt.
void vtkIntersectionPolyDataFilter2::Impl::GetTransform (vtkTransform * transform, vtkPoints * points) protected
Definition at line 2340 of file vtkIntersectionPolyDataFilter2.cxx.
References Cross(), and Dot().
void vtkIntersectionPolyDataFilter2::Impl::operator= (const Impl &) protected
void vtkIntersectionPolyDataFilter2::Impl::Orient (vtkPolyData * pd, vtkTransform * transform, vtkPolyData * boundary, vtkPolygon * boundarypoly) protected
Definition at line 2241 of file vtkIntersectionPolyDataFilter2.cxx.
References iter.
void vtkIntersectionPolyDataFilter2::Impl::SetLoopOrientation (vtkPolyData * pd, simPolygon * loop, vtkIdType * nextCell, vtkIdType nextPt, vtkIdType prevPt, vtkIdList * pointCells) protected
Definition at line 2140 of file vtkIntersectionPolyDataFilter2.cxx.
References Dot(), and simPolygon::orientation.
vtkCellArray * vtkIntersectionPolyDataFilter2::Impl::SplitCell (vtkPolyData * input, vtkIdType cellId, vtkIdType * cellPts, IntersectionMapType * map, vtkPolyData * interLines, int inputIndex, int numCurrCells) protected
Definition at line 629 of file vtkIntersectionPolyDataFilter2.cxx.
References c, Dot(), and iter.
int vtkIntersectionPolyDataFilter2::Impl::SplitMesh (int inputIndex, vtkPolyData * output, vtkPolyData * intersectionLines)
Definition at line 422 of file vtkIntersectionPolyDataFilter2.cxx.
References Dot(), and input().
Referenced by vtkIntersectionPolyDataFilter2::RequestData().
int vtkIntersectionPolyDataFilter2::Impl::TestConcave (double line1[3], double line2[3], int orientation) protected
Definition at line 2295 of file vtkIntersectionPolyDataFilter2.cxx.
Member Data Documentation
vtkIntArray* vtkIntersectionPolyDataFilter2::Impl::BoundaryPoints[2]
Definition at line 161 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by vtkIntersectionPolyDataFilter2::RequestData().
vtkIdTypeArray* vtkIntersectionPolyDataFilter2::Impl::CellIds[2]
Definition at line 152 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections(), Impl(), and vtkIntersectionPolyDataFilter2::RequestData().
vtkCellArray* vtkIntersectionPolyDataFilter2::Impl::IntersectionLines
Definition at line 145 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections(), and vtkIntersectionPolyDataFilter2::RequestData().
IntersectionMapType* vtkIntersectionPolyDataFilter2::Impl::IntersectionMap[2]
Definition at line 168 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections(), and Impl().
IntersectionMapType* vtkIntersectionPolyDataFilter2::Impl::IntersectionPtsMap[2]
Definition at line 169 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections(), and Impl().
vtkPolyData* vtkIntersectionPolyDataFilter2::Impl::Mesh[2]
Definition at line 141 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections(), Impl(), and vtkIntersectionPolyDataFilter2::RequestData().
vtkIdTypeArray* vtkIntersectionPolyDataFilter2::Impl::NewCellIds[2]
Definition at line 148 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by vtkIntersectionPolyDataFilter2::RequestData().
vtkOBBTree* vtkIntersectionPolyDataFilter2::Impl::OBBTree1
Definition at line 142 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections(), and vtkIntersectionPolyDataFilter2::RequestData().
vtkIdTypeArray* vtkIntersectionPolyDataFilter2::Impl::PointCellIds[2]
Definition at line 160 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections(), and vtkIntersectionPolyDataFilter2::RequestData().
PointEdgeMapType* vtkIntersectionPolyDataFilter2::Impl::PointEdgeMap[2]
Definition at line 174 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by Impl().
IntersectionMapType* vtkIntersectionPolyDataFilter2::Impl::PointMapper
Definition at line 170 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by Impl(), and vtkIntersectionPolyDataFilter2::RequestData().
vtkPointLocator* vtkIntersectionPolyDataFilter2::Impl::PointMerger
Definition at line 165 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections(), and vtkIntersectionPolyDataFilter2::RequestData().
vtkIdTypeArray* vtkIntersectionPolyDataFilter2::Impl::SurfaceId
Definition at line 147 of file vtkIntersectionPolyDataFilter2.cxx.
Referenced by FindTriangleIntersections(), and vtkIntersectionPolyDataFilter2::RequestData().
The documentation for this class was generated from the following file:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkIntersectionPolyDataFilter2.cxx