simvascular: cvPolyData Class Reference
cvPolyData Class Reference
#include <cvPolyData.h>
Public Member Functions
cvPolyData ()
cvPolyData (vtkPolyData *pd)
cvPolyData (cvPolyData *pd)
~cvPolyData ()
double FindDistance2 (double x, double y, double z)
double FindDistance (double x, double y, double z)
double FindDistance2 (double x, double y, double z, double radius)
double FindDistance (double x, double y, double z, double radius)
vtkPolyData * GetVtkPolyData ()
void SetDistMethod (PolyData_DistanceT dt)
PolyData_DistanceT GetDistMethod ()
Public Member Functions inherited from cvDataSet
cvDataSet (RepositoryDataT type)
~cvDataSet ()
Public Member Functions inherited from cvDataObject
cvDataObject (RepositoryDataT type)
virtual ~cvDataObject ()
vtkDataObject * GetVtkPtr ()
virtual int GetMemoryUsage ()
Public Member Functions inherited from cvRepositoryData
cvRepositoryData (RepositoryDataT type)
virtual ~cvRepositoryData ()
void Lock ()
void Release ()
int NumLocks ()
RepositoryDataT GetType ()
char * GetName ()
void SetName (char *in)
int GetNumLabels ()
void GetLabelKeys (int *numKeys, char **keys[])
int IsLabelPresent (char *key)
int GetLabel (char *key, char **value)
int SetLabel (char *key, char *value)
void ClearLabel (char *key)
Private Member Functions
int InitDistance ()
int BuildVtkCellLocator ()
void ClearVtkCellLocator ()
Private Attributes
PolyData_DistanceT distMethod_
vtkCellLocator * locator_
vtkGenericCell * genericCell_
Additional Inherited Members
Protected Member Functions inherited from cvDataSet
void ShallowCopy (vtkDataSet *src)
Protected Attributes inherited from cvDataObject
vtkDataObject * data_
Detailed Description
Definition at line 47 of file cvPolyData.h.
Constructor & Destructor Documentation
cvPolyData::cvPolyData ()
Definition at line 44 of file cvPolyData.cxx.
References cvDataObject::data_, distMethod_, genericCell_, locator_, NULL, and PD_DIST_VTK.
cvPolyData::cvPolyData (vtkPolyData * pd)
Definition at line 60 of file cvPolyData.cxx.
References cvDataObject::data_, distMethod_, genericCell_, locator_, NULL, PD_DIST_VTK, and cvDataSet::ShallowCopy().
cvPolyData::cvPolyData (cvPolyData * pd)
Definition at line 77 of file cvPolyData.cxx.
References cvDataObject::data_, distMethod_, genericCell_, locator_, NULL, PD_DIST_VTK, and cvDataSet::ShallowCopy().
cvPolyData::~cvPolyData ()
Definition at line 95 of file cvPolyData.cxx.
References ClearVtkCellLocator().
Member Function Documentation
int cvPolyData::BuildVtkCellLocator () private
Definition at line 260 of file cvPolyData.cxx.
References CV_ERROR, CV_OK, cvDataObject::data_, genericCell_, locator_, and NULL.
Referenced by InitDistance().
void cvPolyData::ClearVtkCellLocator () private
Definition at line 289 of file cvPolyData.cxx.
References genericCell_, locator_, and NULL.
Referenced by ~cvPolyData().
double cvPolyData::FindDistance (double x, double y, double z)
Definition at line 146 of file cvPolyData.cxx.
References CV_OK, distMethod_, FindDistance2(), InitDistance(), and PD_DIST_VTK.
Referenced by cvLevelSetSparseGrid::ConstructHT_Sweep(), cvParasolidSolidModel::Distance(), cvLevelSetDenseGrid::InitPhi(), and cvLevelSetSparseGrid::ReinitPhi().
double cvPolyData::FindDistance (double x, double y, double z, double radius)
Definition at line 219 of file cvPolyData.cxx.
References CV_OK, FindDistance2(), and InitDistance().
double cvPolyData::FindDistance2 (double x, double y, double z)
Definition at line 105 of file cvPolyData.cxx.
References CV_OK, cvDataObject::data_, distMethod_, genericCell_, InitDistance(), locator_, PD_DIST_INVALID, and PD_DIST_VTK.
Referenced by cvLevelSetSparseGrid::ConstructHT(), and FindDistance().
double cvPolyData::FindDistance2 (double x, double y, double z, double radius)
Definition at line 174 of file cvPolyData.cxx.
References CV_OK, distMethod_, genericCell_, InitDistance(), locator_, PD_DIST_INVALID, and PD_DIST_VTK.
PolyData_DistanceT cvPolyData::GetDistMethod () inline
Definition at line 64 of file cvPolyData.h.
References distMethod_.
vtkPolyData* cvPolyData::GetVtkPolyData () inline
Definition at line 61 of file cvPolyData.h.
References cvDataObject::data_.
Referenced by cvCalculateWallShearStress::CalcAvgPointData(), cvCalculateWallShearStress::CalcOSI(), cvCalculateWallShearStress::CalcWallShearMean(), cvCalculateWallShearStress::CalcWallShearPulse(), cvITKLevelSet::GenerateSeedImage(), cvLevelSetStructuredGrid::GetBoundaryData(), cvParasolidSolidModel::MakePoly2dPts(), cvParasolidSolidModel::MakePoly3dSolid(), cvMeshSimDiscreteSolidModel::MakePoly3dSolid(), cvParasolidSolidModel::MakePoly3dSurface(), cvLevelSetDenseGrid::ReinitPhi(), cvLevelSetSparseGrid::ReinitPhi(), cvCalculateTKE::SetInputData(), cvCalculateWallShearStress::SetSurfaceMesh(), cvCalculateWallShearStress::SetTensors(), cvCalculateWallShearStress::SetTractions(), sys_geom_2DWindingNum(), sys_geom_Align(), sys_geom_AlignByDist(), sys_geom_AvgPt(), sys_geom_BBox(), sys_geom_checksurface(), sys_geom_Classify(), sys_geom_DeepCopy(), sys_geom_DisorientProfile(), sys_geom_GetClosedLineRegion(), sys_geom_GetOrderedPts(), sys_geom_getPolyCentroid(), sys_geom_IntegrateEnergy(), sys_geom_IntegrateScalarSurf(), sys_geom_IntegrateScalarThresh(), sys_geom_IntegrateSurface(), sys_geom_IntegrateSurface2(), sys_geom_InterpolateScalar(), sys_geom_InterpolateVector(), sys_geom_intersect(), sys_geom_IntersectWithLine(), sys_geom_MakePolysConsistent(), sys_geom_mathPointData(), sys_geom_MergePts_tol(), sys_geom_NumClosedLineRegions(), sys_geom_OrientProfile(), sys_geom_Pick(), sys_geom_PolysClosed(), sys_geom_PrintSmallPolys(), sys_geom_PrintTriStats(), sys_geom_Project(), sys_geom_PtInPoly(), sys_geom_Reduce(), sys_geom_ReplacePointData(), sys_geom_ReverseAllCells(), sys_geom_RmSmallPolys(), sys_geom_sampleLoop(), sys_geom_ScaleAvg(), sys_geom_subtract(), sys_geom_SurfArea(), sys_geom_Translate(), sys_geom_union(), sys_geom_warp3dPts(), and sys_geom_WriteLines().
int cvPolyData::InitDistance () inline private
Definition at line 84 of file cvPolyData.h.
References BuildVtkCellLocator(), CV_ERROR, CV_OK, distMethod_, genericCell_, locator_, NULL, and PD_DIST_VTK.
Referenced by FindDistance(), and FindDistance2().
void cvPolyData::SetDistMethod (PolyData_DistanceT dt)
Definition at line 240 of file cvPolyData.cxx.
References distMethod_, PD_DIST_INVALID, and PD_DIST_VTK.
Member Data Documentation
PolyData_DistanceT cvPolyData::distMethod_ private
Definition at line 68 of file cvPolyData.h.
Referenced by cvPolyData(), FindDistance(), FindDistance2(), GetDistMethod(), InitDistance(), and SetDistMethod().
vtkGenericCell* cvPolyData::genericCell_ private
Definition at line 74 of file cvPolyData.h.
Referenced by BuildVtkCellLocator(), ClearVtkCellLocator(), cvPolyData(), FindDistance2(), and InitDistance().
vtkCellLocator* cvPolyData::locator_ private
Definition at line 73 of file cvPolyData.h.
Referenced by BuildVtkCellLocator(), ClearVtkCellLocator(), cvPolyData(), FindDistance2(), and InitDistance().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvPolyData.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvPolyData.cxx