simvascular: vtkvmtkMinHeap Class Reference
vtkvmtkMinHeap Class Reference
#include <vtkvmtkMinHeap.h>
Public Member Functions
vtkTypeMacro (vtkvmtkMinHeap, vtkObject)
void PrintSelf (ostream &os, vtkIndent indent)
void Initialize ()
vtkSetObjectMacro (MinHeapScalars, vtkDoubleArray)
vtkGetObjectMacro (MinHeapScalars, vtkDoubleArray)
int GetSize ()
void InsertNextId (vtkIdType id)
void UpdateId (vtkIdType id)
vtkIdType GetMin ()
vtkIdType RemoveMin ()
Static Public Member Functions
static vtkvmtkMinHeap * New ()
Protected Member Functions
vtkvmtkMinHeap ()
~vtkvmtkMinHeap ()
void Swap (vtkIdType loc0, vtkIdType loc1)
int IsLeaf (vtkIdType loc)
vtkIdType GetLeftChild (vtkIdType loc)
vtkIdType GetRightChild (vtkIdType loc)
vtkIdType GetParent (vtkIdType loc)
void SiftUp (vtkIdType loc)
void SiftDown (vtkIdType loc)
vtkIdType RemoveAt (vtkIdType loc)
Protected Attributes
vtkIdList * Heap
vtkIdList * BackPointers
vtkDoubleArray * MinHeapScalars
Private Member Functions
vtkvmtkMinHeap (const vtkvmtkMinHeap &)
void operator= (const vtkvmtkMinHeap &)
Detailed Description
Definition at line 41 of file vtkvmtkMinHeap.h.
Constructor & Destructor Documentation
vtkvmtkMinHeap::vtkvmtkMinHeap () protected
Definition at line 31 of file vtkvmtkMinHeap.cxx.
References BackPointers, Heap, MinHeapScalars, and NULL.
vtkvmtkMinHeap::~vtkvmtkMinHeap () protected
Definition at line 38 of file vtkvmtkMinHeap.cxx.
References BackPointers, Heap, MinHeapScalars, and NULL.
vtkvmtkMinHeap::vtkvmtkMinHeap (const vtkvmtkMinHeap &) private
Member Function Documentation
vtkIdType vtkvmtkMinHeap::GetLeftChild (vtkIdType loc) protected
Definition at line 146 of file vtkvmtkMinHeap.cxx.
References Heap.
Referenced by SiftDown().
vtkIdType vtkvmtkMinHeap::GetMin ()
Definition at line 287 of file vtkvmtkMinHeap.cxx.
References Heap.
vtkIdType vtkvmtkMinHeap::GetParent (vtkIdType loc) protected
Definition at line 180 of file vtkvmtkMinHeap.cxx.
Referenced by SiftUp().
vtkIdType vtkvmtkMinHeap::GetRightChild (vtkIdType loc) protected
Definition at line 163 of file vtkvmtkMinHeap.cxx.
References Heap.
int vtkvmtkMinHeap::GetSize ()
Definition at line 106 of file vtkvmtkMinHeap.cxx.
References Heap.
Referenced by vtkvmtkNonManifoldFastMarching::Propagate().
void vtkvmtkMinHeap::Initialize ()
Definition at line 50 of file vtkvmtkMinHeap.cxx.
References BackPointers, Heap, MinHeapScalars, and NULL.
Referenced by vtkvmtkNonManifoldFastMarching::InitPropagation().
void vtkvmtkMinHeap::InsertNextId (vtkIdType id)
Definition at line 71 of file vtkvmtkMinHeap.cxx.
References BackPointers, Heap, MinHeapScalars, NULL, and SiftUp().
Referenced by vtkvmtkNonManifoldFastMarching::UpdateNeighborhood().
int vtkvmtkMinHeap::IsLeaf (vtkIdType loc) protected
Definition at line 129 of file vtkvmtkMinHeap.cxx.
References Heap.
Referenced by SiftDown().
static vtkvmtkMinHeap* vtkvmtkMinHeap::New () static
Referenced by vtkvmtkNonManifoldFastMarching::vtkvmtkNonManifoldFastMarching().
void vtkvmtkMinHeap::operator= (const vtkvmtkMinHeap &) private
void vtkvmtkMinHeap::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 342 of file vtkvmtkMinHeap.cxx.
vtkIdType vtkvmtkMinHeap::RemoveAt (vtkIdType loc) protected
Definition at line 296 of file vtkvmtkMinHeap.cxx.
References BackPointers, Heap, SiftDown(), and Swap().
vtkIdType vtkvmtkMinHeap::RemoveMin ()
Definition at line 269 of file vtkvmtkMinHeap.cxx.
References BackPointers, Heap, SiftDown(), and Swap().
Referenced by vtkvmtkNonManifoldFastMarching::Propagate().
void vtkvmtkMinHeap::SiftDown (vtkIdType loc) protected
Definition at line 227 of file vtkvmtkMinHeap.cxx.
References GetLeftChild(), Heap, IsLeaf(), MinHeapScalars, NULL, Swap(), and VTK_VMTK_DOUBLE_TOL.
Referenced by RemoveAt(), and RemoveMin().
void vtkvmtkMinHeap::SiftUp (vtkIdType loc) protected
Definition at line 194 of file vtkvmtkMinHeap.cxx.
References GetParent(), Heap, MinHeapScalars, NULL, Swap(), and VTK_VMTK_DOUBLE_TOL.
Referenced by InsertNextId(), and UpdateId().
void vtkvmtkMinHeap::Swap (vtkIdType loc0, vtkIdType loc1) protected
Definition at line 321 of file vtkvmtkMinHeap.cxx.
References BackPointers, and Heap.
Referenced by RemoveAt(), RemoveMin(), SiftDown(), and SiftUp().
void vtkvmtkMinHeap::UpdateId (vtkIdType id)
Definition at line 111 of file vtkvmtkMinHeap.cxx.
References BackPointers, MinHeapScalars, NULL, and SiftUp().
Referenced by vtkvmtkNonManifoldFastMarching::UpdateNeighborhood().
vtkvmtkMinHeap::vtkGetObjectMacro (MinHeapScalars , vtkDoubleArray)
vtkvmtkMinHeap::vtkSetObjectMacro (MinHeapScalars , vtkDoubleArray)
vtkvmtkMinHeap::vtkTypeMacro (vtkvmtkMinHeap , vtkObject)
Member Data Documentation
vtkIdList* vtkvmtkMinHeap::BackPointers protected
Definition at line 92 of file vtkvmtkMinHeap.h.
Referenced by Initialize(), InsertNextId(), RemoveAt(), RemoveMin(), Swap(), UpdateId(), vtkvmtkMinHeap(), and ~vtkvmtkMinHeap().
vtkIdList* vtkvmtkMinHeap::Heap protected
Definition at line 91 of file vtkvmtkMinHeap.h.
Referenced by GetLeftChild(), GetMin(), GetRightChild(), GetSize(), Initialize(), InsertNextId(), IsLeaf(), RemoveAt(), RemoveMin(), SiftDown(), SiftUp(), Swap(), vtkvmtkMinHeap(), and ~vtkvmtkMinHeap().
vtkDoubleArray* vtkvmtkMinHeap::MinHeapScalars protected
Definition at line 94 of file vtkvmtkMinHeap.h.
Referenced by Initialize(), InsertNextId(), SiftDown(), SiftUp(), UpdateId(), vtkvmtkMinHeap(), and ~vtkvmtkMinHeap().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkMinHeap.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/vtkvmtkMinHeap.cxx