simvascular: cvLevelSetVelocity Class Reference
cvLevelSetVelocity Class Reference abstract
#include <cvLevelSetVelocity.h>
Public Member Functions
cvLevelSetVelocity ()
virtual ~cvLevelSetVelocity ()
int LinkLevelSet (cvLevelSet *ls)
int UnlinkLevelSet ()
int GetLevelSet (cvLevelSet **ls)
int UpdateTolerance ()
void SetStopV (double d)
double GetStopV ()
virtual int Valid ()
virtual int StopCondition ()
virtual int Evaluate (double pos[], double *f0, double *f1, double v[], int *forceFlag, double toDot[])=0
virtual int GetMemoryUsage ()=0
Public Attributes
char tclName_ [CV_STRLEN]
Protected Attributes
cvLevelSet * ls_
double tol_
double stopV_
Friends
class cvLevelSet
Detailed Description
Definition at line 56 of file cvLevelSetVelocity.h.
Constructor & Destructor Documentation
cvLevelSetVelocity::cvLevelSetVelocity ()
Definition at line 43 of file cvLevelSetVelocity.cxx.
References FindMachineEpsilon(), ls_, NULL, stopV_, and tol_.
cvLevelSetVelocity::~cvLevelSetVelocity () virtual
Definition at line 59 of file cvLevelSetVelocity.cxx.
References ls_, NULL, and cvLevelSet::UnlinkVelocity().
Member Function Documentation
virtual int cvLevelSetVelocity::Evaluate (double pos[], double * f0, double * f1, double v[], int * forceFlag, double toDot[]) pure virtual
Implemented in cvLevelSetVelocityExponentialDecay, cvLevelSetVelocityKGI, cvLevelSetVelocityPotential, cvLevelSetVelocitySmooth, cvLevelSetVelocityThreshold, and cvLevelSetVelocityConstant.
Referenced by cvLevelSetStructuredGrid::EvaluateV().
int cvLevelSetVelocity::GetLevelSet (cvLevelSet ** ls)
Definition at line 120 of file cvLevelSetVelocity.cxx.
References CV_OK, and ls_.
Referenced by cvLevelSet::LinkVelocity().
virtual int cvLevelSetVelocity::GetMemoryUsage () pure virtual
Implemented in cvLevelSetVelocityExponentialDecay, cvLevelSetVelocityKGI, cvLevelSetVelocityPotential, cvLevelSetVelocitySmooth, cvLevelSetVelocityThreshold, and cvLevelSetVelocityConstant.
Referenced by cvLevelSet::GetMemoryUsage(), and LsetV_GetMemoryUsageMtd().
double cvLevelSetVelocity::GetStopV () inline
Definition at line 70 of file cvLevelSetVelocity.h.
References stopV_.
Referenced by LsetV_GetStopVMtd(), and cvLevelSet::StopCondition().
int cvLevelSetVelocity::LinkLevelSet (cvLevelSet * ls)
Definition at line 71 of file cvLevelSetVelocity.cxx.
References CV_ERROR, CV_OK, cvLevelSet::GetVelocity(), cvLevelSet::LinkVelocity(), ls_, NULL, UnlinkLevelSet(), and UpdateTolerance().
Referenced by cvLevelSet::LinkVelocity().
void cvLevelSetVelocity::SetStopV (double d) inline
Definition at line 69 of file cvLevelSetVelocity.h.
References stopV_.
Referenced by LsetV_SetStopVMtd().
virtual int cvLevelSetVelocity::StopCondition () inline virtual
Reimplemented in cvLevelSetVelocityExponentialDecay, cvLevelSetVelocityKGI, cvLevelSetVelocityPotential, cvLevelSetVelocitySmooth, cvLevelSetVelocityThreshold, and cvLevelSetVelocityConstant.
Definition at line 73 of file cvLevelSetVelocity.h.
Referenced by cvLevelSet::StopCondition().
int cvLevelSetVelocity::UnlinkLevelSet ()
Definition at line 102 of file cvLevelSetVelocity.cxx.
References CV_OK, CV_PHI_TOL, ls_, NULL, tol_, and cvLevelSet::velocity_.
Referenced by LinkLevelSet(), and cvLevelSet::~cvLevelSet().
int cvLevelSetVelocity::UpdateTolerance ()
Definition at line 131 of file cvLevelSetVelocity.cxx.
References CV_ERROR, CV_OK, CV_PHI_TOL, cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::GetHv(), ls_, minimum, NULL, and tol_.
Referenced by cvLevelSet::Init(), and LinkLevelSet().
int cvLevelSetVelocity::Valid () virtual
Reimplemented in cvLevelSetVelocityExponentialDecay, cvLevelSetVelocityKGI, cvLevelSetVelocityPotential, cvLevelSetVelocitySmooth, cvLevelSetVelocityThreshold, and cvLevelSetVelocityConstant.
Definition at line 157 of file cvLevelSetVelocity.cxx.
References ls_, and NULL.
Referenced by cvLevelSetStructuredGrid::EvaluateV(), cvLevelSetVelocityConstant::Valid(), cvLevelSetVelocityThreshold::Valid(), cvLevelSetVelocitySmooth::Valid(), cvLevelSetVelocityPotential::Valid(), cvLevelSetVelocityKGI::Valid(), and cvLevelSetVelocityExponentialDecay::Valid().
Friends And Related Function Documentation
friend class cvLevelSet friend
Definition at line 58 of file cvLevelSetVelocity.h.
Member Data Documentation
cvLevelSet* cvLevelSetVelocity::ls_ protected
Definition at line 86 of file cvLevelSetVelocity.h.
Referenced by cvLevelSetVelocity(), cvLevelSetVelocityConstant::Evaluate(), cvLevelSetVelocityThreshold::Evaluate(), cvLevelSetVelocitySmooth::Evaluate(), cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), cvLevelSetVelocityExponentialDecay::Evaluate(), GetLevelSet(), LinkLevelSet(), cvLevelSetVelocityConstant::StopCondition(), cvLevelSetVelocityThreshold::StopCondition(), cvLevelSetVelocityKGI::StopCondition(), UnlinkLevelSet(), cvLevelSet::UnlinkVelocity(), UpdateTolerance(), Valid(), and ~cvLevelSetVelocity().
double cvLevelSetVelocity::stopV_ protected
Definition at line 88 of file cvLevelSetVelocity.h.
Referenced by cvLevelSetVelocity(), cvLevelSetVelocityKGI::Evaluate(), cvLevelSetVelocityExponentialDecay::Evaluate(), GetStopV(), SetStopV(), and cvLevelSetVelocityKGI::StopCondition().
char cvLevelSetVelocity::tclName_[CV_STRLEN]
Definition at line 80 of file cvLevelSetVelocity.h.
Referenced by DeleteLsetV(), LsetCore_GetVelocityMtd(), LsetVConst_NewCmd(), LsetVExpDecay_NewCmd(), LsetVKGI_NewCmd(), LsetVPotential_NewCmd(), LsetVSmooth_NewCmd(), and LsetVThr_NewCmd().
double cvLevelSetVelocity::tol_ protected
Definition at line 87 of file cvLevelSetVelocity.h.
Referenced by cvLevelSetVelocity(), cvLevelSetVelocitySmooth::Evaluate(), cvLevelSetVelocityExponentialDecay::Evaluate(), UnlinkLevelSet(), and UpdateTolerance().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocity.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocity.cxx