simvascular: cvLevelSetVelocityKGI Class Reference
cvLevelSetVelocityKGI Class Reference
#include <cvLevelSetVelocityKGI.h>
Public Member Functions
cvLevelSetVelocityKGI ()
~cvLevelSetVelocityKGI ()
void PostSetImageAction ()
int GetMaxImageIGrad (double *maxGrad)
int SetEK (double d)
int GetEK (double *d)
int SetEI (double d)
int GetEI (double *d)
int SetBalloonF (double b)
int GetBalloonF (double *b)
int SetGradIPow (double p)
int GetGradIPow (double *p)
int SetBeta (double b)
int GetBeta (double *b)
int SetApplyLocalStop (int flag)
int GetApplyLocalStop (int *flag)
int SetKTol (double t)
int GetKTol (double *t)
int Valid ()
int StopCondition ()
int Evaluate (double pos[], double *f0, double *f1, double v[], int *forceFlag, double toDot[])
int GetMemoryUsage ()
Public Member Functions inherited from cvLevelSetVelocityImage
cvLevelSetVelocityImage ()
virtual ~cvLevelSetVelocityImage ()
int SetImage (Image_T *i, int closed=0)
int SetImage (char *filebase, int fileNumRange[], int imgDims[], double pixDims[], int closed=0)
int SetImage (short *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (double *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int SetImage (float *imgData, int numData, int imgDims[], double pixDims[], double origin[], int closed=0)
int GetImage (Image_T **i)
int GetMagGradRange (double rng[])
int GetXYMagGradRange (double rng[])
int GetZMagGradRange (double rng[])
int GetIntensityRange (double rng[])
int ClearImage ()
Public Member Functions inherited from cvLevelSetVelocity
cvLevelSetVelocity ()
virtual ~cvLevelSetVelocity ()
int LinkLevelSet (cvLevelSet *ls)
int UnlinkLevelSet ()
int GetLevelSet (cvLevelSet **ls)
int UpdateTolerance ()
void SetStopV (double d)
double GetStopV ()
Private Member Functions
void SetUpPotentialField (Image_T *img)
Private Attributes
Image_T * potential_
int eKvalid_
int eIvalid_
int balloonFvalid_
int gradIPowValid_
int betaValid_
double eK_
double eI_
double balloonF_
double gradIPow_
double beta_
int localStop_
double ktol_
Additional Inherited Members
Public Attributes inherited from cvLevelSetVelocity
char tclName_ [CV_STRLEN]
Protected Member Functions inherited from cvLevelSetVelocityImage
int GetImgSize ()
Protected Attributes inherited from cvLevelSetVelocityImage
Image_T * image_
Protected Attributes inherited from cvLevelSetVelocity
cvLevelSet * ls_
double tol_
double stopV_
Detailed Description
Definition at line 43 of file cvLevelSetVelocityKGI.h.
Constructor & Destructor Documentation
cvLevelSetVelocityKGI::cvLevelSetVelocityKGI ()
Definition at line 49 of file cvLevelSetVelocityKGI.cxx.
References balloonFvalid_, betaValid_, eIvalid_, eKvalid_, gradIPowValid_, ktol_, localStop_, NULL, and potential_.
cvLevelSetVelocityKGI::~cvLevelSetVelocityKGI ()
Definition at line 66 of file cvLevelSetVelocityKGI.cxx.
Member Function Documentation
int cvLevelSetVelocityKGI::Evaluate (double pos[], double * f0, double * f1, double v[], int * forceFlag, double toDot[]) virtual
Implements cvLevelSetVelocity.
Definition at line 386 of file cvLevelSetVelocityKGI.cxx.
References balloonF_, beta_, CV_ERROR, CV_OK, Image_T::dim, Dot(), eI_, eK_, GetGradIx(), GetGradIy(), GetGradIz(), cvLevelSet::GetGrid(), GetImageClosed(), gradIPow_, cvLevelSetVelocityImage::image_, InBorder(), cvLevelSetStructuredGrid::InterpK(), cvLevelSetStructuredGrid::InterpN(), K, ktol_, localStop_, cvLevelSetVelocity::ls_, NULL, potential_, cvLevelSetVelocity::stopV_, and Valid().
int cvLevelSetVelocityKGI::GetApplyLocalStop (int * flag)
Definition at line 295 of file cvLevelSetVelocityKGI.cxx.
References CV_OK, and localStop_.
Referenced by LsetVKGI_GetConstMtd().
int cvLevelSetVelocityKGI::GetBalloonF (double * b)
Definition at line 212 of file cvLevelSetVelocityKGI.cxx.
References balloonF_, balloonFvalid_, CV_ERROR, and CV_OK.
Referenced by LsetVKGI_GetConstMtd().
int cvLevelSetVelocityKGI::GetBeta (double * b)
Definition at line 266 of file cvLevelSetVelocityKGI.cxx.
References beta_, betaValid_, CV_ERROR, and CV_OK.
Referenced by LsetVKGI_GetConstMtd().
int cvLevelSetVelocityKGI::GetEI (double * d)
Definition at line 186 of file cvLevelSetVelocityKGI.cxx.
References CV_ERROR, CV_OK, eI_, and eIvalid_.
Referenced by LsetVKGI_GetConstMtd().
int cvLevelSetVelocityKGI::GetEK (double * d)
Definition at line 160 of file cvLevelSetVelocityKGI.cxx.
References CV_ERROR, CV_OK, eK_, and eKvalid_.
Referenced by LsetVKGI_GetConstMtd().
int cvLevelSetVelocityKGI::GetGradIPow (double * p)
Definition at line 238 of file cvLevelSetVelocityKGI.cxx.
References CV_ERROR, CV_OK, gradIPow_, and gradIPowValid_.
Referenced by LsetVKGI_GetConstMtd().
int cvLevelSetVelocityKGI::GetKTol (double * t)
Definition at line 320 of file cvLevelSetVelocityKGI.cxx.
References CV_OK, and ktol_.
int cvLevelSetVelocityKGI::GetMaxImageIGrad (double * maxGrad)
Definition at line 87 of file cvLevelSetVelocityKGI.cxx.
References CV_ERROR, CV_OK, GetMaxGrad(), cvLevelSetVelocityImage::image_, and NULL.
int cvLevelSetVelocityKGI::GetMemoryUsage () virtual
Implements cvLevelSetVelocity.
Definition at line 506 of file cvLevelSetVelocityKGI.cxx.
References cvLevelSetVelocityImage::image_, Img_GetMemoryUsage(), and potential_.
void cvLevelSetVelocityKGI::PostSetImageAction () virtual
Reimplemented from cvLevelSetVelocityImage.
Definition at line 76 of file cvLevelSetVelocityKGI.cxx.
References cvLevelSetVelocityImage::image_, and SetUpPotentialField().
int cvLevelSetVelocityKGI::SetApplyLocalStop (int flag)
Definition at line 280 of file cvLevelSetVelocityKGI.cxx.
References CV_OK, and localStop_.
Referenced by LsetVKGI_SetConstMtd().
int cvLevelSetVelocityKGI::SetBalloonF (double b)
Definition at line 200 of file cvLevelSetVelocityKGI.cxx.
References balloonF_, balloonFvalid_, and CV_OK.
Referenced by LsetVKGI_SetConstMtd().
int cvLevelSetVelocityKGI::SetBeta (double b)
Definition at line 252 of file cvLevelSetVelocityKGI.cxx.
References beta_, betaValid_, and CV_OK.
Referenced by LsetVKGI_SetConstMtd().
int cvLevelSetVelocityKGI::SetEI (double d)
Definition at line 174 of file cvLevelSetVelocityKGI.cxx.
References CV_OK, eI_, and eIvalid_.
Referenced by LsetVKGI_SetConstMtd().
int cvLevelSetVelocityKGI::SetEK (double d)
Definition at line 148 of file cvLevelSetVelocityKGI.cxx.
References CV_OK, eK_, and eKvalid_.
Referenced by LsetVKGI_SetConstMtd().
int cvLevelSetVelocityKGI::SetGradIPow (double p)
Definition at line 226 of file cvLevelSetVelocityKGI.cxx.
References CV_OK, gradIPow_, and gradIPowValid_.
Referenced by LsetVKGI_SetConstMtd().
int cvLevelSetVelocityKGI::SetKTol (double t)
Definition at line 306 of file cvLevelSetVelocityKGI.cxx.
References CV_ERROR, CV_OK, and ktol_.
void cvLevelSetVelocityKGI::SetUpPotentialField (Image_T * img) private
Definition at line 110 of file cvLevelSetVelocityKGI.cxx.
References ComputeImageGrad(), CreateImage(), Pixel_T::gradX, Pixel_T::gradY, Pixel_T::gradZ, Image_Delete(), Image_T::imgDims, Magnitude(), NULL, Image_T::pixelDims, Image_T::pixels, and potential_.
Referenced by PostSetImageAction().
int cvLevelSetVelocityKGI::StopCondition () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 350 of file cvLevelSetVelocityKGI.cxx.
References cvLevelSet::GetCurrTime(), cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::GetMaxF(), cvLevelSetVelocity::ls_, and cvLevelSetVelocity::stopV_.
int cvLevelSetVelocityKGI::Valid () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 331 of file cvLevelSetVelocityKGI.cxx.
References balloonFvalid_, betaValid_, eIvalid_, eKvalid_, gradIPowValid_, cvLevelSetVelocityImage::image_, NULL, and cvLevelSetVelocity::Valid().
Referenced by Evaluate().
Member Data Documentation
double cvLevelSetVelocityKGI::balloonF_ private
Definition at line 93 of file cvLevelSetVelocityKGI.h.
Referenced by Evaluate(), GetBalloonF(), and SetBalloonF().
int cvLevelSetVelocityKGI::balloonFvalid_ private
Definition at line 87 of file cvLevelSetVelocityKGI.h.
Referenced by cvLevelSetVelocityKGI(), GetBalloonF(), SetBalloonF(), and Valid().
double cvLevelSetVelocityKGI::beta_ private
Definition at line 95 of file cvLevelSetVelocityKGI.h.
Referenced by Evaluate(), GetBeta(), and SetBeta().
int cvLevelSetVelocityKGI::betaValid_ private
Definition at line 89 of file cvLevelSetVelocityKGI.h.
Referenced by cvLevelSetVelocityKGI(), GetBeta(), SetBeta(), and Valid().
double cvLevelSetVelocityKGI::eI_ private
Definition at line 92 of file cvLevelSetVelocityKGI.h.
Referenced by Evaluate(), GetEI(), and SetEI().
int cvLevelSetVelocityKGI::eIvalid_ private
Definition at line 86 of file cvLevelSetVelocityKGI.h.
Referenced by cvLevelSetVelocityKGI(), GetEI(), SetEI(), and Valid().
double cvLevelSetVelocityKGI::eK_ private
Definition at line 91 of file cvLevelSetVelocityKGI.h.
Referenced by Evaluate(), GetEK(), and SetEK().
int cvLevelSetVelocityKGI::eKvalid_ private
Definition at line 85 of file cvLevelSetVelocityKGI.h.
Referenced by cvLevelSetVelocityKGI(), GetEK(), SetEK(), and Valid().
double cvLevelSetVelocityKGI::gradIPow_ private
Definition at line 94 of file cvLevelSetVelocityKGI.h.
Referenced by Evaluate(), GetGradIPow(), and SetGradIPow().
int cvLevelSetVelocityKGI::gradIPowValid_ private
Definition at line 88 of file cvLevelSetVelocityKGI.h.
Referenced by cvLevelSetVelocityKGI(), GetGradIPow(), SetGradIPow(), and Valid().
double cvLevelSetVelocityKGI::ktol_ private
Definition at line 97 of file cvLevelSetVelocityKGI.h.
Referenced by cvLevelSetVelocityKGI(), Evaluate(), GetKTol(), and SetKTol().
int cvLevelSetVelocityKGI::localStop_ private
Definition at line 96 of file cvLevelSetVelocityKGI.h.
Referenced by cvLevelSetVelocityKGI(), Evaluate(), GetApplyLocalStop(), and SetApplyLocalStop().
Image_T* cvLevelSetVelocityKGI::potential_ private
Definition at line 81 of file cvLevelSetVelocityKGI.h.
Referenced by cvLevelSetVelocityKGI(), Evaluate(), GetMemoryUsage(), and SetUpPotentialField().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityKGI.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityKGI.cxx