simvascular: cvCPUTimer Class Reference
cvCPUTimer Class Reference
#include <cvTimer.h>
Public Member Functions
cvCPUTimer ()
Public Member Functions inherited from cvBaseTimer
double seconds () const
double granularity ()
void reset ()
Protected Member Functions
cvTimeInBaseTimer currentTime () const
double getGranularity ()
Static Private Attributes
static int granularityKnown_ = 0
Additional Inherited Members
Static Public Attributes inherited from cvBaseTimer
static int calculateGranularityOnConstructor = 0
Protected Attributes inherited from cvBaseTimer
cvTimeInBaseTimer savedTime_
double granularity_
Detailed Description
Definition at line 87 of file cvTimer.h.
Constructor & Destructor Documentation
cvCPUTimer::cvCPUTimer ()
Definition at line 96 of file cvTimer.cxx.
References cvBaseTimer::calculateGranularityOnConstructor, currentTime(), getGranularity(), and cvBaseTimer::savedTime_.
Member Function Documentation
cvTimeInBaseTimer cvCPUTimer::currentTime () const protected virtual
Reimplemented from cvBaseTimer.
Referenced by cvCPUTimer(), and getGranularity().
double cvCPUTimer::getGranularity () protected virtual
Reimplemented from cvBaseTimer.
Definition at line 105 of file cvTimer.cxx.
References currentTime(), cvBaseTimer::granularity_, and granularityKnown_.
Referenced by cvCPUTimer().
Member Data Documentation
int cvCPUTimer::granularityKnown_ = 0 static private
Definition at line 96 of file cvTimer.h.
Referenced by getGranularity().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvTimer.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvTimer.cxx