simvascular: cvWallClockTimer Class Reference
cvWallClockTimer Class Reference
#include <cvTimer.h>
Public Member Functions
cvWallClockTimer ()
Public Member Functions inherited from cvBaseTimer
double seconds () const
double granularity ()
void reset ()
Protected Member Functions
cvTimeInBaseTimer currentTime () const
double getGranularity ()
Static Private Attributes
static int granularityKnown_ = 0
Additional Inherited Members
Static Public Attributes inherited from cvBaseTimer
static int calculateGranularityOnConstructor = 0
Protected Attributes inherited from cvBaseTimer
cvTimeInBaseTimer savedTime_
double granularity_
Detailed Description
Definition at line 100 of file cvTimer.h.
Constructor & Destructor Documentation
cvWallClockTimer::cvWallClockTimer ()
Definition at line 126 of file cvTimer.cxx.
References cvBaseTimer::calculateGranularityOnConstructor, currentTime(), getGranularity(), and cvBaseTimer::savedTime_.
Member Function Documentation
cvTimeInBaseTimer cvWallClockTimer::currentTime () const protected virtual
Reimplemented from cvBaseTimer.
Referenced by cvWallClockTimer(), and getGranularity().
double cvWallClockTimer::getGranularity () protected virtual
Reimplemented from cvBaseTimer.
Definition at line 135 of file cvTimer.cxx.
References currentTime(), cvBaseTimer::granularity_, and granularityKnown_.
Referenced by cvWallClockTimer().
Member Data Documentation
int cvWallClockTimer::granularityKnown_ = 0 static private
Definition at line 109 of file cvTimer.h.
Referenced by getGranularity().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvTimer.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvTimer.cxx