simvascular: cvLevelSetVelocityConstant Class Reference
cvLevelSetVelocityConstant Class Reference
#include <cvLevelSetVelocityConstant.h>
Public Member Functions
cvLevelSetVelocityConstant ()
~cvLevelSetVelocityConstant ()
int SetV (double v)
int GetV (double *v)
int Valid ()
int StopCondition ()
int Evaluate (double pos[], double *f0, double *f1, double v[], int *forceFlag, double toDot[])
int GetMemoryUsage ()
Public Member Functions inherited from cvLevelSetVelocity
cvLevelSetVelocity ()
virtual ~cvLevelSetVelocity ()
int LinkLevelSet (cvLevelSet *ls)
int UnlinkLevelSet ()
int GetLevelSet (cvLevelSet **ls)
int UpdateTolerance ()
void SetStopV (double d)
double GetStopV ()
Private Attributes
double v_
int vValid_
Additional Inherited Members
Public Attributes inherited from cvLevelSetVelocity
char tclName_ [CV_STRLEN]
Protected Attributes inherited from cvLevelSetVelocity
cvLevelSet * ls_
double tol_
double stopV_
Detailed Description
Definition at line 42 of file cvLevelSetVelocityConstant.h.
Constructor & Destructor Documentation
cvLevelSetVelocityConstant::cvLevelSetVelocityConstant ()
Definition at line 43 of file cvLevelSetVelocityConstant.cxx.
References vValid_.
cvLevelSetVelocityConstant::~cvLevelSetVelocityConstant ()
Definition at line 53 of file cvLevelSetVelocityConstant.cxx.
Member Function Documentation
int cvLevelSetVelocityConstant::Evaluate (double pos[], double * f0, double * f1, double v[], int * forceFlag, double toDot[]) virtual
Implements cvLevelSetVelocity.
Definition at line 130 of file cvLevelSetVelocityConstant.cxx.
References CV_ERROR, CV_OK, cvLevelSet::GetGrid(), cvLevelSetStructuredGrid::InterpN(), cvLevelSetVelocity::ls_, NULL, v_, and Valid().
int cvLevelSetVelocityConstant::GetMemoryUsage () inline virtual
Implements cvLevelSetVelocity.
Definition at line 56 of file cvLevelSetVelocityConstant.h.
int cvLevelSetVelocityConstant::GetV (double * v)
Definition at line 75 of file cvLevelSetVelocityConstant.cxx.
References CV_ERROR, CV_OK, v_, and vValid_.
Referenced by LsetVConst_GetConstMtd().
int cvLevelSetVelocityConstant::SetV (double v)
Definition at line 63 of file cvLevelSetVelocityConstant.cxx.
References CV_OK, v_, and vValid_.
Referenced by LsetVConst_SetConstMtd().
int cvLevelSetVelocityConstant::StopCondition () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 103 of file cvLevelSetVelocityConstant.cxx.
References cvLevelSet::GetCurrTime(), and cvLevelSetVelocity::ls_.
int cvLevelSetVelocityConstant::Valid () virtual
Reimplemented from cvLevelSetVelocity.
Definition at line 89 of file cvLevelSetVelocityConstant.cxx.
References cvLevelSetVelocity::Valid(), and vValid_.
Referenced by Evaluate().
Member Data Documentation
double cvLevelSetVelocityConstant::v_ private
Definition at line 59 of file cvLevelSetVelocityConstant.h.
Referenced by Evaluate(), GetV(), and SetV().
int cvLevelSetVelocityConstant::vValid_ private
Definition at line 60 of file cvLevelSetVelocityConstant.h.
Referenced by cvLevelSetVelocityConstant(), GetV(), SetV(), and Valid().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityConstant.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetVelocityConstant.cxx