simvascular: cvLevelSetStructuredGrid Class Reference
cvLevelSetStructuredGrid Class Reference abstract
#include <cvLevelSetStructuredGrid.h>
Public Member Functions
cvLevelSetStructuredGrid (double h[], int dims[], double o[])
virtual ~cvLevelSetStructuredGrid ()
virtual void DeallocateNodes ()=0
virtual int InitPhi (double ctr[], double radius)=0
virtual int InitPhi (cvPolyData *front)=0
virtual int InitPhi (cvSolidModel *solid)=0
virtual int InitPhi (cvStrPts *img, double thr)=0
virtual int ReinitPhi ()=0
int CloseHoles ()
virtual int SetBandParams (double innerPhi, double outerPhi, double mineWidth)
virtual int GetBandParams (double *innerPhi, double *outerPhi, double *mineWidth)
int EvaluateV (cvLevelSetVelocity *vfn, double factor=1.0)
virtual int ProjectV (int save)=0
virtual void ExtendV ()=0
double ComputeDeltaPhi (double factor=1.0)
virtual int UpdatePhi ()
void GetAdjacentIxs (cvLevelSetNode *n, int ixs[])
void GetAdjacentIxs (int index, int ixs[])
int IxWithinExtent (int i, int j, int k)
void FindDpi ()
void FindDmi ()
void FindD0 ()
void FindK ()
void FindK2d ()
void FindK3dg ()
void FindK3dm ()
void FindN ()
int GetAnchorIx (double pos[], int *ix)
int FindEdge (double pos[], cvLevelSetNode **a, cvLevelSetNode **b, char *dir)
int InterpZLS (cvLevelSetNode *a, cvLevelSetNode *b, char code, double zls[])
int InterpK (double pos[], double *k)
int InterpKm (double pos[], double *k)
int InterpKg (double pos[], double *k)
int InterpN (double pos[], double n[])
double GetMaxF ()
vtkFloatingPointType GetMaxV ()
double GetMaxPhiIncr ()
cvPolyData * GetVelocityVectors ()
cvPolyData * GetFront (int closed=0)
cvPolyData * GetActiveNodes ()
virtual cvDataObject * GetPhi ()=0
virtual cvStrPts * GetCurvature ()=0
virtual cvPolyData * GetBoundaryData (GridScalarT t)
int GetNodeSets (cvPolyData ***nodeSets, int *numSets)
int SaveActiveNodes ()
int NumActiveNodes ()
int SaveCoveredNodes ()
int SaveUncoveredNodes ()
int SaveForceMinVNodes ()
int SaveMineNodes ()
int PSetsValid ()
virtual cvPolyData * CreateGridPolyData ()
virtual int GridModified () const
virtual char * StatString ()=0
int GetDim ()
int GetHv (double *hx, double *hy, double *hz)
double GetMinH ()
double ComputeDt (double cflFactor)
double ComputeDt (double maxf, double cflFactor)
double GetMainDiagonal ()
virtual int GetMemoryUsage ()=0
Protected Member Functions
int GetStructuredGridMemoryUsage ()
void FindD0i ()
void FindD0xi ()
void FindD0yi ()
void FindD0zi ()
void FindDelPlus ()
void FindDelMinus ()
virtual void InitIter ()=0
virtual cvLevelSetNode * GetNext ()=0
virtual int IJKToIndex (int i, int j, int k)=0
int IJKToLogicalIx (int i, int j, int k)
int LogicalIxToIJK (int log_ix, int *i, int *j, int *k)
int ProjectV (int posFlag, int save)
int CheckProjectCoverage ()
int SteepestDescentPhi (int ix)
int SteepestAscentPhi (int ix)
void ResetNodeSets ()
void ClearActive ()
void ClearForceMinV ()
void ClearCovered ()
void AssignNode (cvLevelSetNode *n, double f0, double f1, int forceMinVFlag, double toDot[])
void AssignVToNode (cvLevelSetNode *n, double f0, double f1, int forceMinVFlag, double toDot[])
void AssignVToEdge (cvLevelSetNode *a, cvLevelSetNode *b, double f0, double f1, int forceMinVFlag, double toDot[])
virtual void MakePhiVtk (int closed=0)=0
Protected Attributes
cvLevelSetNode * curr_
int * ixBuffer_
int ixBufferSz_
int * nodeSets_
int nodeSetsSize_
int nodeSetsPos_
int pSetsValid_
cvLevelSetNode * grid_
int numNodes_
int I_
int J_
int K_
int numDenseNodes_
double hv_ [3]
double minh_
double maxh_
double origin_ [3]
int dim_
double mainDiagonal_
double tol_
double oneOverTol_
double relTol_
int init_
int d0Valid_
int dpiValid_
int dmiValid_
int delPlusValid_
int delMinusValid_
int deltaPhiValid_
int nValid_
int kValid_
int k3dmValid_
int k3dgValid_
vtkDataSet * phiVtk_
int phiVtkValid_
cvPolyData * velocityVectors_
cvLevelSetVelocity * velocity_
Detailed Description
Definition at line 51 of file cvLevelSetStructuredGrid.h.
Constructor & Destructor Documentation
cvLevelSetStructuredGrid::cvLevelSetStructuredGrid (double h[], int dims[], double o[])
Definition at line 63 of file cvLevelSetStructuredGrid.cxx.
References curr_, d0Valid_, delMinusValid_, delPlusValid_, deltaPhiValid_, dim_, dmiValid_, dpiValid_, FindMachineEpsilon(), grid_, hv_, I_, init_, ixBuffer_, J_, k3dgValid_, k3dmValid_, K_, kValid_, mainDiagonal_, maxh_, maximum, minh_, minimum, nodeSets_, NULL, numDenseNodes_, nValid_, oneOverTol_, origin_, phiVtk_, phiVtkValid_, pSetsValid_, relTol_, sqr, tol_, velocity_, and velocityVectors_.
cvLevelSetStructuredGrid::~cvLevelSetStructuredGrid () virtual
Definition at line 145 of file cvLevelSetStructuredGrid.cxx.
References phiVtk_.
Member Function Documentation
void cvLevelSetStructuredGrid::AssignNode (cvLevelSetNode * n, double f0, double f1, int forceMinVFlag, double toDot[]) protected
Definition at line 2458 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, CV_NODE_FORCE_MINV, cvLevelSetNode::F0_, cvLevelSetNode::F1_, Magnitude(), cvLevelSetNode::state_, and cvLevelSetNode::toDot_.
Referenced by EvaluateV().
void cvLevelSetStructuredGrid::AssignVToEdge (cvLevelSetNode * a, cvLevelSetNode * b, double f0, double f1, int forceMinVFlag, double toDot[]) protected
Definition at line 2631 of file cvLevelSetStructuredGrid.cxx.
void cvLevelSetStructuredGrid::AssignVToNode (cvLevelSetNode * n, double f0, double f1, int forceMinVFlag, double toDot[]) protected
Definition at line 2560 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, CV_NODE_FORCE_MINV, CV_NODE_V_ASSIGNED, cvLevelSetNode::F0_, cvLevelSetNode::F1_, Magnitude(), cvLevelSetNode::state_, and cvLevelSetNode::toDot_.
int cvLevelSetStructuredGrid::CheckProjectCoverage () protected
Definition at line 2232 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, CV_NODE_COVERED, GetNext(), InitIter(), and cvLevelSetNode::state_.
Referenced by cvLevelSetDenseGrid::ProjectV(), and cvLevelSetSparseGrid::ProjectV().
void cvLevelSetStructuredGrid::ClearActive () protected
Definition at line 2409 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, GetNext(), InitIter(), and cvLevelSetNode::state_.
Referenced by EvaluateV().
void cvLevelSetStructuredGrid::ClearCovered () protected
Definition at line 2441 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_COVERED, GetNext(), InitIter(), and cvLevelSetNode::state_.
Referenced by cvLevelSetDenseGrid::ProjectV(), and cvLevelSetSparseGrid::ProjectV().
void cvLevelSetStructuredGrid::ClearForceMinV () protected
Definition at line 2425 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_FORCE_MINV, GetNext(), InitIter(), and cvLevelSetNode::state_.
Referenced by EvaluateV().
int cvLevelSetStructuredGrid::CloseHoles ()
Definition at line 156 of file cvLevelSetStructuredGrid.cxx.
References CV_OK, GetNext(), cvLevelSetNode::i_, I_, InitIter(), cvLevelSetNode::j_, J_, cvLevelSetNode::k_, K_, cvLevelSetNode::phi_, and phiVtkValid_.
double cvLevelSetStructuredGrid::ComputeDeltaPhi (double factor = 1.0)
Definition at line 331 of file cvLevelSetStructuredGrid.cxx.
References ComputeDt(), CV_NODE_ACTIVE, CV_NODE_COVERED, cvLevelSetNode::d0_, cvLevelSetNode::delMinus_, cvLevelSetNode::delPlus_, cvLevelSetNode::deltaPhi_, deltaPhiValid_, cvLevelSetNode::F0_, cvLevelSetNode::F1_, FindD0(), FindDelMinus(), FindDelPlus(), FindN(), GetMaxF(), GetNext(), cvLevelSetNode::index_, InitIter(), IntSign(), maximum, minh_, minimum, cvLevelSetNode::phi_, relTol_, cvLevelSetNode::state_, tol_, and cvLevelSetNode::velocity_.
Referenced by cvLevelSet::EvolveOneTimeStep().
double cvLevelSetStructuredGrid::ComputeDt (double cflFactor)
Definition at line 1991 of file cvLevelSetStructuredGrid.cxx.
References GetMaxF().
Referenced by ComputeDeltaPhi().
double cvLevelSetStructuredGrid::ComputeDt (double maxf, double cflFactor)
Definition at line 2005 of file cvLevelSetStructuredGrid.cxx.
References minh_, and tol_.
cvPolyData * cvLevelSetStructuredGrid::CreateGridPolyData () virtual
Reimplemented in cvLevelSetSparseGrid.
Definition at line 1979 of file cvLevelSetStructuredGrid.cxx.
References NULL.
Referenced by LsetCore_SaveGridMtd().
virtual void cvLevelSetStructuredGrid::DeallocateNodes () pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
int cvLevelSetStructuredGrid::EvaluateV (cvLevelSetVelocity * vfn, double factor = 1.0)
Definition at line 179 of file cvLevelSetStructuredGrid.cxx.
References AssignNode(), c, ClearActive(), ClearForceMinV(), CV_ERROR, CV_OK, deltaPhiValid_, cvLevelSetVelocity::Evaluate(), FindK(), FindN(), GetAdjacentIxs(), GetNext(), grid_, InitIter(), InterpZLS(), minh_, NULL, cvLevelSetNode::phi_, cvLevelSetNode::pos_, relTol_, tol_, cvLevelSetVelocity::Valid(), and velocityVectors_.
Referenced by cvLevelSet::EvolveOneTimeStep().
virtual void cvLevelSetStructuredGrid::ExtendV () pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by cvLevelSet::EvolveOneTimeStep().
void cvLevelSetStructuredGrid::FindD0 ()
Definition at line 704 of file cvLevelSetStructuredGrid.cxx.
References d0Valid_, FindD0i(), FindD0xi(), FindD0yi(), and FindD0zi().
Referenced by ComputeDeltaPhi(), FindK2d(), FindK3dg(), and FindK3dm().
void cvLevelSetStructuredGrid::FindD0i () protected
Definition at line 722 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::d0_, GetNext(), grid_, hv_, InitIter(), cvLevelSetNode::phi_, cvLevelSetNode::xNextIndex_, cvLevelSetNode::xPrevIndex_, cvLevelSetNode::yNextIndex_, cvLevelSetNode::yPrevIndex_, cvLevelSetNode::zNextIndex_, and cvLevelSetNode::zPrevIndex_.
Referenced by FindD0().
void cvLevelSetStructuredGrid::FindD0xi () protected
Definition at line 766 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::d0_, cvLevelSetNode::d0x_, GetNext(), grid_, hv_, InitIter(), cvLevelSetNode::xNextIndex_, cvLevelSetNode::xPrevIndex_, cvLevelSetNode::yNextIndex_, cvLevelSetNode::yPrevIndex_, cvLevelSetNode::zNextIndex_, and cvLevelSetNode::zPrevIndex_.
Referenced by FindD0().
void cvLevelSetStructuredGrid::FindD0yi () protected
Definition at line 810 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::d0_, cvLevelSetNode::d0y_, GetNext(), grid_, hv_, InitIter(), cvLevelSetNode::xNextIndex_, cvLevelSetNode::xPrevIndex_, cvLevelSetNode::yNextIndex_, cvLevelSetNode::yPrevIndex_, cvLevelSetNode::zNextIndex_, and cvLevelSetNode::zPrevIndex_.
Referenced by FindD0().
void cvLevelSetStructuredGrid::FindD0zi () protected
Definition at line 854 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::d0_, cvLevelSetNode::d0z_, GetNext(), grid_, hv_, InitIter(), cvLevelSetNode::xNextIndex_, cvLevelSetNode::xPrevIndex_, cvLevelSetNode::yNextIndex_, cvLevelSetNode::yPrevIndex_, cvLevelSetNode::zNextIndex_, and cvLevelSetNode::zPrevIndex_.
Referenced by FindD0().
void cvLevelSetStructuredGrid::FindDelMinus () protected
Definition at line 1012 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::delMinus_, delMinusValid_, cvLevelSetNode::dm_, cvLevelSetNode::dp_, FindDmi(), FindDpi(), GetNext(), InitIter(), maximum, and minimum.
Referenced by ComputeDeltaPhi().
void cvLevelSetStructuredGrid::FindDelPlus () protected
Definition at line 977 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::delPlus_, delPlusValid_, cvLevelSetNode::dm_, cvLevelSetNode::dp_, FindDmi(), FindDpi(), GetNext(), InitIter(), maximum, and minimum.
Referenced by ComputeDeltaPhi().
void cvLevelSetStructuredGrid::FindDmi ()
Definition at line 938 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::dm_, dmiValid_, GetNext(), grid_, hv_, InitIter(), cvLevelSetNode::phi_, cvLevelSetNode::xPrevIndex_, cvLevelSetNode::yPrevIndex_, and cvLevelSetNode::zPrevIndex_.
Referenced by FindDelMinus(), FindDelPlus(), and FindN().
void cvLevelSetStructuredGrid::FindDpi ()
Definition at line 898 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::dp_, dpiValid_, GetNext(), grid_, hv_, InitIter(), cvLevelSetNode::phi_, cvLevelSetNode::xNextIndex_, cvLevelSetNode::yNextIndex_, and cvLevelSetNode::zNextIndex_.
Referenced by FindDelMinus(), FindDelPlus(), and FindN().
int cvLevelSetStructuredGrid::FindEdge (double pos[], cvLevelSetNode ** a, cvLevelSetNode ** b, char * dir)
Definition at line 1382 of file cvLevelSetStructuredGrid.cxx.
References CV_ERROR, CV_OK, GetAdjacentIxs(), GetAnchorIx(), grid_, minh_, NULL, cvLevelSetNode::pos_, and relTol_.
Referenced by GetBoundaryData(), InterpK(), InterpKg(), InterpKm(), and InterpN().
void cvLevelSetStructuredGrid::FindK ()
Definition at line 1047 of file cvLevelSetStructuredGrid.cxx.
References dim_, FindK2d(), FindK3dg(), FindK3dm(), GetNext(), InitIter(), cvLevelSetNode::K3dm_, cvLevelSetNode::K_, and kValid_.
Referenced by EvaluateV(), GetBoundaryData(), and cvLevelSetDenseGrid::GetCurvature().
void cvLevelSetStructuredGrid::FindK2d ()
Definition at line 1074 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::d0_, cvLevelSetNode::d0x_, cvLevelSetNode::d0y_, FindD0(), GetNext(), InitIter(), cvLevelSetNode::K_, kValid_, oneOverTol_, and tol_.
Referenced by FindK().
void cvLevelSetStructuredGrid::FindK3dg ()
Definition at line 1170 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::d0_, cvLevelSetNode::d0x_, cvLevelSetNode::d0y_, cvLevelSetNode::d0z_, FindD0(), GetNext(), InitIter(), cvLevelSetNode::K3dg_, k3dgValid_, oneOverTol_, and tol_.
Referenced by FindK(), and GetBoundaryData().
void cvLevelSetStructuredGrid::FindK3dm ()
Definition at line 1118 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::d0_, cvLevelSetNode::d0x_, cvLevelSetNode::d0y_, cvLevelSetNode::d0z_, FindD0(), GetNext(), InitIter(), cvLevelSetNode::K3dm_, k3dmValid_, oneOverTol_, and tol_.
Referenced by FindK(), and GetBoundaryData().
void cvLevelSetStructuredGrid::FindN ()
Definition at line 1226 of file cvLevelSetStructuredGrid.cxx.
References dim_, cvLevelSetNode::dm_, cvLevelSetNode::dp_, FindDmi(), FindDpi(), GetNext(), InitIter(), cvLevelSetNode::n_, cvLevelSetNode::nn_, NormVector(), nValid_, and sqr.
Referenced by ComputeDeltaPhi(), and EvaluateV().
cvPolyData * cvLevelSetStructuredGrid::GetActiveNodes ()
Definition at line 1722 of file cvLevelSetStructuredGrid.cxx.
References CV_OK, GetNodeSets(), NULL, and SaveActiveNodes().
Referenced by cvLevelSet::ExtractActiveNodes(), and LsetCore_ExtractActiveNodesMtd().
void cvLevelSetStructuredGrid::GetAdjacentIxs (cvLevelSetNode * n, int ixs[])
Definition at line 574 of file cvLevelSetStructuredGrid.cxx.
References cvLevelSetNode::index_, cvLevelSetNode::xNextIndex_, cvLevelSetNode::xPrevIndex_, cvLevelSetNode::yNextIndex_, cvLevelSetNode::yPrevIndex_, cvLevelSetNode::zNextIndex_, and cvLevelSetNode::zPrevIndex_.
Referenced by EvaluateV(), FindEdge(), ProjectV(), SteepestAscentPhi(), SteepestDescentPhi(), and cvLevelSetSparseGrid::Sweep().
void cvLevelSetStructuredGrid::GetAdjacentIxs (int index, int ixs[])
Definition at line 620 of file cvLevelSetStructuredGrid.cxx.
References IJKToLogicalIx(), IxWithinExtent(), and LogicalIxToIJK().
int cvLevelSetStructuredGrid::GetAnchorIx (double pos[], int * ix)
Definition at line 1354 of file cvLevelSetStructuredGrid.cxx.
References CV_OK, hv_, IJKToIndex(), minh_, origin_, and relTol_.
Referenced by FindEdge().
virtual int cvLevelSetStructuredGrid::GetBandParams (double * innerPhi, double * outerPhi, double * mineWidth) inline virtual
Reimplemented in cvLevelSetSparseGrid.
Definition at line 70 of file cvLevelSetStructuredGrid.h.
References CV_ERROR.
cvPolyData * cvLevelSetStructuredGrid::GetBoundaryData (GridScalarT t) virtual
Definition at line 1763 of file cvLevelSetStructuredGrid.cxx.
References CV_OK, FindEdge(), FindK(), FindK3dg(), FindK3dm(), cvLevelSetNode::GetDoubleDatum(), GetFront(), cvPolyData::GetVtkPolyData(), GS_CURVATURE, GS_CURVATURE_3Dg, GS_CURVATURE_3Dk1, GS_CURVATURE_3Dk2, GS_CURVATURE_3Dm, GS_PHI, LinInterp1D_dbl(), NULL, cvLevelSetNode::pos_, and tol_.
Referenced by LsetCore_GetBoundaryDataMtd().
virtual cvStrPts* cvLevelSetStructuredGrid::GetCurvature () pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by cvLevelSet::ExtractCurvature().
int cvLevelSetStructuredGrid::GetDim () inline
Definition at line 252 of file cvLevelSetStructuredGrid.h.
References dim_.
Referenced by cvLevelSetVelocitySmooth::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
cvPolyData * cvLevelSetStructuredGrid::GetFront (int closed = 0)
Definition at line 1689 of file cvLevelSetStructuredGrid.cxx.
References MakePhiVtk(), and phiVtk_.
Referenced by cvLevelSet::ExtractFront(), GetBoundaryData(), cvLevelSetDenseGrid::ReinitPhi(), cvLevelSetSparseGrid::ReinitPhi(), and cvLevelSetSparseGrid::UpdatePhi().
int cvLevelSetStructuredGrid::GetHv (double * hx, double * hy, double * hz) inline
Definition at line 262 of file cvLevelSetStructuredGrid.h.
References CV_OK, and hv_.
Referenced by cvLevelSetVelocity::UpdateTolerance().
double cvLevelSetStructuredGrid::GetMainDiagonal () inline
Definition at line 136 of file cvLevelSetStructuredGrid.h.
References mainDiagonal_.
double cvLevelSetStructuredGrid::GetMaxF ()
Definition at line 2025 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, cvLevelSetNode::F0_, cvLevelSetNode::F1_, GetNext(), InitIter(), maximum, and cvLevelSetNode::state_.
Referenced by ComputeDeltaPhi(), ComputeDt(), cvLevelSetVelocityThreshold::StopCondition(), cvLevelSetVelocityKGI::StopCondition(), and cvLevelSet::StopCondition().
double cvLevelSetStructuredGrid::GetMaxPhiIncr ()
Definition at line 2074 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, CV_NODE_COVERED, cvLevelSetNode::deltaPhi_, deltaPhiValid_, GetNext(), InitIter(), maximum, oneOverTol_, and cvLevelSetNode::state_.
vtkFloatingPointType cvLevelSetStructuredGrid::GetMaxV ()
Definition at line 2047 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, deltaPhiValid_, GetNext(), InitIter(), maximum, oneOverTol_, cvLevelSetNode::state_, and cvLevelSetNode::velocity_.
Referenced by cvLevelSet::StopCondition().
virtual int cvLevelSetStructuredGrid::GetMemoryUsage () pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by cvLevelSet::GetMemoryUsage().
double cvLevelSetStructuredGrid::GetMinH () inline
Definition at line 275 of file cvLevelSetStructuredGrid.h.
References minh_.
virtual cvLevelSetNode* cvLevelSetStructuredGrid::GetNext () protected pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by CheckProjectCoverage(), ClearActive(), ClearCovered(), ClearForceMinV(), CloseHoles(), ComputeDeltaPhi(), EvaluateV(), FindD0i(), FindD0xi(), FindD0yi(), FindD0zi(), FindDelMinus(), FindDelPlus(), FindDmi(), FindDpi(), FindK(), FindK2d(), FindK3dg(), FindK3dm(), FindN(), GetMaxF(), GetMaxPhiIncr(), GetMaxV(), NumActiveNodes(), ProjectV(), SaveActiveNodes(), SaveCoveredNodes(), SaveForceMinVNodes(), SaveMineNodes(), SaveUncoveredNodes(), and UpdatePhi().
int cvLevelSetStructuredGrid::GetNodeSets (cvPolyData *** nodeSets, int * numSets)
Definition at line 2362 of file cvLevelSetStructuredGrid.cxx.
References CV_OK, grid_, nodeSets_, nodeSetsSize_, and cvLevelSetNode::pos_.
Referenced by GetActiveNodes(), LsetCore_ExtractCoveredNodesMtd(), LsetCore_ExtractForceMinVNodesMtd(), LsetCore_ExtractMineNodesMtd(), LsetCore_ExtractProjectionSetsMtd(), and LsetCore_ExtractUncoveredNodesMtd().
virtual cvDataObject* cvLevelSetStructuredGrid::GetPhi () pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by cvLevelSet::ExtractPhi().
int cvLevelSetStructuredGrid::GetStructuredGridMemoryUsage () protected
Definition at line 676 of file cvLevelSetStructuredGrid.cxx.
References cvDataObject::GetMemoryUsage(), ixBuffer_, ixBufferSz_, nodeSets_, nodeSetsSize_, phiVtk_, and velocityVectors_.
Referenced by cvLevelSetDenseGrid::GetMemoryUsage(), and cvLevelSetSparseGrid::GetMemoryUsage().
cvPolyData * cvLevelSetStructuredGrid::GetVelocityVectors ()
Definition at line 1673 of file cvLevelSetStructuredGrid.cxx.
References NULL, and velocityVectors_.
Referenced by cvLevelSet::ExtractVectors().
virtual int cvLevelSetStructuredGrid::GridModified () const inline virtual
Reimplemented in cvLevelSetSparseGrid.
Definition at line 129 of file cvLevelSetStructuredGrid.h.
Referenced by LsetCore_GridModifiedMtd().
virtual int cvLevelSetStructuredGrid::IJKToIndex (int i, int j, int k) protected pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by GetAnchorIx().
int cvLevelSetStructuredGrid::IJKToLogicalIx (int i, int j, int k) inline protected
Definition at line 285 of file cvLevelSetStructuredGrid.h.
References I_, and J_.
Referenced by GetAdjacentIxs().
virtual void cvLevelSetStructuredGrid::InitIter () protected pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by CheckProjectCoverage(), ClearActive(), ClearCovered(), ClearForceMinV(), CloseHoles(), ComputeDeltaPhi(), EvaluateV(), FindD0i(), FindD0xi(), FindD0yi(), FindD0zi(), FindDelMinus(), FindDelPlus(), FindDmi(), FindDpi(), FindK(), FindK2d(), FindK3dg(), FindK3dm(), FindN(), GetMaxF(), GetMaxPhiIncr(), GetMaxV(), NumActiveNodes(), ProjectV(), SaveActiveNodes(), SaveCoveredNodes(), SaveForceMinVNodes(), SaveMineNodes(), SaveUncoveredNodes(), and UpdatePhi().
virtual int cvLevelSetStructuredGrid::InitPhi (double ctr[], double radius) pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by cvLevelSet::Init().
virtual int cvLevelSetStructuredGrid::InitPhi (cvPolyData * front) pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
virtual int cvLevelSetStructuredGrid::InitPhi (cvSolidModel * solid) pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
virtual int cvLevelSetStructuredGrid::InitPhi (cvStrPts * img, double thr) pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
int cvLevelSetStructuredGrid::InterpK (double pos[], double * k)
Definition at line 1504 of file cvLevelSetStructuredGrid.cxx.
References CV_ERROR, CV_OK, FindEdge(), cvLevelSetNode::K_, LinInterp1D_dbl(), NULL, and cvLevelSetNode::pos_.
Referenced by cvLevelSetVelocitySmooth::Evaluate(), cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int cvLevelSetStructuredGrid::InterpKg (double pos[], double * k)
Definition at line 1576 of file cvLevelSetStructuredGrid.cxx.
References CV_ERROR, CV_OK, FindEdge(), cvLevelSetNode::K3dg_, LinInterp1D_dbl(), NULL, and cvLevelSetNode::pos_.
Referenced by cvLevelSetVelocitySmooth::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int cvLevelSetStructuredGrid::InterpKm (double pos[], double * k)
Definition at line 1540 of file cvLevelSetStructuredGrid.cxx.
References CV_ERROR, CV_OK, FindEdge(), cvLevelSetNode::K3dm_, LinInterp1D_dbl(), NULL, and cvLevelSetNode::pos_.
Referenced by cvLevelSetVelocitySmooth::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int cvLevelSetStructuredGrid::InterpN (double pos[], double n[])
Definition at line 1612 of file cvLevelSetStructuredGrid.cxx.
References CV_ERROR, CV_OK, FindEdge(), LinInterp1D_dbl(), cvLevelSetNode::n_, NULL, and cvLevelSetNode::pos_.
Referenced by cvLevelSetVelocityConstant::Evaluate(), cvLevelSetVelocityThreshold::Evaluate(), cvLevelSetVelocitySmooth::Evaluate(), cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int cvLevelSetStructuredGrid::InterpZLS (cvLevelSetNode * a, cvLevelSetNode * b, char code, double zls[])
Definition at line 1442 of file cvLevelSetStructuredGrid.cxx.
References CV_ERROR, CV_OK, LinInterp1D_dbl(), minh_, NULL, cvLevelSetNode::phi_, cvLevelSetNode::pos_, and relTol_.
Referenced by EvaluateV().
int cvLevelSetStructuredGrid::IxWithinExtent (int i, int j, int k) inline
Definition at line 236 of file cvLevelSetStructuredGrid.h.
References I_, J_, and K_.
Referenced by GetAdjacentIxs(), and cvLevelSetSparseGrid::Sweep_ComparePair().
int cvLevelSetStructuredGrid::LogicalIxToIJK (int log_ix, int * i, int * j, int * k) inline protected
Definition at line 295 of file cvLevelSetStructuredGrid.h.
References CV_ERROR, CV_OK, I_, J_, and K_.
Referenced by GetAdjacentIxs().
virtual void cvLevelSetStructuredGrid::MakePhiVtk (int closed = 0) protected pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by GetFront().
int cvLevelSetStructuredGrid::NumActiveNodes ()
Definition at line 1875 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, GetNext(), InitIter(), and cvLevelSetNode::state_.
Referenced by cvLevelSetSparseGrid::ProjectV().
virtual int cvLevelSetStructuredGrid::ProjectV (int save) pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by cvLevelSet::EvolveOneTimeStep(), cvLevelSetDenseGrid::ProjectV(), and cvLevelSetSparseGrid::ProjectV().
int cvLevelSetStructuredGrid::ProjectV (int posFlag, int save) protected
Definition at line 2102 of file cvLevelSetStructuredGrid.cxx.
References cvIntArrayList::Append(), CV_ERROR, CV_NODE_ACTIVE, CV_NODE_COVERED, CV_OK, cvLevelSetNode::F0_, cvLevelSetNode::F1_, GetAdjacentIxs(), GetNext(), grid_, cvLevelSetNode::index_, InitIter(), cvIntArrayList::IsEmpty(), ixBuffer_, ixBufferSz_, nodeSets_, nodeSetsPos_, NULL, cvLevelSetNode::phi_, pSetsValid_, cvIntArrayList::RemoveFromHead(), cvIntArrayList::Reset(), cvLevelSetNode::state_, SteepestAscentPhi(), SteepestDescentPhi(), and cvLevelSetNode::toDot_.
int cvLevelSetStructuredGrid::PSetsValid () inline
Definition at line 125 of file cvLevelSetStructuredGrid.h.
References pSetsValid_.
Referenced by LsetCore_ExtractProjectionSetsMtd().
virtual int cvLevelSetStructuredGrid::ReinitPhi () pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by cvLevelSet::RebuildPhi().
void cvLevelSetStructuredGrid::ResetNodeSets () protected
Definition at line 2342 of file cvLevelSetStructuredGrid.cxx.
References nodeSets_, nodeSetsPos_, nodeSetsSize_, and NULL.
Referenced by cvLevelSetDenseGrid::ProjectV(), cvLevelSetSparseGrid::ProjectV(), SaveActiveNodes(), SaveCoveredNodes(), SaveForceMinVNodes(), SaveMineNodes(), and SaveUncoveredNodes().
int cvLevelSetStructuredGrid::SaveActiveNodes ()
Definition at line 1854 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, CV_OK, GetNext(), cvLevelSetNode::index_, InitIter(), nodeSets_, nodeSetsPos_, pSetsValid_, ResetNodeSets(), and cvLevelSetNode::state_.
Referenced by GetActiveNodes().
int cvLevelSetStructuredGrid::SaveCoveredNodes ()
Definition at line 1894 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_COVERED, CV_OK, GetNext(), cvLevelSetNode::index_, InitIter(), nodeSets_, nodeSetsPos_, pSetsValid_, ResetNodeSets(), and cvLevelSetNode::state_.
Referenced by LsetCore_ExtractCoveredNodesMtd().
int cvLevelSetStructuredGrid::SaveForceMinVNodes ()
Definition at line 1937 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_FORCE_MINV, CV_OK, GetNext(), cvLevelSetNode::index_, InitIter(), nodeSets_, nodeSetsPos_, pSetsValid_, ResetNodeSets(), and cvLevelSetNode::state_.
Referenced by LsetCore_ExtractForceMinVNodesMtd().
int cvLevelSetStructuredGrid::SaveMineNodes ()
Definition at line 1958 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_MINE, CV_OK, GetNext(), cvLevelSetNode::index_, InitIter(), nodeSets_, nodeSetsPos_, pSetsValid_, ResetNodeSets(), and cvLevelSetNode::state_.
Referenced by LsetCore_ExtractMineNodesMtd().
int cvLevelSetStructuredGrid::SaveUncoveredNodes ()
Definition at line 1915 of file cvLevelSetStructuredGrid.cxx.
References CV_NODE_ACTIVE, CV_NODE_COVERED, CV_OK, GetNext(), cvLevelSetNode::index_, InitIter(), nodeSets_, nodeSetsPos_, pSetsValid_, ResetNodeSets(), and cvLevelSetNode::state_.
Referenced by LsetCore_ExtractUncoveredNodesMtd().
virtual int cvLevelSetStructuredGrid::SetBandParams (double innerPhi, double outerPhi, double mineWidth) inline virtual
Reimplemented in cvLevelSetSparseGrid.
Definition at line 68 of file cvLevelSetStructuredGrid.h.
References CV_ERROR.
Referenced by cvLevelSet::Init().
virtual char* cvLevelSetStructuredGrid::StatString () pure virtual
Implemented in cvLevelSetSparseGrid, and cvLevelSetDenseGrid.
Referenced by cvLevelSet::GetGridStatString().
int cvLevelSetStructuredGrid::SteepestAscentPhi (int ix) protected
Definition at line 2295 of file cvLevelSetStructuredGrid.cxx.
References GetAdjacentIxs(), grid_, hv_, init_, and cvLevelSetNode::phi_.
Referenced by ProjectV().
int cvLevelSetStructuredGrid::SteepestDescentPhi (int ix) protected
Definition at line 2253 of file cvLevelSetStructuredGrid.cxx.
References GetAdjacentIxs(), grid_, hv_, init_, and cvLevelSetNode::phi_.
Referenced by ProjectV().
int cvLevelSetStructuredGrid::UpdatePhi () virtual
Reimplemented in cvLevelSetSparseGrid.
Definition at line 443 of file cvLevelSetStructuredGrid.cxx.
References CV_ERROR, CV_OK, d0Valid_, delMinusValid_, delPlusValid_, cvLevelSetNode::deltaPhi_, deltaPhiValid_, dmiValid_, dpiValid_, GetNext(), InitIter(), k3dgValid_, k3dmValid_, kValid_, nValid_, cvLevelSetNode::phi_, and phiVtkValid_.
Referenced by cvLevelSet::EvolveOneTimeStep().
Member Data Documentation
cvLevelSetNode* cvLevelSetStructuredGrid::curr_ protected
Definition at line 157 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), cvLevelSetDenseGrid::GetNext(), and cvLevelSetDenseGrid::InitIter().
int cvLevelSetStructuredGrid::d0Valid_ protected
Definition at line 212 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindD0(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
int cvLevelSetStructuredGrid::delMinusValid_ protected
Definition at line 212 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindDelMinus(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
int cvLevelSetStructuredGrid::delPlusValid_ protected
Definition at line 212 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindDelPlus(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
int cvLevelSetStructuredGrid::deltaPhiValid_ protected
Definition at line 213 of file cvLevelSetStructuredGrid.h.
Referenced by ComputeDeltaPhi(), cvLevelSetStructuredGrid(), EvaluateV(), GetMaxPhiIncr(), GetMaxV(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
int cvLevelSetStructuredGrid::dim_ protected
Definition at line 197 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetStructuredGrid(), FindK(), FindN(), cvLevelSetSparseGrid::GetCSRStructure(), GetDim(), cvLevelSetDenseGrid::InitPhi(), cvLevelSetSparseGrid::InitSign_Internal(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetDenseGrid::MakePhiVtk(), and cvLevelSetSparseGrid::MakePhiVtk().
int cvLevelSetStructuredGrid::dmiValid_ protected
Definition at line 212 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindDmi(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
int cvLevelSetStructuredGrid::dpiValid_ protected
Definition at line 212 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindDpi(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
cvLevelSetNode* cvLevelSetStructuredGrid::grid_ protected
Definition at line 189 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::BuildL1Map(), cvLevelSetSparseGrid::ConstructCSR(), cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetStructuredGrid(), cvLevelSetSparseGrid::DeallocateCSR(), cvLevelSetDenseGrid::DeallocateNodes(), EvaluateV(), cvLevelSetDenseGrid::ExtendV(), FindD0i(), FindD0xi(), FindD0yi(), FindD0zi(), FindDmi(), FindDpi(), FindEdge(), cvLevelSetSparseGrid::GetCSRStructure(), cvLevelSetDenseGrid::GetMemoryUsage(), cvLevelSetSparseGrid::GetMemoryUsage(), cvLevelSetSparseGrid::GetNext(), GetNodeSets(), cvLevelSetSparseGrid::IJKPresentInCSR(), cvLevelSetSparseGrid::IJKToSparseIx(), cvLevelSetDenseGrid::InitIter(), cvLevelSetDenseGrid::MakePhiVtk(), cvLevelSetSparseGrid::MakePhiVtk(), cvLevelSetDenseGrid::MakeScalarsVtk(), cvLevelSetSparseGrid::PartitionToPolyData(), ProjectV(), cvLevelSetSparseGrid::SanityCheckCSR(), SteepestAscentPhi(), and SteepestDescentPhi().
double cvLevelSetStructuredGrid::hv_[3] protected
Definition at line 194 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), cvLevelSetSparseGrid::ConstructCSR(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetStructuredGrid(), FindD0i(), FindD0xi(), FindD0yi(), FindD0zi(), FindDmi(), FindDpi(), GetAnchorIx(), GetHv(), cvLevelSetSparseGrid::InitPhi(), cvLevelSetSparseGrid::InitSign_Internal(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetDenseGrid::MakePhiVtk(), cvLevelSetDenseGrid::MakeScalarsVtk(), SteepestAscentPhi(), and SteepestDescentPhi().
int cvLevelSetStructuredGrid::I_ protected
Definition at line 192 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::Blot(), cvLevelSetSparseGrid::BuildSeedInterface(), CloseHoles(), cvLevelSetSparseGrid::ComputeHashIx(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetSparseGrid::cvLevelSetSparseGrid(), cvLevelSetStructuredGrid(), cvLevelSetDenseGrid::FindNearestActiveNode(), cvLevelSetSparseGrid::IJKPresentInCSR(), cvLevelSetSparseGrid::IJKPresentInHT(), cvLevelSetSparseGrid::IJKToDenseIx(), cvLevelSetDenseGrid::IJKToIndex(), IJKToLogicalIx(), cvLevelSetSparseGrid::InitPhi(), cvLevelSetSparseGrid::InitSign_Internal(), IxWithinExtent(), LogicalIxToIJK(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetDenseGrid::MakePhiVtk(), cvLevelSetSparseGrid::MakePhiVtk(), cvLevelSetDenseGrid::MakeScalarsVtk(), cvLevelSetSparseGrid::PollNeighborSigns(), cvLevelSetSparseGrid::SanityCheckCSR(), cvLevelSetSparseGrid::Sweep(), and cvLevelSetSparseGrid::Sweep_MarkActiveNodes().
int cvLevelSetStructuredGrid::init_ protected
Definition at line 211 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetStructuredGrid(), cvLevelSetDenseGrid::InitPhi(), cvLevelSetSparseGrid::InitPhi(), cvLevelSetSparseGrid::InitPhi_Internal(), cvLevelSetSparseGrid::InitSign_Internal(), SteepestAscentPhi(), and SteepestDescentPhi().
int* cvLevelSetStructuredGrid::ixBuffer_ protected
Definition at line 169 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetStructuredGrid(), GetStructuredGridMemoryUsage(), cvLevelSetSparseGrid::InitIxBuffer(), ProjectV(), and cvLevelSetDenseGrid::~cvLevelSetDenseGrid().
int cvLevelSetStructuredGrid::ixBufferSz_ protected
Definition at line 170 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetDenseGrid::cvLevelSetDenseGrid(), GetStructuredGridMemoryUsage(), cvLevelSetSparseGrid::InitIxBuffer(), and ProjectV().
int cvLevelSetStructuredGrid::J_ protected
Definition at line 192 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::Blot(), cvLevelSetSparseGrid::BuildSeedInterface(), CloseHoles(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetSparseGrid::cvLevelSetSparseGrid(), cvLevelSetStructuredGrid(), cvLevelSetDenseGrid::FindNearestActiveNode(), cvLevelSetSparseGrid::IJKPresentInCSR(), cvLevelSetSparseGrid::IJKPresentInHT(), cvLevelSetSparseGrid::IJKToDenseIx(), cvLevelSetDenseGrid::IJKToIndex(), IJKToLogicalIx(), cvLevelSetSparseGrid::InitPhi(), cvLevelSetSparseGrid::InitSign_Internal(), IxWithinExtent(), LogicalIxToIJK(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetDenseGrid::MakePhiVtk(), cvLevelSetSparseGrid::MakePhiVtk(), cvLevelSetDenseGrid::MakeScalarsVtk(), cvLevelSetSparseGrid::PollNeighborSigns(), cvLevelSetSparseGrid::SanityCheckCSR(), cvLevelSetSparseGrid::Sweep(), and cvLevelSetSparseGrid::Sweep_MarkActiveNodes().
int cvLevelSetStructuredGrid::k3dgValid_ protected
Definition at line 214 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindK3dg(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
int cvLevelSetStructuredGrid::k3dmValid_ protected
Definition at line 214 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindK3dm(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
int cvLevelSetStructuredGrid::K_ protected
Definition at line 192 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::Blot(), cvLevelSetSparseGrid::BuildSeedInterface(), CloseHoles(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetSparseGrid::cvLevelSetSparseGrid(), cvLevelSetStructuredGrid(), cvLevelSetDenseGrid::FindNearestActiveNode(), cvLevelSetSparseGrid::IJKPresentInCSR(), cvLevelSetSparseGrid::IJKPresentInHT(), cvLevelSetSparseGrid::InitPhi(), cvLevelSetSparseGrid::InitSign_Internal(), IxWithinExtent(), LogicalIxToIJK(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetDenseGrid::MakePhiVtk(), cvLevelSetSparseGrid::MakePhiVtk(), cvLevelSetDenseGrid::MakeScalarsVtk(), cvLevelSetSparseGrid::PollNeighborSigns(), cvLevelSetSparseGrid::SanityCheckCSR(), cvLevelSetSparseGrid::Sweep(), and cvLevelSetSparseGrid::Sweep_MarkActiveNodes().
int cvLevelSetStructuredGrid::kValid_ protected
Definition at line 214 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindK(), FindK2d(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
double cvLevelSetStructuredGrid::mainDiagonal_ protected
Definition at line 198 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), GetMainDiagonal(), and cvLevelSetSparseGrid::SetBandParams().
double cvLevelSetStructuredGrid::maxh_ protected
Definition at line 195 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::ConstructHT(), and cvLevelSetStructuredGrid().
double cvLevelSetStructuredGrid::minh_ protected
Definition at line 195 of file cvLevelSetStructuredGrid.h.
Referenced by ComputeDeltaPhi(), ComputeDt(), cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetStructuredGrid(), EvaluateV(), FindEdge(), cvLevelSetDenseGrid::FindNearestActiveNode(), GetAnchorIx(), GetMinH(), cvLevelSetDenseGrid::InitPhi(), and InterpZLS().
int* cvLevelSetStructuredGrid::nodeSets_ protected
Definition at line 178 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetStructuredGrid(), GetNodeSets(), GetStructuredGridMemoryUsage(), cvLevelSetSparseGrid::InitNodeSets(), ProjectV(), ResetNodeSets(), SaveActiveNodes(), SaveCoveredNodes(), SaveForceMinVNodes(), SaveMineNodes(), SaveUncoveredNodes(), and cvLevelSetDenseGrid::~cvLevelSetDenseGrid().
int cvLevelSetStructuredGrid::nodeSetsPos_ protected
Definition at line 180 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetSparseGrid::InitNodeSets(), ProjectV(), ResetNodeSets(), SaveActiveNodes(), SaveCoveredNodes(), SaveForceMinVNodes(), SaveMineNodes(), and SaveUncoveredNodes().
int cvLevelSetStructuredGrid::nodeSetsSize_ protected
Definition at line 179 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetDenseGrid::cvLevelSetDenseGrid(), GetNodeSets(), GetStructuredGridMemoryUsage(), cvLevelSetSparseGrid::InitNodeSets(), and ResetNodeSets().
int cvLevelSetStructuredGrid::numDenseNodes_ protected
Definition at line 193 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::cvLevelSetSparseGrid(), and cvLevelSetStructuredGrid().
int cvLevelSetStructuredGrid::numNodes_ protected
Definition at line 190 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetDenseGrid::ExtendV(), cvLevelSetDenseGrid::GetMemoryUsage(), cvLevelSetDenseGrid::GetNext(), cvLevelSetDenseGrid::IJKToIndex(), cvLevelSetDenseGrid::MakePhiVtk(), cvLevelSetDenseGrid::MakeScalarsVtk(), and cvLevelSetDenseGrid::StatString().
int cvLevelSetStructuredGrid::nValid_ protected
Definition at line 214 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindN(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
double cvLevelSetStructuredGrid::oneOverTol_ protected
Definition at line 208 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), FindK2d(), FindK3dg(), FindK3dm(), GetMaxPhiIncr(), and GetMaxV().
double cvLevelSetStructuredGrid::origin_[3] protected
Definition at line 196 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), cvLevelSetSparseGrid::ConstructCSR(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetDenseGrid::cvLevelSetDenseGrid(), cvLevelSetStructuredGrid(), GetAnchorIx(), cvLevelSetSparseGrid::InitPhi(), cvLevelSetSparseGrid::InitSign_Internal(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetDenseGrid::MakePhiVtk(), and cvLevelSetDenseGrid::MakeScalarsVtk().
vtkDataSet* cvLevelSetStructuredGrid::phiVtk_ protected
Definition at line 223 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetSparseGrid::CSRToPolyData(), cvLevelSetStructuredGrid(), GetFront(), cvLevelSetDenseGrid::GetPhi(), cvLevelSetSparseGrid::GetPhi(), GetStructuredGridMemoryUsage(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetDenseGrid::MakePhiVtk(), cvLevelSetSparseGrid::MakePhiVtk(), and ~cvLevelSetStructuredGrid().
int cvLevelSetStructuredGrid::phiVtkValid_ protected
Definition at line 224 of file cvLevelSetStructuredGrid.h.
Referenced by CloseHoles(), cvLevelSetStructuredGrid(), cvLevelSetDenseGrid::InitPhi(), cvLevelSetSparseGrid::InitPhi(), cvLevelSetSparseGrid::InitPhi_Internal(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetDenseGrid::MakePhiVtk(), cvLevelSetSparseGrid::MakePhiVtk(), UpdatePhi(), and cvLevelSetSparseGrid::UpdatePhi().
int cvLevelSetStructuredGrid::pSetsValid_ protected
Definition at line 182 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), ProjectV(), PSetsValid(), SaveActiveNodes(), SaveCoveredNodes(), SaveForceMinVNodes(), SaveMineNodes(), and SaveUncoveredNodes().
double cvLevelSetStructuredGrid::relTol_ protected
Definition at line 208 of file cvLevelSetStructuredGrid.h.
Referenced by ComputeDeltaPhi(), cvLevelSetStructuredGrid(), EvaluateV(), FindEdge(), GetAnchorIx(), cvLevelSetDenseGrid::InitPhi(), InterpZLS(), and cvLevelSetSparseGrid::SetBandParams().
double cvLevelSetStructuredGrid::tol_ protected
Definition at line 208 of file cvLevelSetStructuredGrid.h.
Referenced by ComputeDeltaPhi(), ComputeDt(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetStructuredGrid(), EvaluateV(), FindK2d(), FindK3dg(), FindK3dm(), GetBoundaryData(), cvLevelSetSparseGrid::InitPhi(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetDenseGrid::MakePhiVtk(), cvLevelSetSparseGrid::MakePhiVtk(), cvLevelSetSparseGrid::ReinitPhi(), cvLevelSetSparseGrid::TopoUpdate(), and cvLevelSetSparseGrid::UpdatePhi().
cvLevelSetVelocity* cvLevelSetStructuredGrid::velocity_ protected
Definition at line 227 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid().
cvPolyData* cvLevelSetStructuredGrid::velocityVectors_ protected
Definition at line 226 of file cvLevelSetStructuredGrid.h.
Referenced by cvLevelSetStructuredGrid(), EvaluateV(), GetStructuredGridMemoryUsage(), and GetVelocityVectors().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetStructuredGrid.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cvLevelSetStructuredGrid.cxx