simvascular: ImgInfo Class Reference
ImgInfo Class Reference
#include <ImgInfo.h>
Public Member Functions
virtual void SetMinValue (double value)
virtual double GetMinValue ()
virtual void SetMaxValue (double value)
virtual double GetMaxValue ()
ImgInfo ()
virtual ~ImgInfo ()
ImgInfo (int extent[6], double origin[3], double spacing[3])
ImgInfo (int vextent[6], double vorigin[3], double vspacing[3], double minValue, double maxValue)
ImgInfo (vtkStructuredPoints *vtksp)
ImgInfo (const ImgInfo &other)
void SetExtent (int vextent[6])
void GetExtent (int *dOut)
int * GetExtent ()
void SetOrigin (double vorigin[3])
void GetOrigin (double *dOut)
double * GetOrigin ()
void SetSpacing (double vspacing[3])
void GetSpacing (double *dOut)
double * GetSpacing ()
void Print (ostream &os)
Private Attributes
int extent [6]
double origin [3]
double spacing [3]
double m_MinValue
double m_MaxValue
Detailed Description
Definition at line 26 of file ImgInfo.h.
Constructor & Destructor Documentation
ImgInfo::ImgInfo () inline
Definition at line 40 of file ImgInfo.h.
References extent, m_MaxValue, m_MinValue, origin, SetExtent(), SetOrigin(), SetSpacing(), and spacing.
virtual ImgInfo::~ImgInfo () inline virtual
Definition at line 53 of file ImgInfo.h.
ImgInfo::ImgInfo (int extent[6], double origin[3], double spacing[3]) inline
Definition at line 55 of file ImgInfo.h.
References m_MaxValue, m_MinValue, SetExtent(), SetOrigin(), and SetSpacing().
ImgInfo::ImgInfo (int vextent[6], double vorigin[3], double vspacing[3], double minValue, double maxValue) inline
Definition at line 64 of file ImgInfo.h.
References extent, m_MaxValue, m_MinValue, origin, SetExtent(), SetOrigin(), SetSpacing(), and spacing.
ImgInfo::ImgInfo (vtkStructuredPoints * vtksp) inline
Definition at line 73 of file ImgInfo.h.
References extent, m_MaxValue, m_MinValue, origin, SetExtent(), SetOrigin(), SetSpacing(), and spacing.
ImgInfo::ImgInfo (const ImgInfo & other) inline
Definition at line 90 of file ImgInfo.h.
References extent, m_MaxValue, m_MinValue, origin, SetExtent(), SetOrigin(), SetSpacing(), and spacing.
Member Function Documentation
void ImgInfo::GetExtent (int * dOut) inline
Definition at line 102 of file ImgInfo.h.
References extent.
Referenced by cvITKLevelSet::SetFeatureImage(), cvITKLevelSet::SetInputImage(), cvITKLSUtil::vtkPolyDataTo2DImage(), and cvITKLSUtil::vtkPolyDataToVolume().
int* ImgInfo::GetExtent () inline
Definition at line 108 of file ImgInfo.h.
References extent.
virtual double ImgInfo::GetMaxValue () inline virtual
Definition at line 38 of file ImgInfo.h.
Referenced by cvITKLSUtil::itk2vtkRecastAndRescale(), and cvITKLSUtil::vtk2itkRecastAndRescale().
virtual double ImgInfo::GetMinValue () inline virtual
Definition at line 36 of file ImgInfo.h.
Referenced by cvITKLSUtil::itk2vtkRecastAndRescale(), and cvITKLSUtil::vtk2itkRecastAndRescale().
void ImgInfo::GetOrigin (double * dOut) inline
Definition at line 116 of file ImgInfo.h.
References origin.
Referenced by cvITKLSUtil::itk2vtkRecast(), cvITKLSUtil::itk2vtkRecastAndRescale(), cvITKLSUtil::vtk2itkBinaryImageToSeedImage(), cvITKLSUtil::vtk2itkRecastAndRescale(), cvITKLSUtil::vtkChangeImageInformation(), cvITKLSUtil::vtkPolyDataTo2DImage(), and cvITKLSUtil::vtkPolyDataToVolume().
double* ImgInfo::GetOrigin () inline
Definition at line 122 of file ImgInfo.h.
References origin.
void ImgInfo::GetSpacing (double * dOut) inline
Definition at line 130 of file ImgInfo.h.
References spacing.
Referenced by cvITKLSUtil::itk2vtkRecast(), cvITKLSUtil::itk2vtkRecastAndRescale(), cvITKLSUtil::vtk2itkBinaryImageToSeedImage(), cvITKLSUtil::vtk2itkRecastAndRescale(), cvITKLSUtil::vtkChangeImageInformation(), cvITKLSUtil::vtkPolyDataTo2DImage(), and cvITKLSUtil::vtkPolyDataToVolume().
double* ImgInfo::GetSpacing () inline
Definition at line 136 of file ImgInfo.h.
References spacing.
void ImgInfo::Print (ostream & os) inline
Definition at line 140 of file ImgInfo.h.
References extent, m_MaxValue, m_MinValue, origin, and spacing.
Referenced by itkutils_PdToImgCmd().
void ImgInfo::SetExtent (int vextent[6]) inline
Definition at line 99 of file ImgInfo.h.
References extent.
Referenced by ImgInfo(), itkutils_FractEdgeProximity3DCmd(), itkutils_GradientMagnitudeGaussianCmd(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetFeatureImage(), cvITKLevelSet::SetFeatureImage(), cvITKLevelSet::SetInputImage(), and cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetInputImage().
virtual void ImgInfo::SetMaxValue (double value) inline virtual
Definition at line 37 of file ImgInfo.h.
Referenced by itkutils_FractEdgeProximity3DCmd(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetFeatureImage(), and cvITKLevelSetBase< TInputImage, TInternalPixelType >::SetInputImage().
virtual void ImgInfo::SetMinValue (double value) inline virtual
Definition at line 35 of file ImgInfo.h.
Referenced by itkutils_FractEdgeProximity3DCmd().
void ImgInfo::SetOrigin (double vorigin[3]) inline
Definition at line 113 of file ImgInfo.h.
References origin.
Referenced by ImgInfo().
void ImgInfo::SetSpacing (double vspacing[3]) inline
Definition at line 126 of file ImgInfo.h.
References spacing.
Referenced by ImgInfo().
Member Data Documentation
int ImgInfo::extent[6] private
Definition at line 29 of file ImgInfo.h.
Referenced by GetExtent(), ImgInfo(), Print(), and SetExtent().
double ImgInfo::m_MaxValue private
Definition at line 33 of file ImgInfo.h.
Referenced by ImgInfo(), and Print().
double ImgInfo::m_MinValue private
Definition at line 32 of file ImgInfo.h.
Referenced by ImgInfo(), and Print().
double ImgInfo::origin[3] private
Definition at line 30 of file ImgInfo.h.
Referenced by GetOrigin(), ImgInfo(), Print(), and SetOrigin().
double ImgInfo::spacing[3] private
Definition at line 31 of file ImgInfo.h.
Referenced by GetSpacing(), ImgInfo(), Print(), and SetSpacing().
The documentation for this class was generated from the following file:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/ITK/Include/ImgInfo.h