simvascular: cvITKLevelSet Class Reference
cvITKLevelSet Class Reference
#include <cvITKLevelSet.h>
Public Types
typedef cvITKLevelSet Self
typedef itk::Image< short, 2 > ITKExternalImageType
typedef itk::Image< float, 2 > ITKInternalImageType
typedef itk::VTKImageImport
< ITKExternalImageType > itkExternalImportType
typedef itk::VTKImageExport
< ITKExternalImageType > itkExternalExportType
typedef itk::VTKImageImport
< ITKInternalImageType > itkInternalImportType
typedef itk::VTKImageExport
< ITKInternalImageType > itkInternalExportType
Public Member Functions
virtual const char * GetNameOfClass () const
void DeallocateFeatureObjs ()
int SetFeatureImage (cvStrPts *s)
int GetFeatureImage (cvStrPts **s)
cvStrPts * GetVelocityImage ()
void DeallocateSeedObjs ()
int ComputePhaseOneLevelSet (float kc, float expFactorRising, float expFactorFalling)
int ComputePhaseTwoLevelSet (float kupp, float klow)
int ComputeGACLevelSet (float expFactorRising)
int GenerateFeatureImage ()
int GenerateSeedImage ()
void DeallocateFrontObjs ()
int GetFront (cvPolyData **front)
cvPolyData * GetFront ()
cvStrPts * GetFrontImage ()
virtual void SetMaxIterations (int value)
virtual int GetMaxIterations ()
virtual void SetMaxRMSError (double value)
virtual double GetMaxRMSError ()
virtual void SetAdvectionScaling (double value)
virtual double GetAdvectionScaling ()
virtual void SetPropagationScaling (double value)
virtual double GetPropagationScaling ()
virtual void SetCurvatureScaling (double value)
virtual double GetCurvatureScaling ()
virtual void SetSigmaFeature (double value)
virtual double GetSigmaFeature ()
virtual void SetSigmaAdvection (double value)
virtual double GetSigmaAdvection ()
virtual int SetSeed (cvPolyData *value)
virtual int GetSeed (cvPolyData **value)
virtual void SetDebug (bool value)
virtual bool GetDebug ()
int SetInputImage (cvStrPts *s)
virtual int GetInputImage (cvStrPts **value)
void SetInternalImgInfo (vtkStructuredPoints *vtksp)
void ViewITKFront ()
void WriteFrontImages ()
cvITKLevelSet ()
virtual ~cvITKLevelSet ()
Public Attributes
char tclName_ [CV_STRLEN]
Protected Member Functions
void GenerateData ()
cvITKLevelSet (const cvITKLevelSet &)
void operator= (const cvITKLevelSet &)
Private Attributes
ImgInfo InternalImgInfo
ImgInfo ExternalImgInfo
cvStrPts * m_cvInputImage
cvPolyData * m_cvSeed
ITKInternalImageType::Pointer m_itkFeatureImage
ITKInternalImageType::Pointer m_itkSeedImage
vtkSmartPointer< vtkPolyData > m_vtkFrontPolyData
vtkSmartPointer
< vtkStructuredPoints > m_vtkFrontImage
vtkSmartPointer
< vtkStructuredPoints > m_vtkFeatureImage
ITKInternalImageType::Pointer m_itkFrontImage
cvStrPts * m_cvSeedImage
double m_SigmaFeature
double m_SigmaAdvection
double m_MaxRMSError
int m_MaxIterations
double m_PropagationScaling
double m_CurvatureScaling
double m_AdvectionScaling
bool m_Debug
Detailed Description
Definition at line 63 of file cvITKLevelSet.h.
Member Typedef Documentation
typedef itk::VTKImageExport<ITKExternalImageType> cvITKLevelSet::itkExternalExportType
Definition at line 75 of file cvITKLevelSet.h.
typedef itk::Image<short,2> cvITKLevelSet::ITKExternalImageType
Definition at line 71 of file cvITKLevelSet.h.
typedef itk::VTKImageImport<ITKExternalImageType> cvITKLevelSet::itkExternalImportType
Definition at line 74 of file cvITKLevelSet.h.
typedef itk::VTKImageExport<ITKInternalImageType> cvITKLevelSet::itkInternalExportType
Definition at line 78 of file cvITKLevelSet.h.
typedef itk::Image<float,2> cvITKLevelSet::ITKInternalImageType
Definition at line 72 of file cvITKLevelSet.h.
typedef itk::VTKImageImport<ITKInternalImageType> cvITKLevelSet::itkInternalImportType
Definition at line 77 of file cvITKLevelSet.h.
typedef cvITKLevelSet cvITKLevelSet::Self
Typedefs
Definition at line 70 of file cvITKLevelSet.h.
Constructor & Destructor Documentation
cvITKLevelSet::cvITKLevelSet ()
Definition at line 49 of file cvITKLevelSet.cxx.
References m_AdvectionScaling, m_CurvatureScaling, m_cvInputImage, m_cvSeed, m_cvSeedImage, m_Debug, m_itkFeatureImage, m_itkFrontImage, m_itkSeedImage, m_MaxIterations, m_MaxRMSError, m_PropagationScaling, m_SigmaAdvection, m_SigmaFeature, m_vtkFeatureImage, m_vtkFrontImage, m_vtkFrontPolyData, and NULL.
virtual cvITKLevelSet::~cvITKLevelSet () inline virtual
Definition at line 174 of file cvITKLevelSet.h.
References m_cvInputImage, m_cvSeedImage, and NULL.
cvITKLevelSet::cvITKLevelSet (const cvITKLevelSet &) protected
Member Function Documentation
int cvITKLevelSet::ComputeGACLevelSet (float expFactorRising)
Definition at line 193 of file cvITKLevelSet.cxx.
References cvITKLSUtil::CopyITKtoVTK(), cvITKNewMacro, DeallocateFrontObjs(), GenerateFeatureImage(), GenerateSeedImage(), GetDebug(), cvITKLSUtil::itkDeepCopy(), m_AdvectionScaling, m_CurvatureScaling, m_itkFeatureImage, m_itkFrontImage, m_itkSeedImage, m_MaxIterations, m_MaxRMSError, m_PropagationScaling, m_vtkFeatureImage, m_vtkFrontImage, and m_vtkFrontPolyData.
int cvITKLevelSet::ComputePhaseOneLevelSet (float kc, float expFactorRising, float expFactorFalling)
Definition at line 361 of file cvITKLevelSet.cxx.
References cvITKNewMacro, DeallocateFrontObjs(), ExternalImgInfo, GenerateFeatureImage(), GenerateSeedImage(), GetDebug(), m_AdvectionScaling, m_CurvatureScaling, m_itkFeatureImage, m_itkFrontImage, m_itkSeedImage, m_MaxIterations, m_MaxRMSError, m_PropagationScaling, m_SigmaAdvection, m_SigmaFeature, m_vtkFeatureImage, m_vtkFrontImage, and m_vtkFrontPolyData.
int cvITKLevelSet::ComputePhaseTwoLevelSet (float kupp, float klow)
Definition at line 522 of file cvITKLevelSet.cxx.
References cvITKNewMacro, ExternalImgInfo, GenerateFeatureImage(), GenerateSeedImage(), GetDebug(), cvITKLSUtil::itk2vtkRecast(), m_AdvectionScaling, m_CurvatureScaling, m_itkFeatureImage, m_itkSeedImage, m_MaxIterations, m_MaxRMSError, m_PropagationScaling, m_SigmaAdvection, m_vtkFeatureImage, m_vtkFrontImage, and m_vtkFrontPolyData.
void cvITKLevelSet::DeallocateFeatureObjs ()
Definition at line 80 of file cvITKLevelSet.cxx.
References m_cvInputImage, and NULL.
Referenced by SetFeatureImage(), and SetInputImage().
void cvITKLevelSet::DeallocateFrontObjs ()
Definition at line 151 of file cvITKLevelSet.cxx.
Referenced by ComputeGACLevelSet(), and ComputePhaseOneLevelSet().
void cvITKLevelSet::DeallocateSeedObjs ()
Definition at line 181 of file cvITKLevelSet.cxx.
References m_cvSeedImage, and NULL.
void cvITKLevelSet::GenerateData () protected
int cvITKLevelSet::GenerateFeatureImage ()
Definition at line 671 of file cvITKLevelSet.cxx.
References ExternalImgInfo, cvStrPts::GetVtkStructuredPoints(), InternalImgInfo, m_cvInputImage, m_itkFeatureImage, m_SigmaFeature, and m_vtkFeatureImage.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), and ComputePhaseTwoLevelSet().
int cvITKLevelSet::GenerateSeedImage ()
Definition at line 686 of file cvITKLevelSet.cxx.
References ExternalImgInfo, cvPolyData::GetVtkPolyData(), InternalImgInfo, m_cvSeed, m_itkSeedImage, cvITKLSUtil::vtk2itkBinaryImageToSeedImage(), and cvITKLSUtil::vtkPolyDataTo2DImage().
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), and ComputePhaseTwoLevelSet().
virtual double cvITKLevelSet::GetAdvectionScaling () inline virtual
Definition at line 120 of file cvITKLevelSet.h.
virtual double cvITKLevelSet::GetCurvatureScaling () inline virtual
Definition at line 126 of file cvITKLevelSet.h.
virtual bool cvITKLevelSet::GetDebug () inline virtual
Definition at line 138 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), and ComputePhaseTwoLevelSet().
int cvITKLevelSet::GetFeatureImage (cvStrPts ** s)
Definition at line 115 of file cvITKLevelSet.cxx.
References m_cvInputImage, and NULL.
int cvITKLevelSet::GetFront (cvPolyData ** front)
Definition at line 156 of file cvITKLevelSet.cxx.
References GetFront().
cvPolyData * cvITKLevelSet::GetFront ()
Definition at line 166 of file cvITKLevelSet.cxx.
References m_vtkFrontPolyData, and NULL.
Referenced by GetFront().
cvStrPts * cvITKLevelSet::GetFrontImage ()
Definition at line 136 of file cvITKLevelSet.cxx.
References m_vtkFrontImage, and NULL.
virtual int cvITKLevelSet::GetInputImage (cvStrPts ** value) inline virtual
Definition at line 142 of file cvITKLevelSet.h.
virtual int cvITKLevelSet::GetMaxIterations () inline virtual
Definition at line 114 of file cvITKLevelSet.h.
virtual double cvITKLevelSet::GetMaxRMSError () inline virtual
Definition at line 117 of file cvITKLevelSet.h.
virtual const char* cvITKLevelSet::GetNameOfClass () const inline virtual
Definition at line 80 of file cvITKLevelSet.h.
virtual double cvITKLevelSet::GetPropagationScaling () inline virtual
Definition at line 123 of file cvITKLevelSet.h.
virtual int cvITKLevelSet::GetSeed (cvPolyData ** value) inline virtual
Definition at line 135 of file cvITKLevelSet.h.
virtual double cvITKLevelSet::GetSigmaAdvection () inline virtual
Definition at line 132 of file cvITKLevelSet.h.
virtual double cvITKLevelSet::GetSigmaFeature () inline virtual
Definition at line 129 of file cvITKLevelSet.h.
cvStrPts * cvITKLevelSet::GetVelocityImage ()
Definition at line 125 of file cvITKLevelSet.cxx.
References m_vtkFeatureImage, and NULL.
void cvITKLevelSet::operator= (const cvITKLevelSet &) protected
virtual void cvITKLevelSet::SetAdvectionScaling (double value) inline virtual
Definition at line 119 of file cvITKLevelSet.h.
virtual void cvITKLevelSet::SetCurvatureScaling (double value) inline virtual
Definition at line 125 of file cvITKLevelSet.h.
virtual void cvITKLevelSet::SetDebug (bool value) inline virtual
Definition at line 137 of file cvITKLevelSet.h.
int cvITKLevelSet::SetFeatureImage (cvStrPts * s)
Definition at line 103 of file cvITKLevelSet.cxx.
References DeallocateFeatureObjs(), ExternalImgInfo, ImgInfo::GetExtent(), cvStrPts::GetVtkStructuredPoints(), InternalImgInfo, and ImgInfo::SetExtent().
int cvITKLevelSet::SetInputImage (cvStrPts * s)
Definition at line 88 of file cvITKLevelSet.cxx.
References DeallocateFeatureObjs(), ExternalImgInfo, ImgInfo::GetExtent(), cvRepositoryData::GetName(), cvStrPts::GetVtkStructuredPoints(), InternalImgInfo, m_cvInputImage, ImgInfo::SetExtent(), and cvRepositoryData::SetName().
void cvITKLevelSet::SetInternalImgInfo (vtkStructuredPoints * vtksp) inline
Definition at line 145 of file cvITKLevelSet.h.
virtual void cvITKLevelSet::SetMaxIterations (int value) inline virtual
Definition at line 113 of file cvITKLevelSet.h.
virtual void cvITKLevelSet::SetMaxRMSError (double value) inline virtual
Definition at line 116 of file cvITKLevelSet.h.
virtual void cvITKLevelSet::SetPropagationScaling (double value) inline virtual
Definition at line 122 of file cvITKLevelSet.h.
virtual int cvITKLevelSet::SetSeed (cvPolyData * value) inline virtual
Definition at line 134 of file cvITKLevelSet.h.
virtual void cvITKLevelSet::SetSigmaAdvection (double value) inline virtual
Definition at line 131 of file cvITKLevelSet.h.
virtual void cvITKLevelSet::SetSigmaFeature (double value) inline virtual
Definition at line 128 of file cvITKLevelSet.h.
void cvITKLevelSet::ViewITKFront () inline
Definition at line 151 of file cvITKLevelSet.h.
References m_itkFrontImage.
void cvITKLevelSet::WriteFrontImages () inline
Definition at line 164 of file cvITKLevelSet.h.
References m_itkFrontImage, m_vtkFrontImage, and cvITKLSUtil::WriteImage().
Member Data Documentation
ImgInfo cvITKLevelSet::ExternalImgInfo private
Definition at line 202 of file cvITKLevelSet.h.
Referenced by ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), GenerateFeatureImage(), GenerateSeedImage(), SetFeatureImage(), and SetInputImage().
ImgInfo cvITKLevelSet::InternalImgInfo private
Definition at line 201 of file cvITKLevelSet.h.
Referenced by GenerateFeatureImage(), GenerateSeedImage(), SetFeatureImage(), and SetInputImage().
double cvITKLevelSet::m_AdvectionScaling private
Definition at line 228 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), and cvITKLevelSet().
double cvITKLevelSet::m_CurvatureScaling private
Definition at line 227 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), and cvITKLevelSet().
cvStrPts* cvITKLevelSet::m_cvInputImage private
Definition at line 204 of file cvITKLevelSet.h.
Referenced by cvITKLevelSet(), DeallocateFeatureObjs(), GenerateFeatureImage(), GetFeatureImage(), SetInputImage(), and ~cvITKLevelSet().
cvPolyData* cvITKLevelSet::m_cvSeed private
Definition at line 205 of file cvITKLevelSet.h.
Referenced by cvITKLevelSet(), and GenerateSeedImage().
cvStrPts* cvITKLevelSet::m_cvSeedImage private
Definition at line 217 of file cvITKLevelSet.h.
Referenced by cvITKLevelSet(), DeallocateSeedObjs(), and ~cvITKLevelSet().
bool cvITKLevelSet::m_Debug private
Definition at line 231 of file cvITKLevelSet.h.
Referenced by cvITKLevelSet().
ITKInternalImageType::Pointer cvITKLevelSet::m_itkFeatureImage private
Definition at line 207 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), cvITKLevelSet(), and GenerateFeatureImage().
ITKInternalImageType::Pointer cvITKLevelSet::m_itkFrontImage private
Definition at line 216 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), cvITKLevelSet(), ViewITKFront(), and WriteFrontImages().
ITKInternalImageType::Pointer cvITKLevelSet::m_itkSeedImage private
Definition at line 208 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), cvITKLevelSet(), and GenerateSeedImage().
int cvITKLevelSet::m_MaxIterations private
Definition at line 225 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), and cvITKLevelSet().
double cvITKLevelSet::m_MaxRMSError private
Definition at line 224 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), and cvITKLevelSet().
double cvITKLevelSet::m_PropagationScaling private
Definition at line 226 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), and cvITKLevelSet().
double cvITKLevelSet::m_SigmaAdvection private
Definition at line 221 of file cvITKLevelSet.h.
Referenced by ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), and cvITKLevelSet().
double cvITKLevelSet::m_SigmaFeature private
Definition at line 220 of file cvITKLevelSet.h.
Referenced by ComputePhaseOneLevelSet(), cvITKLevelSet(), and GenerateFeatureImage().
vtkSmartPointer<vtkStructuredPoints> cvITKLevelSet::m_vtkFeatureImage private
Definition at line 215 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), cvITKLevelSet(), GenerateFeatureImage(), and GetVelocityImage().
vtkSmartPointer<vtkStructuredPoints> cvITKLevelSet::m_vtkFrontImage private
Definition at line 212 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), cvITKLevelSet(), GetFrontImage(), and WriteFrontImages().
vtkSmartPointer<vtkPolyData> cvITKLevelSet::m_vtkFrontPolyData private
Definition at line 211 of file cvITKLevelSet.h.
Referenced by ComputeGACLevelSet(), ComputePhaseOneLevelSet(), ComputePhaseTwoLevelSet(), cvITKLevelSet(), and GetFront().
char cvITKLevelSet::tclName_[CV_STRLEN]
Definition at line 185 of file cvITKLevelSet.h.
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/ITK/cvITKLevelSet.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/ITK/cvITKLevelSet.cxx