simvascular: PostSolver Class Reference
PostSolver Class Reference
Public Member Functions
PostSolver ()
~PostSolver ()
int SetInputDirectory (const char *indir)
int QueryNumberOfSolutionVariables (int stepNumber)
int QueryNumberOfProcessors ()
int ReadConnectivity ()
int GetNumberOfNodalCoordinates ()
int GetNumberOfElements ()
int GetNumberOfSolutionVariables ()
int GetNumberOfProcessorsUsed ()
double * GetCoordinatePtr ()
int * GetConnectivityPtr ()
double * GetWallProperties ()
int ExportFlowSolverFileFormat (int lstep, int newstepnumber, bool RequestedNewSn, bool RequestedDisplacements, bool RequestedWallprops, bool RequestedTimeDeriv, double *qglobal, double *aglobal, double *dglobal, double *wpglobal, const char *outdir)
int ExportYBar (int stepnumber, int numy, double *yglobal, const char *outdir)
int ParseRestartFile (int stepNumber, const char *field, int *numval, double **myglobal)
int SetInputFileType (const char *iotype)
int CompareResidualFiles (const char *newResFile, const char *refResFile, double threshold)
int CompareVTUFiles (const char *newResFile, const char *refResFile, double threshold)
Private Attributes
int ione_
int itwo_
int ithree_
int iseven_
double * xlocal_
double * xglobal_
int * ien_
int ** ncorpd2d_
double * wplocal_
double * wpglobal_
char iotype_ [80]
char indir_ [255]
int numvar_
int numprocs_
int nshgtot_
int neltot_
int maxnshg_
int nsd_
Detailed Description
Definition at line 85 of file post_solver.cxx.
Constructor & Destructor Documentation
PostSolver::PostSolver ()
Definition at line 145 of file post_solver.cxx.
References NULL.
PostSolver::~PostSolver ()
Definition at line 174 of file post_solver.cxx.
References NULL.
Member Function Documentation
int PostSolver::CompareResidualFiles (const char * newResFile, const char * refResFile, double threshold)
Definition at line 923 of file post_solver.cxx.
References readResidualFromHistorFile().
Referenced by main().
int PostSolver::CompareVTUFiles (const char * newResFile, const char * refResFile, double threshold)
Definition at line 994 of file post_solver.cxx.
References GetVTUPointData(), and NULL.
Referenced by main().
int PostSolver::ExportFlowSolverFileFormat (int lstep, int newstepnumber, bool RequestedNewSn, bool RequestedDisplacements, bool RequestedWallprops, bool RequestedTimeDeriv, double * qglobal, double * aglobal, double * dglobal, double * wpglobal, const char * outdir)
Definition at line 425 of file post_solver.cxx.
References closefile_(), CV_ERROR, CV_OK, CVSOLVER_IO_OK, irstin, lstep, one, openfile_(), writedatablock_(), writeheader_(), and writestring_().
Referenced by main().
int PostSolver::ExportYBar (int stepnumber, int numy, double * yglobal, const char * outdir)
Definition at line 541 of file post_solver.cxx.
References closefile_(), CV_ERROR, CV_OK, CVSOLVER_IO_OK, irstin, openfile_(), writedatablock_(), writeheader_(), and writestring_().
Referenced by main().
int* PostSolver::GetConnectivityPtr () inline
Definition at line 103 of file post_solver.cxx.
Referenced by main().
double* PostSolver::GetCoordinatePtr () inline
Definition at line 102 of file post_solver.cxx.
Referenced by main().
int PostSolver::GetNumberOfElements () inline
Definition at line 98 of file post_solver.cxx.
Referenced by main().
int PostSolver::GetNumberOfNodalCoordinates () inline
Definition at line 97 of file post_solver.cxx.
Referenced by main().
int PostSolver::GetNumberOfProcessorsUsed () inline
Definition at line 100 of file post_solver.cxx.
Referenced by main().
int PostSolver::GetNumberOfSolutionVariables () inline
Definition at line 99 of file post_solver.cxx.
Referenced by main().
double* PostSolver::GetWallProperties () inline
Definition at line 104 of file post_solver.cxx.
Referenced by main().
int PostSolver::ParseRestartFile (int stepNumber, const char * field, int * numval, double ** myglobal)
Definition at line 598 of file post_solver.cxx.
References closefile_(), CV_ERROR, CV_OK, CVSOLVER_IO_OK, filename, irstin, lstep, NULL, openfile_(), readdatablock_(), and readheader_().
Referenced by main().
int PostSolver::QueryNumberOfProcessors ()
Definition at line 232 of file post_solver.cxx.
References closefile_(), CV_ERROR, CV_OK, CVSOLVER_IO_OK, filename, igeom, openfile_(), and readheader_().
Referenced by main().
int PostSolver::QueryNumberOfSolutionVariables (int stepNumber)
Definition at line 209 of file post_solver.cxx.
References closefile_(), CV_ERROR, CV_OK, CVSOLVER_IO_OK, filename, irstin, openfile_(), and readheader_().
Referenced by main().
int PostSolver::ReadConnectivity ()
Definition at line 257 of file post_solver.cxx.
References closefile_(), CV_ERROR, CV_OK, CVSOLVER_IO_OK, filename, igeom, nelblk, nen, nenl, nshl, NULL, numel, openfile_(), readdatablock_(), and readheader_().
Referenced by main().
int PostSolver::SetInputDirectory (const char * indir)
Definition at line 201 of file post_solver.cxx.
References CV_OK.
Referenced by main().
int PostSolver::SetInputFileType (const char * iotype)
Definition at line 195 of file post_solver.cxx.
References CV_OK.
Referenced by main().
Member Data Documentation
int* PostSolver::ien_ private
Definition at line 129 of file post_solver.cxx.
char PostSolver::indir_[255] private
Definition at line 135 of file post_solver.cxx.
int PostSolver::ione_ private
Definition at line 125 of file post_solver.cxx.
char PostSolver::iotype_[80] private
Definition at line 134 of file post_solver.cxx.
int PostSolver::iseven_ private
Definition at line 125 of file post_solver.cxx.
int PostSolver::ithree_ private
Definition at line 125 of file post_solver.cxx.
int PostSolver::itwo_ private
Definition at line 125 of file post_solver.cxx.
int PostSolver::maxnshg_ private
Definition at line 141 of file post_solver.cxx.
int** PostSolver::ncorpd2d_ private
Definition at line 130 of file post_solver.cxx.
int PostSolver::neltot_ private
Definition at line 140 of file post_solver.cxx.
int PostSolver::nsd_ private
Definition at line 142 of file post_solver.cxx.
int PostSolver::nshgtot_ private
Definition at line 139 of file post_solver.cxx.
int PostSolver::numprocs_ private
Definition at line 138 of file post_solver.cxx.
int PostSolver::numvar_ private
Definition at line 137 of file post_solver.cxx.
double* PostSolver::wpglobal_ private
Definition at line 132 of file post_solver.cxx.
double* PostSolver::wplocal_ private
Definition at line 131 of file post_solver.cxx.
double* PostSolver::xglobal_ private
Definition at line 128 of file post_solver.cxx.
double* PostSolver::xlocal_ private
Definition at line 127 of file post_solver.cxx.
The documentation for this class was generated from the following file:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PostSolver/post_solver.cxx