simvascular: cvBaseTimer Class Reference
cvBaseTimer Class Reference
#include <cvTimer.h>
Public Member Functions
double seconds () const
double granularity ()
void reset ()
Static Public Attributes
static int calculateGranularityOnConstructor = 0
Protected Member Functions
virtual cvTimeInBaseTimer currentTime () const
virtual double getGranularity ()
Protected Attributes
cvTimeInBaseTimer savedTime_
double granularity_
Detailed Description
Definition at line 70 of file cvTimer.h.
Member Function Documentation
cvTimeInBaseTimer cvBaseTimer::currentTime () const protected virtual
Reimplemented in cvWallClockTimer, and cvCPUTimer.
Definition at line 79 of file cvTimer.cxx.
Referenced by reset(), and seconds().
double cvBaseTimer::getGranularity () protected virtual
Reimplemented in cvWallClockTimer, and cvCPUTimer.
Definition at line 87 of file cvTimer.cxx.
Referenced by granularity().
double cvBaseTimer::granularity ()
Definition at line 67 of file cvTimer.cxx.
References getGranularity().
Referenced by cvLevelSet::GetTimerGranularity().
void cvBaseTimer::reset ()
Definition at line 73 of file cvTimer.cxx.
References currentTime(), and savedTime_.
Referenced by cvLevelSet::EvolveOneTimeStep(), cvLevelSet::ExtractActiveNodes(), cvLevelSet::ExtractCurvature(), cvLevelSet::ExtractFront(), cvLevelSet::ExtractPhi(), cvLevelSet::ExtractVectors(), cvLevelSet::Init(), and cvLevelSet::RebuildPhi().
double cvBaseTimer::seconds () const
Definition at line 60 of file cvTimer.cxx.
References currentTime(), and savedTime_.
Referenced by cvLevelSet::EvolveOneTimeStep(), cvLevelSet::ExtractActiveNodes(), cvLevelSet::ExtractCurvature(), cvLevelSet::ExtractFront(), cvLevelSet::ExtractPhi(), cvLevelSet::ExtractVectors(), cvLevelSet::Init(), and cvLevelSet::RebuildPhi().
Member Data Documentation
int cvBaseTimer::calculateGranularityOnConstructor = 0 static
Definition at line 76 of file cvTimer.h.
Referenced by cvCPUTimer::cvCPUTimer(), and cvWallClockTimer::cvWallClockTimer().
double cvBaseTimer::granularity_ protected
Definition at line 83 of file cvTimer.h.
Referenced by cvCPUTimer::getGranularity(), and cvWallClockTimer::getGranularity().
cvTimeInBaseTimer cvBaseTimer::savedTime_ protected
Definition at line 82 of file cvTimer.h.
Referenced by cvCPUTimer::cvCPUTimer(), cvWallClockTimer::cvWallClockTimer(), reset(), and seconds().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvTimer.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cvTimer.cxx