simvascular: cvRepository Class Reference
cvRepository Class Reference
#include <cvRepository.h>
Public Member Functions
cvRepository ()
~cvRepository ()
int Register (char *name, cvRepositoryData *obj)
int UnRegister (char *name)
int Exists (char *name)
RepositoryDataT GetType (CONST84 char *name)
cvRepositoryData * GetObject (CONST84 char *name)
int Save (char *filename)
int Load (char *filename)
int GetNumObjects ()
void InitIterator ()
char * GetNextName ()
Private Attributes
Tcl_HashTable table_
int iterValid_
Tcl_HashEntry * currEntryPtr_
Tcl_HashSearch search_
Detailed Description
Definition at line 78 of file cvRepository.h.
Constructor & Destructor Documentation
cvRepository::cvRepository ()
Definition at line 47 of file cvRepository.cxx.
References iterValid_, and table_.
cvRepository::~cvRepository ()
Definition at line 58 of file cvRepository.cxx.
References table_.
Member Function Documentation
int cvRepository::Exists (char * name)
Definition at line 149 of file cvRepository.cxx.
References NULL, and table_.
Referenced by cvMesh_GetFacePolyDataMtd(), cvMesh_GetPolyDataMtd(), cvMesh_GetUnstructuredGridMtd(), cvMesh_NewObjectCmd(), gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_expNegativeImageCmd(), gdscITK_shapeDetectionCmd(), gdscPost_calcAvgPointDataCmd(), gdscPost_calcOSICmd(), gdscPost_calcTKECmd(), gdscPost_calcWallShearCmd(), gdscPost_calcWallShearMeanCmd(), gdscPost_calcWallShearPulseCmd(), gdscPost_readVisMeshCmd(), gdscPost_readVisResCmd(), Geom_AddPointDataCmd(), Geom_AlignProfileCmd(), Geom_CopyCmd(), Geom_DisorientProfileCmd(), Geom_DividePointDataCmd(), Geom_GetClosedLineRegionCmd(), Geom_IntersectCmd(), Geom_MakePolysConsistentCmd(), Geom_MergePtsCmd(), Geom_MultiplyPointDataCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_ProjectCmd(), Geom_ReduceCmd(), Geom_ReorderPgnCmd(), Geom_ReplacePointDataCmd(), Geom_ReverseAllCellsCmd(), Geom_RmSmallPolysCmd(), Geom_sampleLoopCmd(), Geom_ScaleAvgCmd(), Geom_SubtractCmd(), Geom_SubtractPointDataCmd(), Geom_TranslateCmd(), Geom_UnionCmd(), Geom_Warp3dPtsCmd(), Image_CalcCorrectionEqnAutoCmd(), Image_CreateDistanceMapCmd(), Image_DecodeCmd(), Image_FindPathCmd(), Image_ThresholdCmd(), LsetCore_GetBoundaryDataMtd(), LsetCore_SaveGridMtd(), LsetVImage_GetImageObjMtd(), Repos_DeleteCmd(), Repos_ExistsCmd(), Repos_ImportVtkImgCmd(), Repos_ImportVtkPdCmd(), Repos_ImportVtkSpCmd(), Repos_ImportVtkUnstructuredGridCmd(), Repos_ReadVtkPolyDataCmd(), Repos_TypeCmd(), Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_CopyCmd(), Solid_CylinderCmd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_GetAxialIsoparametricCurveMtd(), Solid_GetDiscontinuitiesMtd(), Solid_GetFacePolyDataMtd(), Solid_GetPolyDataMtd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_SphereCmd(), Solid_TorusCmd(), and Solid_TruncatedConeCmd().
char * cvRepository::GetNextName ()
Definition at line 270 of file cvRepository.cxx.
References currEntryPtr_, NULL, search_, and table_.
Referenced by Repos_ListCmd().
int cvRepository::GetNumObjects ()
Definition at line 238 of file cvRepository.cxx.
References table_.
Referenced by Load().
cvRepositoryData * cvRepository::GetObject (CONST84 char * name)
Definition at line 183 of file cvRepository.cxx.
References NULL, and table_.
Referenced by cvMesh_SetVtkPolyDataMtd(), gdscITK_expNegativeImageCmd(), gdscITK_FastMarchCmd(), gdscITK_MinMaxCurvSmoothCmd(), gdscITK_ReadRegionOfInterestCmd(), gdscITK_shapeDetectionCmd(), gdscITK_SigMapCmd(), gdscITK_TLSF_Cmd(), gdscPost_calcAvgPointDataCmd(), gdscPost_calcOSICmd(), gdscPost_calcTKECmd(), gdscPost_calcWallShearCmd(), gdscPost_calcWallShearMeanCmd(), gdscPost_calcWallShearPulseCmd(), gdscPost_readVisResCmd(), Geom_2dWindingNumCmd(), Geom_AddPointDataCmd(), Geom_AlignProfileCmd(), Geom_AvgPtCmd(), Geom_BBoxCmd(), Geom_CheckSurfaceCmd(), Geom_ClassifyCmd(), Geom_CopyCmd(), Geom_DisorientProfileCmd(), Geom_DividePointDataCmd(), Geom_FindDistanceCmd(), Geom_GetClosedLineRegionCmd(), Geom_GetOrderedPtsCmd(), Geom_GetPolyCentroidCmd(), Geom_IntegrateEnergyCmd(), Geom_IntegrateScalarSurfCmd(), Geom_IntegrateScalarThreshCmd(), Geom_IntegrateSurface2Cmd(), Geom_IntegrateSurfaceCmd(), Geom_InterpolateScalarCmd(), Geom_InterpolateVectorCmd(), Geom_IntersectCmd(), Geom_IntersectWithLineCmd(), Geom_MakePolysConsistentCmd(), Geom_MergePtsCmd(), Geom_MultiplyPointDataCmd(), Geom_NumClosedLineRegionsCmd(), Geom_NumPtsCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_PolygonNormCmd(), Geom_PolysClosedCmd(), Geom_PrintSmallPolysCmd(), Geom_PrintTriStatsCmd(), Geom_ProjectCmd(), Geom_PtInPolyCmd(), Geom_ReduceCmd(), Geom_ReorderPgnCmd(), Geom_ReplacePointDataCmd(), Geom_ReverseAllCellsCmd(), Geom_RmSmallPolysCmd(), Geom_sampleLoopCmd(), Geom_ScaleAvgCmd(), Geom_SplinePtsToPathPlanCmd(), Geom_SubtractCmd(), Geom_SubtractPointDataCmd(), Geom_SurfAreaCmd(), Geom_TranslateCmd(), Geom_UnionCmd(), Geom_Warp3dPtsCmd(), Geom_WriteLinesCmd(), Geom_WriteOrderedPtsCmd(), GetType(), Image_CalcCorrectionEqnAutoCmd(), Image_CalcCorrectionEqnCmd(), Image_ComputeStructuredCoordCmd(), Image_CreateDistanceMapCmd(), Image_DecodeCmd(), Image_FindPathCmd(), Image_MaskInPlaceCmd(), Image_ThresholdCmd(), itkls2d_SetInputsMtd(), itkls3d_SetInputsMtd(), itkutils_FractEdgeProximity3DCmd(), itkutils_GradientMagnitudeGaussianCmd(), itkutils_PdToImgCmd(), itkutils_PdToVolCmd(), itkutils_WriteImageCmd(), LsetCore_SetImageSeedMtd(), LsetCore_SetPdSeedMtd(), LsetCore_SetSolidSeedMtd(), LsetVImage_SetImageObjMtd(), Repos_ClearLabelCmd(), Repos_ExportToVtkCmd(), Repos_GetLabelCmd(), Repos_GetLabelKeysCmd(), Repos_SetLabelCmd(), Repos_WriteVtkPolyDataCmd(), Repos_WriteVtkStructuredPointsCmd(), Repos_WriteVtkUnstructuredGridCmd(), Solid_CapSurfToSolidCmd(), Solid_CopyCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_IntersectCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_SetVtkPolyDataMtd(), Solid_SubtractCmd(), and Solid_UnionCmd().
RepositoryDataT cvRepository::GetType (CONST84 char * name)
Definition at line 166 of file cvRepository.cxx.
References GetObject(), cvRepositoryData::GetType(), NULL, and OBJ_NOT_FOUND_T.
Referenced by cvMesh_SetVtkPolyDataMtd(), itkls2d_SetInputsMtd(), itkls3d_SetInputsMtd(), Repos_DeleteCmd(), Repos_TypeCmd(), Repos_WriteVtkPolyDataCmd(), Repos_WriteVtkStructuredPointsCmd(), Repos_WriteVtkUnstructuredGridCmd(), Solid_CopyCmd(), Solid_IntersectCmd(), Solid_SetVtkPolyDataMtd(), Solid_SubtractCmd(), and Solid_UnionCmd().
void cvRepository::InitIterator ()
Definition at line 259 of file cvRepository.cxx.
References currEntryPtr_, iterValid_, search_, and table_.
Referenced by Repos_ListCmd().
int cvRepository::Load (char * filename)
Definition at line 219 of file cvRepository.cxx.
References GetNumObjects().
Referenced by Repos_LoadCmd().
int cvRepository::Register (char * name, cvRepositoryData * obj)
Definition at line 101 of file cvRepository.cxx.
References iterValid_, cvRepositoryData::SetName(), and table_.
Referenced by cvMesh_GetFacePolyDataMtd(), cvMesh_GetPolyDataMtd(), cvMesh_GetUnstructuredGridMtd(), cvMesh_NewObjectCmd(), FMMHelper(), gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_expNegativeImageCmd(), gdscITK_shapeDetectionCmd(), gdscPost_calcAvgPointDataCmd(), gdscPost_calcOSICmd(), gdscPost_calcTKECmd(), gdscPost_calcWallShearCmd(), gdscPost_calcWallShearMeanCmd(), gdscPost_calcWallShearPulseCmd(), gdscPost_readVisMeshCmd(), gdscPost_readVisResCmd(), Geom_AddPointDataCmd(), Geom_AlignProfileCmd(), Geom_CopyCmd(), Geom_DisorientProfileCmd(), Geom_DividePointDataCmd(), Geom_GetClosedLineRegionCmd(), Geom_IntersectCmd(), Geom_MakePolysConsistentCmd(), Geom_MergePtsCmd(), Geom_MultiplyPointDataCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_ProjectCmd(), Geom_ReduceCmd(), Geom_ReorderPgnCmd(), Geom_ReplacePointDataCmd(), Geom_ReverseAllCellsCmd(), Geom_RmSmallPolysCmd(), Geom_sampleLoopCmd(), Geom_ScaleAvgCmd(), Geom_SubtractCmd(), Geom_SubtractPointDataCmd(), Geom_TranslateCmd(), Geom_UnionCmd(), Geom_Warp3dPtsCmd(), Image_CalcCorrectionEqnAutoCmd(), Image_CreateDistanceMapCmd(), Image_DecodeCmd(), Image_FindPathCmd(), Image_ThresholdCmd(), itkutils_FractEdgeProximity3DCmd(), itkutils_GenerateCircleCmd(), itkutils_GradientMagnitudeGaussianCmd(), itkutils_PdToImgCmd(), itkutils_PdToVolCmd(), LsetCore_ExtractActiveNodesMtd(), LsetCore_ExtractCoveredNodesMtd(), LsetCore_ExtractCurvatureMtd(), LsetCore_ExtractForceMinVNodesMtd(), LsetCore_ExtractFrontMtd(), LsetCore_ExtractMineNodesMtd(), LsetCore_ExtractPhiMtd(), LsetCore_ExtractProjectionSetsMtd(), LsetCore_ExtractUncoveredNodesMtd(), LsetCore_ExtractVelMtd(), LsetCore_GetBoundaryDataMtd(), LsetCore_SaveGridMtd(), LsetVImage_GetImageObjMtd(), ReadRegionHelper(), Repos_ImportVtkImgCmd(), Repos_ImportVtkPdCmd(), Repos_ImportVtkSpCmd(), Repos_ImportVtkUnstructuredGridCmd(), Repos_ReadVtkPolyDataCmd(), SigMapHelper(), SmoothHelper(), Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_CopyCmd(), Solid_CylinderCmd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_GetAxialIsoparametricCurveMtd(), Solid_GetDiscontinuitiesMtd(), Solid_GetFacePolyDataMtd(), Solid_GetPolyDataMtd(), Solid_IntersectCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_SphereCmd(), Solid_SubtractCmd(), Solid_TorusCmd(), Solid_TruncatedConeCmd(), Solid_UnionCmd(), and TLSFHelper().
int cvRepository::Save (char * filename)
Definition at line 202 of file cvRepository.cxx.
Referenced by Repos_SaveCmd().
int cvRepository::UnRegister (char * name)
Definition at line 124 of file cvRepository.cxx.
References iterValid_, NULL, cvRepositoryData::NumLocks(), and table_.
Referenced by DeletegdscMesh(), DeleteSolid(), FMMHelper(), ReadRegionHelper(), Repos_DeleteCmd(), SigMapHelper(), SmoothHelper(), and TLSFHelper().
Member Data Documentation
Tcl_HashEntry* cvRepository::currEntryPtr_ private
Definition at line 101 of file cvRepository.h.
Referenced by GetNextName(), and InitIterator().
int cvRepository::iterValid_ private
Definition at line 100 of file cvRepository.h.
Referenced by cvRepository(), InitIterator(), Register(), and UnRegister().
Tcl_HashSearch cvRepository::search_ private
Definition at line 102 of file cvRepository.h.
Referenced by GetNextName(), and InitIterator().
Tcl_HashTable cvRepository::table_ private
Definition at line 99 of file cvRepository.h.
Referenced by cvRepository(), Exists(), GetNextName(), GetNumObjects(), GetObject(), InitIterator(), Register(), UnRegister(), and ~cvRepository().
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvRepository.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvRepository.cxx