simvascular: vtkSurfaceVectors Class Reference
vtkSurfaceVectors Class Reference
#include <vtkSurfaceVectors.h>
Public Types
enum ConstraintMode { Parallel = 0, Perpendicular, PerpendicularScale }
Public Member Functions
vtkTypeMacro (vtkSurfaceVectors, vtkDataSetAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent)
vtkSetMacro (ConstraintMode, int)
vtkGetMacro (ConstraintMode, int)
void SetConstraintModeToParallel ()
void SetConstraintModeToPerpendicular ()
void SetConstraintModeToPerpendicularScale ()
Static Public Member Functions
static vtkSurfaceVectors * New ()
Protected Member Functions
vtkSurfaceVectors ()
~vtkSurfaceVectors ()
virtual int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
virtual int RequestUpdateExtent (vtkInformation *, vtkInformationVector **, vtkInformationVector *)
Protected Attributes
int ConstraintMode
Private Member Functions
vtkSurfaceVectors (const vtkSurfaceVectors &)
void operator= (const vtkSurfaceVectors &)
Detailed Description
Definition at line 29 of file vtkSurfaceVectors.h.
Member Enumeration Documentation
enum vtkSurfaceVectors::ConstraintMode
Enumerator
Parallel
Perpendicular
PerpendicularScale
Definition at line 37 of file vtkSurfaceVectors.h.
Constructor & Destructor Documentation
vtkSurfaceVectors::vtkSurfaceVectors () protected
Definition at line 34 of file vtkSurfaceVectors.cxx.
References Parallel.
vtkSurfaceVectors::~vtkSurfaceVectors () protected
Definition at line 44 of file vtkSurfaceVectors.cxx.
vtkSurfaceVectors::vtkSurfaceVectors (const vtkSurfaceVectors &) private
Member Function Documentation
static vtkSurfaceVectors* vtkSurfaceVectors::New () static
Referenced by vtkIntegrateFlowThroughSurface::GenerateSurfaceVectors().
void vtkSurfaceVectors::operator= (const vtkSurfaceVectors &) private
void vtkSurfaceVectors::PrintSelf (ostream & os, vtkIndent indent)
Definition at line 223 of file vtkSurfaceVectors.cxx.
References Parallel, Perpendicular, and PerpendicularScale.
int vtkSurfaceVectors::RequestData (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected virtual
Definition at line 68 of file vtkSurfaceVectors.cxx.
References Cross(), Dot(), input(), Parallel, Perpendicular, and PerpendicularScale.
int vtkSurfaceVectors::RequestUpdateExtent (vtkInformation * , vtkInformationVector ** , vtkInformationVector *) protected virtual
Definition at line 49 of file vtkSurfaceVectors.cxx.
void vtkSurfaceVectors::SetConstraintModeToParallel () inline
Definition at line 50 of file vtkSurfaceVectors.h.
References Parallel.
void vtkSurfaceVectors::SetConstraintModeToPerpendicular () inline
Definition at line 52 of file vtkSurfaceVectors.h.
References Perpendicular.
void vtkSurfaceVectors::SetConstraintModeToPerpendicularScale () inline
Definition at line 54 of file vtkSurfaceVectors.h.
References PerpendicularScale.
Referenced by vtkIntegrateFlowThroughSurface::GenerateSurfaceVectors().
vtkSurfaceVectors::vtkGetMacro (ConstraintMode , int)
vtkSurfaceVectors::vtkSetMacro (ConstraintMode , int)
vtkSurfaceVectors::vtkTypeMacro (vtkSurfaceVectors , vtkDataSetAlgorithm)
Member Data Documentation
int vtkSurfaceVectors::ConstraintMode protected
Definition at line 69 of file vtkSurfaceVectors.h.
The documentation for this class was generated from the following files:
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkSurfaceVectors.h
/Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/vtkSurfaceVectors.cxx