simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/ThirdParty/zlib/simvascular_zlib/crc32.c File Reference
crc32.c File Reference
#include "zutil.h"
#include "crc32.h"
Macros
#define local static
#define TBLS 1
#define DO1 crc = crc_table[0][((int)crc ^ (*buf++)) & 0xff] ^ (crc >> 8)
#define DO8 DO1; DO1; DO1; DO1; DO1; DO1; DO1; DO1
#define GF2_DIM 32 /* dimension of GF(2) vectors (length of CRC) */
Functions
static unsigned long gf2_matrix_times ()
static void gf2_matrix_square ()
unsigned long * cv_zlib_get_crc_table ()
unsigned long cv_zlib_crc32 (unsigned long crc, unsigned char *buf, unsigned len)
static unsigned long gf2_matrix_times (unsigned long *mat, unsigned long vec)
static void gf2_matrix_square (unsigned long *square, unsigned long *mat)
uLong cv_zlib_crc32_combine (uLong crc1, uLong crc2, long len2)
Macro Definition Documentation
#define DO1 crc = crc_table[0][((int)crc ^ (*buf++)) & 0xff] ^ (crc >> 8)
Definition at line 215 of file crc32.c.
Referenced by cv_zlib_crc32().
#define DO8 DO1; DO1; DO1; DO1; DO1; DO1; DO1; DO1
Definition at line 216 of file crc32.c.
Referenced by cv_zlib_crc32().
#define GF2_DIM 32 /* dimension of GF(2) vectors (length of CRC) */
Definition at line 339 of file crc32.c.
Referenced by cv_zlib_crc32_combine(), and gf2_matrix_square().
#define local static
Definition at line 31 of file crc32.c.
Referenced by PsdUtils_Extrude().
#define TBLS 1
Definition at line 64 of file crc32.c.
Function Documentation
unsigned long cv_zlib_crc32 (unsigned long crc, unsigned char * buf, unsigned len)
Definition at line 219 of file crc32.c.
References DO1, DO8, and Z_NULL.
uLong cv_zlib_crc32_combine (uLong crc1, uLong crc2, long len2)
Definition at line 370 of file crc32.c.
References GF2_DIM, gf2_matrix_square(), gf2_matrix_times(), and L.
unsigned long* cv_zlib_get_crc_table ()
Definition at line 205 of file crc32.c.
References crc_table, and FAR.
static void gf2_matrix_square () static
Referenced by cv_zlib_crc32_combine().
static void gf2_matrix_square (unsigned long * square, unsigned long * mat) static
Definition at line 359 of file crc32.c.
References GF2_DIM, and gf2_matrix_times().
static unsigned long gf2_matrix_times () static
Referenced by cv_zlib_crc32_combine(), and gf2_matrix_square().
static unsigned long gf2_matrix_times (unsigned long * mat, unsigned long vec) static
Definition at line 342 of file crc32.c.