simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cv_repos_init.cxx File Reference
cv_repos_init.cxx File Reference
#include "SimVascular.h"
#include "cv_repos_init.h"
#include "cvRepository.h"
#include "cvPolyData.h"
#include "cvStrPts.h"
#include "cvUnstructuredGrid.h"
#include "cv_arg.h"
#include "cvVTK.h"
#include "vtkTclUtil.h"
#include "cv_globals.h"
Functions
int Repos_ListCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_ExistsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_DeleteCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_TypeCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_ImportVtkPdCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_ImportVtkSpCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_ImportVtkImgCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_ImportVtkUnstructuredGridCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_ExportToVtkCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_SaveCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_LoadCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_WriteVtkPolyDataCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_ReadVtkPolyDataCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_WriteVtkStructuredPointsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_WriteVtkUnstructuredGridCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Repos_GetLabelKeysCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Repos_GetLabelCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Repos_SetLabelCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Repos_ClearLabelCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Repos_Init (Tcl_Interp *interp)
Function Documentation
int Repos_ClearLabelCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1248 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepositoryData::ClearLabel(), cvRepository::GetObject(), gRepository, cvRepositoryData::IsLabelPresent(), NULL, REQUIRED, and STRING_Type.
Referenced by Repos_Init().
int Repos_DeleteCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 251 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepository::GetType(), gRepository, MESH_T, NULL, REQUIRED, SOLID_MODEL_T, STRING_Type, and cvRepository::UnRegister().
Referenced by Repos_Init().
int Repos_ExistsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 214 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), gRepository, NULL, REQUIRED, and STRING_Type.
Referenced by Repos_Init().
int Repos_ExportToVtkCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 408 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, STRUCTURED_PTS_T, TEMPORALDATASET_T, and UNSTRUCTURED_GRID_T.
Referenced by Repos_Init().
int Repos_GetLabelCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1151 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepositoryData::GetLabel(), cvRepository::GetObject(), gRepository, NULL, REQUIRED, and STRING_Type.
Referenced by Repos_Init().
int Repos_GetLabelKeysCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1106 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepositoryData::GetLabelKeys(), cvRepository::GetObject(), gRepository, NULL, REQUIRED, and STRING_Type.
Referenced by Repos_Init().
int Repos_ImportVtkImgCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 619 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, cvRepositoryData::SetName(), and STRING_Type.
Referenced by Repos_Init().
int Repos_ImportVtkPdCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 347 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, cvRepositoryData::SetName(), and STRING_Type.
Referenced by Repos_Init().
int Repos_ImportVtkSpCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 495 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, cvRepositoryData::SetName(), and STRING_Type.
Referenced by Repos_Init().
int Repos_ImportVtkUnstructuredGridCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 557 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, cvRepositoryData::SetName(), and STRING_Type.
Referenced by Repos_Init().
int Repos_Init (Tcl_Interp * interp)
Definition at line 133 of file cv_repos_init.cxx.
References gRepository, NULL, Repos_ClearLabelCmd(), Repos_DeleteCmd(), Repos_ExistsCmd(), Repos_ExportToVtkCmd(), Repos_GetLabelCmd(), Repos_GetLabelKeysCmd(), Repos_ImportVtkImgCmd(), Repos_ImportVtkPdCmd(), Repos_ImportVtkSpCmd(), Repos_ImportVtkUnstructuredGridCmd(), Repos_ListCmd(), Repos_LoadCmd(), Repos_ReadVtkPolyDataCmd(), Repos_SaveCmd(), Repos_SetLabelCmd(), Repos_TypeCmd(), Repos_WriteVtkPolyDataCmd(), Repos_WriteVtkStructuredPointsCmd(), and Repos_WriteVtkUnstructuredGridCmd().
Referenced by SimVascular_Init().
int Repos_ListCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 193 of file cv_repos_init.cxx.
References cvRepository::GetNextName(), gRepository, and cvRepository::InitIterator().
Referenced by Repos_Init().
int Repos_LoadCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 764 of file cv_repos_init.cxx.
References filename, gRepository, and cvRepository::Load().
Referenced by Repos_Init().
int Repos_ReadVtkPolyDataCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 875 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by Repos_Init().
int Repos_SaveCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 735 of file cv_repos_init.cxx.
References filename, gRepository, and cvRepository::Save().
Referenced by Repos_Init().
int Repos_SetLabelCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1197 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), gRepository, cvRepositoryData::IsLabelPresent(), NULL, REQUIRED, cvRepositoryData::SetLabel(), and STRING_Type.
Referenced by Repos_Init().
int Repos_TypeCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 304 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepository::GetType(), gRepository, NULL, RepositoryDataT_EnumToStr(), REQUIRED, and STRING_Type.
Referenced by Repos_Init().
int Repos_WriteVtkPolyDataCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 801 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepository::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, and STRING_Type.
Referenced by Repos_Init().
int Repos_WriteVtkStructuredPointsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 958 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepository::GetType(), gRepository, NULL, REQUIRED, STRING_Type, and STRUCTURED_PTS_T.
Referenced by Repos_Init().
int Repos_WriteVtkUnstructuredGridCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1033 of file cv_repos_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepository::GetType(), gRepository, NULL, REQUIRED, STRING_Type, and UNSTRUCTURED_GRID_T.
Referenced by Repos_Init().