simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Image/cv_calc_correction_eqn.cxx File Reference
cv_calc_correction_eqn.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include <math.h>
#include "cvVTK.h"
#include "cvMath.h"
#include "cvRepository.h"
#include "cvRepositoryData.h"
#include "cvPolyData.h"
#include "cv_sys_geom.h"
#include "cv_calc_correction_eqn.h"
Functions
int img_calcCorrectionEqn (int numRegions, vtkPolyData **listPd, int numImages, vtkStructuredPoints **listImg, int order, double results[])
int img_calcCorrectionEqnAuto (int numRegions, vtkPolyData **listPd, int numImages, vtkStructuredPoints **listImg, int order, double sdev_limit_factor, double results[], vtkStructuredPoints **maskImg)
Function Documentation
int img_calcCorrectionEqn (int numRegions, vtkPolyData ** listPd, int numImages, vtkStructuredPoints ** listImg, int order, double results[])
Definition at line 44 of file cv_calc_correction_eqn.cxx.
References cvMath::createArray(), CV_ERROR, CV_OK, cvMath::deleteArray(), cvMath::fitLeastSquares(), and sys_geom_PtInPoly().
Referenced by Image_CalcCorrectionEqnCmd().
int img_calcCorrectionEqnAuto (int numRegions, vtkPolyData ** listPd, int numImages, vtkStructuredPoints ** listImg, int order, double sdev_limit_factor, double results[], vtkStructuredPoints ** maskImg)
Definition at line 282 of file cv_calc_correction_eqn.cxx.
References cvMath::createArray(), CV_ERROR, CV_OK, cvMath::deleteArray(), cvMath::fitLeastSquares(), and sys_geom_PtInPoly().
Referenced by Image_CalcCorrectionEqnAutoCmd().