simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Image/cv_read_header.h File Reference
cv_read_header.h File Reference
#include "SimVascular.h"
Functions
int mrRead_Header (char *filename, float *vdims_x, float *vdims_y, int *dim_x, int *dim_y, int *file_hdr_size, float ul[], float ur[], float br[], int *rtnvenc, float *rtnvencscale, int *rtnvas_collapse, float *rtnuser2, float *rtnuser5, float *rtnuser6, float *rtnuser7, float *rtnuser8, float *rtnuser9, float *rtnuser12, float *rtnuser13, float *rtnuser14, char *patid, char *patname, char *psdname, int *magWeightFlag, int *examNumber, float nrm_RAS[], int *acquisitionTime, int *heart_rate, int *im_no, int *im_seno)
Function Documentation
int mrRead_Header (char * filename, float * vdims_x, float * vdims_y, int * dim_x, int * dim_y, int * file_hdr_size, float ul[], float ur[], float br[], int * rtnvenc, float * rtnvencscale, int * rtnvas_collapse, float * rtnuser2, float * rtnuser5, float * rtnuser6, float * rtnuser7, float * rtnuser8, float * rtnuser9, float * rtnuser12, float * rtnuser13, float * rtnuser14, char * patid, char * patname, char * psdname, int * magWeightFlag, int * examNumber, float nrm_RAS[], int * acquisitionTime, int * heart_rate, int * im_no, int * im_seno)
Definition at line 145 of file cv_read_header.cxx.
References CV_ERROR, CV_OK, EX_NO, EX_PATID, EX_PATNAME, EX_TYP, IM_ACTUAL_DT, IM_BRHC_A, IM_BRHC_R, IM_BRHC_S, IM_DIM_X, IM_DIM_Y, IM_HRTRATE, IM_IMATRIX_X, IM_IMATRIX_Y, IM_NO, IM_NORM_A, IM_NORM_R, IM_NORM_S, IM_PIXSIZE_X, IM_PIXSIZE_Y, IM_PSDNAME, IM_SENO, IM_SLTHICK, IM_TLHC_A, IM_TLHC_R, IM_TLHC_S, IM_TRHC_A, IM_TRHC_R, IM_TRHC_S, IM_USER12, IM_USER13, IM_USER14, IM_USER2, IM_USER5, IM_USER6, IM_USER7, IM_USER8, IM_USER9, IM_VAS_COLLAPSE, IM_VASFLAGS, IM_VENC, IM_VENCSCALE, mrRead_char(), mrRead_float(), mrRead_int(), mrRead_short_int(), mrRead_unsigned_short_int(), NULL, OFFSET_EXAM, OFFSET_HEADER_LEN, OFFSET_IMAGE, OFFSET_IMAGE_HEIGHT, OFFSET_IMAGE_WIDTH, OFFSET_MAGIC_NUM, OFFSET_SERIES, and OFFSET_SUITE.
Referenced by Image_ReadHeaderCmd().