simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/cv_sys_geom.cxx File Reference
cv_sys_geom.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include <assert.h>
#include <math.h>
#include "cv_sys_geom.h"
#include "cvVTK.h"
#include "cv_vtk_utils.h"
#include "cv_misc_utils.h"
#include "cv_ggems.h"
#include "cvMath.h"
#include "cvSolidModel.h"
#include "vtkSurfaceBooleanOperations.h"
#include "vtkSmartPointer.h"
#include "vtkSortDataArray.h"
#include "vtkPolygon.h"
#include "vtkBooleanOperationPolyDataFilter2.h"
#include "vtkIntersectionPolyDataFilter2.h"
#include "cv_polydatasolid_utils.h"
Macros
#define vtkNew(type, name) vtkSmartPointer<type> name = vtkSmartPointer<type>::New()
Functions
cvPolyData * sys_geom_DeepCopy (cvPolyData *src)
cvPolyData * sys_geom_MergePts (cvPolyData *src)
cvPolyData * sys_geom_MergePts_tol (cvPolyData *src, double tol)
int sys_geom_NumClosedLineRegions (cvPolyData *src, int *num)
int sys_geom_GetClosedLineRegion (cvPolyData *src, int id, cvPolyData **dst)
int sys_geom_Pick (cvPolyData *src, double pos[], cvPolyData **dst)
int sys_geom_Reduce (cvPolyData *src, double tol, cvPolyData **dst)
int sys_geom_MakePolysConsistent (cvPolyData *src, cvPolyData **dst)
int sys_geom_union (cvPolyData *srcA, cvPolyData *srcB, cvPolyData **dst)
int sys_geom_intersect (cvPolyData *srcA, cvPolyData *srcB, cvPolyData **dst)
int sys_geom_subtract (cvPolyData *srcA, cvPolyData *srcB, cvPolyData **dst)
int sys_geom_checksurface (cvPolyData *src, int stats[])
int sys_geom_ReverseAllCells (cvPolyData *src, cvPolyData **dst)
int sys_geom_GetOrderedPts (cvPolyData *src, double **ord_pts, int *num)
int sys_geom_Get2DPgon (cvPolyData *src, double **pgon, int *num)
int sys_geom_ReversePtList (int num, double ptsIn[], double *ptsOut[])
int sys_geom_WriteOrderedPts (cvPolyData *src, char *fn)
int sys_geom_WriteLines (cvPolyData *src, char *fn)
int sys_geom_PolysClosed (cvPolyData *src, int *closed)
int sys_geom_SurfArea (cvPolyData *src, double *area)
int sys_geom_getPolyCentroid (cvPolyData *src, double centroid[])
int sys_geom_PrintTriStats (cvPolyData *surf)
int sys_geom_PrintSmallPolys (cvPolyData *src, double sideTol)
int sys_geom_RmSmallPolys (cvPolyData *src, double sideTol, cvPolyData **dst)
int sys_geom_BBox (cvPolyData *obj, double bbox[])
int sys_geom_OrientProfile (cvPolyData *src, double ppt[], double ptan[], double xhat[], cvPolyData **dst)
int sys_geom_DisorientProfile (cvPolyData *src, double ppt[], double ptan[], double xhat[], cvPolyData **dst)
int sys_geom_Translate (cvPolyData *src, double translate[], cvPolyData **dst)
int sys_geom_ScaleAvg (cvPolyData *src, double factor, cvPolyData **dst)
cvPolyData * sys_geom_Align (cvPolyData *ref, cvPolyData *src)
cvPolyData * sys_geom_ReorderPolygon (cvPolyData *src, int startIx)
cvPolyData * sys_geom_AlignByDist (cvPolyData *ref, cvPolyData *src)
int sys_geom_Classify (cvPolyData *obj, double pt[], int *result)
int sys_geom_PtInPoly (cvPolyData *obj, double pt[], int usePrevPoly, int *result)
cvPolyData * sys_geom_sampleLoop (cvPolyData *src, int targetNumPts)
int sys_geom_2DWindingNum (cvPolyData *pgn)
int sys_geom_PolygonNormal (cvPolyData *pgn, double n[])
int sys_geom_AvgPt (cvPolyData *src, double pt[])
int sys_geom_InterpolateScalar (cvPolyData *src, double pt[], double *scalar)
int sys_geom_InterpolateVector (cvPolyData *src, double pt[], double vect[])
int sys_geom_IntersectWithLine (cvPolyData *src, double p0[], double p1[], double intersect[])
cvPolyData * sys_geom_warp3dPts (cvPolyData *src, double scale)
int sys_geom_mathPointData (cvPolyData *srcA, cvPolyData *srcB, sys_geom_math_scalar scflag, sys_geom_math_vector vflag, cvPolyData **dst)
int sys_geom_Project (cvPolyData *srcA, cvPolyData *srcB, sys_geom_math_scalar scflag, sys_geom_math_vector vflag, cvPolyData **dst)
int sys_geom_ReplacePointData (cvPolyData *srcA, cvPolyData *srcB, sys_geom_math_scalar scflag, sys_geom_math_vector vflag, cvPolyData **dst)
Variables
static double * g_sys_geom_PtInPoly_pgon = NULL
static int g_sys_geom_PtInPoly_num = 0
Macro Definition Documentation
#define vtkNew (type, name) vtkSmartPointer<type> name = vtkSmartPointer<type>::New()
Definition at line 50 of file cv_sys_geom.cxx.
Referenced by sys_geom_intersect(), sys_geom_subtract(), and sys_geom_union().
Function Documentation
int sys_geom_2DWindingNum (cvPolyData * pgn)
Definition at line 2293 of file cv_sys_geom.cxx.
References CV_OK, CV_PI, cvPolyData::GetVtkPolyData(), NormVector(), Round(), sys_geom_MergePts(), VtkUtils_GetClosedLineRegion(), VtkUtils_GetLines(), and VtkUtils_GetPoints().
Referenced by Geom_2dWindingNumCmd(), and sys_geom_Get2DPgon().
cvPolyData* sys_geom_Align (cvPolyData * ref, cvPolyData * src)
Definition at line 1727 of file cv_sys_geom.cxx.
References Cross(), CV_OK, Dot(), cvRepositoryData::GetName(), cvPolyData::GetVtkPolyData(), maximum, NormVector(), NULL, sys_geom_AvgPt(), sys_geom_GetOrderedPts(), sys_geom_PolygonNormal(), sys_geom_ReorderPolygon(), and VtkUtils_ReverseAllCells().
Referenced by Geom_AlignProfileCmd().
cvPolyData* sys_geom_AlignByDist (cvPolyData * ref, cvPolyData * src)
Definition at line 1892 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, Dot(), cvRepositoryData::GetName(), cvPolyData::GetVtkPolyData(), NULL, sys_geom_GetOrderedPts(), sys_geom_PolygonNormal(), sys_geom_ReorderPolygon(), and VtkUtils_ReverseAllCells().
Referenced by Geom_AlignProfileCmd().
int sys_geom_AvgPt (cvPolyData * src, double pt[])
Definition at line 2444 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), sys_geom_MergePts(), and VtkUtils_GetPoints().
Referenced by Geom_AvgPtCmd(), sys_geom_Align(), and sys_geom_ScaleAvg().
int sys_geom_BBox (cvPolyData * obj, double bbox[])
Definition at line 1461 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), maximum, minimum, and VtkUtils_GetPoints().
Referenced by cvLevelSetSparseGrid::BuildSeedInterface(), Geom_BBoxCmd(), and sys_geom_Get2DPgon().
int sys_geom_checksurface (cvPolyData * src, int stats[])
Definition at line 545 of file cv_sys_geom.cxx.
References vtkIntersectionPolyDataFilter2::CleanAndCheckSurface(), CV_ERROR, CV_OK, and cvPolyData::GetVtkPolyData().
Referenced by Geom_CheckSurfaceCmd().
int sys_geom_Classify (cvPolyData * obj, double pt[], int * result)
Definition at line 2015 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), ggemsgeo_solid_angle(), NULL, PI, _ggemsGeoPoint::x, _ggemsGeoPoint::y, and _ggemsGeoPoint::z.
Referenced by Geom_ClassifyCmd(), and cvLevelSetSparseGrid::InitSign_Internal().
cvPolyData* sys_geom_DeepCopy (cvPolyData * src)
Definition at line 69 of file cv_sys_geom.cxx.
References cvPolyData::GetVtkPolyData(), NULL, VtkUtils_DeepCopyCells(), and VtkUtils_DeepCopyPoints().
Referenced by Geom_CopyCmd(), cvParasolidSolidModel::MakeApproxCurveLoop(), cvParasolidSolidModel::MakeInterpCurveLoop(), sys_geom_ScaleAvg(), and sys_geom_Translate().
int sys_geom_DisorientProfile (cvPolyData * src, double ppt[], double ptan[], double xhat[], cvPolyData ** dst)
Definition at line 1550 of file cv_sys_geom.cxx.
References A, B, Cross(), CV_OK, FindMachineEpsilon(), cvPolyData::GetVtkPolyData(), misc_Det3x3(), NormVector(), S, and VtkUtils_DeepCopyCells().
Referenced by Geom_DisorientProfileCmd().
int sys_geom_Get2DPgon (cvPolyData * src, double ** pgon, int * num)
Definition at line 880 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, FindMachineEpsilon(), NULL, sys_geom_2DWindingNum(), sys_geom_BBox(), sys_geom_GetOrderedPts(), and sys_geom_ReversePtList().
Referenced by sys_geom_PtInPoly().
int sys_geom_GetClosedLineRegion (cvPolyData * src, int id, cvPolyData ** dst)
Definition at line 195 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, sys_geom_MergePts(), VtkUtils_FindClosedLineRegions(), VtkUtils_GetClosedLineRegion(), VtkUtils_GetLines(), VtkUtils_GetPoints(), and VtkUtils_MakePolyDataFromLineIds().
Referenced by Geom_GetClosedLineRegionCmd().
int sys_geom_GetOrderedPts (cvPolyData * src, double ** ord_pts, int * num)
Definition at line 707 of file cv_sys_geom.cxx.
References c, CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, sys_geom_MergePts(), VtkUtils_GetLines(), VtkUtils_GetLinkedLines(), and VtkUtils_GetPoints().
Referenced by Geom_GetOrderedPtsCmd(), cvParasolidSolidModel::MakeApproxCurveLoop(), cvParasolidSolidModel::MakeInterpCurveLoop(), PsdUtils_MakeCap(), PsdUtils_MakePoly2d(), sys_geom_Align(), sys_geom_AlignByDist(), sys_geom_Get2DPgon(), sys_geom_PolygonNormal(), sys_geom_ReorderPolygon(), sys_geom_sampleLoop(), and sys_geom_WriteOrderedPts().
int sys_geom_getPolyCentroid (cvPolyData * src, double centroid[])
Definition at line 1197 of file cv_sys_geom.cxx.
References cgeom_GetPolyCentroid(), CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), VtkUtils_GetAllPolys(), and VtkUtils_GetPointsFloat().
Referenced by Geom_GetPolyCentroidCmd().
int sys_geom_InterpolateScalar (cvPolyData * src, double pt[], double * scalar)
Definition at line 2481 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, and cvPolyData::GetVtkPolyData().
Referenced by Geom_InterpolateScalarCmd().
int sys_geom_InterpolateVector (cvPolyData * src, double pt[], double vect[])
Definition at line 2561 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, and cvPolyData::GetVtkPolyData().
Referenced by Geom_InterpolateVectorCmd().
int sys_geom_intersect (cvPolyData * srcA, cvPolyData * srcB, cvPolyData ** dst)
Definition at line 491 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, and vtkNew.
Referenced by Geom_IntersectCmd().
int sys_geom_IntersectWithLine (cvPolyData * src, double p0[], double p1[], double intersect[])
Definition at line 2653 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, and cvPolyData::GetVtkPolyData().
Referenced by Geom_IntersectWithLineCmd().
int sys_geom_MakePolysConsistent (cvPolyData * src, cvPolyData ** dst)
Definition at line 432 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), VtkUtils_DeepCopyCells(), VtkUtils_DeepCopyPoints(), and VtkUtils_MakePolysConsistent().
Referenced by Geom_MakePolysConsistentCmd().
int sys_geom_mathPointData (cvPolyData * srcA, cvPolyData * srcB, sys_geom_math_scalar scflag, sys_geom_math_vector vflag, cvPolyData ** dst)
Definition at line 2771 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, SYS_GEOM_ADD_SCALAR, SYS_GEOM_ADD_VECTOR, SYS_GEOM_DIVIDE_SCALAR, SYS_GEOM_DIVIDE_VECTOR, SYS_GEOM_MULTIPLY_SCALAR, SYS_GEOM_MULTIPLY_VECTOR, SYS_GEOM_NO_SCALAR, SYS_GEOM_NO_VECTOR, SYS_GEOM_SUBTRACT_SCALAR, and SYS_GEOM_SUBTRACT_VECTOR.
Referenced by Geom_AddPointDataCmd(), Geom_DividePointDataCmd(), Geom_MultiplyPointDataCmd(), and Geom_SubtractPointDataCmd().
cvPolyData* sys_geom_MergePts (cvPolyData * src)
Definition at line 113 of file cv_sys_geom.cxx.
References FindMachineEpsilon(), and sys_geom_MergePts_tol().
Referenced by cvMeshSimDiscreteSolidModel::GetFacePolyData(), cvPolyDataSolid::GetFacePolyData(), sys_geom_2DWindingNum(), sys_geom_AvgPt(), sys_geom_GetClosedLineRegion(), sys_geom_GetOrderedPts(), sys_geom_NumClosedLineRegions(), sys_geom_Pick(), sys_geom_Reduce(), and sys_geom_sampleLoop().
cvPolyData* sys_geom_MergePts_tol (cvPolyData * src, double tol)
Definition at line 124 of file cv_sys_geom.cxx.
References cvPolyData::GetVtkPolyData().
Referenced by Geom_MergePtsCmd(), and sys_geom_MergePts().
int sys_geom_NumClosedLineRegions (cvPolyData * src, int * num)
Definition at line 144 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, sys_geom_MergePts(), VtkUtils_FindClosedLineRegions(), VtkUtils_GetLines(), and VtkUtils_GetPoints().
Referenced by Geom_NumClosedLineRegionsCmd().
int sys_geom_OrientProfile (cvPolyData * src, double ppt[], double ptan[], double xhat[], cvPolyData ** dst)
Definition at line 1501 of file cv_sys_geom.cxx.
References Cross(), CV_OK, cvPolyData::GetVtkPolyData(), NormVector(), and VtkUtils_DeepCopyCells().
Referenced by Geom_OrientProfileCmd().
int sys_geom_Pick (cvPolyData * src, double pos[], cvPolyData ** dst)
Definition at line 277 of file cv_sys_geom.cxx.
References cvSolidModel::ClassifyPt(), cvSolidModel::Clear(), CV_ERROR, CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), cvPolyData::GetVtkPolyData(), cvSolidModel::MakePoly2d(), NULL, sys_geom_MergePts(), VtkUtils_FindClosedLineRegions(), VtkUtils_GetClosedLineRegion(), VtkUtils_GetLines(), VtkUtils_GetPoints(), and VtkUtils_MakePolyDataFromLineIds().
Referenced by Geom_PickCmd().
int sys_geom_PolygonNormal (cvPolyData * pgn, double n[])
Definition at line 2375 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, NormVector(), and sys_geom_GetOrderedPts().
Referenced by Geom_PolygonNormCmd(), PsdUtils_MakeCap(), sys_geom_Align(), and sys_geom_AlignByDist().
int sys_geom_PolysClosed (cvPolyData * src, int * closed)
Definition at line 1126 of file cv_sys_geom.cxx.
References cgeom_PolysClosed(), CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), VtkUtils_GetAllPolys(), and VtkUtils_GetPointsFloat().
Referenced by Geom_PolysClosedCmd().
int sys_geom_PrintSmallPolys (cvPolyData * src, double sideTol)
Definition at line 1347 of file cv_sys_geom.cxx.
References cgeom_FindDegen(), CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), VtkUtils_GetAllPolys(), and VtkUtils_GetPointsFloat().
Referenced by Geom_PrintSmallPolysCmd().
int sys_geom_PrintTriStats (cvPolyData * surf)
Definition at line 1235 of file cv_sys_geom.cxx.
References c, Cross(), CV_ERROR, CV_OK, Distance(), FindMachineEpsilon(), cvPolyData::GetVtkPolyData(), Magnitude(), maximum, minimum, VtkUtils_GetAllPolys(), and VtkUtils_GetPoints().
Referenced by Geom_PrintTriStatsCmd().
int sys_geom_Project (cvPolyData * srcA, cvPolyData * srcB, sys_geom_math_scalar scflag, sys_geom_math_vector vflag, cvPolyData ** dst)
Definition at line 2880 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, SYS_GEOM_NO_SCALAR, and SYS_GEOM_NO_VECTOR.
Referenced by Geom_ProjectCmd().
int sys_geom_PtInPoly (cvPolyData * obj, double pt[], int usePrevPoly, int * result)
Definition at line 2084 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, g_sys_geom_PtInPoly_pgon, cvPolyData::GetVtkPolyData(), ggems_CrossingsMultiplyTest(), NULL, and sys_geom_Get2DPgon().
Referenced by Geom_PtInPolyCmd(), img_calcCorrectionEqn(), img_calcCorrectionEqnAuto(), and cvLevelSetSparseGrid::InitSign_Internal().
int sys_geom_Reduce (cvPolyData * src, double tol, cvPolyData ** dst)
Definition at line 402 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, sys_geom_MergePts(), and VtkUtils_FixTopology().
Referenced by Geom_ReduceCmd().
cvPolyData* sys_geom_ReorderPolygon (cvPolyData * src, int startIx)
Definition at line 1836 of file cv_sys_geom.cxx.
References CV_OK, NULL, sys_geom_GetOrderedPts(), and VtkUtils_NewVtkPolyDataLines().
Referenced by Geom_ReorderPgnCmd(), sys_geom_Align(), and sys_geom_AlignByDist().
int sys_geom_ReplacePointData (cvPolyData * srcA, cvPolyData * srcB, sys_geom_math_scalar scflag, sys_geom_math_vector vflag, cvPolyData ** dst)
Definition at line 3029 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, SYS_GEOM_NO_SCALAR, and SYS_GEOM_NO_VECTOR.
Referenced by Geom_ReplacePointDataCmd().
int sys_geom_ReverseAllCells (cvPolyData * src, cvPolyData ** dst)
Definition at line 665 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), VtkUtils_DeepCopyCells(), VtkUtils_DeepCopyPoints(), and VtkUtils_ReverseAllCells().
Referenced by Geom_ReverseAllCellsCmd().
int sys_geom_ReversePtList (int num, double ptsIn[], double * ptsOut[])
Definition at line 929 of file cv_sys_geom.cxx.
References CV_OK.
Referenced by PsdUtils_MakePoly2dPts(), and sys_geom_Get2DPgon().
int sys_geom_RmSmallPolys (cvPolyData * src, double sideTol, cvPolyData ** dst)
Definition at line 1387 of file cv_sys_geom.cxx.
References cgeom_FindDegen(), cgeom_FixDegen(), CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), VtkUtils_GetAllPolys(), VtkUtils_GetPointsFloat(), and VtkUtils_NewVtkPolyData().
Referenced by Geom_RmSmallPolysCmd().
cvPolyData* sys_geom_sampleLoop (cvPolyData * src, int targetNumPts)
Definition at line 2166 of file cv_sys_geom.cxx.
References cvMath::createArray(), CV_ERROR, CV_OK, cvMath::deleteArray(), FindMachineEpsilon(), cvPolyData::GetVtkPolyData(), cvMath::linearInterpolateCurve(), NULL, sys_geom_GetOrderedPts(), sys_geom_MergePts(), VtkUtils_FindClosedLineRegions(), VtkUtils_GetLines(), VtkUtils_GetPoints(), and VtkUtils_NewVtkPolyDataLines().
Referenced by Geom_sampleLoopCmd().
int sys_geom_ScaleAvg (cvPolyData * src, double factor, cvPolyData ** dst)
Definition at line 1696 of file cv_sys_geom.cxx.
References CV_OK, cvPolyData::GetVtkPolyData(), sys_geom_AvgPt(), and sys_geom_DeepCopy().
Referenced by Geom_ScaleAvgCmd().
int sys_geom_subtract (cvPolyData * srcA, cvPolyData * srcB, cvPolyData ** dst)
Definition at line 520 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, and vtkNew.
Referenced by Geom_SubtractCmd().
int sys_geom_SurfArea (cvPolyData * src, double * area)
Definition at line 1154 of file cv_sys_geom.cxx.
References cgeom_CompArea(), CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), VtkUtils_GetAllPolys(), and VtkUtils_GetPointsFloat().
Referenced by Geom_SurfAreaCmd().
int sys_geom_Translate (cvPolyData * src, double translate[], cvPolyData ** dst)
Definition at line 1670 of file cv_sys_geom.cxx.
References CV_OK, cvPolyData::GetVtkPolyData(), and sys_geom_DeepCopy().
Referenced by Geom_TranslateCmd().
int sys_geom_union (cvPolyData * srcA, cvPolyData * srcB, cvPolyData ** dst)
Definition at line 462 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, and vtkNew.
Referenced by Geom_UnionCmd().
cvPolyData* sys_geom_warp3dPts (cvPolyData * src, double scale)
Definition at line 2709 of file cv_sys_geom.cxx.
References cvPolyData::GetVtkPolyData().
Referenced by Geom_Warp3dPtsCmd().
int sys_geom_WriteLines (cvPolyData * src, char * fn)
Definition at line 1080 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, cvPolyData::GetVtkPolyData(), NULL, VtkUtils_GetLines(), and VtkUtils_GetPoints().
Referenced by Geom_WriteLinesCmd().
int sys_geom_WriteOrderedPts (cvPolyData * src, char * fn)
Definition at line 950 of file cv_sys_geom.cxx.
References CV_ERROR, CV_OK, NULL, and sys_geom_GetOrderedPts().
Referenced by Geom_WriteOrderedPtsCmd().
Variable Documentation
int g_sys_geom_PtInPoly_num = 0 static
Definition at line 2082 of file cv_sys_geom.cxx.
double* g_sys_geom_PtInPoly_pgon = NULL static
Definition at line 2081 of file cv_sys_geom.cxx.
Referenced by sys_geom_PtInPoly().