simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/cv_ggems.h File Reference
cv_ggems.h File Reference
#include "cv_misc_utils.h"
Classes
struct _ggemsGeoPoint
Macros
#define PI 3.141592653589793324
#define ggemsGeoZeroVec(v) ((v).x = (v).y = (v).z = 0.0)
#define ggemsGeoMultVec(a, b, c) do {(c).x = a*(b).x; (c).y = a*(b).y; (c).z = a*(b).z; } while (0)
#define ggemsGeo_Vet(a, b, c) do {(c).x = (b).x-(a).x; (c).y = (b).y-(a).y; (c).z = (b).z-(a).z;} while (0)
Typedefs
typedef double Rdouble
typedef float Rfloat
typedef struct _ggemsGeoPoint ggemsGeoPoint
Functions
Rdouble ggemsGeoDotProd (ggemsGeoPoint *vec0, ggemsGeoPoint *vec1)
void ggemsGeoCrossProd (ggemsGeoPoint *in0, ggemsGeoPoint *in1, ggemsGeoPoint *out)
Rdouble ggemsGeoTripleProd (ggemsGeoPoint *vec0, ggemsGeoPoint *vec1, ggemsGeoPoint *vec2)
Rdouble ggemsGeoVecLen (ggemsGeoPoint *vec)
int ggemsGeoPolyNormal (int n_verts, ggemsGeoPoint *verts, ggemsGeoPoint *n)
Rdouble ggemsgeo_solid_angle (int n_vert, ggemsGeoPoint *verts, ggemsGeoPoint *p)
int ggems_CrossingsMultiplyTest (double pgon[], int numverts, double point[])
Macro Definition Documentation
#define ggemsGeo_Vet (a, b, c) do {(c).x = (b).x-(a).x; (c).y = (b).y-(a).y; (c).z = (b).z-(a).z;} while (0)
Definition at line 41 of file cv_ggems.h.
Referenced by ggemsgeo_solid_angle(), and ggemsGeoPolyNormal().
#define ggemsGeoMultVec (a, b, c) do {(c).x = a*(b).x; (c).y = a*(b).y; (c).z = a*(b).z; } while (0)
Definition at line 40 of file cv_ggems.h.
Referenced by ggemsgeo_solid_angle(), and ggemsGeoPolyNormal().
#define ggemsGeoZeroVec (v) ((v).x = (v).y = (v).z = 0.0)
Definition at line 39 of file cv_ggems.h.
Referenced by ggemsGeoPolyNormal().
#define PI 3.141592653589793324
Definition at line 38 of file cv_ggems.h.
Referenced by ggemsgeo_solid_angle(), and sys_geom_Classify().
Typedef Documentation
typedef struct _ggemsGeoPoint ggemsGeoPoint
typedef double Rdouble
Definition at line 43 of file cv_ggems.h.
typedef float Rfloat
Definition at line 44 of file cv_ggems.h.
Function Documentation
int ggems_CrossingsMultiplyTest (double pgon[], int numverts, double point[])
Definition at line 158 of file cv_ggems.cxx.
References X, and Y.
Referenced by sys_geom_PtInPoly().
Rdouble ggemsgeo_solid_angle (int n_vert, ggemsGeoPoint * verts, ggemsGeoPoint * p)
Definition at line 96 of file cv_ggems.cxx.
References ggemsGeo_Vet, ggemsGeoCrossProd(), ggemsGeoDotProd(), ggemsGeoMultVec, ggemsGeoPolyNormal(), ggemsGeoTripleProd(), ggemsGeoVecLen(), maximum, minimum, and PI.
Referenced by sys_geom_Classify().
void ggemsGeoCrossProd (ggemsGeoPoint * in0, ggemsGeoPoint * in1, ggemsGeoPoint * out)
Definition at line 45 of file cv_ggems.cxx.
References _ggemsGeoPoint::x, _ggemsGeoPoint::y, and _ggemsGeoPoint::z.
Referenced by ggemsgeo_solid_angle(), ggemsGeoPolyNormal(), and ggemsGeoTripleProd().
Rdouble ggemsGeoDotProd (ggemsGeoPoint * vec0, ggemsGeoPoint * vec1)
Definition at line 40 of file cv_ggems.cxx.
References _ggemsGeoPoint::x, _ggemsGeoPoint::y, and _ggemsGeoPoint::z.
Referenced by ggemsgeo_solid_angle(), ggemsGeoTripleProd(), and ggemsGeoVecLen().
int ggemsGeoPolyNormal (int n_verts, ggemsGeoPoint * verts, ggemsGeoPoint * n)
Definition at line 65 of file cv_ggems.cxx.
References ggemsGeo_Vet, ggemsGeoCrossProd(), ggemsGeoMultVec, ggemsGeoVecLen(), ggemsGeoZeroVec, _ggemsGeoPoint::x, _ggemsGeoPoint::y, and _ggemsGeoPoint::z.
Referenced by ggemsgeo_solid_angle().
Rdouble ggemsGeoTripleProd (ggemsGeoPoint * vec0, ggemsGeoPoint * vec1, ggemsGeoPoint * vec2)
Definition at line 52 of file cv_ggems.cxx.
References ggemsGeoCrossProd(), and ggemsGeoDotProd().
Referenced by ggemsgeo_solid_angle().
Rdouble ggemsGeoVecLen (ggemsGeoPoint * vec)
Definition at line 60 of file cv_ggems.cxx.
References ggemsGeoDotProd().
Referenced by ggemsgeo_solid_angle(), and ggemsGeoPolyNormal().