simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Image/cv_image.h File Reference
cv_image.h File Reference
#include "SimVascular.h"
Classes
struct Pixel_T
struct Image_T
Enumerations
enum ImageData_T { IMG_INTENSITY, IMG_GRADIX, IMG_GRADIY, IMG_GRADIZ }
Functions
Image_T * ReadImage (char *filebase, int fileNumRange[], char *imgTypeFlag, int imgDims[], double pixelDims[])
Image_T * CreateImage (void *data, int numData, char *imgTypeFlag, int imgDims[], double pixelDims[])
void Image_Delete (Image_T *img)
double ComputePointSlope (Pixel_T *prev, Pixel_T *curr, Pixel_T *next, Image_T *image, int dimFlag)
void ComputeImageGrad (Image_T *image)
double GetMaxGrad (Image_T *image)
void Img_GetMagGradRange (Image_T *image, double rng[])
void Img_GetXYMagGradRange (Image_T *image, double rng[])
void Img_GetZMagGradRange (Image_T *image, double rng[])
void Img_GetIntensityRange (Image_T *image, double rng[])
void SetImageClosed (Image_T *image, int flag)
int GetImageClosed (Image_T *image)
void SetLowerLeft (Image_T *image, double pos[])
void GetLowerLeft (Image_T *image, double pos[])
int InBorder (Image_T *image, double pos[], int borderWd)
void CloseImageGradBounds (Image_T *image)
int LinearInterp (Image_T *image, ImageData_T code, double pos[], double *value)
int GetIntensity (Image_T *image, double pos[], double *result)
int GetGradIx (Image_T *image, double pos[], double *result)
int GetGradIy (Image_T *image, double pos[], double *result)
int GetGradIz (Image_T *image, double pos[], double *result)
void WriteZSlice (Image_T *image, char *filename, int num, char *imgTypeFlag, ImageData_T field)
int InRange (Image_T *image, double pos[])
int Img_GetMemoryUsage (Image_T *image)
Enumeration Type Documentation
enum ImageData_T
Enumerator
IMG_INTENSITY
IMG_GRADIX
IMG_GRADIY
IMG_GRADIZ
Definition at line 66 of file cv_image.h.
Function Documentation
void CloseImageGradBounds (Image_T * image)
Definition at line 636 of file cv_image.cxx.
References Image_T::closed, ComputeImageGrad(), Image_T::dim, Pixel_T::gradX, Pixel_T::gradY, Pixel_T::gradZ, Img_GetMagGradRange(), Image_T::imgDims, and Image_T::pixels.
void ComputeImageGrad (Image_T * image)
Definition at line 312 of file cv_image.cxx.
References ComputePointSlope(), Image_T::dim, Image_T::gradValid, Pixel_T::gradX, Pixel_T::gradY, Pixel_T::gradZ, Image_T::imgDims, and Image_T::pixels.
Referenced by CloseImageGradBounds(), GetGradIx(), GetGradIy(), GetGradIz(), Img_GetMagGradRange(), Img_GetXYMagGradRange(), Img_GetZMagGradRange(), cvLevelSetVelocityImage::SetImage(), and cvLevelSetVelocityKGI::SetUpPotentialField().
double ComputePointSlope (Pixel_T * prev, Pixel_T * curr, Pixel_T * next, Image_T * image, int dimFlag)
Definition at line 225 of file cv_image.cxx.
References Pixel_T::col, Pixel_T::intensity, Image_T::pixelDims, Pixel_T::plane, Pixel_T::row, and sqr.
Referenced by ComputeImageGrad().
Image_T* CreateImage (void * data, int numData, char * imgTypeFlag, int imgDims[], double pixelDims[])
Definition at line 700 of file cv_image.cxx.
References Image_T::closed, Pixel_T::col, Image_T::dim, FindMachineEpsilon(), gMachineEpsilon, Image_T::gradValid, Image_T::imgDims, Pixel_T::intensity, Image_T::lowerleft, NULL, Image_T::pixelDims, Image_T::pixels, Pixel_T::plane, and Pixel_T::row.
Referenced by cvLevelSetSparseGrid::InitPhi(), cvLevelSetVelocityImage::SetImage(), and cvLevelSetVelocityKGI::SetUpPotentialField().
int GetGradIx (Image_T * image, double pos[], double * result)
Definition at line 1173 of file cv_image.cxx.
References ComputeImageGrad(), Image_T::gradValid, IMG_GRADIX, and LinearInterp().
Referenced by cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int GetGradIy (Image_T * image, double pos[], double * result)
Definition at line 1186 of file cv_image.cxx.
References ComputeImageGrad(), Image_T::gradValid, IMG_GRADIY, and LinearInterp().
Referenced by cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int GetGradIz (Image_T * image, double pos[], double * result)
Definition at line 1199 of file cv_image.cxx.
References ComputeImageGrad(), Image_T::gradValid, IMG_GRADIZ, and LinearInterp().
Referenced by cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int GetImageClosed (Image_T * image)
Definition at line 558 of file cv_image.cxx.
References Image_T::closed.
Referenced by cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int GetIntensity (Image_T * image, double pos[], double * result)
Definition at line 1163 of file cv_image.cxx.
References IMG_INTENSITY, and LinearInterp().
Referenced by cvLevelSetVelocityThreshold::Evaluate(), cvLevelSetVelocityPotential::Evaluate(), and cvLevelSetSparseGrid::InitPhi().
void GetLowerLeft (Image_T * image, double pos[])
Definition at line 582 of file cv_image.cxx.
References Image_T::lowerleft.
double GetMaxGrad (Image_T * image)
Definition at line 419 of file cv_image.cxx.
References Img_GetMagGradRange().
Referenced by cvLevelSetVelocityKGI::GetMaxImageIGrad().
void Image_Delete (Image_T * img)
Definition at line 197 of file cv_image.cxx.
References NULL, and Image_T::pixels.
Referenced by cvLevelSetVelocityImage::ClearImage(), cvLevelSetSparseGrid::InitPhi(), and cvLevelSetVelocityKGI::SetUpPotentialField().
void Img_GetIntensityRange (Image_T * image, double rng[])
Definition at line 518 of file cv_image.cxx.
References Image_T::imgDims, Pixel_T::intensity, maximum, minimum, and Image_T::pixels.
Referenced by cvLevelSetVelocityImage::GetIntensityRange().
void Img_GetMagGradRange (Image_T * image, double rng[])
Definition at line 431 of file cv_image.cxx.
References ComputeImageGrad(), Pixel_T::gradX, Pixel_T::gradY, Pixel_T::gradZ, Image_T::imgDims, Magnitude(), maximum, minimum, and Image_T::pixels.
Referenced by CloseImageGradBounds(), cvLevelSetVelocityImage::GetMagGradRange(), and GetMaxGrad().
int Img_GetMemoryUsage (Image_T * image)
Definition at line 1321 of file cv_image.cxx.
References Image_T::imgDims, and NULL.
Referenced by cvLevelSetVelocityImage::GetImgSize(), cvLevelSetVelocityThreshold::GetMemoryUsage(), cvLevelSetVelocityPotential::GetMemoryUsage(), cvLevelSetVelocityKGI::GetMemoryUsage(), and cvLevelSetVelocityExponentialDecay::GetMemoryUsage().
void Img_GetXYMagGradRange (Image_T * image, double rng[])
Definition at line 461 of file cv_image.cxx.
References ComputeImageGrad(), Pixel_T::gradX, Pixel_T::gradY, Image_T::imgDims, Magnitude(), maximum, minimum, and Image_T::pixels.
Referenced by cvLevelSetVelocityImage::GetXYMagGradRange().
void Img_GetZMagGradRange (Image_T * image, double rng[])
Definition at line 490 of file cv_image.cxx.
References ComputeImageGrad(), Pixel_T::gradZ, Image_T::imgDims, maximum, minimum, and Image_T::pixels.
Referenced by cvLevelSetVelocityImage::GetZMagGradRange().
int InBorder (Image_T * image, double pos[], int borderWd)
Definition at line 594 of file cv_image.cxx.
References Image_T::imgDims, Image_T::lowerleft, and Image_T::pixelDims.
Referenced by cvLevelSetVelocityPotential::Evaluate(), cvLevelSetVelocityKGI::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int InRange (Image_T * image, double pos[])
Definition at line 1286 of file cv_image.cxx.
References Image_T::dim, Image_T::imgDims, and Image_T::pixelDims.
Referenced by LinearInterp().
int LinearInterp (Image_T * image, ImageData_T code, double pos[], double * value)
Definition at line 793 of file cv_image.cxx.
References Image_T::dim, gMachineEpsilon, Pixel_T::gradX, Pixel_T::gradY, Pixel_T::gradZ, IMG_GRADIX, IMG_GRADIY, IMG_GRADIZ, IMG_INTENSITY, Image_T::imgDims, InRange(), Pixel_T::intensity, Image_T::lowerleft, Image_T::pixelDims, and Image_T::pixels.
Referenced by GetGradIx(), GetGradIy(), GetGradIz(), and GetIntensity().
Image_T* ReadImage (char * filebase, int fileNumRange[], char * imgTypeFlag, int imgDims[], double pixelDims[])
Definition at line 58 of file cv_image.cxx.
References Image_T::closed, Pixel_T::col, Image_T::dim, Image_T::filebase, filename, Image_T::fileNumRange, FindMachineEpsilon(), gMachineEpsilon, Image_T::gradValid, Image_T::imgDims, Pixel_T::intensity, Image_T::lowerleft, NULL, Image_T::pixelDims, Image_T::pixels, Pixel_T::plane, and Pixel_T::row.
Referenced by cvLevelSetVelocityImage::SetImage().
void SetImageClosed (Image_T * image, int flag)
Definition at line 544 of file cv_image.cxx.
References Image_T::closed.
Referenced by cvLevelSetVelocityImage::SetImage().
void SetLowerLeft (Image_T * image, double pos[])
Definition at line 568 of file cv_image.cxx.
References Image_T::dim, and Image_T::lowerleft.
Referenced by cvLevelSetSparseGrid::InitPhi(), and cvLevelSetVelocityImage::SetImage().
void WriteZSlice (Image_T * image, char * filename, int num, char * imgTypeFlag, ImageData_T field)
Definition at line 1212 of file cv_image.cxx.
References Pixel_T::gradX, Pixel_T::gradY, Pixel_T::gradZ, IMG_GRADIX, IMG_GRADIY, IMG_GRADIZ, IMG_INTENSITY, Image_T::imgDims, Pixel_T::intensity, Image_T::pixels, and Pixel_T::plane.