simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/PostProcessing/cv_post_init.cxx File Reference
cv_post_init.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include <string.h>
#include "cvRepository.h"
#include "cvRepositoryData.h"
#include "cvUnstructuredGrid.h"
#include "cvPolyData.h"
#include "cv_post_init.h"
#include "cv_sys_geom.h"
#include "cv_arg.h"
#include "cv_misc_utils.h"
#include "cvConvertVisFiles.h"
#include "cvCalculateWallShearStress.h"
#include "cvCalculateTKE.cxx"
#include "cv_globals.h"
Functions
int gdscPost_readVisMeshCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscPost_readVisResCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscPost_calcWallShearCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscPost_calcWallShearMeanCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscPost_calcWallShearPulseCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscPost_calcOSICmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscPost_calcAvgPointDataCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscPost_calcTKECmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Gdscpost_Init (Tcl_Interp *interp)
Function Documentation
int gdscPost_calcAvgPointDataCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 961 of file cv_post_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), ARG_List_s::argc, ARG_List_s::argv, cvCalculateWallShearStress::CalcAvgPointData(), cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, cvCalculateWallShearStress::SetSurfaceMesh(), and STRING_Type.
Referenced by Gdscpost_Init().
int gdscPost_calcOSICmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 839 of file cv_post_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvCalculateWallShearStress::CalcOSI(), cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, cvCalculateWallShearStress::SetSurfaceMesh(), and STRING_Type.
Referenced by Gdscpost_Init().
int gdscPost_calcTKECmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1091 of file cv_post_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), ARG_List_s::argc, ARG_List_s::argv, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvCalculateTKE::GetTKEPolyData(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, cvCalculateTKE::SetInputData(), and STRING_Type.
Referenced by Gdscpost_Init().
int gdscPost_calcWallShearCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 428 of file cv_post_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvCalculateWallShearStress::CalcWallShearFromStresses(), cvCalculateWallShearStress::CalcWallShearFromTractions(), CV_ERROR, cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), cvCalculateWallShearStress::GetWallShear(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, cvCalculateWallShearStress::SetSurfaceMesh(), cvCalculateWallShearStress::SetTensors(), cvCalculateWallShearStress::SetTractions(), and STRING_Type.
Referenced by Gdscpost_Init().
int gdscPost_calcWallShearMeanCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 582 of file cv_post_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), ARG_List_s::argc, ARG_List_s::argv, cvCalculateWallShearStress::CalcWallShearMean(), cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, cvCalculateWallShearStress::SetSurfaceMesh(), and STRING_Type.
Referenced by Gdscpost_Init().
int gdscPost_calcWallShearPulseCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 710 of file cv_post_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), ARG_List_s::argc, ARG_List_s::argv, cvCalculateWallShearStress::CalcWallShearPulse(), cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, cvCalculateWallShearStress::SetSurfaceMesh(), and STRING_Type.
Referenced by Gdscpost_Init().
int Gdscpost_Init (Tcl_Interp * interp)
Definition at line 84 of file cv_post_init.cxx.
References gdscPost_calcAvgPointDataCmd(), gdscPost_calcOSICmd(), gdscPost_calcTKECmd(), gdscPost_calcWallShearCmd(), gdscPost_calcWallShearMeanCmd(), gdscPost_calcWallShearPulseCmd(), gdscPost_readVisMeshCmd(), gdscPost_readVisResCmd(), and NULL.
Referenced by SimVascular_Init().
int gdscPost_readVisMeshCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 109 of file cv_post_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, cvRepository::Exists(), cvConvertVisFiles::GetGridObj(), cvRepositoryData::GetName(), gRepository, NULL, cvConvertVisFiles::ReadVisMesh(), cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by Gdscpost_Init().
int gdscPost_readVisResCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 175 of file cv_post_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, CV_ERROR, cvRepository::Exists(), GDSC_OPTIONAL, cvConvertVisFiles::GetDisplacementObj(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvConvertVisFiles::GetResObj(), cvConvertVisFiles::GetStressObj(), cvConvertVisFiles::GetTractionObj(), cvConvertVisFiles::GetTransportObj(), cvRepositoryData::GetType(), cvConvertVisFiles::GetWSSObj(), gRepository, INT_Type, LIST_Type, NULL, cvConvertVisFiles::ReadVisRes(), cvRepository::Register(), REQUIRED, cvConvertVisFiles::SetGrid(), cvConvertVisFiles::SetTractionNodes(), STRING_Type, and UNSTRUCTURED_GRID_T.
Referenced by Gdscpost_Init().