simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cv_misc_utils.h File Reference
cv_misc_utils.h File Reference
#include <math.h>
Macros
#define maximum(A, B) ((A) > (B) ? (A) : (B))
#define minimum(A, B) ((A) < (B) ? (A) : (B))
#define sqr(A) ((A) * (A))
#define CV_PHI_TOL 0.001
#define CV_STRLEN 1000
#define CV_PI 3.141592653589793324
Functions
char * PopArg (int *argc, char **argv[])
double FindMachineEpsilon ()
void NormVector (double *vx, double *vy, double *vz)
double Magnitude (double vx, double vy, double vz)
void Cross (double ax, double ay, double az, double bx, double by, double bz, double *prodx, double *prody, double *prodz)
double Dot (double ax, double ay, double az, double bx, double by, double bz)
double misc_Det3x3 (double mat[])
int Round (double d)
double Distance (double ax, double ay, double az, double bx, double by, double bz)
double Sign (double d, double tol)
int IntSign (double d, double tol)
int Compute3dks (double Kg, double Km, double tol, double ks[])
int CountLines (char *filename)
int LinInterp1D_dbl (double domA, double domB, double rangeA, double rangeB, double domTarget, double *rangeTarget)
Macro Definition Documentation
#define CV_PHI_TOL 0.001
Definition at line 44 of file cv_misc_utils.h.
Referenced by cvLevelSetVelocity::UnlinkLevelSet(), and cvLevelSetVelocity::UpdateTolerance().
#define CV_PI 3.141592653589793324
Definition at line 48 of file cv_misc_utils.h.
Referenced by DiscreteUtils_MakePoly3dSolidVtk(), and sys_geom_2DWindingNum().
#define CV_STRLEN 1000
Definition at line 46 of file cv_misc_utils.h.
Referenced by cvMesh_WriteSpectrumVisMtd(), Geom_BBoxCmd(), Geom_GetOrderedPtsCmd(), cvLevelSet::GetGridStatString(), LsetCore_EvolveOneTimeStepMtd(), LsetCore_ExtractProjectionSetsMtd(), LsetCore_GetCircleSeedMtd(), LsetCore_GetGridMtd(), LsetCore_GetSaveProjectionSetsMtd(), LsetCore_GetTimeMtd(), LsetCore_InitMtd(), LsetCore_RebuildPhiMtd(), LsetCore_SetTimersMtd(), LsetVConst_GetConstMtd(), LsetVExpDecay_GetConstMtd(), LsetVImage_GetImageMtd(), LsetVKGI_GetConstMtd(), LsetVPotential_GetConstMtd(), LsetVSmooth_GetConstMtd(), LsetVThr_GetConstMtd(), Solid_FindCentroidMtd(), cvLevelSetDenseGrid::StatString(), and cvLevelSetSparseGrid::StatString().
#define maximum (A, B) ((A) > (B) ? (A) : (B))
Definition at line 39 of file cv_misc_utils.h.
Referenced by Compute3dks(), cvLevelSetStructuredGrid::ComputeDeltaPhi(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::ConstructHT_Sweep(), cvLevelSetStructuredGrid::cvLevelSetStructuredGrid(), cvLevelSetStructuredGrid::FindDelMinus(), cvLevelSetStructuredGrid::FindDelPlus(), cvLevelSetDenseGrid::FindNearestActiveNode(), cvLevelSetStructuredGrid::GetMaxF(), cvLevelSetStructuredGrid::GetMaxPhiIncr(), cvLevelSetStructuredGrid::GetMaxV(), ggemsgeo_solid_angle(), Img_GetIntensityRange(), Img_GetMagGradRange(), Img_GetXYMagGradRange(), Img_GetZMagGradRange(), PsdUtils_GetBBox(), sys_geom_Align(), sys_geom_BBox(), and sys_geom_PrintTriStats().
#define minimum (A, B) ((A) < (B) ? (A) : (B))
Definition at line 40 of file cv_misc_utils.h.
Referenced by Compute3dks(), cvLevelSetStructuredGrid::ComputeDeltaPhi(), cvLevelSetStructuredGrid::cvLevelSetStructuredGrid(), cvLevelSetStructuredGrid::FindDelMinus(), cvLevelSetStructuredGrid::FindDelPlus(), ggemsgeo_solid_angle(), Img_GetIntensityRange(), Img_GetMagGradRange(), Img_GetXYMagGradRange(), Img_GetZMagGradRange(), PsdUtils_GetBBox(), cvLevelSet::SetDtFactor(), sys_geom_BBox(), sys_geom_PrintTriStats(), and cvLevelSetVelocity::UpdateTolerance().
#define sqr (A) ((A) * (A))
Definition at line 41 of file cv_misc_utils.h.
Referenced by ComputePointSlope(), cvLevelSetStructuredGrid::cvLevelSetStructuredGrid(), and cvLevelSetStructuredGrid::FindN().
Function Documentation
int Compute3dks (double Kg, double Km, double tol, double ks[])
Definition at line 100 of file cv_misc_utils.cxx.
References CV_ERROR, CV_OK, maximum, minimum, and Sign().
Referenced by cvLevelSetNode::ComputeDoubleDatum(), cvLevelSetVelocitySmooth::Evaluate(), and cvLevelSetVelocityExponentialDecay::Evaluate().
int CountLines (char * filename)
Definition at line 153 of file cv_misc_utils.cxx.
References c, and NULL.
void Cross (double ax, double ay, double az, double bx, double by, double bz, double * prodx, double * prody, double * prodz) inline
Definition at line 104 of file cv_misc_utils.h.
Referenced by cvAdaptCore::checkUnitaryOthoganal(), vtkvmtkBoundaryReferenceSystems::ComputeBoundaryNormal(), vtkvmtkBoundaryReferenceSystems::ComputeReferenceSystemPoints(), dp_mth_norm_frame(), vtkBooleanOperationPolyDataFilter2::Impl::GetCellOrientation(), vtkIntersectionPolyDataFilter2::Impl::GetTransform(), vtkIntegrateAttributes::IntegrateTetrahedron(), vtkIntegrateAttributes::IntegrateTriangle(), PsdUtils_MakeCylinder(), PsdUtils_MakeTorus(), vtkSurfaceVectors::RequestData(), sys_geom_Align(), sys_geom_DisorientProfile(), sys_geom_OrientProfile(), sys_geom_PrintTriStats(), vtkvmtkMath::TriangleGradient(), vtkIntersectionPolyDataFilter2::TriangleTriangleIntersection(), VMTKUtils_InsertIds(), and cvAdaptCore::writeMEDITSizeField().
double Distance (double ax, double ay, double az, double bx, double by, double bz) inline
Definition at line 177 of file cv_misc_utils.h.
Referenced by cvLevelSetDenseGrid::FindNearestActiveNode(), and sys_geom_PrintTriStats().
double Dot (double ax, double ay, double az, double bx, double by, double bz) inline
Definition at line 120 of file cv_misc_utils.h.
Referenced by vtkvmtkPolyDataManifoldExtendedNeighborhood::Build(), vtkvmtkBoundaryLayerGenerator::CheckTangle(), cvAdaptCore::checkUnitaryOthoganal(), vtkvmtkNonManifoldFastMarching::ComputeUpdateFromCellNeighbor(), cvLevelSetVelocityKGI::Evaluate(), cvLevelSetVelocityExponentialDecay::Evaluate(), vtkvmtkPolyDataCenterlines::FindVoronoiSeeds(), vtkIntersectionPolyDataFilter2::Impl::FollowLoopOrientation(), vtkBooleanOperationPolyDataFilter2::Impl::GetCellOrientation(), vtkIntersectionPolyDataFilter2::Impl::GetTransform(), vtkIntegrateAttributes::IntegrateTetrahedron(), vtkvmtkBoundaryLayerGenerator::LocalUntangle(), vtkvmtkBoundaryReferenceSystems::OrientBoundaryNormalOutwards(), vtkSurfaceVectors::RequestData(), vtkvmtkInternalTetrahedraExtractor::RequestData(), vtkvmtkPolyDataSurfaceRemeshing::RequestData(), vtkIntersectionPolyDataFilter2::Impl::SetLoopOrientation(), vtkIntersectionPolyDataFilter2::Impl::SplitCell(), vtkIntersectionPolyDataFilter2::Impl::SplitMesh(), sys_geom_Align(), sys_geom_AlignByDist(), vtkvmtkPolyDataSurfaceRemeshing::TestAspectRatioCollapseEdge(), vtkvmtkPolyDataSurfaceRemeshing::TestDelaunayFlipEdge(), vtkvmtkPolyDataSurfaceRemeshing::TestFlipEdgeValidity(), vtkIntersectionPolyDataFilter2::TriangleTriangleIntersection(), VMTKUtils_InsertIds(), and cvAdaptCore::writeMEDITSizeField().
double FindMachineEpsilon ()
Definition at line 66 of file cv_misc_utils.cxx.
References PolyConnList::num.
Referenced by CreateImage(), cvLevelSetStructuredGrid::cvLevelSetStructuredGrid(), cvLevelSetVelocity::cvLevelSetVelocity(), cvSolidModel::cvSolidModel(), dp_mth_norm_frame(), Geom_MergePtsCmd(), PsdUtils_GetCurveGeometry(), PsdUtils_GetWireGeometry(), PsdUtils_MakeCap(), ReadImage(), cvLevelSet::SetDtFactor(), sys_geom_DisorientProfile(), sys_geom_Get2DPgon(), sys_geom_MergePts(), sys_geom_PrintTriStats(), and sys_geom_sampleLoop().
int IntSign (double d, double tol) inline
Definition at line 210 of file cv_misc_utils.h.
Referenced by cvLevelSetStructuredGrid::ComputeDeltaPhi(), cvLevelSetSparseGrid::ConstructHT(), cvLevelSetSparseGrid::MakeClosedPhiVtk(), cvLevelSetSparseGrid::TopoUpdate(), and cvLevelSetSparseGrid::UpdatePhi().
int LinInterp1D_dbl (double domA, double domB, double rangeA, double rangeB, double domTarget, double * rangeTarget) inline
Definition at line 239 of file cv_misc_utils.h.
References CV_OK.
Referenced by cvLevelSetStructuredGrid::GetBoundaryData(), cvLevelSetStructuredGrid::InterpK(), cvLevelSetStructuredGrid::InterpKg(), cvLevelSetStructuredGrid::InterpKm(), cvLevelSetStructuredGrid::InterpN(), and cvLevelSetStructuredGrid::InterpZLS().
double Magnitude (double vx, double vy, double vz) inline
Definition at line 90 of file cv_misc_utils.h.
Referenced by cvLevelSetStructuredGrid::AssignNode(), cvLevelSetStructuredGrid::AssignVToNode(), cvLevelSetVelocityExponentialDecay::Evaluate(), Img_GetMagGradRange(), Img_GetXYMagGradRange(), PsdUtils_MakeCylinder(), PsdUtils_MakeFittedBCurve(), PsdUtils_MakeTorus(), cvLevelSetVelocityKGI::SetUpPotentialField(), and sys_geom_PrintTriStats().
double misc_Det3x3 (double mat[]) inline
Definition at line 135 of file cv_misc_utils.h.
Referenced by sys_geom_DisorientProfile().
void NormVector (double * vx, double * vy, double * vz) inline
Definition at line 71 of file cv_misc_utils.h.
Referenced by dp_mth_norm_frame(), cvAdaptCore::eigen(), cvLevelSetStructuredGrid::FindN(), PsdUtils_Extrude(), PsdUtils_MakeCylinder(), PsdUtils_MakeFittedBCurve(), PsdUtils_MakeTorus(), PsdUtils_Reflect(), PsdUtils_Rotate(), sys_geom_2DWindingNum(), sys_geom_Align(), sys_geom_DisorientProfile(), sys_geom_OrientProfile(), and sys_geom_PolygonNormal().
char* PopArg (int * argc, char ** argv[])
Definition at line 42 of file cv_misc_utils.cxx.
int Round (double d) inline
Definition at line 166 of file cv_misc_utils.h.
Referenced by vtkvmtkBoundaryReferenceSystems::OrientBoundaryNormalOutwards(), sys_geom_2DWindingNum(), and MyUt::TransformPhysicalToIndex().
double Sign (double d, double tol) inline
Definition at line 193 of file cv_misc_utils.h.
Referenced by Compute3dks().