simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/cv_ggems.cxx File Reference
cv_ggems.cxx File Reference
#include "SimVascular.h"
#include <math.h>
#include "cv_ggems.h"
Macros
#define X 0
#define Y 1
Functions
Rdouble ggemsGeoDotProd (ggemsGeoPoint *vec0, ggemsGeoPoint *vec1)
void ggemsGeoCrossProd (ggemsGeoPoint *in0, ggemsGeoPoint *in1, ggemsGeoPoint *out)
Rdouble ggemsGeoTripleProd (ggemsGeoPoint *vec0, ggemsGeoPoint *vec1, ggemsGeoPoint *vec2)
Rdouble ggemsGeoVecLen (ggemsGeoPoint *vec)
int ggemsGeoPolyNormal (int n_verts, ggemsGeoPoint *verts, ggemsGeoPoint *n)
Rdouble ggemsgeo_solid_angle (int n_vert, ggemsGeoPoint *verts, ggemsGeoPoint *p)
int ggems_CrossingsMultiplyTest (double pgon[], int numverts, double point[])
Macro Definition Documentation
#define X 0
Definition at line 151 of file cv_ggems.cxx.
Referenced by ggems_CrossingsMultiplyTest().
#define Y 1
Definition at line 152 of file cv_ggems.cxx.
Referenced by cvMath::compute_v_womersley(), and ggems_CrossingsMultiplyTest().
Function Documentation
int ggems_CrossingsMultiplyTest (double pgon[], int numverts, double point[])
Definition at line 158 of file cv_ggems.cxx.
References X, and Y.
Referenced by sys_geom_PtInPoly().
Rdouble ggemsgeo_solid_angle (int n_vert, ggemsGeoPoint * verts, ggemsGeoPoint * p)
Definition at line 96 of file cv_ggems.cxx.
References ggemsGeo_Vet, ggemsGeoCrossProd(), ggemsGeoDotProd(), ggemsGeoMultVec, ggemsGeoPolyNormal(), ggemsGeoTripleProd(), ggemsGeoVecLen(), maximum, minimum, and PI.
Referenced by sys_geom_Classify().
void ggemsGeoCrossProd (ggemsGeoPoint * in0, ggemsGeoPoint * in1, ggemsGeoPoint * out)
Definition at line 45 of file cv_ggems.cxx.
References _ggemsGeoPoint::x, _ggemsGeoPoint::y, and _ggemsGeoPoint::z.
Referenced by ggemsgeo_solid_angle(), ggemsGeoPolyNormal(), and ggemsGeoTripleProd().
Rdouble ggemsGeoDotProd (ggemsGeoPoint * vec0, ggemsGeoPoint * vec1)
Definition at line 40 of file cv_ggems.cxx.
References _ggemsGeoPoint::x, _ggemsGeoPoint::y, and _ggemsGeoPoint::z.
Referenced by ggemsgeo_solid_angle(), ggemsGeoTripleProd(), and ggemsGeoVecLen().
int ggemsGeoPolyNormal (int n_verts, ggemsGeoPoint * verts, ggemsGeoPoint * n)
Definition at line 65 of file cv_ggems.cxx.
References ggemsGeo_Vet, ggemsGeoCrossProd(), ggemsGeoMultVec, ggemsGeoVecLen(), ggemsGeoZeroVec, _ggemsGeoPoint::x, _ggemsGeoPoint::y, and _ggemsGeoPoint::z.
Referenced by ggemsgeo_solid_angle().
Rdouble ggemsGeoTripleProd (ggemsGeoPoint * vec0, ggemsGeoPoint * vec1, ggemsGeoPoint * vec2)
Definition at line 52 of file cv_ggems.cxx.
References ggemsGeoCrossProd(), and ggemsGeoDotProd().
Referenced by ggemsgeo_solid_angle().
Rdouble ggemsGeoVecLen (ggemsGeoPoint * vec)
Definition at line 60 of file cv_ggems.cxx.
References ggemsGeoDotProd().
Referenced by ggemsgeo_solid_angle(), and ggemsGeoPolyNormal().