simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimDiscreteSolidModel/cv_discrete_utils.cxx File Reference
cv_discrete_utils.cxx File Reference
#include "SimVascular.h"
#include "cv_globals.h"
#include "cv_discrete_utils.h"
#include "cv_misc_utils.h"
#include "cv_vtk_utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <assert.h>
#include <string.h>
#include "tcl.h"
#include "cvVTK.h"
#include "vtkSTLWriter.h"
#include "vtkIntArray.h"
#include "MeshSim.h"
#include "SimDiscrete.h"
Macros
#define MY_MESHSIM_VERTEX_ORDERING 1
#define MY_MESHSIM_EDGE_ORDERING 1
#define MY_MESHSIM_FACE_ORDERING 1
Functions
int DiscreteUtils_Init ()
int discreteCalcJacDet (double xx[2][4], double r, double s, double *determinant)
int DiscreteUtils_MakePoly3dSolidVtk (vtkPolyData *inputPD, int facetCode, double angle, pDiscreteModel *result)
int DiscreteUtils_GetVtkPolyData (pDiscreteModel model, int useMaxDist, double max_dist, vtkPolyData **out)
Macro Definition Documentation
#define MY_MESHSIM_EDGE_ORDERING 1
Definition at line 56 of file cv_discrete_utils.cxx.
#define MY_MESHSIM_FACE_ORDERING 1
Definition at line 57 of file cv_discrete_utils.cxx.
Referenced by cvMeshSimMeshObject::getNeighborMdlRegIds(), and cvMeshSimMeshObject::WriteMetisAdjacency().
#define MY_MESHSIM_VERTEX_ORDERING 1
Definition at line 55 of file cv_discrete_utils.cxx.
Referenced by DiscreteUtils_GetVtkPolyData(), cvMeshSimMeshObject::FindFaceNumber(), cvMeshSimDiscreteSolidModel::FindNodesOnElementFace(), cvMeshSimMeshObject::FindNodesOnElementFace(), cvMeshSimMeshObject::GetElementConnectivity(), cvMeshSimMeshObject::getNextElement(), and cvMeshSimMeshObject::GetPolyData().
Function Documentation
int discreteCalcJacDet (double xx[2][4], double r, double s, double * determinant)
Definition at line 149 of file cv_discrete_utils.cxx.
References CV_ERROR, CV_OK, and Hessian::h.
Referenced by DiscreteUtils_MakePoly3dSolidVtk().
int DiscreteUtils_GetVtkPolyData (pDiscreteModel model, int useMaxDist, double max_dist, vtkPolyData ** out)
Definition at line 447 of file cv_discrete_utils.cxx.
References CV_OK, MY_MESHSIM_VERTEX_ORDERING, NULL, and point.
Referenced by cvMeshSimDiscreteSolidModel::GetPolyData().
int DiscreteUtils_Init ()
Definition at line 64 of file cv_discrete_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by Meshsimdiscretesolid_Init().
int DiscreteUtils_MakePoly3dSolidVtk (vtkPolyData * inputPD, int facetCode, double angle, pDiscreteModel * result)
Definition at line 220 of file cv_discrete_utils.cxx.
References CV_ERROR, CV_OK, CV_PI, discreteCalcJacDet(), iter, NULL, and VtkUtils_GetPoints().
Referenced by cvMeshSimDiscreteSolidModel::MakePoly3dSolid().