simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/SolidModel/cv_solid_init.cxx File Reference
cv_solid_init.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include <string.h>
#include "cvRepository.h"
#include "cv_solid_init.h"
#include "cvSolidModel.h"
#include "cv_arg.h"
#include "cv_misc_utils.h"
#include "cv_vtk_utils.h"
#include "cvPolyData.h"
#include "cvPolyDataSolid.h"
#include "cvFactoryRegistrar.h"
#include "cv_globals.h"
Functions
int Solid_RegistrarsListCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_PolyCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_PolyPtsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_CircleCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_EllipseCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_Box2dCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_Box3dCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_SphereCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_EllipsoidCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_CylinderCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_TruncatedConeCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_TorusCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_Poly3dSolidCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_Poly3dSurfaceCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_ExtrudeZCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_ExtrudeCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_MakeApproxCurveLoopCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_MakeInterpCurveLoopCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_MakeLoftedSurfCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_CapSurfToSolidCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_IntersectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_UnionCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_SubtractCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_ReadNativeCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_CopyCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_ListMethodsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
void DeleteSolid (ClientData clientData)
int Solid_SetKernelCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_GetKernelCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Solid_PrintKernelInfoCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_FindExtentMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_FindCentroidMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetTopoDimMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetSpatialDimMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_ClassifyPtMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_DistanceMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetFaceNormalMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_TranslateMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_RotateMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_ScaleMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_ReflectMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_Apply4x4Mtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_PrintMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_CheckMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_WriteNativeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_WriteVtkPolyDataMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetFacePolyDataMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetPolyDataMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_SetVtkPolyDataMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetDiscontinuitiesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetAxialIsoparametricCurveMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetKernelMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetFaceIdsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetBoundaryFacesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetRegionIdsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetFaceAttrMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_SetFaceAttrMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetRegionAttrMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_SetRegionAttrMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetLabelKeysMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_GetLabelMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_SetLabelMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_ClearLabelMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_DeleteFacesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_DeleteRegionMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_CreateEdgeBlendMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_CombineFacesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int Solid_RemeshFaceMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static void PrintMethods (Tcl_Interp *interp)
int Solid_Init (Tcl_Interp *interp)
Function Documentation
void DeleteSolid (ClientData clientData)
Definition at line 2853 of file cv_solid_init.cxx.
References cvRepositoryData::GetName(), gRepository, and cvRepository::UnRegister().
Referenced by Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_CopyCmd(), Solid_CylinderCmd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_GetAxialIsoparametricCurveMtd(), Solid_IntersectCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_SphereCmd(), Solid_SubtractCmd(), Solid_TorusCmd(), Solid_TruncatedConeCmd(), and Solid_UnionCmd().
static void PrintMethods (Tcl_Interp * interp) static
Definition at line 2927 of file cv_solid_init.cxx.
References tcl_printstr().
Referenced by Solid_ListMethodsCmd(), and Solid_ObjectCmd().
static int Solid_Apply4x4Mtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3459 of file cv_solid_init.cxx.
References cvSolidModel::Apply4x4(), ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepositoryData::GetName(), LIST_Type, NULL, and REQUIRED.
Referenced by Solid_ObjectCmd().
int Solid_Box2dCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 750 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, cvSolidModel::MakeBox2d(), NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_Box3dCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 832 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, LIST_Type, cvSolidModel::MakeBox3d(), NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_CapSurfToSolidCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2082 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvSolidModel::CapSurfToSolid(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, cvRepository::Register(), REQUIRED, SOLID_MODEL_T, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
static int Solid_CheckMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3545 of file cv_solid_init.cxx.
References cvSolidModel::Check().
Referenced by Solid_ObjectCmd().
int Solid_CircleCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 584 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, cvSolidModel::MakeCircle(), NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
static int Solid_ClassifyPtMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3095 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvSolidModel::ClassifyPt(), CV_OK, DOUBLE_Type, GDSC_OPTIONAL, cvRepositoryData::GetName(), cvSolidModel::GetSpatialDim(), cvSolidModel::GetTopoDim(), INT_Type, NULL, and REQUIRED.
Referenced by Solid_ObjectCmd().
static int Solid_ClearLabelMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4162 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepositoryData::ClearLabel(), cvRepositoryData::IsLabelPresent(), NULL, REQUIRED, and STRING_Type.
Referenced by Solid_ObjectCmd().
static int Solid_CombineFacesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4603 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvSolidModel::CombineFaces(), CV_OK, cvRepositoryData::GetName(), INT_Type, NULL, and REQUIRED.
Referenced by Solid_ObjectCmd().
int Solid_CopyCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2240 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvSolidModel::Copy(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepository::GetType(), gRepository, NULL, cvRepository::Register(), REQUIRED, SOLID_MODEL_T, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
static int Solid_CreateEdgeBlendMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4565 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvSolidModel::CreateEdgeBlend(), CV_OK, DOUBLE_Type, cvRepositoryData::GetName(), INT_Type, NULL, and REQUIRED.
Referenced by Solid_ObjectCmd().
int Solid_CylinderCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1113 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, LIST_Type, cvSolidModel::MakeCylinder(), NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
static int Solid_DeleteFacesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4465 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, CV_OK, cvSolidModel::DeleteFaces(), faces(), cvRepositoryData::GetName(), INT_Type, LIST_Type, nfaces, NULL, and REQUIRED.
Referenced by Solid_ObjectCmd().
static int Solid_DeleteRegionMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4524 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DeleteRegion(), cvRepositoryData::GetName(), INT_Type, NULL, and REQUIRED.
Referenced by Solid_ObjectCmd().
static int Solid_DistanceMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3164 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argv, CV_OK, cvSolidModel::Distance(), DOUBLE_Type, cvRepositoryData::GetName(), cvSolidModel::GetSpatialDim(), LIST_Type, NULL, and REQUIRED.
Referenced by Solid_ObjectCmd().
int Solid_EllipseCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 665 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, cvSolidModel::MakeEllipse(), NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_EllipsoidCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1016 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, LIST_Type, cvSolidModel::MakeEllipsoid(), NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_ExtrudeCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1689 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvSolidModel::Extrude(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, cvRepository::Register(), REQUIRED, SOLID_MODEL_T, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_ExtrudeZCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1606 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvSolidModel::ExtrudeZ(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, cvRepository::Register(), REQUIRED, SOLID_MODEL_T, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
static int Solid_FindCentroidMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3000 of file cv_solid_init.cxx.
References CV_OK, CV_STRLEN, cvSolidModel::FindCentroid(), cvRepositoryData::GetName(), cvSolidModel::GetSpatialDim(), and NULL.
Referenced by Solid_ObjectCmd().
static int Solid_FindExtentMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2974 of file cv_solid_init.cxx.
References CV_OK, cvSolidModel::FindExtent(), cvRepositoryData::GetName(), and NULL.
Referenced by Solid_ObjectCmd().
static int Solid_GetAxialIsoparametricCurveMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3946 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvSolidModel::GetAxialIsoparametricCurve(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_ObjectCmd().
int Solid_GetBoundaryFacesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4231 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvSolidModel::GetBoundaryFaces(), cvRepositoryData::GetName(), NULL, and REQUIRED.
Referenced by Solid_ObjectCmd().
static int Solid_GetDiscontinuitiesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3888 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvSolidModel::GetDiscontinuities(), cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by Solid_ObjectCmd().
static int Solid_GetFaceAttrMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4299 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvSolidModel::GetFaceAttribute(), INT_Type, NULL, REQUIRED, and STRING_Type.
Referenced by Solid_ObjectCmd().
static int Solid_GetFaceIdsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4202 of file cv_solid_init.cxx.
References CV_OK, faces(), cvSolidModel::GetFaceIds(), cvRepositoryData::GetName(), and NULL.
Referenced by Solid_ObjectCmd().
static int Solid_GetFaceNormalMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3840 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, cvSolidModel::GetFaceNormal(), INT_Type, NULL, and REQUIRED.
Referenced by Solid_ObjectCmd().
static int Solid_GetFacePolyDataMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3774 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::Exists(), GDSC_OPTIONAL, cvSolidModel::GetFacePolyData(), cvRepositoryData::GetName(), gRepository, INT_Type, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by Solid_ObjectCmd().
int Solid_GetKernelCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2906 of file cv_solid_init.cxx.
References cvSolidModel::gCurrentKernel, NULL, and SolidModel_KernelT_EnumToStr().
Referenced by Solid_Init().
static int Solid_GetKernelMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4017 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), cvSolidModel::GetKernelT(), NULL, SM_KT_INVALID, and SolidModel_KernelT_EnumToStr().
Referenced by Solid_ObjectCmd().
static int Solid_GetLabelKeysMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4049 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), cvRepositoryData::GetLabelKeys(), and NULL.
Referenced by Solid_ObjectCmd().
static int Solid_GetLabelMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4078 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepositoryData::GetLabel(), NULL, REQUIRED, and STRING_Type.
Referenced by Solid_ObjectCmd().
static int Solid_GetPolyDataMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3650 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvSolidModel::GetPolyData(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by Solid_ObjectCmd().
static int Solid_GetRegionAttrMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4382 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvSolidModel::GetRegionAttribute(), INT_Type, NULL, REQUIRED, and STRING_Type.
Referenced by Solid_ObjectCmd().
static int Solid_GetRegionIdsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4269 of file cv_solid_init.cxx.
References CV_OK, cvRepositoryData::GetName(), cvSolidModel::GetRegionIds(), and NULL.
Referenced by Solid_ObjectCmd().
static int Solid_GetSpatialDimMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3069 of file cv_solid_init.cxx.
References CV_OK, cvRepositoryData::GetName(), cvSolidModel::GetSpatialDim(), and NULL.
Referenced by Solid_ObjectCmd().
static int Solid_GetTopoDimMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3043 of file cv_solid_init.cxx.
References CV_OK, cvRepositoryData::GetName(), cvSolidModel::GetTopoDim(), and NULL.
Referenced by Solid_ObjectCmd().
int Solid_Init (Tcl_Interp * interp)
Definition at line 294 of file cv_solid_init.cxx.
References cvSolidModel::gCurrentKernel, cvSolidModel::gRegistrar, NULL, SM_KT_INVALID, SM_KT_PARASOLID, Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_CopyCmd(), Solid_CylinderCmd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_GetKernelCmd(), Solid_IntersectCmd(), Solid_ListMethodsCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_RegistrarsListCmd(), Solid_SetKernelCmd(), Solid_SphereCmd(), Solid_SubtractCmd(), Solid_TorusCmd(), Solid_TruncatedConeCmd(), and Solid_UnionCmd().
Referenced by SimVascular_Init().
int Solid_IntersectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2320 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepository::GetType(), gRepository, cvSolidModel::Intersect(), NULL, cvRepository::Register(), REQUIRED, SM_Simplify_All, SM_Simplify_Invalid, SOLID_MODEL_T, Solid_ObjectCmd(), SolidModel_SimplifyT_EnumToStr(), SolidModel_SimplifyT_StrToEnum(), and STRING_Type.
Referenced by Solid_Init().
int Solid_ListMethodsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2651 of file cv_solid_init.cxx.
References NULL, and PrintMethods().
Referenced by Solid_Init().
int Solid_MakeApproxCurveLoopCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1798 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, cvSolidModel::MakeApproxCurveLoop(), NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_MakeInterpCurveLoopCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1883 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, cvSolidModel::MakeInterpCurveLoop(), NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_MakeLoftedSurfCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1967 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), ARG_List_s::argc, ARG_List_s::argv, CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, cvSolidModel::MakeLoftedSurf(), NULL, cvRepository::Register(), REQUIRED, SOLID_MODEL_T, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2668 of file cv_solid_init.cxx.
References NULL, PrintMethods(), Solid_Apply4x4Mtd(), Solid_CheckMtd(), Solid_ClassifyPtMtd(), Solid_ClearLabelMtd(), Solid_CombineFacesMtd(), Solid_CreateEdgeBlendMtd(), Solid_DeleteFacesMtd(), Solid_DeleteRegionMtd(), Solid_DistanceMtd(), Solid_FindCentroidMtd(), Solid_FindExtentMtd(), Solid_GetAxialIsoparametricCurveMtd(), Solid_GetBoundaryFacesMtd(), Solid_GetDiscontinuitiesMtd(), Solid_GetFaceAttrMtd(), Solid_GetFaceIdsMtd(), Solid_GetFaceNormalMtd(), Solid_GetFacePolyDataMtd(), Solid_GetKernelMtd(), Solid_GetLabelKeysMtd(), Solid_GetLabelMtd(), Solid_GetPolyDataMtd(), Solid_GetRegionAttrMtd(), Solid_GetRegionIdsMtd(), Solid_GetSpatialDimMtd(), Solid_GetTopoDimMtd(), Solid_PrintMtd(), Solid_ReflectMtd(), Solid_RemeshFaceMtd(), Solid_RotateMtd(), Solid_ScaleMtd(), Solid_SetFaceAttrMtd(), Solid_SetLabelMtd(), Solid_SetRegionAttrMtd(), Solid_SetVtkPolyDataMtd(), Solid_TranslateMtd(), Solid_WriteNativeMtd(), and Solid_WriteVtkPolyDataMtd().
Referenced by Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_CopyCmd(), Solid_CylinderCmd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_GetAxialIsoparametricCurveMtd(), Solid_IntersectCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_SphereCmd(), Solid_SubtractCmd(), Solid_TorusCmd(), Solid_TruncatedConeCmd(), and Solid_UnionCmd().
int Solid_Poly3dSolidCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1407 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, cvSolidModel::MakePoly3dSolid(), NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, cvSolidModel::SetPoly3dFacetMethod(), SM_Facet_Invalid, Solid_ObjectCmd(), SolidModel_FacetT_EnumToStr(), SolidModel_FacetT_StrToEnum(), and STRING_Type.
Referenced by Solid_Init().
int Solid_Poly3dSurfaceCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1507 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, cvSolidModel::MakePoly3dSurface(), NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, cvSolidModel::SetPoly3dFacetMethod(), SM_Facet_Invalid, Solid_ObjectCmd(), SolidModel_FacetT_EnumToStr(), SolidModel_FacetT_StrToEnum(), and STRING_Type.
Referenced by Solid_Init().
int Solid_PolyCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 500 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, cvSolidModel::MakePoly2d(), NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_PolyPtsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 418 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, cvSolidModel::MakePoly2dPts(), NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_PrintKernelInfoCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
static int Solid_PrintMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3530 of file cv_solid_init.cxx.
References cvSolidModel::Print().
Referenced by Solid_ObjectCmd().
int Solid_ReadNativeCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2163 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), cvRepository::Exists(), cvSolidModel::gCurrentKernel, cvRepositoryData::GetName(), gRepository, NULL, cvSolidModel::ReadNative(), cvRepository::Register(), REQUIRED, SM_KT_DISCRETE, SM_KT_PARASOLID, SM_KT_POLYDATA, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
static int Solid_ReflectMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3393 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepositoryData::GetName(), LIST_Type, NULL, cvSolidModel::Reflect(), and REQUIRED.
Referenced by Solid_ObjectCmd().
int Solid_RegistrarsListCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 376 of file cv_solid_init.cxx.
References cvFactoryRegistrar::GetFactoryMethodPtr(), and NULL.
Referenced by Solid_Init().
static int Solid_RemeshFaceMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4640 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, CV_OK, DOUBLE_Type, faces(), cvRepositoryData::GetName(), INT_Type, LIST_Type, nfaces, NULL, cvSolidModel::RemeshFace(), and REQUIRED.
Referenced by Solid_ObjectCmd().
static int Solid_RotateMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3296 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argv, CV_OK, DOUBLE_Type, cvRepositoryData::GetName(), LIST_Type, NULL, REQUIRED, and cvSolidModel::Rotate().
Referenced by Solid_ObjectCmd().
static int Solid_ScaleMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3352 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepositoryData::GetName(), NULL, REQUIRED, and cvSolidModel::Scale().
Referenced by Solid_ObjectCmd().
static int Solid_SetFaceAttrMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4341 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), INT_Type, NULL, REQUIRED, cvSolidModel::SetFaceAttribute(), and STRING_Type.
Referenced by Solid_ObjectCmd().
int Solid_SetKernelCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2866 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvSolidModel::gCurrentKernel, NULL, REQUIRED, SM_KT_INVALID, SolidModel_KernelT_EnumToStr(), SolidModel_KernelT_StrToEnum(), and STRING_Type.
Referenced by Solid_Init().
static int Solid_SetLabelMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4117 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepositoryData::IsLabelPresent(), NULL, REQUIRED, cvRepositoryData::SetLabel(), and STRING_Type.
Referenced by Solid_ObjectCmd().
static int Solid_SetRegionAttrMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 4424 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), INT_Type, NULL, REQUIRED, cvSolidModel::SetRegionAttribute(), and STRING_Type.
Referenced by Solid_ObjectCmd().
static int Solid_SetVtkPolyDataMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3713 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepository::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, cvSolidModel::SetVtkPolyDataObject(), and STRING_Type.
Referenced by Solid_ObjectCmd().
int Solid_SphereCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 929 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argv, CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, LIST_Type, cvSolidModel::MakeSphere(), NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_SubtractCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2540 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepository::GetType(), gRepository, NULL, cvRepository::Register(), REQUIRED, SM_Simplify_All, SM_Simplify_Invalid, SOLID_MODEL_T, Solid_ObjectCmd(), SolidModel_SimplifyT_EnumToStr(), SolidModel_SimplifyT_StrToEnum(), STRING_Type, and cvSolidModel::Subtract().
Referenced by Solid_Init().
int Solid_TorusCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1309 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, LIST_Type, cvSolidModel::MakeTorus(), NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
static int Solid_TranslateMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3242 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argv, CV_OK, DOUBLE_Type, cvRepositoryData::GetName(), LIST_Type, NULL, REQUIRED, and cvSolidModel::Translate().
Referenced by Solid_ObjectCmd().
int Solid_TruncatedConeCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1211 of file cv_solid_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), gRepository, LIST_Type, cvSolidModel::MakeTruncatedCone(), NULL, cvRepository::Register(), REQUIRED, Solid_ObjectCmd(), and STRING_Type.
Referenced by Solid_Init().
int Solid_UnionCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2430 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvSolidModel::DefaultInstantiateSolidModel(), DeleteSolid(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepository::GetType(), gRepository, NULL, cvRepository::Register(), REQUIRED, SM_Simplify_All, SM_Simplify_Invalid, SOLID_MODEL_T, Solid_ObjectCmd(), SolidModel_SimplifyT_EnumToStr(), SolidModel_SimplifyT_StrToEnum(), STRING_Type, and cvSolidModel::Union().
Referenced by Solid_Init().
static int Solid_WriteNativeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3567 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, GDSC_OPTIONAL, cvRepositoryData::GetName(), INT_Type, NULL, REQUIRED, STRING_Type, and cvSolidModel::WriteNative().
Referenced by Solid_ObjectCmd().
static int Solid_WriteVtkPolyDataMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 3609 of file cv_solid_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvSolidModel::WriteVtkPolyData().
Referenced by Solid_ObjectCmd().