simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/ITKCode/cv_itk_init.cxx File Reference
cv_itk_init.cxx File Reference
#include "SimVascular.h"
#include "vtkStructuredPoints.h"
#include "vtkSystemIncludes.h"
#include <vtkImageReslice.h>
#include <vtkImageConstantPad.h>
#include "a2itk.h"
#include "cv_misc_utils.h"
#include "cv_arg.h"
#include "cvRepository.h"
#include "cvStrPts.h"
#include "cv_itk_init.h"
#include "cv_globals.h"
Functions
int gdscITK_ReadRegionOfInterestCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscITK_MinMaxCurvSmoothCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscITK_SigMapCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscITK_FastMarchCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscITK_TLSF_Cmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscITK_createSignedDistanceImageWithFMMCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscITK_expNegativeImageCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int gdscITK_shapeDetectionCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
CV_DLL_EXPORT int Simvascularitk_Init (Tcl_Interp *interp)
template<typename PixelType >
static int TLSFTypeHelper (vtkStructuredPoints *sp, vtkStructuredPoints *spLset, Tcl_Interp *interp, double upper, double lower, double prop, double curv, int numIter, char *levelsetName)
template<typename PixelType1 , typename PixelType2 >
static int TLSFHelper (vtkStructuredPoints *sp, vtkStructuredPoints *spLset, Tcl_Interp *interp, double upper, double lower, double prop, double curv, int numIter, char *levelsetName)
template<typename PixelType >
static int FMMHelper (vtkStructuredPoints *sp, Tcl_Interp *interp, char *levelSetName, double start, double stop, int nlistpts, ARG_List *indpts, int npts, int table_sz, ARG_Entry arg_table[])
template<typename PixelType >
static int SigMapHelper (vtkStructuredPoints *sp, Tcl_Interp *interp, char *imageName, double min, double max, double alpha, double beta)
template<typename PixelType >
static int SmoothHelper (vtkStructuredPoints *sp, Tcl_Interp *interp, int numIter, int radius, double timeStep, char *imageName)
static void PadVtkStructuredPoints (vtkStructuredPoints *imageToPad, int padding, float fillValue)
template<typename PixelType >
static int ReadRegionHelper (vtkStructuredPoints *sp, Tcl_Interp *interp, int start[3], int dims[3], double spacing, char *imageName)
Function Documentation
template<typename PixelType > static int FMMHelper (vtkStructuredPoints * sp, Tcl_Interp * interp, char * levelSetName, double start, double stop, int nlistpts, ARG_List * indpts, int npts, int table_sz, ARG_Entry arg_table[]) static
Definition at line 285 of file cv_itk_init.cxx.
References ARG_FreeListArgvs(), ARG_ParseTclListStatic(), DOUBLE_Type, free(), cvRepositoryData::GetName(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput(), gRepository, a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkFmmFilter(), malloc(), NULL, cvRepository::Register(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::SEEDS_ARRAY_MAX, a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput1(), cvRepositoryData::SetName(), and cvRepository::UnRegister().
int gdscITK_createSignedDistanceImageWithFMMCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 955 of file cv_itk_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::createSignedDistanceImageWithFMM(), CV_ERROR, DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput(), gRepository, INT_Type, LIST_Type, NULL, cvRepository::Register(), REQUIRED, cvRepositoryData::SetName(), STRING_Type, and time.
Referenced by Simvascularitk_Init().
int gdscITK_expNegativeImageCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1153 of file cv_itk_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, cvRepository::Exists(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::expNegativeImageFilter(), cvRepositoryData::GetName(), cvRepository::GetObject(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput(), cvRepositoryData::GetType(), gRepository, NULL, cvRepository::Register(), REQUIRED, a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput1(), cvRepositoryData::SetName(), STRING_Type, and STRUCTURED_PTS_T.
Referenced by Simvascularitk_Init().
int gdscITK_FastMarchCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
gdscITK_FastMarchCmd
Definition at line 361 of file cv_itk_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, REQUIRED, STRING_Type, and STRUCTURED_PTS_T.
Referenced by Simvascularitk_Init().
int gdscITK_MinMaxCurvSmoothCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
gdscITK_MinMaxCurvSmoothCmd
Definition at line 630 of file cv_itk_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, NULL, REQUIRED, STRING_Type, and STRUCTURED_PTS_T.
Referenced by Simvascularitk_Init().
int gdscITK_ReadRegionOfInterestCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 853 of file cv_itk_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, LIST_Type, NULL, REQUIRED, STRING_Type, and STRUCTURED_PTS_T.
Referenced by Simvascularitk_Init().
int gdscITK_shapeDetectionCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1280 of file cv_itk_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput(), cvRepositoryData::GetType(), gRepository, INT_Type, NULL, cvRepository::Register(), REQUIRED, a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput1(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput2(), cvRepositoryData::SetName(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::shapeDetectionLevelSet(), STRING_Type, and STRUCTURED_PTS_T.
Referenced by Simvascularitk_Init().
int gdscITK_SigMapCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
gdscITK_SigMapCmd
Definition at line 505 of file cv_itk_init.cxx.
References alpha, ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, REQUIRED, STRING_Type, and STRUCTURED_PTS_T.
Referenced by Simvascularitk_Init().
int gdscITK_TLSF_Cmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
gdscITK_TLSF_Cmd
Definition at line 181 of file cv_itk_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, NULL, REQUIRED, STRING_Type, and STRUCTURED_PTS_T.
Referenced by Simvascularitk_Init().
static void PadVtkStructuredPoints (vtkStructuredPoints * imageToPad, int padding, float fillValue) static
Definition at line 707 of file cv_itk_init.cxx.
Referenced by ReadRegionHelper().
template<typename PixelType > static int ReadRegionHelper (vtkStructuredPoints * sp, Tcl_Interp * interp, int start[3], int dims[3], double spacing, char * imageName) static
Definition at line 795 of file cv_itk_init.cxx.
References free(), cvRepositoryData::GetName(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput(), gRepository, a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkRegionOfInterestFilter(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkResampleFilter(), malloc(), NULL, PadVtkStructuredPoints(), cvRepository::Register(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput1(), cvRepositoryData::SetName(), and cvRepository::UnRegister().
template<typename PixelType > static int SigMapHelper (vtkStructuredPoints * sp, Tcl_Interp * interp, char * imageName, double min, double max, double alpha, double beta) static
Definition at line 458 of file cv_itk_init.cxx.
References free(), cvRepositoryData::GetName(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput(), gRepository, a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkSigMapFilter(), malloc(), NULL, cvRepository::Register(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput1(), cvRepositoryData::SetName(), and cvRepository::UnRegister().
CV_DLL_EXPORT int Simvascularitk_Init (Tcl_Interp * interp)
Definition at line 88 of file cv_itk_init.cxx.
References gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_expNegativeImageCmd(), gdscITK_FastMarchCmd(), gdscITK_MinMaxCurvSmoothCmd(), gdscITK_ReadRegionOfInterestCmd(), gdscITK_shapeDetectionCmd(), gdscITK_SigMapCmd(), gdscITK_TLSF_Cmd(), and NULL.
template<typename PixelType > static int SmoothHelper (vtkStructuredPoints * sp, Tcl_Interp * interp, int numIter, int radius, double timeStep, char * imageName) static
Definition at line 587 of file cv_itk_init.cxx.
References free(), cvRepositoryData::GetName(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput(), gRepository, a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkMinMaxCurvFlowFilter(), malloc(), NULL, cvRepository::Register(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput1(), cvRepositoryData::SetName(), and cvRepository::UnRegister().
template<typename PixelType1 , typename PixelType2 > static int TLSFHelper (vtkStructuredPoints * sp, vtkStructuredPoints * spLset, Tcl_Interp * interp, double upper, double lower, double prop, double curv, int numIter, char * levelsetName) static
Definition at line 132 of file cv_itk_init.cxx.
References free(), cvRepositoryData::GetName(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::getOutput(), gRepository, a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::itkThresholdLevelSet(), malloc(), NULL, cvRepository::Register(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput1(), a2itk< Ta2itkDim, InputPixelType1, InputPixelType2, OutputPixelType >::setInput2(), cvRepositoryData::SetName(), and cvRepository::UnRegister().
template<typename PixelType > static int TLSFTypeHelper (vtkStructuredPoints * sp, vtkStructuredPoints * spLset, Tcl_Interp * interp, double upper, double lower, double prop, double curv, int numIter, char * levelsetName) static
Definition at line 111 of file cv_itk_init.cxx.