simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/cv_spline.cxx File Reference
cv_spline.cxx File Reference
#include "SimVascular.h"
#include "cv_misc_utils.h"
#include <stdio.h>
#include <math.h>
#include "cvVTK.h"
#include "cv_spline.h"
Functions
int sys_geom_splinePtsToPathPlan (vtkPolyData *pd, int numOutputPts, char *filename, int flag, Tcl_Interp *interp)
SplinePoints * sys_geom_SplinePointsInit (int numPts, int dimensions)
void sys_geom_SplinePointsDelete (SplinePoints *sp)
void sys_geom_SplineInterpolate (SplinePoints *input, int type, int numberOfOutputPoints, SplinePoints *output)
int sys_geom_SplineGetTangents (SplinePoints *input, int type, int numberOfOutputPoints, int matchEndPoints, SplinePoints *output)
void sys_geom_SplineGetRotVectors (SplinePoints *input)
int sys_geom_NormalizeVector (vtkFloatingPointType *input, vtkFloatingPointType *output, int sizeVector)
int sys_geom_SplinePath (SplinePoints *input, int type, int numOutputPts, int matchEndPoints, SplinePoints *output)
Function Documentation
int sys_geom_NormalizeVector (vtkFloatingPointType * input, vtkFloatingPointType * output, int sizeVector)
Definition at line 458 of file cv_spline.cxx.
Referenced by sys_geom_SplineGetRotVectors(), and sys_geom_SplineGetTangents().
void sys_geom_SplineGetRotVectors (SplinePoints * input)
Definition at line 395 of file cv_spline.cxx.
References _SplinePoints::dim, MAX_DIM, _SplinePoints::numPts, _SplinePoints::rotVectors, sys_geom_NormalizeVector(), and _SplinePoints::tangents.
Referenced by sys_geom_SplinePath().
int sys_geom_SplineGetTangents (SplinePoints * input, int type, int numberOfOutputPoints, int matchEndPoints, SplinePoints * output)
Definition at line 254 of file cv_spline.cxx.
References CV_ERROR, CV_OK, _SplinePoints::dim, MAX_DIM, _SplinePoints::numPts, _SplinePoints::pts, sys_geom_NormalizeVector(), sys_geom_SplineInterpolate(), sys_geom_SplinePointsDelete(), sys_geom_SplinePointsInit(), and _SplinePoints::tangents.
Referenced by sys_geom_SplinePath().
void sys_geom_SplineInterpolate (SplinePoints * input, int type, int numberOfOutputPoints, SplinePoints * output)
Definition at line 164 of file cv_spline.cxx.
References _SplinePoints::dim, MAX_DIM, _SplinePoints::numPts, and _SplinePoints::pts.
Referenced by sys_geom_SplineGetTangents().
int sys_geom_SplinePath (SplinePoints * input, int type, int numOutputPts, int matchEndPoints, SplinePoints * output)
Definition at line 498 of file cv_spline.cxx.
References CV_ERROR, CV_OK, sys_geom_SplineGetRotVectors(), and sys_geom_SplineGetTangents().
Referenced by sys_geom_splinePtsToPathPlan().
void sys_geom_SplinePointsDelete (SplinePoints * sp)
Definition at line 146 of file cv_spline.cxx.
References _SplinePoints::pts, _SplinePoints::rotVectors, and _SplinePoints::tangents.
Referenced by sys_geom_SplineGetTangents(), and sys_geom_splinePtsToPathPlan().
SplinePoints* sys_geom_SplinePointsInit (int numPts, int dimensions)
Definition at line 114 of file cv_spline.cxx.
References _SplinePoints::dim, _SplinePoints::numPts, _SplinePoints::pts, _SplinePoints::rotVectors, and _SplinePoints::tangents.
Referenced by sys_geom_SplineGetTangents(), and sys_geom_splinePtsToPathPlan().
int sys_geom_splinePtsToPathPlan (vtkPolyData * pd, int numOutputPts, char * filename, int flag, Tcl_Interp * interp)
Definition at line 39 of file cv_spline.cxx.
References CV_ERROR, CV_OK, _SplinePoints::dim, NULL, _SplinePoints::numPts, _SplinePoints::pts, _SplinePoints::rotVectors, sys_geom_SplinePath(), sys_geom_SplinePointsDelete(), sys_geom_SplinePointsInit(), and _SplinePoints::tangents.
Referenced by Geom_SplinePtsToPathPlanCmd().