simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/LevelSet/cv_LsetV_init.cxx File Reference
cv_LsetV_init.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include <string.h>
#include "cv_LsetV_init.h"
#include "cvLevelSetVelocity.h"
#include "cvLevelSetVelocityImage.h"
#include "cvLevelSetVelocityKGI.h"
#include "cvLevelSetVelocityConstant.h"
#include "cvRepository.h"
#include "cvLevelSetVelocityThreshold.h"
#include "cvLevelSetVelocityPotential.h"
#include "cvLevelSetVelocityExponentialDecay.h"
#include "cvLevelSetVelocitySmooth.h"
#include "cv_arg.h"
#include "cv_misc_utils.h"
#include "cv_vtk_utils.h"
#include "cv_globals.h"
Functions
int LsetVKGI_NewCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVConst_NewCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVThr_NewCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVPotential_NewCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVExpDecay_NewCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVSmooth_NewCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
void DeleteLsetV (ClientData clientData)
int LsetV_ListInstancesCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVKGI_ListMethodsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVConst_ListMethodsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVThr_ListMethodsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVPotential_ListMethodsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVExpDecay_ListMethodsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVSmooth_ListMethodsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetV_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVImage_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVKGI_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVConst_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVThr_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVPotential_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVExpDecay_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int LsetVSmooth_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetV_SetStopVMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetV_GetStopVMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetV_GetMemoryUsageMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVImage_SetImageObjMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVImage_GetImageObjMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVImage_SetImageMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVImage_GetImageMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVImage_GetMagGradRangeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVImage_GetXYMagGradRangeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVImage_GetZMagGradRangeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVImage_GetIntensityRangeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVKGI_SetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVKGI_GetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVConst_SetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVConst_GetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVThr_SetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVThr_GetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVPotential_SetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVPotential_GetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVExpDecay_SetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVExpDecay_GetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVSmooth_SetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int LsetVSmooth_GetConstMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int NewName (CONST84 char *name, Tcl_Interp *interp)
static void PrintMethods_V ()
static void PrintMethods_VImage ()
static void PrintMethods_VKGI ()
static void PrintMethods_VConst ()
static void PrintMethods_VThr ()
static void PrintMethods_VPotential ()
static void PrintMethods_VExpDecay ()
static void PrintMethods_VSmooth ()
int Lsetv_Init (Tcl_Interp *interp)
Function Documentation
void DeleteLsetV (ClientData clientData)
Definition at line 660 of file cv_LsetV_init.cxx.
References gLsetVTable, NULL, and cvLevelSetVelocity::tclName_.
Referenced by LsetVConst_NewCmd(), LsetVExpDecay_NewCmd(), LsetVKGI_NewCmd(), LsetVPotential_NewCmd(), LsetVSmooth_NewCmd(), and LsetVThr_NewCmd().
int LsetV_GetMemoryUsageMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1041 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), cvLevelSetVelocity::GetMemoryUsage(), NULL, and vel.
Referenced by LsetV_ObjectCmd().
int LsetV_GetStopVMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1013 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), cvLevelSetVelocity::GetStopV(), NULL, and vel.
Referenced by LsetV_ObjectCmd().
int Lsetv_Init (Tcl_Interp * interp)
Definition at line 296 of file cv_LsetV_init.cxx.
References gLsetVTable, LsetV_ListInstancesCmd(), LsetVConst_NewCmd(), LsetVExpDecay_NewCmd(), LsetVKGI_ListMethodsCmd(), LsetVKGI_NewCmd(), LsetVPotential_NewCmd(), LsetVSmooth_NewCmd(), LsetVThr_NewCmd(), and NULL.
Referenced by SimVascular_Init().
int LsetV_ListInstancesCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 792 of file cv_LsetV_init.cxx.
References gLsetVTable, and NULL.
Referenced by Lsetv_Init().
int LsetV_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 933 of file cv_LsetV_init.cxx.
References LsetV_GetMemoryUsageMtd(), LsetV_GetStopVMtd(), LsetV_SetStopVMtd(), NULL, and PrintMethods_V().
Referenced by LsetVConst_ObjectCmd(), LsetVImage_ObjectCmd(), and LsetVSmooth_ObjectCmd().
int LsetV_SetStopVMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 976 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, NULL, REQUIRED, cvLevelSetVelocity::SetStopV(), and vel.
Referenced by LsetV_ObjectCmd().
static int LsetVConst_GetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1710 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, CV_STRLEN, cvLevelSetVelocityConstant::GetV(), NULL, and vel.
Referenced by LsetVConst_ObjectCmd().
int LsetVConst_ListMethodsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 699 of file cv_LsetV_init.cxx.
References NULL, PrintMethods_V(), and PrintMethods_VConst().
int LsetVConst_NewCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 388 of file cv_LsetV_init.cxx.
References DeleteLsetV(), gLsetVTable, LsetVConst_ObjectCmd(), NewName(), NULL, and cvLevelSetVelocity::tclName_.
Referenced by Lsetv_Init().
int LsetVConst_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1638 of file cv_LsetV_init.cxx.
References LsetV_ObjectCmd(), LsetVConst_GetConstMtd(), LsetVConst_SetConstMtd(), PrintMethods_V(), and PrintMethods_VConst().
Referenced by LsetVConst_NewCmd().
static int LsetVConst_SetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1674 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, NULL, REQUIRED, cvLevelSetVelocityConstant::SetV(), and vel.
Referenced by LsetVConst_ObjectCmd().
static int LsetVExpDecay_GetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2114 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, CV_STRLEN, DKT_EnumToStr(), cvLevelSetVelocityExponentialDecay::Get3DKType(), cvLevelSetVelocityExponentialDecay::GetClamp(), cvLevelSetVelocityExponentialDecay::GetEI(), cvLevelSetVelocityExponentialDecay::GetEIneg(), cvLevelSetVelocityExponentialDecay::GetExpand(), cvLevelSetVelocityExponentialDecay::GetKt(), cvLevelSetVelocityExponentialDecay::GetMonotonic(), and NULL.
Referenced by LsetVExpDecay_ObjectCmd().
int LsetVExpDecay_ListMethodsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 755 of file cv_LsetV_init.cxx.
References NULL, PrintMethods_V(), PrintMethods_VExpDecay(), and PrintMethods_VImage().
int LsetVExpDecay_NewCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 550 of file cv_LsetV_init.cxx.
References DeleteLsetV(), gLsetVTable, LsetVExpDecay_ObjectCmd(), NewName(), NULL, and cvLevelSetVelocity::tclName_.
Referenced by Lsetv_Init().
int LsetVExpDecay_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2006 of file cv_LsetV_init.cxx.
References LsetVExpDecay_GetConstMtd(), LsetVExpDecay_SetConstMtd(), LsetVImage_ObjectCmd(), PrintMethods_V(), PrintMethods_VExpDecay(), and PrintMethods_VImage().
Referenced by LsetVExpDecay_NewCmd().
static int LsetVExpDecay_SetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2045 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), BOOL_Type, CV_OK, DOUBLE_Type, GDSC_OPTIONAL, NULL, REQUIRED, cvLevelSetVelocityExponentialDecay::Set3DKType(), cvLevelSetVelocityExponentialDecay::SetClamp(), cvLevelSetVelocityExponentialDecay::SetEI(), cvLevelSetVelocityExponentialDecay::SetEIneg(), cvLevelSetVelocityExponentialDecay::SetExpand(), cvLevelSetVelocityExponentialDecay::SetKt(), and STRING_Type.
Referenced by LsetVExpDecay_ObjectCmd().
static int LsetVImage_GetImageMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2275 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_STRLEN, Image_T::filebase, Image_T::fileNumRange, cvLevelSetVelocityImage::GetImage(), Image_T::imgDims, NULL, and Image_T::pixelDims.
Referenced by LsetVImage_ObjectCmd().
int LsetVImage_GetImageObjMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1201 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvLevelSetVelocityImage::GetImage(), cvRepositoryData::GetName(), gRepository, Image_T::imgDims, Pixel_T::intensity, NULL, Image_T::pixelDims, Image_T::pixels, cvRepository::Register(), REQUIRED, cvRepositoryData::SetName(), and STRING_Type.
Referenced by LsetVImage_ObjectCmd().
static int LsetVImage_GetIntensityRangeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1603 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, cvLevelSetVelocityImage::GetIntensityRange(), and NULL.
Referenced by LsetVImage_ObjectCmd().
static int LsetVImage_GetMagGradRangeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1507 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, cvLevelSetVelocityImage::GetMagGradRange(), and NULL.
Referenced by LsetVImage_ObjectCmd().
static int LsetVImage_GetXYMagGradRangeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1539 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, cvLevelSetVelocityImage::GetXYMagGradRange(), and NULL.
Referenced by LsetVImage_ObjectCmd().
static int LsetVImage_GetZMagGradRangeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1571 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, cvLevelSetVelocityImage::GetZMagGradRange(), and NULL.
Referenced by LsetVImage_ObjectCmd().
int LsetVImage_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1282 of file cv_LsetV_init.cxx.
References LsetV_ObjectCmd(), LsetVImage_GetImageMtd(), LsetVImage_GetImageObjMtd(), LsetVImage_GetIntensityRangeMtd(), LsetVImage_GetMagGradRangeMtd(), LsetVImage_GetXYMagGradRangeMtd(), LsetVImage_GetZMagGradRangeMtd(), LsetVImage_SetImageMtd(), and LsetVImage_SetImageObjMtd().
Referenced by LsetVExpDecay_ObjectCmd(), LsetVKGI_ObjectCmd(), LsetVPotential_ObjectCmd(), and LsetVThr_ObjectCmd().
static int LsetVImage_SetImageMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2184 of file cv_LsetV_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, INT_Type, LIST_Type, NULL, REQUIRED, cvLevelSetVelocityImage::SetImage(), and STRING_Type.
Referenced by LsetVImage_ObjectCmd().
int LsetVImage_SetImageObjMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1071 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, GDSC_OPTIONAL, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, NULL, REQUIRED, cvLevelSetVelocityImage::SetImage(), STRING_Type, STRUCTURED_PTS_T, VtkUtils_MakeFloatArray(), and VtkUtils_MakeShortArray().
Referenced by LsetVImage_ObjectCmd().
static int LsetVKGI_GetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1447 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, CV_STRLEN, cvLevelSetVelocityKGI::GetApplyLocalStop(), cvLevelSetVelocityKGI::GetBalloonF(), cvLevelSetVelocityKGI::GetBeta(), cvLevelSetVelocityKGI::GetEI(), cvLevelSetVelocityKGI::GetEK(), cvLevelSetVelocityKGI::GetGradIPow(), and NULL.
Referenced by LsetVKGI_ObjectCmd().
int LsetVKGI_ListMethodsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 680 of file cv_LsetV_init.cxx.
References NULL, PrintMethods_V(), PrintMethods_VImage(), and PrintMethods_VKGI().
Referenced by Lsetv_Init().
int LsetVKGI_NewCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 332 of file cv_LsetV_init.cxx.
References DeleteLsetV(), gLsetVTable, LsetVKGI_ObjectCmd(), NewName(), NULL, and cvLevelSetVelocity::tclName_.
Referenced by Lsetv_Init().
int LsetVKGI_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1339 of file cv_LsetV_init.cxx.
References LsetVImage_ObjectCmd(), LsetVKGI_GetConstMtd(), LsetVKGI_SetConstMtd(), PrintMethods_V(), PrintMethods_VImage(), and PrintMethods_VKGI().
Referenced by LsetVKGI_NewCmd().
static int LsetVKGI_SetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1376 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, GDSC_OPTIONAL, INT_Type, NULL, REQUIRED, cvLevelSetVelocityKGI::SetApplyLocalStop(), cvLevelSetVelocityKGI::SetBalloonF(), cvLevelSetVelocityKGI::SetBeta(), cvLevelSetVelocityKGI::SetEI(), cvLevelSetVelocityKGI::SetEK(), and cvLevelSetVelocityKGI::SetGradIPow().
Referenced by LsetVKGI_ObjectCmd().
static int LsetVPotential_GetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1963 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_STRLEN, cvLevelSetVelocityPotential::GetBalloonF(), cvLevelSetVelocityPotential::GetEK(), cvLevelSetVelocityPotential::GetEP(), cvLevelSetVelocityPotential::GetKlow(), cvLevelSetVelocityPotential::GetKupp(), and NULL.
Referenced by LsetVPotential_ObjectCmd().
int LsetVPotential_ListMethodsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 736 of file cv_LsetV_init.cxx.
References NULL, PrintMethods_V(), PrintMethods_VImage(), and PrintMethods_VPotential().
int LsetVPotential_NewCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 496 of file cv_LsetV_init.cxx.
References DeleteLsetV(), gLsetVTable, LsetVPotential_ObjectCmd(), NewName(), NULL, and cvLevelSetVelocity::tclName_.
Referenced by Lsetv_Init().
int LsetVPotential_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1855 of file cv_LsetV_init.cxx.
References LsetVImage_ObjectCmd(), LsetVPotential_GetConstMtd(), LsetVPotential_SetConstMtd(), PrintMethods_V(), PrintMethods_VImage(), and PrintMethods_VPotential().
Referenced by LsetVPotential_NewCmd().
static int LsetVPotential_SetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1894 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, GDSC_OPTIONAL, NULL, REQUIRED, cvLevelSetVelocityPotential::SetEK(), cvLevelSetVelocityPotential::SetEP(), cvLevelSetVelocityPotential::SetKlow(), and cvLevelSetVelocityPotential::SetKupp().
Referenced by LsetVPotential_ObjectCmd().
static int LsetVSmooth_GetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2403 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, CV_STRLEN, cvLevelSetVelocitySmooth::Get3DKType(), cvLevelSetVelocitySmooth::GetKts(), KT_EnumToStr(), and NULL.
Referenced by LsetVSmooth_ObjectCmd().
int LsetVSmooth_ListMethodsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 774 of file cv_LsetV_init.cxx.
References NULL, PrintMethods_V(), and PrintMethods_VSmooth().
int LsetVSmooth_NewCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 604 of file cv_LsetV_init.cxx.
References DeleteLsetV(), gLsetVTable, LsetVSmooth_ObjectCmd(), NewName(), NULL, and cvLevelSetVelocity::tclName_.
Referenced by Lsetv_Init().
int LsetVSmooth_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2320 of file cv_LsetV_init.cxx.
References LsetV_ObjectCmd(), LsetVSmooth_GetConstMtd(), LsetVSmooth_SetConstMtd(), PrintMethods_V(), and PrintMethods_VSmooth().
Referenced by LsetVSmooth_NewCmd().
static int LsetVSmooth_SetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2358 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, GDSC_OPTIONAL, NULL, REQUIRED, cvLevelSetVelocitySmooth::Set3DKType(), cvLevelSetVelocitySmooth::SetKts(), and STRING_Type.
Referenced by LsetVSmooth_ObjectCmd().
static int LsetVThr_GetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1820 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), CV_OK, CV_STRLEN, cvLevelSetVelocityThreshold::GetBalloonF(), cvLevelSetVelocityThreshold::GetThreshold(), and NULL.
Referenced by LsetVThr_ObjectCmd().
int LsetVThr_ListMethodsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 717 of file cv_LsetV_init.cxx.
References NULL, PrintMethods_V(), PrintMethods_VImage(), and PrintMethods_VThr().
int LsetVThr_NewCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 442 of file cv_LsetV_init.cxx.
References DeleteLsetV(), gLsetVTable, LsetVThr_ObjectCmd(), NewName(), NULL, and cvLevelSetVelocity::tclName_.
Referenced by Lsetv_Init().
int LsetVThr_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1741 of file cv_LsetV_init.cxx.
References LsetVImage_ObjectCmd(), LsetVThr_GetConstMtd(), LsetVThr_SetConstMtd(), PrintMethods_V(), PrintMethods_VImage(), and PrintMethods_VThr().
Referenced by LsetVThr_NewCmd().
static int LsetVThr_SetConstMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1778 of file cv_LsetV_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, NULL, REQUIRED, cvLevelSetVelocityThreshold::SetBalloonF(), and cvLevelSetVelocityThreshold::SetThreshold().
Referenced by LsetVThr_ObjectCmd().
static int NewName (CONST84 char * name, Tcl_Interp * interp) static
Definition at line 268 of file cv_LsetV_init.cxx.
References NULL.
Referenced by LsetVConst_NewCmd(), LsetVExpDecay_NewCmd(), LsetVKGI_NewCmd(), LsetVPotential_NewCmd(), LsetVSmooth_NewCmd(), and LsetVThr_NewCmd().
static void PrintMethods_V () static
Definition at line 816 of file cv_LsetV_init.cxx.
Referenced by LsetV_ObjectCmd(), LsetVConst_ListMethodsCmd(), LsetVConst_ObjectCmd(), LsetVExpDecay_ListMethodsCmd(), LsetVExpDecay_ObjectCmd(), LsetVKGI_ListMethodsCmd(), LsetVKGI_ObjectCmd(), LsetVPotential_ListMethodsCmd(), LsetVPotential_ObjectCmd(), LsetVSmooth_ListMethodsCmd(), LsetVSmooth_ObjectCmd(), LsetVThr_ListMethodsCmd(), and LsetVThr_ObjectCmd().
static void PrintMethods_VConst () static
Definition at line 863 of file cv_LsetV_init.cxx.
Referenced by LsetVConst_ListMethodsCmd(), and LsetVConst_ObjectCmd().
static void PrintMethods_VExpDecay () static
Definition at line 905 of file cv_LsetV_init.cxx.
Referenced by LsetVExpDecay_ListMethodsCmd(), and LsetVExpDecay_ObjectCmd().
static void PrintMethods_VImage () static
Definition at line 831 of file cv_LsetV_init.cxx.
Referenced by LsetVExpDecay_ListMethodsCmd(), LsetVExpDecay_ObjectCmd(), LsetVKGI_ListMethodsCmd(), LsetVKGI_ObjectCmd(), LsetVPotential_ListMethodsCmd(), LsetVPotential_ObjectCmd(), LsetVThr_ListMethodsCmd(), and LsetVThr_ObjectCmd().
static void PrintMethods_VKGI () static
Definition at line 849 of file cv_LsetV_init.cxx.
Referenced by LsetVKGI_ListMethodsCmd(), and LsetVKGI_ObjectCmd().
static void PrintMethods_VPotential () static
Definition at line 891 of file cv_LsetV_init.cxx.
Referenced by LsetVPotential_ListMethodsCmd(), and LsetVPotential_ObjectCmd().
static void PrintMethods_VSmooth () static
Definition at line 919 of file cv_LsetV_init.cxx.
Referenced by LsetVSmooth_ListMethodsCmd(), and LsetVSmooth_ObjectCmd().
static void PrintMethods_VThr () static
Definition at line 877 of file cv_LsetV_init.cxx.
Referenced by LsetVThr_ListMethodsCmd(), and LsetVThr_ObjectCmd().