simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Plugins/VMTK/cv_VMTK_utils.cxx File Reference
cv_VMTK_utils.cxx File Reference
#include "cv_VMTK_utils.h"
#include "SimVascular.h"
#include "vtkMath.h"
#include "vtkPolyData.h"
#include "vtkSmartPointer.h"
#include "vtkTriangleFilter.h"
#include "vtkDecimatePro.h"
#include "vtkCleanPolyData.h"
#include "vtkCellData.h"
#include "vtkPolyDataNormals.h"
#include "vtkPointData.h"
#include "vtkIntArray.h"
#include "vtkDoubleArray.h"
#include "vtkThreshold.h"
#include "vtkDataSetSurfaceFilter.h"
#include "vtkGeometryFilter.h"
#include "vtkCellArray.h"
#include "vtkvmtkPolyDataSurfaceRemeshing.h"
#include "vtkvmtkPolyDataSizingFunction.h"
#include "vtkvmtkSurfaceProjection.h"
#include "vtkvmtkCapPolyData.h"
#include "vtkvmtkSimpleCapPolyData.h"
#include "vtkvmtkAppendFilter.h"
#include "vtkvmtkBoundaryLayerGenerator.h"
#include "cv_polydatasolid_utils.h"
Functions
int VMTKUtils_SurfaceRemeshing (vtkPolyData *surfaceMesh, double maxEdgeSize, int meshcapsonly, int preserveedges, double trianglesplitfactor, double collapseanglethreshold, vtkIdList *excludedIds, std::string cellEntityIdsArrayName, int useSizingFunction, vtkDoubleArray *meshSizingFunction)
Function to remesh a surface.
int VMTKUtils_ComputeSizingFunction (vtkPolyData *inpd, double scalefactor, std::string sizingFunctionArrayName)
Function to compute a sizing function of the current mesh. This is a function describing the size of the mesh at each location.
int VMTKUtils_Capper (vtkPolyData *inpd, int captype, int trioutput, int cellEntityIdOffset, std::string cellEntityIdsArrayName)
Function to cap or fill the holes of a vtkPolyData.
int VMTKUtils_BoundaryLayerMesh (vtkUnstructuredGrid *blMesh, vtkUnstructuredGrid *innerSurface, double edgeSize, double blThicknessFactor, int numSublayers, double sublayerRatio, int sidewallCellEntityId, int innerSurfaceCellEntityId, int negateWarpVectors, std::string cellEntityIdsArrayName)
Function to compute the boundary layer on a mesh.
int VMTKUtils_AppendMesh (vtkUnstructuredGrid *meshFromTetGen, vtkUnstructuredGrid *innerMesh, vtkUnstructuredGrid *boundaryMesh, vtkUnstructuredGrid *surfaceWithSize, std::string cellEntityIdsArrayName)
Function append the final combined boundary layer mesh with the volume mesh.
int VMTKUtils_InsertIds (vtkUnstructuredGrid *fullmesh, vtkPolyData *fullpolydata)
Function to attached GlobalElementIDs and GlobalNodeIDs to the final boundary layer mesh. The original values are destroyed by the complex process, so the values are reassigned.
Function Documentation
int VMTKUtils_AppendMesh (vtkUnstructuredGrid * meshFromTetGen, vtkUnstructuredGrid * innerMesh, vtkUnstructuredGrid * boundaryMesh, vtkUnstructuredGrid * surfaceWithSize, std::string cellEntityIdsArrayName)
Function append the final combined boundary layer mesh with the volume mesh.
Parameters
meshFromTetGen This is the full vtu output from TetGen
innerMesh This is the original inner surface extracted from the interior of the boundary layer mesh
boundaryMesh This is the actual boundary layer mesh
surfaceWithSize This is the surface input to tetgen with the mesh sizing function attached to it.
This is the name of the array within the surfaceWithSize mesh that contains the values pertaining to whehter or not it is a capped surface or not.
Returns
CV_OK if the meshes are appended into one final mesh correctly. The full mesh is returned in the first argument
Definition at line 493 of file cv_VMTK_utils.cxx.
References CV_OK.
int VMTKUtils_BoundaryLayerMesh (vtkUnstructuredGrid * blMesh, vtkUnstructuredGrid * innerSurface, double edgeSize, double blThicknessFactor, int numSublayers, double sublayerRatio, int sidewallCellEntityId, int innerSurfaceCellEntityId, int negateWarpVectors, std::string cellEntityIdsArrayName)
Function to compute the boundary layer on a mesh.
Parameters
blMesh This is the returned boundary layer mesh as a vtu
innerSurface This is the inner surface of the final bl mesh
edgeSize This is the desired edge size for the bl mesh
blThicknessFactor This is the portion of the edge size that you would like to be used for the thickness of the boundary layer
numSublayers This is the number of layers in the bl mesh.
sublayerRation This is the ratio at which to decrease the bl mesh by.
sidewallCellEntityId This is the value to assign to the tets that align along the sidewall of the final bl mesh
innerSurfaceCellEntityId This is the value assigned to the inner surface of the bl mesh
negateWarpVectors This is whether or not to use the current vector direction or use the exact opposite. Typically this is 1 because you use the normals as the direction and you would like the bl mesh to go inward (normals are typically oriented outward).
cellEntityIdsArrayName This is the name of the array given to the nodes of the output mesh.
Returns
CV_OK if the boundary layer mesh is created properly
Definition at line 404 of file cv_VMTK_utils.cxx.
References CV_ERROR, CV_OK, and NULL.
int VMTKUtils_Capper (vtkPolyData * inpd, int captype, int trioutput, int cellEntityIdOffset, std::string cellEntityIdsArrayName)
Function to cap or fill the holes of a vtkPolyData.
Parameters
*inpd This is the vtkPolyData to apply the filter
captype This is the type of cap desired. 0 is used for a basic or simple cap. 1 is used if you would like a cap with a point in the center of the holes.
trioutput This is boolean telling whether to make sure the output caps have only triangles or not.
cellEntityIdOffset This is used if an offset from surface is desire
cellEntityIdsArrayName This is the name given if offset is desired
Returns
CV_OK if the mesh sizing function based on the circle is computed correctly
Definition at line 305 of file cv_VMTK_utils.cxx.
References CV_OK, and NULL.
int VMTKUtils_ComputeSizingFunction (vtkPolyData * inpd, double scalefactor, std::string sizingFunctionArrayName)
Function to compute a sizing function of the current mesh. This is a function describing the size of the mesh at each location.
Parameters
*inpd This is the input vtkPolyData to compute the funciton on.
scalefactor This is to scale the output by some factor if necessary Default is 1.2.
sizingFunctionArrayName This is the array name given to the output sizing function attached to the mesh.
Returns
CV_OK if the sizing function is computed correctly.
Definition at line 262 of file cv_VMTK_utils.cxx.
References CV_OK, and NULL.
int VMTKUtils_InsertIds (vtkUnstructuredGrid * fullmesh, vtkPolyData * fullpolydata)
Function to attached GlobalElementIDs and GlobalNodeIDs to the final boundary layer mesh. The original values are destroyed by the complex process, so the values are reassigned.
Parameters
fullmesh This is the full volumetric mesh output by TetGen, VMTK, and custom procedures.
fullpolydata This should be empty coming in. It is then the extracted surface from the fullmesh.
Returns
CV_OK if the Ids are attached to the surfaces without issue
Definition at line 539 of file cv_VMTK_utils.cxx.
References c, Cross(), CV_OK, and Dot().
int VMTKUtils_SurfaceRemeshing (vtkPolyData * surfaceMesh, double maxEdgeSize, int meshcapsonly, int preserveedges, double trianglesplitfactor, double collapseanglethreshold, vtkIdList * excludedIds, std::string cellEntityIdsArrayName, int useSizingFunction, vtkDoubleArray * meshSizingFunction)
Function to remesh a surface.
Parameters
*surfaceMesh this is the current discrete polydata surface to be remeshed. It is also the new returen surface remesh
maxEdgeSize This is the edge size that would like to be targeted for the surface remesh
meshcapsonly This is boolean on whether the whole mesh should be meshed or just caps. If meshcapsonly is 1, then you must provide a list of excluded ids in the *excludedIds param.
preservedges This is a boolean on whether the feature edges should be preserved or not. In most cases, this is 1.
trianglesplit factor. This is just the value for a split triangle when it must be split. Default is 1.0.
collapseanglethreshold. This is the angle at which a triangle is bad triangle and should be collapsed. Default is 0.5.
*excludedIds These are the excluded regions if meshcapsonly is specified.
cellEntityIdsArrayName This is the array name assigned to the nodes of the output surface remesh
useSizingFunction This is if we want to specify a distance at each node for the mesh. Used for mesh refinement!
*meshSizingFunction This is the actual meshSizing Function. Must exist if using a sizing function
Returns
CV_OK is executed correctly. If something goes wrong, CV_ERROR is returned
Definition at line 100 of file cv_VMTK_utils.cxx.
References CV_ERROR, CV_OK, e16, and NULL.
Referenced by cvTetGenMeshObject::GenerateSurfaceRemesh(), and cvPolyDataSolid::RemeshFace().