simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Geometry/cv_geom_init.cxx File Reference
cv_geom_init.cxx File Reference
#include "SimVascular.h"
#include <stdio.h>
#include <string.h>
#include "cvRepository.h"
#include "cvRepositoryData.h"
#include "cvPolyData.h"
#include "cv_geom_init.h"
#include "cv_sys_geom.h"
#include "cv_integrate_surface.h"
#include "cv_arg.h"
#include "cv_misc_utils.h"
#include "cv_globals.h"
Functions
int Geom_ReduceCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_MakePolysConsistentCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_ReverseAllCellsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_NumClosedLineRegionsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_GetClosedLineRegionCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_PickCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_OrientProfileCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_DisorientProfileCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_AlignProfileCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_TranslateCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_ScaleAvgCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_GetOrderedPtsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_WriteOrderedPtsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_WriteLinesCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_PolysClosedCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_SurfAreaCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_GetPolyCentroidCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_PrintTriStatsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_PrintSmallPolysCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_RmSmallPolysCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_BBoxCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_ClassifyCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_PtInPolyCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_MergePtsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_Warp3dPtsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_NumPtsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_sampleLoopCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_2dWindingNumCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_PolygonNormCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_AvgPtCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_CopyCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_ProjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_ReorderPgnCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_SplinePtsToPathPlanCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_IntegrateSurfaceCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_IntegrateSurface2Cmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_IntegrateEnergyCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_FindDistanceCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_InterpolateScalarCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_InterpolateVectorCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_IntersectWithLineCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_AddPointDataCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_SubtractPointDataCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_MultiplyPointDataCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_DividePointDataCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_IntegrateScalarSurfCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_IntegrateScalarThreshCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_ReplacePointDataCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_UnionCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_IntersectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_SubtractCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_CheckSurfaceCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int Geom_Init (Tcl_Interp *interp)
Function Documentation
int Geom_2dWindingNumCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2873 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_2DWindingNum().
Referenced by Geom_Init().
int Geom_AddPointDataCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3797 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), BOOL_Type, CV_OK, cvRepository::Exists(), FALSE, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, SYS_GEOM_ADD_SCALAR, SYS_GEOM_ADD_VECTOR, sys_geom_mathPointData(), SYS_GEOM_NO_SCALAR, and SYS_GEOM_NO_VECTOR.
Referenced by Geom_Init().
int Geom_AlignProfileCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1614 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), BOOL_Type, cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, sys_geom_Align(), and sys_geom_AlignByDist().
Referenced by Geom_Init().
int Geom_AvgPtCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2985 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_AvgPt().
Referenced by Geom_Init().
int Geom_BBoxCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2397 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, CV_STRLEN, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_BBox().
Referenced by Geom_Init().
int Geom_CheckSurfaceCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 718 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), gRepository, NULL, REQUIRED, STRING_Type, and sys_geom_checksurface().
Referenced by Geom_Init().
int Geom_ClassifyCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2456 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_Classify().
Referenced by Geom_Init().
int Geom_CopyCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3043 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_DeepCopy().
Referenced by Geom_Init().
int Geom_DisorientProfileCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1506 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_DisorientProfile().
Referenced by Geom_Init().
int Geom_DividePointDataCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 4106 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), BOOL_Type, CV_OK, cvRepository::Exists(), FALSE, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, SYS_GEOM_DIVIDE_SCALAR, SYS_GEOM_DIVIDE_VECTOR, sys_geom_mathPointData(), SYS_GEOM_NO_SCALAR, and SYS_GEOM_NO_VECTOR.
Referenced by Geom_Init().
int Geom_FindDistanceCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3483 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, REQUIRED, and STRING_Type.
Referenced by Geom_Init().
int Geom_GetClosedLineRegionCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1235 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_GetClosedLineRegion().
Referenced by Geom_Init().
int Geom_GetOrderedPtsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1872 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, CV_STRLEN, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_GetOrderedPts().
Referenced by Geom_Init().
int Geom_GetPolyCentroidCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2158 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_getPolyCentroid().
Referenced by Geom_Init().
int Geom_Init (Tcl_Interp * interp)
Definition at line 247 of file cv_geom_init.cxx.
References Geom_2dWindingNumCmd(), Geom_AddPointDataCmd(), Geom_AlignProfileCmd(), Geom_AvgPtCmd(), Geom_BBoxCmd(), Geom_CheckSurfaceCmd(), Geom_ClassifyCmd(), Geom_CopyCmd(), Geom_DisorientProfileCmd(), Geom_DividePointDataCmd(), Geom_FindDistanceCmd(), Geom_GetClosedLineRegionCmd(), Geom_GetOrderedPtsCmd(), Geom_GetPolyCentroidCmd(), Geom_IntegrateEnergyCmd(), Geom_IntegrateScalarSurfCmd(), Geom_IntegrateScalarThreshCmd(), Geom_IntegrateSurface2Cmd(), Geom_IntegrateSurfaceCmd(), Geom_InterpolateScalarCmd(), Geom_InterpolateVectorCmd(), Geom_IntersectCmd(), Geom_IntersectWithLineCmd(), Geom_MakePolysConsistentCmd(), Geom_MergePtsCmd(), Geom_MultiplyPointDataCmd(), Geom_NumClosedLineRegionsCmd(), Geom_NumPtsCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_PolygonNormCmd(), Geom_PolysClosedCmd(), Geom_PrintSmallPolysCmd(), Geom_PrintTriStatsCmd(), Geom_ProjectCmd(), Geom_PtInPolyCmd(), Geom_ReduceCmd(), Geom_ReorderPgnCmd(), Geom_ReplacePointDataCmd(), Geom_ReverseAllCellsCmd(), Geom_RmSmallPolysCmd(), Geom_sampleLoopCmd(), Geom_ScaleAvgCmd(), Geom_SplinePtsToPathPlanCmd(), Geom_SubtractCmd(), Geom_SubtractPointDataCmd(), Geom_SurfAreaCmd(), Geom_TranslateCmd(), Geom_UnionCmd(), Geom_Warp3dPtsCmd(), Geom_WriteLinesCmd(), Geom_WriteOrderedPtsCmd(), and NULL.
Referenced by SimVascular_Init().
int Geom_IntegrateEnergyCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3401 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), ARG_List_s::argc, ARG_List_s::argv, CV_OK, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_IntegrateEnergy().
Referenced by Geom_Init().
int Geom_IntegrateScalarSurfCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 4312 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_IntegrateScalarSurf().
Referenced by Geom_Init().
int Geom_IntegrateScalarThreshCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 4371 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_IntegrateScalarThresh().
Referenced by Geom_Init().
int Geom_IntegrateSurface2Cmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3336 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_IntegrateSurface2().
Referenced by Geom_Init().
int Geom_IntegrateSurfaceCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3254 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), ARG_List_s::argc, ARG_List_s::argv, CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, LIST_Type, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_IntegrateSurface().
Referenced by Geom_Init().
int Geom_InterpolateScalarCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3555 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_InterpolateScalar().
Referenced by Geom_Init().
int Geom_InterpolateVectorCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3632 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_InterpolateVector().
Referenced by Geom_Init().
int Geom_IntersectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 543 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_intersect().
Referenced by Geom_Init().
int Geom_IntersectWithLineCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3713 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_IntersectWithLine().
Referenced by Geom_Init().
int Geom_MakePolysConsistentCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1034 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_MakePolysConsistent().
Referenced by Geom_Init().
int Geom_MergePtsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2607 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::Exists(), FindMachineEpsilon(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_MergePts_tol().
Referenced by Geom_Init().
int Geom_MultiplyPointDataCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 4003 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), BOOL_Type, CV_OK, cvRepository::Exists(), FALSE, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, sys_geom_mathPointData(), SYS_GEOM_MULTIPLY_SCALAR, SYS_GEOM_MULTIPLY_VECTOR, SYS_GEOM_NO_SCALAR, and SYS_GEOM_NO_VECTOR.
Referenced by Geom_Init().
int Geom_NumClosedLineRegionsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1178 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_NumClosedLineRegions().
Referenced by Geom_Init().
int Geom_NumPtsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2745 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, and STRING_Type.
Referenced by Geom_Init().
int Geom_OrientProfileCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1398 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_OrientProfile().
Referenced by Geom_Init().
int Geom_PickCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1306 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), ARG_List_s::argc, ARG_List_s::argv, CV_OK, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_Pick().
Referenced by Geom_Init().
int Geom_PolygonNormCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2927 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_PolygonNormal().
Referenced by Geom_Init().
int Geom_PolysClosedCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2041 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_PolysClosed().
Referenced by Geom_Init().
int Geom_PrintSmallPolysCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2269 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_PrintSmallPolys().
Referenced by Geom_Init().
int Geom_PrintTriStatsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2216 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_PrintTriStats().
Referenced by Geom_Init().
int Geom_ProjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 4209 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), BOOL_Type, CV_OK, cvRepository::Exists(), FALSE, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, SYS_GEOM_ADD_SCALAR, SYS_GEOM_ADD_VECTOR, SYS_GEOM_NO_SCALAR, SYS_GEOM_NO_VECTOR, and sys_geom_Project().
Referenced by Geom_Init().
int Geom_PtInPolyCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2531 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, LIST_Type, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_PtInPoly().
Referenced by Geom_Init().
int Geom_ReduceCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 384 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_Reduce().
Referenced by Geom_Init().
int Geom_ReorderPgnCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3113 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_ReorderPolygon().
Referenced by Geom_Init().
int Geom_ReplacePointDataCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 4433 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), BOOL_Type, CV_OK, cvRepository::Exists(), FALSE, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, SYS_GEOM_ADD_SCALAR, SYS_GEOM_ADD_VECTOR, SYS_GEOM_NO_SCALAR, SYS_GEOM_NO_VECTOR, and sys_geom_ReplacePointData().
Referenced by Geom_Init().
int Geom_ReverseAllCellsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1106 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_ReverseAllCells().
Referenced by Geom_Init().
int Geom_RmSmallPolysCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2323 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_RmSmallPolys().
Referenced by Geom_Init().
int Geom_sampleLoopCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2799 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_sampleLoop().
Referenced by Geom_Init().
int Geom_ScaleAvgCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1796 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_ScaleAvg().
Referenced by Geom_Init().
int Geom_SplinePtsToPathPlanCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3184 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, filename, GDSC_OPTIONAL, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, INT_Type, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_splinePtsToPathPlan().
Referenced by Geom_Init().
int Geom_SubtractCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 631 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_subtract().
Referenced by Geom_Init().
int Geom_SubtractPointDataCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 3900 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), BOOL_Type, CV_OK, cvRepository::Exists(), FALSE, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, sys_geom_mathPointData(), SYS_GEOM_NO_SCALAR, SYS_GEOM_NO_VECTOR, SYS_GEOM_SUBTRACT_SCALAR, and SYS_GEOM_SUBTRACT_VECTOR.
Referenced by Geom_Init().
int Geom_SurfAreaCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2100 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_SurfArea().
Referenced by Geom_Init().
int Geom_TranslateCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1706 of file cv_geom_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, LIST_Type, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_Translate().
Referenced by Geom_Init().
int Geom_UnionCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 456 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::Exists(), cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_union().
Referenced by Geom_Init().
int Geom_Warp3dPtsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 2676 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), DOUBLE_Type, cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, cvRepository::Register(), REQUIRED, STRING_Type, and sys_geom_warp3dPts().
Referenced by Geom_Init().
int Geom_WriteLinesCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1987 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_WriteLines().
Referenced by Geom_Init().
int Geom_WriteOrderedPtsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1933 of file cv_geom_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepository::GetObject(), cvRepositoryData::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, STRING_Type, and sys_geom_WriteOrderedPts().
Referenced by Geom_Init().