simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimDiscreteSolidModel/cv_discrete_utils.h File Reference
cv_discrete_utils.h File Reference
#include "SimVascular.h"
#include "cvVTK.h"
#include "cvMeshSimDiscreteSolidModel.h"
Functions
int DiscreteUtils_Init ()
int DiscreteUtils_MakePoly3dSolidVtk (vtkPolyData *pd, int faceCode, double angle, pDiscreteModel *result)
int DiscreteUtils_GetVtkPolyData (pDiscreteModel gm, int useMaxDist, double max_dist, vtkPolyData **out)
Function Documentation
int DiscreteUtils_GetVtkPolyData (pDiscreteModel gm, int useMaxDist, double max_dist, vtkPolyData ** out)
Definition at line 447 of file cv_discrete_utils.cxx.
References CV_OK, MY_MESHSIM_VERTEX_ORDERING, NULL, and point.
Referenced by cvMeshSimDiscreteSolidModel::GetPolyData().
int DiscreteUtils_Init ()
Definition at line 64 of file cv_discrete_utils.cxx.
References CV_ERROR, and CV_OK.
Referenced by Meshsimdiscretesolid_Init().
int DiscreteUtils_MakePoly3dSolidVtk (vtkPolyData * pd, int faceCode, double angle, pDiscreteModel * result)
Definition at line 220 of file cv_discrete_utils.cxx.
References CV_ERROR, CV_OK, CV_PI, discreteCalcJacDet(), iter, NULL, and VtkUtils_GetPoints().
Referenced by cvMeshSimDiscreteSolidModel::MakePoly3dSolid().