simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/SolidModel/cv_solid_init.h File Reference
cv_solid_init.h File Reference
#include "SimVascular.h"
#include "tcl.h"
Functions
CV_DLL_EXPORT int Solid_Init (Tcl_Interp *interp)
Function Documentation
CV_DLL_EXPORT int Solid_Init (Tcl_Interp * interp)
Definition at line 294 of file cv_solid_init.cxx.
References cvSolidModel::gCurrentKernel, cvSolidModel::gRegistrar, NULL, SM_KT_INVALID, SM_KT_PARASOLID, Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_CopyCmd(), Solid_CylinderCmd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_GetKernelCmd(), Solid_IntersectCmd(), Solid_ListMethodsCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_RegistrarsListCmd(), Solid_SetKernelCmd(), Solid_SphereCmd(), Solid_SubtractCmd(), Solid_TorusCmd(), Solid_TruncatedConeCmd(), and Solid_UnionCmd().
Referenced by SimVascular_Init().