simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/ParasolidSolidModel/cv_fru_prv.h File Reference
cv_fru_prv.h File Reference
#include "cv_fru.h"
#include "parasolid_kernel.h"
#include "kernel_interface.h"
#include "frustrum_ifails.h"
#include "frustrum_tokens.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <math.h>
Classes
struct file_s
struct GoGeoms
struct GoMan
Macros
#define trace_flag 0
#define PS_LONG_NAME 1
#define PS_SHORT_NAME 0
#define FR_not_started FR_unspecified
#define FR_internal_error FR_unspecified
#define null_strid (-1)
#define max_namelen 255 /* maximum length of a full pathname */
#define max_header_line (max_namelen+32) /* for long FILE=name in the header */
#define max_open_files 32
#define read_access 1
#define write_access 2
#define read_write_access 3
#define end_of_string_c '\0'
#define end_of_string_s "\0"
#define new_line_c '\n'
#define new_line_s "\n"
#define semi_colon_c ';'
#define semi_colon_s ";"
#define dir_separator_c '/'
#define dir_separator_s "/"
#define trace_print if (!trace_flag) /* skip */; else printf
Typedefs
typedef struct file_s * file_p
typedef struct file_s file_t
typedef struct GoGeoms GoGeoms
typedef struct GoMan GoMan
Functions
void fru_fstart (int *)
void fru_fabort (int *)
void fru_fstop (int *)
void fru_fmallo (int *, char **, int *)
void fru_fmfree (int *, char **, int *)
void fru_gosgmt (const int *, const int *, const int *, const int *, const double *, const int *, const int *, int *)
void fru_goopsg (const int *, const int *, const int *, const int *, const double *, const int *, const int *, int *)
void fru_goclsg (const int *, const int *, const int *, const int *, const double *, const int *, const int *, int *)
void fru_gopixl (const int *, const double *, const int *, const int *, int *)
void fru_gooppx (const int *, const double *, const int *, const int *, int *)
void fru_goclpx (const int *, const double *, const int *, const int *, int *)
void fru_ffoprd (const int *, const int *, const char *, const int *, const int *, int *, int *)
void fru_ffopwr (const int *, const int *, const char *, const int *, const char *, const int *, int *, int *)
void fru_ffclos (const int *, const int *, const int *, int *)
void fru_ffread (const int *, const int *, const int *, char *, int *, int *)
void fru_ffwrit (const int *, const int *, const int *, const char *, int *)
void fru_ffoprb (const int *, const int *, const int *, int *, int *, int *)
void fru_ffseek (const int *, const int *, const int *, int *)
void fru_fftell (const int *, const int *, int *, int *)
void FGCRCU (const char *, int *, int *, int *, int *, double *, int *, double *, int *)
void FGCRSU (const char *, int *, int *, int *, int *, double *, int *, double *, int *)
void FGEVCU (int *, double *, double *, double *, int *, double *, int *)
void FGEVSU (int *, double *, double *, double *, double *, int *, int *, int *, double *, int *)
void FGPRCU (int *, double *, double *, double *, int *, int *)
void FGPRSU (int *, double *, double *, double *, int *, int *)
void fru_go_conv_type (const int *segtyp)
void fru_go_conv_geom_type (int type)
void fru_go_circle (const int *segtyp, const int *ntags, const int *tags, const int *ngeom, const double *geom, const int *nlntp, const int *lntp, int *ifail)
void fru_go_man_init ()
void fru_go_man_add_geom (int num_verts, vtkFloatingPointType *verts, int num_poly, int *conn)
void fru_go_norm_frame (double *norm, double *v1, double *v2)
void fru_go_cross_prod (double *v1, double *v2, double *v3)
void fru_go_polyline (const int *segtyp, const int *ntags, const int *tags, const int *ngeom, const double *geom, const int *nlntp, const int *lntp, int *ifail)
void fru_go_vnorm (double *v)
void fru_go_ellipse (const int *segtyp, const int *ntags, const int *tags, const int *ngeom, const double *geom, const int *nlntp, const int *lntp, int *ifail)
Variables
static file_p open_files = NULL
static int stream_id [32]
static int file_count = 0
static int frustrum_started = 0
static char g_preamble_1 [(255+32)] = "\0"
static char g_preamble_2 [(255+32)] = "\0"
static char g_prefix_1 [(255+32)] = "**PART1;\n"
static char g_prefix_2 [(255+32)] = "**PART2;\n"
static char g_prefix_3 [(255+32)] = "**PART3;\n"
static char g_trailer_start [(255+32)] = "**END_OF_HEADER"
static char g_trailer [(255+32)] = "\0"
static char g_unknown_value [] = "unknown"
static char g_fopen_mode_read [] = "r"
static char g_fopen_mode_write [] = "w"
static char g_fopen_mode_append [] = "w+"
static char * input_output_buffer = NULL
static int input_output_buflen = 0
Macro Definition Documentation
#define dir_separator_c '/'
Definition at line 122 of file cv_fru_prv.h.
#define dir_separator_s "/"
Definition at line 123 of file cv_fru_prv.h.
#define end_of_string_c '\0'
Definition at line 100 of file cv_fru_prv.h.
#define end_of_string_s "\0"
Definition at line 101 of file cv_fru_prv.h.
#define FR_internal_error FR_unspecified
Definition at line 82 of file cv_fru_prv.h.
#define FR_not_started FR_unspecified
Definition at line 81 of file cv_fru_prv.h.
#define max_header_line (max_namelen+32) /* for long FILE=name in the header */
Definition at line 93 of file cv_fru_prv.h.
#define max_namelen 255 /* maximum length of a full pathname */
Definition at line 91 of file cv_fru_prv.h.
#define max_open_files 32
Definition at line 94 of file cv_fru_prv.h.
#define new_line_c '\n'
Definition at line 107 of file cv_fru_prv.h.
#define new_line_s "\n"
Definition at line 108 of file cv_fru_prv.h.
#define null_strid (-1)
Definition at line 87 of file cv_fru_prv.h.
#define PS_LONG_NAME 1
Definition at line 76 of file cv_fru_prv.h.
#define PS_SHORT_NAME 0
Definition at line 77 of file cv_fru_prv.h.
#define read_access 1
Definition at line 96 of file cv_fru_prv.h.
#define read_write_access 3
Definition at line 98 of file cv_fru_prv.h.
#define semi_colon_c ';'
Definition at line 111 of file cv_fru_prv.h.
#define semi_colon_s ";"
Definition at line 112 of file cv_fru_prv.h.
#define trace_flag 0
Definition at line 74 of file cv_fru_prv.h.
#define trace_print if (!trace_flag) /* skip */; else printf
Definition at line 132 of file cv_fru_prv.h.
#define write_access 2
Definition at line 97 of file cv_fru_prv.h.
Typedef Documentation
typedef struct file_s* file_p
Definition at line 144 of file cv_fru_prv.h.
typedef struct file_s file_t
typedef struct GoGeoms GoGeoms
typedef struct GoMan GoMan
Function Documentation
void FGCRCU (const char * , int * , int * , int * , int * , double * , int * , double * , int *)
void FGCRSU (const char * , int * , int * , int * , int * , double * , int * , double * , int *)
void FGEVCU (int * , double * , double * , double * , int * , double * , int *)
void FGEVSU (int * , double * , double * , double * , double * , int * , int * , int * , double * , int *)
void FGPRCU (int * , double * , double * , double * , int * , int *)
void FGPRSU (int * , double * , double * , double * , int * , int *)
void fru_fabort (int *)
Definition at line 2465 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_ffclos (const int * , const int * , const int * , int *)
Definition at line 2375 of file frustrum.cxx.
References file_s::access, delete_file(), file_count, filename, FR_not_started, free(), frustrum_started, max_namelen, file_s::name, file_s::next, NULL, file_s::prev, read_write_access, file_s::stream, stream_id, file_s::strid, trace_print, and write_access.
Referenced by fru_init().
void fru_ffoprb (const int * , const int * , const int * , int * , int * , int *)
Definition at line 1989 of file frustrum.cxx.
References file_count, filename, FR_not_started, frustrum_started, g_fopen_mode_append, max_namelen, max_open_files, new_open_file(), null_strid, read_write_access, file_s::strid, and trace_print.
Referenced by fru_init().
void fru_ffoprd (const int * , const int * , const char * , const int * , const int * , int * , int *)
Definition at line 1677 of file frustrum.cxx.
References check_valid_filename(), dir_separator_c, end_of_string_c, extend_schema_filename(), file_count, filename, filetype_format_string(), filetype_guise_string(), FR_not_started, frustrum_started, g_fopen_mode_read, max_namelen, max_open_files, new_open_file(), null_strid, PS_LONG_NAME, PS_SHORT_NAME, read_access, skip_header(), file_s::strid, and trace_print.
Referenced by fru_init().
void fru_ffopwr (const int * , const int * , const char * , const int * , const char * , const int * , int * , int *)
Definition at line 1839 of file frustrum.cxx.
References check_valid_filename(), dir_separator_c, end_of_string_c, extend_schema_filename(), file_count, filename, filetype_format_string(), filetype_guise_string(), FR_not_started, frustrum_started, g_fopen_mode_write, max_namelen, max_open_files, new_open_file(), null_strid, PS_LONG_NAME, PS_SHORT_NAME, file_s::strid, trace_print, write_access, write_header(), and write_xml_header().
Referenced by fru_init().
void fru_ffread (const int * , const int * , const int * , char * , int * , int *)
Definition at line 2146 of file frustrum.cxx.
References file_s::access, FR_internal_error, FR_not_started, frustrum_started, file_s::guise, file_s::next, NULL, read_access, read_from_file(), read_write_access, file_s::strid, and trace_print.
Referenced by fru_init().
void fru_ffseek (const int * , const int * , const int * , int *)
Definition at line 2302 of file frustrum.cxx.
References FR_internal_error, FR_not_started, frustrum_started, file_s::guise, file_s::next, NULL, file_s::stream, file_s::strid, and trace_print.
Referenced by fru_init().
void fru_fftell (const int * , const int * , int * , int *)
Definition at line 2236 of file frustrum.cxx.
References FR_internal_error, FR_not_started, frustrum_started, file_s::guise, file_s::next, NULL, file_s::stream, file_s::strid, and trace_print.
Referenced by fru_init().
void fru_ffwrit (const int * , const int * , const int * , const char * , int *)
Definition at line 2067 of file frustrum.cxx.
References file_s::access, FR_internal_error, FR_not_started, frustrum_started, file_s::guise, file_s::next, NULL, read_write_access, file_s::stream, file_s::strid, trace_print, write_access, and write_to_file().
Referenced by fru_init().
void fru_fmallo (int * , char ** , int *)
Definition at line 1581 of file frustrum.cxx.
References FR_not_started, frustrum_started, NULL, and trace_print.
Referenced by fru_init().
void fru_fmfree (int * , char ** , int *)
Definition at line 1642 of file frustrum.cxx.
References FR_not_started, frustrum_started, and trace_print.
Referenced by fru_init().
void fru_fstart (int *)
Definition at line 1469 of file frustrum.cxx.
References frustrum_started, max_open_files, setup_header(), stream_id, and trace_print.
Referenced by fru_init().
void fru_fstop (int *)
Definition at line 1514 of file frustrum.cxx.
References file_count, FR_not_started, free(), frustrum_started, input_output_buffer, input_output_buflen, file_s::next, NULL, open_files, file_s::prev, file_s::stream, and trace_print.
Referenced by fru_init().
void fru_go_circle (const int * segtyp, const int * ntags, const int * tags, const int * ngeom, const double * geom, const int * nlntp, const int * lntp, int * ifail)
void fru_go_conv_geom_type (int type)
void fru_go_conv_type (const int * segtyp)
void fru_go_cross_prod (double * v1, double * v2, double * v3)
void fru_go_ellipse (const int * segtyp, const int * ntags, const int * tags, const int * ngeom, const double * geom, const int * nlntp, const int * lntp, int * ifail)
void fru_go_man_add_geom (int num_verts, vtkFloatingPointType * verts, int num_poly, int * conn)
void fru_go_man_init ()
void fru_go_norm_frame (double * norm, double * v1, double * v2)
void fru_go_polyline (const int * segtyp, const int * ntags, const int * tags, const int * ngeom, const double * geom, const int * nlntp, const int * lntp, int * ifail)
void fru_go_vnorm (double * v)
void fru_goclpx (const int * , const double * , const int * , const int * , int *)
Definition at line 2641 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_goclsg (const int * , const int * , const int * , const int * , const double * , const int * , const int * , int *)
Definition at line 2711 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_gooppx (const int * , const double * , const int * , const int * , int *)
Definition at line 2618 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_goopsg (const int * , const int * , const int * , const int * , const double * , const int * , const int * , int *)
Definition at line 2687 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_gopixl (const int * , const double * , const int * , const int * , int *)
Definition at line 2664 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
void fru_gosgmt (const int * , const int * , const int * , const int * , const double * , const int * , const int * , int *)
Definition at line 2735 of file frustrum.cxx.
References trace_print.
Referenced by fru_init().
Variable Documentation
int file_count = 0 static
Definition at line 163 of file cv_fru_prv.h.
int frustrum_started = 0 static
Definition at line 167 of file cv_fru_prv.h.
char g_fopen_mode_append[] = "w+" static
Definition at line 215 of file cv_fru_prv.h.
char g_fopen_mode_read[] = "r" static
Definition at line 213 of file cv_fru_prv.h.
char g_fopen_mode_write[] = "w" static
Definition at line 214 of file cv_fru_prv.h.
char g_preamble_1[(255+32)] = "\0" static
Definition at line 195 of file cv_fru_prv.h.
char g_preamble_2[(255+32)] = "\0" static
Definition at line 196 of file cv_fru_prv.h.
char g_prefix_1[(255+32)] = "**PART1;\n" static
Definition at line 197 of file cv_fru_prv.h.
char g_prefix_2[(255+32)] = "**PART2;\n" static
Definition at line 198 of file cv_fru_prv.h.
char g_prefix_3[(255+32)] = "**PART3;\n" static
Definition at line 199 of file cv_fru_prv.h.
char g_trailer[(255+32)] = "\0" static
Definition at line 201 of file cv_fru_prv.h.
char g_trailer_start[(255+32)] = "**END_OF_HEADER" static
Definition at line 200 of file cv_fru_prv.h.
char g_unknown_value[] = "unknown" static
Definition at line 202 of file cv_fru_prv.h.
char* input_output_buffer = NULL static
Definition at line 219 of file cv_fru_prv.h.
int input_output_buflen = 0 static
Definition at line 220 of file cv_fru_prv.h.
file_p open_files = NULL static
Definition at line 159 of file cv_fru_prv.h.
int stream_id[32] static
Definition at line 162 of file cv_fru_prv.h.