simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/MeshObject/cv_mesh_init.cxx File Reference
cv_mesh_init.cxx File Reference
#include "SimVascular.h"
#include "cvMeshSystem.h"
#include "cv_mesh_init.h"
#include <stdio.h>
#include <string.h>
#include "cvRepository.h"
#include "cvRepositoryData.h"
#include "cvPolyData.h"
#include "cv_arg.h"
#include "cvVTK.h"
#include "cv_misc_utils.h"
#include "cv_globals.h"
Functions
int cvMesh_GetMeshKernelCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int cvMesh_SetMeshKernelCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int cvMesh_NewObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int cvMesh_ObjectCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int cvMesh_ListMethodsCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int cvMesh_LogonCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
int cvMesh_LogoffCmd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetElementTypeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_PrintMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_UpdateMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteABAQUSMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteDataExplorerMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteHypermeshMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteMeshVRMLMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WritePROPHLEXMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteSpectrumSolverElementsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteSpectrumSolverNodesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteSpectrumVisMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteSurfaceMeshOOGLMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteSurfaceMeshVRMLMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteMetisAdjacencyMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetElementFacesInModelRegionMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetElementNodesInModelRegionMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetElementFacesOnModelFaceMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetElementNodesOnModelFaceMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetElementsInModelRegionMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetExteriorElementFacesOnRegionMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetExteriorElementNodesOnRegionMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetSharedElementFacesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetSharedElementNodesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GenerateQuadraticElementsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetElementConnectivityMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetNodeCoordsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetPolyDataMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetVtkPolyDataMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetUnstructuredGridMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetFacePolyDataMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetSolidKernelMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetModelFaceInfoMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GetBoundaryFacesMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_LoadModelMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_LoadMeshMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_NewMeshMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetSurfaceMeshFlagMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetSurfaceOptimizationMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetSurfaceSmoothingMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetVolumeMeshFlagMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetVolumeOptimizationMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetVolumeSmoothingMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_GenerateMeshMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteMeshMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_WriteStatsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetGlobalSizeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetMeshOptionsMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetLocalSizeMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetGlobalCurvMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetLocalCurvMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetGlobalMinCurvMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetLocalMinCurvMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetCylinderRefinementMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetSphereRefinementMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetBoundaryLayerMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetSolidKernelMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static int cvMesh_SetSizeFunctionBasedMeshMtd (ClientData clientData, Tcl_Interp *interp, int argc, CONST84 char *argv[])
static void gdscMeshPrintMethods (Tcl_Interp *interp)
void DeletegdscMesh (ClientData clientData)
int Gdscmesh_Init (Tcl_Interp *interp)
Function Documentation
int cvMesh_GenerateMeshMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2687 of file cv_mesh_init.cxx.
References CV_ERROR, cvMeshObject::GenerateMesh(), and NULL.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GenerateQuadraticElementsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1503 of file cv_mesh_init.cxx.
References CV_OK, cvMeshObject::GenerateQuadraticElements(), cvRepositoryData::GetName(), and NULL.
Referenced by cvMesh_ObjectCmd().
int cvMesh_GetBoundaryFacesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2481 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, DOUBLE_Type, cvMeshObject::GetBoundaryFaces(), cvRepositoryData::GetName(), NULL, and REQUIRED.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetElementConnectivityMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1523 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvMeshObject::GetElementConnectivity(), cvRepositoryData::GetName(), INT_Type, NULL, and REQUIRED.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetElementFacesInModelRegionMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
static int cvMesh_GetElementFacesOnModelFaceMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1337 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), BOOL_Type, CV_OK, GDSC_OPTIONAL, cvMeshObject::GetElementFacesOnModelFace(), cvRepositoryData::GetName(), INT_Type, NULL, REQUIRED, and STRING_Type.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetElementNodesInModelRegionMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
static int cvMesh_GetElementNodesOnModelFaceMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1380 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, GDSC_OPTIONAL, cvMeshObject::GetElementNodesOnModelFace(), cvRepositoryData::GetName(), INT_Type, NULL, REQUIRED, and STRING_Type.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetElementsInModelRegionMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1421 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, GDSC_OPTIONAL, cvMeshObject::GetElementsInModelRegion(), cvRepositoryData::GetName(), INT_Type, NULL, REQUIRED, and STRING_Type.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetElementTypeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 862 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), cvMeshObject::GetElementType(), and NULL.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetExteriorElementFacesOnRegionMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1462 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, GDSC_OPTIONAL, cvMeshObject::GetExteriorElementFacesOnRegion(), cvRepositoryData::GetName(), INT_Type, NULL, REQUIRED, and STRING_Type.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetExteriorElementNodesOnRegionMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
static int cvMesh_GetFacePolyDataMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1780 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvMeshObject::GetFacePolyData(), cvRepositoryData::GetName(), gRepository, INT_Type, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by cvMesh_ObjectCmd().
int cvMesh_GetMeshKernelCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 330 of file cv_mesh_init.cxx.
References cvMeshSystem::GetCurrentKernelName(), and NULL.
Referenced by Gdscmesh_Init().
static int cvMesh_GetModelFaceInfoMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2960 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), cvMeshObject::GetModelFaceInfo(), and NULL.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetNodeCoordsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1563 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), cvMeshObject::GetNodeCoords(), INT_Type, cvMeshObject::nodeX_, cvMeshObject::nodeY_, cvMeshObject::nodeZ_, NULL, and REQUIRED.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetPolyDataMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1607 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), cvMeshObject::GetPolyData(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetSharedElementFacesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
static int cvMesh_GetSharedElementNodesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
static int cvMesh_GetSolidKernelMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 831 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), cvMeshObject::GetSolidModelKernel(), NULL, SM_KT_INVALID, and SolidModel_KernelT_EnumToStr().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_GetUnstructuredGridMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1723 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::Exists(), cvRepositoryData::GetName(), cvMeshObject::GetUnstructuredGrid(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by cvMesh_ObjectCmd().
int cvMesh_ListMethodsCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 317 of file cv_mesh_init.cxx.
References gdscMeshPrintMethods(), and NULL.
Referenced by Gdscmesh_Init().
int cvMesh_LoadMeshMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2559 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, cvMeshObject::LoadMesh(), NULL, REQUIRED, and STRING_Type.
Referenced by cvMesh_ObjectCmd().
int cvMesh_LoadModelMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2443 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, cvMeshObject::LoadModel(), NULL, REQUIRED, and STRING_Type.
Referenced by cvMesh_ObjectCmd().
int cvMesh_LogoffCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1879 of file cv_mesh_init.cxx.
References CV_ERROR, cvMeshSystem::GetCurrentKernel(), cvMeshSystem::LogOff(), and NULL.
Referenced by Gdscmesh_Init().
int cvMesh_LogonCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 1838 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, cvMeshSystem::GetCurrentKernel(), cvMeshSystem::LogOn(), NULL, REQUIRED, and STRING_Type.
Referenced by Gdscmesh_Init().
int cvMesh_NewMeshMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2665 of file cv_mesh_init.cxx.
References CV_ERROR, cvMeshObject::NewMesh(), and NULL.
Referenced by cvMesh_ObjectCmd().
int cvMesh_NewObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 254 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvMesh_ObjectCmd(), cvMeshSystem::DefaultInstantiateMeshObject(), DeletegdscMesh(), cvRepository::Exists(), GDSC_OPTIONAL, cvRepositoryData::GetName(), gRepository, NULL, cvRepository::Register(), REQUIRED, and STRING_Type.
Referenced by Gdscmesh_Init().
int cvMesh_ObjectCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 389 of file cv_mesh_init.cxx.
References CV_ERROR, cvMesh_GenerateMeshMtd(), cvMesh_GenerateQuadraticElementsMtd(), cvMesh_GetBoundaryFacesMtd(), cvMesh_GetElementConnectivityMtd(), cvMesh_GetElementFacesOnModelFaceMtd(), cvMesh_GetElementNodesOnModelFaceMtd(), cvMesh_GetElementsInModelRegionMtd(), cvMesh_GetElementTypeMtd(), cvMesh_GetExteriorElementFacesOnRegionMtd(), cvMesh_GetFacePolyDataMtd(), cvMesh_GetModelFaceInfoMtd(), cvMesh_GetNodeCoordsMtd(), cvMesh_GetPolyDataMtd(), cvMesh_GetSolidKernelMtd(), cvMesh_GetUnstructuredGridMtd(), cvMesh_LoadMeshMtd(), cvMesh_LoadModelMtd(), cvMesh_NewMeshMtd(), cvMesh_PrintMtd(), cvMesh_SetBoundaryLayerMtd(), cvMesh_SetCylinderRefinementMtd(), cvMesh_SetGlobalCurvMtd(), cvMesh_SetGlobalMinCurvMtd(), cvMesh_SetGlobalSizeMtd(), cvMesh_SetLocalCurvMtd(), cvMesh_SetLocalMinCurvMtd(), cvMesh_SetLocalSizeMtd(), cvMesh_SetMeshOptionsMtd(), cvMesh_SetSizeFunctionBasedMeshMtd(), cvMesh_SetSolidKernelMtd(), cvMesh_SetSphereRefinementMtd(), cvMesh_SetSurfaceMeshFlagMtd(), cvMesh_SetSurfaceOptimizationMtd(), cvMesh_SetSurfaceSmoothingMtd(), cvMesh_SetVolumeMeshFlagMtd(), cvMesh_SetVolumeOptimizationMtd(), cvMesh_SetVolumeSmoothingMtd(), cvMesh_SetVtkPolyDataMtd(), cvMesh_WriteABAQUSMtd(), cvMesh_WriteDataExplorerMtd(), cvMesh_WriteHypermeshMtd(), cvMesh_WriteMeshMtd(), cvMesh_WriteMeshVRMLMtd(), cvMesh_WriteMetisAdjacencyMtd(), cvMesh_WritePROPHLEXMtd(), cvMesh_WriteSpectrumSolverElementsMtd(), cvMesh_WriteSpectrumSolverNodesMtd(), cvMesh_WriteSpectrumVisMtd(), cvMesh_WriteStatsMtd(), cvMesh_WriteSurfaceMeshOOGLMtd(), cvMesh_WriteSurfaceMeshVRMLMtd(), gdscMeshPrintMethods(), cvMeshObject::GetMeshLoaded(), NULL, and cvMeshObject::Update().
Referenced by cvMesh_NewObjectCmd().
static int cvMesh_PrintMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 755 of file cv_mesh_init.cxx.
References CV_OK, and cvMeshObject::Print().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetBoundaryLayerMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2896 of file cv_mesh_init.cxx.
References ARG_FreeListArgvs(), ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argc, CV_ERROR, DOUBLE_Type, H, INT_Type, LIST_Type, NULL, REQUIRED, and cvMeshObject::SetBoundaryLayer().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetCylinderRefinementMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2811 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argv, CV_ERROR, DOUBLE_Type, LIST_Type, NULL, REQUIRED, and cvMeshObject::SetCylinderRefinement().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetGlobalCurvMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2269 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, INT_Type, NULL, REQUIRED, and cvMeshObject::SetGlobalCurv().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetGlobalMinCurvMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2356 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, INT_Type, NULL, REQUIRED, and cvMeshObject::SetGlobalMinCurv().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetGlobalSizeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2142 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, INT_Type, NULL, REQUIRED, and cvMeshObject::SetGlobalSize().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetLocalCurvMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2312 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, INT_Type, NULL, REQUIRED, and cvMeshObject::SetLocalCurv().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetLocalMinCurvMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2399 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, INT_Type, NULL, REQUIRED, and cvMeshObject::SetLocalMinCurv().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetLocalSizeMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2225 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, INT_Type, NULL, REQUIRED, and cvMeshObject::SetLocalSize().
Referenced by cvMesh_ObjectCmd().
int cvMesh_SetMeshKernelCmd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[])
Definition at line 352 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvMeshObject::GetKernelType(), cvMeshObject::KERNEL_INVALID, NULL, REQUIRED, cvMeshSystem::SetCurrentKernel(), and STRING_Type.
Referenced by Gdscmesh_Init().
static int cvMesh_SetMeshOptionsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2184 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, GDSC_OPTIONAL, NULL, REQUIRED, cvMeshObject::SetMeshOptions(), and STRING_Type.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetSizeFunctionBasedMeshMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2771 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, DOUBLE_Type, NULL, REQUIRED, cvMeshObject::SetSizeFunctionBasedMesh(), and STRING_Type.
Referenced by cvMesh_ObjectCmd().
int cvMesh_SetSolidKernelMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 790 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), NULL, REQUIRED, cvMeshObject::SetSolidModelKernel(), SM_KT_INVALID, SolidModel_KernelT_EnumToStr(), SolidModel_KernelT_StrToEnum(), and STRING_Type.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetSphereRefinementMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2709 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclListStatic(), ARG_ParseTclStr(), ARG_List_s::argv, CV_ERROR, DOUBLE_Type, LIST_Type, NULL, REQUIRED, and cvMeshObject::SetSphereRefinement().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetSurfaceMeshFlagMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1902 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, INT_Type, NULL, REQUIRED, and cvMeshObject::SetSurfaceMeshFlag().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetSurfaceOptimizationMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1942 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, INT_Type, NULL, REQUIRED, and cvMeshObject::SetSurfaceOptimization().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetSurfaceSmoothingMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1982 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, INT_Type, NULL, REQUIRED, and cvMeshObject::SetSurfaceSmoothing().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetVolumeMeshFlagMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2022 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, INT_Type, NULL, REQUIRED, and cvMeshObject::SetVolumeMeshFlag().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetVolumeOptimizationMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2062 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, INT_Type, NULL, REQUIRED, and cvMeshObject::SetVolumeOptimization().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetVolumeSmoothingMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2102 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, INT_Type, NULL, REQUIRED, and cvMeshObject::SetVolumeSmoothing().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_SetVtkPolyDataMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1663 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), cvRepository::GetObject(), cvRepository::GetType(), gRepository, NULL, POLY_DATA_T, REQUIRED, cvMeshObject::SetVtkPolyDataObject(), and STRING_Type.
Referenced by cvMesh_ObjectCmd().
static int cvMesh_UpdateMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 773 of file cv_mesh_init.cxx.
References CV_OK, and cvMeshObject::Update().
static int cvMesh_WriteABAQUSMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 891 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteAbaqusInputDeck().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WriteDataExplorerMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 930 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteDataExplorer().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WriteHypermeshMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 970 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteHypermeshAscii().
Referenced by cvMesh_ObjectCmd().
int cvMesh_WriteMeshMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2624 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, GDSC_OPTIONAL, INT_Type, NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteMesh().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WriteMeshVRMLMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1010 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteMeshVrml().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WriteMetisAdjacencyMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1295 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteMetisAdjacency().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WritePROPHLEXMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1049 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteProphlexInputDeck().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WriteSpectrumSolverElementsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1215 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteSpectrumSolverElements().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WriteSpectrumSolverNodesMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1255 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteSpectrumSolverNodes().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WriteSpectrumVisMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1088 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, CV_STRLEN, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, cvMeshObject::WriteSpectrumVisData(), and cvMeshObject::WriteSpectrumVisMesh().
Referenced by cvMesh_ObjectCmd().
int cvMesh_WriteStatsMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 2592 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_ERROR, NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteStats().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WriteSurfaceMeshOOGLMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1136 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteSurfaceMeshOogl().
Referenced by cvMesh_ObjectCmd().
static int cvMesh_WriteSurfaceMeshVRMLMtd (ClientData clientData, Tcl_Interp * interp, int argc, CONST84 char * argv[]) static
Definition at line 1175 of file cv_mesh_init.cxx.
References ARG_GenSyntaxStr(), ARG_ParseTclStr(), CV_OK, cvRepositoryData::GetName(), NULL, REQUIRED, STRING_Type, and cvMeshObject::WriteSurfaceMeshVrml().
Referenced by cvMesh_ObjectCmd().
void DeletegdscMesh (ClientData clientData)
Definition at line 662 of file cv_mesh_init.cxx.
References cvRepositoryData::GetName(), gRepository, and cvRepository::UnRegister().
Referenced by cvMesh_NewObjectCmd().
int Gdscmesh_Init (Tcl_Interp * interp)
Definition at line 224 of file cv_mesh_init.cxx.
References cvMesh_GetMeshKernelCmd(), cvMesh_ListMethodsCmd(), cvMesh_LogoffCmd(), cvMesh_LogonCmd(), cvMesh_NewObjectCmd(), cvMesh_SetMeshKernelCmd(), cvMeshObject::KERNEL_INVALID, NULL, cvMeshSystem::RegisterKernel(), and cvMeshSystem::SetCurrentKernel().
Referenced by SimVascular_Init().
static void gdscMeshPrintMethods (Tcl_Interp * interp) static
Definition at line 673 of file cv_mesh_init.cxx.
References tcl_printstr().
Referenced by cvMesh_ListMethodsCmd(), and cvMesh_ObjectCmd().