simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Utils/cv_arg.cxx File Reference
cv_arg.cxx File Reference
#include "SimVascular.h"
#include "cv_arg.h"
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
Macros
#define MAX_ARGVAL_PAIRS 100
Functions
static int ARG_FindArgvIx (char *name, int argc, CONST84 char *argv[])
int ARG_ParseTclStr (Tcl_Interp *interp, int argc, CONST84 char *argv[], int startIx, int table_size, ARG_Entry arg_table[])
int ARG_ParseTclListStatic (Tcl_Interp *interp, ARG_List list, ARG_Type t, void *arr, int arrsz, int *numasn)
int ARG_ParseTclListDynamic (Tcl_Interp *interp, ARG_List list, ARG_Type t, void **arr, int *numasn)
char * ARG_GenSyntaxStr (int argc, CONST84 char *argv[], int table_size, ARG_Entry arg_table[])
void ARG_FreeListArgvs (int table_size, ARG_Entry arg_table[])
void ARG_Show (int table_size, ARG_Entry arg_table[])
void tcl_printstr (Tcl_Interp *interp, char *str)
Macro Definition Documentation
#define MAX_ARGVAL_PAIRS 100
Definition at line 40 of file cv_arg.cxx.
Referenced by ARG_ParseTclStr().
Function Documentation
static int ARG_FindArgvIx (char * name, int argc, CONST84 char * argv[]) static
Definition at line 191 of file cv_arg.cxx.
Referenced by ARG_ParseTclStr().
void ARG_FreeListArgvs (int table_size, ARG_Entry arg_table[])
Definition at line 453 of file cv_arg.cxx.
References ARG_List_s::argv, and LIST_Type.
Referenced by cvMesh_SetBoundaryLayerMtd(), FMMHelper(), gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_FastMarchCmd(), gdscITK_MinMaxCurvSmoothCmd(), gdscITK_ReadRegionOfInterestCmd(), gdscITK_SigMapCmd(), gdscITK_TLSF_Cmd(), gdscPost_calcAvgPointDataCmd(), gdscPost_calcTKECmd(), gdscPost_calcWallShearMeanCmd(), gdscPost_calcWallShearPulseCmd(), gdscPost_readVisResCmd(), Geom_AlignProfileCmd(), Geom_ClassifyCmd(), Geom_DisorientProfileCmd(), Geom_FindDistanceCmd(), Geom_IntegrateEnergyCmd(), Geom_IntegrateSurface2Cmd(), Geom_IntegrateSurfaceCmd(), Geom_InterpolateScalarCmd(), Geom_InterpolateVectorCmd(), Geom_IntersectWithLineCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_PtInPolyCmd(), Geom_ScaleAvgCmd(), Geom_TranslateCmd(), Image_CalcCorrectionEqnAutoCmd(), Image_CalcCorrectionEqnCmd(), Image_ComputeStructuredCoordCmd(), Image_CreateDistanceMapCmd(), Image_FindPathCmd(), LsetVImage_SetImageMtd(), Math_computeWomersleyCmd(), Math_curveLengthCmd(), Math_FFTCmd(), Math_fitLeastSquaresCmd(), Math_inverseFFTCmd(), Math_linearInterpCmd(), Math_linearInterpolateCurveCmd(), Math_smoothCurveCmd(), Solid_Apply4x4Mtd(), Solid_Box3dCmd(), Solid_CylinderCmd(), Solid_DeleteFacesMtd(), Solid_DeleteRegionMtd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_MakeLoftedSurfCmd(), Solid_ReflectMtd(), Solid_RemeshFaceMtd(), Solid_TorusCmd(), and Solid_TruncatedConeCmd().
char* ARG_GenSyntaxStr (int argc, CONST84 char * argv[], int table_size, ARG_Entry arg_table[])
Definition at line 381 of file cv_arg.cxx.
References BOOL_Type, DOUBLE_Type, GDSC_OPTIONAL, INT_Type, LIST_Type, ARG_Entry_s::name, REQUIRED, ARG_Entry_s::required, STRING_Type, and ARG_Entry_s::type.
Referenced by cvMesh_GetBoundaryFacesMtd(), cvMesh_GetElementConnectivityMtd(), cvMesh_GetElementFacesOnModelFaceMtd(), cvMesh_GetElementNodesOnModelFaceMtd(), cvMesh_GetElementsInModelRegionMtd(), cvMesh_GetElementTypeMtd(), cvMesh_GetExteriorElementFacesOnRegionMtd(), cvMesh_GetFacePolyDataMtd(), cvMesh_GetModelFaceInfoMtd(), cvMesh_GetNodeCoordsMtd(), cvMesh_GetPolyDataMtd(), cvMesh_GetSolidKernelMtd(), cvMesh_GetUnstructuredGridMtd(), cvMesh_LoadMeshMtd(), cvMesh_LoadModelMtd(), cvMesh_LogonCmd(), cvMesh_NewObjectCmd(), cvMesh_SetBoundaryLayerMtd(), cvMesh_SetCylinderRefinementMtd(), cvMesh_SetGlobalCurvMtd(), cvMesh_SetGlobalMinCurvMtd(), cvMesh_SetGlobalSizeMtd(), cvMesh_SetLocalCurvMtd(), cvMesh_SetLocalMinCurvMtd(), cvMesh_SetLocalSizeMtd(), cvMesh_SetMeshKernelCmd(), cvMesh_SetMeshOptionsMtd(), cvMesh_SetSizeFunctionBasedMeshMtd(), cvMesh_SetSolidKernelMtd(), cvMesh_SetSphereRefinementMtd(), cvMesh_SetSurfaceMeshFlagMtd(), cvMesh_SetSurfaceOptimizationMtd(), cvMesh_SetSurfaceSmoothingMtd(), cvMesh_SetVolumeMeshFlagMtd(), cvMesh_SetVolumeOptimizationMtd(), cvMesh_SetVolumeSmoothingMtd(), cvMesh_SetVtkPolyDataMtd(), cvMesh_WriteABAQUSMtd(), cvMesh_WriteDataExplorerMtd(), cvMesh_WriteHypermeshMtd(), cvMesh_WriteMeshMtd(), cvMesh_WriteMeshVRMLMtd(), cvMesh_WriteMetisAdjacencyMtd(), cvMesh_WritePROPHLEXMtd(), cvMesh_WriteSpectrumSolverElementsMtd(), cvMesh_WriteSpectrumSolverNodesMtd(), cvMesh_WriteSpectrumVisMtd(), cvMesh_WriteStatsMtd(), cvMesh_WriteSurfaceMeshOOGLMtd(), cvMesh_WriteSurfaceMeshVRMLMtd(), gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_expNegativeImageCmd(), gdscITK_FastMarchCmd(), gdscITK_MinMaxCurvSmoothCmd(), gdscITK_ReadRegionOfInterestCmd(), gdscITK_shapeDetectionCmd(), gdscITK_SigMapCmd(), gdscITK_TLSF_Cmd(), gdscPost_calcAvgPointDataCmd(), gdscPost_calcOSICmd(), gdscPost_calcTKECmd(), gdscPost_calcWallShearCmd(), gdscPost_calcWallShearMeanCmd(), gdscPost_calcWallShearPulseCmd(), gdscPost_readVisMeshCmd(), gdscPost_readVisResCmd(), Geom_2dWindingNumCmd(), Geom_AddPointDataCmd(), Geom_AlignProfileCmd(), Geom_AvgPtCmd(), Geom_BBoxCmd(), Geom_CheckSurfaceCmd(), Geom_ClassifyCmd(), Geom_CopyCmd(), Geom_DisorientProfileCmd(), Geom_DividePointDataCmd(), Geom_FindDistanceCmd(), Geom_GetClosedLineRegionCmd(), Geom_GetOrderedPtsCmd(), Geom_GetPolyCentroidCmd(), Geom_IntegrateEnergyCmd(), Geom_IntegrateScalarSurfCmd(), Geom_IntegrateScalarThreshCmd(), Geom_IntegrateSurface2Cmd(), Geom_IntegrateSurfaceCmd(), Geom_InterpolateScalarCmd(), Geom_InterpolateVectorCmd(), Geom_IntersectCmd(), Geom_IntersectWithLineCmd(), Geom_MakePolysConsistentCmd(), Geom_MergePtsCmd(), Geom_MultiplyPointDataCmd(), Geom_NumClosedLineRegionsCmd(), Geom_NumPtsCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_PolygonNormCmd(), Geom_PolysClosedCmd(), Geom_PrintSmallPolysCmd(), Geom_PrintTriStatsCmd(), Geom_ProjectCmd(), Geom_PtInPolyCmd(), Geom_ReduceCmd(), Geom_ReorderPgnCmd(), Geom_ReplacePointDataCmd(), Geom_ReverseAllCellsCmd(), Geom_RmSmallPolysCmd(), Geom_sampleLoopCmd(), Geom_ScaleAvgCmd(), Geom_SplinePtsToPathPlanCmd(), Geom_SubtractCmd(), Geom_SubtractPointDataCmd(), Geom_SurfAreaCmd(), Geom_TranslateCmd(), Geom_UnionCmd(), Geom_Warp3dPtsCmd(), Geom_WriteLinesCmd(), Geom_WriteOrderedPtsCmd(), Image_CalcCorrectionEqnAutoCmd(), Image_CalcCorrectionEqnCmd(), Image_ComputeStructuredCoordCmd(), Image_CreateDistanceMapCmd(), Image_DecodeCmd(), Image_FindPathCmd(), Image_MaskInPlaceCmd(), Image_ReadHeaderCmd(), Image_ThresholdCmd(), itkls2d_GACLevelSetMtd(), itkls2d_PhaseOneLevelSetMtd(), itkls2d_PhaseTwoLevelSetMtd(), itkls2d_SetInputsMtd(), itkls3d_GACLevelSetMtd(), itkls3d_LaplacianLevelSetMtd(), itkls3d_PhaseOneLevelSetMtd(), itkls3d_PhaseTwoLevelSetMtd(), itkls3d_SetInputsMtd(), itkutils_FractEdgeProximity3DCmd(), itkutils_GenerateCircleCmd(), itkutils_GradientMagnitudeGaussianCmd(), itkutils_PdToImgCmd(), itkutils_PdToVolCmd(), itkutils_WriteImageCmd(), LsetCore_ExtractActiveNodesMtd(), LsetCore_ExtractCoveredNodesMtd(), LsetCore_ExtractCurvatureMtd(), LsetCore_ExtractForceMinVNodesMtd(), LsetCore_ExtractFrontMtd(), LsetCore_ExtractMineNodesMtd(), LsetCore_ExtractPhiMtd(), LsetCore_ExtractProjectionSetsMtd(), LsetCore_ExtractUncoveredNodesMtd(), LsetCore_ExtractVelMtd(), LsetCore_FindMaxVMtd(), LsetCore_GetBoundaryDataMtd(), LsetCore_GetGridStatsMtd(), LsetCore_GetMemoryUsageMtd(), LsetCore_GetSaveProjectionSetsMtd(), LsetCore_GetTimeMtd(), LsetCore_GetTimerGranularityMtd(), LsetCore_GetTimeStepMtd(), LsetCore_GetVelocityMtd(), LsetCore_GetVExtensionMtd(), LsetCore_GridModifiedMtd(), LsetCore_IsInitMtd(), LsetCore_ResetTimeStepMtd(), LsetCore_SaveGridMtd(), LsetCore_SetCircleSeedMtd(), LsetCore_SetGridMtd(), LsetCore_SetImageSeedMtd(), LsetCore_SetPdSeedMtd(), LsetCore_SetSaveProjectionSetsMtd(), LsetCore_SetSolidSeedMtd(), LsetCore_SetTimeMtd(), LsetCore_SetVelocityMtd(), LsetCore_SetVExtensionMtd(), LsetCore_VanishedMtd(), LsetV_GetMemoryUsageMtd(), LsetV_GetStopVMtd(), LsetV_SetStopVMtd(), LsetVConst_GetConstMtd(), LsetVConst_SetConstMtd(), LsetVExpDecay_GetConstMtd(), LsetVExpDecay_SetConstMtd(), LsetVImage_GetImageMtd(), LsetVImage_GetImageObjMtd(), LsetVImage_GetIntensityRangeMtd(), LsetVImage_GetMagGradRangeMtd(), LsetVImage_GetXYMagGradRangeMtd(), LsetVImage_GetZMagGradRangeMtd(), LsetVImage_SetImageMtd(), LsetVImage_SetImageObjMtd(), LsetVKGI_GetConstMtd(), LsetVKGI_SetConstMtd(), LsetVPotential_GetConstMtd(), LsetVPotential_SetConstMtd(), LsetVSmooth_GetConstMtd(), LsetVSmooth_SetConstMtd(), LsetVThr_GetConstMtd(), LsetVThr_SetConstMtd(), Math_computeWomersleyCmd(), Math_curveLengthCmd(), Math_FFTCmd(), Math_fitLeastSquaresCmd(), Math_inverseFFTCmd(), Math_linearInterpCmd(), Math_linearInterpolateCurveCmd(), Math_smoothCurveCmd(), Repos_ClearLabelCmd(), Repos_DeleteCmd(), Repos_ExistsCmd(), Repos_ExportToVtkCmd(), Repos_GetLabelCmd(), Repos_GetLabelKeysCmd(), Repos_ImportVtkImgCmd(), Repos_ImportVtkPdCmd(), Repos_ImportVtkSpCmd(), Repos_ImportVtkUnstructuredGridCmd(), Repos_ReadVtkPolyDataCmd(), Repos_SetLabelCmd(), Repos_TypeCmd(), Repos_WriteVtkPolyDataCmd(), Repos_WriteVtkStructuredPointsCmd(), Repos_WriteVtkUnstructuredGridCmd(), Solid_Apply4x4Mtd(), Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_ClassifyPtMtd(), Solid_ClearLabelMtd(), Solid_CombineFacesMtd(), Solid_CopyCmd(), Solid_CreateEdgeBlendMtd(), Solid_CylinderCmd(), Solid_DeleteFacesMtd(), Solid_DeleteRegionMtd(), Solid_DistanceMtd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_GetAxialIsoparametricCurveMtd(), Solid_GetBoundaryFacesMtd(), Solid_GetDiscontinuitiesMtd(), Solid_GetFaceAttrMtd(), Solid_GetFaceNormalMtd(), Solid_GetFacePolyDataMtd(), Solid_GetKernelMtd(), Solid_GetLabelKeysMtd(), Solid_GetLabelMtd(), Solid_GetPolyDataMtd(), Solid_GetRegionAttrMtd(), Solid_IntersectCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_ReflectMtd(), Solid_RemeshFaceMtd(), Solid_RotateMtd(), Solid_ScaleMtd(), Solid_SetFaceAttrMtd(), Solid_SetKernelCmd(), Solid_SetLabelMtd(), Solid_SetRegionAttrMtd(), Solid_SetVtkPolyDataMtd(), Solid_SphereCmd(), Solid_SubtractCmd(), Solid_TorusCmd(), Solid_TranslateMtd(), Solid_TruncatedConeCmd(), Solid_UnionCmd(), Solid_WriteNativeMtd(), and Solid_WriteVtkPolyDataMtd().
int ARG_ParseTclListDynamic (Tcl_Interp * interp, ARG_List list, ARG_Type t, void ** arr, int * numasn)
Definition at line 302 of file cv_arg.cxx.
References ARG_List_s::argc, ARG_List_s::argv, BOOL_Type, DOUBLE_Type, error(), INT_Type, LIST_Type, and STRING_Type.
int ARG_ParseTclListStatic (Tcl_Interp * interp, ARG_List list, ARG_Type t, void * arr, int arrsz, int * numasn)
Definition at line 225 of file cv_arg.cxx.
References ARG_List_s::argc, ARG_List_s::argv, BOOL_Type, DOUBLE_Type, error(), INT_Type, LIST_Type, NULL, and STRING_Type.
Referenced by cvMesh_SetBoundaryLayerMtd(), cvMesh_SetCylinderRefinementMtd(), cvMesh_SetSphereRefinementMtd(), FMMHelper(), gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_FastMarchCmd(), gdscITK_ReadRegionOfInterestCmd(), gdscPost_readVisResCmd(), Geom_ClassifyCmd(), Geom_DisorientProfileCmd(), Geom_FindDistanceCmd(), Geom_InterpolateScalarCmd(), Geom_InterpolateVectorCmd(), Geom_IntersectWithLineCmd(), Geom_OrientProfileCmd(), Geom_PtInPolyCmd(), Geom_TranslateCmd(), Image_ComputeStructuredCoordCmd(), Image_CreateDistanceMapCmd(), Image_FindPathCmd(), LsetCore_SetGridMtd(), LsetVImage_SetImageMtd(), Math_computeWomersleyCmd(), Math_curveLengthCmd(), Math_FFTCmd(), Math_fitLeastSquaresCmd(), Math_inverseFFTCmd(), Math_linearInterpCmd(), Math_linearInterpolateCurveCmd(), Math_smoothCurveCmd(), Solid_Apply4x4Mtd(), Solid_Box3dCmd(), Solid_CylinderCmd(), Solid_DeleteFacesMtd(), Solid_DistanceMtd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ReflectMtd(), Solid_RemeshFaceMtd(), Solid_RotateMtd(), Solid_SphereCmd(), Solid_TorusCmd(), Solid_TranslateMtd(), and Solid_TruncatedConeCmd().
int ARG_ParseTclStr (Tcl_Interp * interp, int argc, CONST84 char * argv[], int startIx, int table_size, ARG_Entry arg_table[])
Definition at line 64 of file cv_arg.cxx.
References ARG_Entry_s::addr, ARG_FindArgvIx(), ARG_List_s::argc, ARG_List_s::argv, BOOL_Type, DOUBLE_Type, error(), INT_Type, LIST_Type, MAX_ARGVAL_PAIRS, ARG_Entry_s::name, NULL, REQUIRED, ARG_Entry_s::required, ARG_Entry_s::str_repr, STRING_Type, ARG_Entry_s::type, and ARG_Entry_s::valid.
Referenced by cvMesh_GetBoundaryFacesMtd(), cvMesh_GetElementConnectivityMtd(), cvMesh_GetElementFacesOnModelFaceMtd(), cvMesh_GetElementNodesOnModelFaceMtd(), cvMesh_GetElementsInModelRegionMtd(), cvMesh_GetExteriorElementFacesOnRegionMtd(), cvMesh_GetFacePolyDataMtd(), cvMesh_GetNodeCoordsMtd(), cvMesh_GetPolyDataMtd(), cvMesh_GetUnstructuredGridMtd(), cvMesh_LoadMeshMtd(), cvMesh_LoadModelMtd(), cvMesh_LogonCmd(), cvMesh_NewObjectCmd(), cvMesh_SetBoundaryLayerMtd(), cvMesh_SetCylinderRefinementMtd(), cvMesh_SetGlobalCurvMtd(), cvMesh_SetGlobalMinCurvMtd(), cvMesh_SetGlobalSizeMtd(), cvMesh_SetLocalCurvMtd(), cvMesh_SetLocalMinCurvMtd(), cvMesh_SetLocalSizeMtd(), cvMesh_SetMeshKernelCmd(), cvMesh_SetMeshOptionsMtd(), cvMesh_SetSizeFunctionBasedMeshMtd(), cvMesh_SetSolidKernelMtd(), cvMesh_SetSphereRefinementMtd(), cvMesh_SetSurfaceMeshFlagMtd(), cvMesh_SetSurfaceOptimizationMtd(), cvMesh_SetSurfaceSmoothingMtd(), cvMesh_SetVolumeMeshFlagMtd(), cvMesh_SetVolumeOptimizationMtd(), cvMesh_SetVolumeSmoothingMtd(), cvMesh_SetVtkPolyDataMtd(), cvMesh_WriteABAQUSMtd(), cvMesh_WriteDataExplorerMtd(), cvMesh_WriteHypermeshMtd(), cvMesh_WriteMeshMtd(), cvMesh_WriteMeshVRMLMtd(), cvMesh_WriteMetisAdjacencyMtd(), cvMesh_WritePROPHLEXMtd(), cvMesh_WriteSpectrumSolverElementsMtd(), cvMesh_WriteSpectrumSolverNodesMtd(), cvMesh_WriteSpectrumVisMtd(), cvMesh_WriteStatsMtd(), cvMesh_WriteSurfaceMeshOOGLMtd(), cvMesh_WriteSurfaceMeshVRMLMtd(), gdscITK_createSignedDistanceImageWithFMMCmd(), gdscITK_expNegativeImageCmd(), gdscITK_FastMarchCmd(), gdscITK_MinMaxCurvSmoothCmd(), gdscITK_ReadRegionOfInterestCmd(), gdscITK_shapeDetectionCmd(), gdscITK_SigMapCmd(), gdscITK_TLSF_Cmd(), gdscPost_calcAvgPointDataCmd(), gdscPost_calcOSICmd(), gdscPost_calcTKECmd(), gdscPost_calcWallShearCmd(), gdscPost_calcWallShearMeanCmd(), gdscPost_calcWallShearPulseCmd(), gdscPost_readVisMeshCmd(), gdscPost_readVisResCmd(), Geom_2dWindingNumCmd(), Geom_AddPointDataCmd(), Geom_AlignProfileCmd(), Geom_AvgPtCmd(), Geom_BBoxCmd(), Geom_CheckSurfaceCmd(), Geom_ClassifyCmd(), Geom_CopyCmd(), Geom_DisorientProfileCmd(), Geom_DividePointDataCmd(), Geom_FindDistanceCmd(), Geom_GetClosedLineRegionCmd(), Geom_GetOrderedPtsCmd(), Geom_GetPolyCentroidCmd(), Geom_IntegrateEnergyCmd(), Geom_IntegrateScalarSurfCmd(), Geom_IntegrateScalarThreshCmd(), Geom_IntegrateSurface2Cmd(), Geom_IntegrateSurfaceCmd(), Geom_InterpolateScalarCmd(), Geom_InterpolateVectorCmd(), Geom_IntersectCmd(), Geom_IntersectWithLineCmd(), Geom_MakePolysConsistentCmd(), Geom_MergePtsCmd(), Geom_MultiplyPointDataCmd(), Geom_NumClosedLineRegionsCmd(), Geom_NumPtsCmd(), Geom_OrientProfileCmd(), Geom_PickCmd(), Geom_PolygonNormCmd(), Geom_PolysClosedCmd(), Geom_PrintSmallPolysCmd(), Geom_PrintTriStatsCmd(), Geom_ProjectCmd(), Geom_PtInPolyCmd(), Geom_ReduceCmd(), Geom_ReorderPgnCmd(), Geom_ReplacePointDataCmd(), Geom_ReverseAllCellsCmd(), Geom_RmSmallPolysCmd(), Geom_sampleLoopCmd(), Geom_ScaleAvgCmd(), Geom_SplinePtsToPathPlanCmd(), Geom_SubtractCmd(), Geom_SubtractPointDataCmd(), Geom_SurfAreaCmd(), Geom_TranslateCmd(), Geom_UnionCmd(), Geom_Warp3dPtsCmd(), Geom_WriteLinesCmd(), Geom_WriteOrderedPtsCmd(), Image_CalcCorrectionEqnAutoCmd(), Image_CalcCorrectionEqnCmd(), Image_ComputeStructuredCoordCmd(), Image_CreateDistanceMapCmd(), Image_DecodeCmd(), Image_FindPathCmd(), Image_MaskInPlaceCmd(), Image_ReadHeaderCmd(), Image_ThresholdCmd(), LsetCore_ExtractActiveNodesMtd(), LsetCore_ExtractCoveredNodesMtd(), LsetCore_ExtractCurvatureMtd(), LsetCore_ExtractForceMinVNodesMtd(), LsetCore_ExtractFrontMtd(), LsetCore_ExtractMineNodesMtd(), LsetCore_ExtractPhiMtd(), LsetCore_ExtractProjectionSetsMtd(), LsetCore_ExtractUncoveredNodesMtd(), LsetCore_ExtractVelMtd(), LsetCore_GetBoundaryDataMtd(), LsetCore_SaveGridMtd(), LsetCore_SetCircleSeedMtd(), LsetCore_SetGridMtd(), LsetCore_SetImageSeedMtd(), LsetCore_SetPdSeedMtd(), LsetCore_SetSaveProjectionSetsMtd(), LsetCore_SetSolidSeedMtd(), LsetCore_SetTimeMtd(), LsetCore_SetVelocityMtd(), LsetCore_SetVExtensionMtd(), LsetV_SetStopVMtd(), LsetVConst_SetConstMtd(), LsetVExpDecay_SetConstMtd(), LsetVImage_GetImageObjMtd(), LsetVImage_SetImageMtd(), LsetVImage_SetImageObjMtd(), LsetVKGI_SetConstMtd(), LsetVPotential_SetConstMtd(), LsetVSmooth_SetConstMtd(), LsetVThr_SetConstMtd(), Math_computeWomersleyCmd(), Math_curveLengthCmd(), Math_FFTCmd(), Math_fitLeastSquaresCmd(), Math_inverseFFTCmd(), Math_linearInterpCmd(), Math_linearInterpolateCurveCmd(), Math_smoothCurveCmd(), Repos_ClearLabelCmd(), Repos_DeleteCmd(), Repos_ExistsCmd(), Repos_ExportToVtkCmd(), Repos_GetLabelCmd(), Repos_GetLabelKeysCmd(), Repos_ImportVtkImgCmd(), Repos_ImportVtkPdCmd(), Repos_ImportVtkSpCmd(), Repos_ImportVtkUnstructuredGridCmd(), Repos_ReadVtkPolyDataCmd(), Repos_SetLabelCmd(), Repos_TypeCmd(), Repos_WriteVtkPolyDataCmd(), Repos_WriteVtkStructuredPointsCmd(), Repos_WriteVtkUnstructuredGridCmd(), Solid_Apply4x4Mtd(), Solid_Box2dCmd(), Solid_Box3dCmd(), Solid_CapSurfToSolidCmd(), Solid_CircleCmd(), Solid_ClassifyPtMtd(), Solid_ClearLabelMtd(), Solid_CombineFacesMtd(), Solid_CopyCmd(), Solid_CreateEdgeBlendMtd(), Solid_CylinderCmd(), Solid_DeleteFacesMtd(), Solid_DeleteRegionMtd(), Solid_DistanceMtd(), Solid_EllipseCmd(), Solid_EllipsoidCmd(), Solid_ExtrudeCmd(), Solid_ExtrudeZCmd(), Solid_GetAxialIsoparametricCurveMtd(), Solid_GetBoundaryFacesMtd(), Solid_GetDiscontinuitiesMtd(), Solid_GetFaceAttrMtd(), Solid_GetFaceNormalMtd(), Solid_GetFacePolyDataMtd(), Solid_GetLabelMtd(), Solid_GetPolyDataMtd(), Solid_GetRegionAttrMtd(), Solid_IntersectCmd(), Solid_MakeApproxCurveLoopCmd(), Solid_MakeInterpCurveLoopCmd(), Solid_MakeLoftedSurfCmd(), Solid_Poly3dSolidCmd(), Solid_Poly3dSurfaceCmd(), Solid_PolyCmd(), Solid_PolyPtsCmd(), Solid_ReadNativeCmd(), Solid_ReflectMtd(), Solid_RemeshFaceMtd(), Solid_RotateMtd(), Solid_ScaleMtd(), Solid_SetFaceAttrMtd(), Solid_SetKernelCmd(), Solid_SetLabelMtd(), Solid_SetRegionAttrMtd(), Solid_SetVtkPolyDataMtd(), Solid_SphereCmd(), Solid_SubtractCmd(), Solid_TorusCmd(), Solid_TranslateMtd(), Solid_TruncatedConeCmd(), Solid_UnionCmd(), Solid_WriteNativeMtd(), and Solid_WriteVtkPolyDataMtd().
void ARG_Show (int table_size, ARG_Entry arg_table[])
Definition at line 474 of file cv_arg.cxx.
References ARG_Entry_s::addr, ARG_List_s::argc, ARG_List_s::argv, BOOL_Type, DOUBLE_Type, INT_Type, LIST_Type, ARG_Entry_s::name, STRING_Type, and ARG_Entry_s::type.
void tcl_printstr (Tcl_Interp * interp, char * str)
Definition at line 521 of file cv_arg.cxx.
References NULL.
Referenced by gdscMeshPrintMethods(), and PrintMethods().