simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/Adaptor/Adapt/cvAdaptHelpers.cxx File Reference
cvAdaptHelpers.cxx File Reference
#include "cvAdaptHelp.h"
Functions
double Bn (int i, int j, int k, double r, double s, double t)
double Bn_2ndChunk (int i, int j, int k, double r, double s, double t)
double Bn_3rdChunk (int i, int j, int k, double r, double s, double t)
double Bn_4thChunk (int i, int j, int k, double r, double s, double t)
double En (int ip, double r, double s)
double Fn (int i, int j, double r, double s)
double E_modeShape (int p, double *L)
double F_modeShapeTri (int p, int i, double *L)
double F_modeShapeQuad (int p, int i, double *L)
double R_modeShapeTet (int p, int i, double *L)
double R_modeShapeHex (int p, int i, double *L)
Function Documentation
double Bn (int i, int j, int k, double r, double s, double t)
Definition at line 45 of file cvAdaptHelpers.cxx.
References Bn_2ndChunk().
Referenced by R_modeShapeTet().
double Bn_2ndChunk (int i, int j, int k, double r, double s, double t)
Definition at line 991 of file cvAdaptHelpers.cxx.
References Bn_3rdChunk().
Referenced by Bn().
double Bn_3rdChunk (int i, int j, int k, double r, double s, double t)
Definition at line 2008 of file cvAdaptHelpers.cxx.
References Bn_4thChunk().
Referenced by Bn_2ndChunk().
double Bn_4thChunk (int i, int j, int k, double r, double s, double t)
Definition at line 3411 of file cvAdaptHelpers.cxx.
Referenced by Bn_3rdChunk().
double E_modeShape (int p, double * L)
Definition at line 5529 of file cvAdaptHelpers.cxx.
References En().
Referenced by Entity_shapeFunction().
double En (int ip, double r, double s)
Definition at line 4191 of file cvAdaptHelpers.cxx.
Referenced by E_modeShape().
double F_modeShapeQuad (int p, int i, double * L)
Definition at line 5567 of file cvAdaptHelpers.cxx.
Referenced by Entity_shapeFunction().
double F_modeShapeTri (int p, int i, double * L)
Definition at line 5538 of file cvAdaptHelpers.cxx.
References alpha, and Fn().
Referenced by Entity_shapeFunction().
double Fn (int i, int j, double r, double s)
Definition at line 4371 of file cvAdaptHelpers.cxx.
Referenced by F_modeShapeTri().
double R_modeShapeHex (int p, int i, double * L)
Definition at line 5606 of file cvAdaptHelpers.cxx.
Referenced by Entity_shapeFunction().
double R_modeShapeTet (int p, int i, double * L)
Definition at line 5572 of file cvAdaptHelpers.cxx.
References alpha, Bn(), and gamma.
Referenced by Entity_shapeFunction().