simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvRepositoryData.cxx File Reference
cvRepositoryData.cxx File Reference
#include "SimVascular.h"
#include "cvRepositoryData.h"
#include "cvIOstream.h"
#include <string.h>
Functions
RepositoryDataT RepositoryDataT_StrToEnum (char *name)
char * RepositoryDataT_EnumToStr (RepositoryDataT val)
Function Documentation
char* RepositoryDataT_EnumToStr (RepositoryDataT val)
Definition at line 61 of file cvRepositoryData.cxx.
References MESH_T, OBJ_NOT_FOUND_T, POLY_DATA_T, SOLID_MODEL_T, STRUCTURED_PTS_T, TEMPORALDATASET_T, and UNSTRUCTURED_GRID_T.
Referenced by itkls2d_SetInputsMtd(), itkls3d_SetInputsMtd(), and Repos_TypeCmd().
RepositoryDataT RepositoryDataT_StrToEnum (char * name)
Definition at line 44 of file cvRepositoryData.cxx.
References OBJ_NOT_FOUND_T, RDT_INVALID, and SOLID_MODEL_T.