simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Core/Repository/cvRepositoryData.h File Reference
cvRepositoryData.h File Reference
#include "SimVascular.h"
#include "tcl.h"
Classes
class cvRepositoryData
Macros
#define RD_MAX_NAME_LEN 1024
Enumerations
enum RepositoryDataT {
RDT_INVALID = -1, OBJ_NOT_FOUND_T, POLY_DATA_T, STRUCTURED_PTS_T,
UNSTRUCTURED_GRID_T, SOLID_MODEL_T, MESH_T, TEMPORALDATASET_T
}
Functions
RepositoryDataT RepositoryDataT_StrToEnum (char *name)
char * RepositoryDataT_EnumToStr (RepositoryDataT val)
Macro Definition Documentation
#define RD_MAX_NAME_LEN 1024
Definition at line 38 of file cvRepositoryData.h.
Referenced by cvRepositoryData::SetName().
Enumeration Type Documentation
enum RepositoryDataT
Enumerator
RDT_INVALID
OBJ_NOT_FOUND_T
POLY_DATA_T
STRUCTURED_PTS_T
UNSTRUCTURED_GRID_T
SOLID_MODEL_T
MESH_T
TEMPORALDATASET_T
Definition at line 45 of file cvRepositoryData.h.
Function Documentation
char* RepositoryDataT_EnumToStr (RepositoryDataT val)
Definition at line 61 of file cvRepositoryData.cxx.
References MESH_T, OBJ_NOT_FOUND_T, POLY_DATA_T, SOLID_MODEL_T, STRUCTURED_PTS_T, TEMPORALDATASET_T, and UNSTRUCTURED_GRID_T.
Referenced by itkls2d_SetInputsMtd(), itkls3d_SetInputsMtd(), and Repos_TypeCmd().
RepositoryDataT RepositoryDataT_StrToEnum (char * name)
Definition at line 44 of file cvRepositoryData.cxx.
References OBJ_NOT_FOUND_T, RDT_INVALID, and SOLID_MODEL_T.