simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PreSolver/directsolve.c File Reference
directsolve.c File Reference
#include "cvFlowsolverOptions.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "spMatrix.h"
Classes
struct Kentry
Macros
#define SPARSE_OFFSET 1
Functions
int debugprint (FILE *, char *,...)
void deleteKentries (Kentry *Kentries)
int StanfordSolveSparseMatrix (Kentry *Kentries, double b[], int numUniqueEntries, int size, double soln[])
Variables
FILE * stddbg
int verbose_
Macro Definition Documentation
#define SPARSE_OFFSET 1
Definition at line 53 of file directsolve.c.
Referenced by StanfordSolveSparseMatrix().
Function Documentation
int debugprint (FILE * , char * , ...)
Definition at line 126 of file cmd.cxx.
References CV_OK, NULL, and verbose_.
Referenced by calcInitDisplacements(), calcInitDisplacements_var_prop(), check_node_order(), cmd_adjacency(), cmd_append_displacements(), cmd_ascii_format(), cmd_boundary_faces(), cmd_create_mesh_deformable(), cmd_create_mesh_deformable_vtp(), cmd_cvsolver_node_order(), cmd_deformable_Evw(), cmd_deformable_kcons(), cmd_deformable_nuvw(), cmd_deformable_pressure(), cmd_deformable_solve(), cmd_deformable_thickness(), cmd_deformable_wall(), cmd_deformable_wall_vtp(), cmd_deformable_write_feap(), cmd_deformable_write_vtk_mesh(), cmd_elements(), cmd_fix_free_edge_nodes(), cmd_fix_free_edge_nodes_vtp(), cmd_initial_pressure(), cmd_initial_velocity(), cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), cmd_nodes(), cmd_noslip(), cmd_noslip_vtp(), cmd_number_of_elements(), cmd_number_of_mesh_edges(), cmd_number_of_mesh_faces(), cmd_number_of_nodes(), cmd_number_of_solnvars(), cmd_prescribed_velocities(), cmd_prescribed_velocities_vtp(), cmd_pressure(), cmd_pressure_vtp(), cmd_proc(), cmd_read_accelerations_vtu(), cmd_read_all_variables_vtu(), cmd_read_displacements(), cmd_read_displacements_vtu(), cmd_read_pressure_velocity_vtu(), cmd_read_pressure_vtu(), cmd_read_restart_accelerations(), cmd_read_restart_displacements(), cmd_read_restart_solution(), cmd_read_varwallprop_vtu(), cmd_read_velocity_vtu(), cmd_set_surface_id(), cmd_set_surface_id_vtp(), cmd_verbose(), cmd_write_geombcdat(), cmd_write_restartdat(), cmd_zero_pressure(), cmd_zero_pressure_vtp(), createMeshForDispCalc(), fixFreeEdgeNodes(), main(), read_variables_vtu(), setBoundaryFacesWithCode(), setBoundaryFacesWithCodeVTK(), setNodesWithCode(), StanfordIterativeSolve(), and StanfordSolveSparseMatrix().
void deleteKentries (Kentry * Kentries)
Definition at line 564 of file displacements.cxx.
Referenced by StanfordSolveSparseMatrix().
int StanfordSolveSparseMatrix (Kentry * Kentries, double b[], int numUniqueEntries, int size, double soln[])
Definition at line 55 of file directsolve.c.
References A, Kentry::col, debugprint(), deleteKentries(), NULL, Kentry::row, SPARSE_OFFSET, stddbg, and Kentry::value.
Variable Documentation
FILE* stddbg
Definition at line 42 of file cmd.cxx.
Referenced by calcInitDisplacements(), calcInitDisplacements_var_prop(), cmd_adjacency(), cmd_append_displacements(), cmd_ascii_format(), cmd_boundary_faces(), cmd_create_mesh_deformable(), cmd_create_mesh_deformable_vtp(), cmd_cvsolver_node_order(), cmd_deformable_Evw(), cmd_deformable_kcons(), cmd_deformable_nuvw(), cmd_deformable_pressure(), cmd_deformable_solve(), cmd_deformable_thickness(), cmd_deformable_wall(), cmd_deformable_wall_vtp(), cmd_deformable_write_feap(), cmd_deformable_write_vtk_mesh(), cmd_elements(), cmd_fix_free_edge_nodes(), cmd_fix_free_edge_nodes_vtp(), cmd_initial_pressure(), cmd_initial_velocity(), cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), cmd_nodes(), cmd_noslip(), cmd_noslip_vtp(), cmd_number_of_elements(), cmd_number_of_mesh_edges(), cmd_number_of_mesh_faces(), cmd_number_of_nodes(), cmd_number_of_solnvars(), cmd_prescribed_velocities(), cmd_prescribed_velocities_vtp(), cmd_pressure(), cmd_pressure_vtp(), cmd_proc(), cmd_read_accelerations_vtu(), cmd_read_all_variables_vtu(), cmd_read_displacements(), cmd_read_displacements_vtu(), cmd_read_pressure_velocity_vtu(), cmd_read_pressure_vtu(), cmd_read_restart_accelerations(), cmd_read_restart_displacements(), cmd_read_restart_solution(), cmd_read_varwallprop_vtu(), cmd_read_velocity_vtu(), cmd_set_surface_id(), cmd_set_surface_id_vtp(), cmd_verbose(), cmd_write_geombcdat(), cmd_write_restartdat(), cmd_zero_pressure(), cmd_zero_pressure_vtp(), createMeshForDispCalc(), fixFreeEdgeNodes(), main(), read_variables_vtu(), setBoundaryFacesWithCode(), setBoundaryFacesWithCodeVTK(), setNodesWithCode(), StanfordIterativeSolve(), and StanfordSolveSparseMatrix().
int verbose_
Definition at line 48 of file supre.cxx.