simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/PreSolver/helpers.cxx File Reference
helpers.cxx File Reference
#include "cvFlowsolverOptions.h"
#include "cmd.h"
#include "cvSolverIO.h"
#include <stdlib.h>
#include <time.h>
Macros
#define gzopen fopen
#define gzprintf fprintf
#define gzFile FILE*
#define gzclose fclose
#define gzgets fgets
#define gzeof feof
Functions
void Cross (double ax, double ay, double az, double bx, double by, double bz, double *prodx, double *prody, double *prodz)
double Dot (double ax, double ay, double az, double bx, double by, double bz)
int writeGEOMBCDAT (char *filename)
int NWopenFile (char *filename)
int NWcloseFile ()
int NWgetNextLine (int *eof)
int NWgetNextNonBlankLine (int *eof)
int parseCmdStr (char *cmd, char *mystr)
int parseNum (char *cmd, int *num)
int parseNum2 (char *cmd, int *num)
int parseDouble (char *cmd, double *num)
int parseDouble2 (char *cmd, double *num)
int parseDouble3 (char *cmd, double *v1, double *v2, double *v3)
int parseFile (char *cmd)
int setNodesWithCode (char *cmd, int val)
int check_node_order (int n0, int n1, int n2, int n3, int elementId, int *k0, int *k1, int *k2, int *k3)
int setBoundaryFacesWithCode (char *cmd, int setSurfID, int surfID, int setCode, int code, double value)
void siftDownEdges (int **edges, int root, int bottom, int array_size)
int fixFreeEdgeNodes (char *cmd)
void siftDownKentriesCalcMesh (int **ids, int root, int bottom, int array_size)
int createMeshForDispCalc (char *cmd)
Variables
char * oformat
int numNodes_
int numElements_
int numMeshEdges_
int numMeshFaces_
int numSolnVars_
int numBoundaryFaces_
int ** boundaryElements_
double * nodes_
int * elements_
int * boundaryElementsIds_
int * xadj_
int xadjSize_
int * adjncy_
int adjncySize_
int * iBC_
int * iBCB_
double * BCB_
int DisplacementNumElements_
int * DisplacementConn_ [3]
int DisplacementNumNodes_
int * DisplacementNodeMap_
FILE * fp_ = NULL
char buffer_ [1024]
Macro Definition Documentation
#define gzclose fclose
Definition at line 44 of file helpers.cxx.
Referenced by NWcloseFile().
#define gzeof feof
Definition at line 46 of file helpers.cxx.
Referenced by NWgetNextLine().
#define gzFile FILE*
Definition at line 43 of file helpers.cxx.
#define gzgets fgets
Definition at line 45 of file helpers.cxx.
Referenced by NWgetNextLine(), cvConvertVisFiles::readNextLineFromFile(), and test_gzio().
#define gzopen fopen
Definition at line 41 of file helpers.cxx.
Referenced by NWopenFile().
#define gzprintf fprintf
Definition at line 42 of file helpers.cxx.
Function Documentation
int check_node_order (int n0, int n1, int n2, int n3, int elementId, int * k0, int * k1, int * k2, int * k3)
Definition at line 374 of file helpers.cxx.
References c, Cross(), CV_ERROR, CV_OK, cvsolver_node_order_, debugprint(), Dot(), elements_, nodes_, numElements_, and numNodes_.
Referenced by cmd_boundary_faces(), cmd_elements(), cmd_mesh_and_adjncy_vtu(), and cmd_mesh_vtu().
int createMeshForDispCalc (char * cmd)
Definition at line 854 of file helpers.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), DisplacementConn_, DisplacementNodeMap_, DisplacementNumElements_, DisplacementNumNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), siftDownKentriesCalcMesh(), and stddbg.
Referenced by cmd_create_mesh_deformable().
void Cross (double ax, double ay, double az, double bx, double by, double bz, double * prodx, double * prody, double * prodz) inline
Definition at line 55 of file helpers.cxx.
Referenced by check_node_order(), and setBoundaryFacesWithCode().
double Dot (double ax, double ay, double az, double bx, double by, double bz) inline
Definition at line 71 of file helpers.cxx.
Referenced by check_node_order(), and setBoundaryFacesWithCode().
int fixFreeEdgeNodes (char * cmd)
Definition at line 620 of file helpers.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), edges, iBC_, NULL, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), siftDownEdges(), and stddbg.
Referenced by cmd_fix_free_edge_nodes().
int NWcloseFile ()
Definition at line 130 of file helpers.cxx.
References CV_OK, fp_, gzclose, and NULL.
Referenced by cmd_adjacency(), cmd_boundary_faces(), cmd_elements(), cmd_nodes(), cmd_read_displacements(), createMeshForDispCalc(), fixFreeEdgeNodes(), setBoundaryFacesWithCode(), and setNodesWithCode().
int NWgetNextLine (int * eof)
Definition at line 141 of file helpers.cxx.
References buffer_, CV_OK, fp_, gzeof, gzgets, and MAXCMDLINELENGTH.
Referenced by NWgetNextNonBlankLine().
int NWgetNextNonBlankLine (int * eof)
Definition at line 157 of file helpers.cxx.
References buffer_, CV_ERROR, CV_OK, MAXCMDLINELENGTH, and NWgetNextLine().
Referenced by cmd_adjacency(), cmd_boundary_faces(), cmd_elements(), cmd_nodes(), cmd_read_displacements(), createMeshForDispCalc(), fixFreeEdgeNodes(), setBoundaryFacesWithCode(), and setNodesWithCode().
int NWopenFile (char * filename)
Definition at line 112 of file helpers.cxx.
References CV_ERROR, CV_OK, fp_, gzopen, and NULL.
Referenced by parseFile().
int parseCmdStr (char * cmd, char * mystr)
Definition at line 168 of file helpers.cxx.
References cmd_token_get(), CV_OK, and MAXSTRINGLENGTH.
Referenced by cmd_append_displacements(), cmd_create_mesh_deformable_vtp(), cmd_deformable_write_feap(), cmd_deformable_write_vtk_mesh(), cmd_fix_free_edge_nodes_vtp(), cmd_mesh_and_adjncy_vtu(), cmd_mesh_vtu(), cmd_noslip_vtp(), cmd_read_all_variables_vtu(), cmd_read_pressure_velocity_vtu(), cmd_read_restart_accelerations(), cmd_read_restart_displacements(), cmd_read_restart_solution(), cmd_write_restartdat(), parseDouble(), parseFile(), parseNum(), and setBoundaryFacesWithCodeVTK().
int parseDouble (char * cmd, double * num)
Definition at line 231 of file helpers.cxx.
References CV_ERROR, CV_OK, MAXSTRINGLENGTH, and parseCmdStr().
Referenced by cmd_deformable_Evw(), cmd_deformable_kcons(), cmd_deformable_nuvw(), cmd_deformable_pressure(), cmd_deformable_thickness(), and cmd_initial_pressure().
int parseDouble2 (char * cmd, double * num)
Definition at line 249 of file helpers.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, and MAXSTRINGLENGTH.
Referenced by cmd_pressure(), and cmd_pressure_vtp().
int parseDouble3 (char * cmd, double * v1, double * v2, double * v3)
Definition at line 278 of file helpers.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, MAXPATHLEN, and MAXSTRINGLENGTH.
Referenced by cmd_initial_velocity().
int parseFile (char * cmd)
Definition at line 318 of file helpers.cxx.
References MAXPATHLEN, NWopenFile(), and parseCmdStr().
Referenced by cmd_adjacency(), cmd_boundary_faces(), cmd_elements(), cmd_nodes(), cmd_read_displacements(), createMeshForDispCalc(), fixFreeEdgeNodes(), setBoundaryFacesWithCode(), and setNodesWithCode().
int parseNum (char * cmd, int * num)
Definition at line 181 of file helpers.cxx.
References CV_ERROR, CV_OK, MAXSTRINGLENGTH, and parseCmdStr().
Referenced by cmd_number_of_elements(), cmd_number_of_mesh_edges(), cmd_number_of_mesh_faces(), cmd_number_of_nodes(), and cmd_number_of_solnvars().
int parseNum2 (char * cmd, int * num)
Definition at line 199 of file helpers.cxx.
References cmd_token_get(), CV_ERROR, CV_OK, MAXPATHLEN, and MAXSTRINGLENGTH.
Referenced by cmd_set_surface_id(), and cmd_set_surface_id_vtp().
int setBoundaryFacesWithCode (char * cmd, int setSurfID, int surfID, int setCode, int code, double value)
Definition at line 454 of file helpers.cxx.
References BCB_, boundaryElements_, boundaryElementsIds_, buffer_, c, Cross(), CV_ERROR, CV_OK, debugprint(), Dot(), elements_, iBCB_, nodes_, NULL, numBoundaryFaces_, numElements_, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
Referenced by cmd_deformable_wall(), cmd_pressure(), cmd_set_surface_id(), and cmd_zero_pressure().
int setNodesWithCode (char * cmd, int val)
Definition at line 329 of file helpers.cxx.
References buffer_, CV_ERROR, CV_OK, debugprint(), iBC_, NULL, numNodes_, NWcloseFile(), NWgetNextNonBlankLine(), parseFile(), and stddbg.
Referenced by cmd_noslip(), and cmd_prescribed_velocities().
void siftDownEdges (int ** edges, int root, int bottom, int array_size)
Definition at line 578 of file helpers.cxx.
Referenced by cmd_fix_free_edge_nodes_vtp(), and fixFreeEdgeNodes().
void siftDownKentriesCalcMesh (int ** ids, int root, int bottom, int array_size)
Definition at line 813 of file helpers.cxx.
Referenced by cmd_create_mesh_deformable_vtp(), and createMeshForDispCalc().
int writeGEOMBCDAT (char * filename)
Definition at line 1940 of file supre-cmds.cxx.
Variable Documentation
int* adjncy_
Definition at line 63 of file supre.cxx.
int adjncySize_
Definition at line 64 of file supre.cxx.
double* BCB_
Definition at line 67 of file supre.cxx.
Referenced by setBoundaryFacesWithCode().
int** boundaryElements_
Definition at line 59 of file supre.cxx.
Referenced by setBoundaryFacesWithCode().
int* boundaryElementsIds_
Definition at line 60 of file supre.cxx.
Referenced by setBoundaryFacesWithCode().
char buffer_[1024]
Definition at line 110 of file helpers.cxx.
Referenced by cmd_adjacency(), cmd_boundary_faces(), cmd_elements(), cmd_nodes(), cmd_read_displacements(), createMeshForDispCalc(), fixFreeEdgeNodes(), NWgetNextLine(), NWgetNextNonBlankLine(), setBoundaryFacesWithCode(), and setNodesWithCode().
int* DisplacementConn_[3]
Definition at line 83 of file supre.cxx.
Referenced by createMeshForDispCalc().
int* DisplacementNodeMap_
Definition at line 85 of file supre.cxx.
Referenced by createMeshForDispCalc().
int DisplacementNumElements_
Definition at line 82 of file supre.cxx.
Referenced by createMeshForDispCalc().
int DisplacementNumNodes_
Definition at line 84 of file supre.cxx.
Referenced by createMeshForDispCalc().
int* elements_
Definition at line 58 of file supre.cxx.
Referenced by check_node_order(), and setBoundaryFacesWithCode().
FILE* fp_ = NULL
Definition at line 109 of file helpers.cxx.
Referenced by NWcloseFile(), NWgetNextLine(), and NWopenFile().
int* iBC_
Definition at line 65 of file supre.cxx.
Referenced by fixFreeEdgeNodes(), and setNodesWithCode().
int* iBCB_
Definition at line 66 of file supre.cxx.
Referenced by setBoundaryFacesWithCode().
double* nodes_
Definition at line 57 of file supre.cxx.
Referenced by check_node_order(), and setBoundaryFacesWithCode().
int numBoundaryFaces_
Definition at line 56 of file supre.cxx.
Referenced by setBoundaryFacesWithCode().
int numElements_
Definition at line 52 of file supre.cxx.
Referenced by check_node_order(), and setBoundaryFacesWithCode().
int numMeshEdges_
Definition at line 53 of file supre.cxx.
int numMeshFaces_
Definition at line 54 of file supre.cxx.
int numNodes_
Definition at line 51 of file supre.cxx.
Referenced by check_node_order(), fixFreeEdgeNodes(), setBoundaryFacesWithCode(), and setNodesWithCode().
int numSolnVars_
Definition at line 55 of file supre.cxx.
char* oformat
Definition at line 46 of file supre.cxx.
Referenced by cvAdaptCore::writeRestartHessians().
int* xadj_
Definition at line 61 of file supre.cxx.
int xadjSize_
Definition at line 62 of file supre.cxx.