simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/ThirdParty/zlib/simvascular_zlib/infback.c File Reference
infback.c File Reference
#include "zutil.h"
#include "inftrees.h"
#include "inflate.h"
#include "inffast.h"
#include "inffixed.h"
Macros
#define LOAD()
#define RESTORE()
#define INITBITS()
#define PULL()
#define PULLBYTE()
#define NEEDBITS(n)
#define BITS(n) ((unsigned)hold & ((1U << (n)) - 1))
#define DROPBITS(n)
#define BYTEBITS()
#define ROOM()
Functions
static void fixedtables ()
int cv_zlib_inflateBackInit_ (z_streamp strm, int windowBits, unsigned char *window, char *version, int stream_size)
static void fixedtables (struct inflate_state *state)
int cv_zlib_inflateBack (z_streamp strm, in_func in, void *in_desc, out_func out, void *out_desc)
int cv_zlib_inflateBackEnd (z_streamp strm)
Macro Definition Documentation
#define BITS (n) ((unsigned)hold & ((1U << (n)) - 1))
Definition at line 181 of file infback.c.
Referenced by cv_zlib_inflateBack().
#define BYTEBITS ()
Value:
do { \
        hold >>= bits & 7; \
        bits -= bits & 7; \
    } while (0)
Definition at line 192 of file infback.c.
Referenced by cv_zlib_inflateBack().
#define DROPBITS (n)
Value:
do { \
        hold >>= (n); \
        bits -= (unsigned)(n); \
    } while (0)
Definition at line 185 of file infback.c.
Referenced by cv_zlib_inflateBack().
#define INITBITS ()
Value:
do { \
        hold = 0; \
        bits = 0; \
    } while (0)
Definition at line 141 of file infback.c.
Referenced by cv_zlib_inflateBack().
#define LOAD ()
Value:
do { \
        put = strm->next_out; \
        left = strm->avail_out; \
        next = strm->next_in; \
        have = strm->avail_in; \
        hold = state->hold; \
        bits = state->bits; \
    } while (0)
Definition at line 119 of file infback.c.
Referenced by cv_zlib_inflateBack().
#define NEEDBITS (n)
Value:
do { \
        while (bits < (unsigned)(n)) \
            PULLBYTE(); \
    } while (0)
Definition at line 174 of file infback.c.
Referenced by cv_zlib_inflateBack().
#define PULL ()
Value:
do { \
        if (have == 0) { \
            have = in(in_desc, &next); \
            if (have == 0) { \
                next = Z_NULL; \
                ret = Z_BUF_ERROR; \
                goto inf_leave; \
            } \
        } \
    } while (0)
Definition at line 149 of file infback.c.
Referenced by cv_zlib_inflateBack().
#define PULLBYTE ()
Value:
do { \
        PULL(); \
        have--; \
        hold += (unsigned long)(*next++) << bits; \
        bits += 8; \
    } while (0)
Definition at line 163 of file infback.c.
Referenced by cv_zlib_inflateBack().
#define RESTORE ()
Value:
do { \
        strm->next_out = put; \
        strm->avail_out = left; \
        strm->next_in = next; \
        strm->avail_in = have; \
        state->hold = hold; \
        state->bits = bits; \
    } while (0)
Definition at line 130 of file infback.c.
Referenced by cv_zlib_inflateBack().
#define ROOM ()
Value:
do { \
        if (left == 0) { \
            put = state->window; \
            left = state->wsize; \
            state->whave = left; \
            if (out(out_desc, put, left)) { \
                ret = Z_BUF_ERROR; \
                goto inf_leave; \
            } \
        } \
    } while (0)
Definition at line 201 of file infback.c.
Referenced by cv_zlib_inflateBack().
Function Documentation
int cv_zlib_inflateBack (z_streamp strm, in_func in, void * in_desc, out_func out, void * out_desc)
Definition at line 241 of file infback.c.
References BAD, code::bits, inflate_state::bits, BITS, BYTEBITS, CODES, inflate_state::codes, inflate_state::distbits, inflate_state::distcode, DISTS, DONE, DROPBITS, inflate_state::extra, fixedtables(), for, inflate_state::have, inflate_state::hold, inflate_fast(), inflate_table(), INITBITS, inflate_state::last, LEN, inflate_state::lenbits, inflate_state::lencode, inflate_state::length, LENS, inflate_state::lens, LOAD, inflate_state::mode, inflate_state::ncode, inflate_state::ndist, NEEDBITS, inflate_state::next, inflate_state::nlen, inflate_state::offset, code::op, order, PULL, PULLBYTE, RESTORE, ROOM, STORED, TABLE, Tracev, Tracevv, TYPE, code::val, inflate_state::whave, inflate_state::window, inflate_state::work, inflate_state::wsize, Z_BUF_ERROR, Z_DATA_ERROR, Z_NULL, Z_STREAM_END, Z_STREAM_ERROR, and zmemcpy().
int cv_zlib_inflateBackEnd (z_streamp strm)
Definition at line 614 of file infback.c.
References Tracev, Z_NULL, Z_OK, Z_STREAM_ERROR, and ZFREE.
int cv_zlib_inflateBackInit_ (z_streamp strm, int windowBits, unsigned char * window, char * version, int stream_size)
Definition at line 28 of file infback.c.
References inflate_state::dmax, Tracev, U, inflate_state::wbits, inflate_state::whave, inflate_state::window, internal_state::window, inflate_state::write, inflate_state::wsize, Z_MEM_ERROR, Z_NULL, Z_OK, Z_STREAM_ERROR, Z_VERSION_ERROR, ZALLOC, zcalloc(), zcfree(), and ZLIB_VERSION.
static void fixedtables () static
Referenced by cv_zlib_inflateBack().
static void fixedtables (struct inflate_state * state) static
Definition at line 73 of file infback.c.
References distfix, DISTS, inflate_table(), lenfix, and LENS.