simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/IncompressibleSolver/Solver/input_fform.cxx File Reference
input_fform.cxx File Reference
#include "cvFlowsolverOptions.h"
#include <fstream>
#include <stdlib.h>
#include <vector>
#include <string>
#include <string.h>
#include "Input.h"
#include "common_c.h"
Functions
void print_error_code (int ierr)
int input_fform (char inpfname[])
int input_fform_ (char inpfname[])
Variables
int SONFATH = 0
char cvsolver_iotype [80]
int myrank
Function Documentation
int input_fform (char inpfname[])
Definition at line 70 of file input_fform.cxx.
References aerfrc, conpar, cvsolver_iotype, genpar, Input::GetValue(), incomp, inpdat, intdat, matdat, MAXSURF, myrank, nomodule, outpar, print_error_code(), sclrs, sequence, solpar, timdat, and timpar.
Referenced by input_fform_(), and main().
int input_fform_ (char inpfname[])
Definition at line 64 of file input_fform.cxx.
References input_fform().
void print_error_code (int ierr)
Definition at line 778 of file input_fform.cxx.
Referenced by input_fform().
Variable Documentation
char cvsolver_iotype
Definition at line 60 of file input_fform.cxx.
Referenced by input_fform().
int myrank
Definition at line 154 of file common_c.h.
Referenced by input_fform(), and main().
int SONFATH = 0
Definition at line 59 of file input_fform.cxx.