simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Modules/ThreeDSolver/IncompressibleSolver/Solver/leslib_code_usr.c File Reference
leslib_code_usr.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "leslib_code_usr.h"
#include "les.h"
#include "cvSolverIO.h"
#include "mpi.h"
Functions
void usrNew (UsrHd usrHd, int *eqnType, double *aperm, double *atemp, double *resf, double *solinc, double *flowDiag, double *sclrDiag, double *lesP, double *lesQ, int *iBC, double *BC, int *iper, int *ilwork, int *numpe, int *nNodes, int *nenl, int *nPermDims, int *nTmpDims, int *rowp, int *colm, double *lhsK, double *lhsP, double *lhsS, int nnz_tot, double *CGsol)
Real * usrPointer (UsrHd usrHd, Integer id, Integer offset, Integer nDims)
void myflesnew_ (Integer *lesId, Integer *lmport, Integer *eqnType, Integer *nDofs, Integer *minIters, Integer *maxIters, Integer *nKvecs, Integer *prjFlag, Integer *nPrjs, Integer *presPrjFlag, Integer *nPresPrjs, Real *tol, Real *presTol, Integer *verbose, Real *stats, Integer *nPermDims, Integer *nTmpDims, char *lmhost)
void savelesrestart_ (Integer *lesId, Real *aperm, Integer *nshg, Integer *myrank, Integer *lstep, Integer *nPermDims)
void readlesrestart_ (Integer *lesId, Real *aperm, Integer *nshg, Integer *myrank, Integer *lstep, Integer *nPermDims)
void myflessolve_ (Integer *lesId, UsrHd usrHd)
int solverlicenseserver_ (char key[])
Variables
char cvsolver_iotype [80]
static int lmNum = 0
static LesHd lesArray [8]
Function Documentation
void myflesnew_ (Integer * lesId, Integer * lmport, Integer * eqnType, Integer * nDofs, Integer * minIters, Integer * maxIters, Integer * nKvecs, Integer * prjFlag, Integer * nPrjs, Integer * presPrjFlag, Integer * nPresPrjs, Real * tol, Real * presTol, Integer * verbose, Real * stats, Integer * nPermDims, Integer * nTmpDims, char * lmhost)
Definition at line 234 of file leslib_code_usr.c.
References lesArray, and lmNum.
void myflessolve_ (Integer * lesId, UsrHd usrHd)
Definition at line 453 of file leslib_code_usr.c.
References lesArray.
void readlesrestart_ (Integer * lesId, Real * aperm, Integer * nshg, Integer * myrank, Integer * lstep, Integer * nPermDims)
Definition at line 362 of file leslib_code_usr.c.
References closefile_(), cvsolver_iotype, filename, free(), lesArray, malloc(), nPresPrjs, nPrjs, nshg, openfile_(), readdatablock_(), and readheader_().
void savelesrestart_ (Integer * lesId, Real * aperm, Integer * nshg, Integer * myrank, Integer * lstep, Integer * nPermDims)
Definition at line 285 of file leslib_code_usr.c.
References closefile_(), cvsolver_iotype, filename, free(), lesArray, malloc(), nPresPrjs, nPrjs, nshg, openfile_(), writedatablock_(), and writeheader_().
int solverlicenseserver_ (char key[])
Definition at line 459 of file leslib_code_usr.c.
void usrNew (UsrHd usrHd, int * eqnType, double * aperm, double * atemp, double * resf, double * solinc, double * flowDiag, double * sclrDiag, double * lesP, double * lesQ, int * iBC, double * BC, int * iper, int * ilwork, int * numpe, int * nNodes, int * nenl, int * nPermDims, int * nTmpDims, int * rowp, int * colm, double * lhsK, double * lhsP, double * lhsS, int nnz_tot, double * CGsol)
Definition at line 70 of file leslib_code_usr.c.
References _Usr::aperm, _Usr::atemp, _Usr::BC, _Usr::CGsol, _Usr::colm, _Usr::eqnType, _Usr::flowDiag, _Usr::iBC, _Usr::ilwork, _Usr::iper, _Usr::lesP, _Usr::lesQ, _Usr::lhsK, _Usr::lhsP, _Usr::lhsS, _Usr::nenl, nenl, _Usr::nNodes, nnz_tot, _Usr::nnz_tot, _Usr::nPermDims, _Usr::nTmpDims, numpe, _Usr::numpe, _Usr::resf, _Usr::rowp, _Usr::sclrDiag, and _Usr::solinc.
Real* usrPointer (UsrHd usrHd, Integer id, Integer offset, Integer nDims)
Definition at line 138 of file leslib_code_usr.c.
References _Usr::aperm, _Usr::atemp, _Usr::nNodes, _Usr::nPermDims, _Usr::resf, and _Usr::solinc.
Referenced by lesAdd(), lesApFull(), lesApG(), lesApKG(), lesApNGt(), lesApNGtC(), lesApSclr(), lesBlkDaxpy(), lesBlkDmaxpy(), lesBlkDot2(), lesBlkDyeax(), lesCp(), lesDaxpy(), lesDiagScaleCp(), lesDot1(), lesDot2(), lesDxpay(), lesInv(), lesPrecPPE(), lesScale(), lesScaleCp(), lesSub(), lesVdimCp(), lesVdimDaxpy(), lesVdimDot2(), and lesZero().
Variable Documentation
char cvsolver_iotype[80]
Definition at line 60 of file input_fform.cxx.
Referenced by readlesrestart_(), and savelesrestart_().
LesHd lesArray[8] static
Definition at line 68 of file leslib_code_usr.c.
Referenced by myflesnew_(), myflessolve_(), readlesrestart_(), and savelesrestart_().
int lmNum = 0 static
Definition at line 67 of file leslib_code_usr.c.
Referenced by myflesnew_().