simvascular: cvITKLSUtil Namespace Reference
cvITKLSUtil Namespace Reference
Typedefs
typedef itk::Image< short, 2 > ITKShort2DImageType
typedef itk::Image< float, 2 > ITKFloat2DImageType
typedef itk::Image< float, 2 > ITKDefaultImageType
typedef itk::Image< short, 3 > ITKShort3DImageType
typedef itk::Image< float, 3 > ITKFloat3DImageType
typedef itk::Image< float, 3 > ITKDefault3DImageType
Functions
void vtkChangeImageInformation (vtkStructuredPoints *vtkImage, ImgInfo *refInfo)
void vtkPolyDataTo2DImage (vtkPolyData *pd, vtkStructuredPoints *vtkImg, ImgInfo *extInfo)
void vtkPolyDataToVolume (vtkPolyData *pd, vtkStructuredPoints *vtkImg, ImgInfo *extInfo)
void vtkGenerateCircle (double radius, double center[3], int numPoints, vtkPolyData *circle)
void WriteImage (vtkStructuredPoints *image, string FilenameBase)
void vtkWriteImage2 (vtkStructuredPoints *image, string FilenameBase)
void WritePerciseVtkImage (vtkStructuredPoints *image, string FilenameBase)
template<typename TImageType , typename TExternalImageType >
int vtkGenerateFeatureImage (vtkStructuredPoints *vtkInputImage, vtkStructuredPoints *vtkOuputImage, ImgInfo *refInfo, double sigma)
template<typename TImageType , typename TExternalImageType >
void vtk2itkRecastAndRescale (vtkStructuredPoints *vtkImage, typename TImageType::Pointer itkImage, ImgInfo *refInfo)
template<typename TImageType >
void itk2vtkRecast (TImageType *itkImage, vtkStructuredPoints *vtkImage, ImgInfo *refInfo)
template<typename TImageType >
void itk2vtkRecastAndRescale (TImageType *itkImage, vtkStructuredPoints *vtkImage, ImgInfo *refInfo)
template<typename TImageType >
void itkGenerateFeatureImage (TImageType *itkInputImage, typename TImageType::Pointer featureImage, double sigma)
template<typename TImageType , typename TExternalImageType >
void vtk2itkBinaryImageToSeedImage (vtkStructuredPoints *vtkImg, typename TImageType::Pointer itkImage, ImgInfo *intInfo)
template<typename TImageType >
void itkDeepCopy (const TImageType *input, typename TImageType::Pointer output)
template<typename TImageType >
void itkDeepCopy (typename TImageType::Pointer input, typename TImageType::Pointer output)
template<typename TImageType >
void itkDeepCopy (const TImageType *input, TImageType *output)
template<typename TImageType >
void CopyVTKtoITK (vtkStructuredPoints *in, TImageType *out)
template<typename TImageType >
void CopyITKtoVTK (const TImageType *in, vtkStructuredPoints *out)
template<typename TImageType >
void WriteImage (const TImageType *input, string FilenameBase)
template<typename TImageType >
void WriteImage2 (const TImageType *input, string FilenameBase)
template<typename TImageType >
void WritePNGImage (const TImageType *input, string FilenameBase)
template<typename ITKImageType >
void CreateImage (typename ITKImageType::Pointer image, typename ITKImageType::SizeType size, typename ITKImageType::SpacingType spacing, typename ITKImageType::PointType origin, typename ITKImageType::PixelType value)
void vtkPolyDataTo2DImage (vtkPolyData *pd, cvStrPts **result, ImgInfo *refInfo)
void vtkPolyDataToVolume (vtkPolyData *pd, cvStrPts **result, ImgInfo *refInfo)
void vtkGenerateCircle (double radius, double center[3], int numPoints, cvPolyData **circle)
template<typename TImageType >
void itkGenerateEdgeProxImage (TImageType *itkInputImage, typename TImageType::Pointer outputImage, double sigma, double kappa, double exponent)
template<typename TImageType , typename TExternalImageType >
void itk2vtkRecastAndRescale (TImageType *itkImage, vtkStructuredPoints *vtkImage, ImgInfo *refInfo)
template<typename TImageType , typename TExternalImageType >
int vtkGenerateEdgeProxImage (vtkStructuredPoints *vtkInputImage, vtkStructuredPoints *vtkOuputImage, ImgInfo *refInfo, double sigma, double kappa, double exponent)
template<typename TImage >
void itkDeepCopy (typename TImage::Pointer input, typename TImage::Pointer output)
template<typename TImage >
void WriteImage (const TImage *input, string FilenameBase)
template<typename TImage >
void WriteImage2 (const TImage *input, string FilenameBase)
template<typename TImage >
static void WritePNGImage (const TImage *input, string FilenameBase)
Variables
ImgInfo DefaultImgInfo
bool Debug = false
Typedef Documentation
typedef itk::Image<float,3> cvITKLSUtil::ITKDefault3DImageType
Definition at line 55 of file cvITKUtils.h.
typedef itk::Image<float,2> cvITKLSUtil::ITKDefaultImageType
Definition at line 52 of file cvITKUtils.h.
typedef itk::Image<float,2> cvITKLSUtil::ITKFloat2DImageType
Definition at line 51 of file cvITKUtils.h.
typedef itk::Image<float,3> cvITKLSUtil::ITKFloat3DImageType
Definition at line 54 of file cvITKUtils.h.
typedef itk::Image<short,2> cvITKLSUtil::ITKShort2DImageType
Definition at line 50 of file cvITKUtils.h.
typedef itk::Image<short,3> cvITKLSUtil::ITKShort3DImageType
Definition at line 53 of file cvITKUtils.h.
Function Documentation
template<typename TImageType > void cvITKLSUtil::CopyITKtoVTK (const TImageType * in, vtkStructuredPoints * out)
Definition at line 400 of file cvITKUtils.hxx.
References MyUtGenerateITKTemplate2VTKBridge.
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputeGACLevelSet(), cvITKLevelSet::ComputeGACLevelSet(), and cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputeLaplacianLevelSet().
template<typename TImageType > void cvITKLSUtil::CopyVTKtoITK (vtkStructuredPoints * in, TImageType * out)
template<typename ITKImageType > void cvITKLSUtil::CreateImage (typename ITKImageType::Pointer image, typename ITKImageType::SizeType size, typename ITKImageType::SpacingType spacing, typename ITKImageType::PointType origin, typename ITKImageType::PixelType value)
Definition at line 293 of file cvITKUtils.hxx.
template<typename TImageType > void cvITKLSUtil::itk2vtkRecast (TImageType * itkImage, vtkStructuredPoints * vtkImage, ImgInfo * refInfo)
Definition at line 377 of file cvITKUtils.hxx.
References ImgInfo::GetOrigin(), and ImgInfo::GetSpacing().
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputePhaseTwoLevelSet(), and cvITKLevelSet::ComputePhaseTwoLevelSet().
template<typename TImageType > void cvITKLSUtil::itk2vtkRecastAndRescale (TImageType * itkImage, vtkStructuredPoints * vtkImage, ImgInfo * refInfo)
Definition at line 174 of file cvITKUtils.hxx.
References cvITKTemplateNewMacro, ImgInfo::GetMaxValue(), ImgInfo::GetMinValue(), ImgInfo::GetOrigin(), ImgInfo::GetSpacing(), and MyUtGenerateITKTemplate2VTKBridge.
template<typename TImageType , typename TExternalImageType > void cvITKLSUtil::itk2vtkRecastAndRescale (TImageType * itkImage, vtkStructuredPoints * vtkImage, ImgInfo * refInfo)
Definition at line 174 of file cvITKUtils.hxx.
References cvITKTemplateNewMacro, ImgInfo::GetMaxValue(), ImgInfo::GetMinValue(), ImgInfo::GetOrigin(), ImgInfo::GetSpacing(), and MyUtGenerateITKTemplate2VTKBridge.
template<typename TImageType > void cvITKLSUtil::itkDeepCopy (const TImageType * input, typename TImageType::Pointer output)
Definition at line 334 of file cvITKUtils.hxx.
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputeGACLevelSet(), cvITKLevelSet::ComputeGACLevelSet(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputeLaplacianLevelSet(), vtk2itkBinaryImageToSeedImage(), and vtk2itkRecastAndRescale().
template<typename TImageType > void cvITKLSUtil::itkDeepCopy (typename TImageType::Pointer input, typename TImageType::Pointer output)
template<typename TImageType > void cvITKLSUtil::itkDeepCopy (const TImageType * input, TImageType * output)
Definition at line 356 of file cvITKUtils.hxx.
template<typename TImage > void cvITKLSUtil::itkDeepCopy (typename TImage::Pointer input, typename TImage::Pointer output)
Definition at line 313 of file cvITKUtils.hxx.
template<typename TImageType > void cvITKLSUtil::itkGenerateEdgeProxImage (TImageType * itkInputImage, typename TImageType::Pointer outputImage, double sigma, double kappa, double exponent)
Definition at line 22 of file cvITKUtils.hxx.
References cvITKTemplateNewMacro.
template<typename TImageType > void cvITKLSUtil::itkGenerateFeatureImage (TImageType * itkInputImage, typename TImageType::Pointer featureImage, double sigma)
Definition at line 83 of file cvITKUtils.hxx.
References cvITKTemplateNewMacro.
template<typename TImageType , typename TExternalImageType > void cvITKLSUtil::vtk2itkBinaryImageToSeedImage (vtkStructuredPoints * vtkImg, typename TImageType::Pointer itkImage, ImgInfo * intInfo)
Definition at line 241 of file cvITKUtils.hxx.
References cvITKTemplateNewMacro, Debug, ImgInfo::GetOrigin(), ImgInfo::GetSpacing(), itkDeepCopy(), and MyUtGenerateVTK2ITKTemplateBridge.
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::CopyFrontToSeed(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::GenerateSeedImage(), and cvITKLevelSet::GenerateSeedImage().
template<typename TImageType , typename TExternalImageType > void cvITKLSUtil::vtk2itkRecastAndRescale (vtkStructuredPoints * vtkImage, typename TImageType::Pointer itkImage, ImgInfo * refInfo)
Definition at line 130 of file cvITKUtils.hxx.
References cvITKTemplateNewMacro, Debug, ImgInfo::GetMaxValue(), ImgInfo::GetMinValue(), ImgInfo::GetOrigin(), ImgInfo::GetSpacing(), itkDeepCopy(), and MyUtGenerateVTK2ITKTemplateBridge.
void cvITKLSUtil::vtkChangeImageInformation (vtkStructuredPoints * vtkImage, ImgInfo * refInfo)
vtk/itk input process ** vtkImage -> ChangeInfo -> RecastRescale -> itk vtk/itk output process ** itk -> RecastRescale -> ChangeInfo -> vtk
Definition at line 26 of file cvITKUtils.cxx.
References Debug, ImgInfo::GetOrigin(), and ImgInfo::GetSpacing().
void cvITKLSUtil::vtkGenerateCircle (double radius, double center[3], int numPoints, cvPolyData ** circle) inline
Definition at line 161 of file cvITKUtils.h.
References vtkGenerateCircle().
void cvITKLSUtil::vtkGenerateCircle (double radius, double center[3], int numPoints, vtkPolyData * circle)
Definition at line 182 of file cvITKUtils.cxx.
Referenced by itkutils_GenerateCircleCmd(), and vtkGenerateCircle().
template<typename TImageType , typename TExternalImageType > int cvITKLSUtil::vtkGenerateEdgeProxImage (vtkStructuredPoints * vtkInputImage, vtkStructuredPoints * vtkOuputImage, ImgInfo * refInfo, double sigma, double kappa, double exponent)
Definition at line 222 of file cvITKUtils.hxx.
template<typename TImageType , typename TExternalImageType > int cvITKLSUtil::vtkGenerateFeatureImage (vtkStructuredPoints * vtkInputImage, vtkStructuredPoints * vtkOuputImage, ImgInfo * refInfo, double sigma)
Definition at line 203 of file cvITKUtils.hxx.
Referenced by itkutils_GradientMagnitudeGaussianCmd().
void cvITKLSUtil::vtkPolyDataTo2DImage (vtkPolyData * pd, vtkStructuredPoints * vtkImg, ImgInfo * extInfo)
Definition at line 65 of file cvITKUtils.cxx.
References Debug, ImgInfo::GetExtent(), ImgInfo::GetOrigin(), and ImgInfo::GetSpacing().
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::GenerateSeedImage(), cvITKLevelSet::GenerateSeedImage(), itkutils_PdToImgCmd(), and vtkPolyDataTo2DImage().
void cvITKLSUtil::vtkPolyDataTo2DImage (vtkPolyData * pd, cvStrPts ** result, ImgInfo * refInfo) inline
Definition at line 145 of file cvITKUtils.h.
References cvStructuredPoints, and vtkPolyDataTo2DImage().
void cvITKLSUtil::vtkPolyDataToVolume (vtkPolyData * pd, vtkStructuredPoints * vtkImg, ImgInfo * extInfo)
Definition at line 129 of file cvITKUtils.cxx.
References Debug, ImgInfo::GetExtent(), ImgInfo::GetOrigin(), and ImgInfo::GetSpacing().
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::GenerateSeedImage(), itkutils_PdToVolCmd(), and vtkPolyDataToVolume().
void cvITKLSUtil::vtkPolyDataToVolume (vtkPolyData * pd, cvStrPts ** result, ImgInfo * refInfo) inline
Definition at line 153 of file cvITKUtils.h.
References cvStructuredPoints, and vtkPolyDataToVolume().
void cvITKLSUtil::vtkWriteImage2 (vtkStructuredPoints * image, string FilenameBase)
Definition at line 236 of file cvITKUtils.cxx.
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::CopyFrontToSeed(), and cvITKLevelSetBase< TInputImage, TInternalPixelType >::GenerateSeedImage().
template<typename TImageType > void cvITKLSUtil::WriteImage (const TImageType * input, string FilenameBase)
void cvITKLSUtil::WriteImage (vtkStructuredPoints * image, string FilenameBase)
Definition at line 224 of file cvITKUtils.cxx.
Referenced by cvITKLevelSet::WriteFrontImages(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::WriteFrontImages(), and WritePerciseVtkImage().
template<typename TImage > void cvITKLSUtil::WriteImage (const TImage * input, string FilenameBase)
Definition at line 413 of file cvITKUtils.hxx.
template<typename TImageType > void cvITKLSUtil::WriteImage2 (const TImageType * input, string FilenameBase)
Referenced by cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputeGACLevelSet(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputeLaplacianLevelSet(), cvITKLevelSetBase< TInputImage, TInternalPixelType >::ComputePhaseOneLevelSet(), and cvITKLevelSetBase< TInputImage, TInternalPixelType >::GenerateFeatureImage().
template<typename TImage > void cvITKLSUtil::WriteImage2 (const TImage * input, string FilenameBase)
Definition at line 427 of file cvITKUtils.hxx.
void cvITKLSUtil::WritePerciseVtkImage (vtkStructuredPoints * image, string FilenameBase)
Definition at line 246 of file cvITKUtils.cxx.
References WriteImage().
Referenced by itkutils_WriteImageCmd().
template<typename TImageType > void cvITKLSUtil::WritePNGImage (const TImageType * input, string FilenameBase)
template<typename TImage > static void cvITKLSUtil::WritePNGImage (const TImage * input, string FilenameBase) static
Definition at line 439 of file cvITKUtils.hxx.
Variable Documentation
bool cvITKLSUtil::Debug = false
Definition at line 24 of file cvITKUtils.cxx.
Referenced by vtk2itkBinaryImageToSeedImage(), vtk2itkRecastAndRescale(), vtkChangeImageInformation(), vtkPolyDataTo2DImage(), and vtkPolyDataToVolume().
ImgInfo cvITKLSUtil::DefaultImgInfo
Definition at line 23 of file cvITKUtils.cxx.
Referenced by itkutils_PdToImgCmd().