simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimMeshObject/scorecXYZ.cxx File Reference
scorecXYZ.cxx File Reference
#include "SimVascular.h"
#include <math.h>
Macros
#define M_PI 3.14159265358979323846
#define MTBIG 1.0e20
Typedefs
typedef double dArray [3]
Functions
double scorecXYZ_circumRad2 (dArray *xyz)
void scorecXYZ_dhdAngs (double xyz[4][3], double *cosAngs)
double scorecXYZ_inscrRad (dArray *xyz)
double scorecDet (int n, double A[3][3])
void scorecAddVt (double *a, double *b, double *v)
void scorecDiffVt (double *a, double *b, double *v)
void scorecScaleVt (double *a, double n)
double scorecDotProd (double *v1, double *v2)
void scorecCrossProd (double *v1, double *v2, double *cp)
int scorecSameSign (double x, double y)
double scorecVecMag (double *vec)
int scorecNormVt (double *v1, double *nv)
double scorecDet3Mat (double *v1, double *v2, double *v3)
void scorecNegVt (double *a)
double scorecXYZ_aspectRatio2 (dArray *xyz)
void scorecXYZ_dihedral (dArray *xyz, double *sml, double *big)
double scorecXYZ_edgLenRatio2 (dArray *xyz)
double scorecXYZ_rbyR2 (dArray *xyz)
int scorecXYZ_shape (dArray *xyz, double *shape)
Macro Definition Documentation
#define M_PI 3.14159265358979323846
Definition at line 44 of file scorecXYZ.cxx.
Referenced by cvAdaptCore::FindCubicRoots().
#define MTBIG 1.0e20
Definition at line 48 of file scorecXYZ.cxx.
Referenced by scorecXYZ_aspectRatio2().
Typedef Documentation
typedef double dArray[3]
Definition at line 41 of file scorecXYZ.cxx.
Function Documentation
void scorecAddVt (double * a, double * b, double * v)
Definition at line 65 of file scorecXYZ.cxx.
void scorecCrossProd (double * v1, double * v2, double * cp)
Definition at line 100 of file scorecXYZ.cxx.
Referenced by scorecXYZ_aspectRatio2(), scorecXYZ_inscrRad(), and scorecXYZ_shape().
double scorecDet (int n, double A[3][3])
Definition at line 55 of file scorecXYZ.cxx.
Referenced by scorecXYZ_circumRad2().
double scorecDet3Mat (double * v1, double * v2, double * v3)
Definition at line 140 of file scorecXYZ.cxx.
void scorecDiffVt (double * a, double * b, double * v)
Definition at line 74 of file scorecXYZ.cxx.
Referenced by scorecXYZ_aspectRatio2(), scorecXYZ_circumRad2(), scorecXYZ_edgLenRatio2(), scorecXYZ_inscrRad(), and scorecXYZ_shape().
double scorecDotProd (double * v1, double * v2)
Definition at line 93 of file scorecXYZ.cxx.
Referenced by scorecXYZ_aspectRatio2(), scorecXYZ_circumRad2(), scorecXYZ_edgLenRatio2(), scorecXYZ_inscrRad(), and scorecXYZ_shape().
void scorecNegVt (double * a)
Definition at line 148 of file scorecXYZ.cxx.
int scorecNormVt (double * v1, double * nv)
Definition at line 124 of file scorecXYZ.cxx.
int scorecSameSign (double x, double y)
Definition at line 109 of file scorecXYZ.cxx.
void scorecScaleVt (double * a, double n)
Definition at line 84 of file scorecXYZ.cxx.
double scorecVecMag (double * vec)
Definition at line 116 of file scorecXYZ.cxx.
double scorecXYZ_aspectRatio2 (dArray * xyz)
Definition at line 155 of file scorecXYZ.cxx.
References MTBIG, scorecCrossProd(), scorecDiffVt(), and scorecDotProd().
Referenced by M_writeSTS().
double scorecXYZ_circumRad2 (dArray * xyz)
Definition at line 336 of file scorecXYZ.cxx.
References scorecDet(), scorecDiffVt(), and scorecDotProd().
Referenced by scorecXYZ_rbyR2().
void scorecXYZ_dhdAngs (double xyz[4][3], double * cosAngs)
Definition at line 394 of file scorecXYZ.cxx.
Referenced by scorecXYZ_dihedral().
void scorecXYZ_dihedral (dArray * xyz, double * sml, double * big)
Definition at line 200 of file scorecXYZ.cxx.
References scorecXYZ_dhdAngs().
Referenced by M_writeSTS().
double scorecXYZ_edgLenRatio2 (dArray * xyz)
Definition at line 240 of file scorecXYZ.cxx.
References scorecDiffVt(), and scorecDotProd().
Referenced by M_writeSTS().
double scorecXYZ_inscrRad (dArray * xyz)
Definition at line 501 of file scorecXYZ.cxx.
References scorecCrossProd(), scorecDiffVt(), scorecDotProd(), and V.
Referenced by scorecXYZ_rbyR2().
double scorecXYZ_rbyR2 (dArray * xyz)
Definition at line 276 of file scorecXYZ.cxx.
References scorecXYZ_circumRad2(), and scorecXYZ_inscrRad().
Referenced by M_writeSTS().
int scorecXYZ_shape (dArray * xyz, double * shape)
Definition at line 288 of file scorecXYZ.cxx.
References scorecCrossProd(), scorecDiffVt(), and scorecDotProd().
Referenced by M_writeSTS().