simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/Licensed/MeshSimMeshObject/stats.cxx File Reference
stats.cxx File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "SimVascular.h"
#include "MeshSim.h"
Macros
#define MY_MESHSIM_VERTEX_ORDERING 1
#define M_PI 3.14159265358979323846
Typedefs
typedef double dArray [3]
Functions
double scorecXYZ_aspectRatio2 (dArray *xyz)
void scorecXYZ_dihedral (dArray *xyz, double *sml, double *big)
double scorecXYZ_edgLenRatio2 (dArray *xyz)
double scorecXYZ_rbyR2 (dArray *xyz)
int scorecXYZ_shape (dArray *xyz, double *shape)
int M_writeSTS (pMesh mesh, char *fname, char *mname)
Variables
const double dhd145 = -0.819152044
const double dhd160 = -0.93969262
const double dhd170 = -0.984807753
Macro Definition Documentation
#define M_PI 3.14159265358979323846
Definition at line 57 of file stats.cxx.
Referenced by M_writeSTS().
#define MY_MESHSIM_VERTEX_ORDERING 1
Definition at line 45 of file stats.cxx.
Referenced by M_writeSTS().
Typedef Documentation
typedef double dArray[3]
Definition at line 51 of file stats.cxx.
Function Documentation
int M_writeSTS (pMesh mesh, char * fname, char * mname)
Definition at line 66 of file stats.cxx.
References CV_ERROR, CV_OK, dhd145, dhd160, dhd170, M_PI, MY_MESHSIM_VERTEX_ORDERING, scorecXYZ_aspectRatio2(), scorecXYZ_dihedral(), scorecXYZ_edgLenRatio2(), scorecXYZ_rbyR2(), and scorecXYZ_shape().
Referenced by cvMeshSimMeshObject::WriteStats().
double scorecXYZ_aspectRatio2 (dArray * xyz)
Definition at line 155 of file scorecXYZ.cxx.
References MTBIG, scorecCrossProd(), scorecDiffVt(), and scorecDotProd().
Referenced by M_writeSTS().
void scorecXYZ_dihedral (dArray * xyz, double * sml, double * big)
Definition at line 200 of file scorecXYZ.cxx.
References scorecXYZ_dhdAngs().
Referenced by M_writeSTS().
double scorecXYZ_edgLenRatio2 (dArray * xyz)
Definition at line 240 of file scorecXYZ.cxx.
References scorecDiffVt(), and scorecDotProd().
Referenced by M_writeSTS().
double scorecXYZ_rbyR2 (dArray * xyz)
Definition at line 276 of file scorecXYZ.cxx.
References scorecXYZ_circumRad2(), and scorecXYZ_inscrRad().
Referenced by M_writeSTS().
int scorecXYZ_shape (dArray * xyz, double * shape)
Definition at line 288 of file scorecXYZ.cxx.
References scorecCrossProd(), scorecDiffVt(), and scorecDotProd().
Referenced by M_writeSTS().
Variable Documentation
const double dhd145 = -0.819152044
Definition at line 47 of file stats.cxx.
Referenced by M_writeSTS().
const double dhd160 = -0.93969262
Definition at line 48 of file stats.cxx.
Referenced by M_writeSTS().
const double dhd170 = -0.984807753
Definition at line 49 of file stats.cxx.
Referenced by M_writeSTS().