simvascular: /Users/danschi/Documents/01_development/07_SV/simvascular_reorg/Code/ThirdParty/zlib/simvascular_zlib/zutil.c File Reference
zutil.c File Reference
#include "zutil.h"
Classes
struct internal_state
Functions
char * cv_zlib_zlibVersion ()
uLong cv_zlib_zlibCompileFlags ()
char * cv_zlib_zError (int err)
void zmemcpy (Bytef *dest, Bytef *source, uInt len)
int zmemcmp (Bytef *s1, Bytef *s2, uInt len)
void zmemzero (Bytef *dest, uInt len)
voidp malloc ()
voidp calloc ()
void free ()
voidpf zcalloc (voidpf opaque, unsigned items, unsigned size)
void zcfree (voidpf opaque, voidpf ptr)
Variables
char * z_errmsg [10]
Function Documentation
voidp calloc ()
Referenced by main(), and zcalloc().
char* cv_zlib_zError (int err)
Definition at line 133 of file zutil.c.
References ERR_MSG.
uLong cv_zlib_zlibCompileFlags ()
Definition at line 32 of file zutil.c.
References L, and z_off_t.
char* cv_zlib_zlibVersion ()
Definition at line 27 of file zutil.c.
References ZLIB_VERSION.
void free ()
Referenced by zcfree().
voidp malloc ()
Referenced by zcalloc().
voidpf zcalloc (voidpf opaque, unsigned items, unsigned size)
Definition at line 300 of file zutil.c.
References calloc(), and malloc().
Referenced by cv_zlib_deflateInit2_(), cv_zlib_inflateBackInit_(), and cv_zlib_inflateInit2_().
void zcfree (voidpf opaque, voidpf ptr)
Definition at line 310 of file zutil.c.
References free().
Referenced by cv_zlib_deflateInit2_(), cv_zlib_inflateBackInit_(), and cv_zlib_inflateInit2_().
int zmemcmp (Bytef* s1, Bytef* s2, uInt len)
Definition at line 160 of file zutil.c.
void zmemcpy (Bytef* dest, Bytef* source, uInt len)
Definition at line 149 of file zutil.c.
Referenced by cv_zlib_deflateCopy(), cv_zlib_deflateSetDictionary(), cv_zlib_gzread(), cv_zlib_inflate(), cv_zlib_inflateBack(), cv_zlib_inflateCopy(), cv_zlib_inflateSetDictionary(), fill_window(), flush_pending(), read_buf(), and updatewindow().
void zmemzero (Bytef* dest, uInt len)
Definition at line 173 of file zutil.c.
Referenced by cv_zlib_gzseek().
Variable Documentation
char* z_errmsg[10]
Initial value:
= {
"need dictionary",
"stream end",
"",
"file error",
"stream error",
"data error",
"insufficient memory",
"buffer error",
"incompatible version",
""}
Definition at line 14 of file zutil.c.